/**
 * NCLEX dosage-calculation key verification — COMPUTATIONAL PATH #2.
 *
 * The offline Dosage Mastery items were generated by a Python script that
 * computed every answer key (path #1). This test recomputes each answer
 * from the raw parameters in the item's `calc` block using formulas written
 * here, independently, in TypeScript — and the two paths must agree exactly.
 * The same dual-path rule AXIOM applies to its math templates ("every
 * generated answer key gets an independent verifier through a second
 * computational path"), where it has caught real authoring bugs (the DM13
 * Laplacian diagonal, an aware-datetime crash) before they served.
 *
 * What is asserted, per item:
 *   1. the recomputed value equals `calc.expected` at the item's rounding,
 *   2. the keyed option's leading number parses to that same value,
 *   3. no distractor parses to the keyed value (no duplicate-correct), and
 *   4. the item is labeled `calc-verified` and its id is unique.
 *
 * If you edit any dosage item's numbers by hand, this test is what catches
 * the slip. Regenerate instead.
 */
import { describe, expect, it } from 'vitest';

import type { NclexQuestion } from '../nclex-types';
import { NCLEX_DOSAGE_BANK2 } from '../nclex-dosage-bank2-data';

/** Independent recomputation — formulas written fresh, not imported. */
function recompute(q: NclexQuestion): number {
  const c = q.calc!;
  const p = c.params;
  switch (c.kind) {
    case 'tablets':
      return p.ordered_mg / p.strength_mg;
    case 'liquid-volume':
      return (p.ordered_mg / p.conc_mg) * p.conc_ml;
    case 'dose-by-weight': {
      const kg = p.weight_is_lb ? p.weight / 2.2 : p.weight;
      return p.mg_per_kg * kg;
    }
    case 'iv-rate-mlhr':
      return p.volume_ml / p.hours;
    case 'iv-drip-gtt':
      return (p.volume_ml * p.drop_factor) / p.minutes;
    case 'unit-conversion':
      return p.value * p.factor;
    case 'reconstitution':
      return (p.ordered_mg / p.conc_mg) * p.conc_ml;
    case 'pediatric-safe-dose':
      return (p.mg_per_kg_day * p.weight_kg) / p.doses_per_day;
    case 'infusion-time':
      return p.volume_ml / p.rate_mlhr;
    case 'iv-dose-mlhr': {
      if ('units_per_kg_hr' in p) {
        // units/kg/hr → units/hr → mL/hr through the bag concentration
        const unitsPerHr = p.units_per_kg_hr * p.weight_kg;
        return unitsPerHr / (p.bag_units / p.bag_ml);
      }
      // mcg/kg/min → mg/hr → mL/hr through the bag concentration
      const mcgPerMin = p.mcg_per_kg_min * p.weight_kg;
      const mgPerHr = (mcgPerMin * 60) / 1000;
      return mgPerHr / (p.bag_mg / p.bag_ml);
    }
    default:
      throw new Error(`no independent formula for calc kind: ${(c as { kind: string }).kind}`);
  }
}

function roundTo(v: number, nd: number): number {
  // Half-UP with float noise quantized away first — the same rule as the
  // server engine's _r(). The dual-path gate caught why this matters:
  // nitroprusside 1 mcg/kg/min at 85 kg is exactly 25.5 mL/hr, and raw
  // float arithmetic lands one path at 25.499999999999996 and the other at
  // 25.500000000000004. Pre-rounding to 9 decimals collapses both onto the
  // true 25.5 before the half-up decision (nursing convention: .5 rounds up).
  const q = Math.round(v * 1e9) / 1e9;
  const f = 10 ** nd;
  return Math.floor(Math.round(q * f * 1e6) / 1e6 + 0.5) / f;
}

/** Leading numeric value of an option string like "3.3 mL" or "150 gtt/min". */
function optionValue(opt: string): number {
  const m = opt.replace(/,/g, '').match(/-?\d+(\.\d+)?/);
  expect(m, `option "${opt}" has no leading number`).not.toBeNull();
  return parseFloat(m![0]);
}

// Part 1 (the 41 dosage items that shipped in nclex-qbank-data.ts) moved to
// the server item bank in NX-5 and its client file was deleted; its dual-path
// verification moved with it — services/api-core/scripts/verify_nclex_bank_keys.py
// recomputes every calc-verified key from metadata.calc against the LIVE bank.
// This test keeps the same rule for what stays client-side: the offline
// Dosage Mastery bank (200 items emitted by emit_nclex_static_bank.py).
const BANKS: [string, NclexQuestion[], number][] = [
  ['bank2', NCLEX_DOSAGE_BANK2, 200],
];

describe.each(BANKS)('NCLEX dosage %s — dual-path key verification', (name, bank, minCount) => {
  it('has the expected bank size', () => {
    expect(bank.length).toBeGreaterThanOrEqual(minCount);
  });

  it('every dosage item carries a calc block and the calc-verified label', () => {
    for (const q of bank) {
      expect(q.calc, q.id).toBeDefined();
      expect(q.verification, q.id).toBe('calc-verified');
      expect(typeof q.correct, q.id).toBe('number');
    }
  });

  it('ids are unique across the bank', () => {
    const ids = bank.map((q) => q.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  for (const q of bank) {
    it(`${q.id} [${q.calc?.kind}] key recomputes independently`, () => {
      const c = q.calc!;
      const independent = roundTo(recompute(q), c.round);

      // 1. Path #2 agrees with path #1.
      expect(independent).toBeCloseTo(c.expected, Math.max(c.round, 6));

      // 2. The keyed option states exactly that value.
      const keyed = optionValue(q.options[q.correct!]);
      expect(keyed).toBeCloseTo(independent, Math.max(c.round, 6));

      // 3. No distractor collides with the key.
      q.options.forEach((opt, i) => {
        if (i === q.correct) return;
        expect(
          Math.abs(optionValue(opt) - independent),
          `${q.id}: distractor "${opt}" equals the key`,
        ).toBeGreaterThan(10 ** -(c.round + 1) / 2);
      });
    });
  }
});

describe('bank2 offline coaching payload', () => {
  it('aligns misconceptionByOption to the options and never marks the key', () => {
    for (const q of NCLEX_DOSAGE_BANK2) {
      expect(q.misconceptionByOption.length, q.id).toBe(q.options.length);
      expect(q.misconceptionByOption[q.correct!], q.id).toBeNull();
      for (const key of q.misconceptionByOption) {
        if (key !== null) {
          expect(q.coaching[key], `${q.id}: coaching missing for ${key}`).toBeTruthy();
        }
      }
    }
  });
});
