apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eureka

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - api-core-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: eureka
  app.kubernetes.io/managed-by: kustomize

images:
  - name: eureka/api-core
    newTag: latest
