"""Full course: C101 — The limit concept.

Gold-standard FC-template lesson: 20 full pages. Every full-course module in
this package should match this depth and structure.
"""

L = "reading"
E = "example"
P = "pitfall"
K = "check"

LESSONS: dict[str, dict] = {
    "C101": {
        "summary": (
            "A complete course on the limit concept: intuition, one-sided limits, "
            "numerical and graphical evaluation, the precise definition, when limits "
            "fail, and why limits are the foundation of all of calculus."
        ),
        "steps": [
            # ---------------------------------------------------------- 1
            (L, "Where you are and why this matters", (
                "Welcome to the first real idea of calculus. Everything in this subject — "
                "derivatives, integrals, series, differential equations — is built on ONE "
                "concept: the LIMIT. The derivative is a limit of slopes. The integral is a "
                "limit of sums. An infinite series is a limit of partial sums. Master limits "
                "and the rest of calculus becomes variations on a theme; skim them and every "
                "later chapter feels like magic tricks without explanations.\n\n"
                "Why does calculus need a new idea at all? Algebra answers STATIC questions: "
                "what is $f(3)$? Where do two lines cross? But the questions that drove the "
                "invention of calculus are about MOTION and APPROACH: how fast is this "
                "falling object moving RIGHT NOW (not on average over a second — right now, "
                "at this instant)? What does this curve look like as we zoom in forever? "
                "What value does this process home in on as we repeat it endlessly?\n\n"
                "Each of those questions asks about behavior AT the edge of what we can "
                "compute directly. Instantaneous speed is distance over time with time "
                "$= 0$ — and $\\frac{0}{0}$ is undefined. The limit is the tool that makes "
                "'what happens as we get arbitrarily close' a precise, computable question "
                "instead of a paradox.\n\n"
                "In this course-chapter you will learn: what a limit MEANS (three ways: "
                "intuitively, numerically, graphically), how one-sided limits sharpen the "
                "idea, the precise definition that took mathematicians 150 years to find, "
                "every standard way limits fail to exist, and how to read limit behavior "
                "off tables, graphs, and formulas. The next chapter (C102) covers the "
                "ALGEBRA of computing limits; this one builds the concept those "
                "computations rest on."
            )),
            # ---------------------------------------------------------- 2
            (L, "Prerequisites check", (
                "You need three things from precalculus, all reviewable in an evening if "
                "rusty.\n\n"
                "1. FUNCTION FLUENCY. A function $f$ assigns one output to each input; "
                "$f(a)$ is the output at $a$. You should be comfortable evaluating things "
                "like $f(x) = \\frac{x^2 - 9}{x - 3}$ at specific points, and noticing "
                "where a formula is UNDEFINED (here: $x = 3$, division by zero). Domain "
                "awareness is essential, because limits live exactly at the edges of "
                "domains.\n\n"
                "2. GRAPH READING. Given a graph, you should be able to trace: as inputs "
                "move along the $x$-axis toward a target, what are the outputs doing? "
                "You'll need to read heights, spot holes (open circles), jumps, and "
                "vertical asymptotes.\n\n"
                "3. THE STANDARD FUNCTION ZOO. Know the shapes of $x^2$, $x^3$, "
                "$\\frac{1}{x}$, $\\sqrt{x}$, $|x|$, $\\sin x$, $\\cos x$, $e^x$, "
                "$\\ln x$. Limits questions constantly say 'consider $f(x) = \\ldots$' "
                "and expect you to see the shape in your head.\n\n"
                "Quick self-check before proceeding (answers at the end of the line):\n\n"
                "• What is $f(2)$ for $f(x) = \\frac{x^2 - 4}{x - 2}$? "
                "(UNDEFINED — the formula gives $\\frac{0}{0}$.)\n"
                "• For $x$ slightly less than 0, is $\\frac{1}{x}$ large positive or "
                "large negative? (Large negative: $\\frac{1}{-0.001} = -1000$.)\n"
                "• What does the graph of $|x|$ look like at the origin? (A corner — "
                "a V shape.)\n\n"
                "If any of these felt shaky, spend twenty minutes with the PRECALC "
                "review nodes before continuing — the payoff is immediate."
            )),
            # ---------------------------------------------------------- 3
            (L, "The core idea, intuitively", (
                "Here is the limit idea in one sentence: $\\lim_{x \\to a} f(x) = L$ "
                "means that $f(x)$ gets AS CLOSE AS YOU LIKE to $L$ whenever $x$ is "
                "close enough to $a$ — without ever asking what happens AT $a$ "
                "itself.\n\n"
                "The crucial, endlessly-tested subtlety is that last clause. The limit "
                "is about the APPROACH, not the ARRIVAL. Think of walking toward a "
                "door: the limit records where you are headed, whether or not the door "
                "is open when you get there, and even whether there is a door at all.\n\n"
                "Three scenarios make the distinction vivid. Let "
                "$g(x) = \\frac{x^2 - 9}{x - 3}$.\n\n"
                "• At every $x \\ne 3$, we can factor: "
                "$g(x) = \\frac{(x-3)(x+3)}{x - 3} = x + 3$. So the graph of $g$ is "
                "the straight line $y = x + 3$ WITH A HOLE at $x = 3$ (where the "
                "formula breaks). As $x$ approaches 3 from either side, the outputs "
                "approach $6$. We write $\\lim_{x \\to 3} g(x) = 6$, even though "
                "$g(3)$ does not exist. The limit sees the trend; it does not care "
                "about the hole.\n\n"
                "• Now IMAGINE we patch the function: define $h(x) = g(x)$ for "
                "$x \\ne 3$ and $h(3) = 100$. The graph is the same line, the same "
                "hole — plus one lonely dot floating at height 100. The limit is "
                "STILL 6. One repaired or misplaced dot cannot change where the "
                "function is heading.\n\n"
                "• Finally define $k(x) = x + 3$ everywhere. Now $k(3) = 6$ AND "
                "$\\lim_{x \\to 3} k(x) = 6$. When the value and the limit agree, the "
                "function is called CONTINUOUS at that point — the star of chapter "
                "C103.\n\n"
                "Same limit in all three cases, three different behaviors at the "
                "point. That independence — limit versus value — is the single most "
                "important idea on this page, and the most common source of lost exam "
                "points in week one of calculus."
            )),
            # ---------------------------------------------------------- 4
            (L, "Numerical and graphical limits, carefully", (
                "Before formulas, learn to FIND limits two concrete ways.\n\n"
                "NUMERICALLY: build a table of inputs marching toward $a$ from both "
                "sides and watch the outputs. For $\\lim_{x \\to 0} \\frac{\\sin x}{x}$ "
                "(x in radians):\n\n"
                "$x = 0.1$: $0.99833$;  $x = 0.01$: $0.99998$;  $x = 0.001$: "
                "$0.9999998$; and from the left, $x = -0.01$ gives $0.99998$ as well "
                "(the function is even). The outputs crowd toward $1$ from both "
                "sides, so the evidence says $\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1$ "
                "— one of the two most famous limits in calculus, and unprovable by "
                "plugging in ($\\frac{0}{0}$).\n\n"
                "A table is EVIDENCE, not proof — a function can fake a trend and "
                "swerve at scales smaller than your table (page 10 shows one that "
                "oscillates forever). But tables build correct intuition and catch "
                "wrong guesses fast.\n\n"
                "GRAPHICALLY: to read $\\lim_{x \\to a} f(x)$ from a graph, cover the "
                "point at $x = a$ with your thumb. Trace the curve toward your thumb "
                "from the left: what height is it heading to? Trace from the right: "
                "same height? If both approaches head to the same height $L$, the "
                "limit is $L$ — regardless of what is under your thumb (a point on "
                "the curve, a hole, a dot somewhere else).\n\n"
                "The thumb trick enforces the definition mechanically: the limit "
                "never looks at $x = a$. When you check work, actually do it — "
                "cover the point. Students who read limits with the point visible "
                "reliably report the VALUE instead of the LIMIT on trick questions, "
                "and every exam has one."
            )),
            # ---------------------------------------------------------- 5
            (E, "First worked examples", (
                "EXAMPLE 1 (a polynomial — the boring case done right). Find "
                "$\\lim_{x \\to 2} (x^2 + 3x)$.\n\n"
                "As $x$ gets close to 2, $x^2$ gets close to 4 and $3x$ gets close "
                "to 6, so the sum approaches $10$. Here the function is continuous, "
                "so the limit equals the value: $\\lim_{x \\to 2}(x^2 + 3x) = 10$. "
                "For polynomials, approach and arrival always agree — that is WHY "
                "plugging in works for them (C102 makes this official).\n\n"
                "EXAMPLE 2 (a hole). Find $\\lim_{t \\to 5} \\frac{t^2 - 25}{t - 5}$.\n\n"
                "Plugging in gives $\\frac{0}{0}$ — undefined, but that tells us "
                "nothing about the limit. For every $t \\ne 5$:\n"
                "$$\\frac{t^2 - 25}{t - 5} = \\frac{(t-5)(t+5)}{t-5} = t + 5,$$\n"
                "and the limit only cares about $t \\ne 5$. So the limit is "
                "$5 + 5 = 10$. The graph is a line with a hole at $(5, 10)$; the "
                "function heads to height 10 from both sides.\n\n"
                "EXAMPLE 3 (limit vs value, on a graph). A graph shows a curve "
                "approaching height 3 from both sides as $x \\to 1$, an open circle "
                "at $(1, 3)$, and a filled dot at $(1, -2)$. Then:\n"
                "$$\\lim_{x \\to 1} f(x) = 3 \\qquad \\text{but} \\qquad f(1) = -2.$$\n"
                "Both statements are true simultaneously. If a problem asks for the "
                "limit, the answer is 3; if it asks for the value, $-2$; if it asks "
                "whether $f$ is continuous at 1, the answer is no, because they "
                "disagree.\n\n"
                "The three examples span the whole story: sometimes the limit equals "
                "the value (Example 1), sometimes the value is missing (Example 2), "
                "sometimes the value exists but lies (Example 3). The limit itself "
                "behaved identically in all three: it watched the approach."
            )),
            # ---------------------------------------------------------- 6
            (L, "One-sided limits", (
                "Approach can happen from two directions, and they can disagree.\n\n"
                "The LEFT-HAND limit, $\\lim_{x \\to a^-} f(x)$, watches inputs "
                "increasing toward $a$ (from below: $2.9, 2.99, 2.999, \\ldots$). "
                "The RIGHT-HAND limit, $\\lim_{x \\to a^+} f(x)$, watches inputs "
                "decreasing toward $a$ (from above: $3.1, 3.01, 3.001, \\ldots$).\n\n"
                "THE FUNDAMENTAL RELATIONSHIP:\n"
                "$$\\lim_{x \\to a} f(x) = L \\iff \\lim_{x \\to a^-} f(x) = L "
                "\\;\\text{AND}\\; \\lim_{x \\to a^+} f(x) = L.$$\n"
                "The two-sided limit exists exactly when both one-sided limits exist "
                "AND agree. If they disagree — or either fails — the two-sided limit "
                "does not exist (often written DNE).\n\n"
                "The canonical example: the step function $f(x) = \\frac{|x|}{x}$, "
                "which equals $-1$ for negative $x$ and $+1$ for positive $x$. As "
                "$x \\to 0^-$, the outputs are all $-1$, so the left limit is $-1$. "
                "As $x \\to 0^+$, all outputs are $+1$: right limit $+1$. They "
                "disagree, so $\\lim_{x \\to 0} \\frac{|x|}{x}$ does not exist. The "
                "graph shows the JUMP: two shelves at different heights.\n\n"
                "One-sided limits matter for three reasons. (1) Piecewise functions "
                "— tax brackets, shipping rates, physics with switched forces — "
                "change formula at breakpoints, and each side must be checked with "
                "its own formula. (2) Domain edges: $\\sqrt{x}$ only has a "
                "right-hand limit at 0, because there is nothing to the left. "
                "(3) They are the DIAGNOSTIC tool: whenever a two-sided limit is in "
                "doubt, split it into its two sides and check each separately. That "
                "one habit resolves most limit confusions mechanically."
            )),
            # ---------------------------------------------------------- 7
            (E, "Worked examples: one-sided limits and piecewise functions", (
                "EXAMPLE 1. Let\n"
                "$$f(x) = \\begin{cases} x^2 + 1 & x < 2 \\\\ 7 & x = 2 \\\\ "
                "6x - 7 & x > 2. \\end{cases}$$\n"
                "Find both one-sided limits at $x = 2$, the two-sided limit, and "
                "compare to $f(2)$.\n\n"
                "Left side (use the $x < 2$ formula): "
                "$\\lim_{x \\to 2^-} (x^2 + 1) = 5$.\n"
                "Right side (use the $x > 2$ formula): "
                "$\\lim_{x \\to 2^+} (6x - 7) = 5$.\n"
                "Both sides give 5, so $\\lim_{x \\to 2} f(x) = 5$. Meanwhile "
                "$f(2) = 7$ — the definition planted the point elsewhere. Limit 5, "
                "value 7, not continuous. Notice the middle line of the definition "
                "($f(2) = 7$) played NO role in either limit computation: limits "
                "never read the value at the point.\n\n"
                "EXAMPLE 2. Same idea, different outcome:\n"
                "$$g(x) = \\begin{cases} 3x - 1 & x \\le 1 \\\\ x + 4 & x > 1. "
                "\\end{cases}$$\n"
                "Left: $\\lim_{x \\to 1^-}(3x - 1) = 2$. Right: "
                "$\\lim_{x \\to 1^+}(x + 4) = 5$. The sides disagree "
                "($2 \\ne 5$): $\\lim_{x \\to 1} g(x)$ DNE. The graph jumps from "
                "height 2 up to height 5.\n\n"
                "EXAMPLE 3 (design problem — the exam favorite). For what value of "
                "the constant $c$ does $\\lim_{x \\to 3} h(x)$ exist, where "
                "$h(x) = cx + 2$ for $x < 3$ and $h(x) = x^2 - c$ for "
                "$x \\ge 3$?\n\n"
                "Force the sides to agree: left limit $= 3c + 2$, right limit "
                "$= 9 - c$. Setting $3c + 2 = 9 - c$ gives $4c = 7$, so "
                "$c = \\frac{7}{4}$. With that $c$, both sides approach "
                "$3 \\cdot \\frac74 + 2 = \\frac{29}{4}$ and the limit exists. "
                "This 'match the sides' template reappears throughout C103 as the "
                "way to build continuous piecewise functions."
            )),
            # ---------------------------------------------------------- 8
            (L, "The precise definition (epsilon-delta)", (
                "'Gets as close as you like' is intuition. Mathematics eventually "
                "demands precision, and here is the definition that Cauchy and "
                "Weierstrass distilled from 150 years of struggle:\n\n"
                "$$\\lim_{x \\to a} f(x) = L \\;\\text{ means: }\\; "
                "\\forall \\varepsilon > 0 \\;\\exists \\delta > 0 : "
                "0 < |x - a| < \\delta \\Rightarrow |f(x) - L| < \\varepsilon.$$\n\n"
                "Read it as a GAME between a skeptic and you. The skeptic hands you "
                "a tolerance $\\varepsilon$ — say, 'get $f(x)$ within $0.01$ of "
                "$L$.' You must produce a $\\delta$ — a radius around $a$ — such "
                "that EVERY $x$ within $\\delta$ of $a$ (except $a$ itself) lands "
                "$f(x)$ within $\\varepsilon$ of $L$. If you can win for EVERY "
                "$\\varepsilon$, no matter how small, the limit is $L$.\n\n"
                "Match each piece to the intuition:\n"
                "• '$\\forall \\varepsilon > 0$' = 'as close as you like' — the "
                "skeptic's tolerance can be arbitrarily tight.\n"
                "• '$\\exists \\delta > 0$' = 'close enough' — you only need SOME "
                "winning radius, and it may depend on $\\varepsilon$ (tighter "
                "tolerance, smaller radius — that's expected).\n"
                "• '$0 < |x - a|$' = 'without asking what happens at $a$' — the "
                "point itself is EXCLUDED. This little '$0 <$' is the entire "
                "limit-versus-value distinction, encoded in one symbol.\n\n"
                "A taste of it in action: prove $\\lim_{x \\to 4}(3x - 5) = 7$. "
                "Given $\\varepsilon$, we need $|3x - 5 - 7| = 3|x - 4| < "
                "\\varepsilon$, which holds whenever $|x - 4| < "
                "\\frac{\\varepsilon}{3}$. So $\\delta = \\frac{\\varepsilon}{3}$ "
                "wins the game, for every $\\varepsilon$. ∎\n\n"
                "In this course you need to UNDERSTAND this definition and use it "
                "on linear examples; wielding it on harder functions is the craft "
                "taught in PT.EPSILONDELTA and perfected in real analysis "
                "(REALAN). But even now it pays rent: every 'does the limit "
                "exist?' dispute is settled by this game and nothing else."
            )),
            # ---------------------------------------------------------- 9
            (E, "Worked examples: reading limits from every representation", (
                "EXAMPLE 1 (from a formula, with a table check). Estimate "
                "$\\lim_{x \\to 0} \\frac{e^x - 1}{x}$.\n\n"
                "Direct substitution: $\\frac{0}{0}$. Table: $x = 0.1$ gives "
                "$\\frac{0.10517}{0.1} = 1.0517$; $x = 0.01$ gives $1.00502$; "
                "$x = -0.01$ gives $0.99502$; $x = 0.001$ gives $1.0005$. Both "
                "sides squeeze toward $1$: the limit is $1$. (This limit IS the "
                "statement that $e^x$ has slope 1 at 0 — the defining property of "
                "the number $e$, as C110 will reveal.)\n\n"
                "EXAMPLE 2 (from a graph description). A function has: a smooth "
                "arc rising to an open circle at $(2, 4)$ from the left; a filled "
                "dot at $(2, 1)$; a curve descending from an open circle at "
                "$(2, 4)$ on the right. Report everything about $x = 2$.\n\n"
                "Left limit: 4. Right limit: 4. Two-sided limit: 4 (sides agree). "
                "Value: $f(2) = 1$ (the filled dot). Continuous? No — limit 4 "
                "$\\ne$ value 1. This is a REMOVABLE discontinuity: redefining "
                "one point ($f(2) := 4$) would repair it.\n\n"
                "EXAMPLE 3 (numerical trap — why tables need both sides). "
                "Estimate $\\lim_{x \\to 1} \\frac{|x - 1|}{x - 1}$ by table. "
                "From the right: $x = 1.01, 1.001$ give $1, 1$. If you stopped "
                "here you would report 1 — wrong. From the left: "
                "$x = 0.99, 0.999$ give $-1, -1$. The sides disagree; the limit "
                "DNE. Moral: a table sampled on only one side is HALF an answer, "
                "and the missing half is where trap questions live.\n\n"
                "EXAMPLE 4 (one-sided at a domain edge). "
                "$\\lim_{x \\to 0^+} \\sqrt{x}\\,$? As $x = 0.01, 0.0001$, "
                "$\\sqrt x = 0.1, 0.01 \\to 0$. The right-hand limit is 0. The "
                "LEFT-hand limit is not just hard — it's meaningless: "
                "$\\sqrt{x}$ has no values for $x < 0$ to approach with. At "
                "domain endpoints, the one-sided limit is the only limit there "
                "is, and by convention that suffices for continuity-at-an-"
                "endpoint questions (C103)."
            )),
            # ---------------------------------------------------------- 10
            (L, "All the ways a limit can fail", (
                "'The limit does not exist' (DNE) is not one phenomenon — it is "
                "three, and you should be able to name which one you are looking "
                "at.\n\n"
                "FAILURE MODE 1: JUMP. The one-sided limits both exist but "
                "disagree. Example: $\\frac{|x|}{x}$ at 0 (left $-1$, right "
                "$+1$). Typical of piecewise definitions and real-world "
                "step-changes (price breaks, phase switches). The graph shows "
                "two shelves.\n\n"
                "FAILURE MODE 2: UNBOUNDED (infinite) behavior. The outputs grow "
                "without bound. Example: $\\lim_{x \\to 0} \\frac{1}{x^2}$ — "
                "outputs exceed any bound as $x \\to 0$ from either side. We "
                "write $\\lim_{x \\to 0} \\frac{1}{x^2} = \\infty$ as a "
                "DESCRIPTION of the behavior (both sides blow up positively), "
                "but the limit does not exist as a number: $\\infty$ is not a "
                "real number, it is shorthand for 'grows past every bound.' "
                "Contrast $\\frac{1}{x}$ at 0: left side $\\to -\\infty$, right "
                "side $\\to +\\infty$ — unbounded AND mismatched; here we don't "
                "even write $= \\infty$; it is simply DNE with a vertical "
                "asymptote. Vertical asymptotes get full treatment in C104.\n\n"
                "FAILURE MODE 3: OSCILLATION. The outputs never settle. The "
                "classic: $\\lim_{x \\to 0} \\sin\\frac{1}{x}$. As $x \\to 0$, "
                "$\\frac1x$ races through $100, 1000, 10000, \\ldots$, so "
                "$\\sin\\frac1x$ keeps cycling through ALL values between $-1$ "
                "and $1$, infinitely often, in every neighborhood of 0. No "
                "single $L$ attracts the outputs; any table you build lies to "
                "you (sample at $x = \\frac{1}{n\\pi}$ and every output is 0!). "
                "This is the standard cautionary example for why tables are "
                "evidence, not proof.\n\n"
                "One REPAIRED cousin worth meeting now: "
                "$x \\sin\\frac{1}{x}$ at 0. The oscillation persists but is "
                "CRUSHED by the factor $x$: outputs are trapped between "
                "$-|x|$ and $|x|$, both of which head to 0. So "
                "$\\lim_{x \\to 0} x \\sin\\frac 1x = 0$ — the SQUEEZE THEOREM "
                "in action: if $g(x) \\le f(x) \\le h(x)$ near $a$ and "
                "$g, h \\to L$, then $f \\to L$. Squeezing returns in C102 as a "
                "genuine computational tool (it proves "
                "$\\frac{\\sin x}{x} \\to 1$)."
            )),
            # ---------------------------------------------------------- 11
            (E, "Worked example: diagnosing failures", (
                "For each limit, decide: exists (find it), or DNE (name the "
                "failure mode).\n\n"
                "(a) $\\lim_{x \\to 2} \\frac{1}{(x - 2)^2}$. Near 2, "
                "$(x-2)^2$ is tiny and POSITIVE from both sides, so the "
                "quotient explodes positively both sides. DNE as a number; "
                "we describe it as $= +\\infty$ (failure mode: unbounded, "
                "consistent sign). Vertical asymptote at $x = 2$.\n\n"
                "(b) $\\lim_{x \\to 2} \\frac{1}{x - 2}$. From the right, "
                "$x - 2$ is tiny positive → $+\\infty$; from the left, tiny "
                "negative → $-\\infty$. DNE, unbounded with MISMATCHED signs "
                "— do not write $= \\infty$ here.\n\n"
                "(c) $\\lim_{x \\to 0} \\frac{|2x|}{x}$. For $x > 0$: "
                "$\\frac{2x}{x} = 2$. For $x < 0$: $\\frac{-2x}{x} = -2$. "
                "Jump: left $-2$, right $+2$, DNE.\n\n"
                "(d) $\\lim_{x \\to 0} \\cos\\frac{1}{x}$. Oscillation — same "
                "disease as $\\sin\\frac1x$: every neighborhood of 0 contains "
                "$x$'s where the cosine is $+1$ and others where it is $-1$. "
                "DNE.\n\n"
                "(e) $\\lim_{x \\to 0} x^2 \\cos\\frac{1}{x}$. Squeeze: "
                "$-x^2 \\le x^2\\cos\\frac1x \\le x^2$ and both fences → 0. "
                "Limit EXISTS and equals 0 — oscillation tamed by a shrinking "
                "amplitude.\n\n"
                "(f) $\\lim_{x \\to 9} \\frac{x - 9}{\\sqrt x - 3}$. "
                "$\\frac00$ form, but not a failure — an invitation. Multiply "
                "by the conjugate or factor: $x - 9 = (\\sqrt x - 3)(\\sqrt x "
                "+ 3)$, so the quotient is $\\sqrt x + 3 \\to 6$. Limit "
                "exists: 6. Moral of (f): $\\frac00$ at the outset means 'work "
                "to do,' never 'DNE' — that misreading is one of the two "
                "biggest week-one errors, and page 12 dissects it."
            )),
            # ---------------------------------------------------------- 12
            (P, "Common misconceptions", (
                "MISCONCEPTION 1: 'The limit is the value.' The single most "
                "damaging one. The limit describes the APPROACH; $f(a)$ "
                "describes the POINT. They agree only for continuous "
                "functions — which is most textbook functions, which is "
                "exactly why the misconception survives: plugging in usually "
                "works, until the exam question with a hole or a relocated "
                "dot. Discipline: when a graph is involved, cover the point "
                "and read the trend.\n\n"
                "MISCONCEPTION 2: '$\\frac{0}{0}$ means the limit doesn't "
                "exist.' Backwards. $\\frac00$ is an INDETERMINATE form: it "
                "means the naive method (plugging in) failed, and the limit "
                "could be ANYTHING — 6 (Example 2, page 5), 1 "
                "($\\frac{\\sin x}{x}$), 0, $\\infty$, or genuinely DNE — "
                "depending on the tug-of-war between numerator and "
                "denominator. Indeterminate = 'not yet determined,' a "
                "starting gun, not a verdict.\n\n"
                "MISCONCEPTION 3: 'Writing $\\lim = \\infty$ means the limit "
                "exists and is infinity.' The equation is a description of "
                "unbounded behavior, not a number. On true/false questions, "
                "'$\\lim_{x\\to 0} \\frac{1}{x^2}$ exists' is FALSE even "
                "though we write it $= \\infty$.\n\n"
                "MISCONCEPTION 4: 'The function must be defined at $a$ for "
                "the limit to exist there.' The opposite of the truth — the "
                "definition deliberately excludes $x = a$ (that '$0 < "
                "|x - a|$'). Limits at holes are the WHOLE POINT: the "
                "derivative in C105 is a limit at a point where the defining "
                "quotient is undefined.\n\n"
                "MISCONCEPTION 5: 'If the table looks settled, the limit is "
                "proven.' $\\sin\\frac1x$ sampled at $x = \\frac{1}{n\\pi}$ "
                "gives a table of perfect zeros — and the limit DNE. Tables "
                "suggest; algebra and theorems conclude."
            )),
            # ---------------------------------------------------------- 13
            (P, "Common computational and procedural errors", (
                "ERROR 1: Using the wrong piece of a piecewise function for a "
                "one-sided limit. For $x \\to 2^-$ you must use the formula "
                "valid for $x < 2$ — the condition on the PIECE, not the "
                "direction of the arrow, decides. Write the piece down before "
                "computing.\n\n"
                "ERROR 2: One-sided sloppiness with signs. As $x \\to 3^-$, "
                "the quantity $x - 3$ is a SMALL NEGATIVE number. Students "
                "compute $\\frac{1}{x-3} \\to +\\infty$ from the left because "
                "'it blows up.' It blows up NEGATIVELY: "
                "$\\frac{1}{-0.001} = -1000$. Track the sign of the tiny "
                "quantity explicitly — write '$\\to 0^-$' — before assigning "
                "$\\pm\\infty$.\n\n"
                "ERROR 3: Cancelling and then forgetting the story. After "
                "simplifying $\\frac{(x-3)(x+3)}{x-3}$ to $x + 3$, the "
                "functions are equal only for $x \\ne 3$ — fine for the "
                "limit, but if a later part asks about $f(3)$ or continuity, "
                "the original function still has a hole. Keep the domain "
                "annotation: '$= x + 3$ for $x \\ne 3$.'\n\n"
                "ERROR 4: Radian/degree mode. $\\lim_{x \\to 0} "
                "\\frac{\\sin x}{x} = 1$ IN RADIANS; in degrees the limit is "
                "$\\frac{\\pi}{180} \\approx 0.0175$. Calculus is radians, "
                "always; a calculator in degree mode fabricates wrong "
                "tables.\n\n"
                "ERROR 5: Two-sided conclusions from one-sided evidence — "
                "checking only $x \\to a^+$ (usually because positive numbers "
                "feel friendlier) and reporting a two-sided limit. The "
                "check-both-sides habit costs ten seconds and is the entire "
                "difference on absolute-value and piecewise problems.\n\n"
                "ERROR 6: Notation drift: writing $\\lim_{x \\to 3} = 6$ "
                "(missing the function), or $f(x) \\to 6$ with no statement "
                "of where $x$ is going. Every limit statement has three "
                "parts — variable target, function, result. Graders and "
                "future-you both need all three."
            )),
            # ---------------------------------------------------------- 14
            (L, "Applications: where raw limits earn their keep", (
                "Limits are usually met as a stepping stone to derivatives, "
                "but the raw concept is already a working tool.\n\n"
                "1. INSTANTANEOUS RATES (the preview that matters most). "
                "Average speed over $[2, 2+h]$ is "
                "$\\frac{s(2+h) - s(2)}{h}$. Instantaneous speed at $t = 2$ "
                "is the LIMIT of that quotient as $h \\to 0$ — a $\\frac00$ "
                "form resolved exactly like this chapter's examples. C105 "
                "builds the whole derivative on this one move.\n\n"
                "2. CONTINUITY AUDITS OF MODELS. A tax schedule charges 10% "
                "up to \\$50{,}000 and 20% above. Is the TAX function "
                "continuous at \\$50{,}000 — i.e., does earning one more "
                "dollar jump your total tax? Compute both one-sided limits "
                "of the tax function at the bracket edge; a mismatch means "
                "the schedule (as written) punishes crossing the line, "
                "which real tax law avoids by applying rates marginally. "
                "One-sided limits are precisely the audit tool.\n\n"
                "3. SENSOR AND SIGNAL SANITY. A measured quantity that "
                "should vary smoothly (temperature, pressure) but whose "
                "reconstruction shows a jump (one-sided limits disagreeing) "
                "at a stitching point reveals an artifact of the data "
                "pipeline, not the physics. 'Do the one-sided limits "
                "match?' is the mathematical form of 'is this jump real?'\n\n"
                "4. REMOVABLE SINGULARITIES IN FORMULAS. Physics and "
                "engineering formulas frequently break at special "
                "parameter values while their limits exist: the formula "
                "$\\frac{\\sin x}{x}$ for diffraction intensity is undefined "
                "at the beam center $x = 0$, yet the intensity there is its "
                "limit, 1. Software that evaluates such formulas must patch "
                "the hole with the limit value — numerical analysts call "
                "this removing the singularity, and it is bread-and-butter "
                "in NUMERICS."
            )),
            # ---------------------------------------------------------- 15
            (E, "Applied worked example: from average to instantaneous", (
                "A ball is dropped from a tower; physics gives its fallen "
                "distance as $s(t) = 4.9t^2$ meters after $t$ seconds. "
                "Question: how fast is it falling exactly 2 seconds in?\n\n"
                "STEP 1 — what we can compute directly: average speeds. "
                "Between $t = 2$ and $t = 3$:\n"
                "$$\\frac{s(3) - s(2)}{3 - 2} = \\frac{44.1 - 19.6}{1} = 24.5 "
                "\\text{ m/s}.$$\n"
                "Between $t = 2$ and $t = 2.1$: "
                "$\\frac{21.609 - 19.6}{0.1} = 20.09$ m/s. Between $t = 2$ "
                "and $t = 2.01$: $\\frac{19.79649 - 19.6}{0.01} = 19.649$ "
                "m/s. Between $t = 2$ and $t = 2.001$: $19.6049$ m/s.\n\n"
                "The table is converging — to what?\n\n"
                "STEP 2 — set up the limit. The average speed over "
                "$[2, 2+h]$ is\n"
                "$$\\frac{s(2 + h) - s(2)}{h} = \\frac{4.9(2+h)^2 - "
                "4.9(4)}{h} = \\frac{4.9(4 + 4h + h^2) - 19.6}{h} = "
                "\\frac{19.6h + 4.9h^2}{h}.$$\n\n"
                "STEP 3 — resolve the $\\frac00$ form. For $h \\ne 0$, "
                "factor: $\\frac{h(19.6 + 4.9h)}{h} = 19.6 + 4.9h$. Now "
                "the limit is transparent:\n"
                "$$\\lim_{h \\to 0} (19.6 + 4.9h) = 19.6 \\text{ m/s}.$$\n\n"
                "The instantaneous speed at $t = 2$ is exactly 19.6 m/s — "
                "the number the table was creeping toward, now obtained "
                "exactly, in three lines, by this chapter's tools: set up "
                "the approach, hit $\\frac00$, simplify away the offending "
                "factor, read the limit.\n\n"
                "Every derivative you will ever compute is this "
                "calculation with the numbers replaced by symbols. If this "
                "page made sense, C105 will feel like a formality."
            )),
            # ---------------------------------------------------------- 16
            (L, "Connections: where this chapter plugs into everything else", (
                "BACKWARD (what this rested on): function evaluation and "
                "graph literacy from PRECALC; absolute values and "
                "inequalities (the $|x - a| < \\delta$ language) from the "
                "algebra track.\n\n"
                "FORWARD, immediately:\n"
                "• C102 (limit laws): today you FOUND limits by inspection "
                "and simplification; C102 legalizes the algebra — sums, "
                "products, quotients of limits, and the systematic "
                "$\\frac00$ toolkit (factor, conjugate, squeeze).\n"
                "• C103 (continuity): 'limit equals value' gets a name, a "
                "theory, and a payoff theorem (IVT). Every "
                "continuity question is a limit question in disguise.\n"
                "• C104 (limits at infinity): the same approach idea with "
                "$x \\to \\pm\\infty$ — end behavior and horizontal "
                "asymptotes; plus the infinite limits met on page 10 grow "
                "into vertical-asymptote theory.\n"
                "• C105 (the derivative): THE payoff. The derivative is "
                "one specific limit — the one you computed on page 15.\n\n"
                "FORWARD, further out: C117's definite integral is a limit "
                "of Riemann sums; C210-C216's sequences and series are "
                "limits of lists and partial sums; every convergence test "
                "is a limit criterion. In multivariable calculus the "
                "approach can come from infinitely many directions "
                "(C304's partial derivatives sidestep this; genuine "
                "multivariable limits are subtler). And REALAN rebuilds "
                "this entire chapter on the epsilon-delta definition alone "
                "— page 8 is the seed of a whole course.\n\n"
                "The dependency graph of calculus fans out from this node "
                "more than from any other. Time invested here compounds."
            )),
            # ---------------------------------------------------------- 17
            (L, "Going deeper: history and the modern view", (
                "It took the sharpest minds 150 years to find page 8. "
                "Newton (1660s) reasoned with 'fluxions' and vanishing "
                "quantities; Leibniz with 'infinitesimals' — numbers "
                "somehow smaller than every positive number yet not zero. "
                "The methods WORKED — planetary orbits fell out — but the "
                "foundations were mush, and critics knew it. Bishop "
                "Berkeley's 1734 takedown mocked infinitesimals as 'ghosts "
                "of departed quantities': you divide by $h$ (so "
                "$h \\ne 0$), then declare $h = 0$ — which is it?\n\n"
                "The repair came in stages. Cauchy (1820s) reframed "
                "everything through limits stated in approach language; "
                "Weierstrass (1850s-60s) removed the last motion-metaphors "
                "and left pure quantifiers — the $\\varepsilon$-$\\delta$ "
                "game, in which nothing moves and nothing vanishes: only "
                "'for every tolerance there is a radius.' That definition "
                "settled Berkeley's objection: we never set $h = 0$; we "
                "ask what value the expression approaches while "
                "$0 < |h|$.\n\n"
                "Two modern epilogues worth knowing. FIRST: infinitesimals "
                "were eventually vindicated — Abraham Robinson's "
                "nonstandard analysis (1960s) constructs a rigorous number "
                "system containing genuine infinitesimals, in which "
                "Leibniz-style arguments become theorems. Both foundations "
                "prove the same calculus; epsilon-delta remains the "
                "standard because it needs no new numbers. SECOND: the "
                "limit concept got MORE general, not less — topology "
                "(TOPO) redefines limits with open sets so the same idea "
                "works for functions between abstract spaces, and "
                "sequences, series, integrals, and derivatives all become "
                "instances of one notion of convergence. What you learned "
                "this chapter is the first, most concrete member of that "
                "family — and the template for all the others."
            )),
            # ---------------------------------------------------------- 18
            (L, "Summary and reference sheet", (
                "THE CONCEPT. $\\lim_{x \\to a} f(x) = L$: outputs get "
                "arbitrarily close to $L$ when inputs are sufficiently "
                "close to (but not equal to) $a$. The limit is about the "
                "approach; $f(a)$ is irrelevant to it.\n\n"
                "ONE-SIDED LIMITS. $x \\to a^-$ (from below), "
                "$x \\to a^+$ (from above). Two-sided limit exists iff "
                "both exist and agree.\n\n"
                "PRECISE DEFINITION. $\\forall \\varepsilon > 0\\; "
                "\\exists \\delta > 0: 0 < |x - a| < \\delta \\Rightarrow "
                "|f(x) - L| < \\varepsilon$. The '$0 <$' excludes the "
                "point itself.\n\n"
                "FAILURE MODES. (1) Jump: one-sided limits disagree. "
                "(2) Unbounded: outputs exceed every bound (write "
                "$\\pm\\infty$ only when the sign is consistent from both "
                "sides; it describes behavior, it is not a number). "
                "(3) Oscillation: outputs never settle "
                "($\\sin \\frac1x$).\n\n"
                "SQUEEZE THEOREM. If $g \\le f \\le h$ near $a$ and "
                "$g, h \\to L$, then $f \\to L$. Tames bounded "
                "oscillations multiplied by shrinking factors: "
                "$x\\sin\\frac1x \\to 0$.\n\n"
                "KEY SPECIAL LIMITS (radians!):\n"
                "$$\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1, \\qquad "
                "\\lim_{x \\to 0} \\frac{e^x - 1}{x} = 1, \\qquad "
                "\\lim_{x \\to 0} \\frac{1 - \\cos x}{x} = 0.$$\n\n"
                "INDETERMINATE MEANS UNDECIDED. $\\frac00$ on substitution "
                "= 'simplify and try again' (factor, conjugate, squeeze), "
                "never 'DNE.'\n\n"
                "WORKFLOW. (1) Substitute. Clean number → likely done "
                "(if continuous). (2) $\\frac{c}{0}$, $c \\ne 0$ → "
                "unbounded; determine signs side by side. (3) $\\frac00$ "
                "→ algebra. (4) Piecewise/absolute value → split into "
                "one-sided limits. (5) Oscillation suspected → hunt for a "
                "squeeze or a DNE argument. (6) Always sanity-check "
                "against a sketch or two table rows."
            )),
            # ---------------------------------------------------------- 19
            (K, "Self-test (with worked solutions)", (
                "Attempt all eight before reading the solutions.\n\n"
                "1. $\\lim_{x \\to 4} \\frac{x^2 - 16}{x - 4}$?\n"
                "2. $f(x) = \\frac{x^2-16}{x-4}$: what is $f(4)$, and is "
                "$f$ continuous at 4?\n"
                "3. $\\lim_{x \\to 0^-} \\frac{1}{x^3}$?\n"
                "4. $g(x) = 5x - 3$ for $x < 1$, $g(x) = x^2 + 1$ for "
                "$x \\ge 1$: does $\\lim_{x \\to 1} g(x)$ exist?\n"
                "5. For what $b$ does $\\lim_{x \\to 2} h(x)$ exist, if "
                "$h = bx^2$ for $x < 2$ and $h = 3x + b$ for $x > 2$?\n"
                "6. $\\lim_{x \\to 0} x^4 \\sin\\frac{1}{x}$?\n"
                "7. True or false: if $\\lim_{x \\to a} f(x)$ exists, "
                "then $f(a)$ is defined.\n"
                "8. Give a $\\delta$ that works for $\\varepsilon = 0.06$ "
                "in proving $\\lim_{x \\to 1}(2x + 1) = 3$.\n\n"
                "SOLUTIONS.\n"
                "1. Factor: $\\frac{(x-4)(x+4)}{x-4} = x + 4 \\to 8$.\n"
                "2. $f(4)$ is UNDEFINED ($\\frac00$); not continuous at 4 "
                "(no value to agree with the limit) — a removable "
                "discontinuity.\n"
                "3. $x \\to 0^-$: $x^3$ is tiny NEGATIVE, so "
                "$\\frac{1}{x^3} \\to -\\infty$ (unbounded, negative "
                "side).\n"
                "4. Left: $5(1) - 3 = 2$. Right: $1 + 1 = 2$. Sides agree: "
                "limit exists and equals 2.\n"
                "5. Left limit $4b$, right limit $6 + b$. $4b = 6 + b "
                "\\Rightarrow b = 2$; the common limit is 8.\n"
                "6. Squeeze: $-x^4 \\le x^4 \\sin\\frac1x \\le x^4$, both "
                "fences $\\to 0$; limit is 0.\n"
                "7. FALSE — problems 1-2 are the counterexample: limit 8, "
                "value undefined. (The definition's '$0 < |x - a|$' "
                "excludes the point.)\n"
                "8. Need $|2x + 1 - 3| = 2|x - 1| < 0.06$, i.e. "
                "$|x - 1| < 0.03$: take $\\delta = 0.03$ (anything "
                "smaller also works).\n\n"
                "Scoring guide: 8/8 — move on with confidence. 6-7 — "
                "reread the pages matching your misses (jump/sign errors "
                "→ pages 6-7 and 13; limit-vs-value → pages 3 and 12). "
                "≤5 — rework pages 3-11 before practicing."
            )),
            # ---------------------------------------------------------- 20
            (K, "Mastery checklist", (
                "Before leaving this chapter you should be able to check "
                "every box honestly:\n\n"
                "□ State what $\\lim_{x \\to a} f(x) = L$ means in plain "
                "language, including why $f(a)$ is irrelevant.\n"
                "□ Estimate a limit from a two-sided table, and explain "
                "why tables are evidence rather than proof (name the "
                "oscillation counterexample).\n"
                "□ Read limits, one-sided limits, values, and "
                "(dis)continuity off a graph with holes, dots, and "
                "jumps — using the cover-the-point discipline.\n"
                "□ Compute one-sided limits of piecewise and "
                "absolute-value functions, choosing the correct piece "
                "each side.\n"
                "□ Solve 'find the constant that makes the limit exist' "
                "problems by matching one-sided limits.\n"
                "□ Classify every DNE as jump, unbounded (with correct "
                "one-sided signs), or oscillation.\n"
                "□ Apply the squeeze theorem to "
                "$x^n \\sin\\frac1x$-type limits.\n"
                "□ Resolve simple $\\frac00$ forms by factoring or "
                "conjugates, and articulate why $\\frac00$ is a starting "
                "gun rather than an answer.\n"
                "□ Explain the $\\varepsilon$-$\\delta$ game and produce "
                "$\\delta$ for a linear function.\n"
                "□ Set up an instantaneous-rate problem as a limit of "
                "average rates and push it through (page 15's "
                "pattern).\n\n"
                "When every box is checked, hit Practice on this node "
                "until the streak feels boring — fluency here pays "
                "compound interest through every later chapter. Then "
                "proceed to C102, where limit computation becomes a "
                "systematic algebra."
            )),
        ],
    },
}
