"""Full course: C304 — Partial derivatives.

FC-template lesson: 20 full pages, matching the C101 gold standard
(calc1_a_limits.py) in depth and structure.
"""

L = "reading"
E = "example"
P = "pitfall"
K = "check"

LESSONS: dict[str, dict] = {
    "C304": {
        "summary": (
            "A complete course on partial derivatives: holding variables fixed, "
            "partials as slopes of surface slices, the limit definitions, computing "
            "partials of any function, higher-order and mixed partials with "
            "Clairaut's theorem, thermodynamic and economic interpretations, and "
            "the PDE, tangent-plane, and gradient roads that open from here."
        ),
        "steps": [
            # ---------------------------------------------------------- 1
            (L, "Where you are and why this matters", (
                "Everything you differentiated in Calculus 1 had ONE input. Almost "
                "nothing in the real world does. The temperature in a room depends on "
                "where you stand ($x$, $y$, $z$) and when you look ($t$). A factory's "
                "output depends on capital AND labor. The energy of a gas depends on "
                "its temperature AND its volume. The moment a function has two or more "
                "inputs, the question 'how fast is $f$ changing?' stops having a "
                "single answer — changing WHICH input? In WHICH direction?\n\n"
                "The PARTIAL DERIVATIVE is the first and simplest answer: change one "
                "input, freeze all the others, and measure the response. It is "
                "deliberately modest — one direction at a time — and that modesty is "
                "its power. Every rule you learned in C105-C110 transfers unchanged, "
                "because with all but one variable frozen you are back to "
                "single-variable calculus. No new differentiation techniques are "
                "needed in this chapter; what is new is the BOOKKEEPING (which "
                "variable is alive?), the GEOMETRY (slopes of slices of a surface), "
                "and the honest fine print (partials can exist while the function "
                "misbehaves — a genuinely multivariable surprise).\n\n"
                "The payoff is enormous. Assemble the partials into a vector and you "
                "get the GRADIENT (C307), the compass of multivariable calculus. Use "
                "them as coefficients and you get the TANGENT PLANE (C305), the "
                "linear approximation that generalizes the tangent line. Set them "
                "all to zero and you are doing OPTIMIZATION (C308). And the great "
                "equations of physics — heat, wave, Laplace — are literally "
                "sentences written in partial derivatives (page 14).\n\n"
                "In this chapter you will learn: what $f_x$ and $f_y$ mean "
                "geometrically and physically, their limit definitions, how to "
                "compute them for any function of two, three, or more variables, "
                "higher-order and mixed partials with Clairaut's theorem (and the "
                "famous counterexample when its hypothesis fails), and how to read "
                "both major notations without ever confusing the order of "
                "differentiation."
            )),
            # ---------------------------------------------------------- 2
            (L, "Prerequisites check", (
                "Partial differentiation is single-variable differentiation with "
                "stage directions. You need three things, all reviewable in an "
                "evening.\n\n"
                "1. THE FULL DIFFERENTIATION TOOLKIT (C105-C110). Power, product, "
                "quotient, and chain rules must be automatic, because every partial "
                "derivative computation IS one of those rules. If "
                "$\\frac{d}{dx}\\left(x^3 e^x\\right)$ or "
                "$\\frac{d}{dx}\\sin(x^2)$ requires thought rather than reflex, "
                "review first — this chapter will stress-test exactly those "
                "reflexes.\n\n"
                "2. THE LIMIT DEFINITION OF THE DERIVATIVE (C101, C105). "
                "$f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}$. Page 4 recycles "
                "this definition verbatim, and pages 10-11 use it in anger on "
                "functions where the shortcut rules do not apply.\n\n"
                "3. FUNCTIONS OF SEVERAL VARIABLES (C301). You should be comfortable "
                "with $z = f(x, y)$ as a SURFACE over the $xy$-plane: inputs are "
                "points $(x, y)$, the output is a height. Know the standard shapes: "
                "$z = x^2 + y^2$ (bowl/paraboloid), $z = 9 - x^2 - y^2$ (dome), "
                "$z = x^2 - y^2$ (saddle).\n\n"
                "Quick self-check (answers follow each question):\n\n"
                "• $\\frac{d}{dx}\\left(x^3 e^x\\right)$? (Product rule: "
                "$(3x^2 + x^3)e^x$.)\n"
                "• $\\frac{d}{dx}\\sin(x^2)$? (Chain rule: $2x\\cos(x^2)$.)\n"
                "• If $y$ is treated as a CONSTANT, what is "
                "$\\frac{d}{dx}\\left(x^2 y^3\\right)$? ($2xy^3$ — the $y^3$ rides "
                "along exactly like the 7 in $7x^2$.)\n"
                "• What surface is $z = x^2 + y^2$, and what curve do you get by "
                "setting $y = 0$? (A paraboloid; the slice is the parabola "
                "$z = x^2$.)\n\n"
                "That last question — slice a surface, get a curve — is the entire "
                "geometric content of this chapter. If all four felt easy, "
                "proceed."
            )),
            # ---------------------------------------------------------- 3
            (L, "The core idea, intuitively: slicing the surface", (
                "Picture the graph of $z = f(x, y)$ as a landscape — a surface "
                "floating over the $xy$-plane. Stand above the point $(a, b)$. "
                "Asking 'what is the slope here?' is ambiguous: facing east the "
                "ground may climb, facing north it may fall. A surface has a "
                "different slope in every direction. The partial derivative's move "
                "is to pick the two axis directions and measure those first.\n\n"
                "Slice the surface with the vertical plane $y = b$ (a wall parallel "
                "to the $x$-axis). The knife-cut is a CURVE: $z = f(x, b)$, an "
                "ordinary single-variable function of $x$, because $b$ is just a "
                "number. The slope of that curve at $x = a$ is the partial "
                "derivative $f_x(a, b)$ — the rate of change of $f$ as you walk in "
                "the $x$-direction. Slice instead with the plane $x = a$ and you "
                "get the curve $z = f(a, y)$, whose slope at $y = b$ is "
                "$f_y(a, b)$ — the rate as you walk in the $y$-direction. Like a "
                "CT scan, the slices turn one incomprehensible 3D object into a "
                "family of familiar 2D curves.\n\n"
                "Concretely: let $f(x, y) = 9 - x^2 - y^2$ (a dome) and stand at "
                "$(1, 2)$, height $f(1, 2) = 4$. The slice $y = 2$ is the parabola "
                "$z = 5 - x^2$, with slope $-2x = -2$ at $x = 1$: walking east, "
                "you descend 2 units of height per unit of ground. The slice "
                "$x = 1$ is $z = 8 - y^2$, slope $-2y = -4$ at $y = 2$: walking "
                "north is twice as steep. Two numbers, two directions, one "
                "point.\n\n"
                "The physical picture is the same. Let $T(x, y)$ be the "
                "temperature on a metal plate. $T_x$ answers 'if I step east, how "
                "fast does it get hotter?'; $T_y$ answers the same for north. "
                "HOLD EVERYTHING ELSE STILL, WIGGLE ONE INPUT, WATCH THE OUTPUT — "
                "that sentence is the whole concept. Every formula in this "
                "chapter is that sentence in symbols."
            )),
            # ---------------------------------------------------------- 4
            (L, "The formal definition", (
                "The slicing picture becomes a definition by recycling C105's "
                "limit. Freeze $y$ at $b$; the slice $g(x) = f(x, b)$ is a "
                "single-variable function; the partial derivative of $f$ with "
                "respect to $x$ at $(a, b)$ is $g'(a)$:\n"
                "$$f_x(a, b) = \\lim_{h \\to 0} \\frac{f(a + h,\\, b) - "
                "f(a, b)}{h},$$\n"
                "and symmetrically\n"
                "$$f_y(a, b) = \\lim_{k \\to 0} \\frac{f(a,\\, b + k) - "
                "f(a, b)}{k}.$$\n"
                "Read the first one closely: only the FIRST slot moves ($a$ "
                "becomes $a + h$); the second slot holds $b$ throughout. The "
                "definition does not merely SUGGEST holding $y$ fixed — it "
                "enforces it: $y$ never changes inside the limit.\n\n"
                "Let us use the definition once, honestly. Take $f(x, y) = x^2 y$ "
                "at a general point $(a, b)$:\n"
                "$$f_x(a, b) = \\lim_{h \\to 0} \\frac{(a+h)^2 b - a^2 b}{h} = "
                "\\lim_{h \\to 0} \\frac{b\\,(2ah + h^2)}{h} = "
                "\\lim_{h \\to 0} b\\,(2a + h) = 2ab.$$\n"
                "Exactly what the shortcut predicts: treat $y$ as a constant and "
                "differentiate $x^2 y$ to get $2xy$. The definition and the rule "
                "agree — the rule IS the definition, streamlined.\n\n"
                "Notation. The curly symbol $\\partial$ (read 'partial' or 'del') "
                "replaces $d$ precisely to warn you that other variables exist "
                "and are being held: $\\frac{\\partial f}{\\partial x}$ is "
                "Leibniz notation, $f_x$ is subscript notation, and "
                "$\\frac{\\partial z}{\\partial x}$, $\\partial_x f$, $D_x f$ "
                "all appear in the wild. Evaluation at a point is written "
                "$f_x(1, 2)$ or "
                "$\\left.\\frac{\\partial f}{\\partial x}\\right|_{(1,2)}$.\n\n"
                "One definition, per variable, per point. Everything else in "
                "this chapter — rules, higher partials, applications — is this "
                "limit wearing different clothes."
            )),
            # ---------------------------------------------------------- 5
            (E, "First worked examples", (
                "The working ritual: name the LIVE variable, demote every other "
                "variable to a constant, then differentiate as in Calculus 1.\n\n"
                "EXAMPLE 1 (polynomial). $f(x, y) = x^3 y^2 + 4x - 7y$.\n"
                "For $f_x$, the live variable is $x$; treat $y^2$ like a frozen "
                "number: $\\frac{\\partial}{\\partial x}(x^3 y^2) = 3x^2 y^2$, "
                "$\\frac{\\partial}{\\partial x}(4x) = 4$, and $-7y$ is a pure "
                "constant, contributing 0. So $f_x = 3x^2 y^2 + 4$. For $f_y$: "
                "$f_y = 2x^3 y - 7$, and this time the $4x$ term dies. At "
                "$(1, 2)$: $f_x(1, 2) = 3(1)(4) + 4 = 16$ — the east-facing "
                "slice of the surface has slope 16 there.\n\n"
                "EXAMPLE 2 (a frozen factor is NOT a product rule). "
                "$f(x, y) = x^2 \\sin y$.\n"
                "For $f_x$, the factor $\\sin y$ is a constant coefficient — no "
                "product rule needed: $f_x = 2x \\sin y$. For $f_y$, the roles "
                "flip and $x^2$ is the coefficient: $f_y = x^2 \\cos y$. The "
                "product rule is only for two factors that BOTH contain the live "
                "variable.\n\n"
                "EXAMPLE 3 (whole terms can vanish). "
                "$f(x, y) = x^2 y^3 + e^y$.\n"
                "$f_x = 2x y^3 + 0 = 2xy^3$: the term $e^y$ contains no $x$ at "
                "all, so with respect to $x$ it is as constant as $\\pi$. "
                "$f_y = 3x^2 y^2 + e^y$. Students who 'differentiate everything "
                "in sight' write $e^y$ inside $f_x$ — the ritual (who is "
                "alive?) prevents this.\n\n"
                "EXAMPLE 4 (a genuine product rule). $f(x, y) = x\\,e^{xy}$.\n"
                "For $f_x$, BOTH factors contain $x$: product rule, with a chain "
                "rule inside ($\\frac{\\partial}{\\partial x} e^{xy} = "
                "y\\,e^{xy}$, since $xy$ has $x$-derivative $y$):\n"
                "$$f_x = 1 \\cdot e^{xy} + x \\cdot y e^{xy} = (1 + xy)\\,"
                "e^{xy}.$$\n"
                "For $f_y$, only the exponential contains $y$; the leading $x$ "
                "is a coefficient: $f_y = x \\cdot x e^{xy} = x^2 e^{xy}$. Same "
                "function, different rule per variable — the bookkeeping decides "
                "everything."
            )),
            # ---------------------------------------------------------- 6
            (L, "Higher-order partials and Clairaut's theorem", (
                "$f_x$ and $f_y$ are themselves functions of $x$ and $y$ — so "
                "they can be differentiated again, in either variable. Two first "
                "partials each split two ways, giving FOUR second-order "
                "partials:\n"
                "$$f_{xx} = (f_x)_x, \\quad f_{xy} = (f_x)_y, \\quad "
                "f_{yx} = (f_y)_x, \\quad f_{yy} = (f_y)_y.$$\n"
                "$f_{xx}$ and $f_{yy}$ are the concavities of the two slice "
                "curves — how each directional slope is itself changing. The "
                "MIXED partials $f_{xy}$ and $f_{yx}$ measure interaction: "
                "$f_{xy}$ asks 'how does the east-facing slope change as I step "
                "north?' On a twisted surface like a saddle, that is genuinely "
                "new information.\n\n"
                "The two mixed partials come from different procedures — $x$ "
                "then $y$, versus $y$ then $x$ — and there is no obvious reason "
                "the results should match. Yet in every example you will compute "
                "this week, they do. That is a theorem:\n\n"
                "CLAIRAUT'S THEOREM (also credited to Schwarz). If $f_{xy}$ and "
                "$f_{yx}$ both exist and are CONTINUOUS on an open disk around "
                "$(a, b)$, then $f_{xy}(a, b) = f_{yx}(a, b)$.\n\n"
                "The hypothesis is not decoration. There is a classic function — "
                "$\\frac{xy(x^2 - y^2)}{x^2 + y^2}$, patched with value 0 at the "
                "origin — whose mixed partials both exist at $(0,0)$ but are NOT "
                "continuous there, and they disagree: one is $-1$, the other "
                "$+1$. Page 17 works it out. For the smooth functions of daily "
                "calculus (polynomials, exponentials, sines, and their "
                "compositions), continuity holds automatically and order never "
                "matters.\n\n"
                "The theorem extends to higher orders and more variables: for a "
                "smooth $f$, a third-order partial like $f_{xxy}$ depends only "
                "on HOW MANY times each variable is used, not the order — "
                "$f_{xxy} = f_{xyx} = f_{yxx}$. Practical payoff: the $n^2$ "
                "second partials of an $n$-variable function form a SYMMETRIC "
                "matrix (the Hessian), which halves your computation and powers "
                "the second-derivative test in C308."
            )),
            # ---------------------------------------------------------- 7
            (E, "Worked examples: standard problems", (
                "EXAMPLE 1 (all four second partials, both mixed orders). "
                "$f(x, y) = x^3 y^2 - 5x y^4$.\n"
                "First partials: $f_x = 3x^2 y^2 - 5y^4$ and "
                "$f_y = 2x^3 y - 20xy^3$.\n"
                "Now the second layer. $f_{xx} = \\frac{\\partial}{\\partial x}"
                "(3x^2y^2 - 5y^4) = 6xy^2$. "
                "$f_{yy} = \\frac{\\partial}{\\partial y}(2x^3y - 20xy^3) = "
                "2x^3 - 60xy^2$. The mixed pair, computed in BOTH orders as a "
                "check:\n"
                "$$f_{xy} = \\frac{\\partial}{\\partial y}\\left(3x^2y^2 - "
                "5y^4\\right) = 6x^2 y - 20y^3, \\qquad "
                "f_{yx} = \\frac{\\partial}{\\partial x}\\left(2x^3y - "
                "20xy^3\\right) = 6x^2 y - 20y^3.$$\n"
                "Equal, as Clairaut promises — and computing both orders is a "
                "free error-check on your first partials.\n\n"
                "EXAMPLE 2 (trig-exponential; a first taste of Laplace). "
                "$f(x, y) = e^x \\cos y$.\n"
                "$f_x = e^x \\cos y$, $f_y = -e^x \\sin y$. Then "
                "$f_{xx} = e^x \\cos y$ and $f_{yy} = -e^x \\cos y$, so\n"
                "$$f_{xx} + f_{yy} = 0.$$\n"
                "Functions satisfying this identity are called HARMONIC — they "
                "solve Laplace's equation, the steady-state equation of page 14. "
                "Both mixed partials equal $-e^x \\sin y$.\n\n"
                "EXAMPLE 3 (chain rule per variable). $f(x, y) = "
                "\\ln(x^2 + y^2)$.\n"
                "$f_x = \\frac{2x}{x^2 + y^2}$, $f_y = \\frac{2y}{x^2 + y^2}$ — "
                "same outer derivative $\\frac{1}{u}$, different inner "
                "derivative per variable. One mixed partial by the quotient "
                "rule: $f_{xy} = \\frac{\\partial}{\\partial y}\\frac{2x}"
                "{x^2+y^2} = \\frac{0 - 2x \\cdot 2y}{(x^2+y^2)^2} = "
                "\\frac{-4xy}{(x^2+y^2)^2}$, and symmetry gives $f_{yx}$ the "
                "same value.\n\n"
                "EXAMPLE 4 (quotient rule per variable). $f(x, y) = "
                "\\frac{x}{x + y}$.\n"
                "$$f_x = \\frac{(x+y) \\cdot 1 - x \\cdot 1}{(x+y)^2} = "
                "\\frac{y}{(x+y)^2}, \\qquad "
                "f_y = \\frac{(x+y) \\cdot 0 - x \\cdot 1}{(x+y)^2} = "
                "\\frac{-x}{(x+y)^2}.$$\n"
                "In $f_y$, the numerator $x$ is a CONSTANT (derivative 0) — the "
                "quotient rule still runs, but half of it vanishes."
            )),
            # ---------------------------------------------------------- 8
            (L, "Techniques, bookkeeping, and reading the notation", (
                "TECHNIQUE 1: NAME THE LIVE VARIABLE, OUT LOUD. Before every "
                "computation, say 'live: $x$; frozen: $y$, $z$.' Strong students "
                "literally re-read the expression pretending each frozen variable "
                "is a specific number: in $y^3 x^2 + \\sin y$, pretend $y = 7$ "
                "and the expression becomes $343\\,x^2 + \\sin 7$ — now the "
                "$x$-derivative ($686x$, i.e. $2y^3x$) is obvious, and so is the "
                "vanishing of $\\sin y$.\n\n"
                "TECHNIQUE 2: REWRITE BEFORE DIFFERENTIATING. "
                "$\\frac{x}{y^2 + 1}$ looks like a quotient-rule job; as a "
                "function of $x$ it is $\\frac{1}{y^2+1} \\cdot x$ — LINEAR, with "
                "$f_x = \\frac{1}{y^2+1}$ on sight. Ask: how does the live "
                "variable actually appear? Often the frozen variables form a "
                "single constant coefficient and the hard-looking rule "
                "evaporates.\n\n"
                "TECHNIQUE 3: FREEZE-THEN-DIFFERENTIATE FOR POINT EVALUATION. To "
                "find $f_x(a, b)$ you may substitute $y = b$ FIRST and then "
                "differentiate the resulting one-variable function — legal, "
                "because $y$ is held at $b$ anyway, and often much faster. The "
                "one absolute prohibition: never substitute the LIVE variable's "
                "value before differentiating ($x = a$ first would freeze the "
                "very motion you are measuring, leaving a constant).\n\n"
                "TECHNIQUE 4: READ THE ORDER OF DIFFERENTIATION CORRECTLY. The "
                "two notations read in OPPOSITE directions:\n"
                "• Subscripts read LEFT TO RIGHT: $f_{xy} = (f_x)_y$ means '$x$ "
                "first, then $y$.'\n"
                "• Leibniz reads RIGHT TO LEFT (inside out): "
                "$\\frac{\\partial^2 f}{\\partial y\\,\\partial x} = "
                "\\frac{\\partial}{\\partial y}\\!\\left(\\frac{\\partial f}"
                "{\\partial x}\\right)$ — also '$x$ first, then $y$.'\n"
                "So $f_{xy}$ and $\\frac{\\partial^2 f}{\\partial y \\partial x}$ "
                "are the SAME object, despite the letters appearing in opposite "
                "orders. By Clairaut this rarely changes answers for smooth "
                "functions, but exam questions about 'which order does this "
                "notation specify?' are common — and for the page-17 "
                "counterexample, the order genuinely matters.\n\n"
                "TECHNIQUE 5: MORE VARIABLES, SAME RITUAL. For "
                "$f(x, y, z, w, \\ldots)$ nothing new happens: exactly one "
                "variable is ever alive. Ten variables just means ten separate "
                "single-variable problems."
            )),
            # ---------------------------------------------------------- 9
            (E, "Worked examples: harder problems", (
                "EXAMPLE 1 (chain rule, then mixed partials both ways). "
                "$f(x, y) = \\sin(x^2 y)$.\n"
                "Inner function $u = x^2 y$: $u_x = 2xy$, $u_y = x^2$. So "
                "$f_x = 2xy\\cos(x^2y)$ and $f_y = x^2\\cos(x^2y)$ — same "
                "cosine, different inner derivative. Now $f_{xy}$, "
                "differentiating $f_x$ with respect to $y$ (product rule: both "
                "$2xy$ and $\\cos(x^2y)$ contain $y$):\n"
                "$$f_{xy} = 2x\\cos(x^2y) + 2xy \\cdot \\left(-\\sin(x^2y)"
                "\\right) x^2 = 2x\\cos(x^2y) - 2x^3y\\,\\sin(x^2y).$$\n"
                "Cross-check via $f_{yx} = \\frac{\\partial}{\\partial x}"
                "\\left(x^2\\cos(x^2y)\\right) = 2x\\cos(x^2y) + x^2 \\cdot "
                "\\left(-\\sin(x^2y)\\right) 2xy$ — identical. Clairaut "
                "verified the hard way.\n\n"
                "EXAMPLE 2 (product and chain in one variable, neither in the "
                "other). $f(x, y) = x^2 e^{xy}$.\n"
                "$f_x$ needs the product rule ($x^2$ and $e^{xy}$ both contain "
                "$x$): $f_x = 2x e^{xy} + x^2 \\cdot y e^{xy} = "
                "(2x + x^2 y)\\,e^{xy}$. $f_y$ needs no product rule at all: "
                "$f_y = x^2 \\cdot x e^{xy} = x^3 e^{xy}$.\n\n"
                "EXAMPLE 3 (a gradient-flavored classic). "
                "$f(x, y) = \\arctan\\!\\left(\\frac{y}{x}\\right)$.\n"
                "Outer derivative $\\frac{1}{1 + (y/x)^2} = "
                "\\frac{x^2}{x^2+y^2}$. Then "
                "$f_x = \\frac{x^2}{x^2+y^2} \\cdot \\left(-\\frac{y}{x^2}"
                "\\right) = \\frac{-y}{x^2+y^2}$ and "
                "$f_y = \\frac{x^2}{x^2+y^2} \\cdot \\frac{1}{x} = "
                "\\frac{x}{x^2+y^2}$. Bonus: $f_{xx} = \\frac{2xy}{(x^2+y^2)^2}$ "
                "and $f_{yy} = \\frac{-2xy}{(x^2+y^2)^2}$, so "
                "$f_{xx} + f_{yy} = 0$ — harmonic again (this $f$ is the polar "
                "angle $\\theta$).\n\n"
                "EXAMPLE 4 (three variables). $w = z\\,e^{xy} + y \\ln z$.\n"
                "Live $x$ (freeze $y, z$): $w_x = z \\cdot y e^{xy} = "
                "yz\\,e^{xy}$; the $y\\ln z$ term dies. Live $y$: "
                "$w_y = z \\cdot x e^{xy} + \\ln z = xz\\,e^{xy} + \\ln z$. "
                "Live $z$: $w_z = e^{xy} + \\frac{y}{z}$. Three variables, "
                "three ordinary derivatives — the ritual scales without "
                "friction."
            )),
            # ---------------------------------------------------------- 10
            (L, "Special cases and edge behavior", (
                "Here is the honest fine print, and it is genuinely "
                "multivariable.\n\n"
                "PARTIALS ARE AXIS-ONLY PROBES. $f_x(a,b)$ and $f_y(a,b)$ "
                "interrogate the function along exactly two lines through "
                "$(a, b)$ — east-west and north-south. They are blind to every "
                "other direction. In single-variable calculus, differentiability "
                "at a point forces continuity there; in two variables, the "
                "EXISTENCE OF BOTH PARTIALS FORCES NOTHING. A function can have "
                "perfectly good partials at a point and still fail to be "
                "continuous there, because it can behave beautifully along the "
                "two axes and pathologically along the diagonal. Page 11 works "
                "the standard example.\n\n"
                "KINKS IN ONE VARIABLE ONLY. $f(x, y) = |x|$ (a folded sheet, "
                "creased along the $y$-axis). $f_y = 0$ everywhere — every "
                "north-south slice is a horizontal line. But $f_x$ fails to "
                "exist anywhere on the crease $x = 0$, for the same reason "
                "$|x|$ has no derivative at 0: the slice has a corner. Partials "
                "can exist in some variables and not others; check each "
                "separately.\n\n"
                "PIECEWISE-DEFINED POINTS NEED THE DEFINITION. If a function is "
                "defined by a formula away from a point and patched by hand at "
                "the point (as in $f(0,0) = 0$ declarations), the shortcut rules "
                "say nothing AT the patch — rules differentiate formulas, and "
                "the formula does not hold there. At such points you must "
                "return to page 4's limit definition. This is not an exotic "
                "situation: it is exactly how every interesting counterexample "
                "in this subject is built, and exam problems love it.\n\n"
                "WHAT RESTORES ORDER: if the partials not only exist at the "
                "point but are CONTINUOUS in a neighborhood of it, the function "
                "is differentiable there — tangent plane, continuity, and all "
                "good behavior included. Continuity of partials, not their mere "
                "existence, is the multivariable analogue of 'differentiable.' "
                "C305 and page 17 tell that story properly."
            )),
            # ---------------------------------------------------------- 11
            (E, "Worked example: edge cases", (
                "THE STANDARD PATHOLOGY. Define\n"
                "$$f(x, y) = \\begin{cases} \\dfrac{xy}{x^2 + y^2} & (x, y) "
                "\\ne (0, 0) \\\\[4pt] 0 & (x, y) = (0, 0). \\end{cases}$$\n"
                "QUESTION: do $f_x(0,0)$ and $f_y(0,0)$ exist? Is $f$ "
                "continuous at the origin?\n\n"
                "STEP 1 — partials at the origin, by the definition (the "
                "formula is patched at $(0,0)$, so rules are off the table):\n"
                "$$f_x(0, 0) = \\lim_{h \\to 0} \\frac{f(h, 0) - f(0,0)}{h} = "
                "\\lim_{h \\to 0} \\frac{\\frac{h \\cdot 0}{h^2 + 0} - 0}{h} = "
                "\\lim_{h \\to 0} \\frac{0}{h} = 0.$$\n"
                "By the symmetry $f(x,y) = f(y,x)$, also $f_y(0,0) = 0$. Both "
                "partials exist, both equal 0. Along the axes, $f$ is "
                "identically zero — flat as a table.\n\n"
                "STEP 2 — continuity, by approaching along other lines. On the "
                "line $y = mx$ (with $x \\ne 0$):\n"
                "$$f(x, mx) = \\frac{x \\cdot mx}{x^2 + m^2x^2} = "
                "\\frac{m}{1 + m^2}.$$\n"
                "This is CONSTANT along each line — but a different constant "
                "per line: 0 along the axes ($m = 0$), $\\frac{1}{2}$ along "
                "$y = x$, $-\\frac{1}{2}$ along $y = -x$. Approaching the "
                "origin along $y = x$, the values sit at $\\frac12$ forever, "
                "nowhere near $f(0,0) = 0$. So $\\lim_{(x,y) \\to (0,0)} "
                "f(x,y)$ does not exist, and $f$ is NOT continuous at the "
                "origin.\n\n"
                "STEP 3 — the verdict. Both partials exist at $(0,0)$, yet $f$ "
                "is not even continuous there. In one variable this is "
                "impossible; in two it is Tuesday. The partials probed the "
                "axes, the axes were innocent, and the crime was on the "
                "diagonal.\n\n"
                "STEP 4 — reconcile with page 10's rescue clause. Away from "
                "the origin the quotient rule gives $f_x = "
                "\\frac{y(y^2 - x^2)}{(x^2+y^2)^2}$; along the $y$-axis this is "
                "$f_x(0, y) = \\frac{1}{y}$, which blows up as $y \\to 0$. The "
                "partials exist everywhere but are wildly DISCONTINUOUS at the "
                "origin — so the 'continuous partials $\\Rightarrow$ "
                "differentiable' theorem never applies, and no contradiction "
                "arises. Existence is cheap; continuity of partials is what "
                "buys good behavior."
            )),
            # ---------------------------------------------------------- 12
            (P, "Common misconceptions", (
                "MISCONCEPTION 1: 'Hold $y$ fixed' means 'set $y = 0$.' No — "
                "frozen, not zero. In $f = x^2 + xy + y^2$, $f_x = 2x + y$: the "
                "$y$ survives as a symbol, because the answer must be valid at "
                "EVERY point $(x, y)$, whatever the frozen value happens to be. "
                "Setting $y = 0$ computes only $f_x(x, 0)$ and silently throws "
                "away the rest of the plane.\n\n"
                "MISCONCEPTION 2: 'The partials exist, so the function is "
                "well-behaved (continuous, differentiable).' Page 11's "
                "$\\frac{xy}{x^2+y^2}$ kills this: partials exist at the "
                "origin, continuity fails. Partials probe two directions out "
                "of infinitely many. Good behavior is certified by CONTINUOUS "
                "partials, not existing ones.\n\n"
                "MISCONCEPTION 3: '$f_{xy} = f_{yx}$, always, no conditions.' "
                "Almost — and 'almost' is the point. Clairaut requires the "
                "mixed partials to be continuous; page 17's counterexample has "
                "$f_{xy}(0,0) = -1 \\ne 1 = f_{yx}(0,0)$. Quote the theorem "
                "WITH its hypothesis.\n\n"
                "MISCONCEPTION 4: '$\\partial$'s cancel like fractions.' In "
                "single-variable calculus, $\\frac{dy}{dx}$ behaves remarkably "
                "like a quotient. Partials do NOT. For three variables related "
                "by one equation (say $P$, $V$, $T$ for a gas), the triple "
                "product rule says\n"
                "$$\\left(\\frac{\\partial P}{\\partial V}\\right)_{\\!T} "
                "\\left(\\frac{\\partial V}{\\partial T}\\right)_{\\!P} "
                "\\left(\\frac{\\partial T}{\\partial P}\\right)_{\\!V} = -1,$$\n"
                "MINUS one — naive cancellation predicts $+1$ and is simply "
                "wrong. A partial derivative is a limit taken under specific "
                "held-variable conditions, not a ratio of little numbers.\n\n"
                "MISCONCEPTION 5: '$f_x$ and $f_y$ tell me the rate of change "
                "in any direction.' They give the axis rates only. The rate "
                "walking northeast is a DIRECTIONAL derivative (C307), computed "
                "from the partials via the gradient — but it is not $f_x$, not "
                "$f_y$, and not their average by default. Two slopes do "
                "determine all the others for DIFFERENTIABLE functions — that "
                "is the miracle of the tangent plane (C305) — but only once "
                "differentiability is earned."
            )),
            # ---------------------------------------------------------- 13
            (P, "Common computational errors", (
                "ERROR 1: Product rule amnesia — and product rule overuse. For "
                "$x^2 e^{xy}$ with respect to $x$, BOTH factors contain $x$: "
                "product rule mandatory. For $x^2 \\sin y$ with respect to "
                "$x$, only one factor does: $\\sin y$ is a coefficient, and "
                "invoking the product rule (though not wrong) invites sign and "
                "term errors. Ask 'do both factors contain the live variable?' "
                "before choosing the rule.\n\n"
                "ERROR 2: Wrong inner derivative in the chain rule. For "
                "$\\sin(x^2 y)$: the inner derivative with respect to $x$ is "
                "$2xy$, but with respect to $y$ it is $x^2$ — NOT $2xy$ again. "
                "The inner derivative must be recomputed for each live "
                "variable; copying it across variables is the single most "
                "common error on mixed-partial problems.\n\n"
                "ERROR 3: Forgetting the chain factor entirely: "
                "$\\frac{\\partial}{\\partial x} e^{xy} = e^{xy}$ (missing the "
                "$y$). The exponent is $xy$, not $x$; its $x$-derivative $y$ "
                "must appear: $y\\,e^{xy}$.\n\n"
                "ERROR 4: Letting a constant term survive. In "
                "$f = x^2y^3 + e^y$, the $x$-partial of $e^y$ is 0, not $e^y$. "
                "Symmetrically, terms with no $y$ die in $f_y$. Scan the "
                "answer: every term of $f_x$ should have come from a term of "
                "$f$ that actually contained $x$.\n\n"
                "ERROR 5: Misreading the order of differentiation. "
                "$\\frac{\\partial^2 f}{\\partial y \\partial x}$ means $x$ "
                "FIRST (inside-out), and equals $f_{xy}$ (left-to-right). "
                "Students who read Leibniz left-to-right differentiate in the "
                "wrong order — harmless for smooth functions by Clairaut, fatal "
                "on definition-based problems and on 'which order?' exam "
                "questions.\n\n"
                "ERROR 6: Substituting the point too early. To compute "
                "$f_x(2, 3)$, you may freeze $y = 3$ first — but freezing "
                "$x = 2$ first turns $f$ into a function with no $x$ left, and "
                "its 'derivative' is 0. Differentiate in the live variable "
                "FIRST, substitute its value LAST. (Frozen variables may be "
                "substituted whenever convenient.)"
            )),
            # ---------------------------------------------------------- 14
            (L, "Applications: marginal quantities, thermodynamics, geometry, PDEs", (
                "1. ECONOMICS: MARGINAL PRODUCTS. Let $Q(K, L)$ be a firm's "
                "output from capital $K$ and labor $L$. Then "
                "$\\frac{\\partial Q}{\\partial L}$ is the MARGINAL PRODUCT OF "
                "LABOR: the extra output from one more unit of labor, "
                "HOLDING CAPITAL FIXED — the held variable is the entire "
                "economic content, since hiring while also buying machines "
                "confounds the measurement. Diminishing returns is a statement "
                "about a second partial: $\\frac{\\partial^2 Q}{\\partial L^2} "
                "< 0$. Page 15 runs a full Cobb-Douglas example.\n\n"
                "2. THERMODYNAMICS: WHY $(\\partial U / \\partial T)_V$ NEEDS "
                "ITS SUBSCRIPT. The internal energy $U$ of a gas can be viewed "
                "as a function of $(T, V)$ or of $(T, P)$ — same physical "
                "quantity, different coordinate systems. 'The derivative of "
                "$U$ with respect to $T$' is therefore AMBIGUOUS until you say "
                "what is held fixed: $\\left(\\frac{\\partial U}{\\partial T}"
                "\\right)_V$ (heating in a sealed rigid tank) and "
                "$\\left(\\frac{\\partial U}{\\partial T}\\right)_P$ (heating "
                "under a free piston) are physically different experiments "
                "with different answers. Thermodynamics writes the held "
                "variable as a subscript precisely because, unlike in math "
                "class, the 'other variables' change identity constantly. The "
                "rate depends not just on what you vary but on what you "
                "hold.\n\n"
                "3. GEOMETRY: SLOPES TODAY, TANGENT PLANES TOMORROW. "
                "$f_x(a,b)$ and $f_y(a,b)$ are the slopes of the two axis "
                "slices — and for differentiable $f$ those two numbers "
                "determine the entire TANGENT PLANE:\n"
                "$$z = f(a,b) + f_x(a,b)\\,(x - a) + f_y(a,b)\\,(y - b),$$\n"
                "the flat sheet that best approximates the surface, and the "
                "star of C305.\n\n"
                "4. PDEs: THE LAWS OF PHYSICS ARE SENTENCES IN PARTIALS. The "
                "HEAT EQUATION $u_t = \\alpha\\, u_{xx}$ says temperature "
                "rises where the profile is concave up (heat flows into "
                "valleys). The WAVE EQUATION $u_{tt} = c^2 u_{xx}$ says "
                "acceleration is proportional to curvature (a stretched "
                "string straightens itself). LAPLACE'S EQUATION "
                "$u_{xx} + u_{yy} = 0$ describes steady states — you met two "
                "harmonic functions on pages 7 and 9. Partial differential "
                "equations are a vast subject (PF.U6 and beyond); this "
                "chapter is where you learn to read their alphabet."
            )),
            # ---------------------------------------------------------- 15
            (E, "Applied worked example: marginal products in a Cobb-Douglas firm", (
                "A firm's output follows the Cobb-Douglas model\n"
                "$$Q(K, L) = 60\\,K^{1/3} L^{2/3},$$\n"
                "with $K = 27$ units of capital and $L = 64$ of labor. Find "
                "current output, both marginal products, interpret them, and "
                "estimate the effect of trading one unit of labor for one of "
                "capital.\n\n"
                "STEP 1 — current output. $K^{1/3} = 27^{1/3} = 3$ and "
                "$L^{2/3} = 64^{2/3} = (64^{1/3})^2 = 16$, so "
                "$Q = 60 \\cdot 3 \\cdot 16 = 2880$.\n\n"
                "STEP 2 — marginal products (power rule per variable; the "
                "other factor is a frozen coefficient):\n"
                "$$Q_K = 20\\,K^{-2/3}L^{2/3}, \\qquad "
                "Q_L = 40\\,K^{1/3}L^{-1/3}.$$\n"
                "At $(27, 64)$: $Q_K = 20 \\cdot \\frac{1}{9} \\cdot 16 = "
                "\\frac{320}{9} \\approx 35.6$ and "
                "$Q_L = 40 \\cdot 3 \\cdot \\frac{1}{4} = 30$.\n\n"
                "STEP 3 — interpretation. One more unit of capital (labor "
                "held at 64) buys $\\approx 35.6$ extra units of output; one "
                "more unit of labor (capital held at 27) buys 30. Capital is "
                "currently the scarcer, more productive input. Diminishing "
                "returns is visible in the formulas: $Q_{LL} = "
                "-\\frac{40}{3}K^{1/3}L^{-4/3} < 0$ — each successive worker "
                "adds less than the last.\n\n"
                "STEP 4 — the trade, by linear approximation (tangent-plane "
                "preview): $\\Delta Q \\approx Q_K\\,\\Delta K + "
                "Q_L\\,\\Delta L = 35.6(+1) + 30(-1) \\approx +5.6$. Check "
                "against the exact value: $Q(28, 63) = 60 \\cdot 28^{1/3} "
                "\\cdot 63^{2/3} \\approx 2884.6$, a gain of $4.6$ — the "
                "one-step estimate is off by about one unit on a base of "
                "2880. Two partial derivatives priced a two-variable decision "
                "in one line; C305 turns this move into a theory.\n\n"
                "STEP 5 — a structural check (Euler's theorem for "
                "degree-one-homogeneous functions): $K\\,Q_K + L\\,Q_L = "
                "27 \\cdot \\frac{320}{9} + 64 \\cdot 30 = 960 + 1920 = 2880 "
                "= Q$. Paying each input its marginal product exactly "
                "exhausts output — a famous economics fact, and a free sanity "
                "check on your partials."
            )),
            # ---------------------------------------------------------- 16
            (L, "Connections: where this chapter plugs into everything else", (
                "BACKWARD (what this rested on): C101/C105 supplied the limit "
                "definition that page 4 recycled slice-by-slice; C105-C110 "
                "supplied every differentiation rule, reused verbatim on the "
                "live variable; C301 supplied functions of several variables "
                "and the surface picture that made 'slice' meaningful.\n\n"
                "FORWARD, immediately:\n"
                "• C305 (tangent planes and differentiability): the two slopes "
                "$f_x, f_y$ become the coefficients of the tangent plane "
                "$z = f(a,b) + f_x(a,b)(x-a) + f_y(a,b)(y-b)$, and "
                "'differentiable' gets its honest multivariable definition — "
                "the one that pages 10-11 showed mere existence of partials "
                "cannot deliver.\n"
                "• C306 (the multivariable chain rule): when $x$ and $y$ "
                "themselves depend on $t$ or on other variables, the partials "
                "become the gears of the machine: $\\frac{dz}{dt} = "
                "f_x \\frac{dx}{dt} + f_y \\frac{dy}{dt}$.\n"
                "• C307 (directional derivatives and the gradient): the "
                "vector $\\nabla f = \\langle f_x, f_y \\rangle$ packages the "
                "axis rates and then, remarkably, answers EVERY direction: "
                "$D_{\\mathbf{u}} f = \\nabla f \\cdot \\mathbf{u}$. Partials "
                "are the components of the compass.\n"
                "• C308 (optimization): interior extrema hide where "
                "$f_x = f_y = 0$; the second-derivative test runs on the "
                "Hessian of second partials via $D = f_{xx}f_{yy} - "
                "f_{xy}^2$ — Clairaut's symmetry working quietly in the "
                "background.\n\n"
                "FORWARD, further out: the rest of the C301-C316 multivariable "
                "track leans on partials continuously — Lagrange multipliers, "
                "multiple integrals (where iterated integration mirrors "
                "iterated differentiation), and the vector-calculus operators "
                "div and curl, which are nothing but organized bundles of "
                "partials. In the physics-foundations units, PF.U3 runs on "
                "held-variable thermodynamic partials like "
                "$(\\partial U/\\partial T)_V$ (page 14's notation, used "
                "daily), and PF.U6 lives inside the heat and wave equations. "
                "And REALAN re-derives this whole chapter rigorously: exact "
                "hypotheses for Clairaut, and the derivative-as-linear-map "
                "viewpoint previewed on page 17."
            )),
            # ---------------------------------------------------------- 17
            (L, "Going deeper: when hypotheses bite, and the modern view", (
                "CLAIRAUT WITHOUT CONTINUITY: THE CLASSIC COUNTEREXAMPLE. "
                "Define $g(0,0) = 0$ and, elsewhere,\n"
                "$$g(x, y) = \\frac{xy\\,(x^2 - y^2)}{x^2 + y^2}.$$\n"
                "Compute $g_x$ along the $y$-axis from the definition: for "
                "fixed $y \\ne 0$,\n"
                "$$g_x(0, y) = \\lim_{h \\to 0} \\frac{g(h, y)}{h} = "
                "\\lim_{h \\to 0} \\frac{y\\,(h^2 - y^2)}{h^2 + y^2} = "
                "\\frac{y \\cdot (-y^2)}{y^2} = -y.$$\n"
                "So $g_x(0, y) = -y$, and differentiating in $y$: "
                "$g_{xy}(0,0) = -1$. But $g$ is antisymmetric under swapping "
                "$x \\leftrightarrow y$ (check: $g(y,x) = -g(x,y)$), so the "
                "mirror computation gives $g_y(x, 0) = x$ and "
                "$g_{yx}(0,0) = +1$. The two mixed partials EXIST and "
                "DISAGREE: $-1 \\ne +1$. No contradiction with Clairaut — the "
                "mixed partials are discontinuous at the origin, so the "
                "theorem's hypothesis fails, and with it the conclusion. "
                "Theorems keep their promises only when you keep their "
                "hypotheses.\n\n"
                "PARTIALS EXIST $\\ne$ DIFFERENTIABLE. Page 11's "
                "$f = \\frac{xy}{x^2+y^2}$ (patched at the origin) has both "
                "partials AT EVERY POINT OF THE PLANE, yet is not even "
                "continuous at $(0,0)$. Two axis probes cannot certify a "
                "two-dimensional limit.\n\n"
                "THE MODERN VIEW: THE DERIVATIVE AS A LINEAR MAP. The mature "
                "definition says $f$ is differentiable at $\\mathbf{a}$ if "
                "there is a LINEAR MAP $Df(\\mathbf{a})$ with\n"
                "$$f(\\mathbf{a} + \\mathbf{h}) = f(\\mathbf{a}) + "
                "Df(\\mathbf{a})\\,\\mathbf{h} + o(\\|\\mathbf{h}\\|),$$\n"
                "an approximation that is good in EVERY direction "
                "simultaneously — not just along the axes. The partials are "
                "then simply the matrix entries of $Df$ (the Jacobian), read "
                "off along the axis directions. This untangles the whole "
                "chapter: partials existing means the matrix CAN be written "
                "down; differentiability means the matrix actually DOES its "
                "approximating job. The bridge theorem — if the partials "
                "exist and are continuous near $\\mathbf{a}$, then $f$ is "
                "differentiable at $\\mathbf{a}$ — is why the smooth functions "
                "of practice never misbehave. REALAN proves it, and proves "
                "Clairaut, from first principles."
            )),
            # ---------------------------------------------------------- 18
            (L, "Summary and reference sheet", (
                "THE CONCEPT. $f_x$ = rate of change of $f$ in the "
                "$x$-direction with ALL other variables frozen; geometrically, "
                "the slope of the slice curve $z = f(x, b)$ cut by the plane "
                "$y = b$.\n\n"
                "DEFINITIONS.\n"
                "$$f_x(a,b) = \\lim_{h \\to 0} \\frac{f(a+h, b) - f(a,b)}{h}, "
                "\\qquad f_y(a,b) = \\lim_{k \\to 0} \\frac{f(a, b+k) - "
                "f(a,b)}{k}.$$\n\n"
                "NOTATION. $f_x = \\frac{\\partial f}{\\partial x} = "
                "\\partial_x f = D_x f$. Subscripts read left-to-right "
                "($f_{xy}$: $x$ first); Leibniz reads right-to-left "
                "($\\frac{\\partial^2 f}{\\partial y \\partial x}$: $x$ "
                "first). Those two expressions are the SAME derivative. "
                "Held variables may appear as subscripts in applied work: "
                "$(\\partial U/\\partial T)_V$.\n\n"
                "COMPUTATION. Name the live variable; every other variable is "
                "a constant; then apply the ordinary rules. Product rule only "
                "when BOTH factors contain the live variable. Chain rule "
                "inner derivatives must be recomputed per variable. You may "
                "substitute frozen values before differentiating, never the "
                "live one.\n\n"
                "HIGHER ORDER. Four second partials: $f_{xx}, f_{xy}, "
                "f_{yx}, f_{yy}$. CLAIRAUT: $f_{xy} = f_{yx}$ wherever both "
                "are continuous; the $\\frac{xy(x^2-y^2)}{x^2+y^2}$ "
                "counterexample ($-1$ vs $+1$ at the origin) shows the "
                "hypothesis is real. For smooth $f$, only the COUNT of each "
                "variable matters in any mixed partial.\n\n"
                "THE FINE PRINT. Existence of partials does NOT imply "
                "continuity or differentiability ($\\frac{xy}{x^2+y^2}$). "
                "CONTINUOUS partials near a point DO imply differentiability "
                "there. At hand-patched points, compute by the limit "
                "definition — rules only differentiate formulas where the "
                "formulas hold.\n\n"
                "KEY FORMS. Tangent plane (C305 preview): $z = f(a,b) + "
                "f_x(a,b)(x-a) + f_y(a,b)(y-b)$. Gradient (C307 preview): "
                "$\\nabla f = \\langle f_x, f_y \\rangle$. PDE alphabet: heat "
                "$u_t = \\alpha u_{xx}$; wave $u_{tt} = c^2 u_{xx}$; Laplace "
                "$u_{xx} + u_{yy} = 0$.\n\n"
                "WORKFLOW. (1) Identify the live variable. (2) Rewrite so "
                "frozen variables form coefficients. (3) Differentiate with "
                "the ordinary rules. (4) For mixed partials, track the order "
                "from the notation. (5) At patched points, use the "
                "definition. (6) Sanity-check mixed partials by computing "
                "both orders."
            )),
            # ---------------------------------------------------------- 19
            (K, "Self-test (with worked solutions)", (
                "Attempt all eight before reading the solutions.\n\n"
                "1. $f(x,y) = x^4y^3 - 2xy + 5$: find $f_x$ and $f_y$.\n"
                "2. $f(x,y) = e^{x^2 y}$: find $f_x$ and $f_y$.\n"
                "3. $g(x,y) = \\frac{x}{y^2 + 1}$: find $g_x$ and $g_y$.\n"
                "4. Verify Clairaut for $f(x,y) = x\\sin y + y^2 e^x$ by "
                "computing $f_{xy}$ and $f_{yx}$ separately.\n"
                "5. $w = xy + yz^2 + xz$: find $w_x$, $w_y$, $w_z$.\n"
                "6. Show that $u(x,t) = e^{-t}\\sin x$ satisfies the heat "
                "equation $u_t = u_{xx}$.\n"
                "7. True or false: if $f_x(a,b)$ and $f_y(a,b)$ both exist, "
                "then $f$ is continuous at $(a,b)$.\n"
                "8. For $f(x,y) = x^2 + 3xy$, compute $f_x(1, 2)$ from the "
                "LIMIT DEFINITION, then check with the rules.\n\n"
                "SOLUTIONS.\n"
                "1. $f_x = 4x^3y^3 - 2y$; $f_y = 3x^4y^2 - 2x$. (The constant "
                "5 dies both times.)\n"
                "2. Chain rule, inner function $x^2y$: $f_x = 2xy\\,e^{x^2y}$ "
                "(inner $x$-derivative $2xy$); $f_y = x^2 e^{x^2y}$ (inner "
                "$y$-derivative $x^2$ — not $2xy$ again!).\n"
                "3. In $x$ the function is linear: $g_x = \\frac{1}{y^2+1}$. "
                "In $y$, write $g = x\\,(y^2+1)^{-1}$: $g_y = "
                "-x\\,(y^2+1)^{-2} \\cdot 2y = \\frac{-2xy}{(y^2+1)^2}$.\n"
                "4. $f_x = \\sin y + y^2 e^x$, so $f_{xy} = \\cos y + "
                "2y e^x$. $f_y = x\\cos y + 2y e^x$, so $f_{yx} = \\cos y + "
                "2y e^x$. Equal, as Clairaut promises for this smooth $f$.\n"
                "5. $w_x = y + z$; $w_y = x + z^2$; $w_z = 2yz + x$. (Each "
                "term contributes only when it contains the live variable.)\n"
                "6. $u_t = -e^{-t}\\sin x$; $u_x = e^{-t}\\cos x$, "
                "$u_{xx} = -e^{-t}\\sin x$. They match: a decaying sine wave "
                "is a solution of the heat equation.\n"
                "7. FALSE. $f = \\frac{xy}{x^2+y^2}$ with $f(0,0) = 0$: both "
                "partials exist at the origin (both are 0) but along $y = x$ "
                "the function sits at $\\frac12$, so it is not continuous "
                "there (page 11).\n"
                "8. $f_x(1,2) = \\lim_{h\\to 0}\\frac{f(1+h, 2) - f(1,2)}{h} "
                "= \\lim_{h\\to 0}\\frac{(1+h)^2 + 6(1+h) - 7}{h} = "
                "\\lim_{h\\to 0}\\frac{8h + h^2}{h} = 8$. Rule check: "
                "$f_x = 2x + 3y = 2 + 6 = 8$. ✓\n\n"
                "Scoring guide: 8/8 — proceed with confidence. 6-7 — reread "
                "the pages matching your misses (chain-rule slips → pages 9 "
                "and 13; existence-vs-continuity → pages 10-11). ≤5 — rework "
                "pages 3-9 before practicing."
            )),
            # ---------------------------------------------------------- 20
            (K, "Mastery checklist", (
                "Before leaving this chapter you should be able to check every "
                "box honestly:\n\n"
                "□ Explain what $f_x(a,b)$ means three ways: frozen-variable "
                "rate, slope of the $y = b$ slice curve, and the limit "
                "$\\lim_{h \\to 0} \\frac{f(a+h,b) - f(a,b)}{h}$.\n"
                "□ Compute first partials of any function built from powers, "
                "exponentials, logs, and trig — choosing product, quotient, "
                "and chain rules per variable correctly.\n"
                "□ Handle three or more variables with the same one-live-"
                "variable ritual.\n"
                "□ Compute all four second partials, and verify "
                "$f_{xy} = f_{yx}$ as a built-in error check.\n"
                "□ State Clairaut's theorem WITH its continuity hypothesis, "
                "and name the $\\frac{xy(x^2-y^2)}{x^2+y^2}$ counterexample "
                "where the mixed partials disagree ($-1$ vs $+1$).\n"
                "□ Translate freely between $f_{xy}$ and "
                "$\\frac{\\partial^2 f}{\\partial y\\,\\partial x}$, reading "
                "the order of differentiation correctly in each notation.\n"
                "□ Use the limit definition at hand-patched points where the "
                "shortcut rules do not apply.\n"
                "□ Explain why existence of partials does not imply "
                "continuity — and produce the $\\frac{xy}{x^2+y^2}$ "
                "counterexample with the line-by-line computation.\n"
                "□ Interpret partials in context: marginal products with the "
                "other input held fixed; why thermodynamics must write "
                "$(\\partial U/\\partial T)_V$ with the held variable "
                "explicit.\n"
                "□ Verify that a given function satisfies a PDE (heat, wave, "
                "or Laplace) by computing the required partials.\n"
                "□ Set up the linear-approximation estimate "
                "$\\Delta f \\approx f_x \\Delta x + f_y \\Delta y$ (page "
                "15's pattern).\n\n"
                "When every box is checked, hit Practice on this node until "
                "the bookkeeping is boring — fluency in 'who is alive?' pays "
                "off in every remaining chapter of the multivariable track. "
                "Then proceed to C305, where the two slopes you can now "
                "compute assemble into the tangent plane and "
                "differentiability gets its honest definition."
            )),
        ],
    },
}
