"""Full course: PS16 — Correlation and linear regression.

FC-template lesson (20 full pages) closing the probability-statistics
sequence: the correlation coefficient and its properties, the least-squares
line, R^2, residual diagnostics, regression to the mean, and the long war
between correlation and causation.
"""

L = "reading"
E = "example"
P = "pitfall"
K = "check"

LESSONS: dict[str, dict] = {
    "PS16": {
        "summary": (
            "A complete course on correlation and least-squares regression: what "
            "r measures and what it cannot see, fitting and interpreting the line, "
            "R^2 as variance explained, residual plots as the real diagnostic, "
            "regression to the mean, and why only experiments establish causation."
        ),
        "steps": [
            # ---------------------------------------------------------- 1
            (L, "Where you are and why this matters", (
                "Every chapter of this sequence so far has studied ONE variable at a "
                "time. PS05-PS10 built random variables and their distributions; PS12 "
                "summarized a single batch of data with a center and a spread; "
                "PS13-PS15 asked whether one mean or one proportion differs from a "
                "hypothesized value. But almost no interesting question in science, "
                "medicine, business, or policy is about one variable. The questions "
                "that matter are about RELATIONSHIPS: does more of this go with more "
                "of that, and by how much, and can we predict one from the other?\n\n"
                "This chapter introduces the two workhorse tools for exactly that, "
                "and they are arguably the most used — and most abused — tools in all "
                "of quantitative work. The CORRELATION COEFFICIENT $r$ compresses the "
                "strength and direction of a linear relationship into one unit-free "
                "number between $-1$ and $1$. The LEAST-SQUARES LINE turns that "
                "relationship into a prediction machine: give me an $x$, I return a "
                "$\\hat{y}$.\n\n"
                "They are also the tools most likely to make you say something false "
                "with a straight face. A single number cannot describe a cloud of "
                "points, and it will not warn you when it is lying. So this chapter "
                "carries an unusual amount of defensive equipment: Anscombe's "
                "quartet, residual plots, outlier influence, extrapolation, "
                "regression to the mean, and the oldest warning in statistics — "
                "correlation is not causation.\n\n"
                "You will learn: what $r$ measures and the four properties that make "
                "it well behaved; the three things it is structurally blind to; how "
                "to fit, interpret, and diagnose the line $\\hat{y} = a + bx$; why "
                "$R^2$ is variance explained and why a high $R^2$ proves almost "
                "nothing on its own; why the regression line is systematically "
                "shallower than the SD line, and what that has to do with tall "
                "fathers and slumping athletes.\n\n"
                "PS16 closes the probability-statistics sequence. It is where the "
                "whole apparatus — variance, sampling, inference — finally points at "
                "a scatterplot and says something useful."
            )),
            # ---------------------------------------------------------- 2
            (L, "Prerequisites check", (
                "Four things from earlier chapters get used on every page here.\n\n"
                "1. MEAN AND STANDARD DEVIATION (PS12, PS06). You must compute "
                "$\\bar{x} = \\frac{1}{n}\\sum x_i$ and the sample SD "
                "$s_x = \\sqrt{\\frac{1}{n-1}\\sum (x_i - \\bar{x})^2}$ without "
                "hesitation, and know that both are non-robust: one wild value moves "
                "them. That non-robustness is inherited by everything in this "
                "chapter.\n\n"
                "2. Z-SCORES (PS10). $z = \\frac{x - \\bar{x}}{s_x}$ converts a "
                "measurement into 'how many SDs above or below average.' Correlation "
                "is built entirely out of z-scores, so if standardizing still feels "
                "like a ritual rather than a translation, review it first.\n\n"
                "3. VARIANCE AS A BUDGET (PS06). Variance adds for independent "
                "pieces, and scales by $c^2$ under multiplication by $c$. The whole "
                "meaning of $R^2$ is a variance budget being split in two.\n\n"
                "4. LINES (algebra). Slope-intercept form $y = a + bx$; slope as "
                "'change in $y$ per unit change in $x$'; intercept as the height at "
                "$x = 0$. Nothing harder than that is required.\n\n"
                "Quick self-check (answers follow):\n\n"
                "• A student scores 82 on a test with mean 70, SD 6. Her z-score? "
                "($z = \\frac{82-70}{6} = 2$ — two SDs above average.)\n"
                "• If every $x_i$ is multiplied by 3, what happens to $s_x$? "
                "(It triples: SD scales linearly, variance by $9$.)\n"
                "• A line has slope $-4$ and passes through $(2, 11)$. Its "
                "intercept? ($11 = a - 8$, so $a = 19$; the line is "
                "$y = 19 - 4x$.)\n"
                "• Data: $2, 4, 9$. Mean and sample SD? (Mean $5$; deviations "
                "$-3, -1, 4$; sum of squares $26$; $s = \\sqrt{26/2} = "
                "\\sqrt{13} \\approx 3.61$.)\n\n"
                "If any of those stalled you, spend twenty minutes on PS12 and PS06 "
                "before continuing. Everything below is those ideas in two "
                "dimensions."
            )),
            # ---------------------------------------------------------- 3
            (L, "The core idea, intuitively", (
                "Start with a scatterplot: each subject contributes a dot at "
                "$(x_i, y_i)$. Now draw two lines through the cloud — a vertical "
                "line at $\\bar{x}$ and a horizontal line at $\\bar{y}$. Those lines "
                "cut the plot into four quadrants around the center of the data, and "
                "correlation is nothing more than a vote count over those "
                "quadrants.\n\n"
                "Translate every point into z-scores: $z_{x_i}$ says how many SDs "
                "right of center the point sits; $z_{y_i}$ how many SDs above. Now "
                "form the PRODUCT $z_{x_i} z_{y_i}$ for each point.\n\n"
                "• Upper-right quadrant (above average on both): positive times "
                "positive $= $ positive.\n"
                "• Lower-left (below average on both): negative times negative $= $ "
                "positive.\n"
                "• Upper-left and lower-right (above on one, below on the other): "
                "the product is NEGATIVE.\n\n"
                "So each point casts a vote. Points that agree ('high with high, low "
                "with low') vote positive; points that disagree vote negative. And "
                "the vote is WEIGHTED: a point that is 2 SDs out on both axes casts a "
                "vote of $4$, while a point sitting near the center casts a vote near "
                "$0$. Points far from the middle dominate — remember that, because it "
                "is the seed of the outlier problem on page 10.\n\n"
                "The correlation $r$ is the AVERAGE of those votes. If agreement "
                "dominates, $r > 0$. If disagreement dominates, $r < 0$. If the "
                "quadrants roughly cancel, $r \\approx 0$.\n\n"
                "Two consequences fall out immediately and for free. First, $r$ is "
                "SYMMETRIC — swapping the roles of $x$ and $y$ swaps the factors in "
                "each product, and multiplication does not care about order. Second, "
                "$r$ is UNIT-FREE, because z-scores already divided out the units: "
                "measure height in inches or centimeters and every z-score, hence "
                "$r$, is identical.\n\n"
                "And here is the built-in blind spot, visible already: the vote only "
                "asks 'same side or opposite side of center?' It has no vocabulary "
                "for 'curved.' A perfect U-shape puts equal weight in agreeing and "
                "disagreeing quadrants, and the votes cancel to zero — for a "
                "relationship with no noise at all."
            )),
            # ---------------------------------------------------------- 4
            (L, "The formal definitions", (
                "CORRELATION. For paired data $(x_1,y_1), \\ldots, (x_n,y_n)$, the "
                "sample correlation coefficient is the average product of z-scores:\n"
                "$$r = \\frac{1}{n-1} \\sum_{i=1}^{n} "
                "\\left(\\frac{x_i - \\bar{x}}{s_x}\\right)"
                "\\left(\\frac{y_i - \\bar{y}}{s_y}\\right).$$\n"
                "It is cleaner to compute with the three CENTERED SUMS\n"
                "$$S_{xx} = \\sum (x_i - \\bar{x})^2, \\quad "
                "S_{yy} = \\sum (y_i - \\bar{y})^2, \\quad "
                "S_{xy} = \\sum (x_i - \\bar{x})(y_i - \\bar{y}),$$\n"
                "in terms of which the $n-1$ factors cancel and\n"
                "$$r = \\frac{S_{xy}}{\\sqrt{S_{xx} S_{yy}}}.$$\n"
                "The numerator $\\frac{S_{xy}}{n-1}$ is the sample COVARIANCE "
                "$s_{xy}$; correlation is covariance with the units scrubbed out: "
                "$r = \\frac{s_{xy}}{s_x s_y}$. The population version replaces "
                "sums with expectations: $\\rho = "
                "\\frac{\\operatorname{Cov}(X,Y)}{\\sigma_X \\sigma_Y}$, and $r$ "
                "estimates $\\rho$ the way $\\bar{x}$ estimates $\\mu$.\n\n"
                "THE LEAST-SQUARES LINE. Among all lines $y = a + bx$, the "
                "regression line is the one minimizing the sum of squared VERTICAL "
                "distances from the data to the line:\n"
                "$$\\text{SSE}(a,b) = \\sum_{i=1}^{n} (y_i - a - b x_i)^2.$$\n"
                "The minimizing coefficients are\n"
                "$$b = r\\,\\frac{s_y}{s_x} = \\frac{S_{xy}}{S_{xx}}, \\qquad "
                "a = \\bar{y} - b\\bar{x},$$\n"
                "and the fitted value at $x$ is $\\hat{y} = a + bx$. The "
                "$i$-th RESIDUAL is $e_i = y_i - \\hat{y}_i$ — observed minus "
                "predicted, signed, in the units of $y$.\n\n"
                "Three definitional details carry real weight. (1) VERTICAL "
                "distances, not perpendicular ones: the line is built to predict "
                "$y$ FROM $x$, so error is measured in the $y$ direction only. That "
                "asymmetry is why swapping the roles gives a different line "
                "(page 10). (2) SQUARED errors, so big misses are punished "
                "quadratically — which is why one outlier can swing the fit. "
                "(3) The formula $b = r \\frac{s_y}{s_x}$ says the slope is the "
                "correlation, re-dressed in units: $r$ is the shape of the "
                "relationship, $\\frac{s_y}{s_x}$ the exchange rate between the "
                "two measuring sticks."
            )),
            # ---------------------------------------------------------- 5
            (E, "First worked examples", (
                "Five students; $x$ = hours of tutoring per week, $y$ = points "
                "gained on a practice exam.\n\n"
                "$x$: $1, 2, 3, 4, 5$   $y$: $8, 6, 10, 14, 12$\n\n"
                "STEP 1 — centers. $\\bar{x} = \\frac{15}{5} = 3$; "
                "$\\bar{y} = \\frac{50}{5} = 10$.\n\n"
                "STEP 2 — deviations, in a table.\n\n"
                "$x_i - \\bar{x}$: $-2, -1, 0, 1, 2$\n"
                "$y_i - \\bar{y}$: $-2, -4, 0, 4, 2$\n\n"
                "STEP 3 — the three sums.\n"
                "$S_{xx} = 4 + 1 + 0 + 1 + 4 = 10$.\n"
                "$S_{yy} = 4 + 16 + 0 + 16 + 4 = 40$.\n"
                "$S_{xy} = (-2)(-2) + (-1)(-4) + (0)(0) + (1)(4) + (2)(2) = "
                "4 + 4 + 0 + 4 + 4 = 16$.\n\n"
                "STEP 4 — correlation.\n"
                "$$r = \\frac{16}{\\sqrt{10 \\cdot 40}} = \\frac{16}{\\sqrt{400}} "
                "= \\frac{16}{20} = 0.8.$$\n"
                "Strong positive linear association. Note every nonzero product in "
                "Step 3 was positive — all four off-center points voted 'agree,' "
                "exactly the quadrant picture from page 3.\n\n"
                "STEP 5 — the SDs. $s_x = \\sqrt{10/4} = \\sqrt{2.5} \\approx "
                "1.581$; $s_y = \\sqrt{40/4} = \\sqrt{10} \\approx 3.162$. Their "
                "ratio is exactly $2$ (since $\\sqrt{10/2.5} = \\sqrt{4}$).\n\n"
                "STEP 6 — the line.\n"
                "$$b = r\\,\\frac{s_y}{s_x} = 0.8 \\times 2 = 1.6, \\qquad "
                "a = \\bar{y} - b\\bar{x} = 10 - 1.6(3) = 10 - 4.8 = 5.2.$$\n"
                "So $\\hat{y} = 5.2 + 1.6x$. Cross-check with the other formula: "
                "$b = \\frac{S_{xy}}{S_{xx}} = \\frac{16}{10} = 1.6$ ✓.\n\n"
                "STEP 7 — verify the line passes through the center. At "
                "$x = \\bar{x} = 3$: $\\hat{y} = 5.2 + 4.8 = 10 = \\bar{y}$ ✓. This "
                "check costs five seconds and catches most arithmetic slips.\n\n"
                "INTERPRET. Slope: each additional hour of tutoring is associated "
                "with $1.6$ more points gained, on average, over the observed range "
                "of 1 to 5 hours. Intercept: a student with zero tutoring is "
                "predicted to gain $5.2$ points — here a mild extrapolation "
                "($x = 0$ sits just outside the data), so treat it as a fitting "
                "constant, not a finding."
            )),
            # ---------------------------------------------------------- 6
            (L, "Main properties and theorems", (
                "P1. RANGE: $-1 \\le r \\le 1$. This is the Cauchy-Schwarz "
                "inequality, $|S_{xy}| \\le \\sqrt{S_{xx}S_{yy}}$, in disguise. "
                "Equality — $r = \\pm 1$ — holds if and only if the points lie "
                "EXACTLY on a line with nonzero slope, positive $r$ for upward, "
                "negative for downward.\n\n"
                "P2. SYMMETRY: $r(x,y) = r(y,x)$. Correlation has no notion of "
                "predictor and response. (Regression does — see P7.)\n\n"
                "P3. UNIT-FREE. Change inches to centimeters, dollars to euros, "
                "Celsius to Fahrenheit: $r$ does not move. Consequently $r$ has no "
                "units and cannot be read as a rate of change.\n\n"
                "P4. INVARIANCE UNDER LINEAR RESCALING: for constants with "
                "$c, d \\neq 0$,\n"
                "$$r(u + cx,\\; v + dy) = \\operatorname{sign}(cd)\\, r(x,y).$$\n"
                "Shifting does nothing (deviations are unchanged); positive scaling "
                "does nothing (the scale factors cancel between numerator and "
                "denominator); a NEGATIVE factor flips the sign, because reversing a "
                "measurement's direction reverses the direction of the association.\n\n"
                "P5. THE LINE PASSES THROUGH $(\\bar{x}, \\bar{y})$. Immediate from "
                "the intercept formula: $\\hat{y}(\\bar{x}) = a + b\\bar{x} = "
                "(\\bar{y} - b\\bar{x}) + b\\bar{x} = \\bar{y}$. The regression line "
                "is pinned to the center of the data and then tilted by $b$.\n\n"
                "P6. RESIDUALS SUM TO ZERO, and are uncorrelated with $x$: "
                "$\\sum e_i = 0$ and $\\sum x_i e_i = 0$. These are exactly the two "
                "first-order conditions from minimizing SSE, so they hold "
                "automatically for ANY dataset — which is why 'my residuals sum to "
                "zero' confirms your arithmetic, never your model.\n\n"
                "P7. THE VARIANCE DECOMPOSITION. Total variation splits cleanly:\n"
                "$$\\underbrace{\\sum (y_i - \\bar{y})^2}_{\\text{SST}} = "
                "\\underbrace{\\sum (\\hat{y}_i - \\bar{y})^2}_{\\text{SSR}} + "
                "\\underbrace{\\sum (y_i - \\hat{y}_i)^2}_{\\text{SSE}},$$\n"
                "and $R^2 = \\frac{\\text{SSR}}{\\text{SST}} = 1 - "
                "\\frac{\\text{SSE}}{\\text{SST}}$ is the FRACTION OF THE VARIANCE "
                "OF $y$ EXPLAINED by the line. For simple linear regression — one "
                "predictor — $R^2 = r^2$ exactly.\n\n"
                "P8. THE Z-SCORE FORM (the most illuminating identity in the "
                "chapter). Divide the line by $s_y$ and you get\n"
                "$$z_{\\hat{y}} = r \\cdot z_x.$$\n"
                "In standardized units the regression line is just 'multiply by "
                "$r$.' Since $|r| \\le 1$, the predicted $y$ is ALWAYS fewer SDs "
                "from its mean than $x$ is from its. That single line of algebra is "
                "regression to the mean, and page 9 cashes it out."
            )),
            # ---------------------------------------------------------- 7
            (E, "Worked examples: standard problems", (
                "EXAMPLE 1 (the line from summary statistics — the most common exam "
                "form). A realtor's data on 60 homes: $\\bar{x} = 1800$ sq ft, "
                "$s_x = 400$ sq ft, $\\bar{y} = 320$ (price, \\$ thousands), "
                "$s_y = 60$, $r = 0.75$. Find the line, predict for a 2000 sq ft "
                "home, and report $R^2$.\n\n"
                "$$b = r\\,\\frac{s_y}{s_x} = 0.75 \\times \\frac{60}{400} = "
                "0.75 \\times 0.15 = 0.1125,$$\n"
                "$$a = \\bar{y} - b\\bar{x} = 320 - 0.1125(1800) = 320 - 202.5 = "
                "117.5.$$\n"
                "So $\\hat{y} = 117.5 + 0.1125x$. Check the center: "
                "$117.5 + 0.1125(1800) = 320$ ✓.\n\n"
                "Prediction at $x = 2000$: $\\hat{y} = 117.5 + 225 = 342.5$, i.e. "
                "\\$342{,}500. $R^2 = 0.75^2 = 0.5625$: size accounts for about "
                "56% of the variance in price.\n\n"
                "INTERPRET IN UNITS. Slope $0.1125$ thousand dollars per square "
                "foot $= \\$112.50$ per additional square foot. Intercept $117.5$ "
                "would be the price of a ZERO-square-foot house — \\$117{,}500 for "
                "nothing. That is not a discovery about vacant lots; it is the "
                "line's height at an $x$ far outside the data. The intercept is "
                "frequently meaningless, and that is fine: it is a fitting "
                "constant, and only interpretable when $x = 0$ is both meaningful "
                "and near the data.\n\n"
                "EXAMPLE 2 (rescaling — testing P3 and P4). Redo Example 1 with "
                "price in DOLLARS rather than thousands. Now $\\bar{y} = 320{,}000$ "
                "and $s_y = 60{,}000$; $r$ is untouched at $0.75$ (P3). The slope "
                "becomes $b = 0.75 \\times \\frac{60{,}000}{400} = 112.5$ dollars "
                "per sq ft — the same physical fact wearing different units. $R^2$ "
                "is still $0.5625$. Lesson: $b$ has units and moves with them; $r$ "
                "and $R^2$ do not.\n\n"
                "EXAMPLE 3 (backing out $r$). A study reports $b = -1.2$ with "
                "$s_x = 4$ and $s_y = 10$. Then\n"
                "$$r = b\\,\\frac{s_x}{s_y} = -1.2 \\times \\frac{4}{10} = -0.48,$$\n"
                "so $R^2 = 0.2304$ — the predictor explains about 23% of the "
                "variance. Note the direction of the ratio: to go from $r$ to $b$ "
                "multiply by $\\frac{s_y}{s_x}$; to come back, multiply by "
                "$\\frac{s_x}{s_y}$. Getting this ratio upside down is error #2 on "
                "page 13."
            )),
            # ---------------------------------------------------------- 8
            (L, "Techniques and strategy", (
                "A reliable workflow, in the order that catches errors earliest.\n\n"
                "STEP 0 — PLOT FIRST. Always. Before $r$, before the line. The "
                "scatterplot answers questions no summary can: is it roughly "
                "linear? are there outliers? is the spread constant across $x$? are "
                "there clusters that should be analyzed separately? Page 11 shows "
                "four datasets with IDENTICAL $r$, $b$, $a$, and $R^2$ and utterly "
                "different pictures. Anyone who computed instead of plotting would "
                "have reported the same conclusion four times, and been wrong three "
                "times.\n\n"
                "STEP 1 — the three sums. Compute $\\bar{x}, \\bar{y}$, then "
                "$S_{xx}, S_{yy}, S_{xy}$. With small data, use deviations; with "
                "many values or a calculator, the algebraically equivalent "
                "computational forms are faster:\n"
                "$$S_{xx} = \\sum x_i^2 - n\\bar{x}^2, \\qquad "
                "S_{xy} = \\sum x_i y_i - n\\bar{x}\\bar{y}.$$\n"
                "(Careful: $\\sum x_i y_i$ is a sum of PRODUCTS, not the product of "
                "sums.) Every quantity in this chapter is a function of "
                "$n, \\bar{x}, \\bar{y}, S_{xx}, S_{yy}, S_{xy}$ — get those six "
                "right and the rest is bookkeeping.\n\n"
                "STEP 2 — $r$, then $b = \\frac{S_{xy}}{S_{xx}}$, then "
                "$a = \\bar{y} - b\\bar{x}$. Prefer $\\frac{S_{xy}}{S_{xx}}$ over "
                "$r\\frac{s_y}{s_x}$ when computing by hand: it avoids two square "
                "roots and the rounding they invite.\n\n"
                "STEP 3 — CHECK THE CENTER. Verify $a + b\\bar{x} = \\bar{y}$. Free, "
                "instant, catches sign and arithmetic slips.\n\n"
                "STEP 4 — RESIDUAL PLOT. Plot $e_i = y_i - \\hat{y}_i$ against "
                "$x_i$. This is THE diagnostic: it strips the slope out and "
                "rescales to the errors alone, so curvature invisible in a steep "
                "scatterplot becomes obvious.\n"
                "• PATTERNLESS CLOUD, centered on zero, even width — the linear "
                "model is adequate. The only good outcome.\n"
                "• CURVE (a U or arch) — nonlinear; the line is systematically "
                "wrong. Transform a variable or add a quadratic term; do not shrug "
                "at a high $R^2$.\n"
                "• FUNNEL (spread growing with $x$) — heteroscedasticity. The slope "
                "survives, but every standard error, interval, and p-value built on "
                "it is untrustworthy; a log transform of $y$ often repairs it.\n\n"
                "STEP 5 — INTERPRET IN CONTEXT, WITH UNITS, HEDGED. 'Each extra "
                "hour of tutoring is ASSOCIATED WITH 1.6 more points, on average, "
                "for students studying 1 to 5 hours.' Verb: associated. Qualifier: "
                "on average. Range: stated."
            )),
            # ---------------------------------------------------------- 9
            (E, "Worked examples: harder problems", (
                "EXAMPLE 1 (one point, enormous damage). Five points sit on a "
                "perfect line: $x = 1,2,3,4,5$, $y = 1,2,3,4,5$, so $r = 1$ and "
                "$\\hat{y} = x$. A sixth subject arrives — $(6, 0)$, a broken sensor "
                "or data-entry slip. Recompute: $n = 6$, $\\bar{x} = 3.5$, "
                "$\\bar{y} = 2.5$.\n"
                "$\\sum x^2 = 91 \\Rightarrow S_{xx} = 91 - 6(3.5)^2 = 17.5$.\n"
                "$\\sum y^2 = 55 \\Rightarrow S_{yy} = 55 - 6(2.5)^2 = 17.5$.\n"
                "$\\sum xy = 55 \\Rightarrow S_{xy} = 55 - 6(3.5)(2.5) = 2.5$.\n"
                "$$r = \\frac{2.5}{\\sqrt{17.5 \\times 17.5}} = \\frac{2.5}{17.5} "
                "= 0.143.$$\n"
                "From perfect to essentially nothing on the strength of ONE point "
                "in six. The line collapses with it: $b = \\frac{2.5}{17.5} = "
                "0.143$, $a = 2.5 - 0.143(3.5) = 2.0$, so $\\hat{y} = 2 + 0.143x$ — "
                "nearly flat, fitting none of the six well. The new point is extreme "
                "in $x$ AND disagrees in $y$: high LEVERAGE plus a large residual "
                "equals high INFLUENCE.\n\n"
                "EXAMPLE 2 (regression to the mean, quantified). Fathers and sons: "
                "both means $69$ in, both SDs $3$ in, $r = 0.5$. A $75$-inch father "
                "has $z_x = \\frac{75-69}{3} = +2$. By P8, $z_{\\hat{y}} = r z_x = "
                "1$, so $\\hat{y} = 69 + 1(3) = 72$ in — tall, but LESS extreme than "
                "his father (1 SD out, not 2).\n\n"
                "Now run it backwards. A $75$-inch son predicts, by the symmetric "
                "setup, $z_{\\hat{x}} = 0.5(2) = 1$: a $72$-inch father, also less "
                "extreme. Heights 'regress' in BOTH directions of time — so nothing "
                "is converging and the population SD does not shrink. Regression to "
                "the mean is IMPERFECT PREDICTION ($|r| < 1$), not a force: part of "
                "any extreme value is signal and part is luck, and luck does not "
                "repeat.\n\n"
                "EXAMPLE 3 (two lines, one dataset). Page 5's tutoring data "
                "($\\bar{x}=3, \\bar{y}=10, S_{xx}=10, S_{yy}=40, S_{xy}=16, "
                "r=0.8$). Predicting $y$ FROM $x$ (vertical errors): "
                "$b = \\frac{16}{10} = 1.6$, so $\\hat{y} = 5.2 + 1.6x$. Predicting "
                "$x$ FROM $y$ (horizontal errors): $b_{xy} = \\frac{S_{xy}}{S_{yy}} "
                "= \\frac{16}{40} = 0.4$, so $\\hat{x} = 0.4y - 1$; put on the same "
                "axes this reads $y = 2.5x + 2.5$ — slope $2.5$, not $1.6$. Two "
                "different lines, both correct. The SD LINE (slope "
                "$\\frac{s_y}{s_x} = 2$, i.e. $y = 2x + 4$) sits between them; the "
                "regression line is shallower by the factor $r$, and "
                "$b_{yx} b_{xy} = 1.6 \\times 0.4 = 0.64 = r^2$, so the two "
                "regressions coincide only at $|r| = 1$. 'The line through the "
                "data' is undefined until you say which variable you predict."
            )),
            # ---------------------------------------------------------- 10
            (L, "Special cases and edge behavior", (
                "$r = 0$ DOES NOT MEAN 'UNRELATED.' It means no LINEAR component. A "
                "perfect parabola centered on $\\bar{x}$ has $r = 0$ with zero "
                "noise: $y$ is deterministic in $x$, perfectly predictable, and $r$ "
                "reports nothing (page 11 computes one). Any symmetric "
                "relationship — U-shapes, circles, dose-response curves where too "
                "little and too much both hurt — is invisible. $r$ is a LINEARITY "
                "meter, not a relationship meter; this is the chapter's most "
                "important limitation.\n\n"
                "$r = \\pm 1$ EXACTLY means points on a perfect line. Real data "
                "rarely does this; when it does, suspect $y$ was computed FROM $x$ "
                "(C and F, price and price-plus-tax) rather than measured.\n\n"
                "$n = 2$. Two points always determine a line, so $r = \\pm 1$ "
                "ALWAYS, carrying zero information. Small $n$ makes $r$ wildly "
                "variable: at $n = 5$, an $r$ of $0.7$ is consistent with "
                "$\\rho = 0$ — which is why PS15's test for $\\rho = 0$ exists.\n\n"
                "ZERO VARIANCE. If every $x_i$ is identical, $S_{xx} = 0$ and $r$ is "
                "$\\frac{0}{0}$ — UNDEFINED, not zero. No direction to compare "
                "against, no line to fit.\n\n"
                "OUTLIERS AND LEVERAGE. Errors are squared and votes weighted by "
                "distance from center, so extreme points dominate. An outlier in "
                "$y$ near $\\bar{x}$ inflates SSE but barely tilts the line; a "
                "HIGH-LEVERAGE point (far out in $x$) acts on a long lever arm and "
                "drags the line to itself. Always ask: which points would move my "
                "conclusion if deleted?\n\n"
                "ANSCOMBE'S QUARTET. Four eleven-point datasets sharing "
                "$\\bar{x} = 9$, $\\bar{y} = 7.5$, $r = 0.816$, "
                "$\\hat{y} = 3.00 + 0.50x$, $R^2 = 0.67$ — identical to two decimals "
                "on every statistic in this chapter. Their pictures: (I) an honest "
                "linear cloud; (II) a perfect PARABOLA; (III) a line with ONE "
                "outlier; (IV) all $x$ identical but one point that creates the "
                "slope. Only (I) deserves a linear summary. Anscombe published these "
                "in 1973 to make 'plot your data' impossible to argue with.\n\n"
                "EXTRAPOLATION. The line is evidence only over the observed $x$ "
                "range. Page 5's tutoring line at $x = 40$ hours predicts $69.2$ "
                "points; the housing line at $x = 0$ pays \\$117{,}500 for nothing. "
                "Two quieter distorters: RANGE RESTRICTION (sampling a narrow slice "
                "of $x$ attenuates $r$ toward zero — the classic case is admission "
                "scores vs GPA among admitted students only) and AGGREGATION "
                "(correlating group averages inflates $r$, because averaging erases "
                "individual noise — an ecological $r$ of $0.9$ can be $0.2$ between "
                "people, and can even reverse sign)."
            )),
            # ---------------------------------------------------------- 11
            (E, "Worked example: edge cases", (
                "(a) A PERFECT RELATIONSHIP WITH $r = 0$. Take $y = x^2$ sampled "
                "symmetrically: $x = -2,-1,0,1,2$ and $y = 4,1,0,1,4$.\n\n"
                "$\\bar{x} = 0$, $\\bar{y} = \\frac{10}{5} = 2$. Deviations: "
                "$x$: $-2,-1,0,1,2$; $y$: $2,-1,-2,-1,2$.\n"
                "$$S_{xy} = (-2)(2) + (-1)(-1) + (0)(-2) + (1)(-1) + (2)(2) = "
                "-4 + 1 + 0 - 1 + 4 = 0.$$\n"
                "So $r = 0$ EXACTLY, hence $b = 0$, and the regression line is the "
                "flat line $\\hat{y} = \\bar{y} = 2$ with $R^2 = 0$. Yet $y$ is a "
                "PERFECT, noiseless function of $x$: knowing $x$ tells you $y$ with "
                "certainty. The tools report 'nothing here' about the most "
                "deterministic relationship possible. Read the votes to see why: "
                "the two left points agree, the two right points disagree, and they "
                "cancel exactly. A scatterplot shows the parabola in one glance.\n\n"
                "(b) $n = 2$ IS ALWAYS PERFECT. Points $(1, 5)$ and $(3, 5000)$. "
                "$\\bar{x} = 2$, $\\bar{y} = 2502.5$; deviations $\\mp 1$ and "
                "$\\mp 2497.5$; $S_{xy} = (-1)(-2497.5) + (1)(2497.5) = 4995$; "
                "$S_{xx} = 2$, $S_{yy} = 2 \\times 2497.5^2$. Then\n"
                "$$r = \\frac{4995}{\\sqrt{2 \\cdot 2 \\cdot 2497.5^2}} = "
                "\\frac{4995}{2 \\times 2497.5} = 1.$$\n"
                "Perfect correlation from two arbitrary points. A reported $r = 1$ "
                "with $n = 2$ is not evidence; it is arithmetic.\n\n"
                "(c) RANGE RESTRICTION, on real numbers. Page 5's data had "
                "$r = 0.8$ across $x = 1$ to $5$. Keep only the top of the range, "
                "$x = 3,4,5$ with $y = 10,14,12$. Now $\\bar{x} = 4$, "
                "$\\bar{y} = 12$; $x$-deviations $-1,0,1$ so $S_{xx} = 2$; "
                "$y$-deviations $-2,2,0$ so $S_{yy} = 8$; "
                "$S_{xy} = (-1)(-2) + 0(2) + (1)(0) = 2$. Then\n"
                "$$r = \\frac{2}{\\sqrt{2 \\cdot 8}} = \\frac{2}{4} = 0.5.$$\n"
                "The same underlying relationship, the same subjects, $r$ down from "
                "$0.8$ to $0.5$ — purely from narrowing the window on $x$. Nothing "
                "about the world changed; only the range did.\n\n"
                "(d) ANSCOMBE, CONCRETELY. All four sets: $n = 11$, $\\bar{x} = 9$, "
                "$s_x \\approx 3.32$, $\\bar{y} = 7.50$, $s_y \\approx 2.03$, "
                "$r \\approx 0.816$, $\\hat{y} = 3.00 + 0.50x$, "
                "$R^2 \\approx 0.67$. Dataset IV is the most alarming: its $x$ "
                "values are $8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8$. Ten points share a "
                "single $x$, so they cannot define any slope at all — the slope is "
                "manufactured entirely by the lone point at $x = 19$. Delete it and "
                "$r$ becomes undefined ($S_{xx} = 0$, case (b) of page 10). A "
                "conclusion resting on one observation, reported with the same "
                "$R^2 = 0.67$ as an honest linear fit.\n\n"
                "The through-line of all four: every statistic on this page was "
                "computed correctly, and every one of them misleads. The "
                "scatterplot is not decoration."
            )),
            # ---------------------------------------------------------- 12
            (P, "Common misconceptions", (
                "MISCONCEPTION 1: 'Correlation implies causation.' The famous one, "
                "still the most damaging. A strong $r$ between $X$ and $Y$ fits at "
                "least four worlds. (i) $X$ causes $Y$. (ii) REVERSE CAUSATION: $Y$ "
                "causes $X$ — hospitals correlate with deaths because sick people "
                "go to hospitals. (iii) CONFOUNDING: a third variable drives both — "
                "ice cream sales correlate with drownings because summer causes "
                "both; firefighters at a blaze correlate with damage because fire "
                "size causes both. (iv) COINCIDENCE: with enough variables some "
                "pair correlates at $0.9$ by luck, and any two rising time series "
                "correlate.\n\n"
                "What DOES establish causation? A RANDOMIZED EXPERIMENT. Assign "
                "treatment by a coin flip and it becomes, by construction, "
                "independent of every confounder — known, unknown, unmeasurable. "
                "Randomization does not remove confounders; it balances them in "
                "expectation across groups, so an outcome difference has nowhere "
                "else to come from. When randomizing is impossible (you cannot "
                "assign people to smoke), causal claims need far heavier machinery "
                "and stay contestable.\n\n"
                "MISCONCEPTION 2: '$r = 0$ means no relationship.' Page 11(a): a "
                "perfect noiseless parabola with $r = 0$. Say 'no LINEAR "
                "association' and you are safe.\n\n"
                "MISCONCEPTION 3: '$r$ measures steepness.' It does not. $r$ "
                "measures TIGHTNESS about a line; the slope $b$ measures steepness. "
                "A nearly flat but razor-thin cloud has $r \\approx 1$ with tiny "
                "$b$; a steep but fat cloud can have modest $r$. And since $r$ is "
                "invariant to rescaling while $b$ is not (Example 2, page 7), no "
                "unit-free number could possibly encode a rate.\n\n"
                "MISCONCEPTION 4: 'High $R^2$ means the model is right.' "
                "Anscombe II has $R^2 = 0.67$ on a perfect parabola. $R^2$ measures "
                "how much variance the line mops up, not whether a line was the "
                "right object. The residual plot answers the second question; "
                "$R^2$ cannot. Nor does high $R^2$ imply causation, good "
                "prediction on new data, or importance.\n\n"
                "MISCONCEPTION 5: 'Regression to the mean is a force.' It is not a "
                "mechanism; it is $|r| < 1$ (P8). Kahneman's flight instructors "
                "praised an exceptional landing and saw worse next time, criticized "
                "a terrible one and saw better — and concluded criticism works, "
                "praise backfires. Both sequences are exactly what imperfect "
                "correlation predicts with NO instructor effect. The same illusion "
                "sells turnarounds, sophomore slumps, and any treatment given to "
                "the worst-off cases.\n\n"
                "MISCONCEPTION 6: 'The regression line is symmetric like $r$ is.' "
                "Page 9, Example 3: $y$-on-$x$ and $x$-on-$y$ are different lines."
            )),
            # ---------------------------------------------------------- 13
            (P, "Common computational errors", (
                "ERROR 1: THE SD RATIO UPSIDE DOWN. $b = r\\frac{s_y}{s_x}$ — "
                "response SD on top. Check it with units: $b$ must come out in "
                "'units of $y$ per unit of $x$,' so $s_y$ must be in the numerator. "
                "In Example 1 on page 7, the correct $b$ is $0.1125$; flipping the "
                "ratio gives $5$, i.e. \\$5{,}000 of price per square foot — "
                "absurd on sight. Let the units audit you.\n\n"
                "ERROR 2: $a = \\bar{y} - b\\bar{x}$, NOT $\\bar{y} - b$, and not "
                "built from a raw data pair. The intercept formula exists precisely "
                "to force the line through $(\\bar{x}, \\bar{y})$ — which is also "
                "how you check it (page 8, Step 3).\n\n"
                "ERROR 3: LOSING THE SIGN OF $r$. Going from $R^2$ back to $r$ "
                "requires a square root, and $\\sqrt{0.64} = \\pm 0.8$. $R^2$ has "
                "thrown the direction away. Recover the sign from the SLOPE: $r$ "
                "and $b$ always share a sign, because $\\frac{s_y}{s_x} > 0$. "
                "Reporting $r = +0.8$ for a downward-sloping fit is a real and "
                "common blunder.\n\n"
                "ERROR 4: INCONSISTENT SD CONVENTIONS. $r$ is immune to the $n$ vs "
                "$n-1$ choice (factors cancel), but $b = r\\frac{s_y}{s_x}$ needs "
                "the SAME convention in $s_x$ and $s_y$; mixing them corrupts the "
                "slope by $\\sqrt{\\frac{n}{n-1}}$. Fix: compute "
                "$b = \\frac{S_{xy}}{S_{xx}}$ and sidestep it.\n\n"
                "ERROR 5: $\\sum x_i y_i \\neq (\\sum x_i)(\\sum y_i)$. The formula "
                "needs the sum of PRODUCTS, multiplied pair by pair. On page 5's "
                "data $\\sum x_i y_i = 8+12+30+56+60 = 166$, while "
                "$(\\sum x_i)(\\sum y_i) = 750$. Then $S_{xy} = 166 - 5(3)(10) = "
                "16$ ✓.\n\n"
                "ERROR 6: RESIDUAL SIGN REVERSED. $e_i = y_i - \\hat{y}_i$, "
                "OBSERVED minus PREDICTED; a positive residual means the line "
                "UNDER-predicted. Reverse it and every diagnostic inverts.\n\n"
                "ERROR 7: ROUNDING TOO EARLY. Rounding $r$, then computing $b$, "
                "then $a = \\bar{y} - b\\bar{x}$ multiplies the error by $\\bar{x}$ "
                "— which can be 1800. Carry full precision; round once, at the "
                "report.\n\n"
                "ERROR 8: INVERTING THE LINE TO PREDICT BACKWARDS. Given "
                "$\\hat{y} = 5.2 + 1.6x$ and asked to predict $x$ from a known $y$, "
                "students solve $x = \\frac{y - 5.2}{1.6}$. That is algebra, not "
                "statistics: it is the $y$-on-$x$ line read sideways, and it is NOT "
                "the least-squares predictor of $x$. The correct object is the "
                "$x$-on-$y$ regression, $b_{xy} = \\frac{S_{xy}}{S_{yy}}$ — a "
                "different line (page 9, Example 3).\n\n"
                "ERROR 9: COMPUTING BEFORE PLOTTING. Not arithmetic, but it costs "
                "more points, papers, and money than all the others combined."
            )),
            # ---------------------------------------------------------- 14
            (L, "Applications", (
                "1. CALIBRATION. Every measuring instrument is regressed into "
                "existence. Run known standards through a spectrophotometer, "
                "regress instrument reading on known concentration, and the fitted "
                "line converts future readings into concentrations. Here $R^2$ is "
                "genuinely expected above $0.999$, the residual plot detects "
                "detector saturation as a curve at high concentration, and the "
                "linear range is stated explicitly precisely to forbid "
                "extrapolation. This is regression at its most honest: a designed "
                "experiment where $x$ is set by the analyst, so causation is not in "
                "question.\n\n"
                "2. COST ACCOUNTING. Regress total cost on production volume and "
                "the line decomposes the business: the intercept estimates FIXED "
                "cost (rent, salaried staff), the slope estimates VARIABLE cost per "
                "unit (materials, hourly labor). This is one of the rare cases "
                "where the intercept is the point of the exercise. Page 15 works it "
                "end to end.\n\n"
                "3. FINANCE. A stock's BETA is literally the slope of the "
                "regression of the stock's returns on the market's returns — "
                "$\\beta = r \\frac{s_{\\text{stock}}}{s_{\\text{market}}}$, this "
                "chapter's formula wearing a Greek letter. $\\beta > 1$ means the "
                "stock amplifies market moves; $R^2$ says what fraction of the "
                "stock's variability is market-wide (systematic) versus "
                "company-specific.\n\n"
                "4. EPIDEMIOLOGY, AND THE LIMITS. Observational studies cannot "
                "randomize. The smoking-cancer case took decades to settle NOT "
                "because the correlation was weak, but because the confounding "
                "objection (a genetic factor causing both the habit and the "
                "disease — Fisher's own argument) had to be defeated without an "
                "experiment. It was, by dose response, temporal ordering, "
                "mechanism, and consistency across dozens of populations — the cost "
                "of doing without randomization.\n\n"
                "5. MACHINE LEARNING. Linear regression is the first model in every "
                "ML course, and no toy: it is the base case of supervised "
                "learning — a hypothesis class, a squared-error loss, an "
                "optimization, a held-out evaluation. $R^2$ becomes a test-set "
                "metric, residual analysis becomes error analysis, and more "
                "predictors turn the line into a hyperplane. Every misconception on "
                "page 12 survives into ML at scale, doing more damage per hour.\n\n"
                "6. SPORTS AND PERFORMANCE. Regression to the mean explains the "
                "sophomore slump, the cover jinx, and why the worst plant improves "
                "after the consultant visits. Any policy triggered by an EXTREME "
                "measurement looks effective for free; correcting for it needs a "
                "control group — an experiment."
            )),
            # ---------------------------------------------------------- 15
            (E, "Applied worked example: fixed and variable costs", (
                "A workshop records five months of output and total cost. $x$ = "
                "units produced (hundreds), $y$ = total cost (\\$ thousands).\n\n"
                "$x$: $2, 4, 6, 8, 10$   $y$: $14, 17, 22, 24, 28$\n\n"
                "QUESTION: split the cost structure into fixed and variable "
                "components, and forecast the cost of a 700-unit month.\n\n"
                "STEP 0 — plot. Five points marching up and to the right, tightly. "
                "A line is plausible.\n\n"
                "STEP 1 — centers and sums. $\\bar{x} = \\frac{30}{5} = 6$; "
                "$\\bar{y} = \\frac{105}{5} = 21$.\n"
                "$x$-deviations: $-4,-2,0,2,4$ so $S_{xx} = 16+4+0+4+16 = 40$.\n"
                "$y$-deviations: $-7,-4,1,3,7$ so $S_{yy} = 49+16+1+9+49 = 124$.\n"
                "$$S_{xy} = (-4)(-7) + (-2)(-4) + (0)(1) + (2)(3) + (4)(7) = "
                "28 + 8 + 0 + 6 + 28 = 70.$$\n\n"
                "STEP 2 — the line.\n"
                "$$b = \\frac{S_{xy}}{S_{xx}} = \\frac{70}{40} = 1.75, \\qquad "
                "a = 21 - 1.75(6) = 21 - 10.5 = 10.5.$$\n"
                "$\\hat{y} = 10.5 + 1.75x$. Center check: $10.5 + 1.75(6) = 21 = "
                "\\bar{y}$ ✓.\n\n"
                "STEP 3 — correlation and $R^2$.\n"
                "$$r = \\frac{70}{\\sqrt{40 \\times 124}} = \\frac{70}{\\sqrt{4960}} "
                "= \\frac{70}{70.43} = 0.994, \\qquad R^2 = 0.988.$$\n\n"
                "STEP 4 — residuals. Fitted values: $14.0, 17.5, 21.0, 24.5, 28.0$. "
                "Residuals: $0, -0.5, +1.0, -0.5, 0$. They sum to zero ✓ (P6), and "
                "$\\text{SSE} = 0 + 0.25 + 1 + 0.25 + 0 = 1.5$. Confirm $R^2$ the "
                "other way: $1 - \\frac{1.5}{124} = 0.988$ ✓ — matching $r^2$ as "
                "P7 promises.\n\n"
                "STEP 5 — INTERPRET IN BUSINESS UNITS. Slope $1.75$ thousand per "
                "hundred units $= \\$17.50$ of VARIABLE cost per unit (materials, "
                "hourly labor). Intercept $10.5$ is \\$10{,}500 of FIXED cost per "
                "month (rent, salaries, insurance) — the cost at zero output. "
                "Unusually, this intercept IS worth interpreting: $x = 0$ is a "
                "coherent scenario (a shutdown month), unlike the zero-square-foot "
                "house on page 7. But it is still extrapolation — the data runs 200 "
                "to 1000 units, and a truly idle month might shed some 'fixed' "
                "costs — so report it as fixed cost UNDER NORMAL OPERATION.\n\n"
                "STEP 6 — the forecast. 700 units is $x = 7$: "
                "$\\hat{y} = 10.5 + 1.75(7) = 22.75$, about \\$22{,}750. Legitimate, "
                "since $7$ is inside the range. A forecast at $x = 50$ would give "
                "\\$98{,}000 and be worthless: beyond capacity the workshop adds a "
                "shift or a machine and the cost curve jumps.\n\n"
                "STEP 7 — the honest caveat. $R^2 = 0.988$ is excellent, but the "
                "residuals $0, -0.5, +1.0, -0.5, 0$ form a faint ARCH — middle "
                "above the line, shoulders below. With $n = 5$ that is far too "
                "little to call curvature, and the misses are at most \\$1{,}000 "
                "against costs near \\$21{,}000. But it is the shape to watch as "
                "data accumulates: real economies of scale would bend this curve. "
                "The discipline: even at near-perfect $R^2$, read the residuals."
            )),
            # ---------------------------------------------------------- 16
            (L, "Connections to the rest of the curriculum", (
                "BACKWARD (what this rested on):\n"
                "• PS06 (variance and SD). The scaling rules explain why $r$ is "
                "unit-free and why $b$ is not, and the variance-as-a-budget idea IS "
                "$R^2$: $\\text{SST} = \\text{SSR} + \\text{SSE}$ is a variance "
                "decomposition, the same accounting that made variances add.\n"
                "• PS12 (descriptive statistics). $r$ and $b$ are built from means "
                "and SDs, so they inherit their fragility. PS12 taught that the "
                "mean is dragged by outliers while the median is not; page 9's "
                "collapse from $r = 1$ to $r = 0.143$ is that same lesson in two "
                "dimensions, and it motivates robust alternatives (page 17).\n\n"
                "FORWARD, and this is where regression becomes INFERENCE:\n"
                "• PS13 (sampling distributions, standard error). Your fitted slope "
                "$b$ is a statistic computed from one sample — a random variable "
                "with its own sampling distribution and its own standard error, "
                "$SE(b) = \\frac{s_e}{\\sqrt{S_{xx}}}$. Notice what that says: "
                "spreading your $x$ values out (bigger $S_{xx}$) buys precision, "
                "which is how experiments get designed.\n"
                "• PS14 (confidence intervals). $b \\pm t^* SE(b)$ is a confidence "
                "interval for the TRUE slope $\\beta$ — the honest way to report a "
                "regression, since a slope with no interval is a point estimate "
                "pretending to be a fact.\n"
                "• PS15 (hypothesis testing). 'Is there a real linear "
                "relationship?' is the test of $H_0: \\beta = 0$ using "
                "$t = \\frac{b}{SE(b)}$ — distance from the null in SE units, "
                "PS15's whole idea applied here. The equivalent test of "
                "$H_0: \\rho = 0$ answers the $n = 2$ worry from page 10: it is "
                "exactly the machinery that tells you whether an $r$ is more than "
                "small-sample noise.\n\n"
                "SIDEWAYS, into other tracks:\n"
                "• C115 (optimization). Least squares is a calculus max-min "
                "problem: minimize $\\text{SSE}(a,b) = \\sum (y_i - a - bx_i)^2$ by "
                "setting both partial derivatives to zero. The two resulting NORMAL "
                "EQUATIONS produce exactly $b = \\frac{S_{xy}}{S_{xx}}$ and "
                "$a = \\bar{y} - b\\bar{x}$ — and $\\sum e_i = 0$, "
                "$\\sum x_i e_i = 0$ from P6 ARE those derivatives.\n"
                "• LA.U8.N2 (projection and least squares) — the deepest "
                "connection. Stack the data into $\\mathbf{y} \\in \\mathbb{R}^n$ "
                "and a design matrix $A$ with columns $\\mathbf{1}$ and "
                "$\\mathbf{x}$. The fitted vector $\\hat{\\mathbf{y}}$ is the "
                "ORTHOGONAL PROJECTION of $\\mathbf{y}$ onto the column space of "
                "$A$, and the coefficients solve $A^{T}A\\mathbf{v} = "
                "A^{T}\\mathbf{y}$. The residual is perpendicular to that plane — "
                "P6 as geometry — making $\\text{SST} = \\text{SSR} + \\text{SSE}$ "
                "the PYTHAGOREAN THEOREM, and $r$ the cosine of the angle between "
                "the centered data vectors (page 17).\n\n"
                "Multiple regression is just this projection with more columns in "
                "$A$. Once you see regression as projection, the subject is linear "
                "algebra."
            )),
            # ---------------------------------------------------------- 17
            (L, "Going deeper", (
                "WHY 'REGRESSION' IS A STRANGE NAME — a historical accident. Francis "
                "Galton, studying heredity in the 1880s, saw that tall fathers had "
                "tall-but-less-tall sons and short fathers short-but-less-short "
                "ones. He published this in 1886 as 'Regression towards mediocrity "
                "in hereditary stature,' believing he had found a biological force "
                "pulling the species toward average. He had not — he had found "
                "$|r| < 1$, page 9's Example 2 exactly, time-symmetry and all, which "
                "his biological reading cannot survive. Karl Pearson formalized the "
                "coefficient (hence 'Pearson's $r$'), and a field ended up named for "
                "a misread phenomenon that had no mechanism.\n\n"
                "WHY $|r| \\le 1$: THE GEOMETRY. Center the data into vectors "
                "$\\mathbf{u} = (x_i - \\bar{x})$ and $\\mathbf{v} = "
                "(y_i - \\bar{y})$ in $\\mathbb{R}^n$. Then\n"
                "$$r = \\frac{S_{xy}}{\\sqrt{S_{xx}S_{yy}}} = "
                "\\frac{\\langle \\mathbf{u}, \\mathbf{v} \\rangle}"
                "{\\|\\mathbf{u}\\|\\,\\|\\mathbf{v}\\|} = \\cos\\theta,$$\n"
                "where $\\theta$ is the ANGLE between them. Every property in this "
                "chapter becomes geometry: $|r| \\le 1$ is just "
                "$|\\cos\\theta| \\le 1$ (Cauchy-Schwarz); $r = \\pm 1$ means the "
                "vectors are parallel or antiparallel; $r = 0$ means PERPENDICULAR; "
                "unit-invariance holds because scaling a vector does not change its "
                "direction. Page 5's data: $\\mathbf{u} = (-2,-1,0,1,2)$, "
                "$\\mathbf{v} = (-2,-4,0,4,2)$, inner product $16$, norms "
                "$\\sqrt{10}$ and $\\sqrt{40}$, so $\\cos\\theta = "
                "\\frac{16}{20} = 0.8$ and $\\theta \\approx 36.9°$. Correlation is "
                "an angle.\n\n"
                "BEYOND PEARSON. Because $r$ sees only lines, alternatives exist. "
                "SPEARMAN's rank correlation applies Pearson's formula to the "
                "RANKS, catching any monotone relationship and shrugging off "
                "outliers; Kendall's tau counts concordant pairs. DISTANCE "
                "CORRELATION and MUTUAL INFORMATION are zero if and only if the "
                "variables are truly independent — they would flag page 11's "
                "parabola instantly, where Pearson reports $0$.\n\n"
                "THE CAUSATION FRONTIER. 'Correlation is not causation' is where "
                "most courses stop and modern statistics starts. Fisher gave us "
                "randomization in the 1920s, still the gold standard. When you "
                "cannot randomize, a toolkit approximates it: NATURAL EXPERIMENTS "
                "exploit accidents that assign treatment as-if randomly; "
                "INSTRUMENTAL VARIABLES use something that moves the treatment but "
                "touches the outcome only through it; REGRESSION DISCONTINUITY "
                "compares subjects just above and below a cutoff. Judea Pearl's "
                "causal graphs let you read off which variables to adjust for — and "
                "which to LEAVE ALONE, since controlling for a variable on the "
                "causal path, or for a common effect (collider), manufactures bias. "
                "'Just add more controls' is not a strategy. Witness SIMPSON'S "
                "PARADOX: every subgroup can show a positive association while the "
                "pooled data shows a negative one, and which answer is right depends "
                "on causal structure — a question no correlation can settle."
            )),
            # ---------------------------------------------------------- 18
            (L, "Summary and formula sheet", (
                "CORRELATION.\n"
                "$$r = \\frac{1}{n-1}\\sum z_{x_i} z_{y_i} = "
                "\\frac{S_{xy}}{\\sqrt{S_{xx}S_{yy}}} = \\frac{s_{xy}}{s_x s_y} = "
                "\\cos\\theta.$$\n"
                "Measures the strength and direction of LINEAR association. "
                "$-1 \\le r \\le 1$. Symmetric, unit-free, invariant under "
                "rescaling (sign flips if exactly one variable is negated). Blind "
                "to curvature; dragged by outliers.\n\n"
                "THE THREE SUMS.\n"
                "$$S_{xx} = \\sum x_i^2 - n\\bar{x}^2, \\quad "
                "S_{yy} = \\sum y_i^2 - n\\bar{y}^2, \\quad "
                "S_{xy} = \\sum x_i y_i - n\\bar{x}\\bar{y}.$$\n\n"
                "THE LEAST-SQUARES LINE. Minimizes $\\sum (y_i - \\hat{y}_i)^2$ "
                "(VERTICAL errors):\n"
                "$$\\hat{y} = a + bx, \\qquad b = r\\,\\frac{s_y}{s_x} = "
                "\\frac{S_{xy}}{S_{xx}}, \\qquad a = \\bar{y} - b\\bar{x}.$$\n"
                "Always passes through $(\\bar{x}, \\bar{y})$. Residuals "
                "$e_i = y_i - \\hat{y}_i$ satisfy $\\sum e_i = 0$ and "
                "$\\sum x_i e_i = 0$ automatically. In standardized units: "
                "$z_{\\hat{y}} = r z_x$.\n\n"
                "INTERPRETATION. $b$: predicted change in $y$ per ONE-UNIT increase "
                "in $x$, on average, within the observed range. $a$: predicted $y$ "
                "at $x = 0$ — meaningful only if $x = 0$ is both sensible and near "
                "the data.\n\n"
                "VARIANCE EXPLAINED.\n"
                "$$\\text{SST} = \\text{SSR} + \\text{SSE}, \\qquad "
                "R^2 = \\frac{\\text{SSR}}{\\text{SST}} = "
                "1 - \\frac{\\text{SSE}}{\\text{SST}} = r^2 \\;"
                "(\\text{simple regression only}).$$\n\n"
                "RESIDUAL PLOT — THE DIAGNOSTIC. Patternless cloud → linear model "
                "adequate. Curve/arch → nonlinear; fix the model. Funnel → "
                "non-constant variance; inference is untrustworthy. A high $R^2$ "
                "does not excuse you from looking.\n\n"
                "THE FIVE TRAPS.\n"
                "1. $r = 0$ means no LINEAR association (perfect parabola: $r=0$).\n"
                "2. Outliers steer both $r$ and the line; high leverage = far out "
                "in $x$.\n"
                "3. Extrapolation beyond the $x$-range is unsupported by anything.\n"
                "4. $y$-on-$x$ $\\ne$ $x$-on-$y$; both are shallower than the SD "
                "line (slope $\\frac{s_y}{s_x}$) by the factor $r$ — which IS "
                "regression to the mean, a consequence of $|r| < 1$ and not a "
                "force.\n"
                "5. Correlation is not causation: confounding, reverse causation, "
                "coincidence. Only a RANDOMIZED EXPERIMENT balances unknown "
                "confounders by construction.\n\n"
                "WORKFLOW. Plot → three sums → $r$ → $b$, $a$ → check "
                "$(\\bar{x},\\bar{y})$ → residual plot → interpret with units, the "
                "word 'associated,' and the range stated."
            )),
            # ---------------------------------------------------------- 19
            (K, "Self-test (with worked solutions)", (
                "Attempt all eight before reading the solutions.\n\n"
                "1. Given $\\bar{x} = 20$, $s_x = 5$, $\\bar{y} = 100$, "
                "$s_y = 15$, $r = -0.6$, find the regression line.\n"
                "2. Report and interpret $R^2$ for that fit.\n"
                "3. Predict $y$ at $x = 25$. Would $x = 60$ be legitimate if the "
                "data ran from 10 to 30?\n"
                "4. In problem 1, $x$ is re-expressed in a unit ten times larger "
                "(so each value is divided by 10). What happens to $r$ and to $b$?\n"
                "5. True or false: $r = 0$ implies $x$ and $y$ are unrelated.\n"
                "6. A fit has $R^2 = 0.90$, but the residual plot is a clean U. "
                "What do you conclude?\n"
                "7. Fathers and sons: means $69$ in, SDs $3$ in, $r = 0.5$. Predict "
                "the son of a $75$-inch father. Does this mean humanity is "
                "converging on average height?\n"
                "8. A dataset has $S_{xx} = 50$, $S_{yy} = 200$, $S_{xy} = -60$. "
                "Find $r$ and $b$.\n\n"
                "SOLUTIONS.\n"
                "1. $b = -0.6 \\times \\frac{15}{5} = -1.8$; "
                "$a = 100 - (-1.8)(20) = 136$. Line $\\hat{y} = 136 - 1.8x$. Center "
                "check: $136 - 1.8(20) = 100$ ✓.\n"
                "2. $R^2 = (-0.6)^2 = 0.36$: the line explains 36% of $y$'s "
                "variance. $R^2$ dropped the minus sign — direction lives in $r$ "
                "and $b$ only.\n"
                "3. $\\hat{y}(25) = 136 - 45 = 91$, legitimate ($25 \\in [10,30]$). "
                "$x = 60$ is double the largest observed $x$: pure extrapolation, "
                "unsupported.\n"
                "4. $r$ is UNCHANGED at $-0.6$ (unit-free). New $s_x = 0.5$, so "
                "$b = -0.6 \\times \\frac{15}{0.5} = -18$ — the slope multiplies by "
                "10, since one new unit is ten old ones. Check: "
                "$\\bar{x} = 2$, $a = 100 + 36 = 136$, and $\\hat{y}(2.5) = 91$, the "
                "same prediction as (3). Units changed; the physics did not.\n"
                "5. FALSE — it implies no LINEAR association. Counterexample: "
                "$y = x^2$ on $x = -2,\\ldots,2$ gives $r = 0$ while $y$ is "
                "perfectly determined by $x$.\n"
                "6. The linear model is WRONG despite the high $R^2$. A U-shaped "
                "residual plot means systematic error — over at the ends, under in "
                "the middle (or vice versa). $R^2$ measures variance mopped up, not "
                "correctness of form. Fit a curve; do not report the line.\n"
                "7. $z_x = 2$, so $z_{\\hat{y}} = 0.5(2) = 1$ and "
                "$\\hat{y} = 69 + 3 = 72$ in. NO convergence: a 75-inch son "
                "predicts a 72-inch father too, and the population SD stays at 3. "
                "It is $|r| < 1$, not a force.\n"
                "8. $r = \\frac{-60}{\\sqrt{50 \\times 200}} = \\frac{-60}{100} = "
                "-0.6$; $b = \\frac{-60}{50} = -1.2$ (signs agree, as they must).\n\n"
                "SCORING. 8/8 — you own this chapter. 6-7 — reread the pages your "
                "misses map to (3-4 → pages 6-7, 13; 5-6 → pages 10-12; 7 → pages "
                "6, 9). $\\le 5$ — rework pages 3-11 before practicing."
            )),
            # ---------------------------------------------------------- 20
            (K, "Mastery checklist", (
                "Before leaving this chapter — and this sequence — check every box:\n\n"
                "□ State what $r$ measures, and explain the z-score/quadrant "
                "picture that makes its sign and magnitude obvious.\n"
                "□ Name the four properties of $r$ (range, symmetry, unit-free, "
                "rescaling-invariant) and say why each follows from the "
                "definition.\n"
                "□ Compute $S_{xx}, S_{yy}, S_{xy}$ from raw data and get $r$, $b$, "
                "and $a$ — then verify the line passes through "
                "$(\\bar{x}, \\bar{y})$.\n"
                "□ Fit the line from summary statistics alone "
                "($\\bar{x}, s_x, \\bar{y}, s_y, r$) and back out $r$ from $b$.\n"
                "□ Interpret slope and intercept IN CONTEXT with units, using "
                "'associated with,' and say when an intercept is meaningless.\n"
                "□ Define $R^2$ as variance explained, connect it to "
                "$\\text{SST} = \\text{SSR} + \\text{SSE}$, and explain why "
                "$R^2 = r^2$ here.\n"
                "□ Read a residual plot: cloud (fine), curve (wrong model), funnel "
                "(bad inference) — and explain why a high $R^2$ does not excuse "
                "skipping it.\n"
                "□ Produce a dataset with $r = 0$ and a perfect relationship, and "
                "explain what $r$ is structurally blind to.\n"
                "□ Show how ONE outlier moves $r$ and the line, and distinguish "
                "leverage from influence.\n"
                "□ Explain why extrapolation is unsupported, with a concrete "
                "absurdity.\n"
                "□ Derive regression to the mean from $z_{\\hat{y}} = r z_x$, show "
                "it runs in both directions, and debunk the flight-instructor "
                "fallacy.\n"
                "□ Explain why $y$-on-$x$ and $x$-on-$y$ differ, and why both are "
                "shallower than the SD line.\n"
                "□ List the four explanations for a strong $r$ (causation, reverse "
                "causation, confounding, coincidence) and explain why "
                "RANDOMIZATION — and essentially only randomization — settles the "
                "question.\n\n"
                "AND THAT CLOSES THE SEQUENCE. PS16 is the last chapter of the "
                "probability-statistics track. Look what sixteen chapters built: "
                "PS01-PS04 made chance computable; PS05-PS10 built random variables "
                "and their distributions; PS11's central limit theorem explained "
                "the normal's ubiquity; PS12 summarized data; PS13 turned a "
                "statistic into a random variable with a standard error; PS14-PS15 "
                "turned that into intervals and tests. PS16 finally aimed the whole "
                "apparatus at two variables and asked the question people actually "
                "care about: how does this go with that — and does it MAKE it "
                "happen?\n\n"
                "Where next. For the mathematics underneath: LA.U8.N2 recasts all "
                "of this as orthogonal projection and opens multiple regression, "
                "where $A^{T}A\\mathbf{v} = A^{T}\\mathbf{y}$ handles any number of "
                "predictors; C115 supplies the optimization behind the normal "
                "equations. For the applications: the same line, with a different "
                "loss and a link, becomes logistic regression and the whole "
                "supervised-learning canon — where every trap on page 12 still "
                "waits.\n\n"
                "Hit Practice until the workflow — plot, sums, line, center check, "
                "residuals, hedged sentence — is automatic. Then find a real "
                "scatterplot and be the person who plots it first."
            )),
        ],
    },
}
