/**
 * GMAT (Focus Edition) — Question Bank
 * 75 original, blueprint-faithful, SME-audited questions
 * (Quantitative Reasoning + Verbal Reasoning + Data Insights).
 * topicId: 0 = Quantitative Reasoning, 1 = Verbal Reasoning, 2 = Data Insights.
 */

export interface GMATQuestion {
  id: string;
  topicId: number;
  domain: string;
  skill: string;
  difficulty: number;
  passage?: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const GMAT_QUESTIONS: GMATQuestion[] = [
  {
    id: "gmat_0001", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 1,
    question: "A retailer buys a jacket for $80 and increases the price by 25% to set the marked price. During a promotion, the retailer sells the jacket at 20% off the marked price. What is the promotional selling price?",
    options: ["$76", "$80", "$84", "$96", "$100"],
    correct: 1,
    explanation: "Marked price = 80 x 1.25 = 100. Promotional price = 100 x 0.80 = 80. The two percentage changes do NOT simply cancel because 25% and 20% apply to different bases: 1.25 x 0.80 = 1.00, which returns to cost here. $100 is the marked price before the discount. $84 mistakenly nets the percents to +5% (25 - 20). $96 = 0.80 x 120, treating the markup as +50%. $76 subtracts a flat 20% of 80. Only $80 is correct.",
  },
  {
    id: "gmat_0002", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 1,
    question: "An inheritance of $4,500 is divided among three heirs in the ratio 3 : 5 : 7. How much does the heir with the largest share receive?",
    options: ["$900", "$1,200", "$1,500", "$1,800", "$2,100"],
    correct: 4,
    explanation: "Total parts = 3 + 5 + 7 = 15, so one part = 4,500 / 15 = 300. The largest share is 7 parts = 7 x 300 = 2,100. $1,500 is the middle share (5 parts), $900 is the smallest (3 parts). $1,800 = 6 parts, an off-by-one error. $1,200 corresponds to 4 parts and matches no heir. Only $2,100 is correct.",
  },
  {
    id: "gmat_0003", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 1,
    question: "A student has taken 5 tests with an average score of 78. To raise the average to exactly 80 after a 6th test, what must the student score on the 6th test?",
    options: ["82", "84", "86", "88", "90"],
    correct: 4,
    explanation: "Required total for six tests = 80 x 6 = 480. Current total = 78 x 5 = 390. The 6th score must be 480 - 390 = 90. A common error is 80 + 2 = 82, covering the 2-point gap only once; but the deficit must be made up across all six tests. 84, 86, and 88 all under-count the shortfall. Only 90 is correct.",
  },
  {
    id: "gmat_0004", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 2,
    question: "Pipe A can fill a tank in 6 hours and pipe B can fill the same tank in 4 hours. If both pipes are opened together on an empty tank, how many hours will it take to fill the tank?",
    options: ["2", "2.4", "2.5", "3.6", "5"],
    correct: 1,
    explanation: "Combined rate = 1/6 + 1/4 = 2/12 + 3/12 = 5/12 tank per hour. Time = 1 / (5/12) = 12/5 = 2.4 hours. A frequent trap is averaging the times: (6 + 4)/2 = 5, which is wrong. 2.5 comes from (6+4)/4. 3.6 inverts a step. 2 mistakes the rate. Only 2.4 is correct.",
  },
  {
    id: "gmat_0005", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 2,
    question: "A chemist has 40 liters of a solution that is 30% acid. How many liters of pure water must be added so that the resulting mixture is 24% acid?",
    options: ["6", "8", "10", "12", "16"],
    correct: 2,
    explanation: "The acid amount is fixed at 0.30 x 40 = 12 liters. After adding x liters of water: 12 / (40 + x) = 0.24, so 40 + x = 12 / 0.24 = 50, giving x = 10. Adding water dilutes concentration while keeping the acid quantity constant. 6 comes from applying 0.30 - 0.24 = 0.06 to a base. 8, 12, and 16 result from letting the acid amount change rather than stay fixed. Only 10 satisfies the equation.",
  },
  {
    id: "gmat_0006", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 2,
    question: "A town's population was 20,000. In the first year it increased by 10%, and in the second year it decreased by 10%. What was the population at the end of the two years?",
    options: ["19,600", "19,800", "20,000", "20,200", "22,000"],
    correct: 1,
    explanation: "Year 1: 20,000 x 1.10 = 22,000. Year 2: 22,000 x 0.90 = 19,800. Successive +10% then -10% yields a net factor of 1.10 x 0.90 = 0.99, a 1% net decrease, not zero. 20,000 is the classic trap of assuming the percents cancel. 22,000 stops after year 1. 20,200 and 19,600 come from arithmetic slips. Only 19,800 is correct.",
  },
  {
    id: "gmat_0007", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 2,
    question: "A driver travels 120 miles from town P to town Q at an average speed of 40 miles per hour, then returns along the same route at an average speed of 60 miles per hour. What is the driver's average speed, in miles per hour, for the entire round trip?",
    options: ["45", "48", "50", "52", "55"],
    correct: 1,
    explanation: "Average speed = total distance / total time. Time out = 120/40 = 3 hours; time back = 120/60 = 2 hours. Total = 240 miles in 5 hours = 48 mph. The trap answer 50 is the simple mean of 40 and 60, which is wrong because more time is spent at the slower speed. Equivalently, harmonic mean = 2 x 40 x 60 / (40 + 60) = 48. 45, 52, and 55 are unsupported. Only 48 is correct.",
  },
  {
    id: "gmat_0008", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 3,
    question: "A merchant sells two watches for $90 each. On the first watch the merchant makes a 20% profit relative to its cost, and on the second watch the merchant takes a 20% loss relative to its cost. Considering both watches together, what is the merchant's overall result?",
    options: ["A profit of $7.50", "No profit and no loss", "A loss of $3.60", "A loss of $7.50", "A loss of $9.00"],
    correct: 3,
    explanation: "Cost of watch 1: 90 / 1.20 = 75. Cost of watch 2: 90 / 0.80 = 112.50. Total cost = 187.50; total revenue = 180. Net = 180 - 187.50 = -7.50, a loss of $7.50. When equal selling prices give equal-percentage profit and loss, the result is always a net loss. 'No profit/no loss' is the trap of assuming +20% and -20% cancel. $9.00 and $3.60 come from applying the percentages to selling price instead of cost. A $7.50 profit reverses the sign. Only a $7.50 loss is correct.",
  },
  {
    id: "gmat_0009", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 3,
    question: "A father is currently 4 times as old as his son. In 20 years, the father will be twice as old as his son. How old is the father now?",
    options: ["30", "32", "36", "40", "48"],
    correct: 3,
    explanation: "Let the son's age be S; father = 4S. In 20 years: 4S + 20 = 2(S + 20). Then 4S + 20 = 2S + 40, so 2S = 20, S = 10 and father = 40. Check: now 40 and 10 (4x); in 20 years 60 and 30 (2x). 30 and 36 come from mis-forming the future equation; 32 and 48 from arithmetic errors on S. Only 40 satisfies both conditions.",
  },
  {
    id: "gmat_0010", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 3,
    question: "$5,000 is invested at an annual interest rate of 10%. How much more interest is earned in 2 years if the interest is compounded annually rather than computed as simple interest?",
    options: ["$25", "$50", "$100", "$500", "$550"],
    correct: 1,
    explanation: "Simple interest for 2 years = 5,000 x 0.10 x 2 = 1,000. Compound: 5,000 x 1.10^2 = 6,050, so interest = 1,050. Difference = 1,050 - 1,000 = 50. The extra $50 is interest earned on the first year's $500 of interest (500 x 0.10 = 50). $100 double-counts; $500 is one year's simple interest; $550 is the second-year compound interest amount; $25 halves the result. Only $50 is correct.",
  },
  {
    id: "gmat_0011", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 3,
    question: "A crew of 12 workers can complete a job in 8 days, with each worker working at the same constant rate. The crew works together for 2 days, after which 4 workers leave. How many additional days will the remaining workers need to finish the job?",
    options: ["6", "7.5", "8", "9", "12"],
    correct: 3,
    explanation: "Total work = 12 x 8 = 96 worker-days. In 2 days, 12 workers complete 12 x 2 = 24 worker-days, leaving 96 - 24 = 72. Remaining crew = 12 - 4 = 8 workers, so days = 72 / 8 = 9. The trap answer 6 wrongly uses the original 12 workers (72/12). 8 forgets to subtract the work already done. 12 uses only 6 workers. 7.5 is unsupported. Only 9 is correct.",
  },
  {
    id: "gmat_0012", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Arithmetic and Word Problems", difficulty: 3,
    question: "The sum of five consecutive even integers is 130. What is the largest of these integers?",
    options: ["26", "28", "30", "32", "34"],
    correct: 2,
    explanation: "Let the integers be n, n+2, n+4, n+6, n+8. Their sum is 5n + 20 = 130, so 5n = 110 and n = 22. The integers are 22, 24, 26, 28, 30, and the largest is 30. The middle term is 130/5 = 26 (a trap for those who stop at the average). 28 is the second-largest. 32 and 34 overshoot. Only 30 is the largest term.",
  },
  {
    id: "gmat_0013", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 1,
    question: "If 5x - 3 = 2x + 12, what is the value of x?",
    options: ["3", "5", "9", "15", "-5"],
    correct: 1,
    explanation: "Subtract 2x from both sides: 3x - 3 = 12. Add 3: 3x = 15, so x = 5. Option (A) 3 wrongly divides 12 by an incorrect coefficient. Option (C) 9 comes from adding rather than subtracting the 3. Option (D) 15 is the value of 3x, not x. Option (E) -5 flips the sign incorrectly.",
  },
  {
    id: "gmat_0014", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 1,
    question: "A number increased by 40% equals 84. What is the number?",
    options: ["50", "56", "60", "44", "120"],
    correct: 2,
    explanation: "Let the number be n. Then 1.4n = 84, so n = 84 / 1.4 = 60. Check: 60 + 40% of 60 = 60 + 24 = 84. Option (A) 50 gives 70, not 84. Option (B) 56 comes from subtracting 40% of 84 — incorrect. Option (D) 44 comes from subtracting 40 from 84. Option (E) 120 comes from dividing by 0.7 instead of 1.4.",
  },
  {
    id: "gmat_0015", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 1,
    question: "If 3(y + 2) = 4y - 5, what is the value of y?",
    options: ["11", "1", "-1", "7", "-11"],
    correct: 0,
    explanation: "Expand: 3y + 6 = 4y - 5. Subtract 3y: 6 = y - 5. Add 5: y = 11. Option (B) 1 comes from a sign error in moving the 5. Option (C) -1 mishandles both constants. Option (D) 7 comes from dividing 6 by an incorrect leftover coefficient. Option (E) -11 flips the sign of the correct answer.",
  },
  {
    id: "gmat_0016", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 2,
    question: "Machine A can fill a tank in 6 hours and machine B can fill the same tank in 4 hours. Working together, how many hours will they take to fill the tank?",
    options: ["2.4", "2.5", "5", "10", "1.2"],
    correct: 0,
    explanation: "Combined rate = 1/6 + 1/4 = 2/12 + 3/12 = 5/12 tank per hour. Time = 1 / (5/12) = 12/5 = 2.4 hours. Option (B) 2.5 is a near-miss from an arithmetic slip. Option (C) 5 averages the two times incorrectly, (6+4)/2. Option (D) 10 adds the two times. Option (E) 1.2 comes from inverting the rate calculation wrongly.",
  },
  {
    id: "gmat_0017", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 2,
    question: "The sum of two numbers is 54 and their difference is 12. What is the product of the two numbers?",
    options: ["648", "693", "660", "540", "621"],
    correct: 1,
    explanation: "Let the numbers be x and y with x + y = 54 and x - y = 12. Adding: 2x = 66, so x = 33; then y = 21. Product = 33 × 21 = 693. Option (A) 648 = 36 × 18 uses wrong split values. Option (C) 660 uses 33 × 20. Option (D) 540 uses an incorrect pair. Option (E) 621 = 27 × 23 splits the numbers incorrectly.",
  },
  {
    id: "gmat_0018", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 2,
    question: "A car travels the first 120 miles of a trip at 40 miles per hour and the next 120 miles at 60 miles per hour. What is the car's average speed, in miles per hour, for the entire trip?",
    options: ["50", "48", "45", "52", "44"],
    correct: 1,
    explanation: "Time for first leg = 120/40 = 3 hours; time for second leg = 120/60 = 2 hours. Total distance = 240 miles, total time = 5 hours. Average speed = 240/5 = 48 mph. Option (A) 50 is the trap of averaging the two speeds, (40+60)/2. Options (C) 45 and (D) 52 are arithmetic-slip distractors. Option (E) 44 uses a weighting error.",
  },
  {
    id: "gmat_0019", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 2,
    question: "A store marks up an item by 25% over its cost, then offers a 20% discount on the marked-up price. If the final selling price is $60, what was the cost of the item?",
    options: ["$60", "$62.50", "$50", "$48", "$75"],
    correct: 0,
    explanation: "Let cost = c. Marked-up price = 1.25c; after a 20% discount = 0.80 × 1.25c = 1.00c = c. So the final price equals the cost, meaning c = $60. Option (B) $62.50 comes from applying only the markup. Option (C) $50 assumes a net 20% markdown from 60. Option (D) $48 applies the 20% discount to 60. Option (E) $75 applies the 25% markup to 60.",
  },
  {
    id: "gmat_0020", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 2,
    question: "If x and y are positive integers such that 2x + 3y = 29, how many ordered pairs (x, y) satisfy the equation?",
    options: ["3", "4", "5", "6", "2"],
    correct: 2,
    explanation: "Solve for x: x = (29 - 3y)/2. Since 29 is odd, 3y must be odd for the numerator to be even, so y must be odd. Testing odd y: y = 1 gives x = 13; y = 3 gives x = 10; y = 5 gives x = 7; y = 7 gives x = 4; y = 9 gives x = 1. All five yield positive integer x. y = 11 gives x = -2 (invalid). So there are exactly 5 pairs. Option (A) 3 and (B) 4 undercount by missing valid endpoints. Option (D) 6 overcounts by including an invalid pair. Option (E) 2 only counts a couple of cases.",
  },
  {
    id: "gmat_0021", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 3,
    question: "A tank contains 40 liters of a solution that is 15% acid. How many liters of pure acid must be added to make the solution 25% acid?",
    options: ["16/3", "5", "20/3", "8", "10"],
    correct: 0,
    explanation: "Initial acid = 0.15 × 40 = 6 liters. Let a liters of pure acid be added. New acid = 6 + a; new total = 40 + a. Set (6 + a)/(40 + a) = 0.25, so 6 + a = 10 + 0.25a, giving 0.75a = 4 and a = 16/3 ≈ 5.33. Option (B) 5 rounds incorrectly. Option (C) 20/3 comes from a setup error in the denominator. Option (D) 8 ignores that added acid also increases the total volume. Option (E) 10 uses the wrong target concentration difference.",
  },
  {
    id: "gmat_0022", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 3,
    question: "The value of an investment grows by 10% in the first year and by 20% in the second year. Over the two years, by what overall percent does the investment grow?",
    options: ["30%", "32%", "15%", "22%", "31%"],
    correct: 1,
    explanation: "Multiplying the growth factors: 1.10 × 1.20 = 1.32, an overall growth of 32%. Option (A) 30% incorrectly adds the two percentages. Option (C) 15% averages them. Options (D) 22% and (E) 31% are near-miss distractors from mis-multiplying the factors.",
  },
  {
    id: "gmat_0023", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 3,
    question: "Working alone, Pipe X fills a pool in 3 hours. Pipe X and Pipe Y together fill the pool in 2 hours. How long, in hours, would Pipe Y take to fill the pool alone?",
    options: ["6", "5", "1", "2.5", "4"],
    correct: 0,
    explanation: "Together they fill 1/2 pool per hour. Pipe X alone fills 1/3 per hour. So Pipe Y's rate = 1/2 - 1/3 = 3/6 - 2/6 = 1/6 pool per hour, meaning Y takes 6 hours alone. Option (B) 5 adds times incorrectly. Option (C) 1 inverts the rate wrongly. Option (D) 2.5 averages the times. Option (E) 4 comes from a subtraction error in the rates.",
  },
  {
    id: "gmat_0024", topicId: 0, domain: "Quantitative Reasoning", skill: "Problem Solving — Algebra", difficulty: 3,
    question: "If x^2 - 5x + 6 = 0 and x > 0, and y = 2x + 1, what is the sum of all possible values of y?",
    options: ["8", "12", "5", "10", "7"],
    correct: 1,
    explanation: "Factor: x^2 - 5x + 6 = (x - 2)(x - 3) = 0, so x = 2 or x = 3 (both positive). Then y = 2(2)+1 = 5 or y = 2(3)+1 = 7. Sum of all possible y-values = 5 + 7 = 12. Option (A) 8 sums the roots plus a stray term. Options (C) 5 and (E) 7 each give only one of the two y-values. Option (D) 10 doubles the sum of roots without adding the constants correctly.",
  },
  {
    id: "gmat_0025", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 1,
    passage: "The Riverdale Public Library recently extended its weekday hours, staying open until 10 p.m. instead of 6 p.m. In the three months following this change, the total number of books checked out per week rose by 40 percent compared with the same three months of the previous year. The library director concluded that the extended evening hours were responsible for the increase in checkouts.",
    question: "Which of the following, if true, most weakens the library director's conclusion?",
    options: ["During the three months in question, the library ran a widely advertised program that waived all late fees for patrons who borrowed at least five books.", "A neighboring town's library, which did not change its hours, saw its weekly checkouts remain roughly constant over the same period.", "Most of the additional checkouts occurred during the newly added evening hours rather than during daytime hours.", "The library hired two additional staff members to cover the extended evening shifts.", "Some patrons reported that they preferred visiting the library in the evening after work."],
    correct: 0,
    explanation: "The conclusion attributes the checkout increase to extended hours. Option A weakens it by supplying an alternative cause operating during the same period, a fee-waiver program tied directly to borrowing books, that could explain the 40 percent rise independent of the hours change. The other options do not weaken. B (a control town holding steady) tends to support that Riverdale's change mattered. C says extra checkouts happened in the new evening hours, which supports the director. D is a neutral operational detail. E provides mild anecdotal support for the hours explanation, not a challenge to it.",
  },
  {
    id: "gmat_0026", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 1,
    passage: "A consumer-electronics company found that customers who registered their new headphones online within a week of purchase were far less likely to return the product than customers who did not register. To reduce its return rate, the company plans to send every new buyer a reminder email encouraging prompt online registration.",
    question: "The company's plan relies on which of the following assumptions?",
    options: ["Registering the headphones online causes at least some customers to keep products they would otherwise have returned.", "Customers who return headphones never register them online.", "The reminder email will reach every customer who buys the headphones.", "Most product returns are caused by defects that registration cannot address.", "Customers who register online are more satisfied with the product than those who do not."],
    correct: 0,
    explanation: "The plan assumes that prompting registration will lower returns, which requires that registration actually influences the decision to keep the product, at least for some customers, rather than merely correlating with an already-committed type of buyer. Option A states exactly this causal link. B is too extreme and not needed. C is too strong; the plan can succeed without reaching literally every buyer. D would undermine the plan, so it is not an assumption it depends on. E describes a possible correlation but the plan does not require satisfaction to be the mechanism; it requires that encouraging registration actually reduces returns.",
  },
  {
    id: "gmat_0027", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 2,
    passage: "In the coastal region of Valea, the population of a small fish species declined sharply over the past decade. During the same period, the number of cormorants, birds that feed heavily on these fish, increased substantially. Marine biologists have therefore proposed reducing the cormorant population to allow the fish stocks to recover.",
    question: "Which of the following, if true, most seriously calls into question the effectiveness of the biologists' proposal?",
    options: ["Cormorants also feed on several other fish species whose populations have remained stable over the past decade.", "The decline in the small fish species was caused primarily by warming coastal waters that reduce the survival of fish eggs, not by predation.", "Cormorant populations in a neighboring region have also grown over the same period.", "Reducing the cormorant population would require substantial funding from regional authorities.", "The small fish species reproduces rapidly under favorable conditions."],
    correct: 1,
    explanation: "The proposal treats cormorant predation as the cause of the fish decline. Option B undercuts this by identifying a different primary cause, warming waters killing fish eggs, so reducing cormorants would not address the actual driver and would likely fail to restore the stocks. A is neutral to slightly relevant but does not show the proposal would fail. C concerns another region and does not bear on Valea's mechanism. D raises a cost concern, not an effectiveness concern about the proposal's biological logic. E, if anything, suggests the fish could recover, which does not challenge the proposal's effectiveness at reducing predation pressure.",
  },
  {
    id: "gmat_0028", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 2,
    passage: "A manufacturing firm installed a new automated inspection system on its assembly line, expecting to catch more defective units before shipping. In the quarter after installation, the number of customer complaints about defective products actually rose compared with the previous quarter. The plant manager concluded that the new inspection system performs worse than the manual inspection it replaced.",
    question: "Which of the following, if true, most weakens the plant manager's conclusion?",
    options: ["The new inspection system flags a wider range of defect types than the manual inspectors did.", "Total product shipments during the quarter after installation were more than double those of the previous quarter because of a large new contract.", "The manual inspectors who were replaced had received extensive training over many years.", "Some customers submit complaints about products that are not actually defective.", "The new system requires periodic recalibration to maintain accuracy."],
    correct: 1,
    explanation: "The manager infers worse performance from a rise in the raw number of complaints. Option B weakens this by revealing that shipment volume more than doubled; a rise in the absolute count of complaints could accompany a lower defect rate per unit, so the raw increase does not show the system is worse. A actually suggests the new system is more capable. C describes the old inspectors' qualifications but does not resolve why complaints rose. D applies to both systems and does not explain the increase. E notes a maintenance need but gives no evidence the system underperformed the manual method.",
  },
  {
    id: "gmat_0029", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 2,
    passage: "Nutritionists observed that people who regularly drink green tea have, on average, lower rates of a certain chronic illness than people who do not. A wellness columnist concluded that adding green tea to one's daily routine will reduce a person's risk of developing the illness.",
    question: "Which of the following, if true, most undermines the columnist's conclusion?",
    options: ["Green tea contains antioxidants that laboratory studies have linked to reduced cellular damage.", "People who regularly drink green tea tend to exercise more and eat more vegetables than people who do not.", "The chronic illness in question can take many years to develop.", "Some people find the taste of green tea unpleasant and stop drinking it after a short time.", "Black tea, which is more popular in the region studied, contains fewer of these antioxidants."],
    correct: 1,
    explanation: "The columnist infers a causal benefit of green tea from a correlation. Option B undermines this by pointing to confounding variables: green-tea drinkers also exercise more and eat more vegetables, so their lower illness rate might stem from those healthy behaviors rather than from the tea itself. A supports the causal claim. C is neutral regarding causation. D concerns adherence, not whether the tea causes the benefit. E compares black tea but does not challenge whether green tea's association is causal.",
  },
  {
    id: "gmat_0030", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 2,
    passage: "The city of Marbourg is considering a congestion charge for driving in its downtown core during peak hours. Supporters argue that because a similar charge in the city of Elden reduced downtown traffic by 20 percent within a year, Marbourg can expect a comparable reduction if it adopts the same charge.",
    question: "The supporters' argument depends on which of the following assumptions?",
    options: ["Marbourg's downtown traffic is currently heavier than Elden's was before its congestion charge.", "Elden's congestion charge was the lowest fee that could still reduce traffic.", "No factor unique to Elden was primarily responsible for the traffic reduction there.", "Most residents of Marbourg support the introduction of a congestion charge.", "Reducing downtown traffic is the only benefit a congestion charge can provide."],
    correct: 2,
    explanation: "The argument reasons from analogy: because it worked in Elden, it will work similarly in Marbourg. This requires that Elden's result was attributable to the charge itself and not to some special circumstance in Elden that Marbourg lacks. Option C states this necessary assumption. A about relative traffic levels is not required for a comparable percentage reduction. B about fee optimization is irrelevant to whether the effect transfers. D about public support concerns political feasibility, not the predicted effect. E about other benefits is outside the scope of the traffic-reduction prediction.",
  },
  {
    id: "gmat_0031", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 2,
    passage: "A software company requires all new engineers to complete a two-week onboarding course before they begin project work. Managers noticed that engineers who scored in the top quarter on the course's final quiz went on to receive higher performance ratings in their first year than engineers who scored in the bottom quarter. The head of training argues that making the course more rigorous would raise the first-year performance of future hires.",
    question: "Which of the following, if true, most seriously weakens the head of training's argument?",
    options: ["The final quiz mainly measures general aptitude that the engineers already possessed before the course began.", "A few engineers who scored in the bottom quarter later became strong performers.", "The onboarding course covers material that engineers rarely use in their daily project work.", "Engineers who score well on the quiz tend to report enjoying the course more.", "Some managers assign performance ratings more generously than others."],
    correct: 0,
    explanation: "The head of training assumes the course itself drives later performance, so making it harder will improve outcomes. Option A weakens this by indicating the quiz merely reflects pre-existing aptitude; if the score measures what engineers already knew rather than what the course taught, then intensifying the course would not necessarily raise performance, because the correlation is not driven by course content. B is a minor exception that does not overturn the trend. C hints the course content is less useful but does not directly address whether more rigor would help performance as measured. D is a neutral side effect. E introduces rating noise but does not systematically undercut the causal claim.",
  },
  {
    id: "gmat_0032", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 2,
    passage: "An airline introduced a policy allowing passengers to board in the order they arrive at the gate, rather than by assigned zones. After the change, the average time to board a full flight decreased by four minutes. An analyst wants to determine whether the new boarding policy, rather than some other factor, was responsible for the improvement.",
    question: "Which of the following would be most useful to know in evaluating whether the new policy caused the faster boarding?",
    options: ["Whether passengers reported greater satisfaction with the new boarding process.", "Whether the airline simultaneously reduced the amount of carry-on luggage each passenger was permitted to bring aboard.", "Whether the four-minute reduction was consistent across flights of different sizes.", "Whether competing airlines use zone-based boarding.", "Whether gate agents preferred the new boarding method to the old one."],
    correct: 1,
    explanation: "To evaluate causation, we need to rule out alternative explanations for the faster boarding. Option B is decisive: if the airline also cut allowed carry-on luggage at the same time, that separate change could account for the four-minute reduction, so knowing whether it happened tells us whether the policy alone deserves credit. A concerns satisfaction, not boarding speed causation. C explores the effect's distribution but does not isolate the cause. D and E concern competitors' practices and agents' preferences, neither of which bears on what caused this airline's improvement.",
  },
  {
    id: "gmat_0033", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 3,
    passage: "A regional hospital adopted a new electronic checklist that surgical teams must complete before every operation. In the year after adoption, the rate of serious surgical complications at the hospital fell by 15 percent. Hospital administrators credited the checklist for the decline and recommended that all hospitals in the region adopt it to achieve similar results.",
    question: "Which of the following, if true, most strengthens the administrators' recommendation?",
    options: ["During the same year, the hospital did not change its surgical staff, procedures, or patient-selection criteria in any other way.", "The hospital that adopted the checklist is the largest in the region.", "Surgical teams reported that completing the checklist added only a few minutes to each operation.", "The 15 percent decline was measured against the hospital's own complication rate from the previous year.", "Some surgeons initially resisted using the checklist but later found it helpful."],
    correct: 0,
    explanation: "The recommendation to spread the checklist rests on the claim that the checklist caused the 15 percent decline. Option A strengthens this causal claim by eliminating alternative explanations: with no other changes to staff, procedures, or patients, the checklist becomes the most plausible cause of the improvement, supporting the expectation that other hospitals would benefit too. B about hospital size is irrelevant to causation. C about time cost speaks to feasibility, not effectiveness. D merely clarifies the baseline of the measurement without isolating the cause. E describes attitudes, not outcomes, and thus does not bolster the causal link.",
  },
  {
    id: "gmat_0034", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 3,
    passage: "Economist: Whenever the central bank of Torvia has lowered interest rates in the past, consumer spending has risen within six months. The central bank lowered interest rates last month. Therefore, consumer spending in Torvia will rise within the next six months.",
    question: "Which of the following, if true, most calls into question the economist's prediction?",
    options: ["On each previous occasion when rates were lowered, household confidence in the economy was already rising, but confidence is currently falling steeply.", "The central bank has lowered interest rates more frequently in the last decade than in earlier decades.", "Consumer spending in Torvia has historically been influenced by many factors besides interest rates.", "The most recent rate cut was smaller than the average of previous cuts.", "Interest rates in neighboring countries have remained unchanged."],
    correct: 0,
    explanation: "The economist projects a past pattern onto the present. Option A most damages the prediction by revealing that the past cases shared a condition, rising household confidence, that is absent now; indeed confidence is falling steeply. If that condition helped produce the spending rise before, its reversal now undermines the inference that the pattern will repeat. B about frequency of cuts does not bear on the effect. C is true but generic and does not specifically block this prediction. D notes a smaller cut, which weakens only weakly and does not identify a broken condition the way A does. E about other countries is irrelevant to Torvia's outcome.",
  },
  {
    id: "gmat_0035", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 3,
    passage: "A publisher noticed that its novels with brightly colored covers sell more copies than its novels with muted covers. Concluding that bright covers cause higher sales, the publisher decided to reissue its entire backlist with brightly colored covers, expecting each reissued title to sell more copies as a result.",
    question: "Which of the following, if true, most seriously weakens the publisher's expectation about the reissues?",
    options: ["The publisher has historically chosen bright covers for the novels it expected to be most popular and invested the largest marketing budgets in them.", "A rival publisher recently reissued several titles with bright covers and saw modest sales gains.", "Bright covers cost slightly more to print than muted covers.", "Readers surveyed said they notice cover color when browsing in bookstores.", "Some of the publisher's best-selling novels have muted covers."],
    correct: 0,
    explanation: "The publisher infers that bright covers cause higher sales and expects reissuing will boost each title. Option A weakens this by exposing a confound and a case of reverse selection: the publisher already assigned bright covers, plus the largest marketing budgets, to the novels it expected to sell best. So the observed sales gap likely reflects those titles' inherent appeal and marketing rather than the covers, meaning merely recoloring the backlist need not raise sales. B offers mild support from a rival. C is a minor cost point. D suggests color is noticed but not that it drives sales causally. E is a single counterexample that does not address the causal mechanism.",
  },
  {
    id: "gmat_0036", topicId: 1, domain: "Verbal Reasoning", skill: "Critical Reasoning", difficulty: 3,
    passage: "A large retail chain introduced self-checkout kiosks in its stores, and over the following year the average time customers spent waiting in checkout lines fell noticeably. The chain's operations director argued that the shorter wait times would increase customer loyalty, and therefore predicted that annual revenue per store would rise in the coming year.",
    question: "The operations director's prediction assumes which of the following?",
    options: ["Factors other than shorter wait times will not offset any gain in revenue that increased customer loyalty would produce.", "The self-checkout kiosks cost less to operate than the staffed checkout lanes they replaced.", "Customers who use self-checkout kiosks buy more items than customers who use staffed lanes.", "Shorter wait times are the aspect of shopping that customers value most.", "No competing retail chain in the area has installed self-checkout kiosks."],
    correct: 0,
    explanation: "The director moves from increased loyalty to a prediction of higher revenue per store. For that prediction to hold, no countervailing factor must cancel out the revenue gain that loyalty is expected to produce; option A states exactly this necessary assumption, and its negation (some other factor does offset the gain) would break the prediction. B about operating cost concerns profit, not the revenue prediction, and is not required. C would help but is a stronger, unneeded claim about basket size. D overstates the case; the argument needs shorter waits to boost loyalty, not to be the single most valued factor. E about competitors is not something the prediction depends on.",
  },
  {
    id: "gmat_0037", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 1,
    passage: "For decades, the prevailing view among ecologists held that coral reefs recover from bleaching events only when water temperatures return to their long-term averages. Recent field studies in the Indian Ocean, however, have documented reefs that regained health while ambient temperatures remained elevated. Researchers attribute this to the presence of heat-tolerant strains of symbiotic algae that colonize the corals during the recovery phase. Although these strains support coral survival, they appear to provide fewer nutrients than the strains they replace, potentially leaving the reefs more vulnerable to other stressors such as disease.",
    question: "The primary purpose of the passage is to",
    options: ["describe a finding that complicates a previously accepted account of how coral reefs recover", "argue that heat-tolerant algae will ultimately save coral reefs from extinction", "compare the nutrient output of two competing strains of symbiotic algae", "criticize ecologists for failing to study reefs in the Indian Ocean", "propose a new method for measuring water temperatures around coral reefs"],
    correct: 0,
    explanation: "The passage opens with a long-standing view (recovery requires temperatures to return to average), then presents field studies that contradict it, and finally notes a complicating trade-off (the new algae provide fewer nutrients). This structure matches (A): a finding that complicates an accepted account. (B) overstates the passage; it never claims reefs will be saved from extinction and in fact ends on a note of continued vulnerability. (C) describes only one detail in the final sentence, not the passage's overall purpose. (D) is unsupported; the passage credits, not criticizes, the researchers. (E) is a fabricated detail; measuring temperature is not proposed.",
  },
  {
    id: "gmat_0038", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 1,
    passage: "A municipal transit authority recently replaced its aging diesel buses with electric models, expecting to cut operating costs. In the first year, fuel-and-electricity expenses fell by roughly forty percent, as projected. Total operating costs, however, declined only slightly, because the electric buses required more frequent and more expensive battery maintenance than the authority had anticipated. Ridership, meanwhile, remained essentially unchanged throughout the transition.",
    question: "The passage suggests that the transit authority's expectation about operating costs was based on which of the following assumptions?",
    options: ["Savings on fuel and electricity would not be substantially offset by other cost increases.", "Ridership would rise once the new electric buses were introduced.", "Battery maintenance would be less expensive than diesel engine maintenance.", "Diesel buses could not be operated economically at current fuel prices.", "Electric buses would attract riders who preferred environmentally friendly transit."],
    correct: 0,
    explanation: "The authority expected lower operating costs from switching to electric. That expectation only holds if the fuel/electricity savings would not be largely canceled out by other rising costs, which is exactly what happened with battery maintenance. So (A) is the assumption. (B) and (E) concern ridership, which the passage says stayed unchanged and which was not the basis for the cost expectation. (C) is a specific claim the passage never makes; in fact battery costs proved higher than anticipated, but the passage does not say the authority assumed they'd beat diesel maintenance specifically. (D) is unsupported; nothing addresses whether diesel was economical.",
  },
  {
    id: "gmat_0039", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 1,
    passage: "Historians once assumed that the rapid spread of printed pamphlets in sixteenth-century Europe was driven mainly by rising literacy rates. Newer scholarship challenges this assumption, noting that many pamphlets were read aloud in public squares and taverns to audiences who could not themselves read. On this view, a single literate reader could transmit a pamphlet's contents to dozens of listeners. The reach of printed material, these scholars argue, therefore depended less on how many people could read than on the social settings in which reading occurred.",
    question: "According to the passage, the newer scholarship differs from the older view primarily in its emphasis on",
    options: ["the social contexts in which printed material was consumed", "the total number of pamphlets produced in the sixteenth century", "the declining cost of printing over the course of the century", "the political content that made certain pamphlets popular", "the accuracy with which readers reproduced pamphlet texts aloud"],
    correct: 0,
    explanation: "The newer scholarship shifts the explanation from literacy rates to the settings in which reading happened (public squares, taverns, reading aloud). That is the social context, so (A) is correct. (B) is never discussed; the passage does not quantify pamphlet production. (C) introduces printing cost, which the passage never mentions. (D) mentions political content, but the passage does not attribute popularity to content. (E) about accuracy of oral reproduction is a plausible-sounding but wholly unsupported detail.",
  },
  {
    id: "gmat_0040", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "In the study of animal cognition, some researchers argue that certain birds display genuine planning for the future, citing scrub jays that cache food in locations where they have previously found themselves hungry. Skeptics counter that such behavior could reflect a simpler mechanism: the birds may associate particular locations with the discomfort of hunger and cache food there without any representation of future need. Proponents of the planning interpretation respond that in controlled experiments, jays cache specific foods in specific places according to what they will lack, not merely where they felt hunger. This selectivity, they contend, is difficult to explain by association alone.",
    question: "The proponents' final response functions primarily to",
    options: ["identify a feature of the birds' behavior that the skeptics' explanation does not readily account for", "concede that association may explain some but not all instances of caching", "propose an entirely new mechanism distinct from both planning and association", "question whether the controlled experiments were properly designed", "acknowledge that the evidence for future planning remains inconclusive"],
    correct: 0,
    explanation: "The skeptics offer an associative account (birds cache where they felt hunger). The proponents reply that jays cache specific foods in specific places matching what they will lack, and argue this selectivity is hard to explain by association. So the response points to a behavioral feature the associative explanation cannot readily handle, which is (A). (B) is wrong; the proponents do not concede association explains any instances here. (C) is wrong; they defend planning, not a third mechanism. (D) is the opposite of their stance; they rely on the experiments rather than questioning them. (E) contradicts their confident tone; they argue the evidence favors planning.",
  },
  {
    id: "gmat_0041", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "Economists studying minimum-wage increases have traditionally relied on comparisons between neighboring regions, one of which raised its wage floor while the other did not. Critics of this approach observe that neighboring regions may differ in ways unrelated to the policy, such as industry composition or the timing of local economic shocks, and that these differences can masquerade as effects of the wage change. A more recent method addresses this concern by constructing a synthetic comparison region from a weighted combination of many areas, chosen so that the combination closely tracks the treated region's pre-policy trends. Because the synthetic region matches the treated region's history, divergences after the policy are more plausibly attributed to the policy itself.",
    question: "The passage indicates that the synthetic-comparison method offers an advantage over the traditional method because the synthetic method",
    options: ["produces a comparison case whose pre-policy behavior more closely resembles that of the treated region", "eliminates the need to observe any region's economic history before the policy takes effect", "relies on a single neighboring region rather than a combination of many areas", "measures the effects of wage changes without reference to industry composition", "guarantees that no economic shocks will affect either region after the policy"],
    correct: 0,
    explanation: "The passage says the synthetic region is built to closely track the treated region's pre-policy trends, so divergences afterward can be attributed to the policy. That matching of pre-policy history is the stated advantage, giving (A). (B) is the reverse; the method depends on pre-policy history, not eliminating it. (C) inverts the method, which combines many areas rather than using one neighbor. (D) is unsupported; industry composition is cited as a problem for the old method, not something the new method ignores. (E) overreaches; nothing guarantees the absence of future shocks.",
  },
  {
    id: "gmat_0042", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "A recent report on remote work concluded that employees who work from home are more productive than their office-based counterparts, pointing to survey data in which remote workers reported completing more tasks per week. The report's author acknowledged, however, that the surveyed remote workers were disproportionately drawn from software and writing professions, whose output is comparatively easy to quantify in discrete tasks. Office-based workers in the sample, by contrast, more often held roles centered on meetings and coordination. The author nonetheless treated the task-completion figures as directly comparable across the two groups.",
    question: "Which of the following, if true, would most strengthen a challenge to the report's conclusion?",
    options: ["Employees in coordination-heavy roles contribute value that is not captured by counts of completed tasks.", "Some remote workers in the survey occasionally traveled to an office for meetings.", "The survey was administered to both groups using identical questions.", "Software professionals report higher job satisfaction when permitted to work from home.", "Office-based workers in the sample worked slightly longer hours than remote workers."],
    correct: 0,
    explanation: "The report compares task counts, but the two groups do work of different measurable kinds; office workers do meeting/coordination roles. (A) directly undermines the comparison by showing that task counts miss real value from coordination roles, so the higher task numbers for remote workers don't establish greater productivity. That most strengthens the challenge. (B) is minor and doesn't affect the productivity comparison. (C) actually supports the report's fairness rather than challenging it. (D) concerns satisfaction, not productivity. (E) about hours is tangential and, if anything, cuts unpredictably; it does not address the flawed task-count comparison.",
  },
  {
    id: "gmat_0043", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 3,
    passage: "The conventional account of the decline of a certain medieval trading league attributes its collapse to the rise of centralized nation-states that could tax and regulate commerce beyond the league's reach. A revisionist historian argues instead that the league's decline was already underway before these states consolidated their power, and that the true cause lay in the league's own governance: member cities retained veto power over collective decisions, which increasingly paralyzed responses to shifting trade routes. The historian concedes that the emergence of strong states accelerated the final dissolution but maintains that it did not initiate the decline. Critics respond that the paralysis the historian describes was itself a response to external pressure from those very states, making the two explanations less separable than the historian allows.",
    question: "The critics' response, as described in the passage, challenges the revisionist historian's argument by",
    options: ["suggesting that a cause the historian treats as internal may have been produced by the external factor the historian downplays", "denying that the league's member cities ever held veto power over collective decisions", "arguing that centralized nation-states consolidated their power earlier than the historian assumes", "asserting that shifting trade routes, rather than governance, were the league's undoing", "conceding that the historian has correctly identified the initial cause of the decline"],
    correct: 0,
    explanation: "The historian distinguishes an internal cause (veto-induced paralysis) from an external one (strong states), claiming the internal cause initiated the decline. The critics reply that the paralysis was itself a response to external state pressure, blurring the internal/external line. That is precisely (A): a supposedly internal cause may have been produced by the external factor. (B) contradicts the passage; the critics do not deny veto power existed. (C) is a different argument about timing that the critics do not make. (D) misattributes a claim; trade-route shifts are the trigger the veto power failed to address, not the critics' thesis. (E) is the opposite of a challenge and misstates the critics' position.",
  },
  {
    id: "gmat_0044", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 3,
    passage: "In pharmacology, a drug's therapeutic index is the ratio between the dose that produces toxicity and the dose that produces the desired effect; a higher index indicates a wider margin of safety. A newly developed compound has a therapeutic index roughly three times that of the standard treatment it might replace. Yet clinicians have been reluctant to adopt it, because its effect on the body varies far more from patient to patient than the standard drug's does. A dose calibrated to the average patient may therefore be ineffective in some individuals and unexpectedly toxic in others, even though the compound's index, computed from average responses, appears reassuring.",
    question: "The passage most strongly supports which of the following inferences about the therapeutic index?",
    options: ["A favorable therapeutic index does not by itself ensure that a drug will be safe and effective across a diverse population of patients.", "A drug's therapeutic index tends to decrease as variability in patient response increases.", "The standard treatment is unsafe for patients whose responses deviate from the average.", "Clinicians should prefer any drug whose therapeutic index exceeds that of existing treatments.", "Variability in patient response is the primary determinant of a drug's therapeutic index."],
    correct: 0,
    explanation: "The passage shows a drug with a strong (high) therapeutic index that clinicians still resist because patient-to-patient variability can make an average-based dose ineffective or toxic for individuals. The supported inference is that a favorable index alone does not guarantee safety and efficacy across diverse patients, which is (A). (B) misstates the relationship; the index is computed from average responses and the passage does not say variability lowers the index; it says the index can look reassuring despite high variability. (C) overreaches; the standard drug is described as less variable, not unsafe at the margins. (D) is contradicted by the very reluctance the passage describes. (E) is wrong because the passage says the index derives from average responses, not from variability.",
  },
  {
    id: "gmat_0045", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 3,
    passage: "Literary scholars have long debated why a particular nineteenth-century novelist revised her early works so extensively for later editions. One camp holds that the revisions reflect maturing artistic judgment, pointing to tighter prose and more consistent characterization in the revised texts. Another camp contends that the changes were largely concessions to the tastes of a changing readership, noting that the novelist removed passages that had drawn criticism from reviewers. A third scholar observes that the two explanations need not conflict: an author's evolving sense of craft may itself be shaped by the reception of her earlier work, so that responsiveness to critics and the refinement of artistic judgment become one and the same process.",
    question: "The position of the third scholar is best described as one that",
    options: ["treats the two competing explanations as potentially aspects of a single underlying process rather than as alternatives", "rejects both competing explanations in favor of a third, unrelated account of the revisions", "endorses the first camp's explanation while dismissing the second camp's as unsupported", "argues that the novelist's revisions actually weakened the artistic quality of her early works", "maintains that reviewers' criticism had no genuine influence on the novelist's revisions"],
    correct: 0,
    explanation: "The third scholar says the two explanations 'need not conflict' and that responsiveness to critics and refinement of judgment can be 'one and the same process.' That reframes the two rival accounts as facets of a single process, giving (A). (B) is wrong; the scholar does not reject both for an unrelated account but reconciles them. (C) is wrong; the scholar does not privilege the first camp over the second. (D) introduces a value judgment (revisions weakened the works) the scholar never makes. (E) contradicts the scholar's view, which grants that critical reception genuinely shaped the author's craft.",
  },
  {
    id: "gmat_0046", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "A technology firm introduced a policy of publishing the salary range for every open position, expecting that transparency would speed up hiring by attracting candidates confident they would be fairly paid. Applications did rise after the policy took effect. Hiring managers reported, however, that the average time to fill a position lengthened, because many applicants who might once have been persuaded to accept an offer now used the published ranges as a floor and negotiated more assertively. The firm's leadership continues to defend the policy on the grounds that it improved employee retention among those eventually hired.",
    question: "Which of the following best describes the relationship between the second sentence ('Applications did rise after the policy took effect') and the sentence that follows it?",
    options: ["The second sentence reports an outcome consistent with the firm's expectation, and the following sentence introduces an unanticipated effect that worked against that expectation.", "The second sentence states the firm's central goal, and the following sentence explains how that goal was achieved.", "The second sentence presents evidence that the policy failed, and the following sentence offers a competing interpretation of that evidence.", "The second sentence describes a cause, and the following sentence describes the sole effect of that cause.", "The second sentence raises an objection to the policy, and the following sentence rebuts it."],
    correct: 0,
    explanation: "The firm expected transparency to speed hiring; the rise in applications is consistent with that hope, but the next sentence reveals an unanticipated downside: time to fill lengthened because applicants negotiated harder. So the rising applications match the expectation while the following sentence introduces a countervailing effect, which is (A). (B) is wrong; the firm's goal was faster hiring, not more applications per se, and the next sentence describes a setback, not achievement. (C) mischaracterizes the rise in applications as evidence of failure. (D) is wrong; the following sentence describes an unexpected effect, not the sole effect, of the policy. (E) misreads the logic; neither sentence is an objection-and-rebuttal pair.",
  },
  {
    id: "gmat_0047", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 1,
    question: "If x is a positive integer, is x even?\n\n(1) x + 3 is odd.\n(2) 5x is even.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 3,
    explanation: "Statement (1): x + 3 is odd means x must be even (even + odd = odd), so x is even — sufficient. Statement (2): 5x is even. Since 5 is odd, 5x is even only when x is even — sufficient. Each statement alone answers the question with a definite 'yes,' so the answer is EACH ALONE. Choices (1) and (2) understate one statement; (3) is wrong because neither is needed jointly; (5) is wrong because both settle it.",
  },
  {
    id: "gmat_0048", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 1,
    question: "A jar contains only red and blue marbles. How many red marbles are in the jar?\n\n(1) The jar contains 40 marbles in total.\n(2) The number of blue marbles is 3 times the number of red marbles.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 2,
    explanation: "Let R = red, B = blue. Statement (1) gives R + B = 40, but R alone is not fixed — insufficient. Statement (2) gives B = 3R, a ratio only, so R could be any value — insufficient. Together: R + 3R = 40, so 4R = 40 and R = 10 — sufficient. The answer is BOTH TOGETHER. (1) and (2) fail alone; (4) is wrong since neither alone works; (5) is wrong because together they pin R down.",
  },
  {
    id: "gmat_0049", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 2,
    question: "Is the integer n divisible by 6?\n\n(1) n is divisible by 3.\n(2) n is divisible by 4.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 2,
    explanation: "Divisibility by 6 requires divisibility by both 2 and 3. Statement (1): n divisible by 3 does not guarantee divisibility by 2 (e.g., 9 is not divisible by 6, but 12 is) — insufficient. Statement (2): n divisible by 4 gives divisibility by 2 but not by 3 (e.g., 4 is not divisible by 6, but 12 is) — insufficient. Together: n is divisible by 3 and by 4, hence by 2, so n is divisible by 6 — sufficient. The answer is BOTH TOGETHER. A common trap is picking (5), forgetting that divisibility by 4 supplies the needed factor of 2 alongside the 3.",
  },
  {
    id: "gmat_0050", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 2,
    question: "What is the value of the two-digit positive integer k?\n\n(1) The tens digit of k is twice the units digit of k.\n(2) The sum of the digits of k is 9.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 2,
    explanation: "Let t = tens digit, u = units digit. Statement (1): t = 2u gives 21, 42, 63, 84 (u from 1 to 4; u = 0 gives t = 0, not two-digit) — many values, insufficient. Statement (2): t + u = 9 gives 18, 27, 36, 45, 54, 63, 72, 81, 90 — insufficient. Together: t = 2u and t + u = 9, so 2u + u = 9, u = 3, t = 6, giving k = 63 uniquely — sufficient. The answer is BOTH TOGETHER. Neither alone narrows to one value; (5) is wrong because the combined equations have a single solution.",
  },
  {
    id: "gmat_0051", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 2,
    question: "Is x > y?\n\n(1) x - y > -2\n(2) x + 3 > y + 5",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 1,
    explanation: "We want to know whether x - y > 0. Statement (1): x - y > -2 allows x - y = 1 (yes) or x - y = -1 (no) — insufficient. Statement (2): x + 3 > y + 5 simplifies to x - y > 2, which forces x - y > 0, so x > y — sufficient. The answer is statement (2) ALONE. Statement (1)'s bound of -2 is too loose; (4) fails because (1) alone is not enough; (5) is wrong because (2) alone settles it.",
  },
  {
    id: "gmat_0052", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 2,
    question: "A store sold pens at $2 each and notebooks at $5 each, and nothing else. What was the store's total revenue from these sales?\n\n(1) The store sold a total of 30 items.\n(2) The store sold 12 notebooks.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 2,
    explanation: "Let p = pens, n = notebooks; revenue = 2p + 5n. Statement (1): p + n = 30, but the split between $2 and $5 items is unknown, so revenue varies — insufficient. Statement (2): n = 12 fixes notebook revenue at $60 but leaves p unknown — insufficient. Together: p + n = 30 and n = 12 give p = 18, so revenue = 2(18) + 5(12) = 36 + 60 = $96 — sufficient. The answer is BOTH TOGETHER. Neither alone determines both counts.",
  },
  {
    id: "gmat_0053", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 2,
    question: "If p and q are positive integers, what is the value of p?\n\n(1) The greatest common divisor of p and q is 6.\n(2) q = 18 and the least common multiple of p and 18 is 36.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 2,
    explanation: "Statement (1): GCD(p, q) = 6 tells us 6 divides p, but p could be 6, 12, 18, and so on — insufficient. Statement (2): q = 18 and LCM(p, 18) = 36. The values of p that give LCM(p, 18) = 36 are p = 4, 12, and 36 (each has LCM 36 with 18), so p is not unique — insufficient. Together: GCD(p, 18) = 6 must also hold. Checking the candidates from (2): GCD(4, 18) = 2, GCD(12, 18) = 6, GCD(36, 18) = 18. Only p = 12 satisfies both conditions, so p = 12 uniquely — sufficient. The answer is BOTH TOGETHER.",
  },
  {
    id: "gmat_0054", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 3,
    question: "Each of the 25 students in a class studies French, Spanish, or both. How many students study both French and Spanish?\n\n(1) 18 students study French and 15 students study Spanish.\n(2) 5 students study only Spanish.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 0,
    explanation: "Since every student studies at least one language, the union covers all 25: |French| + |Spanish| - |Both| = 25. Statement (1): 18 + 15 - Both = 25, so Both = 8 — sufficient. Statement (2): 5 study only Spanish, so 20 study French (those not in the only-Spanish group). But the number studying both equals 20 minus those who study only French, which is unknown; Both is not fixed — insufficient. Since (1) alone determines Both and (2) alone does not, the answer is statement (1) ALONE. Choice (4) fails because (2) leaves Both undetermined.",
  },
  {
    id: "gmat_0055", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 3,
    question: "Is the positive integer n a prime number?\n\n(1) n has exactly two positive divisors.\n(2) n is odd and 20 < n < 30.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 0,
    explanation: "Statement (1): Having exactly two positive divisors (1 and itself) is the definition of a prime number, so n is prime — sufficient, definite 'yes.' Statement (2): odd n with 20 < n < 30 gives 21, 23, 25, 27, 29. Among these 23 and 29 are prime but 21, 25, 27 are not — the answer varies, insufficient. The answer is statement (1) ALONE. Choice (4) fails because (2) alone gives conflicting answers; (3) and (5) are wrong because (1) alone fully settles it.",
  },
  {
    id: "gmat_0056", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 3,
    question: "What is the value of x²?\n\n(1) x² - 5x + 6 = 0\n(2) x < 2.5",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 2,
    explanation: "Statement (1): x² - 5x + 6 = 0 factors as (x - 2)(x - 3) = 0, so x = 2 (x² = 4) or x = 3 (x² = 9) — two values, insufficient. Statement (2): x < 2.5 alone leaves x, and thus x², wide open — insufficient. Together: from (1) x is 2 or 3; (2) requires x < 2.5, eliminating 3 and leaving x = 2, so x² = 4 — sufficient. The answer is BOTH TOGETHER. Choice (1) fails due to the two roots; (2) alone gives nothing; (5) is wrong because the constraint isolates one root.",
  },
  {
    id: "gmat_0057", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 3,
    question: "Machine A and Machine B each work at their own constant rate. Working together, how long does it take them to complete one job?\n\n(1) Machine A alone completes the job in 6 hours.\n(2) Machine B alone works at twice the rate of Machine A.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 2,
    explanation: "Combined time depends on both rates. Statement (1): A's rate is 1/6 job per hour, but B's rate is unknown — insufficient. Statement (2): B's rate is twice A's, a relationship only, with no absolute value — insufficient. Together: A = 1/6 per hour, B = 2/6 = 1/3 per hour, combined = 1/6 + 1/3 = 1/2 job per hour, so the job takes 2 hours — sufficient. The answer is BOTH TOGETHER. Neither statement alone supplies both absolute rates; (5) is wrong because together the rates are fully determined.",
  },
  {
    id: "gmat_0058", topicId: 2, domain: "Data Insights", skill: "Data Sufficiency", difficulty: 3,
    question: "If a, b, and c are consecutive integers with a < b < c, is their product abc divisible by 24?\n\n(1) a is even.\n(2) b is divisible by 3.",
    options: ["Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.", "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.", "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.", "EACH statement ALONE is sufficient.", "Statements (1) and (2) TOGETHER are NOT sufficient."],
    correct: 0,
    explanation: "For three consecutive integers, one is always divisible by 3, so a factor of 3 is automatic; the question reduces to whether abc contributes a factor of 8. Statement (1): a is even, so a and c are both even (they share parity). Among two consecutive even numbers a and a+2, one is divisible by 4, so a(a+2) is divisible by 4 × 2 = 8; combined with the guaranteed factor of 3, abc is divisible by 24 — sufficient. Statement (2): b divisible by 3 only restates the automatic factor of 3 and says nothing about the power of 2. For example, a=2, b=3, c=4 gives 24 (divisible), but a=5, b=6, c=7 gives 210, which is not divisible by 24 — the answer varies, insufficient. The answer is statement (1) ALONE.",
  },
  {
    id: "gmat_0059", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 1,
    passage: "A pie chart (described in text) shows how a household's $4,000 monthly budget is divided.\n\nCategory | Share of Budget\nHousing | 35%\nFood | 20%\nTransportation | 15%\nSavings | 10%\nOther | 20%",
    question: "How many dollars per month does the household allocate to Transportation?",
    options: ["$400", "$600", "$800", "$1,400"],
    correct: 1,
    explanation: "Transportation is 15% of the $4,000 budget: 0.15 * 4,000 = $600. Correct answer: $600. $400 is 10% (the Savings share). $800 is 20% (Food or Other). $1,400 is 35% (Housing). Only $600 matches Transportation's 15% slice.",
  },
  {
    id: "gmat_0060", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 1,
    passage: "A bar chart (described in text) shows monthly rainfall in millimeters for a town.\n\nMonth | Rainfall (mm)\nJanuary | 40\nFebruary | 55\nMarch | 70\nApril | 35\nMay | 50",
    question: "Rainfall in March exceeded rainfall in April by what percent of April's rainfall?",
    options: ["50%", "75%", "100%", "125%", "200%"],
    correct: 2,
    explanation: "March = 70 mm, April = 35 mm. The excess is 70 - 35 = 35 mm. As a percent of April's rainfall: 35/35 = 1.00 = 100%. The correct answer is 100%. A reader computing 35/70 = 50% (percent of March instead of April) picks 50%. A reader computing 70/35 = 200% confuses the ratio with the percent excess. 75% and 125% are arithmetic traps with no clean basis. Only 100% is uniquely defensible.",
  },
  {
    id: "gmat_0061", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 1,
    passage: "The table shows the number of bicycles rented from a shop over four days.\n\nDay | Bicycles Rented\nMonday | 18\nTuesday | 24\nWednesday | 30\nThursday | 12\n\nTotal across the four days: 84",
    question: "Wednesday's rentals accounted for what fraction of the four-day total?",
    options: ["3/14", "2/7", "5/14", "3/7"],
    correct: 2,
    explanation: "Wednesday = 30 rentals; the four-day total = 84. The fraction is 30/84 = 5/14. Correct answer: 5/14. The distractor 3/14 comes from Monday's 18/84 = 3/14. 2/7 = 24/84 is Tuesday's share. 3/7 = 36/84 does not match any single day. Only 5/14 corresponds to Wednesday's 30 out of 84.",
  },
  {
    id: "gmat_0062", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 2,
    passage: "The table gives quarterly revenue (in thousands of dollars) for two product lines at a company during one year.\n\nQuarter | Product A | Product B\nQ1 | 120 | 90\nQ2 | 140 | 110\nQ3 | 130 | 150\nQ4 | 160 | 140\nAnnual total | 550 | 490",
    question: "In how many of the four quarters did Product B's revenue account for more than 50% of the combined revenue of the two products in that quarter?",
    options: ["None", "One", "Two", "Three", "Four"],
    correct: 1,
    explanation: "Product B exceeds 50% of the quarter's combined total only when B > A. Compare each quarter: Q1 (90 vs 120, B<A), Q2 (110 vs 140, B<A), Q3 (150 vs 130, B>A), Q4 (140 vs 160, B<A). Only Q3 has B greater than A, so B exceeds 50% in exactly one quarter. 'None' misses Q3. 'Two' or more wrongly counts quarters where B is close to but below A (e.g., Q4 140 vs 160). 'Four' ignores the comparison entirely. One is uniquely correct.",
  },
  {
    id: "gmat_0063", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 2,
    passage: "A line graph (described in text) tracks a stock's closing price over five trading days.\n\nDay | Closing Price ($)\nDay 1 | 50\nDay 2 | 55\nDay 3 | 52\nDay 4 | 58\nDay 5 | 62",
    question: "The largest single-day percent increase in closing price, relative to the previous day's close, occurred from which day to the next?",
    options: ["Day 1 to Day 2", "Day 2 to Day 3", "Day 3 to Day 4", "Day 4 to Day 5"],
    correct: 2,
    explanation: "Compute each day-over-day percent change relative to the prior close. Day 1 to 2: (55-50)/50 = 10.0%. Day 2 to 3: (52-55)/55 = -5.5% (a decrease). Day 3 to 4: (58-52)/52 = 6/52 = 11.5%. Day 4 to 5: (62-58)/58 = 6.9%. The largest increase is Day 3 to Day 4 at about 11.5%, exceeding Day 1 to 2's 10%. Correct answer: Day 3 to Day 4. A reader stopping at the +5 dollar jump from Day 1 to 2 without dividing by the base picks that option; the +6 dollar jump on a base of 52 is a larger percent. Day 2 to 3 is a decrease. Day 4 to 5 is only 6.9%.",
  },
  {
    id: "gmat_0064", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 2,
    passage: "The table shows the composition of a 200-student graduating class by major and by whether the student studied abroad.\n\nMajor | Studied Abroad | Did Not Study Abroad\nBusiness | 30 | 50\nEngineering | 15 | 45\nArts | 25 | 35\nColumn totals: Studied Abroad = 70; Did Not = 130",
    question: "Among students who studied abroad, what fraction were Business majors?",
    options: ["3/20", "3/8", "3/7", "3/10", "1/2"],
    correct: 2,
    explanation: "Students who studied abroad total 70 (30 + 15 + 25). Business majors among them number 30. The fraction is 30/70 = 3/7. Correct answer: 3/7. The distractor 3/20 comes from 30/200 (Business abroad over the whole class). 3/8 comes from 30/80, dividing by all Business students (30 + 50). 3/10 comes from 30/100 (an unrelated round number). 1/2 is a careless guess. Only 3/7 uses the correct denominator (all study-abroad students).",
  },
  {
    id: "gmat_0065", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 2,
    passage: "The table shows the population (in thousands) of four towns in two census years.\n\nTown | Year 2000 | Year 2010\nAlbern | 60 | 78\nBrixton | 80 | 92\nCarden | 45 | 63\nDelmar | 100 | 115",
    question: "Which town had the greatest percent increase in population from 2000 to 2010?",
    options: ["Albern", "Brixton", "Carden", "Delmar"],
    correct: 2,
    explanation: "Percent increase = (2010 - 2000)/2000. Albern: 18/60 = 30%. Brixton: 12/80 = 15%. Carden: 18/45 = 40%. Delmar: 15/100 = 15%. Carden's 40% is the greatest, even though its absolute increase (18) equals Albern's, because Carden's starting population is smaller. Correct answer: Carden. A reader comparing absolute increases sees Albern and Carden both +18 and Delmar +15, and might pick Albern; but percent increase depends on the base. Delmar and Brixton grew only 15%. Carden is uniquely correct.",
  },
  {
    id: "gmat_0066", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 3,
    passage: "A table reports a subscription service's data for three consecutive years.\n\nYear | Subscribers (thousands) | Revenue ($ millions)\nYear 1 | 400 | 24\nYear 2 | 500 | 32\nYear 3 | 480 | 36",
    question: "In which year(s) was the average (mean) annual revenue per subscriber greater than $70?",
    options: ["Year 1 only", "Year 3 only", "Year 2 and Year 3 only", "Year 1 and Year 3 only", "All three years"],
    correct: 1,
    explanation: "Revenue per subscriber = revenue divided by subscribers, with units aligned: Year 1 = $24,000,000 / 400,000 = $60. Year 2 = $32,000,000 / 500,000 = $64. Year 3 = $36,000,000 / 480,000 = $75. Only Year 3 exceeds $70, so the answer is Year 3 only. A reader who forgets to align the thousand/million scales, or who compares raw ratios, may include Year 2 (64) thinking it clears 70, giving 'Year 2 and Year 3.' Year 1 (60) and Year 2 (64) both fall below 70. Year 3 alone is uniquely correct.",
  },
  {
    id: "gmat_0067", topicId: 2, domain: "Data Insights", skill: "Graphics and Table Interpretation", difficulty: 3,
    passage: "A stacked-bar chart (described in text) shows a factory's monthly output, with total units produced and the number found defective.\n\nMonth | Total Produced | Defective Units\nJanuary | 500 | 25\nFebruary | 600 | 42\nMarch | 750 | 30\nApril | 800 | 56",
    question: "Ranking the months from lowest to highest defect rate (defective units as a percent of that month's total produced), which month has the second-lowest defect rate?",
    options: ["January", "February", "March", "April"],
    correct: 0,
    explanation: "Compute each defect rate: January 25/500 = 5.0%; February 42/600 = 7.0%; March 30/750 = 4.0%; April 56/800 = 7.0%. Ranked lowest to highest: March 4.0% (lowest), January 5.0% (second-lowest), then February and April tied at 7.0%. The second-lowest defect rate is January. Correct answer: January. A reader who ranks by raw defective counts (25, 30, 42, 56) would call January lowest and March second, mistakenly picking March. Comparing rates, not counts, is required. February and April are the highest, not second-lowest. January is uniquely correct.",
  },
  {
    id: "gmat_0068", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 1,
    passage: "A logistics company evaluates two courier contractors for a new delivery route.\n\nSource 1 (Rate Sheet):\n- Contractor A charges a flat $200 per day plus $1.50 per package delivered.\n- Contractor B charges a flat $50 per day plus $3.00 per package delivered.\n\nSource 2 (Route Memo):\n\"The new route requires deliveries every day. Daily package volume has been forecast, but the exact number varies. Management wants the cheaper contractor for the volume actually seen.\"",
    question: "At what daily package volume do Contractor A and Contractor B cost exactly the same amount for a single day?",
    options: ["50 packages", "75 packages", "100 packages", "150 packages", "200 packages"],
    correct: 2,
    explanation: "Set the daily costs equal: 200 + 1.50p = 50 + 3.00p. Subtract 50 and 1.50p from both sides: 150 = 1.50p, so p = 100. At 100 packages both cost $350. Distractor 50 divides the flat-fee difference (150) by 3.00 instead of by the per-package difference (1.50); 75 and 150 come from mis-subtracting one of the variable rates; 200 doubles the correct value. Only 100 balances the two full daily-cost expressions.",
  },
  {
    id: "gmat_0069", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 1,
    passage: "An online retailer applies three shipping tiers.\n\nSource 1 (Tier Table):\n| Tier | Order value required | Shipping fee |\n|----------|----------------------|-------------|\n| Standard | Under $35 | $6.99 |\n| Plus | $35 to $74.99 | $3.99 |\n| Prime | $75 or more | $0.00 |\n\nSource 2 (Order Log excerpt):\n\"Customer placed a cart totaling $68.40 before shipping. She then removed a $9.00 item and added a $17.60 item, then checked out.\"",
    question: "What shipping fee was applied at checkout?",
    options: ["$0.00", "$3.99", "$6.99", "$10.98"],
    correct: 0,
    explanation: "Start at $68.40, remove $9.00 to get $59.40, then add $17.60 to reach $77.00. Because $77.00 is at least $75, the order qualifies for the Prime tier at $0.00. Distractor $3.99 keeps the original $68.40 (Plus tier) without applying both edits; $6.99 wrongly treats the total as under $35; $10.98 nonsensically sums two fees. Only $0.00 reflects the correct final cart value.",
  },
  {
    id: "gmat_0070", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 2,
    passage: "A city transit authority is choosing a monthly pass structure.\n\nSource 1 (Fare Options):\n- Pay-per-ride: $2.75 per ride, no cap.\n- Monthly Pass: $110 flat, unlimited weekday rides; weekends excluded.\n\nSource 2 (Rider Survey Note):\n\"Commuter Dana takes 2 rides on each weekday (to and from work) and does not ride on weekends for commuting. This month has 22 weekdays. Dana also expects 3 weekend personal-errand rides, which she pays per ride under either plan because the pass excludes weekend service.\"",
    question: "How much would the Monthly Pass save Dana this month compared with paying per ride for every ride she takes?",
    options: ["$1.00", "$11.00", "$12.50", "$19.25", "The pass would cost more than paying per ride."],
    correct: 1,
    explanation: "Weekday rides: 22 x 2 = 44, all covered by the pass. Paying per ride for those 44 = 44 x $2.75 = $121.00 versus $110.00 for the pass, a saving of $11.00. The 3 weekend rides cost $2.75 each under BOTH plans (pass excludes weekends), so they cancel and do not affect the comparison. Distractor $19.25 wrongly adds the weekend rides (3 x $2.75 = $8.25) to the savings; $12.50 and $1.00 come from miscounting weekday rides; 'costs more' ignores that 44 rides already exceed the pass price.",
  },
  {
    id: "gmat_0071", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 2,
    passage: "A subscription software firm reports quarterly figures.\n\nSource 1 (Q3 Metrics):\n- Customers at start of Q3: 1,200\n- New customers added during Q3: 300\n- Customers who churned (cancelled) during Q3: 150\n- Monthly recurring revenue (MRR) per active customer: constant at $40\n\nSource 2 (Finance Note):\n\"MRR is measured at the END of each quarter using the customer count active at that moment. Churned customers are removed before the end-of-quarter count; new customers are included.\"",
    question: "What is the firm's MRR at the end of Q3?",
    options: ["$48,000", "$54,000", "$57,000", "$60,000", "$66,000"],
    correct: 1,
    explanation: "End-of-Q3 active customers = 1,200 + 300 - 150 = 1,350. MRR = 1,350 x $40 = $54,000. Distractor $48,000 uses the starting 1,200; $60,000 uses 1,500 (adds new, forgets churn); $57,000 uses 1,425 (nets only half the churn); $66,000 adds both new and churned to the base. Only $54,000 correctly nets new against churned per the Finance Note.",
  },
  {
    id: "gmat_0072", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 2,
    passage: "A manufacturer sources a component from two suppliers.\n\nSource 1 (Quotes):\n- Supplier X: $12.00 per unit; defect rate 5%. Defective units are unusable and not replaced.\n- Supplier Y: $13.20 per unit; defect rate 1%. Defective units are unusable and not replaced.\n\nSource 2 (Procurement Rule):\n\"Compare suppliers on effective cost per GOOD (non-defective) unit, and buy from whichever gives the lower effective cost per good unit. Round to the nearest cent.\"",
    question: "Which supplier has the lower effective cost per good unit, and what is that cost?",
    options: ["Supplier X, at $12.00", "Supplier X, at $12.63", "Supplier Y, at $13.20", "Supplier Y, at $13.33", "The two suppliers tie at about $12.63."],
    correct: 1,
    explanation: "Effective cost = price / fraction good. Supplier X: $12.00 / 0.95 = $12.63. Supplier Y: $13.20 / 0.99 = $13.33. X ($12.63) is lower than Y ($13.33). 'Supplier X at $12.00' ignores the defect adjustment; 'Supplier Y at $13.20' ignores adjustment and picks the wrong supplier; 'Supplier Y at $13.33' computes Y correctly but names the wrong winner; the tie option is false because the adjusted costs differ. Only 'Supplier X, at $12.63' is both correct and correctly identified.",
  },
  {
    id: "gmat_0073", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 3,
    passage: "A regional bank scores and decides loan applications.\n\nSource 1 (Scoring Rules):\n- Base score starts at 600.\n- Add 40 if annual income is at least $80,000.\n- Add 30 if the applicant has no missed payments in the last 24 months.\n- Subtract 50 if debt-to-income (DTI) exceeds 40%.\n- Subtract 25 if the requested loan exceeds 3x annual income.\n\nSource 2 (Decision Table):\n| Final score | Decision |\n|-------------|--------------|\n| 660 or above| Auto-approve |\n| 620 to 659 | Manual review|\n| Below 620 | Auto-decline |\n\nSource 3 (Applicant File):\n\"Priya earns $92,000 per year, has had no missed payments in 30 months, carries a DTI of 44%, and requests a loan of $250,000.\"",
    question: "What decision does Priya's application receive?",
    options: ["Auto-approve", "Manual review", "Auto-decline", "Cannot be determined from the information given"],
    correct: 1,
    explanation: "Base 600. Income $92,000 >= $80,000: +40 = 640. No missed payments in 30 months covers the last 24 months: +30 = 670. DTI 44% > 40%: -50 = 620. Loan $250,000 vs 3x income = $276,000; since $250,000 does NOT exceed $276,000, the -25 does not apply, leaving 620. A score of 620 falls in the 620-659 band: Manual review. Auto-approve omits the DTI penalty; Auto-decline wrongly applies the -25 loan penalty; 'cannot be determined' is false because every input is specified.",
  },
  {
    id: "gmat_0074", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 3,
    passage: "A publisher compares e-book royalty structures for the same title, priced at $10.00 to the reader.\n\nSource 1 (Platform Terms):\n- Platform Alpha pays the author 70% of (list price minus a $0.30 per-copy delivery fee).\n- Platform Beta pays the author 60% of list price, with no delivery fee.\n\nSource 2 (Sales Forecast):\n\"The title is expected to sell 5,000 copies. Management will publish exclusively on whichever platform yields greater total author royalties for these 5,000 copies.\"",
    question: "Which platform yields greater total author royalties for 5,000 copies, and by how much?",
    options: ["Alpha, by $3,950", "Alpha, by $500", "Beta, by $1,050", "Beta, by $3,950", "They yield equal royalties."],
    correct: 0,
    explanation: "Alpha per copy: 70% of ($10.00 - $0.30) = 0.70 x $9.70 = $6.79. Beta per copy: 60% of $10.00 = $6.00. Alpha's per-copy advantage is $6.79 - $6.00 = $0.79. Over 5,000 copies: 5,000 x $0.79 = $3,950, so Alpha yields $3,950 more (Alpha total $33,950 vs Beta total $30,000). 'Alpha, by $500' and 'Beta' options mishandle the delivery fee or reverse the winner; 'equal' is false because the per-copy amounts differ. Only 'Alpha, by $3,950' matches both the correct winner and the correct gap.",
  },
  {
    id: "gmat_0075", topicId: 2, domain: "Data Insights", skill: "Two-Part and Multi-Source Reasoning", difficulty: 3,
    passage: "A hospital schedules operating-room (OR) time using two data sources.\n\nSource 1 (Procedure Durations, cleanup already included):\n| Procedure | Total OR time needed |\n|-----------|----------------------|\n| Type P | 90 minutes |\n| Type Q | 120 minutes |\n| Type R | 45 minutes |\n\nSource 2 (Scheduling Constraints):\n\"A single OR operates from 8:00 AM to 5:00 PM (9 hours). The listed 'Total OR time needed' already includes the mandatory cleanup between procedures, so no extra buffer is required between back-to-back cases. The OR must not run past 5:00 PM. On Tuesday the OR is committed to exactly two Type Q procedures and one Type P procedure; any remaining time may be filled with Type R procedures.\"",
    question: "What is the maximum number of Type R procedures that can be added to Tuesday's schedule?",
    options: ["2", "3", "4", "5", "7"],
    correct: 2,
    explanation: "Daily capacity = 9 hours = 540 minutes. Committed time = two Type Q (2 x 120 = 240) + one Type P (90) = 330 minutes. Remaining = 540 - 330 = 210 minutes. Each Type R needs 45 minutes, so floor(210 / 45) = 4 (using 180 minutes, with 30 minutes idle). Distractor 7 forgets one Type Q (uses 120 + 90 = 210 committed, leaving 330, then 330/45 = 7); 5 rounds 210/45 up instead of down; 3 subtracts an unneeded buffer; 2 double-counts committed time. Only 4 fits within the 210 remaining minutes without running past 5:00 PM.",
  },
];

export const GMAT_QUESTION_COUNT = GMAT_QUESTIONS.length;

export function getGMATQuestions(topicId?: number): GMATQuestion[] {
  return topicId === undefined ? GMAT_QUESTIONS : GMAT_QUESTIONS.filter((q) => q.topicId === topicId);
}
