export interface GMATFlashcard {
  id: number;
  front: string;
  back: string;
  domain: string;      // one of the domain ids below
  domainName: string;
  category: string;    // 'definition' | 'concept' | 'formula' | 'strategy' | 'grammar' | 'mnemonic'
  topics: string[];    // ['GMAT']
}

export const GMAT_FLASHCARD_DOMAINS = [
  { id: 'quant',         label: 'Quant',    name: 'Quantitative Reasoning', count: 28 },
  { id: 'verbal',        label: 'Verbal',   name: 'Verbal Reasoning',       count: 18 },
  { id: 'data_insights', label: 'DI',       name: 'Data Insights',          count: 18 },
  { id: 'strategy',      label: 'Strategy', name: 'Test Strategy',          count: 8 },
];

export const GMAT_FLASHCARDS: GMATFlashcard[] = [
  // ===================== QUANT (28) =====================
  {
    id: 1,
    front: 'What is a prime number?',
    back: 'A positive integer greater than 1 with exactly two distinct factors: 1 and itself. 2 is the only even prime and the smallest prime. 1 is not prime. Primes under 20: 2, 3, 5, 7, 11, 13, 17, 19.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'definition',
    topics: ['GMAT'],
  },
  {
    id: 2,
    front: 'Rules for even and odd results of operations.',
    back: 'even +/- even = even; odd +/- odd = even; even +/- odd = odd. even x anything = even; odd x odd = odd. Parity questions can often be solved by testing one even and one odd case rather than algebra.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 3,
    front: 'Divisibility rules for 3, 4, 6, 8, and 9.',
    back: 'Divisible by 3 if the digit sum is divisible by 3; by 9 if the digit sum is divisible by 9. By 4 if the last two digits form a multiple of 4; by 8 if the last three digits form a multiple of 8. By 6 if divisible by both 2 and 3.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 4,
    front: 'How do you find the number of factors of an integer?',
    back: 'Prime-factorize the integer, add 1 to each exponent, then multiply the results. For 72 = 2^3 x 3^2, the count is (3+1)(2+1) = 12 factors. This counts all positive divisors.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 5,
    front: 'Relationship between GCF and LCM of two numbers.',
    back: 'For any two positive integers a and b: GCF(a,b) x LCM(a,b) = a x b. The GCF (greatest common factor) uses the lowest shared prime powers; the LCM (least common multiple) uses the highest prime powers across both numbers.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 6,
    front: 'Exponent rules you must know cold.',
    back: 'a^m x a^n = a^(m+n); a^m / a^n = a^(m-n); (a^m)^n = a^(mn); a^0 = 1 for nonzero a; a^(-n) = 1 / a^n. A negative base to an even power is positive; to an odd power is negative.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 7,
    front: 'How do fractional exponents work?',
    back: 'a^(1/n) is the nth root of a, and a^(m/n) equals the nth root of a raised to the m power. For example, 8^(2/3) = (cube root of 8)^2 = 2^2 = 4. Rewriting roots as fractional exponents simplifies most GMAT radical problems.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 8,
    front: 'The three common algebraic factoring patterns.',
    back: 'Difference of squares: a^2 - b^2 = (a+b)(a-b). Perfect square: a^2 + 2ab + b^2 = (a+b)^2. Perfect square: a^2 - 2ab + b^2 = (a-b)^2. Recognizing these lets you factor quickly instead of expanding.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 9,
    front: 'The quadratic formula.',
    back: 'For ax^2 + bx + c = 0 with a not equal to 0, x = (-b plus or minus the square root of (b^2 - 4ac)) / (2a). The discriminant b^2 - 4ac tells you the number of real roots: positive gives two, zero gives one, negative gives none.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 10,
    front: 'The basic percent-change formula.',
    back: 'Percent change = (new value - original value) / original value x 100. A rise from 40 to 50 is +25 percent; a drop from 50 to 40 is -20 percent. The base of comparison is always the original, so increases and decreases are not symmetric.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 11,
    front: 'How do successive percent changes combine?',
    back: 'They multiply, not add. A 20 percent increase followed by a 20 percent decrease gives 1.20 x 0.80 = 0.96, a net 4 percent loss. Use multipliers (1 + rate for increase, 1 - rate for decrease) to chain any sequence of changes.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 12,
    front: 'Simple interest vs compound interest formulas.',
    back: 'Simple: A = P(1 + rt). Compound: A = P(1 + r/n)^(nt), where n is compounding periods per year. P is principal, r the annual rate as a decimal, t years. Compounding always yields more than simple interest over the same period.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 13,
    front: 'The core rate equation and its variants.',
    back: 'Distance = rate x time. Work problems use Work = rate x time. For combined work, add rates: if one worker finishes in a hours and another in b hours, together they take ab / (a + b) hours.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 14,
    front: 'How do you find an average speed for a round trip?',
    back: 'Average speed = total distance / total time, never the simple average of the two speeds. For equal distances at speeds x and y, the average is the harmonic mean 2xy / (x + y). Time weights slower legs more heavily.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 15,
    front: 'Weighted average concept.',
    back: 'When groups of different sizes are combined, the overall average lies closer to the larger group. Weighted average = (sum of each value x its weight) / (sum of weights). Mixture and blended-price problems are weighted averages in disguise.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 16,
    front: 'Permutations vs combinations.',
    back: 'Use permutations when order matters: nPr = n! / (n - r)!. Use combinations when order does not matter: nCr = n! / (r!(n - r)!). Committees and groups are combinations; rankings, seatings, and passwords are permutations.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 17,
    front: 'Basic probability rules.',
    back: 'P(event) = favorable outcomes / total outcomes. P(not A) = 1 - P(A). For independent events, P(A and B) = P(A) x P(B). For mutually exclusive events, P(A or B) = P(A) + P(B); otherwise subtract P(A and B).',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 18,
    front: 'Sum of the first n consecutive integers.',
    back: 'Sum = n(n + 1) / 2. More generally, the sum of any evenly spaced set equals the average of the first and last terms multiplied by the number of terms: sum = ((first + last) / 2) x count.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 19,
    front: 'Properties of an arithmetic sequence.',
    back: 'Consecutive terms differ by a constant d. The nth term is a1 + (n - 1)d. In any evenly spaced set the mean equals the median, so the sum is just the mean times the number of terms. Counting terms: (last - first) / d + 1.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 20,
    front: 'The Pythagorean theorem and common triples.',
    back: 'In a right triangle, leg^2 + leg^2 = hypotenuse^2. Memorize the triples 3-4-5, 5-12-13, 8-15-17, and 7-24-25 and their multiples to save time. Recognizing a triple avoids computing a square root.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 21,
    front: 'Ratios in the two special right triangles.',
    back: 'A 45-45-90 triangle has sides in ratio 1 : 1 : square root of 2. A 30-60-90 triangle has sides in ratio 1 : square root of 3 : 2, with the shortest side opposite the 30 degree angle. These appear constantly in geometry problems.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 22,
    front: 'Area formulas for the common shapes.',
    back: 'Triangle: (1/2) x base x height. Rectangle: length x width. Circle: pi x r^2, circumference 2 x pi x r. Trapezoid: (1/2)(base1 + base2) x height. Parallelogram: base x height.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 23,
    front: 'Slope and the equation of a line.',
    back: 'Slope m = (y2 - y1) / (x2 - x1) = rise over run. Slope-intercept form is y = mx + b, where b is the y-intercept. Parallel lines share the same slope; perpendicular slopes are negative reciprocals (product equals -1).',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'formula',
    topics: ['GMAT'],
  },
  {
    id: 24,
    front: 'What is Data Sufficiency and what does it actually ask?',
    back: 'Data Sufficiency gives a question plus two statements. You do not solve for the value; you decide whether the statements provide ENOUGH information to answer. A statement is sufficient only if it yields one definite answer (or a definite yes/no).',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 25,
    front: 'The five fixed answer choices in Data Sufficiency.',
    back: '(A) Statement 1 alone is sufficient, but 2 alone is not. (B) Statement 2 alone is sufficient, but 1 alone is not. (C) Both together are sufficient, but neither alone is. (D) Each alone is sufficient. (E) Both together are still not sufficient.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 26,
    front: 'Mnemonic for the Data Sufficiency choices.',
    back: 'Remember AD / BCE. First test statement 1 alone: if sufficient the answer is A or D, if not it is B, C, or E. Then test statement 2 alone to narrow within that branch. This decision tree prevents mixing information between statements.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'mnemonic',
    topics: ['GMAT'],
  },
  {
    id: 27,
    front: 'Common trap in Data Sufficiency about the two statements.',
    back: 'The two statements never contradict each other, and each must be evaluated independently first before combining. Do not carry a value from statement 1 into statement 2. Also, a statement can be sufficient even if it does not let you find the actual number.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 28,
    front: 'Why plug in numbers 0, 1, negatives, and fractions in DS?',
    back: 'To test sufficiency, look for two allowed cases that give different answers; that proves insufficiency. Boundary values (0, 1), negatives, and proper fractions often break assumptions, since x^2 can be less than x when 0 < x < 1.',
    domain: 'quant',
    domainName: 'Quantitative Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },

  // ===================== VERBAL (18) =====================
  {
    id: 29,
    front: 'What does a Strengthen question ask, and how do you answer it?',
    back: 'It asks which choice, if true, makes the conclusion more likely. Find the argument gap between evidence and conclusion, then pick the answer that supports the assumption or rules out an alternative explanation. The correct answer need not prove the conclusion.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 30,
    front: 'What does a Weaken question ask?',
    back: 'Which choice, if true, makes the conclusion less likely. Attack the gap between premises and conclusion, often by introducing an alternative cause or showing the evidence does not lead where the author claims. It need not disprove the argument, only undermine it.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 31,
    front: 'What is an Assumption in Critical Reasoning?',
    back: 'An unstated premise the argument needs to be valid. Test a candidate with the Negation Test: if negating the statement destroys the conclusion, it is a required assumption. Correct assumptions are usually modest, not sweeping.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 32,
    front: 'What is the Negation Test?',
    back: 'A tool for Assumption questions: negate each answer choice and check whether the argument falls apart. If the negated statement makes the conclusion impossible or clearly weaker, that choice is the necessary assumption. Only one choice should break the argument when negated.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 33,
    front: 'How is an Inference question different from Strengthen or Weaken?',
    back: 'An Inference (or Must Be True) answer must follow directly from the stated facts, taking them as given. You are not evaluating an argument; you are finding what is guaranteed. Avoid choices that go beyond the passage or require outside assumptions.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 34,
    front: 'What does an Evaluate the Argument question want?',
    back: 'The choice whose answer would most affect the argument. Ask: would knowing this make the conclusion stronger or weaker? The best answer is a question whose two possible answers push the argument in opposite directions.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 35,
    front: 'How do you handle a Resolve the Paradox question?',
    back: 'The stimulus presents two facts that seem contradictory. The correct answer adds information that makes both facts true at once, explaining away the apparent conflict. Wrong answers deepen the paradox or address only one of the two facts.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 36,
    front: 'How should you read a Reading Comprehension passage?',
    back: 'Read for structure, not detail: note the main point, the author tone, and how each paragraph functions. Do not memorize facts; you can return to the text. Building a mental map of the passage lets you locate details quickly for specific questions.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 37,
    front: 'How do you attack an RC main-idea question?',
    back: 'Pick the choice that captures the whole passage, not just one paragraph. Watch scope: the credited answer matches the passage breadth exactly. Reject choices that are too narrow, too broad, or that contradict the author tone.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 38,
    front: 'What is the difference between Detail and Inference RC questions?',
    back: 'Detail questions have answers stated explicitly in the text, so locate the line and match. Inference questions require a small logical step beyond the text but must still be supported. Both reward answers grounded in the passage, not outside knowledge.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 39,
    front: 'What is parallelism in Sentence Correction?',
    back: 'Items in a list or joined by a conjunction must share the same grammatical form. Correct: she likes running, swimming, and cycling. Words linked by pairs such as not only ... but also, either ... or, and both ... and must be structurally parallel.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'grammar',
    topics: ['GMAT'],
  },
  {
    id: 40,
    front: 'What is a misplaced or dangling modifier?',
    back: 'A modifier must sit next to the word it describes. An opening participial phrase modifies the subject that immediately follows the comma. Wrong: Running late, the bus was missed. The noun after the comma must be the one performing the action.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'grammar',
    topics: ['GMAT'],
  },
  {
    id: 41,
    front: 'How do you check subject-verb agreement on the GMAT?',
    back: 'Find the true subject and ignore intervening prepositional phrases and clauses. The verb agrees with the subject in number, not with a nearby noun. Collective nouns and phrases like along with or as well as do not change a singular subject to plural.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'grammar',
    topics: ['GMAT'],
  },
  {
    id: 42,
    front: 'How should pronouns behave in Sentence Correction?',
    back: 'Every pronoun needs a single, clear, and grammatically matching antecedent. Ambiguous references (it, they, this) with more than one possible noun are wrong. The pronoun must agree with its antecedent in number.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'grammar',
    topics: ['GMAT'],
  },
  {
    id: 43,
    front: 'When do you use countable vs uncountable comparison words?',
    back: 'Use fewer, number, and many for countable items; use less, amount, and much for uncountable quantities. Fewer errors, less time. Use between for two things and among for three or more.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'grammar',
    topics: ['GMAT'],
  },
  {
    id: 44,
    front: 'Give examples of tested GMAT idioms.',
    back: 'Fixed pairings the GMAT checks include: not only ... but also, either ... or, neither ... nor, as ... as, distinguish X from Y, so ... that, and prefer X to Y. Using the wrong second half of an idiom pair makes a choice incorrect.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'grammar',
    topics: ['GMAT'],
  },
  {
    id: 45,
    front: 'How do you keep comparisons logical in Sentence Correction?',
    back: 'Compare like things to like things. Wrong: The economy of Brazil is larger than Argentina. Right: larger than that of Argentina. Add words such as that of or those of so a country is compared to a country, not to an economy.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'grammar',
    topics: ['GMAT'],
  },
  {
    id: 46,
    front: 'General strategy for the Verbal section on the Focus Edition.',
    back: 'Verbal Reasoning has only Critical Reasoning and Reading Comprehension; Sentence Correction was removed from the Focus Edition. Focus on argument logic and passage structure, pace yourself at roughly under two minutes per question, and answer every item since there is no wrong-answer penalty.',
    domain: 'verbal',
    domainName: 'Verbal Reasoning',
    category: 'strategy',
    topics: ['GMAT'],
  },

  // ===================== DATA INSIGHTS (18) =====================
  {
    id: 47,
    front: 'What is the Data Insights section on the GMAT Focus Edition?',
    back: 'A full scored section of 20 questions in 45 minutes that measures data literacy. It blends quantitative and verbal skills across five question types: Data Sufficiency, Multi-Source Reasoning, Table Analysis, Graphics Interpretation, and Two-Part Analysis.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'definition',
    topics: ['GMAT'],
  },
  {
    id: 48,
    front: 'Which five question types appear in Data Insights?',
    back: 'Data Sufficiency, Multi-Source Reasoning, Table Analysis, Graphics Interpretation, and Two-Part Analysis. Questions are interleaved rather than grouped, and an on-screen calculator is available only in this section.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 49,
    front: 'How is Data Sufficiency in Data Insights different from the old Quant version?',
    back: 'The logic and the five fixed answer choices are identical, but in the Focus Edition all Data Sufficiency questions live in Data Insights, not in Quant. You still decide whether the statements give enough information rather than solving fully.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 50,
    front: 'Restate the five Data Sufficiency answer choices.',
    back: '(A) Statement 1 alone suffices, 2 alone does not. (B) Statement 2 alone suffices, 1 alone does not. (C) Both together suffice, neither alone. (D) Each alone suffices. (E) Both together are still insufficient. These are always in this order.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 51,
    front: 'What is a Multi-Source Reasoning question?',
    back: 'It presents two or three tabbed sources, such as text, tables, or charts, that you toggle between. Questions ask you to synthesize information across tabs, often as a set of yes/no or true/false statements that must all be judged correctly for credit.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'definition',
    topics: ['GMAT'],
  },
  {
    id: 52,
    front: 'Strategy for Multi-Source Reasoning.',
    back: 'Skim all tabs first to learn what each contains, then read the question to know which tab holds the needed data. Do not memorize; jump to the relevant source. Watch for statements that require combining two tabs, a common trap.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 53,
    front: 'What is a Table Analysis question?',
    back: 'It shows a sortable spreadsheet-style table. You typically answer three true/false or yes/no statements about the data. Sorting columns by different fields quickly reveals maxima, minima, medians, and thresholds without manual scanning.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'definition',
    topics: ['GMAT'],
  },
  {
    id: 54,
    front: 'How do you use the sort feature in Table Analysis efficiently?',
    back: 'Each statement often targets one column, so sort by that column before evaluating it. Sorting groups the extreme or qualifying rows together, making it fast to check counts, ranges, and whether a claim holds. Re-sort per statement rather than eyeballing.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 55,
    front: 'What is a Graphics Interpretation question?',
    back: 'It gives a chart, plot, or graph and asks you to complete sentences using drop-down menus. You interpret trends, values, correlations, or projections from the visual. Each blank is a separate drop-down, and you must fill both to earn credit.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'definition',
    topics: ['GMAT'],
  },
  {
    id: 56,
    front: 'What should you check first on a Graphics Interpretation chart?',
    back: 'Read the axis labels, units, scale, and legend before drawing conclusions. Note whether an axis is linear or logarithmic and whether the scale starts at zero. Misreading units or a truncated axis is the most common error on these questions.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 57,
    front: 'What is a Two-Part Analysis question?',
    back: 'It poses a problem with a two-column answer table; you select one option in each column, often two related values that jointly satisfy a condition. It can be quantitative, verbal, or both, and both selections must be correct for the point.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'definition',
    topics: ['GMAT'],
  },
  {
    id: 58,
    front: 'Strategy for Two-Part Analysis with trade-off answers.',
    back: 'Many pairs ask for two quantities meeting a joint constraint (for example, values that sum to a target). Test the answer options against the constraint rather than solving open-ended. The same option may legitimately be chosen for both columns unless prohibited.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 59,
    front: 'How does the answer format differ across Data Insights question types?',
    back: 'Data Sufficiency uses five radio choices. Multi-Source, Table, and some Graphics use multi-statement true/false grids. Graphics Interpretation uses drop-downs. Two-Part Analysis uses a two-column selection table. Multi-part items require every part correct for credit.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 60,
    front: 'How do you read percentages and proportions in tables and charts?',
    back: 'Confirm the base of each percentage: a percentage of a subgroup is not comparable to a percentage of the whole. Distinguish percent, percentage points, and raw counts. A rising percentage can accompany a falling count if the total shrank.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 61,
    front: 'How do you interpret correlation on a scatter plot?',
    back: 'A positive correlation trends up-right, negative trends down-right, and scattered points show little correlation. Correlation is not causation, and one outlier can distort the perceived trend. Estimate direction and strength, not an exact coefficient.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 62,
    front: 'Common trap: partially sufficient information in Data Insights.',
    back: 'A source may give data that looks helpful but does not resolve the exact question asked. In Data Sufficiency this means the statement is insufficient; in multi-statement grids it means one statement is false or unsupported. Match evidence to the precise claim.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 63,
    front: 'When should you use the Data Insights calculator?',
    back: 'An on-screen calculator is provided only in Data Insights, not in Quant. Use it for messy arithmetic on real data, but avoid it for simple estimates where mental math is faster. Over-reliance costs time in a 20-question, 45-minute section.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 64,
    front: 'Overall pacing approach for Data Insights.',
    back: 'With 20 questions in 45 minutes, budget just over two minutes each, but expect multi-source and table items to run longer while data sufficiency runs shorter. Since multi-part questions need every part right, invest a little extra to avoid losing the whole item.',
    domain: 'data_insights',
    domainName: 'Data Insights',
    category: 'strategy',
    topics: ['GMAT'],
  },

  // ===================== STRATEGY (8) =====================
  {
    id: 65,
    front: 'What are the three sections of the GMAT Focus Edition?',
    back: 'Quantitative Reasoning, Verbal Reasoning, and Data Insights. Each section has 21, 23, and 20 questions respectively, and each is allotted 45 minutes, for a total test time of about 2 hours and 15 minutes. You may take the sections in any order you choose.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 66,
    front: 'What is the score scale on the GMAT Focus Edition?',
    back: 'The total score ranges from 205 to 805 and always ends in a 5. Each of the three sections is scored from 60 to 90, and all three sections contribute equally to the total, unlike the older exam where Data Insights was not part of the main score.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 67,
    front: 'How does the question review and bookmarking feature work?',
    back: 'Within each section you can bookmark questions, and at the end of the section you may review and edit up to three answers using the remaining time. This is new to the Focus Edition; budget a small buffer so you can revisit flagged questions.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 68,
    front: 'How is the GMAT Focus Edition adaptive?',
    back: 'It is question-adaptive: within a section the difficulty of the next question adjusts to your running performance. Early questions carry weight in calibrating difficulty, but there is no penalty for guessing, so never leave an item blank.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'concept',
    topics: ['GMAT'],
  },
  {
    id: 69,
    front: 'What is the per-question timing on the Focus Edition?',
    back: 'Quant gives 21 questions in 45 minutes (about 2 minutes 9 seconds each), Verbal 23 in 45 minutes (about 1 minute 57 seconds each), and Data Insights 20 in 45 minutes (about 2 minutes 15 seconds each). Track pace against section checkpoints.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 70,
    front: 'Why should you never leave a question blank?',
    back: 'The GMAT penalizes unanswered questions at the end of a section more heavily than wrong answers, and there is no deduction for incorrect guesses. If time runs low, eliminate what you can and guess so that every question is answered.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 71,
    front: 'How should you use the ability to reorder sections and take breaks?',
    back: 'You choose the order of the three sections and get one optional 10-minute break. Start with your strongest section to build confidence, or your weakest while fresh. Plan your section order in advance so you are not deciding under pressure on test day.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['GMAT'],
  },
  {
    id: 72,
    front: 'What extra insights does the Focus Edition score report include?',
    back: 'Beyond the total and section scores, the report provides detailed performance insights: pacing data, time spent per question type, and relative strengths across content areas. Scores are valid for five years, and you can send them selectively after seeing them.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'concept',
    topics: ['GMAT'],
  },
];

export function getGMATFlashcards(domain?: string): GMATFlashcard[] {
  if (!domain) return GMAT_FLASHCARDS;
  return GMAT_FLASHCARDS.filter(c => c.domain === domain);
}
export const GMAT_FLASHCARD_COUNT = GMAT_FLASHCARDS.length;
