/**
 * GRE Flashcard deck — covering Quantitative Reasoning, Verbal Reasoning,
 * high-frequency vocabulary, Analytical Writing, and general test strategy.
 *
 * All content is original wording. Math is written as plain text (x^2, sqrt(2)).
 */

export interface GREFlashcard {
  id: number;
  front: string;
  back: string;
  domain: string;      // one of the domain ids below
  domainName: string;  // the matching domain name
  category: string;    // 'definition' | 'concept' | 'formula' | 'strategy' | 'vocabulary' | 'mnemonic'
  topics: string[];    // e.g. ['GRE']
}

export const GRE_FLASHCARD_DOMAINS = [
  { id: 'quant',    label: 'Quant',    name: 'Quantitative Reasoning',    count: 28 },
  { id: 'verbal',   label: 'Verbal',   name: 'Verbal Reasoning',          count: 18 },
  { id: 'vocab',    label: 'Vocab',    name: 'High-Frequency Vocabulary', count: 22 },
  { id: 'writing',  label: 'Writing',  name: 'Analytical Writing',        count: 10 },
  { id: 'strategy', label: 'Strategy', name: 'Test Strategy',             count: 7 },
];

export const GRE_FLASHCARD_CATEGORIES = ['definition','concept','formula','strategy','vocabulary','mnemonic'] as const;

export const GRE_FLASHCARDS: GREFlashcard[] = [
  // ============================================================
  // DOMAIN: quant (28 cards, ids 1–28)
  // ============================================================

  { id: 1, front: 'Difference of squares', back: 'a^2 - b^2 = (a + b)(a - b). Recognizing this factoring on the GRE lets you simplify expressions and Quantitative Comparison quantities quickly. Example: 51^2 - 49^2 = (51 + 49)(51 - 49) = 100 * 2 = 200.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 2, front: 'Perfect-square trinomials', back: '(a + b)^2 = a^2 + 2ab + b^2 and (a - b)^2 = a^2 - 2ab + b^2. Memorize both. If you see a^2 + 2ab + b^2 in a problem, rewrite it as (a + b)^2 to collapse it into a single term.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 3, front: 'Exponent rules: multiplication and division', back: 'When multiplying like bases, add exponents: x^a * x^b = x^(a+b). When dividing, subtract: x^a / x^b = x^(a-b). A power raised to a power multiplies: (x^a)^b = x^(a*b).', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 4, front: 'Negative and zero exponents', back: 'Any nonzero base to the zero power equals 1: x^0 = 1. A negative exponent is a reciprocal: x^(-n) = 1 / x^n. So 2^(-3) = 1/8. These show up constantly in Quantitative Comparison.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 5, front: 'Fractional exponents', back: 'A fractional exponent is a root: x^(1/n) = the nth root of x, and x^(m/n) = the nth root of (x^m). For example, 27^(2/3) = (cube root of 27)^2 = 3^2 = 9.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 6, front: 'Average (arithmetic mean)', back: 'Average = (sum of terms) / (number of terms). Rearranged: sum = average * count. On the GRE it is often faster to work with the total sum than with individual values, especially in weighted-average problems.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 7, front: 'Median, mode, and range', back: 'Median = the middle value of an ordered list (average the two middle values if the count is even). Mode = the most frequently occurring value. Range = largest value minus smallest value. The median is resistant to outliers; the mean is not.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'definition', topics: ['GRE'] },
  { id: 8, front: 'Distance, rate, and time', back: 'distance = rate * time, so rate = distance / time and time = distance / rate. For an average speed over a whole trip, use total distance / total time, NOT the simple average of the two speeds.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 9, front: 'Percent change', back: 'Percent change = (new value - old value) / (old value) * 100. A rise from 40 to 50 is (50 - 40)/40 = 25% increase. Note a 25% increase followed by a 25% decrease does NOT return to the original value.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 10, front: 'Percent of a number', back: 'To find P percent of N, compute (P/100) * N. "What percent" translates to x/100. Translate word problems literally: "is" means equals, "of" means multiply, "what" means the unknown variable.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 11, front: 'Simple vs. compound interest', back: 'Simple interest: A = P(1 + rt). Compound interest: A = P(1 + r/n)^(nt), where n is the number of compounding periods per year. Compound growth exceeds simple growth for the same rate over more than one period.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 12, front: 'Probability of a single event', back: 'Probability = (number of favorable outcomes) / (total number of equally likely outcomes). It is always between 0 and 1. The probability of an event NOT happening is 1 minus the probability that it does.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 13, front: 'Probability: AND vs. OR', back: 'For independent events, P(A and B) = P(A) * P(B). For mutually exclusive events, P(A or B) = P(A) + P(B). If events can overlap, use P(A or B) = P(A) + P(B) - P(A and B).', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 14, front: 'Combinations vs. permutations', back: 'Use a combination when order does NOT matter: C(n, k) = n! / (k!(n-k)!). Use a permutation when order DOES matter: P(n, k) = n! / (n-k)!. "Committee" signals combinations; "ranking" or "arrangement" signals permutations.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 15, front: 'Area and circumference of a circle', back: 'Area = pi * r^2. Circumference = 2 * pi * r = pi * d, where d is the diameter. A sector or arc is a fraction of the whole based on its central angle over 360 degrees.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 16, front: 'Area formulas for common shapes', back: 'Triangle: (1/2) * base * height. Rectangle: length * width. Parallelogram: base * height. Trapezoid: (1/2)(b1 + b2) * height. The height must be perpendicular to the base you use.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 17, front: 'Pythagorean theorem', back: 'For a right triangle with legs a and b and hypotenuse c: a^2 + b^2 = c^2. Common integer triples worth memorizing: 3-4-5, 5-12-13, 8-15-17, and their multiples like 6-8-10.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 18, front: 'Special right triangles', back: 'A 45-45-90 triangle has side ratio 1 : 1 : sqrt(2) (legs equal, hypotenuse = leg * sqrt(2)). A 30-60-90 triangle has side ratio 1 : sqrt(3) : 2 (short leg : long leg : hypotenuse). These appear in squares and equilateral triangles.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 19, front: 'Sum of interior angles of a polygon', back: 'The interior angles of an n-sided polygon sum to (n - 2) * 180 degrees. A triangle sums to 180, a quadrilateral to 360, a pentagon to 540. Each interior angle of a regular polygon is that sum divided by n.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 20, front: 'Volume of common solids', back: 'Rectangular box: length * width * height. Cylinder: pi * r^2 * h. Cube: s^3. Surface area of a box is the sum of the areas of all six faces. Match the formula to whether the problem asks for volume or surface area.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 21, front: 'Slope of a line', back: 'Slope = rise / run = (y2 - y1) / (x2 - x1). Slope-intercept form is y = mx + b, where m is the slope and b is the y-intercept. Parallel lines share a slope; perpendicular slopes are negative reciprocals.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'formula', topics: ['GRE'] },
  { id: 22, front: 'Divisibility rules', back: 'A number is divisible by 3 if its digit sum is divisible by 3; by 9 if the digit sum is divisible by 9; by 4 if its last two digits form a multiple of 4; by 6 if it is divisible by both 2 and 3.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 23, front: 'Prime numbers and prime factorization', back: 'A prime has exactly two factors: 1 and itself. 2 is the only even prime; 1 is NOT prime. Prime factorization breaks a number into a product of primes, which is the key to finding GCF and LCM.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'definition', topics: ['GRE'] },
  { id: 24, front: 'GCF and LCM', back: 'The greatest common factor is the product of the shared prime factors (lowest powers). The least common multiple uses every prime factor at its highest power. For any two integers, GCF(a,b) * LCM(a,b) = a * b.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 25, front: 'Even and odd properties', back: 'even + even = even, odd + odd = even, even + odd = odd. even * anything = even; odd * odd = odd. These parity rules let you eliminate answer choices without full computation.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 26, front: 'Ratios and proportions', back: 'A ratio a:b can be scaled by any common factor, so a:b = ka:kb. Solve proportions by cross-multiplication: if a/b = c/d, then a*d = b*c. Keep units consistent when setting up the proportion.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 27, front: 'Standard deviation (conceptual)', back: 'Standard deviation measures how spread out data are around the mean. A larger spread means a larger standard deviation. The GRE rarely asks you to compute it by hand but often tests which of two data sets has the greater spread.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 28, front: 'Quantitative Comparison: the four answer choices', back: 'Every QC question has the same choices: (A) Quantity A is greater, (B) Quantity B is greater, (C) the two are equal, (D) the relationship cannot be determined. Choose D whenever the answer changes as you test different valid values.', domain: 'quant', domainName: 'Quantitative Reasoning', category: 'strategy', topics: ['GRE'] },

  // ============================================================
  // DOMAIN: verbal (18 cards, ids 29–46)
  // ============================================================

  { id: 29, front: 'Text Completion: predict before you peek', back: 'Read the whole sentence first and predict a word for the blank in your own terms before looking at the choices. This anchors you to the intended meaning and protects you from tempting words that fit the tone but not the logic.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 30, front: 'Text Completion: use signal words', back: 'Contrast words (but, although, however, despite, yet) reverse direction; continuation words (moreover, indeed, because, thus) keep it. Identifying these transition cues tells you whether the blank agrees with or opposes the surrounding clause.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 31, front: 'Text Completion: multi-blank strategy', back: 'For two- and three-blank questions, fill the blank you are most confident about first, then use it to constrain the others. Each blank is scored independently with no partial credit, so all blanks must be correct.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 32, front: 'Sentence Equivalence: pick two synonyms', back: 'You must select TWO of six choices that both complete the sentence AND produce sentences with the same meaning. First predict the meaning, then look for a matched synonym pair. A word with no partner cannot be correct.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 33, front: 'Sentence Equivalence trap: lone tempting word', back: 'A choice may fit the blank perfectly yet lack a synonym among the other options. Because the answer requires two words that yield equivalent sentences, a strong word without a partner is a trap. Always confirm the pair.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 34, front: 'Reading Comprehension: map the passage', back: 'As you read, track the author main point, the purpose of each paragraph, and any shift in tone or viewpoint. A quick mental map lets you locate support fast without rereading the whole passage for each question.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 35, front: 'Reading Comprehension: answer from the text', back: 'Correct RC answers are always supported by the passage, not by outside knowledge or plausible real-world reasoning. If a choice sounds true but has no textual basis, eliminate it. Point to the exact lines that justify your answer.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 36, front: 'Reading Comprehension: question types', back: 'Common types include main idea, detail, inference, author purpose, function of a sentence, and vocabulary-in-context. Identify the type first, because each demands a different scope: some want the big picture, others a single line.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 37, front: 'Inference questions on Reading Comprehension', back: 'An inference must follow logically from the passage without going beyond it. The right answer is the one that MUST be true given the text, not merely one that could be true. Avoid choices that are too strong or too broad.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 38, front: 'Reading Comprehension: extreme-language trap', back: 'Choices containing absolute words like always, never, all, none, or only are often wrong because passages rarely support such sweeping claims. Prefer measured answers using words like some, may, tends to, or often.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 39, front: 'Critical Reasoning: identify the conclusion', back: 'Before evaluating any argument-based question, separate the conclusion (the claim being argued for) from the premises (the support). Conclusion indicators include therefore, thus, and hence. Misreading the conclusion derails every later step.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 40, front: 'Critical Reasoning: strengthen vs. weaken', back: 'To strengthen an argument, add a fact that makes the conclusion more likely or closes a logical gap. To weaken it, introduce a fact that undermines the link between premise and conclusion, such as an alternative explanation.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 41, front: 'Critical Reasoning: assumption questions', back: 'An assumption is an unstated premise the argument depends on. Test a candidate by negating it: if the negation destroys the argument, it is a required assumption. Correct assumptions are usually modest, not sweeping.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 42, front: 'Vocabulary-in-context questions', back: 'When a passage asks what a word means in context, the answer is often a secondary or less common definition, not the everyday one. Substitute each choice back into the sentence and keep the one that preserves the intended meaning.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 43, front: 'Eliminate to two, then decide', back: 'On tough verbal questions you can usually rule out three choices quickly. When two remain, return to the exact wording of the sentence or passage and pick the one with direct textual support rather than the one that merely feels right.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 44, front: 'Positive or negative charge of the blank', back: 'Even when you do not know a vocabulary word, you can often tell whether a blank needs a positive or negative word from the sentence tone. Assigning a plus or minus charge to each choice can eliminate half the options at once.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },
  { id: 45, front: 'Beware answers that are half right', back: 'A common verbal trap pairs an accurate phrase with one inaccurate detail: a swapped subject, a missing qualifier, or a reversed relationship. One wrong word invalidates the entire choice, so read every word before committing.', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'concept', topics: ['GRE'] },
  { id: 46, front: 'Do not overthink the main idea', back: 'The main idea of a passage is usually stated or strongly implied near the start or end, and it should account for the whole passage, not just one paragraph. Reject choices that are too narrow (a single detail) or too broad (beyond the passage).', domain: 'verbal', domainName: 'Verbal Reasoning', category: 'strategy', topics: ['GRE'] },

  // ============================================================
  // DOMAIN: vocab (22 cards, ids 47–68)
  // ============================================================

  { id: 47, front: 'Ubiquitous', back: 'Seeming to be present everywhere at the same time; extremely widespread or common. Example use: smartphones have become ubiquitous in modern life. Related idea: omnipresent.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 48, front: 'Ephemeral', back: 'Lasting for only a very short time; fleeting and transitory. Often used of things that pass quickly, such as an ephemeral trend or an ephemeral bloom. Opposite: enduring, permanent.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 49, front: 'Laconic', back: 'Using very few words; terse to the point of seeming blunt or reserved. A laconic reply gives minimal information. Contrast with verbose or loquacious, which mean wordy.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 50, front: 'Prodigal', back: 'Recklessly wasteful, especially with money or resources; spending lavishly. Note it does NOT mean "returning" despite the phrase prodigal son. Opposite: frugal, thrifty.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 51, front: 'Capricious', back: 'Given to sudden, unpredictable changes of mood or behavior; impulsive and whimsical. A capricious ruler makes decisions on a whim. Related: fickle, mercurial, volatile.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 52, front: 'Pragmatic', back: 'Dealing with problems in a practical, realistic way rather than through theory or ideals. A pragmatic solution focuses on what actually works. Contrast with idealistic or dogmatic.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 53, front: 'Esoteric', back: 'Understood by or intended for only a small group with specialized knowledge; obscure to outsiders. Esoteric jargon confuses the uninitiated. Opposite: accessible, exoteric.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 54, front: 'Gregarious', back: 'Fond of the company of others; sociable and outgoing. A gregarious person thrives at parties. Also used in biology for animals that live in groups. Opposite: solitary, reclusive.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 55, front: 'Obfuscate', back: 'To deliberately make something unclear, confusing, or hard to understand. Vague language can obfuscate the real meaning. Opposite: clarify, elucidate, illuminate.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 56, front: 'Meticulous', back: 'Showing great attention to detail; very careful and precise. A meticulous editor catches every error. Related: scrupulous, painstaking. Opposite: careless, slapdash.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 57, front: 'Ameliorate', back: 'To make a bad or unsatisfactory situation better; to improve or relieve. New policies aimed to ameliorate poverty. Opposite: aggravate, worsen, exacerbate.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 58, front: 'Cogent', back: 'Clear, logical, and convincing; forcefully persuasive. A cogent argument leaves little room for doubt. Related: compelling, sound. Opposite: unconvincing, weak.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 59, front: 'Disparate', back: 'Fundamentally different in kind; distinct and not comparable. The report combined disparate sources of data. Do not confuse with desperate. Related: dissimilar, divergent.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 60, front: 'Enervate', back: 'To weaken or drain of energy and vitality. The oppressive heat enervated the hikers. Note it means to weaken, NOT to energize, despite how it sounds. Opposite: invigorate, energize.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 61, front: 'Tacit', back: 'Understood or implied without being stated outright; unspoken. A tacit agreement needs no formal words. Related: implicit, unstated. Opposite: explicit, express.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 62, front: 'Venerate', back: 'To regard with deep respect and reverence; to honor as sacred or admirable. Many cultures venerate their ancestors. Related: revere, esteem. Opposite: despise, scorn.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 63, front: 'Superfluous', back: 'More than is needed or useful; excessive and unnecessary. Editing removes superfluous words. Related: redundant, surplus. Opposite: essential, necessary.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 64, front: 'Intransigent', back: 'Refusing to change one point of view or demands; stubbornly uncompromising. The intransigent negotiator rejected every offer. Related: obdurate, inflexible. Opposite: flexible, accommodating.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 65, front: 'Sanguine', back: 'Cheerfully optimistic or confident, especially in a difficult situation. She remained sanguine about the project despite delays. Related: hopeful, buoyant. Opposite: pessimistic, gloomy.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 66, front: 'Pejorative', back: 'Expressing disapproval or contempt; belittling in tone. A pejorative label carries a negative connotation. Related: derogatory, disparaging. Opposite: complimentary, laudatory.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 67, front: 'Assuage', back: 'To make an unpleasant feeling less intense; to soothe, ease, or relieve. Kind words assuaged her grief. Related: alleviate, mollify, appease. Opposite: intensify, aggravate.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },
  { id: 68, front: 'Nascent', back: 'Just coming into existence and beginning to develop; in an early stage. The nascent industry showed rapid growth. Related: emerging, incipient, budding. Opposite: mature, established.', domain: 'vocab', domainName: 'High-Frequency Vocabulary', category: 'vocabulary', topics: ['GRE'] },

  // ============================================================
  // DOMAIN: writing (10 cards, ids 69–78)
  // ============================================================

  { id: 69, front: 'The Analytical Writing task on the current GRE', back: 'The current GRE has a single 30-minute Analytical Writing task: Analyze an Issue. You take a position on a general claim and support it with reasons and examples. The older Analyze an Argument task was retired in the shortened GRE format.', domain: 'writing', domainName: 'Analytical Writing', category: 'concept', topics: ['GRE'] },
  { id: 70, front: 'Issue essay: structure', back: 'Use a clear structure: an introduction that states your position, two or three body paragraphs each developing one reason with a concrete example, and a conclusion that reinforces your stance. A visible structure signals organization to the scorer.', domain: 'writing', domainName: 'Analytical Writing', category: 'strategy', topics: ['GRE'] },
  { id: 71, front: 'Issue essay: take a clear position', back: 'Commit to a defensible thesis early rather than sitting on the fence. You can still acknowledge the other side, but your essay must argue for one position. A wishy-washy stance weakens the essay and lowers the score.', domain: 'writing', domainName: 'Analytical Writing', category: 'strategy', topics: ['GRE'] },
  { id: 72, front: 'Address the specific instructions', back: 'Each Issue prompt comes with specific instructions, such as "discuss the extent to which you agree" or "address the most compelling counterarguments." Responding to those exact instructions is part of the scoring, so read them carefully.', domain: 'writing', domainName: 'Analytical Writing', category: 'strategy', topics: ['GRE'] },
  { id: 73, front: 'Use concrete, specific examples', back: 'Support each reason with a concrete example: a historical event, a scientific finding, a hypothetical scenario, or personal experience. Specific evidence is far more persuasive than vague generalities and is a hallmark of high-scoring essays.', domain: 'writing', domainName: 'Analytical Writing', category: 'strategy', topics: ['GRE'] },
  { id: 74, front: 'Acknowledge and rebut a counterargument', back: 'A strong Issue essay considers an opposing view and then explains why your position still holds. Showing you understand complexity and can defend against objections demonstrates the critical thinking the graders reward.', domain: 'writing', domainName: 'Analytical Writing', category: 'strategy', topics: ['GRE'] },
  { id: 75, front: 'Analytical Writing scoring scale', back: 'The essay is scored from 0 to 6 in half-point increments. Two independent raters (one human and one automated scoring engine) evaluate it; if they disagree substantially, a second human resolves the difference. The final score is their average.', domain: 'writing', domainName: 'Analytical Writing', category: 'concept', topics: ['GRE'] },
  { id: 76, front: 'What a 6 essay demonstrates', back: 'A top-scoring essay presents a cogent, well-articulated position, develops it with compelling and relevant reasons and examples, sustains a clear focus, and uses varied, precise language with strong control of grammar and mechanics.', domain: 'writing', domainName: 'Analytical Writing', category: 'concept', topics: ['GRE'] },
  { id: 77, front: 'Budget your 30 minutes', back: 'A workable split: about 5 minutes to plan and outline, roughly 20 minutes to write, and 5 minutes to proofread. Planning first prevents rambling and helps you finish a complete essay, which matters more than a polished but unfinished one.', domain: 'writing', domainName: 'Analytical Writing', category: 'strategy', topics: ['GRE'] },
  { id: 78, front: 'Clarity and variety in writing', back: 'Graders reward clear organization, logical transitions, and sentence variety over ornate vocabulary. Use transition words to link ideas, vary sentence length, and leave a few minutes to fix obvious grammar and spelling errors.', domain: 'writing', domainName: 'Analytical Writing', category: 'strategy', topics: ['GRE'] },

  // ============================================================
  // DOMAIN: strategy (7 cards, ids 79–85)
  // ============================================================

  { id: 79, front: 'Section-level adaptive format', back: 'The GRE is section-adaptive: your performance on the first scored section of a measure (Verbal or Quant) determines the difficulty of the second section. Because scoring accounts for difficulty, a harder second section can yield a higher score.', domain: 'strategy', domainName: 'Test Strategy', category: 'concept', topics: ['GRE'] },
  { id: 80, front: 'No penalty for wrong answers', back: 'The GRE does not deduct points for incorrect answers, so never leave a question blank. If you are unsure or running low on time, eliminate what you can and make an educated guess. A blank guarantees zero; a guess has a chance.', domain: 'strategy', domainName: 'Test Strategy', category: 'strategy', topics: ['GRE'] },
  { id: 81, front: 'Mark and review within a section', back: 'You can move freely within a section: skip a hard question, use Mark to flag it, and return before time runs out via the Review screen. Answer the easy questions first to lock in points, then circle back to the tough ones.', domain: 'strategy', domainName: 'Test Strategy', category: 'strategy', topics: ['GRE'] },
  { id: 82, front: 'Score ranges and structure', back: 'Verbal and Quantitative are each scored from 130 to 170 in one-point increments; Analytical Writing is scored from 0 to 6 in half-point steps. The shortened GRE runs under two hours with no scheduled break.', domain: 'strategy', domainName: 'Test Strategy', category: 'concept', topics: ['GRE'] },
  { id: 83, front: 'Pacing: spend time where it pays', back: 'Every question in a section is worth the same, so do not sink several minutes into one hard problem while easy points go unanswered. Aim for a steady pace, guess and flag when stuck, and use leftover time to revisit flagged items.', domain: 'strategy', domainName: 'Test Strategy', category: 'strategy', topics: ['GRE'] },
  { id: 84, front: 'Use the on-screen calculator wisely', back: 'The Quant section includes a basic on-screen calculator. Use it for tedious arithmetic, but rely on estimation and number sense for most problems, since many questions are designed to be solved faster by reasoning than by calculation.', domain: 'strategy', domainName: 'Test Strategy', category: 'strategy', topics: ['GRE'] },
  { id: 85, front: 'ScoreSelect: choose which scores to send', back: 'The ScoreSelect option lets you decide which test dates to report to schools: your most recent, all scores, or any specific administrations. This means one weaker attempt need not follow you if a later attempt goes better.', domain: 'strategy', domainName: 'Test Strategy', category: 'concept', topics: ['GRE'] },
];

export function getGREFlashcards(domain?: string): GREFlashcard[] {
  if (!domain) return GRE_FLASHCARDS;
  return GRE_FLASHCARDS.filter(c => c.domain === domain);
}

export const GRE_FLASHCARD_COUNT = GRE_FLASHCARDS.length;
