/**
 * GRE (General Test) — Question Bank
 * 87 original, blueprint-faithful, SME-audited questions (Verbal + Quantitative Reasoning).
 * topicId: 0 = Quantitative Reasoning, 1 = Verbal Reasoning.
 */

export interface GREQuestion {
  id: string;
  topicId: number;
  domain: string;
  skill: string;
  difficulty: number;
  passage?: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const GRE_QUESTIONS: GREQuestion[] = [
  {
    id: "gre_0001", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 1,
    passage: "For decades, urban planners treated street trees as decorative amenities, secondary to the practical business of moving traffic. Recent studies have inverted this assumption, showing that dense canopy cover measurably lowers summer road-surface temperatures and reduces the frequency of heat-related emergency calls. Consequently, several cities have begun classifying trees as infrastructure rather than ornament.",
    question: "The passage suggests that the reclassification of street trees as infrastructure was primarily motivated by:",
    options: ["A long-standing aesthetic preference among urban planners", "Evidence of measurable practical benefits to public health and road conditions", "A shortage of funds for conventional traffic infrastructure", "The desire to make cities appear more attractive to tourists", "Legal requirements imposed on municipalities by higher authorities"],
    correct: 1,
    explanation: "The passage attributes the reclassification to 'recent studies' showing that canopy cover lowers road temperatures and reduces heat-related emergency calls, i.e., measurable practical benefits (B). (A) reverses the argument, since aesthetics is the old view being overturned. (C), (D), and (E) introduce funding shortages, tourism, and legal mandates that the passage never mentions.",
  },
  {
    id: "gre_0002", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 1,
    passage: "The novelist's early works were praised for their taut, economical prose, in which not a single word seemed wasted. Her later novels, by contrast, sprawl across hundreds of pages of digression and ornament. Critics remain divided: some see the shift as a decline into self-indulgence, while others regard it as a mature willingness to let a story breathe.",
    question: "According to the passage, critics disagree about whether the change in the novelist's style represents:",
    options: ["A response to commercial pressure from her publishers", "A deterioration or a sign of artistic growth", "A deliberate imitation of an earlier literary tradition", "An improvement in the accuracy of her historical detail", "A shift from fiction toward nonfiction writing"],
    correct: 1,
    explanation: "The final sentence frames the disagreement precisely: some critics see 'a decline into self-indulgence' while others see 'a mature willingness'—that is, deterioration versus artistic growth (B). (A) commercial pressure, (C) imitation of tradition, (D) historical accuracy, and (E) a genre shift are all absent from the passage.",
  },
  {
    id: "gre_0003", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "Conventional wisdom holds that introducing a predator into an ecosystem reduces the population of its prey. Yet on one island, the arrival of a fox species was followed by a rise in the population of the ground-nesting birds it hunts. Ecologists eventually determined that the foxes preyed even more heavily on the rats that had been raiding the birds' nests, so the birds' losses to foxes were more than offset by the eggs the rats no longer destroyed.",
    question: "The explanation offered by the ecologists depends on which of the following assumptions?",
    options: ["Foxes prefer hunting rats to hunting ground-nesting birds", "Before the foxes arrived, rats destroyed enough eggs to depress the bird population", "The rat population on the island was larger than the fox population", "Ground-nesting birds cannot survive on islands without predators", "The foxes were introduced deliberately rather than arriving by chance"],
    correct: 1,
    explanation: "For reduced rat predation to raise the bird population, the rats' egg destruction must previously have been a meaningful check on bird numbers (B); otherwise removing that pressure would not produce a net gain. (A) is not required—the foxes need only reduce rats substantially, regardless of preference. (C) relative population sizes, (D) an absolute claim about survival, and (E) how the foxes arrived are irrelevant to the causal mechanism described.",
  },
  {
    id: "gre_0004", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "The prevailing account of the empire's collapse emphasizes external invasion. But the tax records tell a subtler story: revenues from the agricultural provinces had been declining for two generations before the first invaders crossed the frontier. By the time the armies arrived, the treasury could no longer pay the very soldiers meant to repel them.",
    question: "The author cites the tax records primarily in order to:",
    options: ["Prove that external invasion played no role in the empire's collapse", "Suggest that internal economic decline preceded and enabled the collapse", "Argue that the empire's soldiers were disloyal from the outset", "Demonstrate that agricultural provinces were unimportant to the empire", "Show that the invaders were wealthier than the empire they attacked"],
    correct: 1,
    explanation: "The tax records show revenues falling 'for two generations before' the invasion and a treasury unable to pay its soldiers, positioning economic decline as prior and enabling (B). (A) overstates the point—the author revises, not eliminates, the role of invasion ('a subtler story,' not 'no role'). (C) misreads unpaid soldiers as disloyal-from-the-start; (D) contradicts the emphasis on declining agricultural revenue; (E) about the invaders' wealth is never discussed.",
  },
  {
    id: "gre_0005", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "Advocates of open-plan offices claim they foster collaboration by removing the physical barriers between coworkers. A recent study, however, found that when a firm switched to an open plan, face-to-face interaction dropped by seventy percent while electronic messaging rose sharply. The authors suggest that, deprived of privacy, employees retreated into digital channels to reclaim a sense of personal space.",
    question: "The study described in the passage most directly challenges which assumption held by advocates of open-plan offices?",
    options: ["That electronic messaging is an inferior form of communication", "That removing physical barriers necessarily increases in-person collaboration", "That employees value privacy more than they value collaboration", "That open-plan offices are less expensive to maintain", "That collaboration is beneficial to a firm's performance"],
    correct: 1,
    explanation: "Advocates assume removing barriers 'fosters collaboration' via more interaction; the finding that face-to-face contact fell 70 percent directly undercuts the link between removing barriers and increased in-person collaboration (B). (A) is not the advocates' assumption and the passage makes no quality judgment about messaging. (C) overgeneralizes about employee values beyond the evidence. (D) cost and (E) the value of collaboration itself are not at issue.",
  },
  {
    id: "gre_0006", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 3,
    passage: "It would be a mistake to read the reformer's public caution as timidity. In private correspondence she pressed her allies toward far more radical ends than she ever avowed in the assembly, calculating that a proposal presented as moderate could pass where an openly sweeping one would provoke reaction. Her restraint, in short, was a matter of tactics, not of conviction.",
    question: "The passage implies that the reformer's public statements differed from her private views chiefly because she believed that:",
    options: ["Her allies would abandon her if they learned her true aims", "Moderation was the position she genuinely held on the issues", "A measured proposal stood a better chance of being enacted than a bold one", "The assembly lacked the authority to enact radical reforms", "Public opinion had shifted decisively against all forms of reform"],
    correct: 2,
    explanation: "The passage states she calculated that a proposal 'presented as moderate could pass where an openly sweeping one would provoke reaction'—strategic concealment to improve chances of passage (C). (B) is explicitly denied ('not of conviction'). (A) misattributes the risk to her allies, whom she was privately pressing toward radical ends, not hiding from. (D) the assembly's authority and (E) a decisive shift against all reform are not stated; the concern is reaction to sweeping proposals, not blanket opposition.",
  },
  {
    id: "gre_0007", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 3,
    passage: "Skeptics of the new dating technique note that it has never been tested on samples of known age older than five thousand years. Its defenders reply that the physical principle underlying the method is the same across all time scales, so a validation at younger ages should suffice. Yet this reply assumes precisely what the skeptics doubt: that no additional process, negligible over short spans, accumulates enough influence over longer ones to distort the result.",
    question: "The passage indicates that the defenders' reply is inadequate because it:",
    options: ["Relies on samples that have themselves been inaccurately dated", "Presupposes the very point that is in dispute between the two sides", "Depends on a physical principle that has since been disproved", "Concedes that the technique fails for samples younger than five thousand years", "Ignores the possibility that the technique works better on older samples"],
    correct: 1,
    explanation: "The final sentence says the reply 'assumes precisely what the skeptics doubt'—it begs the question by presupposing no long-term distorting process exists (B). (A) misstates the issue: the concern is untested old samples, not mis-dated ones. (C) the principle is not disproved—its constancy across time scales is exactly what is assumed. (D) reverses the situation, since the technique is validated at younger ages. (E) contradicts the passage, which raises the risk of distortion over long spans, not improved accuracy.",
  },
  {
    id: "gre_0008", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 3,
    passage: "The historian argues that the guild system, long portrayed as a brake on economic growth, in fact underwrote it. By guaranteeing that members who shared trade secrets would not be undercut by imitators, the guilds gave master craftsmen a reason to train apprentices thoroughly rather than hoard their knowledge. The resulting diffusion of skill, she contends, laid the groundwork for innovations that later, freer markets merely harvested.",
    question: "Which of the following, if true, would most strengthen the historian's argument?",
    options: ["Some guilds imposed fines on members who trained too many apprentices", "In regions without guilds, craftsmen were markedly more secretive about their techniques", "Guild membership was often restricted to the sons of existing members", "The freer markets that followed the guilds produced more patents than the guilds had", "Many guilds also regulated the prices at which their members could sell goods"],
    correct: 1,
    explanation: "The historian's causal claim is that guilds encouraged the sharing and diffusion of skill by protecting members from imitators. Evidence that craftsmen were 'markedly more secretive' where guilds were absent supports the contrast that guilds promoted openness (B). (A) fines for training apprentices would weaken the claim about thorough training. (C) restricting membership to sons speaks to access, not skill diffusion. (D) more patents later is consistent with the 'harvesting' framing but does not show guilds caused the underlying diffusion. (E) price regulation is unrelated to the transmission of knowledge.",
  },
  {
    id: "gre_0009", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 2,
    passage: "The committee's report concluded that the bridge failed because of a flaw in its original design. A dissenting member, however, pointed out that the same design had supported thousands of similar bridges for over a century without incident. She argued that the decisive factor was not the design but the corrosion that decades of deferred maintenance had allowed to spread through the joints.",
    question: "The dissenting member's argument relies most directly on which of the following as evidence?",
    options: ["The bridge had carried heavier loads than its designers intended", "Bridges of identical design had performed reliably for a very long time", "The committee lacked the expertise to evaluate structural corrosion", "Deferred maintenance is the leading cause of bridge failures nationwide", "The bridge's joints had been replaced shortly before it failed"],
    correct: 1,
    explanation: "The dissenter's case rests on the observation that 'the same design had supported thousands of similar bridges for over a century without incident,' which undercuts the design-flaw explanation and points elsewhere (B). (A) heavier loads and (E) replaced joints are not mentioned. (C) attacks the committee's competence, which the dissenter does not do. (D) a national statistic is a broader claim than the passage supports; her argument turns on this bridge and its design counterparts, not nationwide data.",
  },
  {
    id: "gre_0010", topicId: 1, domain: "Verbal Reasoning", skill: "Reading Comprehension", difficulty: 1,
    passage: "Migratory songbirds face a peculiar difficulty: the insects they feed their young now hatch, on average, earlier in the spring than they did a few decades ago, as temperatures have risen. The birds, however, time their migration by day length, a cue that has not changed. As a result, many arrive to breed only after the peak of their food supply has already passed.",
    question: "According to the passage, the mismatch faced by the songbirds arises because:",
    options: ["The insects the birds eat have grown scarcer overall", "The birds have begun migrating later than in previous decades", "The cue the birds use to time migration does not track the warming that shifts insect hatching", "Day length in spring has grown shorter over recent decades", "The birds have changed their diet in response to warmer temperatures"],
    correct: 2,
    explanation: "The passage explains that insects hatch earlier because of warming, while the birds rely on day length, 'a cue that has not changed,' so their timing no longer matches the food peak (C). (A) claims fewer insects overall, but the issue is timing, not abundance. (B) reverses the situation—the birds' timing is unchanged, not later. (D) is contradicted, since day length has not changed. (E) a diet change is never mentioned.",
  },
  {
    id: "gre_0011", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 1,
    question: "Although the committee had expected the negotiations to be brief, the two parties' refusal to compromise on even minor points made the process unexpectedly ______.",
    options: ["protracted", "amicable", "succinct", "transparent", "lucrative"],
    correct: 0,
    explanation: "The blank describes a process made long and drawn-out by mutual refusal to compromise. 'Protracted' (extended in time) fits precisely and contrasts with the expected brevity. 'Succinct' is the opposite (brief). 'Amicable' (friendly) contradicts the refusal to compromise. 'Transparent' and 'lucrative' are irrelevant to the length signaled by 'unexpectedly' and the contrast with 'brief.'",
  },
  {
    id: "gre_0012", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 1,
    question: "The documentary was praised for its ______ portrayal of rural life, avoiding both sentimental idealization and cynical exaggeration.",
    options: ["balanced", "nostalgic", "distorted", "hostile", "exuberant"],
    correct: 0,
    explanation: "The phrase 'avoiding both sentimental idealization and cynical exaggeration' signals a portrayal that steers between two extremes, so 'balanced' is uniquely supported. 'Nostalgic' aligns with the sentimental extreme the film avoids; 'distorted' and 'exuberant' suggest exaggeration; 'hostile' aligns with cynicism. Only 'balanced' captures the even-handedness the sentence describes.",
  },
  {
    id: "gre_0013", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 1,
    question: "Far from being ______, the senator's remarks were so vague that reporters left the briefing unsure of what policy she actually endorsed.",
    options: ["explicit", "tedious", "lengthy", "impassioned", "controversial"],
    correct: 0,
    explanation: "'Far from being ___' sets up a contrast with 'so vague,' so the blank needs a word meaning clear or specific. 'Explicit' is that opposite and is uniquely defensible. 'Tedious,' 'lengthy,' 'impassioned,' and 'controversial' are not the logical antonym of 'vague'; a speech can be vague yet still tedious, long, passionate, or controversial, so none provides the required contrast.",
  },
  {
    id: "gre_0014", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 2,
    question: "The critic argued that the novelist's later works, once celebrated for their inventiveness, had grown ______, recycling the same character types and plot devices book after book.",
    options: ["formulaic", "enigmatic", "audacious", "ornate", "polarizing"],
    correct: 0,
    explanation: "The clause 'recycling the same character types and plot devices book after book' defines a lack of originality, and 'once celebrated for their inventiveness' sets up a decline. 'Formulaic' (following a predictable formula) is uniquely supported. 'Audacious' and 'enigmatic' suggest boldness or mystery, not repetition; 'ornate' concerns elaborate style, not sameness; 'polarizing' concerns divided opinion, which the sentence does not address.",
  },
  {
    id: "gre_0015", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 2,
    question: "Because the evidence linking the additive to any measurable harm remained ______, regulators declined to ban the compound, calling instead for further study.",
    options: ["tenuous", "conclusive", "damning", "abundant", "irrefutable"],
    correct: 0,
    explanation: "Regulators declining to ban and calling for more study implies the evidence was weak or insufficient. 'Tenuous' (flimsy, insubstantial) fits and is uniquely defensible. 'Conclusive,' 'damning,' and 'irrefutable' all denote strong evidence that would justify a ban, contradicting the outcome. 'Abundant' concerns quantity, not strength, and would not explain the reluctance to act.",
  },
  {
    id: "gre_0016", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 2,
    question: "The mentor's feedback was valued precisely because it was so ______: she pointed out flaws candidly, without softening them into empty reassurances.",
    options: ["unsparing", "perfunctory", "evasive", "deferential", "effusive"],
    correct: 0,
    explanation: "'Pointed out flaws candidly, without softening them' describes blunt, uncompromising honesty. 'Unsparing' (withholding no criticism) is uniquely supported. 'Perfunctory' means done carelessly, the opposite of valued attention; 'evasive' and 'deferential' both imply avoiding directness; 'effusive' means gushing with praise, which contradicts 'pointed out flaws.'",
  },
  {
    id: "gre_0017", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 2,
    question: "The general's memoir is curiously ______ about his most disastrous campaign, devoting pages to trivial skirmishes while dismissing the defeat in a single sentence.",
    options: ["reticent", "candid", "exhaustive", "boastful", "meticulous"],
    correct: 0,
    explanation: "Dismissing a major defeat 'in a single sentence' while dwelling on trivialities signals deliberate near-silence about the important matter. 'Reticent' (reserved, disinclined to speak) fits uniquely. 'Candid,' 'exhaustive,' and 'meticulous' all imply thorough disclosure, contradicting the one-sentence brush-off; 'boastful' does not match minimizing a disaster.",
  },
  {
    id: "gre_0018", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 3,
    question: "Though popularly remembered as a firebrand, the reformer was in private remarkably ______, weighing objections to his proposals with a patience that surprised even his opponents.",
    options: ["circumspect", "dogmatic", "incendiary", "capricious", "truculent"],
    correct: 0,
    explanation: "'Though' sets up a contrast with 'firebrand,' and 'weighing objections with patience' defines careful, cautious deliberation. 'Circumspect' (prudent, considering all circumstances) is uniquely supported. 'Dogmatic,' 'incendiary,' and 'truculent' reinforce the firebrand image rather than contrasting with it; 'capricious' (impulsive) contradicts the patient weighing of objections.",
  },
  {
    id: "gre_0019", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 3,
    question: "The essayist's prose, admired by some for its density, struck other readers as needlessly ______, burying simple observations beneath layers of qualification and digression.",
    options: ["turgid", "laconic", "limpid", "spare", "perspicuous"],
    correct: 0,
    explanation: "'Burying simple observations beneath layers of qualification and digression' describes overwrought, bloated writing. 'Turgid' (pompous, overblown) is uniquely defensible. 'Laconic' and 'spare' mean terse or economical, the opposite of the described excess; 'limpid' and 'perspicuous' both mean clear and easily understood, contradicting the burying of meaning.",
  },
  {
    id: "gre_0020", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 3,
    question: "Scholars have long treated the chronicle as ______, but recent discoveries of forged interpolations have forced historians to reassess passages once accepted as authentic.",
    options: ["unimpeachable", "apocryphal", "fragmentary", "derivative", "polemical"],
    correct: 0,
    explanation: "'But' contrasts prior trust with newly exposed forgeries, so the blank needs a word meaning beyond question or entirely trustworthy. 'Unimpeachable' (unable to be doubted or discredited) fits uniquely. 'Apocryphal' means of doubtful authenticity, which would not need reassessment in light of forgeries; 'fragmentary,' 'derivative,' and 'polemical' describe other textual qualities that do not set up the required contrast with newly discovered forgery.",
  },
  {
    id: "gre_0021", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 3,
    question: "The philosopher's system, for all its ambition, rests on an assumption so ______ that a single well-chosen counterexample threatens to bring the entire edifice down.",
    options: ["precarious", "axiomatic", "robust", "venerable", "abstruse"],
    correct: 0,
    explanation: "An assumption that one counterexample can topple is dangerously unstable, so 'precarious' (insecure, easily overturned) is uniquely supported. 'Robust' means sturdy, the opposite of vulnerable to a single counterexample; 'axiomatic' means self-evident and would resist refutation; 'venerable' concerns age and respect, and 'abstruse' concerns obscurity, neither of which explains the fragility the sentence emphasizes.",
  },
  {
    id: "gre_0022", topicId: 1, domain: "Verbal Reasoning", skill: "Text Completion (single blank)", difficulty: 3,
    question: "Rather than the sweeping condemnation his colleagues anticipated, the reviewer offered only ______ criticism, tempering each objection with generous acknowledgment of the author's achievements.",
    options: ["measured", "scathing", "wholesale", "perfunctory", "vitriolic"],
    correct: 0,
    explanation: "'Rather than sweeping condemnation' and 'tempering each objection with generous acknowledgment' describe restrained, moderate criticism. 'Measured' (deliberate and restrained) is uniquely defensible. 'Scathing' and 'vitriolic' denote the harshness explicitly ruled out; 'wholesale' matches the sweeping condemnation the reviewer avoided; 'perfunctory' means cursory or indifferent, which does not fit criticism paired with genuine acknowledgment of merit.",
  },
  {
    id: "gre_0023", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 1,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "Although the committee had expected a heated argument, the proposal passed with surprising ease, meeting almost no ________ from the members.",
    options: ["opposition", "enthusiasm", "clarity", "precedent", "funding"],
    correct: 0,
    explanation: "The sentence contrasts an expected 'heated argument' with the proposal passing 'with surprising ease.' The blank names what was NOT encountered, so it must mean resistance: 'opposition' fits perfectly. 'Enthusiasm' reverses the logic (encountering no enthusiasm would explain a failure, not an easy passage). 'Clarity,' 'precedent,' and 'funding' are contextually irrelevant to the argument-versus-ease contrast. On the real test the co-answer would be a synonym such as 'resistance.'",
  },
  {
    id: "gre_0024", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 1,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "The critic praised the novel for its ________ prose, noting that not a single word could be removed without weakening the whole.",
    options: ["economical", "ornate", "tedious", "ambiguous", "derivative"],
    correct: 0,
    explanation: "The clue 'not a single word could be removed' signals prose that is spare and efficient, so 'economical' is correct. 'Ornate' means elaborate and heavily decorated, the opposite of spare. 'Tedious' and 'derivative' are pejorative and clash with 'praised.' 'Ambiguous' addresses unclear meaning, not efficiency. On the real test the co-answer would be a synonym such as 'spare' or 'concise.'",
  },
  {
    id: "gre_0025", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 2,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "Far from being the revolutionary he was reputed to be, the composer was in matters of form deeply ________, borrowing structures that had been fixed for over a century.",
    options: ["conventional", "idiosyncratic", "volatile", "innovative", "reclusive"],
    correct: 0,
    explanation: "'Far from being the revolutionary' sets up a contrast: the composer was actually traditional, confirmed by 'borrowing structures fixed for over a century.' 'Conventional' captures this. 'Innovative' and 'idiosyncratic' align with 'revolutionary,' the very idea being negated. 'Volatile' (unstable) and 'reclusive' (withdrawn) describe temperament or unpredictability, not adherence to established form. On the real test the co-answer would be a synonym such as 'traditional' or 'orthodox.'",
  },
  {
    id: "gre_0026", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 2,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "The senator's apology was so ________ that it managed to placate her critics without ever conceding that she had done anything genuinely wrong.",
    options: ["adroit", "perfunctory", "candid", "belligerent", "verbose"],
    correct: 0,
    explanation: "The apology accomplishes a delicate feat: it placates critics yet concedes no real fault, which requires skill and finesse, so 'adroit' fits. 'Perfunctory' (done carelessly, without effort) would be unlikely to placate anyone. 'Candid' (frank) contradicts the refusal to admit wrongdoing. 'Belligerent' (hostile) is incompatible with placating critics. 'Verbose' (wordy) says nothing about the apology's cleverness. On the real test the co-answer would be a synonym such as 'deft.'",
  },
  {
    id: "gre_0027", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 2,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "Once ________ by scholars as a minor footnote to the period, the pamphlet is now regarded as one of the era's most consequential documents.",
    options: ["dismissed", "celebrated", "banned", "reprinted", "annotated"],
    correct: 0,
    explanation: "The word 'Once' plus the contrast 'now regarded as one of the most consequential' signals a reversal from low to high esteem; the blank must express prior low regard: 'dismissed' fits ('minor footnote' reinforces this). 'Celebrated' would already grant it high status, leaving nothing to reverse. 'Banned' concerns suppression, not scholarly estimation of importance. 'Reprinted' and 'annotated' describe treatment of the text, not evaluation of its significance. On the real test the co-answer would be a synonym such as 'disregarded.'",
  },
  {
    id: "gre_0028", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 3,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "The biographer's refusal to varnish her subject's failings lends the portrait a ________ that more admiring accounts, for all their polish, conspicuously lack.",
    options: ["candor", "opacity", "grandeur", "levity", "timidity"],
    correct: 0,
    explanation: "Not varnishing (i.e., not glossing over) failings produces honesty; the blank names the quality that flattering accounts lack, so 'candor' is correct. 'Opacity' (impenetrability) is nearly opposite to the transparency implied by refusing to conceal. 'Grandeur' and 'levity' name unrelated qualities (magnificence, lightness). 'Timidity' contradicts the boldness of exposing failings. The trap is 'polish,' which tempts a reader toward an aesthetic word, but the contrast is between honest exposure and flattering concealment. On the real test the co-answer would be a synonym such as 'frankness.'",
  },
  {
    id: "gre_0029", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 3,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "Rather than settling the dispute, the arbiter's ruling proved so ________ that both parties claimed vindication and neither felt bound to alter its conduct.",
    options: ["equivocal", "stringent", "conciliatory", "exhaustive", "peremptory"],
    correct: 0,
    explanation: "If both parties could each claim victory and neither felt constrained, the ruling must have been ambiguous, open to opposing readings: 'equivocal' fits. 'Stringent' (strict) and 'peremptory' (allowing no dispute) would compel compliance, contradicting that neither felt bound. 'Conciliatory' tempts because both sides seem satisfied, but a conciliatory ruling seeks compromise, whereas here each side reads total vindication, indicating vagueness rather than mediation. 'Exhaustive' (thorough) would tend to leave no room for opposing interpretations. On the real test the co-answer would be a synonym such as 'ambiguous.'",
  },
  {
    id: "gre_0030", topicId: 1, domain: "Verbal Reasoning", skill: "Sentence Equivalence", difficulty: 3,
    passage: "Sentence Equivalence (adapted to single-best): choose the ONE word that best completes the sentence. On the actual GRE, this item type asks you to select TWO words that both fit the sentence and produce sentences alike in meaning.",
    question: "The essayist's reputation for ________ is misleading; beneath the placid, unhurried surface of his sentences lies a temperament forever on the verge of indignation.",
    options: ["equanimity", "erudition", "prolixity", "cynicism", "asperity"],
    correct: 0,
    explanation: "The blank is a reputation the sentence calls 'misleading,' contrasted with a hidden temperament 'on the verge of indignation'; the 'placid, unhurried surface' points to apparent calm, so 'equanimity' (composure) is correct. 'Asperity' (harshness) matches the hidden indignation, not the misleading calm surface it must contrast with. 'Cynicism' is a plausible inner trait but not what the placid surface conveys, and it does not contrast with indignation. 'Erudition' (learning) and 'prolixity' (wordiness) are unrelated to the calm-versus-anger opposition the sentence builds. On the real test the co-answer would be a synonym such as 'composure.'",
  },
  {
    id: "gre_0031", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 1,
    passage: "x is a positive number.",
    question: "Quantity A: 3x/4\nQuantity B: 2x/3",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 0,
    explanation: "Since x is positive, comparing the coefficients suffices. 3/4 = 0.75 and 2/3 ≈ 0.667, so 3x/4 > 2x/3 for every positive x; multiplying both sides of 3/4 > 2/3 by the positive value x preserves the inequality. Quantity A is greater. 'Equal' fails because the fractions differ; 'B greater' reverses the comparison; 'cannot be determined' fails because the sign of x is fixed as positive, so the direction never changes.",
  },
  {
    id: "gre_0032", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 1,
    question: "Quantity A: 25% of 80\nQuantity B: 80% of 25",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 2,
    explanation: "25% of 80 = 0.25 × 80 = 20, and 80% of 25 = 0.80 × 25 = 20. Because a% of b always equals b% of a (both equal ab/100), the quantities are equal. The 'greater' options fail since both evaluate to exactly 20; 'cannot be determined' fails because both are fixed constants with no variables.",
  },
  {
    id: "gre_0033", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 1,
    passage: "n is an integer and 4 < n < 8.",
    question: "Quantity A: n\nQuantity B: 6",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 3,
    explanation: "The integers strictly between 4 and 8 are 5, 6, and 7. If n = 5, Quantity B is greater; if n = 6, the quantities are equal; if n = 7, Quantity A is greater. Since more than one relationship is possible, the answer cannot be determined. Each of the three fixed-relationship options fails because it holds for only some allowed values of n, not all.",
  },
  {
    id: "gre_0034", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 2,
    passage: "0 < x < 1.",
    question: "Quantity A: x²\nQuantity B: x³",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 0,
    explanation: "For a number strictly between 0 and 1, higher powers get smaller. Formally, x³ = x²·x, and since 0 < x < 1 we have x < 1, so multiplying the positive quantity x² by a factor less than 1 decreases it: x³ < x². Thus Quantity A is greater. 'B greater' is the classic trap of assuming a cube always exceeds a square; 'equal' would require x = 0 or x = 1, both excluded; the constrained range fixes the direction, so it is determinable.",
  },
  {
    id: "gre_0035", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 2,
    passage: "The average (arithmetic mean) of 5 numbers is 12.",
    question: "Quantity A: the sum of the 5 numbers\nQuantity B: 60",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 2,
    explanation: "Average = sum ÷ count, so sum = average × count = 12 × 5 = 60. The sum is fixed at 60 regardless of the individual values, so the quantities are equal. The 'greater' options fail because the sum is uniquely determined; 'cannot be determined' is a trap for those who think the unknown individual values matter, but only their total is asked for and that total is pinned down.",
  },
  {
    id: "gre_0036", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 2,
    passage: "a and b are positive numbers with a + b = 10.",
    question: "Quantity A: ab\nQuantity B: 24",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 3,
    explanation: "With a + b = 10 fixed, the product ab ranges over (0, 25]: it is maximized at 25 when a = b = 5, and approaches 0 as one variable nears 0. For example, a = 5, b = 5 gives ab = 25 > 24 (Quantity A greater), while a = 1, b = 9 gives ab = 9 < 24 (Quantity B greater). Since both directions occur, the relationship cannot be determined. Any single fixed-relationship choice fails because it does not hold across all valid (a, b).",
  },
  {
    id: "gre_0037", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 2,
    passage: "A line in the xy-plane has equation y = 2x − 3.",
    question: "Quantity A: the y-coordinate of the line's y-intercept\nQuantity B: the x-coordinate of the line's x-intercept",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 1,
    explanation: "The y-intercept occurs at x = 0: y = 2(0) − 3 = −3, so Quantity A = −3. The x-intercept occurs at y = 0: 0 = 2x − 3, giving x = 3/2 = 1.5, so Quantity B = 1.5. Since 1.5 > −3, Quantity B is greater. 'A greater' ignores that −3 is negative; 'equal' is wrong since the values differ; the line is fully specified, so it is determinable.",
  },
  {
    id: "gre_0038", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 3,
    passage: "x < 0.",
    question: "Quantity A: (x − 1)²\nQuantity B: (x + 1)²",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 0,
    explanation: "Expand the difference: (x − 1)² − (x + 1)² = (x² − 2x + 1) − (x² + 2x + 1) = −4x. Since x < 0, −4x > 0, so (x − 1)² > (x + 1)² for every negative x. Quantity A is greater. Checking x = −2 gives 9 vs 1, confirming this. 'Equal' would require x = 0 (excluded); 'B greater' reverses the sign of −4x; because the sign of x is fixed negative, the comparison never flips, so it is determinable.",
  },
  {
    id: "gre_0039", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 3,
    passage: "2^a = 8 and 3^b = 81.",
    question: "Quantity A: a\nQuantity B: b",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 1,
    explanation: "Since 8 = 2³, we get a = 3. Since 81 = 3⁴, we get b = 4. Thus b > a, and Quantity B is greater. The larger base (3) reaching a larger power might mislead intuition, but solving each equation gives exact values. 'A greater' and 'equal' contradict a = 3, b = 4; both equations have unique real solutions, so the relationship is fully determined.",
  },
  {
    id: "gre_0040", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 3,
    passage: "x is a real number.",
    question: "Quantity A: x² + 1\nQuantity B: 2x",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 3,
    explanation: "Consider the difference: (x² + 1) − 2x = (x − 1)², which is always ≥ 0. So Quantity A ≥ Quantity B for all x, with equality exactly when x = 1. For x = 1 the quantities are equal, but for x = 0 we get 1 vs 0 (Quantity A greater). Since the comparison is sometimes 'equal' and sometimes 'A greater,' no single relationship holds for all x, so it cannot be determined. 'A greater' is the trap: it is true for most x but fails at x = 1, where they are equal — a QC answer must hold for every allowed value.",
  },
  {
    id: "gre_0041", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 3,
    passage: "A circle has radius r and a square has side length r, where r > 0.",
    question: "Quantity A: the area of the circle\nQuantity B: the area of the square",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 0,
    explanation: "The circle's area is πr² and the square's area is r². Their ratio is πr² / r² = π ≈ 3.14 > 1, independent of the value of r. So the circle's area is always greater, and Quantity A is greater. 'Equal' or 'B greater' would require π ≤ 1, which is false; 'cannot be determined' is a trap for those who think the unknown r matters, but r² cancels, leaving the constant π.",
  },
  {
    id: "gre_0042", topicId: 0, domain: "Quantitative Reasoning", skill: "Quantitative Comparison", difficulty: 2,
    passage: "0 < x < y.",
    question: "Quantity A: x / y\nQuantity B: (x + 2) / (y + 2)",
    options: ["Quantity A is greater", "Quantity B is greater", "The two quantities are equal", "The relationship cannot be determined from the information given."],
    correct: 1,
    explanation: "Cross-multiply (all denominators positive): compare x(y + 2) = xy + 2x with (x + 2)y = xy + 2y. Since 0 < x < y, we have 2x < 2y, so xy + 2x < xy + 2y, meaning x/y < (x + 2)/(y + 2). Adding the same positive amount to numerator and denominator of a proper fraction (one less than 1) moves it closer to 1, i.e., increases it. Quantity B is greater. 'A greater' reverses this; 'equal' would require x = y (excluded); the strict inequality 0 < x < y fixes the direction, so it is determinable.",
  },
  {
    id: "gre_0043", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 1,
    question: "What is the sum of the first 30 positive even integers?",
    options: ["465", "900", "930", "960", "1860"],
    correct: 2,
    explanation: "The first 30 positive even integers are 2, 4, ..., 60. Their sum equals 2(1 + 2 + ... + 30) = 2 * (30*31/2) = 30*31 = 930. Distractor 465 is the sum of the first 30 positive integers (1..30), forgetting to double. 900 comes from wrongly using 30^2. 960 comes from miscounting the last term. 1860 = 2*930 double-counts by doubling twice.",
  },
  {
    id: "gre_0044", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 1,
    question: "What is the least common multiple of 12 and 18?",
    options: ["6", "36", "54", "72", "216"],
    correct: 1,
    explanation: "12 = 2^2 * 3 and 18 = 2 * 3^2. The LCM takes the highest power of each prime: 2^2 * 3^2 = 4 * 9 = 36. Distractor 6 is the GCD, not the LCM. 216 = 12*18 is the product, which equals LCM*GCD, not the LCM alone. 54 is a multiple of 18 but not of 12, and 72 is a multiple of 36 but not the smallest common multiple, so neither is the LCM.",
  },
  {
    id: "gre_0045", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 1,
    question: "How many two-digit positive integers have digits that sum to 9?",
    options: ["8", "9", "10", "11", "18"],
    correct: 1,
    explanation: "The two-digit numbers with digit sum 9 are 18, 27, 36, 45, 54, 63, 72, 81, and 90 — exactly 9 of them. Distractor 8 comes from omitting 90 (thinking the units digit cannot be 0, but 90 is valid). 10 comes from wrongly including 09, which is not a two-digit number. 18 double-counts. The tens digit runs from 1 to 9, forcing a unique units digit each time, giving 9 numbers.",
  },
  {
    id: "gre_0046", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 1,
    question: "What is the value of (2^10 - 2^8) / 2^7 ?",
    options: ["2", "3", "4", "6", "12"],
    correct: 3,
    explanation: "Factor the numerator: 2^10 - 2^8 = 2^8(2^2 - 1) = 2^8 * 3. Dividing by 2^7 gives 2^(8-7) * 3 = 2 * 3 = 6. Distractor 3 forgets the factor of 2 (dividing 2^8 by 2^7 leaves 2, not 1). Distractor 2 keeps only the power of two and drops the 3. Distractor 12 doubles the result. Distractor 4 = 2^2 comes from subtracting exponents incorrectly.",
  },
  {
    id: "gre_0047", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 2,
    question: "What is the units digit of 3^47 ?",
    options: ["1", "3", "7", "8", "9"],
    correct: 2,
    explanation: "The units digits of powers of 3 cycle with period 4: 3^1=3, 3^2=9, 3^3=7, 3^4=1, then repeat. Since 47 = 4*11 + 3, the units digit matches that of 3^3, which is 7. Distractor 3 (position 1), 9 (position 2), and 1 (position 4) are the other cycle values chosen with a wrong remainder. 8 is not in the cycle at all. The key is 47 mod 4 = 3.",
  },
  {
    id: "gre_0048", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 2,
    question: "How many positive divisors does 360 have?",
    options: ["12", "16", "20", "24", "30"],
    correct: 3,
    explanation: "Factor 360 = 2^3 * 3^2 * 5^1. The number of positive divisors is (3+1)(2+1)(1+1) = 4 * 3 * 2 = 24. Distractor 12 comes from forgetting to add 1 to one of the exponents before multiplying. 16 uses a wrong exponent for 3. 20 and 30 result from other arithmetic slips in applying the divisor-count formula. The correct method adds 1 to each exponent before multiplying.",
  },
  {
    id: "gre_0049", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 2,
    question: "What is the remainder when 7^100 is divided by 5?",
    options: ["0", "1", "2", "3", "4"],
    correct: 1,
    explanation: "Since 7 leaves remainder 2 mod 5, 7^100 is congruent to 2^100 mod 5. Powers of 2 mod 5 cycle 2, 4, 3, 1 with period 4. Because 100 is a multiple of 4, 2^100 is congruent to 1 mod 5. So the remainder is 1. Distractor 2 wrongly uses 7 congruent to 2 without accounting for the exponent's cycle. Distractor 4 picks the wrong position in the 2,4,3,1 cycle. 0 and 3 are cycle values selected with an incorrect exponent remainder.",
  },
  {
    id: "gre_0050", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 2,
    question: "How many integers from 1 to 200, inclusive, are divisible by 6 but NOT by 4?",
    options: ["13", "16", "17", "20", "33"],
    correct: 2,
    explanation: "Multiples of 6 up to 200: floor(200/6) = 33. Among these, those also divisible by 4 are divisible by lcm(6,4) = 12: floor(200/12) = 16. So the count divisible by 6 but not by 4 is 33 - 16 = 17. Distractor 33 counts all multiples of 6 (ignoring the 'not by 4' condition). Distractor 16 counts the multiples of 12 that must be removed. Distractor 20 wrongly subtracts multiples of 24 instead of 12. 13 mis-subtracts.",
  },
  {
    id: "gre_0051", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 2,
    question: "What is the sum of the distinct prime factors of 84?",
    options: ["7", "10", "12", "14", "19"],
    correct: 2,
    explanation: "84 = 2^2 * 3 * 7, so the distinct prime factors are 2, 3, and 7, summing to 12. Distractor 14 = 2+2+3+7 double-counts the repeated factor 2 (using all prime factors with multiplicity). Distractor 7 gives only the largest prime factor. 10 = 3+7 omits 2, and 19 is an unrelated sum. The word 'distinct' means each prime is counted once.",
  },
  {
    id: "gre_0052", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 3,
    question: "n is the least positive integer that leaves a remainder of 3 when divided by 7 and a remainder of 2 when divided by 5. What is the value of n?",
    options: ["12", "17", "22", "31", "37"],
    correct: 1,
    explanation: "Numbers that leave remainder 3 mod 7 are 3, 10, 17, 24, ... . Testing these against remainder 2 mod 5 (units digit 2 or 7): 3 mod 5 = 3 (no), 10 mod 5 = 0 (no), 17 mod 5 = 2 (yes). So n = 17. Distractor 12 satisfies 12 mod 5 = 2 but 12 mod 7 = 5, failing the first condition. Distractor 22 satisfies 22 mod 5 = 2 but 22 mod 7 = 1. Distractor 37 gives 37 mod 7 = 2 (not 3), so it fails the first condition. Distractor 31 gives 31 mod 7 = 3 but 31 mod 5 = 1, failing the second. Only 17 satisfies both conditions and is least.",
  },
  {
    id: "gre_0053", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 3,
    question: "If x and y are positive integers such that x + y = 15 and the product xy is as large as possible, what is the value of xy ?",
    options: ["44", "54", "56", "560", "225"],
    correct: 2,
    explanation: "For a fixed sum, the product of two positive integers is maximized when the integers are as close as possible. Since 15 is odd, the closest split is 7 and 8, giving xy = 7*8 = 56. Distractor 54 = 6*9 and 44 = 4*11 use non-optimal splits. Distractor 225 = 15^2 mistakenly squares the sum itself. 560 mistakenly multiplies by an extra factor of 10. The integer constraint forces the split 7 and 8.",
  },
  {
    id: "gre_0054", topicId: 0, domain: "Quantitative Reasoning", skill: "Arithmetic and Number Properties", difficulty: 3,
    question: "Which of the following fractions is greatest?",
    options: ["3/5", "5/8", "7/11", "9/14", "2/3"],
    correct: 4,
    explanation: "Convert to decimals: 3/5 = 0.600, 5/8 = 0.625, 7/11 ≈ 0.636, 9/14 ≈ 0.643, 2/3 ≈ 0.667. The largest is 2/3. A useful check: compare each to 2/3 by cross-multiplication — e.g., 9/14 vs 2/3 gives 27 vs 28, so 9/14 < 2/3; and 7/11 vs 2/3 gives 21 vs 22, so 7/11 < 2/3. Every other option is strictly less than 2/3, so 2/3 is uniquely greatest. The near-miss distractor 9/14 (≈0.643) is designed to trap quick estimation.",
  },
  {
    id: "gre_0055", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 1,
    question: "If 3x - 7 = 11, what is the value of 5x + 2?",
    options: ["12", "28", "30", "32", "34"],
    correct: 3,
    explanation: "Solve 3x - 7 = 11: add 7 to get 3x = 18, so x = 6. Then 5x + 2 = 5(6) + 2 = 32. Option E (34) comes from a miscalculation; A (12) reflects sign errors; B (28) uses 5(6) - 2; C (30) forgets the +2. Only 32 is correct.",
  },
  {
    id: "gre_0056", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 1,
    question: "A number n satisfies n/4 + 3 = 10. What is the value of n?",
    options: ["18", "24", "28", "32", "40"],
    correct: 2,
    explanation: "From n/4 + 3 = 10, subtract 3 to get n/4 = 7, so n = 28. Option A (18) uses n/4 = 4.5 from a wrong subtraction; B (24) treats the equation as n/4 = 6; D (32) uses n/4 = 8; E (40) uses n/4 = 10, ignoring the +3. Only 28 satisfies the equation.",
  },
  {
    id: "gre_0057", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 1,
    question: "If 2(x + 5) = 3x - 4, what is the value of x?",
    options: ["-14", "-6", "6", "14", "24"],
    correct: 3,
    explanation: "Expand: 2x + 10 = 3x - 4. Subtract 2x from both sides: 10 = x - 4, so x = 14. Option A (-14) is a sign error; B (-6) comes from mishandling the subtraction; C (6) drops a term; E (24) adds instead of subtracts. Only x = 14 checks: 2(19) = 38 and 3(14) - 4 = 38.",
  },
  {
    id: "gre_0058", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 2,
    question: "If x^2 - 5x + 6 = 0 and x > 2, what is the value of x?",
    options: ["1", "2", "3", "5", "6"],
    correct: 2,
    explanation: "Factor: (x - 2)(x - 3) = 0, so x = 2 or x = 3. The condition x > 2 selects x = 3. Option B (2) is the excluded root; A (1) is not a root; D (5) and E (6) come from misreading the constant or linear terms. Only x = 3 satisfies both the equation and x > 2.",
  },
  {
    id: "gre_0059", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 2,
    question: "The line y = mx + b passes through the points (1, 5) and (3, 11). What is the value of b?",
    options: ["1", "2", "3", "5", "8"],
    correct: 1,
    explanation: "Slope m = (11 - 5)/(3 - 1) = 6/2 = 3. Using (1, 5): 5 = 3(1) + b, so b = 2. Option A (1) misuses a point; C (3) is the slope m, not b; D (5) is the y-value at x = 1; E (8) comes from adding m and a coordinate. Only b = 2 gives a line through both points.",
  },
  {
    id: "gre_0060", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 2,
    question: "If sqrt(2x + 3) = 5, what is the value of x?",
    options: ["1", "4", "11", "14", "22"],
    correct: 2,
    explanation: "Square both sides: 2x + 3 = 25, so 2x = 22 and x = 11. Option A (1) mishandles the square; B (4) uses 5 without squaring; D (14) uses 2x + 3 = 31; E (22) forgets to divide by 2. Only x = 11 gives sqrt(25) = 5.",
  },
  {
    id: "gre_0061", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 2,
    question: "If a and b are numbers such that a + b = 10 and a - b = 4, what is the value of ab?",
    options: ["16", "20", "21", "24", "25"],
    correct: 2,
    explanation: "Adding the equations: 2a = 14, so a = 7; then b = 3. Thus ab = 7 * 3 = 21. Option A (16) uses a wrong split; B (20) comes from a = 5, b = 4 errors; D (24) uses a = 8, b = 3; E (25) uses a = b = 5. Only ab = 21 satisfies both original equations.",
  },
  {
    id: "gre_0062", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 3,
    question: "If 2^(x+1) = 8^(x-1), what is the value of x?",
    options: ["1", "2", "3", "4", "5"],
    correct: 1,
    explanation: "Write 8 = 2^3, so 8^(x-1) = 2^(3x-3). Set exponents equal: x + 1 = 3x - 3, giving 4 = 2x, so x = 2. Option A (1) comes from a sign slip; C (3) sets x + 1 = 3x incorrectly; D (4) and E (5) come from arithmetic errors. Only x = 2 makes both sides equal 8.",
  },
  {
    id: "gre_0063", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 3,
    question: "For all x not equal to 3, the expression (x^2 - 9)/(x - 3) is equivalent to which of the following?",
    options: ["x - 3", "x + 3", "x^2 - 3", "x - 9", "x + 9"],
    correct: 1,
    explanation: "Factor the numerator as a difference of squares: x^2 - 9 = (x - 3)(x + 3). Cancel the common (x - 3) factor (valid since x != 3), leaving x + 3. Option A (x - 3) keeps the wrong factor; C, D, and E do not follow from correct factoring. Only x + 3 is equivalent.",
  },
  {
    id: "gre_0064", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 3,
    question: "If f(x) = 2x^2 - 3x + 1, what is the value of f(a + 1) - f(a) in terms of a?",
    options: ["4a - 1", "4a + 1", "2a - 1", "4a - 3", "2a + 1"],
    correct: 0,
    explanation: "f(a+1) = 2(a+1)^2 - 3(a+1) + 1 = 2a^2 + 4a + 2 - 3a - 3 + 1 = 2a^2 + a. And f(a) = 2a^2 - 3a + 1. Subtract: (2a^2 + a) - (2a^2 - 3a + 1) = 4a - 1. Option B (4a + 1) drops the -1; C and E mishandle the squared term; D (4a - 3) uses a wrong constant. Only 4a - 1 is correct.",
  },
  {
    id: "gre_0065", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 3,
    question: "The sum of the roots of the equation x^2 - kx + 12 = 0 is 7. What is the value of k times the product of the roots?",
    options: ["7", "12", "19", "84", "144"],
    correct: 3,
    explanation: "For x^2 - kx + 12 = 0, the sum of the roots equals k and the product equals 12. Given the sum is 7, k = 7. The product of the roots is 12, so k times the product = 7 * 12 = 84. Option A (7) is just k; B (12) is just the product; C (19) adds instead of multiplies; E (144) squares the product. Only 84 is correct.",
  },
  {
    id: "gre_0066", topicId: 0, domain: "Quantitative Reasoning", skill: "Algebra", difficulty: 3,
    question: "If 1/x + 1/y = 1/4 and x = y, what is the value of x?",
    options: ["2", "4", "6", "8", "16"],
    correct: 3,
    explanation: "With x = y, the equation becomes 2/x = 1/4, so x = 8. Option A (2) comes from a 2/x = 1 error; B (4) treats 1/x = 1/4, ignoring the doubling; C (6) is an arithmetic slip; E (16) doubles incorrectly. Check: 1/8 + 1/8 = 2/8 = 1/4. Only x = 8 works.",
  },
  {
    id: "gre_0067", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 1,
    question: "In a right triangle, the two legs have lengths 9 and 12. What is the length of the hypotenuse?",
    options: ["13", "15", "18", "21", "sqrt(63)"],
    correct: 1,
    explanation: "By the Pythagorean theorem, hypotenuse = sqrt(9^2 + 12^2) = sqrt(81 + 144) = sqrt(225) = 15. This is the key. The distractor 13 comes from mistakenly using legs 5 and 12; 18 and 21 come from adding or manipulating the legs directly (9+12=21) rather than squaring; sqrt(63) comes from subtracting the squares (144-81=63), which would find a leg given the hypotenuse, not the hypotenuse itself.",
  },
  {
    id: "gre_0068", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 1,
    question: "A circle has a circumference of 16*pi. What is the area of the circle?",
    options: ["8*pi", "16*pi", "32*pi", "64*pi", "256*pi"],
    correct: 3,
    explanation: "Circumference = 2*pi*r = 16*pi gives r = 8. Area = pi*r^2 = pi*8^2 = 64*pi, which is the key. The distractor 8*pi mistakes the radius (8) for the area; 16*pi just repeats the circumference; 32*pi doubles the radius instead of squaring it; 256*pi squares the diameter (16) instead of the radius.",
  },
  {
    id: "gre_0069", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 1,
    question: "An isosceles triangle has a vertex (apex) angle of 40 degrees. What is the measure of each of its two equal base angles?",
    options: ["40 degrees", "50 degrees", "70 degrees", "100 degrees", "140 degrees"],
    correct: 2,
    explanation: "The three angles sum to 180 degrees. The two base angles are equal, so each equals (180 - 40)/2 = 140/2 = 70 degrees, the key. The distractor 140 is the sum of the two base angles before dividing; 50 assumes a right angle somewhere (90-40); 100 comes from 140-40; 40 wrongly assumes all listed angles are equal.",
  },
  {
    id: "gre_0070", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 2,
    question: "A square has a side length of 10. A circle is inscribed in the square so that it touches all four sides. What is the area of the region inside the square but outside the circle?",
    options: ["100 - 25*pi", "100 - 100*pi", "100 - 10*pi", "25*pi", "100 - 50*pi"],
    correct: 0,
    explanation: "The square has area 10^2 = 100. The inscribed circle has diameter 10, so radius 5 and area pi*5^2 = 25*pi. The region between them is 100 - 25*pi, the key. The distractor 100 - 100*pi uses radius 10 (the diameter) instead of 5; 100 - 10*pi mistakenly uses the side length as the radius-squared factor; 25*pi is only the circle's area, not the difference; 100 - 50*pi doubles the correct circle area.",
  },
  {
    id: "gre_0071", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 2,
    question: "In the coordinate plane, point A is at (2, 3) and point B is at (7, 15). What is the distance between A and B?",
    options: ["12", "13", "17", "sqrt(17)", "sqrt(29)"],
    correct: 1,
    explanation: "Distance = sqrt((7-2)^2 + (15-3)^2) = sqrt(5^2 + 12^2) = sqrt(25 + 144) = sqrt(169) = 13, the key. The distractor 17 adds the leg differences (5+12) instead of squaring; sqrt(17) takes the square root of that sum (5+12) rather than of the sum of squares; 12 uses only the vertical difference; sqrt(29) squares and adds the wrong differences (2^2 + 5^2) instead of the coordinate gaps.",
  },
  {
    id: "gre_0072", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 2,
    question: "A cube has a total surface area of 96 square units. What is the volume of the cube, in cubic units?",
    options: ["16", "48", "64", "96", "512"],
    correct: 2,
    explanation: "A cube has 6 congruent square faces, so 6*e^2 = 96 gives e^2 = 16 and edge e = 4. Volume = e^3 = 4^3 = 64, the key. The distractor 16 stops at e^2 (a single face area); 48 halves the surface area; 96 repeats the surface area; 512 uses edge 8 (from taking e^2 = 96/... incorrectly, or cubing the wrong root).",
  },
  {
    id: "gre_0073", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 2,
    question: "Two triangles are similar. The ratio of the length of a side in the smaller triangle to the corresponding side in the larger triangle is 3 to 5. What is the ratio of the area of the smaller triangle to the area of the larger triangle?",
    options: ["3 to 5", "6 to 10", "9 to 25", "9 to 15", "27 to 125"],
    correct: 2,
    explanation: "For similar figures, the ratio of areas equals the square of the ratio of corresponding sides: (3/5)^2 = 9/25, the key. The distractor 3 to 5 forgets to square (that is the side ratio); 6 to 10 just scales the side ratio linearly; 9 to 15 squares only the numerator; 27 to 125 cubes the ratio, which would apply to volumes of similar solids, not areas of triangles.",
  },
  {
    id: "gre_0074", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 3,
    question: "A right circular cone has a base radius of 6 and a height of 8. What is the lateral (side) surface area of the cone? (Lateral surface area = pi * r * l, where l is the slant height.)",
    options: ["48*pi", "60*pi", "96*pi", "100*pi", "36*pi"],
    correct: 1,
    explanation: "The slant height is l = sqrt(r^2 + h^2) = sqrt(6^2 + 8^2) = sqrt(36 + 64) = sqrt(100) = 10. Lateral surface area = pi*r*l = pi*6*10 = 60*pi, the key. The distractor 48*pi uses the height (8) as the slant height (pi*6*8); 96*pi uses pi*r*(r+h)... or doubles incorrectly; 100*pi uses the slant-height computation l^2 in place of r*l; 36*pi uses pi*r^2, the base area, not the lateral area.",
  },
  {
    id: "gre_0075", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 3,
    question: "A square has a side length of 8. At each of the four corners of the square, a quarter circle of radius 4 is drawn inside the square, with its center at that corner. What is the area of the region of the square not covered by any of the quarter circles?",
    options: ["64 - 16*pi", "64 - 4*pi", "64 - 64*pi", "64 - 32*pi", "16 - 16*pi"],
    correct: 0,
    explanation: "The square has area 8^2 = 64. Four quarter circles of radius 4 together make one full circle of area pi*4^2 = 16*pi, and since radius 4 is exactly half the side, none of them overlap. Uncovered area = 64 - 16*pi, the key. The distractor 64 - 4*pi uses only one quarter circle's area (16*pi/4 = 4*pi); 64 - 64*pi treats each quarter as a full circle of radius 4 times four; 64 - 32*pi doubles the true circle area; 16 - 16*pi uses the wrong square area (mistaking side 4 for the square).",
  },
  {
    id: "gre_0076", topicId: 0, domain: "Quantitative Reasoning", skill: "Geometry", difficulty: 3,
    question: "In a circle, a central angle intercepts an arc. An inscribed angle intercepts the same arc. If the central angle measures 100 degrees, what is the measure of the inscribed angle?",
    options: ["25 degrees", "40 degrees", "50 degrees", "100 degrees", "200 degrees"],
    correct: 2,
    explanation: "The inscribed angle theorem states that an inscribed angle is half the central angle subtending the same arc. So the inscribed angle = 100/2 = 50 degrees, the key. The distractor 100 wrongly sets them equal; 200 doubles instead of halves (reversing the relationship); 25 divides by 4; 40 comes from an unjustified (100 minus supplement) manipulation such as treating the arc's complement, none of which the theorem supports.",
  },
  {
    id: "gre_0077", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 1,
    question: "The five values in a data set are 8, 12, 15, 20, and 25. What is the arithmetic mean (average) of the data set?",
    options: ["15", "16", "17", "18", "20"],
    correct: 1,
    explanation: "The mean is the sum divided by the count: (8 + 12 + 15 + 20 + 25) / 5 = 80 / 5 = 16, so the key is 16. Choice 15 is the median, not the mean. Choice 17 results from a wrong sum such as 85/5. Choices 18 and 20 do not correspond to any correct computation and are inflated guesses. Only 16 satisfies the definition of arithmetic mean.",
  },
  {
    id: "gre_0078", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 1,
    question: "In a data set of 7 numbers arranged in increasing order, the values are 3, 5, 9, 11, 14, 18, 22. What is the median?",
    options: ["9", "11", "12", "14", "82/7"],
    correct: 1,
    explanation: "For 7 ordered values, the median is the 4th value (the middle one). Counting 3, 5, 9, 11, 14, 18, 22, the 4th term is 11, so the key is 11. Choice 9 is the 3rd value. Choice 12 is not a value in the set. Choice 14 is the 5th value. Choice 82/7 is the mean (sum 82 divided by 7), not the median. Only 11 is the middle term.",
  },
  {
    id: "gre_0079", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 1,
    question: "A jar contains 4 red marbles, 6 blue marbles, and 10 green marbles. If one marble is drawn at random, what is the probability that it is blue?",
    options: ["1/5", "3/10", "6/16", "3/7", "2/5"],
    correct: 1,
    explanation: "Total marbles = 4 + 6 + 10 = 20. Probability of blue = 6/20 = 3/10, so the key is 3/10. Choice 1/5 = 4/20 is the probability of red. Choice 6/16 wrongly excludes the green count from the total (uses 16 instead of 20). Choice 3/7 comes from an unrelated ratio. Choice 2/5 = 8/20 does not match the 6 blue marbles. Only 3/10 is correct.",
  },
  {
    id: "gre_0080", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 2,
    question: "A data set has 6 values with a mean of 15. If a seventh value of 29 is added to the data set, what is the mean of the 7 values?",
    options: ["16", "17", "18", "22", "119/6"],
    correct: 1,
    explanation: "The original sum is 6 * 15 = 90. Adding 29 gives a new sum of 90 + 29 = 119 over 7 values: 119 / 7 = 17, so the key is 17. Choice 16 is a miscount of the new mean. Choice 18 overshoots. Choice 22 averages 15 and 29 incorrectly. Choice 119/6 wrongly keeps the divisor at 6 instead of 7. Only 17 is correct.",
  },
  {
    id: "gre_0081", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 2,
    question: "The standard deviation of the data set {4, 4, 4, 4} is s. What is the value of s?",
    options: ["0", "1", "2", "4", "sqrt(4)"],
    correct: 0,
    explanation: "When all values in a data set are identical, every value equals the mean (here 4), so each deviation from the mean is 0 and the standard deviation is 0. The key is 0. Choices 1 and 2 assume nonzero spread that does not exist. Choice 4 confuses the common value with the spread. Choice sqrt(4) = 2 again assumes a variance of 4, which is false since the variance is 0. Only 0 is correct.",
  },
  {
    id: "gre_0082", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 2,
    question: "A fair six-sided die is rolled twice. What is the probability that the sum of the two rolls equals 7?",
    options: ["1/12", "1/9", "1/6", "5/36", "7/36"],
    correct: 2,
    explanation: "There are 36 equally likely outcomes. Sums of 7 occur for (1,6),(2,5),(3,4),(4,3),(5,2),(6,1): 6 outcomes. Probability = 6/36 = 1/6, so the key is 1/6. Choice 1/12 = 3/36 undercounts the pairs. Choice 1/9 = 4/36 also undercounts. Choice 5/36 corresponds to a sum of 6 or 8, not 7. Choice 7/36 mistakenly uses 7 outcomes. Only 1/6 is correct for a sum of 7.",
  },
  {
    id: "gre_0083", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 2,
    question: "In a normal distribution with mean 50 and standard deviation 8, approximately what percent of the data lies between 42 and 58? (Use the approximation that about 68% of data lies within one standard deviation of the mean.)",
    options: ["34%", "50%", "68%", "95%", "99.7%"],
    correct: 2,
    explanation: "The interval 42 to 58 spans from mean minus one standard deviation (50 - 8 = 42) to mean plus one standard deviation (50 + 8 = 58). By the empirical rule, about 68% of data lies within one standard deviation of the mean, so the key is 68%. Choice 34% is only one side (half of 68%). Choice 50% is the proportion below the mean. Choice 95% corresponds to two standard deviations. Choice 99.7% corresponds to three standard deviations. Only 68% matches a one-SD interval.",
  },
  {
    id: "gre_0084", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 2,
    question: "A data set of 5 numbers has a mean of 20. Four of the numbers are 14, 18, 22, and 26. What is the fifth number?",
    options: ["18", "20", "22", "24", "80"],
    correct: 1,
    explanation: "The total sum must be 5 * 20 = 100. The four known values sum to 14 + 18 + 22 + 26 = 80. The fifth number is 100 - 80 = 20, so the key is 20. Choices 18 and 22 are existing values, not the missing one. Choice 24 comes from an incorrect target sum. Choice 80 is the sum of the four known values, mistaken for the answer. Only 20 makes the mean equal 20.",
  },
  {
    id: "gre_0085", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 3,
    question: "A box contains 5 white and 3 black balls. Two balls are drawn at random without replacement. What is the probability that both balls are white?",
    options: ["5/14", "25/64", "5/28", "15/56", "1/2"],
    correct: 0,
    explanation: "P(first white) = 5/8. Given one white removed, P(second white) = 4/7. Multiply: (5/8)*(4/7) = 20/56 = 5/14, so the key is 5/14. Choice 25/64 = (5/8)^2 wrongly assumes replacement. Choice 5/28 halves the correct value. Choice 15/56 uses an incorrect numerator. Choice 1/2 is an unrelated guess. Only 5/14 accounts correctly for drawing without replacement.",
  },
  {
    id: "gre_0086", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 3,
    question: "A test has questions where the probability that a student answers any single question correctly is 0.8, independently of other questions. What is the probability that the student answers all of the first 3 questions correctly?",
    options: ["0.512", "0.24", "0.8", "0.96", "0.64"],
    correct: 0,
    explanation: "For independent events, multiply the probabilities: 0.8 * 0.8 * 0.8 = 0.512, so the key is 0.512. Choice 0.24 = 0.8 * 0.3 uses a wrong factor. Choice 0.8 is the probability for a single question only. Choice 0.96 wrongly adds probabilities toward 1. Choice 0.64 = 0.8^2 covers only two questions, not three. Only 0.512 = 0.8^3 gives all three correct.",
  },
  {
    id: "gre_0087", topicId: 0, domain: "Quantitative Reasoning", skill: "Data Analysis and Statistics", difficulty: 3,
    question: "A data set consists of the integers from 1 to 9 inclusive, each appearing exactly once. If the value 9 is replaced by the value 45, which of the following statements is true about the change from the original data set to the new data set?",
    options: ["The mean increases and the median stays the same", "The mean stays the same and the median increases", "Both the mean and the median increase", "The mean increases and the median decreases", "Both the mean and the median stay the same"],
    correct: 0,
    explanation: "Original set: 1..9, mean = 45/9 = 5, median = 5 (the 5th value). Replacing 9 with 45 raises the sum from 45 to 81, so the new mean = 81/9 = 9, which increases. The ordered new set is 1,2,3,4,5,6,7,8,45; the 5th value (median) is still 5, unchanged, because only the largest value changed and it remained the largest. So the key is 'mean increases, median stays the same.' The other choices misstate one or both effects; the median is unaffected by changing an extreme value while the mean is pulled upward. Only the first statement holds.",
  },
];

export const GRE_QUESTION_COUNT = GRE_QUESTIONS.length;

export function getGREQuestions(topicId?: number): GREQuestion[] {
  return topicId === undefined ? GRE_QUESTIONS : GRE_QUESTIONS.filter((q) => q.topicId === topicId);
}
