/**
 * LSAT Flashcard deck — covering Logical Reasoning, Reading Comprehension,
 * format/scoring facts, and exam strategy / common traps.
 *
 * Current LSAT format (post Aug 2024): 2× LR + 1× RC, NO Logic Games.
 */

export interface LSATFlashcard {
  id: number;
  front: string;
  back: string;
  domain: string;     // 'lr' | 'rc' | 'format' | 'strategy'
  domainName: string;
  category: string;   // 'definition' | 'concept' | 'comparison' | 'question' | 'tip' | 'mnemonic'
  topics: string[];   // ['LSAT']
}

export const LSAT_FLASHCARD_DOMAINS = [
  { id: 'lr', label: 'LR', name: 'Logical Reasoning', count: 60 },
  { id: 'rc', label: 'RC', name: 'Reading Comprehension', count: 30 },
  { id: 'format', label: 'Format', name: 'LSAT Format & Scoring', count: 10 },
  { id: 'strategy', label: 'Strategy', name: 'Exam Strategy & Traps', count: 10 },
] as const;

export const LSAT_FLASHCARD_CATEGORIES = ['definition','concept','comparison','question','tip','mnemonic'] as const;

export const LSAT_FLASHCARDS: LSATFlashcard[] = [
  // ============================================================
  // DOMAIN: lr (60 cards, ids 1–60)
  // ============================================================

  // --- Strengthen (5 cards) ---
  { id: 1, front: 'What does a Strengthen question ask you to do?', back: 'Identify the answer choice that, if true, would make the argument\'s conclusion MORE likely to be true. You are NOT required to prove the conclusion — you only need to add support. Look for answers that close logical gaps or rule out alternative explanations.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 2, front: 'Common Strengthen stem patterns', back: '"Which of the following, if true, most strengthens the argument?" / "...most supports the conclusion?" / "...most helps to justify the reasoning?" The phrase "if true" signals you should accept the answer as fact and test its impact on the conclusion.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 3, front: 'Strengthen trap: irrelevant comparison', back: 'A common wrong answer compares the argument\'s subject to something else in a way that doesn\'t actually bear on the conclusion. If the comparison doesn\'t affect the logical link between premises and conclusion, it doesn\'t strengthen.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 4, front: 'Strengthen by ruling out an alternative', back: 'If an argument relies on cause X explaining effect Y, an answer that eliminates an alternative cause (e.g., "Z did not occur") strengthens by removing a competing explanation. This is one of the most common correct-answer patterns.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 5, front: 'Strengthen vs. Sufficient Assumption', back: 'Strengthen merely adds support — it does NOT need to guarantee the conclusion. Sufficient Assumption must, if true, make the conclusion logically follow. Strengthen is a softer standard.', domain: 'lr', domainName: 'Logical Reasoning', category: 'comparison', topics: ['LSAT'] },

  // --- Weaken (5 cards) ---
  { id: 6, front: 'What does a Weaken question ask you to do?', back: 'Identify the answer choice that, if true, would make the argument\'s conclusion LESS likely to be true. You do not need to disprove the conclusion — only to undermine it. Attack the link between premises and conclusion.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 7, front: 'Common Weaken stem patterns', back: '"Which of the following, if true, most weakens the argument?" / "...most calls into question the conclusion?" / "...most undermines the reasoning?" Treat the answer as fact and ask: does this make the conclusion harder to believe?', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 8, front: 'Weaken trap: wrong-direction answer', back: 'Test-makers often include a tempting answer that actually STRENGTHENS the argument. After picking a Weaken answer, re-read the stem to confirm you are weakening, not strengthening.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 9, front: 'Weaken a causal argument', back: 'For arguments of the form "X caused Y": (1) propose an alternative cause for Y, (2) show Y occurred without X, (3) show X occurred without Y, or (4) reverse the causal direction (Y caused X). Any of these weakens.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 10, front: 'Weaken vs. disprove', back: 'A Weaken answer does NOT need to prove the conclusion false. Even an answer that introduces serious doubt is sufficient. Eliminate answers that demand a stronger standard than the question requires.', domain: 'lr', domainName: 'Logical Reasoning', category: 'comparison', topics: ['LSAT'] },

  // --- Necessary Assumption (5 cards) ---
  { id: 11, front: 'What is a Necessary Assumption?', back: 'A premise the argument MUST rely on for its conclusion to hold. If the assumption were false, the argument would fall apart. NA answers tend to be modestly worded and minimal — just enough to bridge the gap.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 12, front: 'Necessary Assumption stem patterns', back: '"The argument depends on assuming which of the following?" / "Which of the following is an assumption REQUIRED by the argument?" / "...the argument relies on which one of the following?" The keyword is dependency/requirement.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 13, front: 'The Negation Test for Necessary Assumption', back: 'Negate the answer choice. If the negated version DESTROYS the argument, the original is necessary. If the argument still works after negation, the answer is not required and should be eliminated. This is the gold-standard NA technique.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 14, front: 'Necessary Assumption trap: too strong', back: 'NA answers are usually weakly worded ("at least some", "is not always impossible"). Avoid answers with extreme language like "all", "never", "every" unless the argument truly requires that strength.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 15, front: 'Necessary vs. Sufficient Assumption', back: 'Necessary = the argument REQUIRES it (without it, argument fails). Sufficient = if granted, it GUARANTEES the conclusion. Necessary is weaker and minimal; Sufficient is stronger and often a conditional rule that bridges premises to conclusion.', domain: 'lr', domainName: 'Logical Reasoning', category: 'comparison', topics: ['LSAT'] },

  // --- Inference (5 cards) ---
  { id: 16, front: 'What is an Inference (Must Be True) question?', back: 'Asks what MUST be true given the stimulus. The correct answer follows necessarily from the information provided — you should be able to point to the supporting text. Stay strictly within what the stimulus says.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 17, front: 'Inference stem patterns', back: '"If the statements above are true, which of the following must also be true?" / "Which of the following is most strongly supported by the information?" / "The statements above, if true, most logically imply..."', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 18, front: 'Inference trap: too-strong language', back: 'Wrong answers often use absolute language ("must", "always", "every") that the stimulus does not support. Correct answers are usually conservatively worded ("some", "at least one", "may"). Match certainty to the text.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 19, front: 'Inference trap: outside-knowledge', back: 'Do NOT use real-world knowledge to fill gaps. Every correct inference is supported by the stimulus alone. If an answer requires assumptions not stated, eliminate it — even if it is "obviously true" in real life.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 20, front: 'Inference vs. Main Point', back: 'Inference asks what FOLLOWS from the stimulus (not necessarily the author\'s point). Main Point asks for the author\'s primary CONCLUSION. Inference stimuli are often non-argumentative; Main Point stimuli always contain a conclusion.', domain: 'lr', domainName: 'Logical Reasoning', category: 'comparison', topics: ['LSAT'] },

  // --- Flaw (5 cards) ---
  { id: 21, front: 'What is a Flaw question?', back: 'Asks you to identify the LOGICAL error in the argument — the reasoning is broken in some standard way (causal fallacy, equivocation, ad hominem, circular reasoning, etc.). The premises may be true, but the conclusion does not follow.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 22, front: 'Common LSAT flaws to memorize', back: '(1) Correlation-causation, (2) Necessary-Sufficient confusion, (3) Ad hominem, (4) Circular reasoning, (5) Equivocation, (6) Hasty generalization, (7) Appeal to authority/popularity, (8) Straw man, (9) Sampling bias, (10) Part-whole confusion.', domain: 'lr', domainName: 'Logical Reasoning', category: 'mnemonic', topics: ['LSAT'] },
  { id: 23, front: 'Flaw stem patterns', back: '"The reasoning in the argument is flawed because..." / "Which of the following most accurately describes a flaw in the reasoning?" / "The argument is vulnerable to criticism on the grounds that..."', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 24, front: 'Flaw trap: describes-something-that-didn\'t-happen', back: 'Wrong Flaw answers often describe a fallacy the argument did NOT commit. Verify the flaw is actually present in the stimulus. If the answer says the argument "ignores X" but the argument never addresses X anyway, it may not be a flaw.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 25, front: 'Necessary-Sufficient flaw', back: 'The argument treats a necessary condition as if it were sufficient (or vice versa). Example: "Studying is necessary to pass. Anna studied, so she will pass." Studying is necessary but not sufficient — Anna could still fail.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },

  // --- Principle (3 cards) ---
  { id: 26, front: 'What is a Principle question?', back: 'Asks you to connect an abstract principle (a general rule) to a specific situation. May go in either direction: (1) which principle justifies the argument? or (2) which situation conforms to / violates the stated principle?', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 27, front: 'Principle stem patterns', back: '"Which of the following principles, if valid, most helps to justify the reasoning?" / "...most conforms to the principle stated above?" / "The reasoning above most closely conforms to which of the following principles?"', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 28, front: 'Principle answer must match scope', back: 'A correct Principle answer applies to the situation in the stimulus AND matches its scope. Too broad and the principle applies to many irrelevant cases; too narrow and it fails to justify the conclusion. Aim for tight fit.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Main Point (3 cards) ---
  { id: 29, front: 'What is a Main Point question?', back: 'Asks you to identify the author\'s PRIMARY conclusion. The right answer captures the central claim — not a premise, not a subsidiary conclusion, not background context.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 30, front: 'Main Point stem patterns', back: '"Which of the following most accurately expresses the main conclusion of the argument?" / "The main point of the argument is that..." / "Which of the following best states the central idea?"', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 31, front: 'Main Point trap: a true premise', back: 'Wrong answers often paraphrase a premise rather than the conclusion. Ask: which sentence does the rest of the argument SUPPORT? That is the conclusion. Premises support; conclusions are supported.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Role (3 cards) ---
  { id: 32, front: 'What is a Role / Function question?', back: 'Asks you to describe the role a particular statement (often bolded) plays in the argument. Roles include: main conclusion, subsidiary conclusion, premise, background, opposing view cited and rejected, evidence supporting a sub-claim.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 33, front: 'Role stem patterns', back: '"The claim that X plays which of the following roles in the argument?" / "The portion in boldface serves which of the following functions?" / "...figures in the argument in which one of the following ways?"', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 34, front: 'Role tip: map premises and conclusions first', back: 'Before reading answer choices, decide whether the bolded statement is a premise, sub-conclusion, main conclusion, or opposing view. Then match your label to the answer choices. This prevents getting trapped by verbose wrong choices.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Resolve Paradox (3 cards) ---
  { id: 35, front: 'What is a Resolve the Paradox question?', back: 'The stimulus presents two facts that seem contradictory or surprising. The correct answer provides information that makes BOTH facts true simultaneously — explaining the apparent tension without denying either side.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 36, front: 'Resolve Paradox stem patterns', back: '"Which of the following, if true, most helps to resolve the apparent paradox?" / "...most helps to explain the discrepancy?" / "...best reconciles the two findings?"', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 37, front: 'Resolve Paradox trap: deepens the paradox', back: 'Wrong answers often make the contradiction worse instead of resolving it. After picking, re-check: does this answer let BOTH stated facts be true at once? If not, eliminate.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Method (3 cards) ---
  { id: 38, front: 'What is a Method of Reasoning question?', back: 'Asks you to describe HOW the argument proceeds — the technique or rhetorical strategy used. Examples: analogy, generalization from cases, eliminating alternatives, appeal to a principle, counterexample.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 39, front: 'Method stem patterns', back: '"The argument proceeds by..." / "Which of the following most accurately describes the method used in the argument?" / "The argument supports its conclusion by..."', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 40, front: 'Method tip: match abstraction level', back: 'Method answers are usually written abstractly ("draws an analogy", "cites an authority"). Identify the technique in your own words first, then match. Beware of answers that describe a method the argument did not actually use.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Sufficient Assumption (3 cards) ---
  { id: 41, front: 'What is a Sufficient Assumption?', back: 'An assumption that, if added to the premises, GUARANTEES the conclusion follows. Often takes the form of a conditional rule that bridges the premises to the conclusion. Stronger than Necessary Assumption.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 42, front: 'Sufficient Assumption stem patterns', back: '"Which of the following, if assumed, would allow the conclusion to be properly drawn?" / "The conclusion follows logically if which of the following is assumed?" / "Which assumption justifies the inference?"', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 43, front: 'Sufficient Assumption: connect new terms', back: 'Identify the term that appears in the conclusion but NOT in the premises (or vice versa). The correct SA usually contains a conditional linking that orphan term to existing premises, completing the chain to the conclusion.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Parallel Reasoning (2 cards) ---
  { id: 44, front: 'What is a Parallel Reasoning question?', back: 'Asks which answer choice has the same LOGICAL STRUCTURE as the stimulus argument. Match abstract form, not subject matter. The conclusion type, premise type, and inference pattern should align.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 45, front: 'Parallel: match structural features', back: 'Check: (1) conclusion certainty (must/might/probably), (2) conditional vs. causal logic, (3) number and type of premises, (4) presence of counter-evidence. Identical surface topic is irrelevant; identical structure is everything.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Parallel Flaw (2 cards) ---
  { id: 46, front: 'What is a Parallel Flaw question?', back: 'Asks which answer has the same FLAWED logical structure as the stimulus. First identify the specific flaw in the stimulus, then find the answer that commits the SAME flaw — not just any flaw.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 47, front: 'Parallel Flaw: name the flaw first', back: 'Before scanning answers, label the stimulus flaw (e.g., "necessary-sufficient confusion", "correlation-causation"). Then eliminate answers that contain different flaws or no flaw at all.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Point at Issue (2 cards) ---
  { id: 48, front: 'What is a Point at Issue question?', back: 'Two speakers offer opposing views. The correct answer is a statement that one speaker would AGREE with and the other would DISAGREE with — and both views must be supported by what each speaker actually said.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 49, front: 'Point at Issue: the agree/disagree test', back: 'For each answer choice, ask: would speaker 1 agree? Would speaker 2 agree? The correct answer produces opposite responses (yes/no) — and BOTH responses must be supported by the stimuli. If a speaker is silent, that doesn\'t count.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Argument Evaluation (2 cards) ---
  { id: 50, front: 'What is an Argument Evaluation question?', back: 'Asks which piece of information would help DETERMINE whether the argument is good — i.e., answering a question one way would strengthen, and the opposite answer would weaken. The right answer probes the argument\'s key dependency.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 51, front: 'Evaluation stem patterns', back: '"Which of the following would be most useful to know in evaluating the argument?" / "The answer to which question would most help in assessing the argument?" Pair test: knowing the answer should pull the argument in opposite directions.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },

  // --- Complete the Argument (2 cards) ---
  { id: 52, front: 'What is a Complete the Argument question?', back: 'The stimulus ends with "Therefore..." or a blank. The correct answer fills in the missing piece (usually the conclusion or a key premise) that follows naturally from what came before.', domain: 'lr', domainName: 'Logical Reasoning', category: 'definition', topics: ['LSAT'] },
  { id: 53, front: 'Complete: anticipate before reading answers', back: 'Predict the missing piece BEFORE reading choices. The correct answer should feel like the obvious next sentence — supported by the premises and matching the stimulus\'s scope and tone.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // --- Necessary/Sufficient logic (2 cards) ---
  { id: 54, front: 'Necessary vs. Sufficient condition', back: 'Sufficient: if X happens, Y must happen (X → Y). Necessary: Y cannot happen without X (¬X → ¬Y, or equivalently Y → X). On the LSAT, look for indicator words: "if", "when", "all" signal sufficient; "only if", "requires", "must" signal necessary.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 55, front: 'The contrapositive', back: 'For any conditional "If A, then B" (A → B), the logically equivalent contrapositive is "If not B, then not A" (¬B → ¬A). Negate AND switch. The contrapositive is always true when the original is. The converse (B → A) and inverse (¬A → ¬B) are NOT equivalent.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },

  // --- General LR strategy (5 cards) ---
  { id: 56, front: 'Identify the conclusion first', back: 'Before analyzing answer choices, locate the conclusion. Use indicator words ("therefore", "thus", "hence", "so", "it follows that") and the "Why test" — the premises explain WHY the conclusion is true. Mismapping premise vs. conclusion sinks LR.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },
  { id: 57, front: 'Premise indicator words', back: '"Because", "since", "for", "given that", "as", "due to", "in light of" all introduce premises. When you see them, the next clause is offered as SUPPORT for some other claim (the conclusion).', domain: 'lr', domainName: 'Logical Reasoning', category: 'mnemonic', topics: ['LSAT'] },
  { id: 58, front: 'Conclusion indicator words', back: '"Therefore", "thus", "hence", "so", "consequently", "it follows that", "we may conclude", "clearly" typically introduce conclusions. Note: "clearly" and "obviously" are sometimes used by the author to mark the main point.', domain: 'lr', domainName: 'Logical Reasoning', category: 'mnemonic', topics: ['LSAT'] },
  { id: 59, front: 'Translate common formal-logic phrases', back: '"All A are B" → A → B. "No A are B" → A → ¬B. "Only B are A" → A → B (only flips direction). "A unless B" → ¬B → A (or equivalently ¬A → B). "A only if B" → A → B. Translate before solving conditional puzzles.', domain: 'lr', domainName: 'Logical Reasoning', category: 'concept', topics: ['LSAT'] },
  { id: 60, front: 'Pre-phrasing the answer', back: 'After reading the stimulus and stem but BEFORE looking at answer choices, predict the correct answer in your own words. This anchors your evaluation and makes you less susceptible to seductive wrong answers.', domain: 'lr', domainName: 'Logical Reasoning', category: 'tip', topics: ['LSAT'] },

  // ============================================================
  // DOMAIN: rc (30 cards, ids 61–90)
  // ============================================================

  // --- Specific Detail (4 cards) ---
  { id: 61, front: 'What is an RC Specific Reference / Detail question?', back: 'Asks what the passage explicitly said about a particular topic. The answer is supported by a specific line or paragraph you can point to. These are typically the most common RC question type.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 62, front: 'Detail stem patterns', back: '"According to the passage..." / "The passage states that..." / "The author indicates that..." These signal you should return to the passage and find the textual support before evaluating answers.', domain: 'rc', domainName: 'Reading Comprehension', category: 'concept', topics: ['LSAT'] },
  { id: 63, front: 'Detail trap: half-right, half-wrong', back: 'A common wrong answer mixes accurate language from the passage with a small inaccuracy. Read every word — a single misattribution, scope shift, or extra qualifier can make a tempting answer wrong.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },
  { id: 64, front: 'Detail tip: prove with a citation', back: 'For every Detail answer, locate the exact sentence in the passage that supports it. If you cannot point to specific text, you are likely inferring beyond what is stated. Detail answers must be DIRECTLY supported.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- Inference (4 cards) ---
  { id: 65, front: 'What is an RC Inference question?', back: 'Asks what can be reasonably concluded from the passage, even if not explicitly stated. The answer must be strongly supported by the text — stay close to the passage and avoid leaps.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 66, front: 'RC Inference stem patterns', back: '"The passage suggests that..." / "It can be inferred from the passage that..." / "The author would most likely agree that..." / "The passage implies that..."', domain: 'rc', domainName: 'Reading Comprehension', category: 'concept', topics: ['LSAT'] },
  { id: 67, front: 'RC Inference trap: too-strong language', back: 'Wrong inferences often use extreme language ("must", "always", "never") that the passage does not support. Correct RC inferences usually use cautious wording ("suggests", "could", "is consistent with").', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },
  { id: 68, front: 'RC Inference trap: outside knowledge', back: 'Even if an answer is true in the real world, eliminate it unless the passage supports it. RC inferences come strictly from the text, not from your own knowledge or assumptions about the topic.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- Function / Purpose (4 cards) ---
  { id: 69, front: 'What is an RC Function / Purpose question?', back: 'Asks WHY the author included a particular detail, example, paragraph, or quote. The answer should describe the rhetorical role it plays — supporting a claim, providing contrast, illustrating a point, qualifying a prior assertion.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 70, front: 'Function stem patterns', back: '"The author mentions X primarily in order to..." / "The function of the second paragraph is to..." / "The reference to X serves to..." / "The example of Y is included to..."', domain: 'rc', domainName: 'Reading Comprehension', category: 'concept', topics: ['LSAT'] },
  { id: 71, front: 'Function tip: zoom out to surrounding context', back: 'To answer a Function question, look at the sentences immediately before and after the referenced text. The function is almost always explained by the surrounding context — what was the author trying to argue, illustrate, or refute?', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },
  { id: 72, front: 'Function trap: describes content, not purpose', back: 'A common wrong answer accurately summarizes WHAT a detail says rather than WHY it was mentioned. The right answer describes the rhetorical purpose, not the substance.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- Main Point (3 cards) ---
  { id: 73, front: 'What is an RC Main Point question?', back: 'Asks for the central claim of the entire passage. The answer should capture the passage\'s overall argument or thesis — not just one section, not a minor detail, and not an opposing view that was discussed.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 74, front: 'Main Point stem patterns (RC)', back: '"Which of the following most accurately expresses the main point of the passage?" / "The primary purpose of the passage is to..." / "The central idea of the passage is that..."', domain: 'rc', domainName: 'Reading Comprehension', category: 'concept', topics: ['LSAT'] },
  { id: 75, front: 'Main Point: must cover full scope', back: 'A correct Main Point answer accounts for ALL parts of the passage — including any counterarguments or qualifications. Answers too narrow (covering only one paragraph) or too broad (covering more than the passage) are wrong.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- Comparative Passage (3 cards) ---
  { id: 76, front: 'What is a Comparative Passage question?', back: 'Each LSAT RC section includes one pair of shorter passages (Passage A and Passage B) on a related topic. Questions ask about each passage individually or about their relationship — agreement, disagreement, scope difference.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 77, front: 'Comparative strategy: relate the passages', back: 'After reading both passages, articulate the relationship in one sentence: Do they agree on a thesis? Disagree on a key point? Discuss the same topic from different scopes (general vs. specific)? Most questions hinge on this relationship.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },
  { id: 78, front: 'Comparative trap: extends one passage to the other', back: 'Wrong answers often assume Passage A\'s author would endorse a claim made in Passage B (or vice versa) without textual support. Only attribute views to an author when that author actually stated something supporting the view.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- Structure (3 cards) ---
  { id: 79, front: 'What is an RC Structure question?', back: 'Asks how the passage is organized — its rhetorical pattern. Examples: problem-solution, compare-contrast, chronological narrative, claim-objection-response, general-to-specific, or theory-then-evidence.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 80, front: 'Structure stem patterns', back: '"Which of the following best describes the organization of the passage?" / "The passage proceeds primarily by..." / "Which of the following best represents the structure of the passage as a whole?"', domain: 'rc', domainName: 'Reading Comprehension', category: 'concept', topics: ['LSAT'] },
  { id: 81, front: 'Structure tip: outline paragraph functions', back: 'During your initial read, jot one or two words per paragraph describing its function (intro, evidence, counterargument, conclusion). This map makes Structure questions answerable in seconds and aids every other RC question type.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- Application (3 cards) ---
  { id: 82, front: 'What is an RC Application question?', back: 'Asks you to apply the passage\'s reasoning or principles to a new scenario not discussed in the passage. Functions like an LR Principle question — match the underlying logic to a fresh case.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 83, front: 'Application stem patterns', back: '"Which of the following situations is most analogous to..." / "The author would most likely consider which of the following an example of..." / "Based on the passage, which scenario best illustrates..."', domain: 'rc', domainName: 'Reading Comprehension', category: 'concept', topics: ['LSAT'] },
  { id: 84, front: 'Application: extract the principle', back: 'Before reading answers, abstract the passage\'s principle in your own words (e.g., "innovation emerges from constraint, not freedom"). Then test each scenario against that abstract rule. Surface similarity in topic is a trap.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- Attitude (3 cards) ---
  { id: 85, front: 'What is an RC Attitude / Tone question?', back: 'Asks how the author feels about the topic, a specific claim, or a referenced person/theory. Options span supportive, skeptical, ambivalent, critical, neutral, enthusiastic — and gradations in between.', domain: 'rc', domainName: 'Reading Comprehension', category: 'definition', topics: ['LSAT'] },
  { id: 86, front: 'Attitude stem patterns', back: '"The author\'s attitude toward X can best be described as..." / "Which of the following best describes the author\'s view of..." / "The tone of the passage is best characterized as..."', domain: 'rc', domainName: 'Reading Comprehension', category: 'concept', topics: ['LSAT'] },
  { id: 87, front: 'Attitude tip: match degree, not just direction', back: 'LSAT authors rarely take extreme positions. Eliminate answers with extreme tone words ("contemptuous", "unequivocally enthusiastic") unless the passage clearly supports them. Look for mid-strength language ("cautious", "qualified", "measured").', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // --- General RC strategy (3 cards) ---
  { id: 88, front: 'RC skimming strategy: structure over detail', back: 'Read for structure on first pass — who is making what claim, what are the main supporting reasons, where is the author\'s voice? Do NOT try to memorize details; you can return to the passage for them. Save time for the questions.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },
  { id: 89, front: 'RC structural note-taking', back: 'Annotate as you read: circle conclusion-indicator words, mark contrast pivots ("however", "yet", "although"), bracket lists, and write one-word summaries next to each paragraph. This investment pays back across 5–8 questions per passage.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },
  { id: 90, front: 'RC question order: easier questions first', back: 'Main Point, Attitude, and Structure questions are often the fastest because they leverage your structural map. Specific Detail questions take longer because they require returning to the text. Consider tackling the global questions first within each passage.', domain: 'rc', domainName: 'Reading Comprehension', category: 'tip', topics: ['LSAT'] },

  // ============================================================
  // DOMAIN: format (10 cards, ids 91–100)
  // ============================================================

  { id: 91, front: 'Current LSAT section structure (post Aug 2024)', back: 'The scored LSAT has 3 sections: 2× Logical Reasoning (≈25 Qs each) + 1× Reading Comprehension (≈27 Qs, 4 passages). Plus 1 unscored experimental section that looks identical to either LR or RC. Total ≈75 scored questions.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 92, front: 'What can the experimental section be?', back: 'The unscored experimental section is either another LR or another RC section. You will NOT know which section is experimental during the test, so you must give your best effort on all four sections. Logic Games are no longer used (even as experimental).', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 93, front: 'LSAT scoring scale', back: 'Scored LSAT results report on a 120–180 scale (180 is perfect). The raw score (number of correct answers out of ≈75) is converted to the scaled score via a test-specific conversion table. There is NO penalty for wrong answers — always guess.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 94, front: 'Approximate raw-to-scaled conversion', back: 'Rough benchmarks: ≈99 raw correct (impossible — max is ~75) but ~75/75 → 180; ~65–67 → 170; ~55 → 160; ~44 → 150; ~33 → 140. Conversions shift slightly by test form. Missing ~10 questions still yields a competitive 170+ score.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 95, front: 'LSAT timing per section', back: 'Each section is 35 minutes. With ≈25 LR Qs per section, that is ≈84 seconds per LR question. With ≈27 RC Qs across 4 passages, that is ≈78 seconds per RC question (including passage reading time of ~3–4 minutes per passage).', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 96, front: 'LSAT Argumentative Writing', back: 'A separate, unproctored take-at-home component (administered via LSAC\'s LSAT Writing platform). It is NOT scored on the 120–180 scale — instead, your essay is sent to law schools as part of your application file. You must complete one Writing sample to receive a score report.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 97, front: 'LSAT retake rules', back: 'LSAC limits retakes to: 3 times in a single testing year (June–May), 5 times within the current and 5 past testing years, and 7 times total in a lifetime. Scoring 180 used to trigger a retake ban; the current rule restricts based on these counts.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 98, front: 'Logic Games removal', back: 'The Analytical Reasoning section (commonly called Logic Games) was officially removed from the LSAT in August 2024 following a settlement with disability-rights advocates. The current LSAT contains NO Logic Games — only LR and RC.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },
  { id: 99, front: 'LawHub: the official LSAT QBank', back: 'LawHub (lawhub.lsac.org) is LSAC\'s official PrepTest platform. Free tier gives access to a handful of sample PrepTests; LawHub Advantage (paid subscription) unlocks the full library of disclosed PrepTests under realistic digital-test conditions.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'definition', topics: ['LSAT'] },
  { id: 100, front: 'LSAT score release timeline', back: 'Scores are typically released about 2–3 weeks after the test date (varies slightly by administration). You receive an email when your score is available in your LSAC account. Score Preview lets first-time test-takers see a score before deciding whether to keep or cancel it.', domain: 'format', domainName: 'LSAT Format & Scoring', category: 'concept', topics: ['LSAT'] },

  // ============================================================
  // DOMAIN: strategy (10 cards, ids 101–110)
  // ============================================================

  { id: 101, front: 'Out-of-scope answer trap', back: 'Wrong answers often introduce a concept, comparison, or claim never mentioned in the stimulus or passage. If an answer requires you to bring in new information to make it work, it is likely out of scope — eliminate it.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 102, front: 'Wrong-direction trap (Strengthen / Weaken)', back: 'On Strengthen and Weaken questions, test-makers always include a tempting answer that does the OPPOSITE — strengthens when you want to weaken, or vice versa. Before confirming an answer, re-read the stem and re-check direction.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 103, front: 'Too-strong language in Inference answers', back: 'Inference answers using "must", "always", "never", "all", or "no" are usually wrong unless the stimulus uses equally strong language. Correct inferences typically use measured wording: "some", "at least one", "may", "is consistent with".', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 104, front: 'Half-right, half-wrong answers', back: 'A frequent trap pairs accurate language from the stimulus with a small inaccuracy — a swapped subject, a missing qualifier, a flipped direction. Read EVERY word of long answer choices; one wrong word eliminates the entire answer.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 105, front: 'Skipping vs. educated guessing', back: 'There is NO penalty for wrong answers on the LSAT. Never leave a question blank. If time is running out, eliminate what you can and guess on the rest. A single eliminated wrong answer roughly doubles your odds of guessing correctly.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 106, front: 'Time management: pacing benchmarks', back: 'LR: aim for ~85 seconds per question on average (35 min ÷ ~25 Qs). RC: aim for ~3–4 min reading each passage and ~1:20 per question. If you exceed a benchmark on a tough question, flag it and move on — return at the end.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 107, front: 'Skip and return strategy', back: 'If a question stumps you for more than ~30 seconds beyond average, mark it and move on. You will likely find easier questions later, banking time. Return to the marked question with a fresh mindset — and always bubble a guess in case you run out of time.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 108, front: 'Read the stem first or last?', back: 'In LR, read the question STEM first. Knowing whether you are facing a Strengthen, Weaken, Flaw, or Inference question shapes how you read the stimulus and what you look for. Reading stem-first is a small habit that adds up to several points.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 109, front: 'Identify the conclusion before evaluating answers', back: 'For any argument-based LR question, your first job is to identify the conclusion and the premises that support it. If you misidentify the conclusion, every subsequent step (strengthen, weaken, flaw, assumption) is built on sand.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
  { id: 110, front: 'The negation test for Necessary Assumption', back: 'For each NA answer choice, negate it. If the negated version DESTROYS the argument, the original is required (correct). If the argument survives the negation, the choice is not necessary (eliminate). This is the single most reliable LR technique.', domain: 'strategy', domainName: 'Exam Strategy & Traps', category: 'tip', topics: ['LSAT'] },
];
