/**
 * MPEP chapter list (9th ed.) + eMPEP URL helpers — Patent Bar practice browser.
 * Official eMPEP: https://mpep.uspto.gov/RDMS/MPEP/current
 */

export const MPEP_CHAPTER_LIST = [
  { num: '100', title: 'Secrecy, Access, National Security, and Foreign Filing' },
  { num: '200', title: 'Types and Status of Application; Naming of Inventor' },
  { num: '300', title: 'Ownership and Assignment' },
  { num: '400', title: 'Representative of Inventor or Owner' },
  { num: '500', title: 'Receipt and Handling of Mail and Papers' },
  { num: '600', title: 'Parts, Form, and Content of Application' },
  { num: '700', title: 'Examination of Applications' },
  { num: '800', title: 'Restriction in Applications Filed Under 35 U.S.C. 111; Double Patenting' },
  { num: '900', title: 'Prior Art, Classification, and Search' },
  { num: '1000', title: 'Matters Decided by Various U.S. Patent and Trademark Office Officials' },
  { num: '1100', title: 'Statutory Invention Registration (Rescinded) and Pre-Grant Publication' },
  { num: '1200', title: 'Appeal' },
  { num: '1300', title: 'Allowance and Issue' },
  { num: '1400', title: 'Correction of Patents' },
  { num: '1500', title: 'Design Patents' },
  { num: '1600', title: 'Plant Patents' },
  { num: '1700', title: 'Miscellaneous' },
  { num: '1800', title: 'Patent Cooperation Treaty' },
  { num: '1900', title: 'Protest' },
  { num: '2000', title: 'Duty of Disclosure, Candor, and Good Faith' },
  { num: '2100', title: 'Patentability' },
  { num: '2200', title: 'Citation of Prior Art and Ex Parte Reexamination' },
  { num: '2300', title: 'Inter Partes Reexamination' },
  { num: '2400', title: 'Biotechnology' },
  { num: '2500', title: 'Maintenance Fees' },
  { num: '2600', title: 'Optional Inter Partes Reexamination' },
  { num: '2700', title: 'Patent Terms and Extensions' },
  { num: '2800', title: 'Supplemental Examination' },
  { num: '2900', title: 'International Design Applications' },
] as const;

// USPTO portals:
//   1. The SPA reader (PRIMARY): https://mpep.uspto.gov/RDMS/MPEP/current
//      The official eMPEP. The actual Patent Bar exam uses this app.
//   2. The static HTML mirror:  https://www.uspto.gov/web/offices/pac/mpep/
//      Fallback for chapters the SPA can't deep-link to.
//
// IMPORTANT — Why the URL pattern is d0e####, not chXXX:
// The SPA's internal routing uses anchors of the form `#/current/d0e####.html`
// (where d0e#### is a stable section identifier). The intuitive-looking
// `#/current/ch700.html` is NOT a real route — the SPA spins forever waiting
// for a document that doesn't exist in its index, which is the "loads
// continuously" symptom users reported.
//
// We pre-computed the first-section d0e id for every chapter by scraping the
// static MPEP mirror (each section page links to its eMPEP d0e anchor). For
// chapters 2800/2900 (newer additions to the MPEP that don't yet have d0e
// anchors in the static mirror) we fall back to the static URL.
const EMPEP_STATIC_BASE = 'https://www.uspto.gov/web/offices/pac/mpep';
const EMPEP_SPA_BASE = 'https://mpep.uspto.gov/RDMS/MPEP/current';

/**
 * Chapter → first-section d0e id mapping. Generated by fetching each chapter's
 * static-mirror page and picking the first d0e####. These are the anchors the
 * SPA actually understands; opening one navigates the eMPEP directly to that
 * chapter's opening section.
 *
 * Empty value (currently 2800, 2900) means the SPA doesn't have a d0e anchor
 * for that chapter and we fall back to the static mirror in eMpepChapterUrl().
 */
const CHAPTER_TO_D0E: Record<string, string> = {
  '100':  'd0e2719',
  '200':  'd0e4514',
  '300':  'd0e17906',
  '400':  'd0e20984',
  '500':  'd0e25755',
  '600':  'd0e34922',
  '700':  'd0e55492',
  '800':  'd0e97928',
  '900':  'd0e110030',
  '1000': 'd0e116260',
  '1100': 'd0e121728',
  '1200': 'd0e122849',
  '1300': 'd0e131475',
  '1400': 'd0e135563',
  '1500': 'd0e150263',
  '1600': 'd0e161286',
  '1700': 'd0e162459',
  '1800': 'd0e163756',
  '1900': 'd0e193937',
  '2000': 'd0e195426',
  '2100': 'd0e198682',
  '2200': 'd0e222159',
  '2300': 'd0e237669',
  '2400': 'd0e240728',
  '2500': 'd0e247910',
  '2600': 'd0e249828',
  '2700': 'd0e276883',
  '2800': '', // no d0e anchor — falls back to static mirror
  '2900': '', // no d0e anchor — falls back to static mirror
};

/**
 * Open this chapter in the official eMPEP SPA. The link resolves to the
 * chapter's opening section using the correct d0e#### anchor; users land on
 * the right page in seconds instead of staring at "Loading..." forever.
 *
 *   Input  '700'  → .../#/current/d0e55492.html
 *   Input  '2100' → .../#/current/d0e198682.html
 *   Input  '2800' → falls back to static mirror (no d0e anchor exists)
 *   Input  ''     → index
 */
export function eMpepChapterUrl(chapterNum: string): string {
  const digits = chapterNum.replace(/\D/g, '');
  if (!digits) return eMpepIndexUrl();
  const d0e = CHAPTER_TO_D0E[digits];
  if (d0e) return `${EMPEP_SPA_BASE}#/current/${d0e}.html`;
  // No d0e mapping for this chapter — use the static mirror, which always works.
  return `${EMPEP_STATIC_BASE}/mpep-${digits.padStart(4, '0')}.html`;
}

/**
 * Official eMPEP SPA URL for a deep section anchor.
 * The MPEP SPA assigns each numbered section a `d0e####` id (e.g. the
 * URL ../#/current/d0e34301.html jumps directly to one specific subsection).
 * Pass the bare id ("d0e34301") or the full ".html" form; both work.
 */
export function eMpepSectionUrl(anchor: string): string {
  const a = anchor.replace(/\.html$/i, '').trim();
  if (!a) return eMpepIndexUrl();
  return `${EMPEP_SPA_BASE}#/current/${a}.html`;
}

/** eMPEP SPA index. */
export function eMpepIndexUrl(): string {
  return `${EMPEP_SPA_BASE}#/current/index.html`;
}

/** Static HTML mirror URL — fast fallback when the SPA is slow or unavailable. */
export function eMpepStaticChapterUrl(chapterNum: string): string {
  const digits = chapterNum.replace(/\D/g, '');
  if (!digits) return `${EMPEP_STATIC_BASE}/mpep.html`;
  return `${EMPEP_STATIC_BASE}/mpep-${digits.padStart(4, '0')}.html`;
}

/** Full-text search on the eMPEP SPA (search exists only on the SPA portal). */
export function eMpepSearchUrl(query: string): string {
  const q = encodeURIComponent(query.trim());
  return `${EMPEP_SPA_BASE}#/search?q=${q}`;
}
