/**
 * NCLEX-RN (2026 test plan) — Question Bank, part 1 of 2.
 *
 * PROVENANCE — two tiers, honestly labeled:
 *
 *  - `calc-verified` (the dosage-calculation items): every answer key was
 *    COMPUTED, not typed. The items were generated by a Python script
 *    (authoring path) whose arithmetic is re-checked by
 *    `lib/__tests__/nclex-dosage-verify.test.ts` (an independently written
 *    TypeScript path) from the raw parameters in each item's `calc` block.
 *    The two computations must agree exactly, the keyed option must parse to
 *    the expected value, and no distractor may equal it. This is the same
 *    dual-path discipline AXIOM uses for its math templates.
 *
 *  - `unverified` (the clinical items): AI-authored against mainstream
 *    nursing references, pending subject-matter-expert review — the same
 *    tier and badge as the Patent Bar authored bank. NCSBN releases no
 *    official NCLEX items, so unlike the Patent Bar there is no
 *    public-domain official tier to import; everything clinical is original
 *    and labeled accordingly.
 *
 * Categories follow the 8 Client Needs of the 2026 test plan (effective
 * 2026-04-01, frozen through 2029-03-31). topicId map:
 *   0 mgmt_of_care · 1 safety_infection · 2 health_promotion ·
 *   3 psychosocial · 4 basic_care · 5 pharm_parenteral ·
 *   6 reduction_risk · 7 physio_adaptation
 *
 * Part 2 (`nclex-qbank-clinical2-data.ts`) carries Basic Care & Comfort,
 * Pharmacology (non-calculation), Reduction of Risk, and Physiological
 * Adaptation — the same split-by-tranche pattern the Patent Bar bank uses.
 */

export interface NclexCalcSpec {
  kind:
    | 'tablets'
    | 'liquid-volume'
    | 'dose-by-weight'
    | 'iv-rate-mlhr'
    | 'iv-drip-gtt'
    | 'unit-conversion'
    | 'reconstitution'
    | 'pediatric-safe-dose'
    | 'infusion-time'
    | 'iv-dose-mlhr';
  /** The raw clinical parameters the stem states in prose. */
  params: Record<string, number>;
  /** The exact numeric answer keyed in options[correct]. */
  expected: number;
  unit: string;
  /** Decimal places used when formatting the keyed option. */
  round: number;
}

export interface NclexQuestion {
  id: string;
  topicId: number;
  subtopic: string;
  difficulty: number; // 1-3
  question: string;
  options: string[];
  correct?: number; // single-answer MCQ
  type?: 'mcq' | 'multi'; // 'multi' = select-all-that-apply (SATA)
  correctAnswers?: number[]; // SATA: the set of correct option indices
  explanation: string;
  /** 'calc-verified' = dual-path computed key; 'unverified' = pending SME. */
  verification: 'calc-verified' | 'unverified';
  calc?: NclexCalcSpec;
}

const TOPIC_ID_MAP: Record<number, string> = {
  0: 'mgmt_of_care',
  1: 'safety_infection',
  2: 'health_promotion',
  3: 'psychosocial',
  4: 'basic_care',
  5: 'pharm_parenteral',
  6: 'reduction_risk',
  7: 'physio_adaptation',
};

export function getNclexTopicSectionId(numericId: number): string {
  return TOPIC_ID_MAP[numericId] || 'mgmt_of_care';
}

export function getNclexVerification(q: NclexQuestion): 'calc-verified' | 'unverified' {
  return q.verification;
}

// ─────────────────────────────────────────────────────────────────
// DOSAGE CALCULATION — generated, keys computed, dual-path verified
// (see file header). Do not hand-edit values: regenerate instead.
// ─────────────────────────────────────────────────────────────────
export const NCLEX_DOSAGE_QUESTIONS: NclexQuestion[] = [
  {"id": "nx_dose_001", "topicId": 5, "subtopic": "Tablets & capsules", "difficulty": 1, "question": "A client is prescribed levothyroxine 0.075 mg PO daily. The pharmacy supplies 0.025 mg tablets. How many tablets should the nurse administer per dose?", "options": ["6 tablet(s)", "1.5 tablet(s)", "4 tablet(s)", "3 tablet(s)"], "correct": 3, "explanation": "Desired over have: 0.075 mg ÷ 0.025 mg/tablet = 3 tablets. Always confirm the ordered dose and the supplied strength are in the same unit before dividing.", "verification": "calc-verified", "calc": {"kind": "tablets", "params": {"ordered_mg": 0.075, "strength_mg": 0.025}, "expected": 3.0, "unit": "tablet(s)", "round": 1}},
  {"id": "nx_dose_002", "topicId": 5, "subtopic": "Tablets & capsules", "difficulty": 1, "question": "A client is prescribed metoprolol 75 mg PO twice daily. The pharmacy supplies 50 mg tablets. How many tablets should the nurse administer per dose?", "options": ["3 tablet(s)", "1.5 tablet(s)", "0.8 tablet(s)", "2.5 tablet(s)"], "correct": 1, "explanation": "Desired over have: 75 mg ÷ 50 mg/tablet = 1.5 tablets. Always confirm the ordered dose and the supplied strength are in the same unit before dividing.", "verification": "calc-verified", "calc": {"kind": "tablets", "params": {"ordered_mg": 75, "strength_mg": 50}, "expected": 1.5, "unit": "tablet(s)", "round": 1}},
  {"id": "nx_dose_003", "topicId": 5, "subtopic": "Tablets & capsules", "difficulty": 1, "question": "A client is prescribed warfarin 7.5 mg PO daily. The pharmacy supplies 5 mg tablets. How many tablets should the nurse administer per dose?", "options": ["3 tablet(s)", "0.8 tablet(s)", "1.5 tablet(s)", "2.5 tablet(s)"], "correct": 2, "explanation": "Desired over have: 7.5 mg ÷ 5 mg/tablet = 1.5 tablets. Always confirm the ordered dose and the supplied strength are in the same unit before dividing.", "verification": "calc-verified", "calc": {"kind": "tablets", "params": {"ordered_mg": 7.5, "strength_mg": 5}, "expected": 1.5, "unit": "tablet(s)", "round": 1}},
  {"id": "nx_dose_004", "topicId": 5, "subtopic": "Tablets & capsules", "difficulty": 1, "question": "A client is prescribed prednisone 60 mg PO daily. The pharmacy supplies 20 mg tablets. How many tablets should the nurse administer per dose?", "options": ["6 tablet(s)", "1.5 tablet(s)", "4 tablet(s)", "3 tablet(s)"], "correct": 3, "explanation": "Desired over have: 60 mg ÷ 20 mg/tablet = 3 tablets. Always confirm the ordered dose and the supplied strength are in the same unit before dividing.", "verification": "calc-verified", "calc": {"kind": "tablets", "params": {"ordered_mg": 60, "strength_mg": 20}, "expected": 3.0, "unit": "tablet(s)", "round": 1}},
  {"id": "nx_dose_005", "topicId": 5, "subtopic": "Tablets & capsules", "difficulty": 1, "question": "A client is prescribed digoxin 0.25 mg PO daily. The pharmacy supplies 0.125 mg tablets. How many tablets should the nurse administer per dose?", "options": ["2 tablet(s)", "4 tablet(s)", "1 tablet(s)", "3 tablet(s)"], "correct": 0, "explanation": "Desired over have: 0.25 mg ÷ 0.125 mg/tablet = 2 tablets. Always confirm the ordered dose and the supplied strength are in the same unit before dividing.", "verification": "calc-verified", "calc": {"kind": "tablets", "params": {"ordered_mg": 0.25, "strength_mg": 0.125}, "expected": 2.0, "unit": "tablet(s)", "round": 1}},
  {"id": "nx_dose_006", "topicId": 5, "subtopic": "Oral liquids", "difficulty": 1, "question": "A client is prescribed amoxicillin suspension 375 mg PO. The label reads 250 mg per 5 mL. How many milliliters should the nurse administer?", "options": ["1.5 mL", "7.5 mL", "15 mL", "3.8 mL"], "correct": 1, "explanation": "Desired ÷ have × volume: (375 ÷ 250) × 5 mL = 7.5 mL. The commonest error is dropping the 'per volume' term and reporting the bare ratio.", "verification": "calc-verified", "calc": {"kind": "liquid-volume", "params": {"ordered_mg": 375, "conc_mg": 250, "conc_ml": 5}, "expected": 7.5, "unit": "mL", "round": 1}},
  {"id": "nx_dose_007", "topicId": 5, "subtopic": "Oral liquids", "difficulty": 1, "question": "A client is prescribed acetaminophen elixir 480 mg PO. The label reads 160 mg per 5 mL. How many milliliters should the nurse administer?", "options": ["15 mL", "3 mL", "30 mL", "7.5 mL"], "correct": 0, "explanation": "Desired ÷ have × volume: (480 ÷ 160) × 5 mL = 15 mL. The commonest error is dropping the 'per volume' term and reporting the bare ratio.", "verification": "calc-verified", "calc": {"kind": "liquid-volume", "params": {"ordered_mg": 480, "conc_mg": 160, "conc_ml": 5}, "expected": 15.0, "unit": "mL", "round": 1}},
  {"id": "nx_dose_008", "topicId": 5, "subtopic": "Oral liquids", "difficulty": 1, "question": "A client is prescribed furosemide oral solution 30 mg PO. The label reads 10 mg per 1 mL. How many milliliters should the nurse administer?", "options": ["3 mL", "6 mL", "1.5 mL", "5.5 mL"], "correct": 0, "explanation": "Desired ÷ have × volume: (30 ÷ 10) × 1 mL = 3 mL. The commonest error is dropping the 'per volume' term and reporting the bare ratio.", "verification": "calc-verified", "calc": {"kind": "liquid-volume", "params": {"ordered_mg": 30, "conc_mg": 10, "conc_ml": 1}, "expected": 3.0, "unit": "mL", "round": 1}},
  {"id": "nx_dose_009", "topicId": 5, "subtopic": "Oral liquids", "difficulty": 1, "question": "A client is prescribed phenytoin suspension 250 mg PO. The label reads 125 mg per 5 mL. How many milliliters should the nurse administer?", "options": ["2 mL", "20 mL", "10 mL", "5 mL"], "correct": 2, "explanation": "Desired ÷ have × volume: (250 ÷ 125) × 5 mL = 10 mL. The commonest error is dropping the 'per volume' term and reporting the bare ratio.", "verification": "calc-verified", "calc": {"kind": "liquid-volume", "params": {"ordered_mg": 250, "conc_mg": 125, "conc_ml": 5}, "expected": 10.0, "unit": "mL", "round": 1}},
  {"id": "nx_dose_010", "topicId": 5, "subtopic": "Oral liquids", "difficulty": 1, "question": "A client is prescribed famotidine oral suspension 20 mg PO. The label reads 40 mg per 5 mL. How many milliliters should the nurse administer?", "options": ["0.5 mL", "2.5 mL", "5 mL", "1.2 mL"], "correct": 1, "explanation": "Desired ÷ have × volume: (20 ÷ 40) × 5 mL = 2.5 mL. The commonest error is dropping the 'per volume' term and reporting the bare ratio.", "verification": "calc-verified", "calc": {"kind": "liquid-volume", "params": {"ordered_mg": 20, "conc_mg": 40, "conc_ml": 5}, "expected": 2.5, "unit": "mL", "round": 1}},
  {"id": "nx_dose_011", "topicId": 5, "subtopic": "Weight-based dosing", "difficulty": 2, "question": "A client weighing 18 kg is prescribed cefazolin 25 mg/kg/dose. How many milligrams should the nurse administer per dose?", "options": ["990 mg", "900 mg", "225 mg", "450 mg"], "correct": 3, "explanation": "25 mg/kg × 18 kg = 450 mg. When the weight is given in pounds, dividing by 2.2 BEFORE multiplying is the whole question.", "verification": "calc-verified", "calc": {"kind": "dose-by-weight", "params": {"mg_per_kg": 25, "weight": 18, "weight_is_lb": 0}, "expected": 450, "unit": "mg", "round": 1}},
  {"id": "nx_dose_012", "topicId": 5, "subtopic": "Weight-based dosing", "difficulty": 2, "question": "A client weighing 22 lb is prescribed acetaminophen 15 mg/kg/dose. How many milligrams should the nurse administer per dose?", "options": ["150 mg", "330 mg", "300 mg", "75 mg"], "correct": 0, "explanation": "Convert first: 22 lb ÷ 2.2 = 10 kg. Then 15 mg/kg × 10 kg = 150 mg. When the weight is given in pounds, dividing by 2.2 BEFORE multiplying is the whole question.", "verification": "calc-verified", "calc": {"kind": "dose-by-weight", "params": {"mg_per_kg": 15, "weight": 22, "weight_is_lb": 1}, "expected": 150.0, "unit": "mg", "round": 1}},
  {"id": "nx_dose_013", "topicId": 5, "subtopic": "Weight-based dosing", "difficulty": 2, "question": "A client weighing 60 kg is prescribed gentamicin 2.5 mg/kg/dose. How many milligrams should the nurse administer per dose?", "options": ["150 mg", "330 mg", "300 mg", "75 mg"], "correct": 0, "explanation": "2.5 mg/kg × 60 kg = 150 mg. When the weight is given in pounds, dividing by 2.2 BEFORE multiplying is the whole question.", "verification": "calc-verified", "calc": {"kind": "dose-by-weight", "params": {"mg_per_kg": 2.5, "weight": 60, "weight_is_lb": 0}, "expected": 150.0, "unit": "mg", "round": 1}},
  {"id": "nx_dose_014", "topicId": 5, "subtopic": "Weight-based dosing", "difficulty": 2, "question": "A client weighing 110 lb is prescribed vancomycin 15 mg/kg/dose. How many milligrams should the nurse administer per dose?", "options": ["1650 mg", "1500 mg", "375 mg", "750 mg"], "correct": 3, "explanation": "Convert first: 110 lb ÷ 2.2 = 50 kg. Then 15 mg/kg × 50 kg = 750 mg. When the weight is given in pounds, dividing by 2.2 BEFORE multiplying is the whole question.", "verification": "calc-verified", "calc": {"kind": "dose-by-weight", "params": {"mg_per_kg": 15, "weight": 110, "weight_is_lb": 1}, "expected": 750.0, "unit": "mg", "round": 1}},
  {"id": "nx_dose_015", "topicId": 5, "subtopic": "Weight-based dosing", "difficulty": 2, "question": "A client weighing 30 kg is prescribed morphine 0.1 mg/kg/dose. How many milligrams should the nurse administer per dose?", "options": ["6.6 mg", "3 mg", "6 mg", "1.5 mg"], "correct": 1, "explanation": "0.1 mg/kg × 30 kg = 3 mg. When the weight is given in pounds, dividing by 2.2 BEFORE multiplying is the whole question.", "verification": "calc-verified", "calc": {"kind": "dose-by-weight", "params": {"mg_per_kg": 0.1, "weight": 30, "weight_is_lb": 0}, "expected": 3.0, "unit": "mg", "round": 1}},
  {"id": "nx_dose_016", "topicId": 5, "subtopic": "IV pump rate", "difficulty": 1, "question": "A provider prescribes 0.9% sodium chloride 1000 mL IV to infuse over 8 hours. At how many milliliters per hour should the nurse set the infusion pump? (Round to the nearest whole number.)", "options": ["208 mL/hr", "250 mL/hr", "125 mL/hr", "62 mL/hr"], "correct": 2, "explanation": "Rate = volume ÷ time: 1000 mL ÷ 8 hr = 125 mL/hr. Pumps are programmed in mL/hr - minutes never enter this calculation.", "verification": "calc-verified", "calc": {"kind": "iv-rate-mlhr", "params": {"volume_ml": 1000, "hours": 8}, "expected": 125.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_017", "topicId": 5, "subtopic": "IV pump rate", "difficulty": 1, "question": "A provider prescribes lactated Ringer's 500 mL IV to infuse over 3 hours. At how many milliliters per hour should the nurse set the infusion pump? (Round to the nearest whole number.)", "options": ["278 mL/hr", "333 mL/hr", "83 mL/hr", "167 mL/hr"], "correct": 3, "explanation": "Rate = volume ÷ time: 500 mL ÷ 3 hr = 167 mL/hr. Pumps are programmed in mL/hr - minutes never enter this calculation.", "verification": "calc-verified", "calc": {"kind": "iv-rate-mlhr", "params": {"volume_ml": 500, "hours": 3}, "expected": 167.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_018", "topicId": 5, "subtopic": "IV pump rate", "difficulty": 1, "question": "A provider prescribes D5W 250 mL IV to infuse over 2 hours. At how many milliliters per hour should the nurse set the infusion pump? (Round to the nearest whole number.)", "options": ["208 mL/hr", "250 mL/hr", "62 mL/hr", "125 mL/hr"], "correct": 3, "explanation": "Rate = volume ÷ time: 250 mL ÷ 2 hr = 125 mL/hr. Pumps are programmed in mL/hr - minutes never enter this calculation.", "verification": "calc-verified", "calc": {"kind": "iv-rate-mlhr", "params": {"volume_ml": 250, "hours": 2}, "expected": 125.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_019", "topicId": 5, "subtopic": "IV pump rate", "difficulty": 1, "question": "A provider prescribes 0.45% sodium chloride 1800 mL IV to infuse over 24 hours. At how many milliliters per hour should the nurse set the infusion pump? (Round to the nearest whole number.)", "options": ["75 mL/hr", "125 mL/hr", "150 mL/hr", "38 mL/hr"], "correct": 0, "explanation": "Rate = volume ÷ time: 1800 mL ÷ 24 hr = 75 mL/hr. Pumps are programmed in mL/hr - minutes never enter this calculation.", "verification": "calc-verified", "calc": {"kind": "iv-rate-mlhr", "params": {"volume_ml": 1800, "hours": 24}, "expected": 75.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_020", "topicId": 5, "subtopic": "IV pump rate", "difficulty": 1, "question": "A provider prescribes D5 1/2 NS with 20 mEq KCl 1000 mL IV to infuse over 6 hours. At how many milliliters per hour should the nurse set the infusion pump? (Round to the nearest whole number.)", "options": ["278 mL/hr", "333 mL/hr", "83 mL/hr", "167 mL/hr"], "correct": 3, "explanation": "Rate = volume ÷ time: 1000 mL ÷ 6 hr = 167 mL/hr. Pumps are programmed in mL/hr - minutes never enter this calculation.", "verification": "calc-verified", "calc": {"kind": "iv-rate-mlhr", "params": {"volume_ml": 1000, "hours": 6}, "expected": 167.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_021", "topicId": 5, "subtopic": "Gravity drip rate", "difficulty": 2, "question": "A provider prescribes 0.9% sodium chloride 1000 mL IV to infuse over 480 minutes by gravity. The tubing drop factor is 15 gtt/mL. At how many drops per minute should the nurse regulate the infusion? (Round to the nearest whole number.)", "options": ["2 gtt/min", "62 gtt/min", "31 gtt/min", "16 gtt/min"], "correct": 2, "explanation": "gtt/min = (volume × drop factor) ÷ minutes = (1000 × 15) ÷ 480 = 31 gtt/min. Forgetting the drop factor gives mL/min, not drops.", "verification": "calc-verified", "calc": {"kind": "iv-drip-gtt", "params": {"volume_ml": 1000, "minutes": 480, "drop_factor": 15}, "expected": 31.0, "unit": "gtt/min", "round": 0}},
  {"id": "nx_dose_022", "topicId": 5, "subtopic": "Gravity drip rate", "difficulty": 2, "question": "A provider prescribes an antibiotic in 100 mL 100 mL IV to infuse over 30 minutes by gravity. The tubing drop factor is 10 gtt/mL. At how many drops per minute should the nurse regulate the infusion? (Round to the nearest whole number.)", "options": ["3 gtt/min", "33 gtt/min", "67 gtt/min", "17 gtt/min"], "correct": 1, "explanation": "gtt/min = (volume × drop factor) ÷ minutes = (100 × 10) ÷ 30 = 33 gtt/min. Forgetting the drop factor gives mL/min, not drops.", "verification": "calc-verified", "calc": {"kind": "iv-drip-gtt", "params": {"volume_ml": 100, "minutes": 30, "drop_factor": 10}, "expected": 33.0, "unit": "gtt/min", "round": 0}},
  {"id": "nx_dose_023", "topicId": 5, "subtopic": "Gravity drip rate", "difficulty": 2, "question": "A provider prescribes lactated Ringer's 500 mL IV to infuse over 240 minutes by gravity. The tubing drop factor is 20 gtt/mL. At how many drops per minute should the nurse regulate the infusion? (Round to the nearest whole number.)", "options": ["2 gtt/min", "42 gtt/min", "83 gtt/min", "21 gtt/min"], "correct": 1, "explanation": "gtt/min = (volume × drop factor) ÷ minutes = (500 × 20) ÷ 240 = 42 gtt/min. Forgetting the drop factor gives mL/min, not drops.", "verification": "calc-verified", "calc": {"kind": "iv-drip-gtt", "params": {"volume_ml": 500, "minutes": 240, "drop_factor": 20}, "expected": 42.0, "unit": "gtt/min", "round": 0}},
  {"id": "nx_dose_024", "topicId": 5, "subtopic": "Gravity drip rate", "difficulty": 2, "question": "A provider prescribes D5W 150 mL IV to infuse over 60 minutes by gravity. The tubing drop factor is 15 gtt/mL. At how many drops per minute should the nurse regulate the infusion? (Round to the nearest whole number.)", "options": ["2 gtt/min", "75 gtt/min", "19 gtt/min", "38 gtt/min"], "correct": 3, "explanation": "gtt/min = (volume × drop factor) ÷ minutes = (150 × 15) ÷ 60 = 38 gtt/min. Forgetting the drop factor gives mL/min, not drops.", "verification": "calc-verified", "calc": {"kind": "iv-drip-gtt", "params": {"volume_ml": 150, "minutes": 60, "drop_factor": 15}, "expected": 38.0, "unit": "gtt/min", "round": 0}},
  {"id": "nx_dose_025", "topicId": 5, "subtopic": "Gravity drip rate", "difficulty": 2, "question": "A provider prescribes an IVPB in 50 mL 50 mL IV to infuse over 20 minutes by gravity. The tubing drop factor is 60 gtt/mL. At how many drops per minute should the nurse regulate the infusion? (Round to the nearest whole number.)", "options": ["150 gtt/min", "2 gtt/min", "300 gtt/min", "75 gtt/min"], "correct": 0, "explanation": "gtt/min = (volume × drop factor) ÷ minutes = (50 × 60) ÷ 20 = 150 gtt/min. Forgetting the drop factor gives mL/min, not drops.", "verification": "calc-verified", "calc": {"kind": "iv-drip-gtt", "params": {"volume_ml": 50, "minutes": 20, "drop_factor": 60}, "expected": 150.0, "unit": "gtt/min", "round": 0}},
  {"id": "nx_dose_026", "topicId": 5, "subtopic": "Metric conversion", "difficulty": 1, "question": "A provider prescribes digoxin 125 mcg PO daily. The medication administration record lists the dose in milligrams. How many milligrams is the prescribed dose?", "options": ["1.25 mg", "0.125 mg", "12.5 mg", "0.013 mg"], "correct": 1, "explanation": "mcg to mg divides by 1,000: 125 mcg = 0.125 mg. Moving the decimal the wrong direction turns a cardiac dose into a 10-fold error - the classic fatal slip.", "verification": "calc-verified", "calc": {"kind": "unit-conversion", "params": {"value": 125, "factor": 0.001}, "expected": 0.125, "unit": "mg", "round": 3}},
  {"id": "nx_dose_027", "topicId": 5, "subtopic": "Metric conversion", "difficulty": 1, "question": "A medication order reads 0.5 g PO every 8 hours. The tablets on hand are labeled in milligrams. How many milligrams equal the ordered dose?", "options": ["50 mg", "500 mg", "5000 mg", "5 mg"], "correct": 1, "explanation": "g to mg multiplies by 1,000: 0.5 g = 500 mg.", "verification": "calc-verified", "calc": {"kind": "unit-conversion", "params": {"value": 0.5, "factor": 1000}, "expected": 500, "unit": "mg", "round": 0}},
  {"id": "nx_dose_028", "topicId": 5, "subtopic": "Household conversion", "difficulty": 1, "question": "A parent will measure a child's medication at home with kitchen teaspoons. The prescribed dose is 10 mL. How many teaspoons should the nurse teach the parent to give?", "options": ["1 teaspoon(s)", "3 teaspoon(s)", "2 teaspoon(s)", "5 teaspoon(s)"], "correct": 2, "explanation": "1 teaspoon = 5 mL, so 10 mL = 2 teaspoons. (Best practice is still an oral syringe; if household measures must be used, teach level, standardized spoons.)", "verification": "calc-verified", "calc": {"kind": "unit-conversion", "params": {"value": 10, "factor": 0.2}, "expected": 2, "unit": "teaspoon(s)", "round": 0}},
  {"id": "nx_dose_029", "topicId": 5, "subtopic": "Reconstitution", "difficulty": 2, "question": "After reconstitution, a vial of cefazolin yields a concentration of 225 mg/mL. The prescription is cefazolin 750 mg IV. How many milliliters should the nurse draw up? (Round to the nearest tenth.)", "options": ["0.3 mL", "6.7 mL", "3.3 mL", "1.7 mL"], "correct": 2, "explanation": "Desired ÷ have: 750 mg ÷ 225 mg/mL = 3.3 mL. Use the concentration printed for the diluent volume you actually added - not the vial's total content.", "verification": "calc-verified", "calc": {"kind": "reconstitution", "params": {"ordered_mg": 750, "conc_mg": 225, "conc_ml": 1}, "expected": 3.3, "unit": "mL", "round": 1}},
  {"id": "nx_dose_030", "topicId": 5, "subtopic": "Reconstitution", "difficulty": 2, "question": "After reconstitution, a vial of ampicillin yields a concentration of 250 mg/mL. The prescription is ampicillin 500 mg IV. How many milliliters should the nurse draw up? (Round to the nearest tenth.)", "options": ["0.5 mL", "4 mL", "2 mL", "1 mL"], "correct": 2, "explanation": "Desired ÷ have: 500 mg ÷ 250 mg/mL = 2 mL. Use the concentration printed for the diluent volume you actually added - not the vial's total content.", "verification": "calc-verified", "calc": {"kind": "reconstitution", "params": {"ordered_mg": 500, "conc_mg": 250, "conc_ml": 1}, "expected": 2.0, "unit": "mL", "round": 1}},
  {"id": "nx_dose_031", "topicId": 5, "subtopic": "Reconstitution", "difficulty": 2, "question": "After reconstitution, a vial of methylprednisolone yields a concentration of 62.5 mg/mL. The prescription is methylprednisolone 100 mg IV. How many milliliters should the nurse draw up? (Round to the nearest tenth.)", "options": ["1.6 mL", "0.6 mL", "3.2 mL", "0.8 mL"], "correct": 0, "explanation": "Desired ÷ have: 100 mg ÷ 62.5 mg/mL = 1.6 mL. Use the concentration printed for the diluent volume you actually added - not the vial's total content.", "verification": "calc-verified", "calc": {"kind": "reconstitution", "params": {"ordered_mg": 100, "conc_mg": 62.5, "conc_ml": 1}, "expected": 1.6, "unit": "mL", "round": 1}},
  {"id": "nx_dose_032", "topicId": 5, "subtopic": "Pediatric safe dose", "difficulty": 3, "question": "The maximum safe dosage of amoxicillin for children is 50 mg/kg/day divided every 12 hours (2 doses/day). For a child weighing 16 kg, what is the maximum safe amount per dose?", "options": ["800 mg", "200 mg", "400 mg", "100 mg"], "correct": 2, "explanation": "Daily maximum: 50 × 16 = 800 mg/day. Divide by 2 doses: 400 mg/dose. Reporting the whole-day maximum as a single dose is the error this item family exists to catch.", "verification": "calc-verified", "calc": {"kind": "pediatric-safe-dose", "params": {"mg_per_kg_day": 50, "doses_per_day": 2, "weight_kg": 16}, "expected": 400.0, "unit": "mg", "round": 0}},
  {"id": "nx_dose_033", "topicId": 5, "subtopic": "Pediatric safe dose", "difficulty": 3, "question": "The maximum safe dosage of cephalexin for children is 100 mg/kg/day divided every 6 hours (4 doses/day). For a child weighing 20 kg, what is the maximum safe amount per dose?", "options": ["2000 mg", "500 mg", "250 mg", "400 mg"], "correct": 1, "explanation": "Daily maximum: 100 × 20 = 2000 mg/day. Divide by 4 doses: 500 mg/dose. Reporting the whole-day maximum as a single dose is the error this item family exists to catch.", "verification": "calc-verified", "calc": {"kind": "pediatric-safe-dose", "params": {"mg_per_kg_day": 100, "doses_per_day": 4, "weight_kg": 20}, "expected": 500.0, "unit": "mg", "round": 0}},
  {"id": "nx_dose_034", "topicId": 5, "subtopic": "Pediatric safe dose", "difficulty": 3, "question": "The maximum safe dosage of ibuprofen for children is 40 mg/kg/day divided every 6 hours (4 doses/day). For a child weighing 25 kg, what is the maximum safe amount per dose?", "options": ["1000 mg", "125 mg", "160 mg", "250 mg"], "correct": 3, "explanation": "Daily maximum: 40 × 25 = 1000 mg/day. Divide by 4 doses: 250 mg/dose. Reporting the whole-day maximum as a single dose is the error this item family exists to catch.", "verification": "calc-verified", "calc": {"kind": "pediatric-safe-dose", "params": {"mg_per_kg_day": 40, "doses_per_day": 4, "weight_kg": 25}, "expected": 250.0, "unit": "mg", "round": 0}},
  {"id": "nx_dose_035", "topicId": 5, "subtopic": "Infusion time", "difficulty": 2, "question": "An infusion of 0.9% sodium chloride 1000 mL is running at 80 mL/hr. How many hours will the infusion take to complete?", "options": ["12.5 hours", "8 hours", "25 hours", "6.2 hours"], "correct": 0, "explanation": "Time = volume ÷ rate: 1000 ÷ 80 = 12.5 hours. This is also how you anticipate the next bag - subtract elapsed time from this total.", "verification": "calc-verified", "calc": {"kind": "infusion-time", "params": {"volume_ml": 1000, "rate_mlhr": 80}, "expected": 12.5, "unit": "hours", "round": 1}},
  {"id": "nx_dose_036", "topicId": 5, "subtopic": "Infusion time", "difficulty": 2, "question": "An infusion of D5W 600 mL is running at 75 mL/hr. How many hours will the infusion take to complete?", "options": ["12.5 hours", "16 hours", "8 hours", "4 hours"], "correct": 2, "explanation": "Time = volume ÷ rate: 600 ÷ 75 = 8 hours. This is also how you anticipate the next bag - subtract elapsed time from this total.", "verification": "calc-verified", "calc": {"kind": "infusion-time", "params": {"volume_ml": 600, "rate_mlhr": 75}, "expected": 8.0, "unit": "hours", "round": 1}},
  {"id": "nx_dose_037", "topicId": 5, "subtopic": "Critical-care infusions", "difficulty": 3, "question": "A provider prescribes dopamine at 5 mcg/kg/min for a client weighing 80 kg. The pharmacy supplies dopamine 400 mg in 250 mL. At how many milliliters per hour should the nurse set the pump? (Round to the nearest whole number.)", "options": ["30 mL/hr", "8 mL/hr", "55 mL/hr", "15 mL/hr"], "correct": 3, "explanation": "Dose: 5 × 80 = 400 mcg/min = 24 mg/hr. Concentration: 400 mg ÷ 250 mL = 1.6 mg/mL. Rate: 24 ÷ 1.6 = 15 mL/hr. The mcg-to-mg step is where this calculation dies - do it explicitly, in writing.", "verification": "calc-verified", "calc": {"kind": "iv-dose-mlhr", "params": {"mcg_per_kg_min": 5, "weight_kg": 80, "bag_mg": 400, "bag_ml": 250}, "expected": 15.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_038", "topicId": 5, "subtopic": "Critical-care infusions", "difficulty": 3, "question": "A provider prescribes norepinephrine at 0.1 mcg/kg/min for a client weighing 70 kg. The pharmacy supplies norepinephrine 4 mg in 250 mL. At how many milliliters per hour should the nurse set the pump? (Round to the nearest whole number.)", "options": ["26 mL/hr", "52 mL/hr", "13 mL/hr", "66 mL/hr"], "correct": 0, "explanation": "Dose: 0.1 × 70 = 7 mcg/min = 0.42 mg/hr. Concentration: 4 mg ÷ 250 mL = 0.016 mg/mL. Rate: 0.42 ÷ 0.016 = 26 mL/hr. The mcg-to-mg step is where this calculation dies - do it explicitly, in writing.", "verification": "calc-verified", "calc": {"kind": "iv-dose-mlhr", "params": {"mcg_per_kg_min": 0.1, "weight_kg": 70, "bag_mg": 4, "bag_ml": 250}, "expected": 26.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_039", "topicId": 5, "subtopic": "Critical-care infusions", "difficulty": 3, "question": "A provider prescribes nitroprusside at 0.5 mcg/kg/min for a client weighing 60 kg. The pharmacy supplies nitroprusside 50 mg in 250 mL. At how many milliliters per hour should the nurse set the pump? (Round to the nearest whole number.)", "options": ["18 mL/hr", "9 mL/hr", "4 mL/hr", "9000 mL/hr"], "correct": 1, "explanation": "Dose: 0.5 × 60 = 30 mcg/min = 1.8 mg/hr. Concentration: 50 mg ÷ 250 mL = 0.2 mg/mL. Rate: 1.8 ÷ 0.2 = 9 mL/hr. The mcg-to-mg step is where this calculation dies - do it explicitly, in writing.", "verification": "calc-verified", "calc": {"kind": "iv-dose-mlhr", "params": {"mcg_per_kg_min": 0.5, "weight_kg": 60, "bag_mg": 50, "bag_ml": 250}, "expected": 9.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_040", "topicId": 5, "subtopic": "Heparin protocol", "difficulty": 3, "question": "A heparin protocol prescribes 18 units/kg/hr for a client weighing 70 kg. The infusion bag contains heparin 25,000 units in 250 mL. At how many milliliters per hour should the nurse set the pump? (Round to the nearest whole number.)", "options": ["13 mL/hr", "25 mL/hr", "6 mL/hr", "18 mL/hr"], "correct": 0, "explanation": "Dose: 18 × 70 = 1260 units/hr. Concentration: 25,000 ÷ 250 = 100 units/mL. Rate: 1260 ÷ 100 = 13 mL/hr. Heparin errors are never small errors - verify with a second nurse per policy.", "verification": "calc-verified", "calc": {"kind": "iv-dose-mlhr", "params": {"units_per_kg_hr": 18, "weight_kg": 70, "bag_units": 25000, "bag_ml": 250}, "expected": 13.0, "unit": "mL/hr", "round": 0}},
  {"id": "nx_dose_041", "topicId": 5, "subtopic": "Heparin protocol", "difficulty": 3, "question": "A heparin protocol prescribes 18 units/kg/hr for a client weighing 90 kg. The infusion bag contains heparin 25,000 units in 500 mL. At how many milliliters per hour should the nurse set the pump? (Round to the nearest whole number.)", "options": ["16 mL/hr", "65 mL/hr", "32 mL/hr", "37 mL/hr"], "correct": 2, "explanation": "Dose: 18 × 90 = 1620 units/hr. Concentration: 25,000 ÷ 500 = 50 units/mL. Rate: 1620 ÷ 50 = 32 mL/hr. Heparin errors are never small errors - verify with a second nurse per policy.", "verification": "calc-verified", "calc": {"kind": "iv-dose-mlhr", "params": {"units_per_kg_hr": 18, "weight_kg": 90, "bag_units": 25000, "bag_ml": 500}, "expected": 32.0, "unit": "mL/hr", "round": 0}},
];

// ─────────────────────────────────────────────────────────────────
// CLINICAL ITEMS — AI-authored, unverified pending SME review
// ─────────────────────────────────────────────────────────────────

export const NCLEX_CLINICAL_QUESTIONS_1: NclexQuestion[] = [
  // ═══ TOPIC 0 — Management of Care (14) ═══
  {
    id: 'nx_moc_001',
    topicId: 0,
    subtopic: 'Prioritization',
    difficulty: 2,
    question:
      'The nurse receives report on four clients. Which client should the nurse assess first?',
    options: [
      'A client with asthma who has audible inspiratory stridor after a bee sting',
      'A client 2 days post abdominal surgery reporting incisional pain of 6/10',
      'A client with type 2 diabetes whose fasting glucose is 180 mg/dL',
      'A client awaiting discharge teaching for new warfarin therapy',
    ],
    correct: 0,
    explanation:
      'Stridor after an allergen exposure signals impending airway obstruction from anaphylaxis — an airway emergency that outranks pain, an elevated but not critical glucose, and teaching. Airway always wins the "who first" question unless another client is actively coding.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_002',
    topicId: 0,
    subtopic: 'Delegation',
    difficulty: 2,
    question:
      'Which task is appropriate for the registered nurse to delegate to assistive personnel (AP)?',
    options: [
      'Obtaining vital signs on a client who returned from surgery 30 minutes ago',
      'Ambulating a client whose condition has been stable for two days',
      'Teaching a client how to use an incentive spirometer',
      'Assessing a newly admitted client’s skin for pressure injuries',
    ],
    correct: 1,
    explanation:
      'AP may perform routine care for STABLE clients with predictable outcomes. A fresh post-op client’s vitals are an assessment in disguise (the data drive immediate decisions), and teaching and assessment can never be delegated — they are the nurse’s own scope.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_003',
    topicId: 0,
    subtopic: 'Delegation',
    difficulty: 2,
    question:
      'Which client care activity may the registered nurse assign to a licensed practical nurse (LPN/LVN)?',
    options: [
      'Completing the initial admission assessment for a new client',
      'Developing the plan of care for a client with heart failure',
      'Administering scheduled oral medications to a stable client',
      'Providing discharge teaching about insulin self-injection',
    ],
    correct: 2,
    explanation:
      'LPNs care for stable clients with expected outcomes: they administer most medications, reinforce teaching, and collect data. Initial assessment, care-plan development, and initial teaching remain RN responsibilities in every state model the exam tests.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_004',
    topicId: 0,
    subtopic: 'Informed consent',
    difficulty: 1,
    question:
      'A client scheduled for surgery asks the nurse detailed questions about the procedure’s risks before signing the consent form. What is the nurse’s appropriate action?',
    options: [
      'Answer the questions using the surgical brochure',
      'Have the client sign and note the questions in the chart',
      'Ask the charge nurse to explain the risks',
      'Contact the surgeon to return and answer the questions',
    ],
    correct: 3,
    explanation:
      'Explaining the procedure, its risks, benefits, and alternatives is the PROVIDER’s legal duty — the nurse witnesses the signature and verifies the client’s understanding appears informed and voluntary. Unanswered risk questions mean consent is not yet informed, so the surgeon must return before signing.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_005',
    topicId: 0,
    subtopic: 'Informed consent',
    difficulty: 2,
    question:
      'A client who signed a surgical consent form yesterday tells the nurse, "I’ve changed my mind — I don’t want the operation." What is the nurse’s best action?',
    options: [
      'Notify the surgeon that the client is withdrawing consent',
      'Remind the client that the consent form has already been signed',
      'Ask the family to help the client reconsider the decision',
      'Document the statement and continue preoperative preparation',
    ],
    correct: 0,
    explanation:
      'Consent may be withdrawn at any time, verbally, right up to the procedure — a signature does not bind the client. The nurse stops preparation and notifies the provider. Pressuring through family or proceeding anyway would constitute battery.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_006',
    topicId: 0,
    subtopic: 'Advance directives',
    difficulty: 2,
    question:
      'A client with a documented do-not-resuscitate (DNR) prescription develops increasing dyspnea and anxiety. Which action should the nurse take?',
    options: [
      'Withhold all interventions because of the DNR status',
      'Provide oxygen and comfort measures as prescribed',
      'Prepare for intubation while awaiting the provider',
      'Ask the family whether to treat the symptoms',
    ],
    correct: 1,
    explanation:
      'DNR means no CPR at the moment of arrest — nothing more. Symptom management, oxygen, positioning, and every other comfort and treatment measure continue. Withholding ordinary care from a DNR client is a common and dangerous misreading of the order.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_007',
    topicId: 0,
    subtopic: 'Confidentiality',
    difficulty: 1,
    question:
      'The nurse overhears two colleagues discussing a client’s HIV status by name in a public elevator. What should the nurse do first?',
    options: [
      'Report both colleagues to the state board of nursing',
      'File an anonymous complaint with the compliance office',
      'Address the colleagues directly and ask them to stop',
      'Ignore it since the colleagues are involved in the client’s care',
    ],
    correct: 2,
    explanation:
      'The breach is happening NOW, so the first action is the one that stops it: speak up directly. Chain-of-command reporting follows if the behavior continues. Even caregivers involved in the case may not discuss protected information where others can hear.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_008',
    topicId: 0,
    subtopic: 'Assignment & floating',
    difficulty: 3,
    question:
      'A medical-surgical nurse is floated to the coronary care unit and assigned a client with an unfamiliar titrated infusion. What is the nurse’s best response?',
    options: [
      'Refuse the float assignment and return to the home unit',
      'Accept the assignment and look up the infusion protocol',
      'Ask another nurse on the unit to co-sign all care provided',
      'Inform the charge nurse of skill limitations and request an assignment matching current competencies',
    ],
    correct: 3,
    explanation:
      'A floated nurse accepts the float but negotiates the ASSIGNMENT: state what is within competence and what is not, so unfamiliar high-risk tasks (titration) go to unit staff while the floated nurse takes stable clients. Outright refusal risks abandonment; quietly winging it risks the client.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_009',
    topicId: 0,
    subtopic: 'Disaster triage',
    difficulty: 3,
    question:
      'Following a mass-casualty incident, which victim should receive treatment FIRST under disaster triage principles?',
    options: [
      'A victim with an open chest wound and respiratory rate of 34/min',
      'A victim who is not breathing after the airway is repositioned',
      'A victim walking around with a bleeding forearm laceration',
      'A victim with a closed femur fracture and stable vital signs',
    ],
    correct: 0,
    explanation:
      'Disaster triage reverses everyday logic: resources go to the salvageable critical (red tag) — here the chest wound with respiratory compromise. The apneic victim who does not breathe after airway repositioning is tagged expectant (black), the walker is minimal (green), and the stable fracture is delayed (yellow).',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_010',
    topicId: 0,
    subtopic: 'Delegation',
    difficulty: 2,
    type: 'multi',
    question:
      'Which tasks may the registered nurse delegate to assistive personnel (AP)? Select all that apply.',
    options: [
      'Recording intake and output for a client with heart failure',
      'Assisting a stable client with a shower',
      'Evaluating a client’s response to a new pain medication',
      'Turning and repositioning a client on a schedule',
      'Administering a subcutaneous heparin injection',
      'Ambulating a client two days after hip replacement per protocol',
    ],
    correctAnswers: [0, 1, 3, 5],
    explanation:
      'AP scope covers standard, unchanging care for stable clients: measuring and recording (not interpreting) I&O, hygiene, scheduled repositioning, and protocol ambulation. Evaluating a medication response is assessment; giving injections is medication administration — both stay with licensed staff.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_011',
    topicId: 0,
    subtopic: 'Incident reporting',
    difficulty: 2,
    question:
      'A nurse realizes a client received another client’s antihypertensive an hour ago. After assessing the client, blood pressure is 92/58 mm Hg. Which action sequence is correct?',
    options: [
      'Complete an incident report and document "incident report filed" in the medical record',
      'Notify the provider, monitor the client, and complete an incident report that stays out of the medical record',
      'Document the error in the medical record only if the client becomes symptomatic',
      'Report the error to the pharmacy and await further instructions',
    ],
    correct: 1,
    explanation:
      'Client first (assess — already done), then provider notification and monitoring, then an incident report for the quality system. The report itself is never referenced in the chart; the chart records the facts — what was given, the assessment, who was notified — without mentioning the report’s existence.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_012',
    topicId: 0,
    subtopic: 'Prioritization',
    difficulty: 2,
    question:
      'The nurse hears gurgling respirations from a client with a new tracheostomy while another assigned client reports chest pain rated 8/10. What should the nurse do first?',
    options: [
      'Obtain a 12-lead ECG on the client with chest pain',
      'Administer PRN nitroglycerin to the client with chest pain',
      'Suction the client with the tracheostomy',
      'Delegate tracheostomy suctioning to assistive personnel',
    ],
    correct: 2,
    explanation:
      'Gurgling from an artificial airway is an immediate airway-patency threat — airway precedes even a potential cardiac event. Suctioning is quick, then the chest-pain workup follows. Suctioning an artificial airway is never delegated to AP.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_013',
    topicId: 0,
    subtopic: 'Interdisciplinary care',
    difficulty: 1,
    question:
      'A client recovering from a stroke coughs and chokes when swallowing thin liquids. A referral to which team member is most appropriate?',
    options: [
      'Occupational therapist',
      'Physical therapist',
      'Registered dietitian',
      'Speech-language pathologist',
    ],
    correct: 3,
    explanation:
      'Swallowing evaluation and dysphagia therapy belong to the speech-language pathologist. The dietitian adjusts what is served after the SLP determines safe consistencies; OT addresses activities of daily living; PT addresses mobility.',
    verification: 'unverified',
  },
  {
    id: 'nx_moc_014',
    topicId: 0,
    subtopic: 'Informed consent',
    difficulty: 3,
    type: 'multi',
    question:
      'Which elements are required for a client’s informed consent to be valid? Select all that apply.',
    options: [
      'The client has the capacity to make the decision',
      'The decision is voluntary and free of coercion',
      'Risks, benefits, and alternatives have been explained by the provider',
      'The client’s family agrees with the decision',
      'The nurse has explained the surgical technique in detail',
    ],
    correctAnswers: [0, 1, 2],
    explanation:
      'Valid consent = capacity + voluntariness + disclosure by the person performing the procedure. Family agreement is irrelevant for a client with capacity, and explaining the procedure is the provider’s duty, not the nurse’s — the nurse witnesses and advocates.',
    verification: 'unverified',
  },

  // ═══ TOPIC 1 — Safety & Infection Control (12) ═══
  {
    id: 'nx_sic_001',
    topicId: 1,
    subtopic: 'Transmission precautions',
    difficulty: 2,
    question:
      'A child is admitted with measles (rubeola). Which room placement and personal protective equipment are required?',
    options: [
      'Negative-pressure airborne infection isolation room; N95 respirator',
      'Private room with the door open; surgical mask within 3 feet',
      'Standard room; gown and gloves for all contact',
      'Cohorted room with another febrile child; surgical mask',
    ],
    correct: 0,
    explanation:
      'Measles, tuberculosis, and varicella are the airborne three: negative-pressure room, door closed, and a fit-tested N95 (or PAPR) for everyone entering. A surgical mask protects against droplets, not airborne nuclei that remain suspended for hours.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_002',
    topicId: 1,
    subtopic: 'Transmission precautions',
    difficulty: 2,
    question:
      'The nurse is caring for a client with meningococcal meningitis who was started on antibiotics 6 hours ago. Which precaution applies?',
    options: [
      'Airborne precautions with an N95 respirator',
      'Droplet precautions with a surgical mask within 3 feet of the client',
      'Contact precautions with gown and gloves',
      'Standard precautions only, since antibiotics have begun',
    ],
    correct: 1,
    explanation:
      'Neisseria meningitidis spreads by large droplets: surgical mask on approach, private room or cohorting. Droplet precautions continue until 24 hours of effective antibiotics — at 6 hours the client is still contagious.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_003',
    topicId: 1,
    subtopic: 'Transmission precautions',
    difficulty: 2,
    question:
      'After caring for a client with Clostridioides difficile infection, which hand-hygiene method must the nurse use?',
    options: [
      'Alcohol-based hand rub for at least 20 seconds',
      'Alcohol rub followed by donning new gloves',
      'Soap and water',
      'Chlorhexidine wipes on visibly clean hands',
    ],
    correct: 2,
    explanation:
      'C. difficile forms spores that alcohol does not kill — only the mechanical action of washing with soap and water physically removes them. This is the exam’s favorite exception to the "alcohol rub is preferred" rule.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_004',
    topicId: 1,
    subtopic: 'PPE sequence',
    difficulty: 1,
    question:
      'When donning personal protective equipment for contact and droplet precautions, which sequence is correct?',
    options: [
      'Gloves, gown, mask, goggles',
      'Mask, gloves, gown, goggles',
      'Goggles, mask, gown, gloves',
      'Gown, mask, goggles, gloves',
    ],
    correct: 3,
    explanation:
      'Donning goes gown → mask/respirator → goggles/face shield → gloves (gloves last so they cover the gown cuffs). Doffing reverses the contamination logic: gloves first, gown, then eyewear, mask last, hand hygiene throughout.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_005',
    topicId: 1,
    subtopic: 'PPE sequence',
    difficulty: 1,
    question:
      'Which piece of personal protective equipment should the nurse remove FIRST when leaving the room of a client on contact precautions?',
    options: ['Gown', 'Gloves', 'Goggles', 'Mask'],
    correct: 1,
    explanation:
      'Gloves are the most contaminated item and come off first, followed by goggles, gown, and mask (mask always last, outside the room for airborne). Removing the gown first would drag contaminated gloves across clothing.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_006',
    topicId: 1,
    subtopic: 'Restraints',
    difficulty: 2,
    question:
      'A client with acute confusion repeatedly pulls at a central line, and less-restrictive alternatives have failed. Wrist restraints are prescribed. Which action is required?',
    options: [
      'Release the restraints and assess circulation at least every 2 hours',
      'Tie the restraints to the side rails with a double knot',
      'Renew the prescription automatically every 72 hours',
      'Keep the restraints in place until the confusion fully resolves',
    ],
    correct: 0,
    explanation:
      'Restrained limbs are released, exercised, and checked for circulation and skin integrity on a schedule (commonly every 2 hours). Restraints tie to the bed FRAME with a quick-release knot, orders are time-limited and never PRN, and the need is reassessed continuously — not parked until discharge.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_007',
    topicId: 1,
    subtopic: 'Fall prevention',
    difficulty: 1,
    question:
      'Which intervention is appropriate for a hospitalized older adult identified as a high fall risk?',
    options: [
      'Raise all four side rails whenever the client is in bed',
      'Keep the bed in the lowest position with the call light within reach',
      'Place the client in a room far from the nurses’ station to reduce noise',
      'Encourage the client to wait for staff before using the urinal',
    ],
    correct: 1,
    explanation:
      'Low bed, locked wheels, call light in reach, clear path, non-skid footwear, and a room NEAR the station are the core bundle. All four rails up is a restraint (and a fall-over-the-rail hazard). Toileting needs should be scheduled proactively, not deferred.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_008',
    topicId: 1,
    subtopic: 'Fire safety',
    difficulty: 1,
    question:
      'The nurse discovers a small fire in a client’s bathroom while the client is in bed. What is the nurse’s FIRST action?',
    options: [
      'Pull the nearest fire alarm',
      'Attempt to extinguish the fire',
      'Move the client away from the room',
      'Close the bathroom door to confine the fire',
    ],
    correct: 2,
    explanation:
      'RACE: Rescue anyone in immediate danger first, then Alarm, Confine, Extinguish/Evacuate. With a client in the room, rescue precedes the alarm — the sequence flexes only when no one is in danger.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_009',
    topicId: 1,
    subtopic: 'Infection control',
    difficulty: 2,
    type: 'multi',
    question:
      'The nurse is caring for a client with Clostridioides difficile diarrhea. Which infection-control measures are required? Select all that apply.',
    options: [
      'Wash hands with soap and water after care',
      'Use alcohol-based hand rub as the primary hand hygiene',
      'Wear gown and gloves for all room entry',
      'Dedicate equipment such as the stethoscope to this client',
      'Clean surfaces with a sporicidal (bleach-based) agent',
    ],
    correctAnswers: [0, 2, 3, 4],
    explanation:
      'C. diff = contact precautions plus the spore problem: soap-and-water hand washing, gown and gloves on entry, dedicated equipment, and sporicidal cleaning. Alcohol rub fails against spores — relying on it as primary hand hygiene is the one practice here that must be rejected.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_010',
    topicId: 1,
    subtopic: 'Home safety',
    difficulty: 1,
    question:
      'The nurse is teaching a client who will use home oxygen. Which client statement indicates a need for further teaching?',
    options: [
      '"I will keep my oxygen at least 10 feet away from the gas stove."',
      '"I will wear cotton clothing rather than synthetic fabrics."',
      '"I will post no-smoking signs at my front door."',
      '"I will use petroleum jelly to keep my nostrils from drying out."',
    ],
    correct: 3,
    explanation:
      'Petroleum-based products are combustible in an oxygen-enriched environment — water-based lubricant only. Distance from open flames, no-smoking signage, and static-reducing cotton clothing are all correct practices.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_011',
    topicId: 1,
    subtopic: 'Sharps safety',
    difficulty: 1,
    question:
      'After administering an intramuscular injection, which action by the nurse prevents needlestick injury?',
    options: [
      'Activate the safety device and place the syringe directly in a sharps container',
      'Recap the needle carefully using both hands',
      'Bend the needle before disposal so it cannot be reused',
      'Leave the syringe on the medication tray for later disposal',
    ],
    correct: 0,
    explanation:
      'Engage the engineered safety feature and dispose at the point of use — immediately, into the sharps container. Recapping, bending, or carrying exposed sharps are the three classic causes of occupational needlesticks.',
    verification: 'unverified',
  },
  {
    id: 'nx_sic_012',
    topicId: 1,
    subtopic: 'Seizure precautions',
    difficulty: 2,
    type: 'multi',
    question:
      'The nurse is preparing a room for a client admitted with new-onset seizures. Which items and measures are appropriate? Select all that apply.',
    options: [
      'Padding on the side rails',
      'Suction equipment and oxygen at the bedside',
      'A padded tongue blade taped above the bed',
      'The bed kept in the lowest position',
      'Soft limb restraints applied prophylactically',
    ],
    correctAnswers: [0, 1, 3],
    explanation:
      'Seizure precautions: padded rails, low bed, and immediate access to suction and oxygen. Nothing ever goes in a seizing client’s mouth — the tongue blade is an obsolete danger — and restraints during a seizure cause injury.',
    verification: 'unverified',
  },

  // ═══ TOPIC 2 — Health Promotion & Maintenance (10) ═══
  {
    id: 'nx_hpm_001',
    topicId: 2,
    subtopic: 'Infant development',
    difficulty: 2,
    question:
      'During a 6-month well-child visit, which developmental finding should the nurse expect?',
    options: [
      'Walks holding onto furniture',
      'Rolls from back to abdomen',
      'Says two or three words with meaning',
      'Builds a tower of two blocks',
    ],
    correct: 1,
    explanation:
      'By 6 months an infant rolls both ways, sits with support, and babbles. Cruising furniture is ~10-12 months, first meaningful words ~12 months, and a two-block tower ~15 months. Milestone offsets like these are the exam’s favorite pediatric pattern.',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_002',
    topicId: 2,
    subtopic: 'Toddler safety',
    difficulty: 1,
    question:
      'The nurse is teaching parents of a 2-year-old about choking prevention. Which food should be eliminated entirely rather than modified?',
    options: [
      'Grapes cut lengthwise into quarters',
      'Toast cut into thin strips',
      'Whole round hot dog slices',
      'Scrambled eggs in small portions',
    ],
    correct: 2,
    explanation:
      'Round, coin-shaped hot dog slices are the classic airway plug for toddlers — they must be cut lengthwise, never served as rounds. Quartered grapes, toast strips, and scrambled eggs are already in safe form.',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_003',
    topicId: 2,
    subtopic: 'Immunizations',
    difficulty: 2,
    question:
      'Which client should NOT receive the measles-mumps-rubella (MMR) vaccine?',
    options: [
      'A 12-month-old with a mild cold and low-grade fever',
      'A 4-year-old whose sibling is immunocompromised',
      'A toddler allergic to penicillin',
      'A woman who is 8 weeks pregnant',
    ],
    correct: 3,
    explanation:
      'MMR is a live attenuated vaccine: contraindicated in pregnancy and significant immunosuppression. Mild illness is not a contraindication, penicillin allergy is irrelevant, and household contacts of immunocompromised people SHOULD be vaccinated (the virus does not shed transmissibly).',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_004',
    topicId: 2,
    subtopic: 'Prenatal care',
    difficulty: 1,
    question:
      'A client planning pregnancy asks why folic acid is recommended before conception. The nurse explains that adequate folic acid intake reduces the risk of which condition?',
    options: [
      'Neural tube defects such as spina bifida',
      'Gestational diabetes',
      'Preeclampsia in the third trimester',
      'Newborn jaundice',
    ],
    correct: 0,
    explanation:
      'The neural tube closes in the first four weeks — often before pregnancy is recognized — so 400 mcg daily folic acid must begin BEFORE conception to prevent defects like spina bifida and anencephaly.',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_005',
    topicId: 2,
    subtopic: 'Postpartum care',
    difficulty: 2,
    question:
      'Twelve hours after vaginal delivery, the nurse palpates a fundus that is boggy and displaced to the right of midline. What should the nurse do first?',
    options: [
      'Massage the fundus until firm',
      'Assist the client to empty the bladder',
      'Administer the PRN oxytocin infusion',
      'Notify the health care provider',
    ],
    correct: 1,
    explanation:
      'Right-of-midline displacement is the signature of a full bladder pushing the uterus aside and preventing contraction. Emptying the bladder usually restores tone; massage and oxytocin follow if bogginess persists. (Boggy AND midline? Then massage is the first move.)',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_006',
    topicId: 2,
    subtopic: 'Newborn assessment',
    difficulty: 2,
    question:
      'Which finding in a 12-hour-old newborn requires immediate follow-up?',
    options: [
      'Bluish discoloration of the hands and feet',
      'Irregular breathing with brief 5-second pauses',
      'Central cyanosis of the lips and trunk',
      'Head circumference 2 cm larger than chest circumference',
    ],
    correct: 2,
    explanation:
      'Acrocyanosis (blue hands and feet) is normal for 24-48 hours, periodic breathing with pauses under 20 seconds is normal, and head exceeding chest by ~2 cm is expected. Central cyanosis is never normal — it signals hypoxemia and possible congenital heart disease.',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_007',
    topicId: 2,
    subtopic: 'Fetal monitoring',
    difficulty: 3,
    question:
      'A laboring client receiving an oxytocin infusion develops recurrent late decelerations on the fetal monitor. Which action should the nurse take FIRST?',
    options: [
      'Increase the oxytocin rate to shorten labor',
      'Prepare the client for immediate cesarean birth',
      'Document the pattern and continue monitoring',
      'Stop the oxytocin infusion and reposition the client to her side',
    ],
    correct: 3,
    explanation:
      'Late decelerations mean uteroplacental insufficiency. The intrauterine resuscitation bundle: stop the uterotonic, lateral position, IV fluid bolus, oxygen, and notify the provider. Increasing oxytocin worsens the insult; surgery is a provider decision after resuscitation fails.',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_008',
    topicId: 2,
    subtopic: 'Adolescent development',
    difficulty: 1,
    question:
      'According to Erikson, the primary psychosocial task of adolescence is the development of which of the following?',
    options: [
      'A sense of personal identity',
      'Initiative in play and activities',
      'Trust in caregivers',
      'Generativity through guiding others',
    ],
    correct: 0,
    explanation:
      'Adolescence is identity versus role confusion — trying on values, groups, and future selves. Trust belongs to infancy, initiative to the preschool years, and generativity to middle adulthood.',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_009',
    topicId: 2,
    subtopic: 'Older adult health',
    difficulty: 2,
    question:
      'Which finding in an 82-year-old client should the nurse recognize as NOT a normal change of aging?',
    options: [
      'Difficulty reading small print at close range',
      'New disorientation to place and time',
      'Decreased skin elasticity and thinner skin',
      'Slower reaction time when responding to questions',
    ],
    correct: 1,
    explanation:
      'Presbyopia, thinning skin, and slowed processing are expected with age. Acute confusion or new disorientation is never normal aging — it demands a workup for delirium, whose common reversible causes include infection, medications, and hypoxia.',
    verification: 'unverified',
  },
  {
    id: 'nx_hpm_010',
    topicId: 2,
    subtopic: 'Aging changes',
    difficulty: 2,
    type: 'multi',
    question:
      'Which findings should the nurse attribute to normal physiologic aging? Select all that apply.',
    options: [
      'Decreased skin turgor and elasticity',
      'Reduced near vision (presbyopia)',
      'Urinary incontinence',
      'Decreased bladder capacity with more frequent urination',
      'Confusion in the late afternoon',
    ],
    correctAnswers: [0, 1, 3],
    explanation:
      'Turgor loss, presbyopia, and smaller bladder capacity are expected. Incontinence and confusion are common in older adults but always pathological findings to investigate — treating them as "just aging" is the error this question exists to catch.',
    verification: 'unverified',
  },

  // ═══ TOPIC 3 — Psychosocial Integrity (10) ═══
  {
    id: 'nx_psy_001',
    topicId: 3,
    subtopic: 'Therapeutic communication',
    difficulty: 2,
    question:
      'A client awaiting biopsy results says, "I’m so afraid it’s cancer." Which nursing response is most therapeutic?',
    options: [
      '"Don’t worry — most biopsies come back benign."',
      '"Why do you think it will be cancer?"',
      '"Tell me more about what you’re afraid of."',
      '"You should stay positive until the results are in."',
    ],
    correct: 2,
    explanation:
      'The therapeutic response opens the door to the feeling. False reassurance and "stay positive" dismiss it, and "why" questions demand justification and put clients on the defensive — all three are classic non-therapeutic blocks.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_002',
    topicId: 3,
    subtopic: 'Suicide risk',
    difficulty: 2,
    question:
      'A client being treated for depression says, "Everyone would be better off without me." What is the nurse’s priority action?',
    options: [
      'Document the statement and inform the next shift',
      'Change the subject to something pleasant',
      'Reassure the client that many people care',
      'Ask directly, "Are you thinking about killing yourself?"',
    ],
    correct: 3,
    explanation:
      'Suicidal statements are assessed directly and immediately — asking about suicide does not plant the idea, it opens the only door to assessing plan, means, and intent. Deflection, reassurance, or delayed handoff all leave the risk unmeasured.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_003',
    topicId: 3,
    subtopic: 'Suicide precautions',
    difficulty: 2,
    question:
      'A client admitted after a suicide attempt states an intent to try again and describes a specific plan. Which intervention is required?',
    options: [
      'One-to-one constant observation',
      'Checks by staff every 15 minutes',
      'A private room close to the nurses’ station',
      'A written no-suicide contract',
    ],
    correct: 0,
    explanation:
      'Active intent plus a plan is the highest-risk state: continuous one-to-one observation, environment stripped of means. Fifteen-minute checks leave lethal windows, private rooms reduce observation, and no-suicide contracts have no protective evidence.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_004',
    topicId: 3,
    subtopic: 'Substance withdrawal',
    difficulty: 3,
    question:
      'A client hospitalized for pancreatitis, who reports drinking a pint of vodka daily, develops tremors, tachycardia, and blood pressure 168/98 mm Hg about 18 hours after the last drink. Which prescription should the nurse administer?',
    options: [
      'Naloxone IV push',
      'Lorazepam per the withdrawal protocol',
      'Haloperidol for agitation',
      'Clonidine for blood pressure',
    ],
    correct: 1,
    explanation:
      'Autonomic hyperactivity 6-24 hours after the last drink is early alcohol withdrawal; benzodiazepines are the treatment and the prophylaxis against seizures and delirium tremens (peak 48-72 h). Naloxone reverses opioids; antipsychotics lower the seizure threshold.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_005',
    topicId: 3,
    subtopic: 'Mandatory reporting',
    difficulty: 2,
    question:
      'A 4-year-old has bruises in various healing stages on the back and thighs, and the caregiver’s explanation does not match the injuries. What is the nurse’s legal obligation?',
    options: [
      'Confront the caregiver about the suspected abuse',
      'Wait for the provider to confirm abuse before acting',
      'Report the suspicion to child protective services',
      'Document the findings and schedule a follow-up visit',
    ],
    correct: 2,
    explanation:
      'Nurses are mandated reporters: SUSPICION triggers the report — confirmation is the agency’s job, not a prerequisite. Confronting caregivers risks the child and the investigation; documentation alone discharges nothing.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_006',
    topicId: 3,
    subtopic: 'Intimate partner violence',
    difficulty: 2,
    question:
      'The nurse suspects intimate partner violence during an emergency department visit. Which approach to screening is correct?',
    options: [
      'Ask the screening questions while the partner is present to observe reactions',
      'Ask the partner to describe how the injuries occurred',
      'Give the client a pamphlet and wait for disclosure',
      'Interview the client alone, in private',
    ],
    correct: 3,
    explanation:
      'Screening is valid only in private — a victim cannot answer truthfully next to the abuser, and asking may escalate danger at home. Separate the interview from the partner using routine pretexts (imaging, procedures) if needed.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_007',
    topicId: 3,
    subtopic: 'Grief',
    difficulty: 2,
    question:
      'Two weeks after her husband’s death, a widow tells the nurse she sometimes hears his voice calling her name. How should the nurse interpret this?',
    options: [
      'An expected experience in acute grief',
      'An early sign of psychotic depression',
      'Complicated grief requiring referral',
      'An adverse medication effect',
    ],
    correct: 0,
    explanation:
      'Transient hallucinations of the deceased — hearing a voice, sensing a presence — are common and normal in acute grief. Complicated grief is a matter of intensity and duration (persistent, functionally disabling, typically past 6-12 months), not this single early experience.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_008',
    topicId: 3,
    subtopic: 'Anxiety & panic',
    difficulty: 1,
    question:
      'A client is hyperventilating and gripping the bedrail during a panic attack. Which nursing action is appropriate?',
    options: [
      'Leave the client alone to regain composure',
      'Stay with the client and give brief, simple directions',
      'Explain in detail why the fear is irrational',
      'Encourage the client to describe childhood stressors',
    ],
    correct: 1,
    explanation:
      'During panic, cognition narrows: stay present, reduce stimulation, use short simple sentences, and model slow breathing. Reasoning, analysis, and exploration belong AFTER the attack; leaving increases terror.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_009',
    topicId: 3,
    subtopic: 'Dementia care',
    difficulty: 2,
    question:
      'A client with dementia repeatedly tries to leave the unit, saying, "I have to get to work." Which response by the nurse is best?',
    options: [
      '"You retired years ago — you don’t work anymore."',
      '"If you keep trying to leave, we’ll have to restrain you."',
      '"Walk with me and tell me about the work you do."',
      '"Your family asked us to keep you here."',
    ],
    correct: 2,
    explanation:
      'Redirection with validation meets the emotional need (purpose, urgency) without arguing with the client’s reality. Reorientation-by-correction agitates in mid-to-late dementia, and threats of restraint are never therapeutic.',
    verification: 'unverified',
  },
  {
    id: 'nx_psy_010',
    topicId: 3,
    subtopic: 'Therapeutic communication',
    difficulty: 2,
    type: 'multi',
    question:
      'Which techniques are examples of therapeutic communication? Select all that apply.',
    options: [
      'Sitting in silence while a tearful client collects thoughts',
      'Restating: "You feel the treatments aren’t helping."',
      'Asking, "Why did you stop taking your medication?"',
      'Offering an open-ended prompt: "What was that like for you?"',
      'Saying, "Everything will be fine after surgery."',
    ],
    correctAnswers: [0, 1, 3],
    explanation:
      'Silence, restatement, and open-ended prompts invite the client’s story. "Why" questions demand defense of behavior, and blanket reassurance closes the conversation while promising what no one can guarantee — both are non-therapeutic.',
    verification: 'unverified',
  },
];

/** Part-1 combined export: dosage (calc-verified) + clinical topics 0-3. */
export const NCLEX_QUESTIONS: NclexQuestion[] = [
  ...NCLEX_DOSAGE_QUESTIONS,
  ...NCLEX_CLINICAL_QUESTIONS_1,
];
