/**
 * Patent Bar — WS3 gap-fill: Post-Issuance Proceedings (topicId 5).
 *
 * 44 AI-authored questions taking this blueprint section from 103 to its
 * TERMINAL size of 147 (see docs/monetization/PATENT_BAR_COVERAGE_MATRIX.md:
 * at the exact-proportion bank of 980 — the only state in which all six
 * blueprint floors hold simultaneously — post-issuance needs 147 questions).
 * Grounded in reissue practice (35 U.S.C. 251–252, 37 CFR 1.171–1.178,
 * MPEP 1400), certificates of correction and disclaimers (35 U.S.C.
 * 253–255, 37 CFR 1.321–1.323), maintenance fees (35 U.S.C. 41(b)–(c),
 * 37 CFR 1.362–1.378), ex parte reexamination (35 U.S.C. 301–307, MPEP
 * 2200), inter partes review (35 U.S.C. 311–319), post-grant review
 * (35 U.S.C. 321–329), and supplemental examination (35 U.S.C. 257).
 * All original compositions.
 *
 * VERIFICATION STATUS: every item here is 'unverified' (AI-authored,
 * pending SME review via /dashboard/test-prep/patent_bar/review-queue).
 * None may appear in a scored mock until reviewed. Answer keys are
 * deliberately balanced (A:9, B:9, C:9, D:9, E:8 — asserted by
 * qbank-key-balance.test.ts).
 */

import type { PatentBarQuestion } from './patent-bar-qbank-data';

export const PATENT_BAR_GAPFILL_POST_ISSUANCE: PatentBarQuestion[] = [
  {
    id: 'pb_gf5_001', topicId: 5, subtopic: 'reissue_grounds', difficulty: 1,
    question: 'Under 35 U.S.C. 251, a patent may be reissued when, through error, the patent is deemed wholly or partly inoperative or invalid:',
    options: [
      'For any reason, including invalidating prior art the examiner missed.',
      'Only because the claims are too narrow.',
      'By reason of a defective specification or drawing, or by reason of the patentee claiming more or less than the patentee had a right to claim.',
      'Only where the Office, not the applicant, caused the defect.',
      'Only within nine months of grant.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 251 authorizes reissue for ERROR making the patent wholly or partly inoperative or invalid via a defective specification or drawing, or via claiming MORE or LESS than the patentee was entitled to claim. Reissue corrects the patentee’s own errors — it is not a vehicle for relitigating examiner art misses generally, and (except for broadening) it has no fixed deadline.',
  },
  {
    id: 'pb_gf5_002', topicId: 5, subtopic: 'reissue_broadening', difficulty: 1,
    question: 'A reissue application that seeks to ENLARGE the scope of the claims of the original patent must be:',
    options: [
      'Applied for within TWO YEARS from the grant of the original patent.',
      'Applied for within nine months from grant.',
      'Applied for before any maintenance fee is due.',
      'Filed with the consent of all licensees.',
      'Filed only after a certificate of correction is refused.',
    ],
    correct: 0,
    explanation: 'The final sentence of 35 U.S.C. 251: no reissue broadening the scope of the claims may be applied for more than TWO YEARS after the original grant. A narrowing reissue may be filed at any time during the patent term; the two-year clock is strictly a broadening limit.',
  },
  {
    id: 'pb_gf5_003', topicId: 5, subtopic: 'reissue_broadening', difficulty: 2,
    question: 'For purposes of the two-year rule, a reissue claim "enlarges the scope" of the original claims if it:',
    options: [
      'Adds any limitation not present in the original claims.',
      'Merely rewords a claim without changing coverage.',
      'Covers fewer embodiments than the original claims.',
      'Increases the number of claims.',
      'Is broader than the original claims in ANY respect, even if narrower in others.',
    ],
    correct: 4,
    explanation: 'A claim is a broadening claim if it is broader in ANY respect than the original claims — even if simultaneously narrowed elsewhere. A claim that covers something the original claims did not cover enlarges scope; adding claims alone, or narrowing, does not.',
  },
  {
    id: 'pb_gf5_004', topicId: 5, subtopic: 'reissue_term', difficulty: 1,
    question: 'The term of a reissued patent is:',
    options: [
      'Twenty years from the reissue application’s filing date.',
      'The unexpired part of the ORIGINAL patent’s term — reissue neither extends nor restarts the term.',
      'Fifteen years from reissue grant.',
      'Reset to twenty years from reissue grant.',
      'Determined by the examiner based on the scope of the changes.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 251: the reissued patent is granted "for the unexpired part of the term of the original patent." Reissue fixes errors; it never adds term. (Maintenance fees likewise stay on the original patent’s schedule.)',
  },
  {
    id: 'pb_gf5_005', topicId: 5, subtopic: 'reissue_new_matter', difficulty: 2,
    question: 'During prosecution of a reissue application, the applicant seeks to add examples that were not in the original patent to support the reissue claims. This is:',
    options: [
      'Permitted, because the reissue specification may be perfected.',
      'Permitted if the examples existed at the original filing date.',
      'Permitted with a supplemental oath.',
      'Prohibited — 35 U.S.C. 251 expressly forbids introducing NEW MATTER into a reissue application.',
      'Permitted only in a broadening reissue.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 251(a): the reissue must be "for the invention disclosed in the original patent," and no new matter may be introduced. The reissue disclosure is confined to what the original patent disclosed; anything new belongs in a new application.',
  },
  {
    id: 'pb_gf5_006', topicId: 5, subtopic: 'reissue_recapture', difficulty: 2,
    question: 'In the original prosecution, the patentee narrowed claim 1 by adding a limitation to overcome a prior-art rejection. In a broadening reissue filed 18 months after grant, the patentee seeks to delete exactly that limitation. This is:',
    options: [
      'Proper, because the reissue was filed within two years.',
      'Barred by the RECAPTURE doctrine — reissue cannot be used to reacquire subject matter deliberately surrendered during the original prosecution to obtain allowance.',
      'Proper if the prior art is distinguished in a new declaration.',
      'Proper because recapture applies only to narrowing reissues.',
      'Barred only if litigation is pending.',
    ],
    correct: 1,
    explanation: 'The recapture rule bars reissue claims that reclaim subject matter surrendered to secure the original patent (MPEP 1412.02). Deliberate amendment or argument-based surrender to overcome art is not "error" under 251 — the two-year window does not cure recapture.',
  },
  {
    id: 'pb_gf5_007', topicId: 5, subtopic: 'reissue_intervening_rights', difficulty: 2,
    question: 'After a patent is reissued with substantively amended claims, a competitor who had been making a product covered by the NEW claims (but not the original ones) before the reissue date:',
    options: [
      'Is liable for infringement back to the original patent date.',
      'Is liable from the reissue date with treble damages.',
      'Must destroy existing inventory.',
      'Enjoys ABSOLUTE intervening rights as to specific things made before reissue (which may continue to be used or sold), and a court may additionally grant EQUITABLE intervening rights for continued practice where substantial preparations were made.',
      'Has no defense unless it obtained an opinion of counsel.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 252: claims not substantially identical to the originals take effect only from reissue grant. Absolute intervening rights protect specific articles made before reissue; equitable intervening rights let a court permit continued operations begun (or substantially prepared) before reissue. Claims carried over unchanged are enforceable continuously.',
  },
  {
    id: 'pb_gf5_008', topicId: 5, subtopic: 'reissue_oath', difficulty: 2,
    question: 'The reissue oath or declaration must:',
    options: [
      'Identify at least one error being relied upon as the basis for reissue (the AIA REMOVED the former requirement to aver that the error arose "without any deceptive intention").',
      'Aver that the error occurred without any deceptive intention, as the statute still requires.',
      'Be signed by the examiner of the original patent.',
      'List every error in the patent, however minor.',
      'Be accompanied by an opinion of counsel on validity.',
    ],
    correct: 0,
    explanation: '37 CFR 1.175: the reissue oath/declaration states that the applicant believes the patent defective and identifies at least one 251 error relied on. The AIA struck "without any deceptive intention" from 251 — no deceptive-intent averment survives. Every error need not be cataloged; one qualifying error suffices.',
  },
  {
    id: 'pb_gf5_009', topicId: 5, subtopic: 'reissue_grounds', difficulty: 3,
    question: 'After a restriction requirement in the original prosecution, the applicant elected one invention, never filed a divisional on the non-elected claims, and let the patent issue. A reissue application now seeking the non-elected claims is:',
    options: [
      'Proper, because failure to file a divisional is a classic 251 error.',
      'Proper if filed within two years of grant.',
      'Proper if the restriction requirement was erroneous.',
      'Proper only in an ex parte reexamination.',
      'Improper — under the Orita doctrine, failure to file a divisional on non-elected claims is not correctable "error" under 251.',
    ],
    correct: 4,
    explanation: 'In re Orita / MPEP 1412.01: seeking claims the applicant could have pursued in a divisional after restriction — but simply chose not to — is not the kind of error 251 reaches. The reissue claims would be for a non-elected invention, not the invention of the original patent.',
  },
  {
    id: 'pb_gf5_010', topicId: 5, subtopic: 'reissue_grounds', difficulty: 2,
    question: 'A patentee discovers the issued patent never claimed the foreign priority to which it was entitled. This may be corrected by:',
    options: [
      'A statutory disclaimer.',
      'A maintenance-fee filing.',
      'A reissue application (or, where the requirements are met, a certificate of correction under 37 CFR 1.55) — failure to make or perfect a priority claim is a recognized correctable defect.',
      'Nothing — priority is fixed at issuance forever.',
      'A new original application claiming the same priority.',
    ],
    correct: 2,
    explanation: 'MPEP 1402/1417: among the recognized reissue-correctable defects is the failure to make, or to perfect, a claim to foreign priority. (In limited circumstances 37 CFR 1.55(g) permits a certificate-of-correction route.) Disclaimers and maintenance filings have nothing to do with priority.',
  },
  {
    id: 'pb_gf5_011', topicId: 5, subtopic: 'reissue_procedure', difficulty: 2,
    question: 'The original letters patent, once a reissue application is filed:',
    options: [
      'Are canceled immediately upon the reissue filing.',
      'Remain enforceable even after the reissue grants.',
      'Must be litigated in parallel.',
      'Are transferred to the reissue examiner for destruction.',
      'Are the subject of an OFFER TO SURRENDER — the original patent is deemed surrendered, effective only upon the GRANT of the reissue patent.',
    ],
    correct: 4,
    explanation: '37 CFR 1.178: the reissue application includes an offer to surrender the original patent, and surrender takes effect when the reissue issues. Until then the original patent stands — if the reissue is abandoned or refused, the original patent remains as it was.',
  },
  {
    id: 'pb_gf5_012', topicId: 5, subtopic: 'reissue_procedure', difficulty: 3,
    question: 'Which is TRUE about the mechanics of reissue prosecution?',
    options: [
      'Reissue applications are examined in secret.',
      'Only the changed claims may be examined.',
      'A reissue application is examined like a regular application (all claims, any ground of rejection), is open to public inspection, and continuations or divisionals of a reissue — including multiple reissues of one patent — are permitted.',
      'The claims enjoy a presumption of validity during reissue examination.',
      'Third parties may file oppositions in a reissue.',
    ],
    correct: 2,
    explanation: 'Reissue reopens full examination — every claim is examinable on any statutory ground, the file is open to the public (MPEP 1430 announcements invite submissions of pertinent art), and reissue families (continuation/divisional reissues, multiple reissues of one patent) are recognized practice (MPEP 1451).',
  },
  {
    id: 'pb_gf5_013', topicId: 5, subtopic: 'certificate_correction', difficulty: 1,
    question: 'A mistake in a patent that is clearly attributable to the USPTO (for example, a printing error) is corrected by:',
    options: [
      'A reissue application with fee.',
      'An ex parte reexamination.',
      'A petition to the Director with fee.',
      'A certificate of correction under 35 U.S.C. 254 — issued WITHOUT a fee, at the Office’s initiative or at the patentee’s request.',
      'A terminal disclaimer.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 254/37 CFR 1.322: Office mistakes are corrected by certificate of correction at NO fee. Compare 255: correcting the APPLICANT’s own clerical or typographical mistake requires the fee.',
  },
  {
    id: 'pb_gf5_014', topicId: 5, subtopic: 'certificate_correction', difficulty: 2,
    question: 'A certificate of correction for a mistake made by the APPLICANT is available under 35 U.S.C. 255 when the mistake:',
    options: [
      'Is of a clerical or typographical nature or of minor character, occurred in good faith, and its correction does not involve new matter or require reexamination.',
      'Broadens the claims by less than ten percent.',
      'Was caused by the applicant’s prior attorney.',
      'Is discovered within two years of grant.',
      'Relates only to the drawings.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 255 has four working conditions: clerical/typographical/minor character, good faith, and — as construed — the correction must not constitute new matter nor require reexamination. Substantive changes are reissue territory; there is no two-year limit on certificates.',
  },
  {
    id: 'pb_gf5_015', topicId: 5, subtopic: 'certificate_correction', difficulty: 2,
    question: 'A patentee wants to fix an issued claim by deleting a limitation, modestly broadening the claim. A certificate of correction:',
    options: [
      'Is proper if the change is small.',
      'Is NOT available — a certificate of correction cannot make substantive changes to claim scope; a broadening change requires a broadening reissue within two years of grant.',
      'Is proper with the patentee’s good-faith declaration.',
      'Is proper if all claims are corrected consistently.',
      'Is proper upon payment of a broadening surcharge.',
    ],
    correct: 1,
    explanation: 'Certificates of correction handle clerical/typographical/minor matters that change neither scope nor substance. Deleting a claim limitation broadens the claim — that demands a reissue under 251, and because it broadens, the reissue must be applied for within two years of the original grant.',
  },
  {
    id: 'pb_gf5_016', topicId: 5, subtopic: 'disclaimers', difficulty: 2,
    question: 'A patentee concludes that claims 5–7 of its issued patent are invalid over newly found prior art, and wishes to formally give them up while keeping the rest of the patent. The proper mechanism is:',
    options: [
      'A STATUTORY DISCLAIMER under 35 U.S.C. 253 disclaiming those complete claims, filed with the required fee and recorded in the Office.',
      'A certificate of correction deleting the claims.',
      'Abandonment of the entire patent.',
      'An amendment under 37 CFR 1.312.',
      'A reissue adding narrower claims while ignoring the invalid ones.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 253(a): a patentee may disclaim any complete claim(s); the disclaimer is filed and recorded, and the patent is treated as though the disclaimed claims never existed. Certificates of correction cannot cancel claims, and 1.312 amendments apply only to pending applications.',
  },
  {
    id: 'pb_gf5_017', topicId: 5, subtopic: 'disclaimers', difficulty: 2,
    question: 'To be effective in overcoming an obviousness-type double patenting rejection, a terminal disclaimer must, in addition to disclaiming the terminal part of the term:',
    options: [
      'Be signed by all inventors personally.',
      'Disclaim at least one complete claim as well.',
      'Be filed before the first Office action.',
      'Be approved by the Patent Trial and Appeal Board.',
      'Include the provision that the patent will be enforceable only while it and the reference patent/application are COMMONLY OWNED (37 CFR 1.321(c)-(d)).',
    ],
    correct: 4,
    explanation: 'The 1.321(c)/(d) common-ownership enforcement clause is what prevents the harassment-by-multiple-assignees problem that underlies obviousness-type double patenting. A bare term disclaimer without the clause does not cure ODP.',
  },
  {
    id: 'pb_gf5_018', topicId: 5, subtopic: 'maintenance_fees', difficulty: 1,
    question: 'Maintenance fees on a utility patent are due:',
    options: [
      'Annually on the grant anniversary.',
      'At 3.5, 7.5, and 11.5 years after grant — each payable without surcharge in the six-month window preceding the due date.',
      'At 4, 8, and 12 years after filing.',
      'Only if the patent is licensed.',
      'At 5 and 10 years after grant.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 41(b)/37 CFR 1.362: three maintenance fees, due 3.5, 7.5, and 11.5 years from grant, each payable in the preceding six-month window (3–3.5, 7–7.5, 11–11.5 years) without surcharge.',
  },
  {
    id: 'pb_gf5_019', topicId: 5, subtopic: 'maintenance_fees', difficulty: 2,
    question: 'A patentee misses the 7.5-year maintenance fee due date. The patent:',
    options: [
      'Expires immediately.',
      'Remains in force for one more year automatically.',
      'May still be maintained by paying the fee WITH A SURCHARGE during the six-month grace period; if the fee is not paid by the end of the grace period, the patent expires as of the end of that period (the 8-year mark).',
      'Enters reexamination automatically.',
      'Is transferred to the public domain after 30 days.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 41(b)(2)/37 CFR 1.362(e): a six-month grace period with surcharge follows each due date. Unpaid at the end of grace, the patent expires as of that date (4, 8, or 12 years from grant). The USPTO is not obligated to send reminders.',
  },
  {
    id: 'pb_gf5_020', topicId: 5, subtopic: 'maintenance_fees', difficulty: 2,
    question: 'A patent expired for nonpayment of a maintenance fee. Reinstatement is available:',
    options: [
      'Never — expiration for nonpayment is final.',
      'Only within one year of expiration.',
      'Only upon proof the USPTO failed to send a reminder.',
      'By petition under 37 CFR 1.378 with the maintenance fee and petition fee, upon a statement that the delay in payment was UNINTENTIONAL.',
      'By filing a reissue application.',
    ],
    correct: 3,
    explanation: '37 CFR 1.378(b): the Director may accept late payment where the delay was unintentional (the separate "unavoidable" standard was eliminated in 2013). The petition includes the fee, surcharge, and unintentional-delay statement; extended delays may require additional explanation.',
  },
  {
    id: 'pb_gf5_021', topicId: 5, subtopic: 'maintenance_fees', difficulty: 3,
    question: 'During the period a patent stood expired for nonpayment (before it was reinstated), a competitor began manufacturing the patented product. After reinstatement, the competitor:',
    options: [
      'Is liable for infringement during the lapse.',
      'Must pay a compulsory royalty for the lapse period.',
      'Loses any defense once the patent is reinstated.',
      'Is protected by INTERVENING RIGHTS under 35 U.S.C. 41(c)(2) — the court may protect use, purchases, and business begun (or substantially prepared) during the lapse, similar to reissue intervening rights.',
      'May continue only if it files a protest.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 41(c)(2) creates intervening rights paralleling 252: things made/purchased/used during the expiration period, and continued practice where substantial preparation occurred, may be protected notwithstanding reinstatement — the reliance interest of those who acted while the patent stood expired.',
  },
  {
    id: 'pb_gf5_022', topicId: 5, subtopic: 'maintenance_fees', difficulty: 2,
    question: 'Maintenance fees are required for:',
    options: [
      'All issued patents.',
      'Utility patents (including reissues of utility patents, on the ORIGINAL patent’s schedule) — but not design patents, plant patents, or (for applications filed before certain dates) statutory exceptions.',
      'Design and plant patents only.',
      'Utility patents only during their first ten years.',
      'Any patent that has been licensed or asserted.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 41(b): maintenance fees attach to utility patents. A reissued utility patent stays on the original patent’s 3.5/7.5/11.5 schedule (37 CFR 1.362(b)). Design and plant patents never pay maintenance fees.',
  },
  {
    id: 'pb_gf5_023', topicId: 5, subtopic: 'ex_parte_reexam', difficulty: 1,
    question: 'A request for EX PARTE reexamination may be filed by:',
    options: [
      'Only a party sued for infringement.',
      'Only the patent owner.',
      'ANY person — including the patent owner, a competitor, or an anonymous real party filing through an attorney — at any time during the patent’s period of enforceability.',
      'Only the Director.',
      'Only a licensee in good standing.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 302: "Any person at any time may file a request for reexamination." Unlike IPR, the real party in interest need not be identified, so ex parte requests can be effectively anonymous; the Director may also order reexamination sua sponte (35 U.S.C. 303(a)).',
  },
  {
    id: 'pb_gf5_024', topicId: 5, subtopic: 'ex_parte_reexam', difficulty: 1,
    question: 'The ONLY prior art that can support an ex parte reexamination request is:',
    options: [
      'Public uses and sales.',
      'Expert declarations about the state of the art.',
      'Evidence of derivation.',
      'Any evidence admissible in district court.',
      'Prior PATENTS and PRINTED PUBLICATIONS bearing on patentability under 35 U.S.C. 102 and 103.',
    ],
    correct: 4,
    explanation: '35 U.S.C. 301/302: reexamination is built on patents and printed publications only. On-sale activity, public use, and 112 issues cannot be raised (contrast PGR, where any 282(b) invalidity ground is available).',
  },
  {
    id: 'pb_gf5_025', topicId: 5, subtopic: 'ex_parte_reexam', difficulty: 2,
    question: 'Within three months of an ex parte reexamination request, the Director must determine whether the request raises:',
    options: [
      'A SUBSTANTIAL NEW QUESTION OF PATENTABILITY (SNQ) affecting any claim — if so, reexamination is ordered; a denial refunds part of the fee and is not appealable by the requester.',
      'A reasonable likelihood that the requester would prevail.',
      'Clear and convincing evidence of invalidity.',
      'A prima facie case of unenforceability.',
      'More-likely-than-not unpatentability.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 303(a): the SNQ standard, decided within 3 months. "Reasonable likelihood of prevailing" is the IPR institution threshold and "more likely than not" is PGR’s — keeping the three thresholds straight is a favorite exam point.',
  },
  {
    id: 'pb_gf5_026', topicId: 5, subtopic: 'ex_parte_reexam', difficulty: 2,
    question: 'After ex parte reexamination is ordered, the third-party requester’s participation:',
    options: [
      'Continues throughout, like inter partes review.',
      'Includes oral argument before the examiner.',
      'Is limited to ONE reply — if the patent owner files an optional statement (due within two months of the order), the requester may reply within two months; after that, the proceeding is entirely ex parte between the Office and the patent owner.',
      'Ends immediately upon the order.',
      'Includes the right to appeal an adverse result.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 304: owner statement (optional, 2 months), single requester reply (2 months from the statement), then the third party is out. That is the "ex parte" in ex parte reexamination — and the requester has no appeal (35 U.S.C. 306 gives appeal rights to the patent owner only).',
  },
  {
    id: 'pb_gf5_027', topicId: 5, subtopic: 'ex_parte_reexam', difficulty: 2,
    question: 'During ex parte reexamination, the patent owner amends claims. The amendments:',
    options: [
      'May broaden the claims if filed within two years of grant.',
      'May broaden if supported by the original disclosure.',
      'Are prohibited entirely.',
      'Must be entered without examination.',
      'May NARROW or clarify but may NOT enlarge the scope of the claims — and claims amended or added in reexamination carry intervening rights under 35 U.S.C. 307(b).',
    ],
    correct: 4,
    explanation: '35 U.S.C. 305: no proposed amended or new claim enlarging scope is permitted in reexamination (the two-year broadening window belongs to REISSUE). Amended/new claims that emerge from reexam get 252-style intervening rights via 307(b).',
  },
  {
    id: 'pb_gf5_028', topicId: 5, subtopic: 'ex_parte_reexam', difficulty: 3,
    question: 'Which is TRUE about how claims are treated during ex parte reexamination of an unexpired patent?',
    options: [
      'Claims are given their BROADEST REASONABLE INTERPRETATION consistent with the specification, there is no presumption of validity before the examiner, and the proceeding is conducted with SPECIAL DISPATCH.',
      'Claims are construed as a district court would, with a presumption of validity.',
      'Claims are construed narrowly to preserve validity.',
      'The examiner must defer to any prior court construction.',
      'The proceeding follows ordinary examination timelines.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 305 commands special dispatch; in reexamination of unexpired patents the Office applies BRI and no presumption of validity — the Office is reassessing patentability, not adjudicating infringement. (For an expired patent, whose claims can no longer be amended, a district-court-style construction is used.)',
  },
  {
    id: 'pb_gf5_029', topicId: 5, subtopic: 'ex_parte_reexam', difficulty: 2,
    question: 'At the close of an ex parte reexamination that confirms some claims and cancels others, the Office:',
    options: [
      'Reissues the patent with a new term.',
      'Publishes a notice in the Federal Register only.',
      'Requires the owner to file a disclaimer.',
      'Issues a REEXAMINATION CERTIFICATE canceling unpatentable claims, confirming patentable claims, and incorporating any amended or new claims into the patent.',
      'Vacates the original grant entirely.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 307(a): the proceeding ends with a certificate — cancellation of claims held unpatentable, confirmation of claims held patentable, and incorporation of amended/new claims (those carrying intervening rights under 307(b)). The patent’s term is unaffected.',
  },
  {
    id: 'pb_gf5_030', topicId: 5, subtopic: 'prior_art_citation', difficulty: 2,
    question: 'Under 35 U.S.C. 301, any person may cite to the Office, for placement in a patent’s file:',
    options: [
      'Physical samples of prior-art products.',
      'Prior art consisting of PATENTS or PRINTED PUBLICATIONS believed to bear on patentability, and/or statements of the PATENT OWNER filed in a federal court or Office proceeding taking a position on claim scope.',
      'Expert opinions on obviousness.',
      'Confidential sales records.',
      'Evidence of the owner’s inequitable conduct.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 301(a): citable material is (1) patents/printed publications and (2) patent-owner claim-scope statements from federal court or USPTO proceedings (an AIA addition, usable for claim construction in later Office proceedings). The citing party may request anonymity; the citation alone triggers no proceeding.',
  },
  {
    id: 'pb_gf5_031', topicId: 5, subtopic: 'ipr', difficulty: 1,
    question: 'A petition for INTER PARTES REVIEW may be filed by:',
    options: [
      'Anyone, including the patent owner seeking to strengthen its claims.',
      'A person who is NOT the patent owner, challenging claims only under 35 U.S.C. 102 or 103 and only on the basis of prior art consisting of patents or printed publications.',
      'Only a defendant already sued for infringement.',
      'Only the Director.',
      'Any person, on any invalidity ground including 35 U.S.C. 101 and 112.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 311(a)-(b): the petitioner must not own the patent, and IPR grounds are limited to anticipation/obviousness over patents and printed publications. Eligibility (101) and definiteness/enablement (112) challenges belong to PGR — not IPR.',
  },
  {
    id: 'pb_gf5_032', topicId: 5, subtopic: 'ipr', difficulty: 2,
    question: 'An IPR petition may be filed:',
    options: [
      'Only after the LATER of nine months from the patent’s grant, or the termination of any post-grant review of the patent.',
      'At any time, including the day the patent issues.',
      'Only within nine months of grant.',
      'Only after a district court finds infringement.',
      'Only within one year of grant.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 311(c): IPR waits out the PGR window — the petition comes after the later of 9 months post-grant or PGR termination. (The 9-month wait is the mirror image of PGR, which must be filed WITHIN 9 months of grant.)',
  },
  {
    id: 'pb_gf5_033', topicId: 5, subtopic: 'ipr', difficulty: 2,
    question: 'A company was served with a complaint alleging infringement of a patent on March 1 of last year. This year, 14 months after service, the company petitions for IPR of that patent. The petition is:',
    options: [
      'Timely, because IPR has no service-based deadline.',
      'Timely if the litigation is stayed.',
      'Timely if joined with an existing IPR filed by another party (joinder is an exception the Director may allow) — otherwise BARRED by 35 U.S.C. 315(b), which requires filing within ONE YEAR of service of the complaint.',
      'Barred forever, with no exceptions of any kind.',
      'Converted automatically to a PGR.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 315(b): an IPR petition filed more than 1 year after the petitioner (or a real party in interest or privy) was served with an infringement complaint is barred — but the time bar does not apply to a request for JOINDER under 315(c). Also remember 315(a): a petitioner who earlier filed a civil action challenging validity is barred outright.',
  },
  {
    id: 'pb_gf5_034', topicId: 5, subtopic: 'ipr', difficulty: 2,
    question: 'The threshold for INSTITUTING inter partes review is:',
    options: [
      'A substantial new question of patentability.',
      'More-likely-than-not unpatentability of at least one claim.',
      'A REASONABLE LIKELIHOOD that the petitioner would prevail with respect to at least one challenged claim.',
      'Clear and convincing evidence of anticipation.',
      'Probable cause found by the Director personally.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 314(a): institution requires a reasonable likelihood of petitioner success on at least one claim. Compare: SNQ (ex parte reexam) and more-likely-than-not (PGR). Institution decisions are final and nonappealable (314(d)).',
  },
  {
    id: 'pb_gf5_035', topicId: 5, subtopic: 'ipr', difficulty: 2,
    question: 'After an IPR reaches a FINAL WRITTEN DECISION, the petitioner (and its real parties in interest and privies):',
    options: [
      'May relitigate the same art in district court.',
      'Is estopped only as to claims that were canceled.',
      'May file unlimited follow-on IPR petitions on new art.',
      'Faces no estoppel unless the PTAB says so expressly.',
      'Is ESTOPPED — before the Office, the district courts, and the ITC — from asserting invalidity on any ground the petitioner RAISED OR REASONABLY COULD HAVE RAISED during the IPR.',
    ],
    correct: 4,
    explanation: '35 U.S.C. 315(e): final-written-decision estoppel covers grounds raised or reasonably could have been raised, and applies in Office proceedings, civil actions, and ITC proceedings alike. It attaches per-claim upon the FWD — one of the most consequential strategic features of IPR.',
  },
  {
    id: 'pb_gf5_036', topicId: 5, subtopic: 'ipr', difficulty: 2,
    question: 'Once instituted, an inter partes review is conducted by:',
    options: [
      'A patent examiner in the reexamination unit.',
      'The Commissioner for Patents.',
      'A district judge detailed to the Office.',
      'The Central Reexamination Unit with PTAB oversight.',
      'The Patent Trial and Appeal Board, which must ordinarily issue its final written decision within ONE YEAR of institution (extendable up to six months for good cause).',
    ],
    correct: 4,
    explanation: '35 U.S.C. 316(a)(11)/318: IPRs are PTAB trials on a statutory clock — final written decision within 12 months of institution, extendable once by up to 6 months for good cause. Appeal from the FWD goes to the Federal Circuit.',
  },
  {
    id: 'pb_gf5_037', topicId: 5, subtopic: 'ipr', difficulty: 3,
    question: 'During an IPR, the patent owner wishes to change its claims. The owner may:',
    options: [
      'Amend freely, as in ex parte prosecution.',
      'Broaden the claims to capture the petitioner’s product.',
      'Not amend at all — IPR claims are frozen.',
      'File ONE MOTION TO AMEND proposing a reasonable number of SUBSTITUTE claims, which may not enlarge claim scope or introduce new matter (additional motions only by agreement or for good cause).',
      'Amend only by filing a co-pending reissue — which is prohibited during IPR.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 316(d): one motion to amend, substitute claims, no broadening, no new matter. (A parallel reissue or reexamination is not prohibited — the Office coordinates them — but the in-IPR mechanism is the 316(d) motion.)',
  },
  {
    id: 'pb_gf5_038', topicId: 5, subtopic: 'pgr', difficulty: 2,
    question: 'A petition for POST-GRANT REVIEW must be filed:',
    options: [
      'Within one year of service of an infringement complaint.',
      'At any time during the patent’s enforceability.',
      'Within NINE MONTHS of the patent’s grant (or of a broadening reissue’s grant), and only against patents subject to the AIA first-inventor-to-file regime.',
      'After the patent’s first maintenance fee.',
      'Within nine months of the first commercial sale.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 321(c): the PGR window is the first 9 months after grant, and PGR reaches only first-inventor-to-file (AIA) patents. After the window closes, IPR (with its narrower grounds) becomes the PTAB route.',
  },
  {
    id: 'pb_gf5_039', topicId: 5, subtopic: 'pgr', difficulty: 2,
    question: 'The grounds available in post-grant review include:',
    options: [
      'Only anticipation and obviousness over patents and printed publications.',
      'ANY invalidity ground that could be raised under 35 U.S.C. 282(b)(2) or (3) — including 101 subject-matter eligibility, 102, 103, and 112 (except best mode) — plus on-sale and public-use prior art.',
      'Inequitable conduct.',
      'Improper inventorship only.',
      'Antitrust misuse of the patent.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 321(b): PGR is the broad-grounds proceeding — eligibility, novelty (including sales and public uses), obviousness, written description, enablement, and definiteness (best mode is excluded as a defense by 282(b)(3)(A)). Unenforceability theories like inequitable conduct are not within PTAB review.',
  },
  {
    id: 'pb_gf5_040', topicId: 5, subtopic: 'pgr', difficulty: 3,
    question: 'The threshold for instituting post-grant review is that the petition demonstrates:',
    options: [
      'That it is MORE LIKELY THAN NOT that at least one challenged claim is unpatentable — or, alternatively, that the petition raises a novel or unsettled legal question important to other patents or applications.',
      'A reasonable likelihood of prevailing on one claim.',
      'A substantial new question of patentability.',
      'Irreparable harm to the petitioner.',
      'A certified refusal from the examiner corps.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 324(a)-(b): PGR institution requires more-likely-than-not unpatentability of at least one claim, or a novel/unsettled legal question of importance beyond the case. This is a HIGHER bar than IPR’s reasonable-likelihood standard — the price of PGR’s broader grounds.',
  },
  {
    id: 'pb_gf5_041', topicId: 5, subtopic: 'supplemental_exam', difficulty: 2,
    question: 'Supplemental examination under 35 U.S.C. 257 may be requested by:',
    options: [
      'ONLY the patent owner, asking the Office to consider, reconsider, or correct information believed relevant to the patent — and the information is NOT limited to patents and printed publications.',
      'Any person, like ex parte reexamination.',
      'Only an accused infringer.',
      'Only the Director sua sponte.',
      'Licensees with the owner’s consent.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 257(a): supplemental examination is an owner-only tool, and unlike reexamination its "information" can be anything relevant — sales activity, 112 issues, declarations — not just patents and printed publications. The Office decides within 3 months whether any item raises a substantial new question.',
  },
  {
    id: 'pb_gf5_042', topicId: 5, subtopic: 'supplemental_exam', difficulty: 3,
    question: 'The principal strategic benefit of supplemental examination is that:',
    options: [
      'It stays all pending litigation automatically.',
      'A patent shall NOT be held unenforceable for inequitable conduct based on information that was considered, reconsidered, or corrected in a supplemental examination — subject to exceptions for allegations already pled before the request and defenses raised in actions filed before it concludes (and material fraud may be referred to the Attorney General).',
      'It broadens claims without the two-year limit.',
      'It permanently bars any reexamination of the patent.',
      'It erases prior art from the record.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 257(c): the inoculation effect — curing would-be inequitable-conduct problems by putting the information before the Office. The carve-outs matter: allegations already particularized (e.g., in a pleading or ANDA notice) before the request, and defenses in litigation/ITC actions brought before completion, are not immunized; fraud can be referred out.',
  },
  {
    id: 'pb_gf5_043', topicId: 5, subtopic: 'supplemental_exam', difficulty: 3,
    question: 'If the supplemental examination certificate states that a substantial new question of patentability IS raised by an item of information:',
    options: [
      'The patent is immediately held invalid.',
      'The owner has three months to respond before any action.',
      'The Director ORDERS EX PARTE REEXAMINATION of the patent, conducted under the reexamination rules EXCEPT that the patent owner may not file the usual initial statement, and the reexamination is not limited to patents and printed publications.',
      'A post-grant review is instituted automatically.',
      'The certificate simply notes the question with no further proceeding.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 257(b): an SNQ found in supplemental examination triggers a Director-ordered ex parte reexamination — but a modified one: no 304 patent-owner statement, and the reexamination can address the full range of information (not just patents/printed publications), since the underlying request was not so limited.',
  },
  {
    id: 'pb_gf5_044', topicId: 5, subtopic: 'ipr', difficulty: 2,
    question: 'The petitioner and patent owner in an instituted IPR reach a settlement before the Board decides the merits. The proceeding:',
    options: [
      'Must continue to a final written decision regardless.',
      'Terminates only if the Director personally approves.',
      'Continues with the Director substituted as petitioner in every case.',
      'Is TERMINATED as to the petitioner upon their joint request (the settlement must be in writing and filed), and no 315(e) estoppel attaches to that petitioner — though the Office MAY proceed to a decision if the merits are already decided or in appropriate cases.',
      'Converts to an ex parte reexamination.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 317: joint-request termination is available before the Office decides the merits; the written settlement is filed with the Office, and a petitioner who settles out avoids final-written-decision estoppel. The Board retains discretion to proceed to a decision where the case is effectively complete.',
  },
];
