/**
 * Patent Bar — WS3 gap-fill: PCT & International Filing (topicId 4).
 *
 * 40 AI-authored questions taking this blueprint section from 58 to its
 * TERMINAL size of 98 (see docs/monetization/PATENT_BAR_COVERAGE_MATRIX.md:
 * at the exact-proportion bank of 980 — the only state in which all six
 * blueprint floors hold simultaneously — PCT needs 98 questions). Grounded
 * in the Patent Cooperation Treaty (Articles 11, 19, 21, 22, 34; Rules
 * 26bis, 46, 54bis, 90bis, 91), 35 U.S.C. 351–376 (esp. 363, 365, 371),
 * 37 CFR 1.401–1.499, and MPEP Chapter 1800. All original compositions.
 *
 * VERIFICATION STATUS: every item here is 'unverified' (AI-authored,
 * pending SME review via /dashboard/test-prep/patent_bar/review-queue).
 * None may appear in a scored mock until reviewed. Answer keys are
 * deliberately balanced (exactly 8 per option position — asserted by
 * qbank-key-balance.test.ts).
 */

import type { PatentBarQuestion } from './patent-bar-qbank-data';

export const PATENT_BAR_GAPFILL_PCT: PatentBarQuestion[] = [
  {
    id: 'pb_gf4_001', topicId: 4, subtopic: 'pct_basics', difficulty: 1,
    question: 'Filing an international application under the Patent Cooperation Treaty (PCT):',
    options: [
      'Results in a single "international patent" enforceable in all contracting states.',
      'Grants provisional patent rights in every contracting state immediately upon filing.',
      'Secures a single international filing date having effect in all PCT contracting states, but patents are still granted (or refused) only by the individual national and regional offices.',
      'Eliminates the need to pay any national filing fees later.',
      'Is available only for inventions first patented in the United States.',
    ],
    correct: 2,
    explanation: 'The PCT centralizes FILING, search, publication, and optional preliminary examination — one application with one filing date effective in every contracting state. There is no international patent: after the international phase, the applicant enters the national phase in the offices where protection is desired, and each office grants or refuses on its own.',
  },
  {
    id: 'pb_gf4_002', topicId: 4, subtopic: 'pct_filing_date', difficulty: 2,
    question: 'Under PCT Article 11, a receiving Office accords an international filing date when, at a minimum, the application contains an indication that it is intended as an international application, the applicant has the required nationality/residence, it is in the prescribed language, and it includes:',
    options: [
      'The name of the applicant, a part that appears to be a description, and a part that appears to be a claim.',
      'The name of the applicant, an abstract, and formal drawings.',
      'The full filing fee, a description, and at least three claims.',
      'A certified priority document and a description.',
      'An oath or declaration, a description, and a claim.',
    ],
    correct: 0,
    explanation: 'Article 11(1) filing-date elements: intent that it be an international application, applicant entitlement, prescribed language, the applicant’s name, a part appearing to be a description, and a part appearing to be a claim. Fees, the abstract, drawings, the oath, and the priority document are NOT filing-date requirements — they are furnished or invited later.',
  },
  {
    id: 'pb_gf4_003', topicId: 4, subtopic: 'pct_filing_date', difficulty: 2,
    question: 'An applicant transmits an international application to the RO/US consisting of a request, a description, and drawings — but no claims — along with all fees. The receiving Office will:',
    options: [
      'Accord the transmittal date as the international filing date, since fees were paid.',
      'Accord the filing date but require claims within two months.',
      'Treat the application as a U.S. provisional application.',
      'Forward the papers to the International Bureau for a filing-date decision.',
      'Not accord an international filing date until at least one claim is furnished — the filing date becomes the date the claim is received.',
    ],
    correct: 4,
    explanation: 'A part appearing to be a CLAIM is an Article 11 filing-date requirement for international applications (unlike a U.S. national application under the PLT-amended rules, and unlike a provisional). The defect is invited to be corrected, and the international filing date becomes the date the missing element arrives.',
  },
  {
    id: 'pb_gf4_004', topicId: 4, subtopic: 'pct_receiving_office', difficulty: 1,
    question: 'The USPTO is a competent receiving Office (RO/US) for an international application when:',
    options: [
      'Any applicant, of any nationality, chooses to file there.',
      'At least one applicant is a United States national or resident (any applicant may instead file with the International Bureau as receiving Office).',
      'All applicants are U.S. nationals.',
      'The invention was made in the United States, regardless of the applicants.',
      'A corresponding U.S. nonprovisional application is already pending.',
    ],
    correct: 1,
    explanation: '37 CFR 1.412/1.421: RO/US is competent if at least one applicant is a U.S. national or resident. The International Bureau is an alternative receiving Office available to nationals/residents of any contracting state. Where the invention was MADE controls the foreign-filing-license question, not RO competence.',
  },
  {
    id: 'pb_gf4_005', topicId: 4, subtopic: 'pct_priority', difficulty: 1,
    question: 'An international application may claim the right of priority of an earlier application filed:',
    options: [
      'Within 6 months, as with design applications.',
      'Within 18 months, matching the publication timeline.',
      'Within 24 months, matching the Chapter II demand deadline.',
      'Within 12 months — including priority based on an earlier U.S. provisional or nonprovisional application.',
      'Only from an earlier foreign application, never a U.S. one.',
    ],
    correct: 3,
    explanation: 'The Paris Convention 12-month priority period applies to PCT filings, and the earlier application may be any regular national filing — including a U.S. provisional or nonprovisional. Most PCT deadlines (publication at 18 months, national phase at 30 months) are then measured from that priority date.',
  },
  {
    id: 'pb_gf4_006', topicId: 4, subtopic: 'pct_publication', difficulty: 1,
    question: 'An international application is published by the International Bureau:',
    options: [
      'Six months after the international filing date.',
      'Promptly after the expiration of 18 months from the priority date (or from the international filing date if no priority is claimed).',
      'Only after the applicant enters the national phase.',
      'Only if the applicant requests publication and pays a fee.',
      'By each designated Office separately.',
    ],
    correct: 1,
    explanation: 'PCT Article 21(2)(a): the IB publishes the international application promptly after 18 months from the priority date. Publication is automatic and centralized at WIPO — no request is needed (a request accelerates it; withdrawal before technical preparations are complete prevents it).',
  },
  {
    id: 'pb_gf4_007', topicId: 4, subtopic: 'pct_isr', difficulty: 2,
    question: 'The International Searching Authority (ISA) establishes for each international application:',
    options: [
      'A binding decision on patentability in all designated states.',
      'A certificate of novelty.',
      'An examination on the merits with claim rejections.',
      'An international search report (listing relevant prior art) together with a written opinion on novelty, inventive step, and industrial applicability.',
      'A national search report for the receiving Office only.',
    ],
    correct: 3,
    explanation: 'The ISA produces the ISR — citations of relevant prior art documents — plus a non-binding written opinion on the Article 33 criteria. It is not an examination on the merits and binds no office; if no Chapter II demand is filed, the written opinion later becomes the International Preliminary Report on Patentability (Chapter I).',
  },
  {
    id: 'pb_gf4_008', topicId: 4, subtopic: 'pct_amendments', difficulty: 2,
    question: 'An amendment under PCT Article 19:',
    options: [
      'Is limited to the CLAIMS and is filed with the International Bureau after the international search report is established.',
      'May amend the description, claims, and drawings, and is filed with the receiving Office.',
      'May amend only the abstract.',
      'Is filed with the International Preliminary Examining Authority together with a demand.',
      'Is unavailable if the application claims priority.',
    ],
    correct: 0,
    explanation: 'Article 19 permits ONE amendment of the CLAIMS ONLY, filed directly with the International Bureau after receipt of the ISR (it may be accompanied by a brief statement). Amendments to the description and drawings belong to Article 34, made before the IPEA during Chapter II examination.',
  },
  {
    id: 'pb_gf4_009', topicId: 4, subtopic: 'pct_chapter2', difficulty: 2,
    question: 'A demand for international preliminary examination (Chapter II) must be filed within:',
    options: [
      '19 months from the priority date, in all cases.',
      '2 months from the international filing date.',
      '16 months from the priority date.',
      '30 months from the priority date.',
      'The later of 3 months from the transmittal of the international search report and written opinion, or 22 months from the priority date.',
    ],
    correct: 4,
    explanation: 'PCT Rule 54bis: the demand deadline is the LATER of (a) 3 months from transmittal of the ISR and written opinion or (b) 22 months from the priority date. Since the 2002 Article 22 change, the 30-month U.S. national-stage deadline applies whether or not a demand is filed — the old 19-month "demand to get 30 months" practice is obsolete.',
  },
  {
    id: 'pb_gf4_010', topicId: 4, subtopic: 'pct_amendments', difficulty: 2,
    question: 'Amendments under PCT Article 34 differ from Article 19 amendments in that Article 34 amendments:',
    options: [
      'Are limited to the claims.',
      'Are filed with the designated Offices directly.',
      'May amend the description, claims, AND drawings, and are made before the International Preliminary Examining Authority during Chapter II examination.',
      'Are permitted only before the international search report issues.',
      'Require the consent of all designated Offices.',
    ],
    correct: 2,
    explanation: 'Article 34(2)(b) allows amendment of the description, claims, and drawings before the IPEA — the vehicle for arguing and amending in response to the written opinion during Chapter II. Article 19 is the narrower claims-only, IB-filed amendment. Neither may add subject matter beyond the disclosure as filed.',
  },
  {
    id: 'pb_gf4_011', topicId: 4, subtopic: 'pct_national_stage', difficulty: 1,
    question: 'To enter the U.S. national stage under 35 U.S.C. 371, the applicant must act by:',
    options: [
      '20 months from the priority date.',
      '12 months from the international filing date.',
      '18 months from the priority date.',
      '36 months from the priority date.',
      '30 months from the priority date (or from the international filing date if no priority was claimed).',
    ],
    correct: 4,
    explanation: 'The U.S. national-stage deadline is 30 months from the priority date — with or without a Chapter II demand. (Some other offices allow 31 months or more; each designated office’s own deadline must be checked.)',
  },
  {
    id: 'pb_gf4_012', topicId: 4, subtopic: 'pct_national_stage', difficulty: 2,
    question: 'To avoid abandonment of an international application as to the United States, by the 30-month deadline the applicant MUST:',
    options: [
      'File the oath or declaration, the translation, and all fees.',
      'File a preliminary amendment conforming the claims to U.S. practice.',
      'Pay the basic national fee (and provide a copy of the international application, unless already communicated by the International Bureau or filed at the USPTO).',
      'File an information disclosure statement citing the ISR references.',
      'Appoint a U.S.-registered practitioner.',
    ],
    correct: 2,
    explanation: '37 CFR 1.495(b): the 30-month hard requirements are the basic national fee and the copy of the international application (where needed). The English translation and the inventor’s oath/declaration may be furnished later, with a surcharge, in response to a notification — missing THOSE at 30 months is curable; missing the fee is abandonment.',
  },
  {
    id: 'pb_gf4_013', topicId: 4, subtopic: 'pct_national_stage', difficulty: 3,
    question: 'An applicant misses the 30-month deadline entirely, and the international application becomes abandoned as to the United States. The applicant may:',
    options: [
      'Do nothing — the abandonment is incurable.',
      'Refile the same international application with a new filing date.',
      'Ask the International Bureau to extend the 30-month period.',
      'Petition to revive under 37 CFR 1.137 on the basis that the delay was unintentional, with the petition fee and the required national-stage submissions.',
      'Convert the application to a design application.',
    ],
    correct: 3,
    explanation: 'Failure to meet the 371 requirements abandons the application as to the U.S., but revival is available by petition under 37 CFR 1.137 with a statement that the entire delay was UNINTENTIONAL (the stricter "unavoidable" standard was eliminated in 2013). The IB cannot extend a designated office’s national-stage deadline.',
  },
  {
    id: 'pb_gf4_014', topicId: 4, subtopic: 'pct_bypass', difficulty: 2,
    question: 'Instead of entering the national stage under 35 U.S.C. 371, an applicant may obtain U.S. examination of PCT-disclosed subject matter by:',
    options: [
      'Filing a regular U.S. application under 35 U.S.C. 111(a) that claims benefit of the international application under 35 U.S.C. 365(c) — the "bypass" continuation route.',
      'Requesting that the ISA transmit its search report to the examiner.',
      'Filing a petition to convert the international application into a provisional.',
      'Recording the international application in EFS as a national filing.',
      'Waiting for the USPTO to open the national stage automatically at 30 months.',
    ],
    correct: 0,
    explanation: 'The bypass route: while the international application (designating the U.S.) is still pending, file an ordinary 111(a) continuation/continuation-in-part claiming 365(c) benefit of the international application. National-stage entry never happens; the bypass application is examined as a regular domestic filing.',
  },
  {
    id: 'pb_gf4_015', topicId: 4, subtopic: 'pct_bypass', difficulty: 3,
    question: 'A practical difference between a 371 national-stage application and a 111(a) "bypass" continuation of the same international application is that the bypass application:',
    options: [
      'Cannot claim the benefit of the international filing date.',
      'May be filed as a continuation-in-part adding new matter (the added matter getting only the bypass filing date), which a national-stage entry can never do.',
      'Is exempt from the duty of disclosure.',
      'Is examined under the PCT unity-of-invention standard.',
      'Must be filed in the language of the international publication.',
    ],
    correct: 1,
    explanation: 'A national-stage application IS the international application entering the U.S. — its content is fixed; new matter is impossible. A bypass filing is a NEW 111(a) application, so it can be a CIP adding matter (new matter gets its own date), and it is examined under ordinary U.S. restriction practice rather than unity of invention.',
  },
  {
    id: 'pb_gf4_016', topicId: 4, subtopic: 'pct_prior_art', difficulty: 3,
    question: 'Under the AIA, the WIPO publication of an international application that designates the United States is available as prior art under 35 U.S.C. 102(a)(2):',
    options: [
      'As of the effective filing date of the subject matter disclosed, regardless of the language of publication.',
      'Only if the publication was in English.',
      'Only after the application enters the U.S. national stage.',
      'As of the 18-month publication date only.',
      'Never — only granted U.S. patents have secret prior-art effect.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 102(d) treats a WIPO-published PCT application designating the U.S. as a U.S. application publication for 102(a)(2), effective as of its earliest effective filing date — in ANY language. [Pre-AIA contrast: old 102(e) gave the international filing date only if the PCT was published in ENGLISH and designated the U.S.]',
  },
  {
    id: 'pb_gf4_017', topicId: 4, subtopic: 'pct_provisional_rights', difficulty: 3,
    question: 'Provisional rights (a reasonable royalty under 35 U.S.C. 154(d)) based on the publication of an international application designating the United States that was published in Japanese:',
    options: [
      'Are never available for PCT publications.',
      'Run from the Japanese-language international publication date.',
      'Run from the international filing date.',
      'Run from the 30-month national-stage entry.',
      'Become available only once an English translation of the international publication is provided (plus the usual actual-notice and substantially-identical-claim conditions).',
    ],
    correct: 4,
    explanation: '35 U.S.C. 154(d)(4): where the international publication is in a language other than English, provisional rights do not begin until the English translation is furnished. As always, the infringer needs actual notice and the issued claim must be substantially identical to the published claim.',
  },
  {
    id: 'pb_gf4_018', topicId: 4, subtopic: 'pct_priority', difficulty: 3,
    question: 'An applicant files an international application with RO/US 13 months after its intended priority application — one month past the 12-month period. The right of priority:',
    options: [
      'Is irretrievably lost.',
      'May be RESTORED upon request filed within 2 months of the priority period’s expiry, where RO/US finds the failure to file within 12 months was unintentional (with the required fee and statement).',
      'Is automatically restored because the delay was under six months.',
      'May be restored only by the International Bureau.',
      'May be preserved by converting the application to a national filing.',
    ],
    correct: 1,
    explanation: 'PCT Rule 26bis.3 permits restoration of the right of priority for applications filed within 2 months after the 12-month period expired. RO/US applies the "unintentional" criterion. Note that designated offices applying the stricter "due care" standard may reach their own conclusion in the national phase.',
  },
  {
    id: 'pb_gf4_019', topicId: 4, subtopic: 'pct_designations', difficulty: 1,
    question: 'Regarding designation of states, the filing of a PCT request today:',
    options: [
      'Requires the applicant to list and pay for each designated state individually.',
      'Designates only the receiving Office’s state unless others are added.',
      'Constitutes the automatic designation of ALL PCT contracting states bound by the treaty on the international filing date.',
      'Requires separate designation fees for each region.',
      'Permits at most ten designations.',
    ],
    correct: 2,
    explanation: 'Since 2004, filing the request automatically designates every contracting state (one flat international filing fee). The applicant chooses where to actually pursue protection later, at national-phase entry — unentered designations simply lapse.',
  },
  {
    id: 'pb_gf4_020', topicId: 4, subtopic: 'pct_publication', difficulty: 3,
    question: 'An applicant decides, 16 months into the priority period, to keep the invention secret and avoid any publication. The applicant should:',
    options: [
      'File a nonpublication request with the International Bureau.',
      'Withdraw only the priority claim.',
      'Enter the national phase early.',
      'Withdraw the international application before the International Bureau completes its technical preparations for publication.',
      'Request deferred examination.',
    ],
    correct: 3,
    explanation: 'PCT Rule 90bis.1: withdrawing the international application before completion of the IB’s technical preparations (roughly 15 days before the publication date) prevents international publication. There is no PCT counterpart to the U.S. nonpublication request — publication at 18 months is otherwise automatic.',
  },
  {
    id: 'pb_gf4_021', topicId: 4, subtopic: 'pct_ffl', difficulty: 2,
    question: 'An invention was made in the United States. Before filing an international application DIRECTLY with the International Bureau as receiving Office, the applicant must:',
    options: [
      'Register the invention with the Department of Commerce.',
      'File a U.S. provisional first.',
      'Obtain the ISA’s permission.',
      'Obtain a foreign filing license under 37 CFR 5.11 (filing with RO/US instead avoids the issue, since that filing itself undergoes national-security screening).',
      'Nothing — PCT filings are exempt from license requirements.',
    ],
    correct: 3,
    explanation: 'For inventions made in the U.S., filing abroad — including an international application filed at the IB or a foreign receiving Office — requires a foreign filing license (37 CFR 5.11(a)). Filing with RO/US is itself a U.S. filing subject to security review, which is why it is the standard route.',
  },
  {
    id: 'pb_gf4_022', topicId: 4, subtopic: 'pct_language', difficulty: 1,
    question: 'An international application filed with the United States Receiving Office (RO/US) must be in:',
    options: [
      'Any PCT publication language.',
      'English.',
      'English or Spanish.',
      'Any language, with an English translation within 14 months.',
      'The language of the earliest priority application.',
    ],
    correct: 1,
    explanation: '37 CFR 1.412(c)(6)(i): RO/US accepts international applications in ENGLISH only. An applicant wanting to file in another language can use the International Bureau as receiving Office (it accepts any language, subject to translation rules for search and publication).',
  },
  {
    id: 'pb_gf4_023', topicId: 4, subtopic: 'pct_fees', difficulty: 2,
    question: 'The fees due on filing an international application at RO/US are:',
    options: [
      'A single consolidated PCT fee set by the USPTO.',
      'The basic national fee and the search fee.',
      'The transmittal fee (for the receiving Office), the international filing fee (for the International Bureau), and the search fee (for the chosen International Searching Authority).',
      'The international filing fee only.',
      'The transmittal fee and the designation fee for each state.',
    ],
    correct: 2,
    explanation: 'Three fees accompany an RO/US filing: the RO’s transmittal fee, the IB’s international filing fee, and the ISA’s search fee (which varies with the authority chosen). Per-state designation fees no longer exist; national fees come later, at national-phase entry.',
  },
  {
    id: 'pb_gf4_024', topicId: 4, subtopic: 'pct_unity', difficulty: 2,
    question: 'If the ISA finds that an international application lacks unity of invention (claims not linked by a single general inventive concept), it will:',
    options: [
      'Refuse to search the application entirely.',
      'Require cancellation of the extra inventions.',
      'Reject the claims for lack of unity.',
      'Split the application into divisionals automatically.',
      'Search the invention first mentioned in the claims and invite the applicant to pay additional search fees for the others (payable under protest if the applicant disagrees).',
    ],
    correct: 4,
    explanation: 'PCT Article 17(3)(a)/Rule 40: the ISA searches the first-mentioned invention and invites additional fees for the rest; the applicant may pay under protest and contest the finding. Unsearched inventions can face consequences later in some national phases, but nothing is "rejected" in the international phase.',
  },
  {
    id: 'pb_gf4_025', topicId: 4, subtopic: 'pct_national_stage', difficulty: 2,
    question: 'During examination of a U.S. NATIONAL-STAGE (371) application, the standard the examiner applies when deciding whether the claims may be kept in one application is:',
    options: [
      'The PCT unity-of-invention standard (37 CFR 1.499) — not the ordinary U.S. "independent and distinct" restriction practice, which governs bypass continuations instead.',
      'Ordinary U.S. restriction practice under 35 U.S.C. 121.',
      'Whichever standard the applicant elects.',
      'No standard — national-stage applications cannot be restricted.',
      'The standard of the International Preliminary Examining Authority’s report.',
    ],
    correct: 0,
    explanation: 'National-stage applications are subject to UNITY OF INVENTION (37 CFR 1.475/1.499), a more applicant-favorable standard than domestic restriction practice. A bypass 111(a) continuation of the same PCT, by contrast, is examined under regular U.S. restriction practice — one of the strategic differences between the two routes.',
  },
  {
    id: 'pb_gf4_026', topicId: 4, subtopic: 'pct_term', difficulty: 2,
    question: 'A U.S. patent issues from a national-stage (371) application. Its 20-year term is measured from:',
    options: [
      'The national-stage entry date.',
      'The foreign priority date.',
      'The international filing date of the PCT application.',
      'The date the basic national fee was paid.',
      'The international publication date.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 154(a)(2): the 20-year term runs from the earliest U.S. or 365(c)/120-benefit filing date — for a national-stage patent, the INTERNATIONAL filing date. Foreign priority under 119/365(a)-(b) never counts against term. The same is true of a bypass continuation claiming 365(c) benefit.',
  },
  {
    id: 'pb_gf4_027', topicId: 4, subtopic: 'pct_isr', difficulty: 2,
    question: 'For an international application filed at RO/US, the international search is performed by:',
    options: [
      'The USPTO in every case.',
      'The International Bureau.',
      'The receiving Office of the applicant’s choice.',
      'An examiner in the corresponding U.S. national application.',
      'A competent International Searching Authority selected by the applicant from those available to RO/US filers (the USPTO itself, the EPO, KIPO, and certain other offices).',
    ],
    correct: 4,
    explanation: 'The applicant chooses the ISA in the request. RO/US filers may select the USPTO or one of several other competent authorities (e.g., the European Patent Office or the Korean office), trading off fees, speed, and the value of an early European-style search.',
  },
  {
    id: 'pb_gf4_028', topicId: 4, subtopic: 'pct_chapter2', difficulty: 2,
    question: 'If the applicant never files a Chapter II demand, the written opinion of the ISA:',
    options: [
      'Is converted by the International Bureau into the International Preliminary Report on Patentability (Chapter I) and communicated to the designated Offices.',
      'Lapses with no further effect.',
      'Becomes a binding rejection in the national phase.',
      'Must be answered within two months to keep the application alive.',
      'Is republished as the international search report.',
    ],
    correct: 0,
    explanation: 'With no demand, the ISA’s written opinion becomes the IPRP (Chapter I) — a non-binding patentability assessment made available to all designated Offices. Filing a demand (Chapter II) lets the applicant amend under Article 34 and argue before an IPEA, yielding an IPRP (Chapter II) instead.',
  },
  {
    id: 'pb_gf4_029', topicId: 4, subtopic: 'pct_timeline', difficulty: 2,
    question: 'An international application is filed claiming priority of an application filed 11 months earlier. The 30-month period for U.S. national-stage entry is measured from:',
    options: [
      'The international filing date.',
      'The date the ISR is established.',
      'The international publication date.',
      'The PRIORITY date — giving this applicant only about 19 more months after the international filing.',
      'The date of the demand, if one is filed.',
    ],
    correct: 3,
    explanation: 'All the major PCT clocks — 18-month publication, 22-month demand outer limit, 30-month national phase — run from the PRIORITY date when priority is claimed. Filing the PCT late in the priority year therefore shortens the international phase; only with no priority claim do the clocks run from the international filing date.',
  },
  {
    id: 'pb_gf4_030', topicId: 4, subtopic: 'pct_fees', difficulty: 3,
    question: 'A small-entity applicant files at RO/US and later enters the U.S. national stage. Small-entity fee reductions apply to:',
    options: [
      'All fees in both phases.',
      'The U.S. national-stage fees (e.g., the basic national fee), but NOT to international-phase fees such as the international filing fee — treaty-set fees have no small-entity discount.',
      'The international filing fee only.',
      'No PCT-related fees whatsoever.',
      'Only micro-entity applicants, in either phase.',
    ],
    correct: 1,
    explanation: 'Small- and micro-entity reductions are creatures of U.S. fee statutes and apply to USPTO national fees, including national-stage fees. The international filing fee and similar treaty-governed international-phase fees carry no small-entity reduction (separate PCT fee reductions exist — e.g., for electronic filing — but they are not entity-based).',
  },
  {
    id: 'pb_gf4_031', topicId: 4, subtopic: 'pct_amendments', difficulty: 3,
    question: 'The time limit for filing an Article 19 amendment of the claims with the International Bureau is:',
    options: [
      'One month from the international filing date.',
      'Two months from the transmittal of the international search report, or 16 months from the priority date, whichever expires LATER.',
      '18 months from the priority date in all cases.',
      'Any time before national-phase entry.',
      'Two months from international publication.',
    ],
    correct: 1,
    explanation: 'PCT Rule 46.1: Article 19 amendments are due within 2 months of ISR transmittal or 16 months from priority, whichever is later (and an amendment reaching the IB before publication preparations are complete is treated as timely). The point is to let amended claims appear in the international publication.',
  },
  {
    id: 'pb_gf4_032', topicId: 4, subtopic: 'pct_national_stage', difficulty: 3,
    question: 'An international application was filed (via the International Bureau) and published in German, designating the U.S. For U.S. national-stage entry, the English translation:',
    options: [
      'Is required — and if not filed with the 30-month submission, the USPTO will notify the applicant and set a period to furnish it with a surcharge; failure then abandons the application.',
      'Is unnecessary, because examiners may examine in German.',
      'Must have been filed with the International Bureau before publication.',
      'Is required only if the examiner requests one.',
      'Must be certified by the receiving Office.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 371(c)(2)/37 CFR 1.495(c): a non-English international application needs an English translation in the national stage. Unlike the basic national fee (a hard 30-month requirement), the translation may follow in response to a notification with surcharge — but ignoring that notice abandons the case.',
  },
  {
    id: 'pb_gf4_033', topicId: 4, subtopic: 'pct_benefit', difficulty: 2,
    question: 'A later-filed U.S. nonprovisional application may claim the benefit of a pending international application under 35 U.S.C. 365(c) if:',
    options: [
      'The international application was searched by the USPTO as ISA.',
      'The international application entered the national phase first.',
      'The international application has already been published.',
      'The international application designated the United States, and the usual benefit requirements (copendency, cross-reference, 112 support) are met.',
      'The two applications share at least one claim verbatim.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 365(c) extends 120-style benefit to international applications that DESIGNATE the U.S. — the basis of bypass practice. The ordinary continuity rules apply: copendency with the international application, a proper benefit claim, and 112 support in the international disclosure.',
  },
  {
    id: 'pb_gf4_034', topicId: 4, subtopic: 'pct_effect', difficulty: 2,
    question: 'Under 35 U.S.C. 363, an international application designating the United States has, from its international filing date:',
    options: [
      'No effect in the United States until the national stage begins.',
      'The effect of an issued U.S. patent.',
      'The effect of a national application regularly filed in the USPTO.',
      'The effect of a provisional application only.',
      'Prior-art effect but no pendency effect.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 363: an international application designating the U.S. IS, in effect, a pending regularly filed U.S. application from its international filing date — which is why it supports 365(c) benefit claims, why abandoning it matters, and why its filing date anchors the patent term.',
  },
  {
    id: 'pb_gf4_035', topicId: 4, subtopic: 'pct_publication', difficulty: 3,
    question: 'An applicant wants the international application published BEFORE the 18-month date (for example, to start provisional-rights notice running). The applicant:',
    options: [
      'Cannot alter the publication schedule.',
      'Must enter the national phase early instead.',
      'Must file a petition with the receiving Office.',
      'May obtain early publication only if the ISR has issued.',
      'May request early publication from the International Bureau (a special fee applies if the international search report is not yet available).',
    ],
    correct: 4,
    explanation: 'PCT Article 21(2)(b)/Rule 48.4: the applicant may ask the IB to publish early. If the ISR is not yet available, a special publication fee is due. Early publication can accelerate provisional-rights exposure and prior-art effect of the publication.',
  },
  {
    id: 'pb_gf4_036', topicId: 4, subtopic: 'pct_missing_parts', difficulty: 3,
    question: 'An applicant files an international application at RO/US claiming priority to an earlier application, but accidentally omits page 5 of the description. Page 5 was fully contained in the priority application, and the request included the standard incorporation-by-reference statement. The applicant may:',
    options: [
      'Not add the page — the application is fixed at filing.',
      'Add the page only by losing the priority claim.',
      'Add the page with the filing date becoming the date page 5 arrives.',
      'Petition the International Bureau for a waiver.',
      'Furnish the missing page and, because it was completely contained in the priority document and incorporated by reference, KEEP the original international filing date.',
    ],
    correct: 4,
    explanation: 'PCT Rules 4.18/20.6: a missing element or part that is completely contained in the priority application can be incorporated by reference, preserving the original international filing date. Without that mechanism, furnishing missing material re-dates the application to the day it arrives.',
  },
  {
    id: 'pb_gf4_037', topicId: 4, subtopic: 'pct_corrections', difficulty: 3,
    question: 'Rectification of an "obvious mistake" in an international application under PCT Rule 91:',
    options: [
      'Permits any error to be fixed within two months.',
      'Is unavailable once the ISR issues.',
      'Applies to typographical errors in the request only.',
      'Is allowed only where it is obvious that something else was intended than what appears, and that nothing else could have been intended — it cannot be used to add omitted sheets or new matter.',
      'Requires consent of all designated Offices.',
    ],
    correct: 3,
    explanation: 'Rule 91.1: the mistake and its correction must both be obvious — the "nothing else could have been intended" standard — to the competent authority. Missing sheets and substantive additions are outside Rule 91 (the incorporation-by-reference rules, not rectification, address omitted material).',
  },
  {
    id: 'pb_gf4_038', topicId: 4, subtopic: 'pct_receiving_office', difficulty: 2,
    question: 'A sole applicant who is a U.S. resident (and U.S. national) may properly file an international application with which receiving Office(s)?',
    options: [
      'Any receiving Office in the world.',
      'Only the International Bureau.',
      'RO/US, or the International Bureau acting as receiving Office.',
      'RO/US only.',
      'Any English-language receiving Office.',
    ],
    correct: 2,
    explanation: 'Competence follows nationality/residence: a U.S. national-resident may use RO/US or the IB (competent for nationals/residents of ANY contracting state). A foreign national receiving Office would be competent only if the applicant had that state’s nationality or residence. Remember the foreign filing license before filing at the IB for U.S.-made inventions.',
  },
  {
    id: 'pb_gf4_039', topicId: 4, subtopic: 'pct_chapter2', difficulty: 2,
    question: 'International preliminary examination under Chapter II is conducted by:',
    options: [
      'The International Bureau.',
      'An International Preliminary Examining Authority (IPEA), producing the International Preliminary Report on Patentability (Chapter II) after the applicant may amend and argue.',
      'The receiving Office that accorded the filing date.',
      'Each designated Office in parallel.',
      'The examiner assigned to the eventual U.S. national stage.',
    ],
    correct: 1,
    explanation: 'A demand elects Chapter II before an IPEA (for RO/US filers, typically the same office chosen as ISA). The applicant may amend under Article 34 and engage with the examiner; the result is the IPRP (Chapter II) — an advisory opinion on novelty, inventive step, and industrial applicability.',
  },
  {
    id: 'pb_gf4_040', topicId: 4, subtopic: 'pct_timeline', difficulty: 2,
    question: 'Which is TRUE about national-phase deadlines across designated Offices?',
    options: [
      'The 30-month period applies to the United States, but other designated Offices set their own deadlines (many allow 31 months or more) — each office where protection is sought must be checked individually.',
      'Every PCT contracting state uses exactly 30 months.',
      'The International Bureau enforces a single worldwide deadline.',
      'National-phase deadlines run from the international publication date.',
      'Missing one office’s deadline abandons the application everywhere.',
    ],
    correct: 0,
    explanation: 'The 30-month floor comes from Article 22, but offices may (and do) allow longer — e.g., 31 months in several jurisdictions. Deadlines run from the priority date, and each designation stands or falls independently: missing the U.S. deadline abandons only the U.S. designation.',
  },
];
