/**
 * Patent Bar — WS3 gap-fill: final top-up tranche (mixed sections).
 *
 * 55 AI-authored questions landing the bank at the EXACT-PROPORTION size of
 * 980 — the only state in which all six blueprint floors hold simultaneously
 * (see docs/monetization/PATENT_BAR_COVERAGE_MATRIX.md). Composition:
 *   - 30 Ethics & Professional Conduct (`pb_gf7b_001`–`030`, topicId 7):
 *     second ethics tranche (117 → 147), covering 37 CFR Part 11 ground the
 *     first tranche's scenarios did not: confidentiality exceptions
 *     (11.106(b)), the 11.108 specific-conflict catalogue, former-client and
 *     imputed conflicts + lateral screening (11.109–11.111), organization
 *     and diminished-capacity clients (11.113–11.114), trust accounts
 *     (11.115), withdrawal (11.116 + 1.36(b)), advisor/evaluator roles
 *     (11.201/11.203), tribunal duties (11.301–11.305), third-party contact
 *     rules (11.402–11.404), supervision & fee-sharing (11.503–11.504),
 *     advertising (11.702/11.704), reporting misconduct (11.803), and the
 *     1.56 foreign-search-report duty.
 *   - 24 Patentability & Prior Art (`pb_gf0_001`–`024`, topicId 0):
 *     AIA 102 categories & grace-period exceptions, Helsinn, experimental
 *     use, printed-publication accessibility, 102(a)(2)/(b)(2)(C), Graham/
 *     KSR/secondary considerations/analogous art, Alice-Mayo, Myriad,
 *     Chakrabarty, 112(a)/(b)/(f), best mode post-AIA, utility,
 *     inventorship, derivation, statutory double patenting, 100(i).
 *   - 1 Patent Prosecution (`pb_gf2_001`, topicId 2): issue-fee timing.
 * All original compositions.
 *
 * VERIFICATION STATUS: every item here is 'unverified' (AI-authored,
 * pending SME review via /dashboard/test-prep/patent_bar/review-queue).
 * None may appear in a scored mock until reviewed. Answer keys are
 * deliberately balanced (exactly 11 per option position — asserted by
 * qbank-key-balance.test.ts).
 */

import type { PatentBarQuestion } from './patent-bar-qbank-data';

export const PATENT_BAR_GAPFILL_TOPUP: PatentBarQuestion[] = [
  {
    id: 'pb_gf7b_001', topicId: 7, subtopic: 'ethics_confidentiality', difficulty: 2,
    question: 'Under 37 CFR 11.106(b), a practitioner MAY reveal information relating to the representation of a client, to the extent reasonably necessary, in each of the following situations EXCEPT:',
    options: [
      'To prevent reasonably certain death or substantial bodily harm.',
      'To secure legal advice about the practitioner’s own compliance with the USPTO Rules of Professional Conduct.',
      'To respond to a client’s embarrassing but lawful business practices that the practitioner finds distasteful.',
      'To establish a defense in a controversy between the practitioner and the client.',
      'To comply with a court order.',
    ],
    correct: 2,
    explanation: '11.106(b) lists narrow permissive-disclosure grounds: preventing death/substantial bodily harm, preventing or mitigating client crime/fraud using the practitioner’s services, securing ethics-compliance advice, self-defense in practitioner-client controversies or proceedings, and complying with law or a court order. Distaste for a client’s lawful conduct is not among them — confidentiality holds.',
  },
  {
    id: 'pb_gf7b_002', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'Two unrelated clients ask the same practitioner to prosecute their applications, and the practitioner realizes the two claim sets are directly adverse — each client’s broadest claims would read on the other’s product. Under 37 CFR 11.107, the practitioner may proceed for both only if:',
    options: [
      'The practitioner reasonably believes competent and diligent representation can be provided to each, the representation is not prohibited by law or involve a claim by one client against the other in the same proceeding, and EACH client gives informed consent, confirmed in writing.',
      'The practitioner erects an internal ethical wall between the two files.',
      'The clients are billed separately.',
      'The practitioner discloses each client’s confidences to the other.',
      'Either client has paid a retainer first.',
    ],
    correct: 0,
    explanation: '11.107(b): a concurrent conflict can be waived only when the practitioner reasonably believes both representations can be competent and diligent, the situation is not categorically unwaivable, and each affected client gives INFORMED CONSENT CONFIRMED IN WRITING. Screening within a solo practice cures nothing, and revealing confidences would itself violate 11.106.',
  },
  {
    id: 'pb_gf7b_003', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 3,
    question: 'A client offers to pay prosecution fees by giving the practitioner a 10% ownership stake in the client’s startup. Under 37 CFR 11.108(a), the practitioner may enter this business transaction with the client only if:',
    options: [
      'The stake is worth less than the fees would have been.',
      'A partner in the practitioner’s firm approves.',
      'The client is a sophisticated businessperson.',
      'The transaction is documented within one year.',
      'The terms are fair and reasonable, fully disclosed in writing in an understandable way; the client is advised in writing of the desirability of seeking independent counsel and given the opportunity to do so; and the client gives informed consent, in a writing signed by the client, covering the terms and the practitioner’s role.',
    ],
    correct: 4,
    explanation: '11.108(a) imposes the three-part protocol for practitioner-client business deals (including equity-for-fees): objectively fair terms fully disclosed in writing, written advice to seek independent counsel plus a real chance to get it, and the client’s signed informed consent. Sophistication and relative value do not substitute for the protocol.',
  },
  {
    id: 'pb_gf7b_004', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'A grateful elderly client asks her patent practitioner to draft a codicil to her will leaving the practitioner her vacation home. Under 37 CFR 11.108(c), the practitioner:',
    options: [
      'May draft it if two witnesses are present.',
      'May NOT prepare an instrument giving the practitioner (or the practitioner’s close relatives) a substantial gift from a client — unless the practitioner is related to the client.',
      'May draft it because the client initiated the gift.',
      'May draft it if the gift is disclosed to the OED.',
      'May accept the gift but must value it at fair market rates.',
    ],
    correct: 1,
    explanation: '11.108(c): a practitioner shall not solicit a substantial gift from a client, nor prepare an instrument giving the practitioner or a person related to the practitioner a substantial gift, unless the practitioner or recipient is related to the client. Client initiation does not cure it — the practitioner cannot be the drafter of their own windfall.',
  },
  {
    id: 'pb_gf7b_005', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 3,
    question: 'A practitioner representing an inventor in a headline-grabbing patent dispute is approached by a publisher about a book deal telling the story of the case. Under 37 CFR 11.108(d), the practitioner may:',
    options: [
      'Sign now if the client receives half the royalties.',
      'Sign now with the client’s informed consent.',
      'Sign now if the book will not be published until after the case.',
      'NOT negotiate or acquire literary or media rights to an account based in substantial part on information relating to the representation until the representation has CONCLUDED.',
      'Never write about the representation, even decades later.',
    ],
    correct: 3,
    explanation: '11.108(d) bars making or negotiating literary/media-rights deals about the representation PRIOR TO ITS CONCLUSION — the concern is that the story’s dramatic value could distort professional judgment during the case. After the representation ends, such an agreement is permissible (confidentiality permitting).',
  },
  {
    id: 'pb_gf7b_006', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'A cash-strapped inventor asks the practitioner to lend him living expenses while his infringement suit and reexamination are pending. Under 37 CFR 11.108(e), the practitioner may:',
    options: [
      'Lend living expenses if interest-free.',
      'NOT provide financial assistance in connection with the pending proceeding — except advancing court costs and expenses of the proceeding (repayment contingent on outcome is fine), or paying such costs outright for an indigent client.',
      'Lend any amount if documented as a promissory note.',
      'Provide assistance up to the amount of fees already paid.',
      'Provide assistance only through a third-party finance company the practitioner owns.',
    ],
    correct: 1,
    explanation: '11.108(e): financial assistance to a client in connection with pending or contemplated litigation/proceedings is prohibited — with two exceptions: advancing costs and expenses of the proceeding (contingent repayment allowed), and paying those costs for an indigent client. Living-expense loans fall outside both exceptions.',
  },
  {
    id: 'pb_gf7b_007', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'An employer offers to pay a practitioner’s fees for prosecuting its employee-inventor’s personal side-project application. Under 37 CFR 11.108(f), the practitioner may accept payment from the employer only if:',
    options: [
      'The employer signs the engagement letter.',
      'The employer receives copies of all correspondence.',
      'The fee is at market rates.',
      'The inventor-client gives informed consent; there is no interference with the practitioner’s independent judgment or the practitioner-client relationship; and information relating to the representation stays protected under 11.106.',
      'The employer agrees to arbitration of fee disputes.',
    ],
    correct: 3,
    explanation: '11.108(f) permits third-party payor arrangements on three conditions: client informed consent, no interference with independence or the client relationship, and preserved confidentiality. The payor buys no seat at the table — the client, not the employer, directs the representation and receives the confidences.',
  },
  {
    id: 'pb_gf7b_008', topicId: 7, subtopic: 'ethics_former_client', difficulty: 2,
    question: 'A practitioner who formerly prosecuted Alpha Corp.’s battery-electrode portfolio is asked by Beta Inc. to draft claims aimed at designing around — and invalidating — those same Alpha patents. Under 37 CFR 11.109(a), the practitioner:',
    options: [
      'May NOT represent Beta in this same or substantially related matter in which Beta’s interests are materially adverse to former client Alpha, unless Alpha gives informed consent, confirmed in writing.',
      'May proceed because Alpha is no longer a client.',
      'May proceed if he refreshes no memory of Alpha’s files.',
      'May proceed after one year has passed.',
      'May never again work in battery technology.',
    ],
    correct: 0,
    explanation: '11.109(a): the former-client rule turns on (1) same or substantially related matter and (2) material adversity — both present here. Only Alpha’s informed written consent clears it. There is no cooling-off period that erases the conflict, and no field-wide ban either: unrelated battery work for Beta would be fine.',
  },
  {
    id: 'pb_gf7b_009', topicId: 7, subtopic: 'ethics_imputation', difficulty: 3,
    question: 'A practitioner who is personally disqualified from a matter (because of work at her PRIOR firm) joins a new firm that wants to take that very matter. Under 37 CFR 11.110, the new firm:',
    options: [
      'Is automatically disqualified with no cure.',
      'May take the matter only if the practitioner resigns.',
      'May take the matter if she promises orally not to discuss it.',
      'Must obtain an OED waiver.',
      'May take the matter if the disqualified practitioner is TIMELY SCREENED from any participation, is apportioned no part of the fee from it, and written notice is promptly given to the affected former client.',
    ],
    correct: 4,
    explanation: '11.110: conflicts are generally imputed to the firm, but for a lateral’s prior-firm conflicts the rule provides a screening cure — timely screen, no fee apportionment from the matter, and prompt written notice to the former client so compliance can be policed. An informal promise is not a screen.',
  },
  {
    id: 'pb_gf7b_010', topicId: 7, subtopic: 'ethics_former_gov', difficulty: 3,
    question: 'A former USPTO examiner, now at a law firm, is personally barred from a matter she personally and substantially examined. Under 37 CFR 11.111 (former public officer or employee), her FIRM:',
    options: [
      'Is also barred permanently from the matter.',
      'May handle it only with the applicant’s consent.',
      'May knowingly undertake the matter if the disqualified former examiner is timely screened from participation, receives no part of the fee from it, and written notice is promptly given to the USPTO to enable compliance checking.',
      'May handle it after the former examiner has been gone from the Office for two years.',
      'May handle it only before the PTAB, not in examination.',
    ],
    correct: 2,
    explanation: '11.111 incorporates the Model Rule 1.11 framework: the former government employee’s personal bar (matters of personal and substantial participation) is NOT imputed to the firm if she is screened, unfeed from the matter, and the agency gets prompt written notice. The individual’s own bar, by contrast, is permanent for those matters.',
  },
  {
    id: 'pb_gf7b_011', topicId: 7, subtopic: 'ethics_organization', difficulty: 3,
    question: 'In-house patent counsel learns that a vice president is deliberately withholding invalidating prior art from the USPTO in the company’s applications. Under 37 CFR 11.113 (organization as client), counsel’s obligation is to:',
    options: [
      'Resign immediately without more.',
      'Report the VP to the police.',
      'Say nothing — the VP is the client contact.',
      'Follow the VP’s instructions but memo the file.',
      'Proceed as reasonably necessary in the BEST INTEREST OF THE ORGANIZATION — including referring the matter up the ladder to higher authority, and if necessary to the highest authority that can act (e.g., the board) — because the client is the organization, not the officer.',
    ],
    correct: 4,
    explanation: '11.113(a)-(b): the organization is the client. When an officer’s act related to the representation violates a legal duty to the organization or the law in a way likely to cause substantial injury, counsel refers it up the ladder. (Here the underlying conduct also implicates the 1.56 duty of disclosure and the 11.303 duty of candor — counsel cannot simply follow orders.)',
  },
  {
    id: 'pb_gf7b_012', topicId: 7, subtopic: 'ethics_diminished_capacity', difficulty: 2,
    question: 'A practitioner’s longtime solo-inventor client is showing signs of significant cognitive decline and is about to abandon a valuable application against his apparent interests. Under 37 CFR 11.114, the practitioner should:',
    options: [
      'Withdraw immediately to avoid liability.',
      'Take over the client’s decisions as de facto guardian.',
      'Maintain, as far as reasonably possible, a NORMAL client relationship — and, when there is risk of substantial harm and the client cannot act in his own interest, take reasonably necessary protective action (such as consulting family or seeking a guardian), revealing information only to the extent reasonably necessary.',
      'Report the client to the OED.',
      'Complete the abandonment as instructed without question.',
    ],
    correct: 2,
    explanation: '11.114: diminished capacity does not end the relationship — the practitioner maintains normalcy as far as possible and may take calibrated protective action where the client is at risk of substantial harm, with implied limited authority to reveal information as needed for that purpose. The practitioner neither becomes the decision-maker nor blindly executes harmful instructions.',
  },
  {
    id: 'pb_gf7b_013', topicId: 7, subtopic: 'ethics_safekeeping', difficulty: 2,
    question: 'A client pays a practitioner a $10,000 advance for fees not yet earned and USPTO fees not yet incurred. Under 37 CFR 11.115, the practitioner must:',
    options: [
      'Deposit it in the firm operating account and track it in the ledger.',
      'Return it and bill monthly instead.',
      'Split it between operating and personal accounts.',
      'Deposit it into a separate client trust account, withdrawing fees only AS EARNED and expenses only as incurred — and keep complete records for five years after termination of the representation.',
      'Hold it in cash in the office safe.',
    ],
    correct: 3,
    explanation: '11.115: client and third-party property is held separate from the practitioner’s own; unearned advances live in the trust account until earned (withdrawal as earned/incurred), and complete records are kept for FIVE years after the representation ends. Parking client money in the operating account is classic commingling — a leading cause of discipline.',
  },
  {
    id: 'pb_gf7b_014', topicId: 7, subtopic: 'ethics_withdrawal', difficulty: 3,
    question: 'A client insists that the practitioner file a response containing factual assertions the practitioner KNOWS are false. The client refuses to relent and the practitioner is attorney of record in the pending application. The practitioner:',
    options: [
      'MUST withdraw (continuing would violate the Rules), taking steps reasonably practicable to protect the client’s interests — reasonable notice, time to engage other counsel, surrender of papers, refund of unearned fees — and, as attorney of record, must request withdrawal and obtain the Office’s approval under 37 CFR 1.36(b).',
      'Must file the response as instructed — the client decides.',
      'May quietly stop working on the case until it goes abandoned.',
      'Must report the client to the Director of the USPTO before doing anything.',
      'May withdraw only at a natural break in prosecution.',
    ],
    correct: 0,
    explanation: '11.116(a)(1) makes withdrawal MANDATORY when continuing will violate the Rules (filing known falsehoods violates 11.303/11.18). 11.116(d) requires protecting the client on the way out, and in a pending application the practitioner of record cannot just vanish — 37 CFR 1.36(b) requires requesting and receiving Office approval to withdraw. Silent abandonment would itself violate 11.103.',
  },
  {
    id: 'pb_gf7b_015', topicId: 7, subtopic: 'ethics_advisor', difficulty: 1,
    question: 'Under 37 CFR 11.201, a practitioner rendering advice to a client:',
    options: [
      'Must limit the advice strictly to technical legal points.',
      'Shall exercise INDEPENDENT professional judgment and render CANDID advice — and may refer not only to law but to other considerations such as moral, economic, social, and political factors relevant to the client’s situation.',
      'Must tell the client whatever supports the client’s chosen course.',
      'May give business advice only if separately compensated.',
      'Must put all advice in writing.',
    ],
    correct: 1,
    explanation: '11.201: the advisor role demands independence and candor — including unwelcome truths (e.g., that a claim set is likely invalid). The rule expressly allows advice to draw on moral, economic, social, and political considerations, since purely technical advice can be of little value.',
  },
  {
    id: 'pb_gf7b_016', topicId: 7, subtopic: 'ethics_evaluation', difficulty: 3,
    question: 'A client asks its practitioner to prepare a patentability opinion that the client will show to prospective investors. Under 37 CFR 11.203, the practitioner may provide this evaluation for use by third persons if:',
    options: [
      'Providing it is compatible with other aspects of the practitioner’s relationship with the client — and, where the evaluation is likely to affect the client’s interests materially and adversely, only with the client’s informed consent; information otherwise stays protected under 11.106.',
      'The investors also sign engagement letters.',
      'The opinion carries a disclaimer of all liability.',
      'The OED approves the arrangement in advance.',
      'The practitioner has no equity in the client.',
    ],
    correct: 0,
    explanation: '11.203: third-party evaluations (opinions for investors, lenders, acquirers) are permitted when compatible with the client relationship; informed consent is required where the evaluation may hurt the client materially. The practitioner should candidly assess — an investor-facing opinion is not marketing copy, and confidentiality limits what it can reveal.',
  },
  {
    id: 'pb_gf7b_017', topicId: 7, subtopic: 'ethics_tribunal', difficulty: 2,
    question: 'A client wants the practitioner to file a petition raising an argument the practitioner knows is squarely foreclosed with no good-faith basis for change, purely to delay a competitor. Under 37 CFR 11.301, the practitioner:',
    options: [
      'May file it because zealous advocacy requires it.',
      'May file it if labeled as a protective filing.',
      'May file it if the client accepts the risk of sanctions.',
      'May file it once, but not twice.',
      'May NOT bring or defend a proceeding, or assert or controvert an issue, without a basis in law and fact that is not frivolous — though a good-faith argument for EXTENSION, MODIFICATION, or REVERSAL of existing law is permitted.',
    ],
    correct: 4,
    explanation: '11.301 is the meritorious-claims rule: frivolous positions are forbidden regardless of client instruction, but genuine good-faith arguments to change the law are protected. Delay-for-delay’s-sake also implicates 11.302 (expediting) and the 11.18 certifications attached to every Office paper.',
  },
  {
    id: 'pb_gf7b_018', topicId: 7, subtopic: 'ethics_tribunal', difficulty: 3,
    question: 'Briefing an appeal to the PTAB, a practitioner discovers a precedential Federal Circuit decision directly adverse to her client’s position. Opposing counsel (in an inter partes matter) has not cited it. Under 37 CFR 11.303(a)(2), the practitioner must:',
    options: [
      'Stay silent — adversaries bear their own research burdens.',
      'DISCLOSE the controlling, directly adverse legal authority to the tribunal — and may then argue against its application or for its modification.',
      'Cite it only if the Board asks.',
      'Withdraw from the appeal.',
      'Cite it in a confidential side letter to the judges.',
    ],
    correct: 1,
    explanation: '11.303(a)(2): candor to the tribunal includes disclosing legal authority in the controlling jurisdiction known to be directly adverse and not disclosed by opposing counsel. Disclosure is compatible with advocacy — counsel discloses, then distinguishes or attacks the authority. In EX PARTE proceedings, 11.303(d) goes further, requiring disclosure of all material facts.',
  },
  {
    id: 'pb_gf7b_019', topicId: 7, subtopic: 'ethics_tribunal', difficulty: 3,
    question: 'Mid-way through a PTAB trial, a practitioner learns that a declaration he offered — and reasonably believed true at the time — contains materially false test data. Under 37 CFR 11.303(a)(3) and (b), the practitioner must:',
    options: [
      'Do nothing, because he did not know of the falsity when offering it.',
      'Quietly refrain from citing the declaration again.',
      'Take REASONABLE REMEDIAL MEASURES — including, if necessary, disclosure to the tribunal — because the duty of candor continues to the conclusion of the proceeding and overrides confidentiality to that extent.',
      'Wait for opposing counsel to discover the problem.',
      'Withdraw the declaration only with the client’s permission.',
    ],
    correct: 2,
    explanation: '11.303(a)(3)/(b): on learning that offered material evidence is false, the practitioner must take reasonable remedial measures up to and including disclosure to the tribunal — even over the client’s objection, and even though the information would otherwise be confidential. Silence and mere non-reliance do not cure a false record.',
  },
  {
    id: 'pb_gf7b_020', topicId: 7, subtopic: 'ethics_fairness', difficulty: 2,
    question: 'Anticipating discovery in a PTAB proceeding, a client asks its practitioner for advice on "cleaning up" old lab notebooks that contain damaging entries. Under 37 CFR 11.304(a), the practitioner:',
    options: [
      'May assist because the notebooks are client property.',
      'May advise deletion if litigation has not yet begun.',
      'May watch but not assist.',
      'Must NOT unlawfully obstruct another party’s access to evidence or unlawfully alter, destroy, or conceal material having potential evidentiary value — nor counsel or assist anyone else to do so.',
      'Must first seek a protective order.',
    ],
    correct: 3,
    explanation: '11.304(a) is the fairness-to-opposing-party rule: no unlawful obstruction, alteration, destruction, or concealment of potentially evidentiary material, and no counseling or assisting it. "Cleaning up" damaging notebooks in anticipation of a proceeding is spoliation counseling — a serious disciplinary (and potentially criminal) matter.',
  },
  {
    id: 'pb_gf7b_021', topicId: 7, subtopic: 'ethics_third_parties', difficulty: 2,
    question: 'A practitioner representing a patent owner in a licensing dispute wants to phone the infringer’s in-house engineer — whom the practitioner knows is represented by the infringer’s counsel in the matter — to "get the real story." Under 37 CFR 11.402, the practitioner:',
    options: [
      'May call, because engineers are not lawyers.',
      'May call if he identifies himself honestly.',
      'May call after business hours in a personal capacity.',
      'May NOT communicate about the subject of the representation with a person known to be represented in the matter, absent the other counsel’s consent or legal authorization.',
      'May e-mail but not call.',
    ],
    correct: 3,
    explanation: '11.402: the no-contact rule bars communicating about the matter with persons known to be represented in it, without their counsel’s consent or legal authority. Honest self-identification does not cure it, and for represented ORGANIZATIONS the protection extends to constituents whose conduct is at issue or who can bind the organization.',
  },
  {
    id: 'pb_gf7b_022', topicId: 7, subtopic: 'ethics_third_parties', difficulty: 2,
    question: 'An unrepresented co-inventor, whose interests conflict with the practitioner’s client, calls the practitioner for guidance about signing assignment papers. Under 37 CFR 11.403, the practitioner:',
    options: [
      'May give full legal advice if accurate.',
      'Must not state or imply that the practitioner is disinterested, must correct any misunderstanding about the practitioner’s role, and must give no legal advice other than the advice to SECURE INDEPENDENT COUNSEL.',
      'Must refer the caller to the OED.',
      'May negotiate the assignment terms freely.',
      'Must refuse to speak at all.',
    ],
    correct: 1,
    explanation: '11.403: with unrepresented persons the practitioner cannot pose as neutral, must fix role misunderstandings, and — where interests conflict with the client’s — the only permissible legal advice is to get their own counsel. Speaking is allowed; advising is not.',
  },
  {
    id: 'pb_gf7b_023', topicId: 7, subtopic: 'ethics_supervision', difficulty: 2,
    question: 'A paralegal in a practitioner’s office, following the office’s (nonexistent) docketing procedures, misses a response deadline and an application goes abandoned. Under 37 CFR 11.503, the practitioner with managerial authority:',
    options: [
      'Bears no responsibility — the paralegal erred.',
      'Is responsible only if she directed the specific error.',
      'Is accountable for failing to make REASONABLE EFFORTS to ensure the office has measures giving reasonable assurance that nonpractitioner assistants’ conduct is compatible with the practitioner’s professional obligations — a docketing system being the paradigm example.',
      'Is automatically suspended.',
      'Can shift responsibility by firing the paralegal.',
    ],
    correct: 2,
    explanation: '11.503: managers must institute reasonable supervisory measures for nonpractitioner assistants, and a practitioner is responsible for an assistant’s conduct she orders, ratifies, or — as a manager — fails to prevent or mitigate when knowing of it in time. Running a patent practice without a docketing system is itself the violation (and a 11.101/11.103 problem).',
  },
  {
    id: 'pb_gf7b_024', topicId: 7, subtopic: 'ethics_independence', difficulty: 3,
    question: 'An invention-promotion company offers to send a practitioner a steady stream of inventor clients in exchange for 30% of each legal fee. Under 37 CFR 11.504(a), this arrangement is:',
    options: [
      'Permitted as a routine referral arrangement.',
      'Permitted if disclosed to each client.',
      'Permitted if the company is bonded.',
      'Permitted up to 25% of the fee.',
      'PROHIBITED — a practitioner may not share legal fees with a nonpractitioner (the narrow exceptions cover things like payments to a deceased practitioner’s estate, purchase of a practice, and including nonpractitioner employees in compensation or retirement plans).',
    ],
    correct: 4,
    explanation: '11.504(a): fee-sharing with nonpractitioners is barred to protect independent professional judgment from lay control; disclosure does not cure it. The enumerated exceptions (estate payments, practice purchases, employee compensation/retirement plans, certain nonprofit court-awarded fees) do not include referral kickbacks — a recurring invention-promotion abuse.',
  },
  {
    id: 'pb_gf7b_025', topicId: 7, subtopic: 'ethics_independence', difficulty: 3,
    question: 'A registered patent agent proposes forming a partnership with a nonpractitioner marketing executive; the firm would both market inventions and prosecute patent applications. Under 37 CFR 11.504(b), the partnership is:',
    options: [
      'PROHIBITED — a practitioner may not form a partnership with a nonpractitioner if ANY of the partnership’s activities consist of the practice of patent law before the Office.',
      'Permitted because agents are not attorneys.',
      'Permitted if the executive stays out of client files.',
      'Permitted with OED registration of the firm.',
      'Permitted if prosecution revenue stays below half of income.',
    ],
    correct: 0,
    explanation: '11.504(b): no partnership with a nonpractitioner where any partnership activity is the practice of law (which includes patent prosecution). It applies fully to registered agents — they are practitioners under the rules. Internal walls and revenue ratios do not change the structural prohibition.',
  },
  {
    id: 'pb_gf7b_026', topicId: 7, subtopic: 'ethics_advertising', difficulty: 2,
    question: 'A practitioner’s website advertises: "We guarantee your patent will be granted, and our claims never get rejected." Under 37 CFR 11.701, this communication is:',
    options: [
      'Permitted puffery.',
      'Permitted if a disclaimer appears in the footer.',
      'PROHIBITED as a false or misleading communication about the practitioner’s services — grant outcomes cannot be guaranteed, and statements creating unjustified expectations mislead.',
      'Permitted if the practitioner’s historical allowance rate is high.',
      'Regulated only by state bars, not the USPTO.',
    ],
    correct: 2,
    explanation: '11.701 forbids false or misleading communications about the practitioner or the practitioner’s services — including truthful statements presented so as to create unjustified expectations. No one controls examination outcomes, so a grant guarantee is inherently misleading; OED discipline applies regardless of any state bar’s rules.',
  },
  {
    id: 'pb_gf7b_027', topicId: 7, subtopic: 'ethics_advertising', difficulty: 2,
    question: 'Under 37 CFR 11.704, a practitioner registered to practice before the USPTO in patent matters may properly hold herself out using:',
    options: [
      'The title "Patent Specialist Certified by the Federal Government."',
      'Any title, since titles are commercial speech.',
      '"Licensed Patent Judge."',
      '"USPTO-Endorsed Counsel."',
      'The designation "Registered Patent Attorney" (or "Registered Patent Agent" for an agent) — the recognized way to communicate USPTO registration in patent matters.',
    ],
    correct: 4,
    explanation: '11.704: a practitioner may communicate fields of practice and, when registered, may use the official "Registered Patent Attorney"/"Registered Patent Agent" designations. Invented certifications and titles implying government endorsement are misleading under 11.701.',
  },
  {
    id: 'pb_gf7b_028', topicId: 7, subtopic: 'ethics_unauthorized_practice', difficulty: 3,
    question: 'A practitioner suspended by the OED continues to serve his old clients as a "patent consultant": he interviews inventors, drafts the claims and responses, and has a registered friend sign and file everything unchanged. This arrangement:',
    options: [
      'Constitutes UNAUTHORIZED PRACTICE by the suspended individual — and the registered practitioner who lends a signature without exercising independent judgment aids that violation (11.505, 11.804; cf. the 11.58 limits on suspended practitioners).',
      'Is proper because a registered practitioner signs the papers.',
      'Is proper if clients are told about the suspension.',
      'Is proper if the consultant charges only for technical work.',
      'Is proper for responses but not for new applications.',
    ],
    correct: 0,
    explanation: 'A suspended practitioner may not do the substantive work of practice before the Office behind a signature of convenience — that is unauthorized practice, and the signer who rubber-stamps it violates the duty to exercise independent judgment plus the 11.18 certifications, and assists a violation (11.804(a)). Client disclosure changes nothing.',
  },
  {
    id: 'pb_gf7b_029', topicId: 7, subtopic: 'ethics_duty_disclosure', difficulty: 2,
    question: 'While a U.S. application is pending, the EPO cites two highly relevant references in the search report of the client’s counterpart European application. Under 37 CFR 1.56, the practitioner should:',
    options: [
      'Ignore them — foreign proceedings are separate.',
      'Cite them only if the EPO maintains its objections.',
      'Wait until allowance to decide.',
      'Submit the references to the USPTO in an information disclosure statement — prior art cited in counterpart foreign applications is classic material information within the duty of disclosure.',
      'Send them to the examiner informally by phone.',
    ],
    correct: 3,
    explanation: 'The 1.56 duty of candor covers everyone substantively involved in prosecution, and MPEP 2001.06(a) singles out prior art cited in related foreign applications as material information to bring to the examiner’s attention — via a compliant IDS under 37 CFR 1.97/1.98, within the applicable time windows.',
  },
  {
    id: 'pb_gf7b_030', topicId: 7, subtopic: 'ethics_reporting', difficulty: 3,
    question: 'A practitioner acquires actual knowledge that another practitioner forged an inventor’s signature on a declaration — conduct raising a substantial question of that practitioner’s honesty. Under 37 CFR 11.803, the practitioner:',
    options: [
      'May report, but has no obligation.',
      'SHALL inform the OED Director — knowledge of another practitioner’s violation raising a substantial question as to honesty, trustworthiness, or fitness triggers a mandatory report (confidential information protected by 11.106 excepted).',
      'Must first confront the other practitioner privately.',
      'Must report only if a client was harmed.',
      'Should report to the local bar association instead.',
    ],
    correct: 1,
    explanation: '11.803 makes reporting MANDATORY for known violations that raise a substantial question of honesty, trustworthiness, or fitness — the profession’s self-policing obligation. The report goes to the OED Director; the exception is information protected by the practitioner’s own 11.106 confidentiality duty.',
  },
  {
    id: 'pb_gf0_001', topicId: 0, subtopic: 'aia_102_categories', difficulty: 1,
    question: 'Under AIA 35 U.S.C. 102(a)(1), a person is not entitled to a patent if, before the effective filing date, the claimed invention was:',
    options: [
      'Known to any single person anywhere.',
      'Patented, described in a printed publication, in public use, on sale, or OTHERWISE AVAILABLE TO THE PUBLIC.',
      'Conceived by another who was diligent.',
      'Described in an abandoned unpublished application.',
      'Independently invented by another, even in secret.',
    ],
    correct: 1,
    explanation: 'AIA 102(a)(1) lists the public-domain categories — patents, printed publications, public use, on sale — and adds the catch-all "otherwise available to the public," with no geographic limits. Secret knowledge, private conception, and unpublished abandoned applications are not 102(a)(1) art.',
  },
  {
    id: 'pb_gf0_002', topicId: 0, subtopic: 'grace_period', difficulty: 1,
    question: 'An inventor publishes a paper fully describing her invention, then files a U.S. application eight months later. Under 35 U.S.C. 102(b)(1)(A), her own paper:',
    options: [
      'Is NOT prior art against her application — a disclosure made by the inventor (or one who obtained it from the inventor) one year or less before the effective filing date falls within the grace period.',
      'Is prior art that anticipates her claims.',
      'Is prior art unless she disclaims its content.',
      'Bars the application unless she files a declaration of prior invention.',
      'Is prior art in the U.S. but not abroad.',
    ],
    correct: 0,
    explanation: '102(b)(1)(A): the AIA grace period shields the inventor’s own disclosures (and disclosures derived from the inventor) made within one year before the effective filing date. Beware: most foreign systems have no comparable grace period — the paper may still destroy foreign rights.',
  },
  {
    id: 'pb_gf0_003', topicId: 0, subtopic: 'on_sale_bar', difficulty: 3,
    question: 'More than one year before its effective filing date, a company sold its new drug formulation to a distributor under a confidentiality agreement; the sale was announced but the formulation kept secret. Under Helsinn v. Teva, the sale:',
    options: [
      'Is not prior art because the details were confidential.',
      'Is prior art only if the distributor resold to the public.',
      'Counts only as 102(a)(2) secret art.',
      'PLACES the invention "on sale" under AIA 102(a)(1) — a commercial sale to a third party who is required to keep the invention confidential can still trigger the on-sale bar.',
      'Is excused as experimental use.',
    ],
    correct: 3,
    explanation: 'Helsinn (2019): the AIA did not change the settled meaning of "on sale" — a commercial sale or offer for sale suffices even if the invention’s details remain confidential. The catch-all "otherwise available to the public" did not narrow the on-sale bar to public-disclosing sales.',
  },
  {
    id: 'pb_gf0_004', topicId: 0, subtopic: 'public_use', difficulty: 2,
    question: 'An inventor laid his experimental wooden pavement in a public toll road and monitored its durability for six years before filing. Under the doctrine of City of Elizabeth v. American Nicholson Pavement, this use:',
    options: [
      'Was a barring public use because the public drove on it.',
      'Was a barring public use after the first year.',
      'Was EXPERIMENTAL USE — a bona fide effort to test and perfect the invention, under the inventor’s surveillance, negates "public use" even though the testing occurred in public.',
      'Was excused only because the road was tolled.',
      'Transferred the invention to the public domain by dedication.',
    ],
    correct: 2,
    explanation: 'City of Elizabeth: genuine experimentation — durability testing that could only happen on a real road, monitored by the inventor — is not invalidating public use. The touchstones are the inventor’s control and the testing purpose; market testing of consumer demand, by contrast, does not qualify.',
  },
  {
    id: 'pb_gf0_005', topicId: 0, subtopic: 'printed_publication', difficulty: 2,
    question: 'Which of the following is most likely a "printed publication" under 35 U.S.C. 102?',
    options: [
      'A confidential internal memo circulated to five employees under NDA.',
      'An encrypted file on a private server.',
      'A handwritten notebook locked in the inventor’s desk.',
      'A grant proposal held confidentially by a funding agency.',
      'A single doctoral thesis, cataloged and indexed by subject in a university library so that the interested public could locate it.',
    ],
    correct: 4,
    explanation: 'The printed-publication touchstone is PUBLIC ACCESSIBILITY — In re Hall held one indexed, shelved thesis sufficient because an interested researcher exercising reasonable diligence could find it. Confidential and access-restricted materials are not publicly accessible. (Even a temporarily displayed conference poster can qualify — In re Klopfenstein.)',
  },
  {
    id: 'pb_gf0_006', topicId: 0, subtopic: 'aia_102a2', difficulty: 3,
    question: 'A competitor’s U.S. application, FILED before your client’s effective filing date but PUBLISHED after it, describes (without claiming) your client’s invention. Under AIA 102, the competitor’s application:',
    options: [
      'Is not prior art because it published after your client’s filing.',
      'Is prior art only for obviousness.',
      'Is prior art only if it issues as a patent within a year.',
      'Cannot be removed by any exception.',
      'IS prior art under 102(a)(2) as of the date it was EFFECTIVELY FILED — though it is removed if the subject matter was obtained from your client’s inventor, was previously publicly disclosed by that inventor, or was commonly owned no later than your client’s effective filing date (102(b)(2)(A)-(C)).',
    ],
    correct: 4,
    explanation: '102(a)(2) is the AIA’s "secret prior art": U.S. patents and published applications (including WIPO-published PCTs designating the U.S.) count from their effectively-filed date, not their publication date. The 102(b)(2) exceptions — derivation from the inventor, prior inventor disclosure, and common ownership — are the escape routes.',
  },
  {
    id: 'pb_gf0_007', topicId: 0, subtopic: 'obviousness', difficulty: 1,
    question: 'The factual inquiries underlying an obviousness determination under Graham v. John Deere are:',
    options: [
      'Commercial success, licensing, and copying only.',
      'The examiner’s experience and the art unit’s allowance rate.',
      'Long-felt need and failure of others only.',
      'The scope and content of the prior art; the differences between the prior art and the claims; the level of ordinary skill in the pertinent art; and objective evidence of nonobviousness (secondary considerations).',
      'Whether any single reference shows every element.',
    ],
    correct: 3,
    explanation: 'Graham’s framework: prior-art scope/content, claim-versus-art differences, level of ordinary skill, plus secondary considerations (commercial success, long-felt need, failure of others, etc.). Single-reference-shows-all is ANTICIPATION (102), not obviousness.',
  },
  {
    id: 'pb_gf0_008', topicId: 0, subtopic: 'obviousness', difficulty: 2,
    question: 'Under KSR v. Teleflex, an examiner supporting an obviousness rejection:',
    options: [
      'Must find an explicit teaching, suggestion, or motivation in the references themselves.',
      'May not combine more than two references.',
      'Need not apply a rigid teaching-suggestion-motivation test — common sense, design incentives, and "obvious to try" (choosing from a finite number of identified, predictable solutions with a reasonable expectation of success) can supply the reason to combine, articulated with reasoning.',
      'May rely on hindsight reconstruction of the invention.',
      'Must show the combination was commercially available.',
    ],
    correct: 2,
    explanation: 'KSR rejected the rigid TSM requirement: the analysis is flexible, and predictable variations, market forces, and obvious-to-try logic can render claims obvious — but the examiner must still articulate reasoning with rational underpinning (no naked hindsight), per MPEP 2143.',
  },
  {
    id: 'pb_gf0_009', topicId: 0, subtopic: 'obviousness', difficulty: 2,
    question: 'To rebut an obviousness rejection with evidence of commercial success, the applicant must show:',
    options: [
      'Gross revenue exceeding an Office threshold.',
      'A NEXUS — that the success is attributable to the claimed invention’s merits rather than to unclaimed features, marketing, or market position.',
      'Success in at least two countries.',
      'That competitors have taken licenses at any price.',
      'Nothing further; sales figures speak for themselves.',
    ],
    correct: 1,
    explanation: 'Objective indicia carry weight only with a nexus to the claimed subject matter (MPEP 716.03). Sales driven by advertising, brand, or features outside the claims prove nothing about nonobviousness. The same nexus requirement applies to long-felt need, praise, licensing, and copying evidence.',
  },
  {
    id: 'pb_gf0_010', topicId: 0, subtopic: 'analogous_art', difficulty: 2,
    question: 'A reference qualifies as ANALOGOUS prior art for obviousness purposes if it is:',
    options: [
      'From the same field of endeavor as the claimed invention, OR — even if from a different field — reasonably pertinent to the particular problem the inventor was trying to solve.',
      'From the same patent classification subclass only.',
      'Less than twenty years old.',
      'Cited in at least one other patent in the field.',
      'Authored by a person of ordinary skill.',
    ],
    correct: 0,
    explanation: 'The two-prong analogous-art test (In re Bigio; MPEP 2141.01(a)): same field of endeavor, or reasonably pertinent to the inventor’s problem. A hair-brush reference can be analogous art against a toothbrush claim; classification and age are at most secondary indicators.',
  },
  {
    id: 'pb_gf0_011', topicId: 0, subtopic: 'eligibility', difficulty: 1,
    question: 'The statutory categories of patent-eligible subject matter under 35 U.S.C. 101 are:',
    options: [
      'Process, machine, manufacture, and composition of matter (plus improvements thereof) — subject to the judicially created exceptions for laws of nature, natural phenomena, and abstract ideas.',
      'Apparatus, method, system, and software.',
      'Anything under the sun, without exception.',
      'Products only, not processes.',
      'Machines and compositions only.',
    ],
    correct: 0,
    explanation: '101 names four categories — process, machine, manufacture, composition of matter — and the courts overlay three exceptions: laws of nature, natural phenomena, and abstract ideas. "Anything under the sun that is made by man" (Chakrabarty) describes the categories’ breadth but does not erase the exceptions.',
  },
  {
    id: 'pb_gf0_012', topicId: 0, subtopic: 'eligibility', difficulty: 2,
    question: 'The Alice/Mayo framework for subject-matter eligibility asks:',
    options: [
      'Whether the claim is novel, then whether it is nonobvious.',
      'Whether the invention is technological, then whether it is useful.',
      'FIRST, whether the claim is directed to a judicial exception (law of nature, natural phenomenon, abstract idea); and IF SO, whether the claim’s additional elements — individually and as an ordered combination — supply an INVENTIVE CONCEPT amounting to significantly more than the exception itself.',
      'Whether a machine or transformation is present, which is dispositive.',
      'Whether the specification discloses source code.',
    ],
    correct: 2,
    explanation: 'The two-step Alice/Mayo test (administered in prosecution through MPEP 2106’s Step 2A/2B): identify direction to an exception, then look for significantly more. Well-understood, routine, conventional activity appended to an exception does not confer eligibility; the machine-or-transformation test is a useful clue, not dispositive.',
  },
  {
    id: 'pb_gf0_013', topicId: 0, subtopic: 'eligibility', difficulty: 3,
    question: 'Under Association for Molecular Pathology v. Myriad Genetics, claims to isolated naturally occurring genomic DNA and claims to cDNA are, respectively:',
    options: [
      'Both patent-eligible.',
      'Both patent-ineligible.',
      'Eligible only if claimed as methods.',
      'Eligible and ineligible depending on the length of the sequence.',
      'INELIGIBLE (isolated genomic DNA is a product of nature — isolation alone does not create eligibility) and ELIGIBLE (cDNA’s exons-only sequence is not naturally occurring, except for very short segments indistinguishable from natural DNA).',
    ],
    correct: 4,
    explanation: 'Myriad (2013): merely isolating a natural genomic sequence does not make it patent-eligible, but lab-synthesized cDNA — with introns removed — is a non-natural molecule and eligible. The case is the modern anchor of product-of-nature analysis (MPEP 2106.04(b)-(c)).',
  },
  {
    id: 'pb_gf0_014', topicId: 0, subtopic: 'eligibility', difficulty: 2,
    question: 'In Diamond v. Chakrabarty, the Supreme Court held that a live, genetically engineered bacterium capable of breaking down crude oil was:',
    options: [
      'Ineligible because living things are products of nature.',
      'Eligible only under the Plant Patent Act.',
      'Ineligible absent congressional authorization for life patents.',
      'PATENT-ELIGIBLE subject matter — a nonnaturally occurring manufacture or composition of matter, a product of human ingenuity with markedly different characteristics from anything found in nature.',
      'Eligible only as a trade secret.',
    ],
    correct: 3,
    explanation: 'Chakrabarty (1980): the line is not living-versus-inanimate but natural-versus-made — the engineered bacterium had markedly different characteristics from any found in nature. The "markedly different characteristics" inquiry remains the USPTO’s product-of-nature screen today.',
  },
  {
    id: 'pb_gf0_015', topicId: 0, subtopic: 'written_description', difficulty: 2,
    question: 'Under 35 U.S.C. 112(a), the WRITTEN DESCRIPTION requirement — as distinct from enablement — asks whether:',
    options: [
      'The claims are supported by working examples.',
      'The specification reasonably conveys to those skilled in the art that the inventor had POSSESSION of the claimed subject matter as of the filing date — a requirement separate from teaching how to make and use it.',
      'The best mode is disclosed.',
      'The claims use antecedent basis correctly.',
      'The applicant deposited biological material.',
    ],
    correct: 1,
    explanation: 'Ariad v. Eli Lilly (en banc): written description and enablement are separate 112(a) requirements. Written description = possession shown by the disclosure (especially sharp for later-added or genus claims); enablement = teaching skilled artisans to make and use without undue experimentation. Working examples help but are not categorically required.',
  },
  {
    id: 'pb_gf0_016', topicId: 0, subtopic: 'enablement', difficulty: 2,
    question: 'Whether a disclosure requires "undue experimentation" — defeating enablement — is analyzed using the In re Wands factors, which include:',
    options: [
      'The commercial value of the invention and the size of the market.',
      'The number of claims and length of the specification.',
      'The applicant’s diligence during prosecution.',
      'The quantity of experimentation necessary, amount of direction or guidance presented, presence or absence of working examples, nature of the invention, state of the prior art, relative skill in the art, predictability of the art, and breadth of the claims.',
      'The examiner’s workload and the art unit’s backlog.',
    ],
    correct: 3,
    explanation: 'The eight Wands factors (MPEP 2164.01(a)) frame the undue-experimentation inquiry — some experimentation is fine, even considerable, if routine; broad claims in unpredictable arts with thin guidance are where enablement rejections live. Commercial factors and prosecution conduct are irrelevant.',
  },
  {
    id: 'pb_gf0_017', topicId: 0, subtopic: 'best_mode', difficulty: 3,
    question: 'Post-AIA, the BEST MODE requirement of 35 U.S.C. 112(a):',
    options: [
      'REMAINS a statutory requirement for the application — but failure to disclose the best mode is no longer a basis for invalidating, canceling, or holding unenforceable any patent claim (35 U.S.C. 282(b)(3)(A)).',
      'Was deleted from the statute entirely.',
      'Is now the primary invalidity defense in litigation.',
      'Applies only to design patents.',
      'Requires updating the disclosure as better modes are found after filing.',
    ],
    correct: 0,
    explanation: 'The AIA left best mode in 112(a) — applicants must still disclose the best mode contemplated AT FILING (no updating duty) — but removed its teeth in litigation via 282(b)(3)(A). In practice examiners rarely can police it, but it remains a formal filing requirement.',
  },
  {
    id: 'pb_gf0_018', topicId: 0, subtopic: 'definiteness', difficulty: 2,
    question: '35 U.S.C. 112(b) requires that claims particularly point out and distinctly claim the invention. The Supreme Court’s definiteness standard (Nautilus v. Biosig) asks whether the claims, read in light of the specification and prosecution history:',
    options: [
      'Are amenable to any construction at all.',
      'Inform those skilled in the art about the scope of the invention with REASONABLE CERTAINTY — absolute precision is unattainable and not required, but zones of uncertainty are intolerable.',
      'Are insolubly ambiguous.',
      'Use only terms defined in the specification.',
      'Avoid all relative terminology such as "about."',
    ],
    correct: 1,
    explanation: 'Nautilus replaced the "insolubly ambiguous" formulation with reasonable certainty. Relative terms ("about," "substantially") are not automatically indefinite — the question is whether the skilled artisan can fix the scope. (In prosecution, examiners also test clarity against the broadest reasonable interpretation, MPEP 2173.)',
  },
  {
    id: 'pb_gf0_019', topicId: 0, subtopic: 'means_plus_function', difficulty: 3,
    question: 'A claim recites "means for fastening the panel to the frame" and the specification discloses only a spring clip as the fastening structure. Under 35 U.S.C. 112(f), the limitation covers:',
    options: [
      'Every fastening device known in the art.',
      'Only the exact spring clip shown in the drawings.',
      'Nothing — means-plus-function claims are invalid per se.',
      'Any structure with the same function, regardless of equivalence.',
      'The spring clip described in the specification AND ITS EQUIVALENTS — means-plus-function limitations are construed to cover the corresponding structure disclosed in the specification and equivalents thereof; with NO corresponding structure disclosed, the claim would be indefinite.',
    ],
    correct: 4,
    explanation: '112(f) trades broad functional wording for scope tethered to the disclosed corresponding structure plus equivalents. The bargain has a trap: no corresponding structure in the specification means no discernible scope — indefiniteness under 112(b) (MPEP 2181).',
  },
  {
    id: 'pb_gf0_020', topicId: 0, subtopic: 'utility', difficulty: 2,
    question: 'To satisfy the utility requirement of 35 U.S.C. 101 under the Office’s guidelines, a claimed invention must have a utility that is:',
    options: [
      'Commercially proven at the time of filing.',
      'Superior to existing alternatives.',
      'SPECIFIC to the subject matter claimed, SUBSTANTIAL (a real-world use, not requiring further research to identify one), and CREDIBLE to a person of ordinary skill in view of the disclosure.',
      'Approved by a regulatory agency where applicable.',
      'Demonstrated by in-human data for pharmaceutical claims.',
    ],
    correct: 2,
    explanation: 'MPEP 2107: specific, substantial, credible. In re Fisher applied it to reject ESTs claimed only as generic research probes — a "throw-away" research utility is not substantial. Commercial success, superiority, and regulatory approval have never been required.',
  },
  {
    id: 'pb_gf0_021', topicId: 0, subtopic: 'inventorship', difficulty: 2,
    question: 'Which correctly states the law of INVENTORSHIP?',
    options: [
      'Whoever performs the experiments is an inventor.',
      'The supervisor of the laboratory is presumptively an inventor.',
      'Inventorship turns on CONCEPTION — a joint inventor must contribute to the conception of at least one claim; joint inventors need not work together physically, at the same time, or make equal contributions (35 U.S.C. 116).',
      'Only the first-named inventor has enforceable rights.',
      'Anyone who funds the research may be named.',
    ],
    correct: 2,
    explanation: 'Conception — the definite and permanent idea of the complete operative invention — is the touchstone. 116(a) expressly liberalizes joint invention: no same-place, same-time, or equal-contribution requirement; contribution to one claim suffices. Pure reduction to practice at another’s direction, supervision alone, and funding do not make inventors.',
  },
  {
    id: 'pb_gf0_022', topicId: 0, subtopic: 'derivation', difficulty: 3,
    question: 'Before your client filed, a colleague to whom the inventor had privately explained the invention published its details without authorization. Under AIA 102(b)(1)(A), the colleague’s publication:',
    options: [
      'Bars the application as a third-party disclosure.',
      'IS NOT prior art — the grace-period exception covers disclosures by one who OBTAINED the subject matter directly or indirectly FROM the inventor, made one year or less before the effective filing date (a true independent third-party disclosure, by contrast, would not be excepted under (b)(1)(A)).',
      'Is prior art unless the colleague retracts it.',
      'Requires abandoning and refiling.',
      'Converts the application to a derivation proceeding automatically.',
    ],
    correct: 1,
    explanation: '102(b)(1)(A) shields not only the inventor’s own disclosures but those of anyone who obtained the subject matter from the inventor — the leak/derivation shield. (Where a deriver improperly FILES an application, the remedy is a 135 derivation proceeding, which must be sought within one year of the deriver’s claim publication.)',
  },
  {
    id: 'pb_gf0_023', topicId: 0, subtopic: 'double_patenting', difficulty: 3,
    question: 'An applicant’s second application claims the IDENTICAL invention claimed in her issued patent. The rejection, and its cure, are:',
    options: [
      'Obviousness-type double patenting; file a terminal disclaimer.',
      'Anticipation under 102; antedate the patent.',
      'Improper — an inventor may claim the same invention twice.',
      'Restriction; elect one application.',
      'STATUTORY (same-invention) double patenting under 35 U.S.C. 101 ("A patent" means one) — and it CANNOT be overcome by a terminal disclaimer; the claims must be canceled or amended to differ.',
    ],
    correct: 4,
    explanation: 'Same-invention double patenting flows from 101’s singular "a patent" and admits no terminal-disclaimer cure — only NONSTATUTORY (obviousness-type) double patenting, for merely obvious variants, can be defused by a 1.321(c)/(d) terminal disclaimer. Distinguishing the two rejections and their cures is a perennial exam point.',
  },
  {
    id: 'pb_gf0_024', topicId: 0, subtopic: 'effective_filing_date', difficulty: 2,
    question: 'Under 35 U.S.C. 100(i), the "effective filing date" of a claimed invention — the date against which AIA prior art is measured — is:',
    options: [
      'The actual filing date of the application containing the claim, OR, if the application is entitled to priority or benefit of an earlier application (119, 120, 121, 365, 386) that supports the claim, the filing date of the EARLIEST such application.',
      'Always the actual U.S. filing date, ignoring priority.',
      'The date of conception if diligently reduced to practice.',
      'The international publication date for PCT-derived cases.',
      'The date the inventor first disclosed the invention publicly.',
    ],
    correct: 0,
    explanation: '100(i) makes the effective filing date claim-specific: the earliest priority/benefit filing that provides 112(a) support for that claim. Conception dates died with first-to-invent; each claim’s prior-art universe is fixed by its own effective filing date — which is why priority-chain support matters so much under the AIA.',
  },
  {
    id: 'pb_gf2_001', topicId: 2, subtopic: 'issue_fee', difficulty: 2,
    question: 'A Notice of Allowance mails on June 1 setting the issue fee due. The applicant asks whether the payment deadline can be extended. The issue fee:',
    options: [
      'May be extended up to five months under 37 CFR 1.136(a).',
      'May be extended two months for cause under 1.136(b).',
      'Has no fixed deadline while the application is allowed.',
      'Must be paid within THREE MONTHS of the notice, and that period is STATUTORY and NOT extendable (35 U.S.C. 151) — late payment leads to abandonment, curable only by revival for unintentional delay.',
      'Is due at issuance, whenever that occurs.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 151: the issue fee is due within 3 months of the Notice of Allowance, and 1.136 extensions do NOT apply to statutory periods. Miss it and the application is abandoned; the path back is a 1.137 petition to revive (unintentional standard). A favorite trap against the usual 1.136(a) reflex.',
  },
];
