/**
 * Patent Bar — WS3 gap-fill: Ethics & Professional Conduct (topicId 7).
 *
 * 65 AI-authored questions closing the largest blueprint coverage gap
 * (ethics was 7.3% of the bank vs its 15% blueprint weight — see
 * docs/monetization/PATENT_BAR_COVERAGE_MATRIX.md). Grounded in the USPTO
 * Rules of Professional Conduct (37 CFR Part 11, the post-2013 rules) and
 * the duty of disclosure (37 CFR 1.56). All original compositions.
 *
 * VERIFICATION STATUS: every item here is 'unverified' (AI-authored,
 * pending SME review via /dashboard/test-prep/patent_bar/review-queue).
 * None may appear in a scored mock until reviewed. Answer keys are
 * deliberately balanced (13 per option position; asserted by
 * qbank-key-balance.test.ts).
 */

import type { PatentBarQuestion } from './patent-bar-qbank-data';

export const PATENT_BAR_GAPFILL_ETHICS: PatentBarQuestion[] = [
  {
    id: 'pb_gf7_001', topicId: 7, subtopic: 'ethics_competence', difficulty: 1,
    question: 'Under 37 CFR 11.101, competent representation of a client before the USPTO requires:',
    options: [
      'Only the legal knowledge reasonably necessary for the representation.',
      'A minimum of five years of patent prosecution experience.',
      'The legal, scientific, and technical knowledge, skill, thoroughness, and preparation reasonably necessary for the representation.',
      'A technical degree in the specific field of the client’s invention.',
      'Certification by the OED Director in the relevant technology area.',
    ],
    correct: 2,
    explanation: 'Competence under 37 CFR 11.101 expressly includes the LEGAL, SCIENTIFIC, AND TECHNICAL knowledge, skill, thoroughness and preparation reasonably necessary for the representation — patent practice adds the scientific/technical dimension to the usual competence standard. No specific years of experience, field-specific degree, or special certification is required.',
  },
  {
    id: 'pb_gf7_002', topicId: 7, subtopic: 'ethics_diligence', difficulty: 1,
    question: 'A registered practitioner receives an Office action with a three-month shortened statutory period but does not begin work or inform the client until the sixth month, requiring extension fees. Which rule is most directly implicated?',
    options: [
      '37 CFR 11.103, which requires a practitioner to act with reasonable diligence and promptness in representing a client.',
      '37 CFR 11.505, which prohibits the unauthorized practice of law.',
      '37 CFR 11.701, which governs communications concerning a practitioner’s services.',
      '37 CFR 11.115, which governs safekeeping of client property.',
      '37 CFR 11.303, which governs candor toward the tribunal.',
    ],
    correct: 0,
    explanation: '37 CFR 11.103 requires reasonable diligence and promptness. Sitting on an Office action so long that avoidable extension fees accrue — without informing the client — is the classic diligence failure (and implicates the 11.104 communication duty as well).',
  },
  {
    id: 'pb_gf7_003', topicId: 7, subtopic: 'ethics_communication', difficulty: 2,
    question: 'Under 37 CFR 11.104, a practitioner prosecuting a patent application must:',
    options: [
      'Promptly inform the client of any decision requiring the client’s informed consent.',
      'Keep the client reasonably informed about the status of the application.',
      'Promptly comply with reasonable requests for information from the client.',
      'Explain matters to the extent reasonably necessary for the client to make informed decisions.',
      'All of the above.',
    ],
    correct: 4,
    explanation: '37 CFR 11.104 imposes all four duties: prompt notice of matters requiring informed consent, reasonable status updates (including received Office actions), prompt compliance with reasonable information requests, and explanation sufficient for informed client decisions.',
  },
  {
    id: 'pb_gf7_004', topicId: 7, subtopic: 'ethics_scope', difficulty: 2,
    question: 'A client instructs a practitioner to pursue broad claims the practitioner believes are unlikely to be allowed. Under 37 CFR 11.102, the practitioner:',
    options: [
      'Must withdraw immediately, since the client is directing prosecution strategy.',
      'Must abide by the client’s decisions concerning the objectives of the representation, while consulting with the client as to the means.',
      'May ignore the client’s instruction because claim strategy is solely the practitioner’s decision.',
      'Must report the disagreement to the OED Director.',
      'May file the broad claims only if the client signs a malpractice waiver.',
    ],
    correct: 1,
    explanation: 'Under 37 CFR 11.102 the CLIENT controls the objectives of the representation and the practitioner consults on the means. Pursuing broader protection is a legitimate client objective; the practitioner advises but does not override it (and may limit the scope of representation only with the client’s informed consent).',
  },
  {
    id: 'pb_gf7_005', topicId: 7, subtopic: 'ethics_communication', difficulty: 2,
    question: 'A practitioner receives a Notice of Allowance but decides not to tell the client until after the issue fee deadline has passed because the client owes fees. This conduct most directly violates:',
    options: [
      'Nothing — a practitioner may withhold communications until outstanding bills are paid.',
      '37 CFR 11.108, prohibiting business transactions with clients.',
      '37 CFR 11.703, governing solicitation of clients.',
      'The duties of communication and diligence (37 CFR 11.104, 11.103), because withholding a deadline-critical communication can forfeit the client’s rights.',
      '37 CFR 11.902, requiring arbitration of fee disputes.',
    ],
    correct: 3,
    explanation: 'A fee dispute never justifies concealing a deadline-critical development. Failing to relay a Notice of Allowance before the issue-fee deadline violates the communication duty of 37 CFR 11.104 and the diligence duty of 11.103, and can abandon the application to the client’s severe prejudice.',
  },
  {
    id: 'pb_gf7_006', topicId: 7, subtopic: 'ethics_fees', difficulty: 2,
    question: 'Which factor is among those relevant to whether a fee is reasonable under 37 CFR 11.105?',
    options: [
      'The client’s annual revenue.',
      'The time and labor required, the novelty and difficulty of the questions involved, and the skill requisite to perform the service properly.',
      'The number of other clients the practitioner represents.',
      'Whether the client is a small entity under 37 CFR 1.27.',
      'The practitioner’s law school class rank.',
    ],
    correct: 1,
    explanation: '37 CFR 11.105(a) lists reasonableness factors including the time and labor required, novelty and difficulty of the questions, requisite skill, customary fees, results obtained, time limitations, the professional relationship, experience/reputation/ability, and whether the fee is fixed or contingent.',
  },
  {
    id: 'pb_gf7_007', topicId: 7, subtopic: 'ethics_fees', difficulty: 3,
    question: 'Regarding contingent fees for patent prosecution before the USPTO, which statement is most accurate?',
    options: [
      'Contingent fees are prohibited in all matters before the Office.',
      'Contingent fees are permitted only in reexamination proceedings.',
      'Contingent fees require approval by the OED Director.',
      'Contingent fees are permitted only for small-entity clients.',
      'A contingent fee is permitted if it is in a writing signed by the client that states the method by which the fee is to be determined.',
    ],
    correct: 4,
    explanation: 'Under 37 CFR 11.105(c), a fee may be contingent on the outcome (except where prohibited, e.g., domestic-relations and criminal-defense matters, which do not arise in patent prosecution) provided the agreement is in a writing signed by the client stating how the fee will be determined and what expenses are deducted.',
  },
  {
    id: 'pb_gf7_008', topicId: 7, subtopic: 'ethics_safekeeping', difficulty: 2,
    question: 'Under 37 CFR 11.115, funds of a client held by a practitioner in connection with a representation must be:',
    options: [
      'Kept in a separate account, with complete records maintained for five years after termination of the representation.',
      'Deposited into the practitioner’s operating account for ease of billing.',
      'Invested in interest-bearing instruments for the practitioner’s benefit.',
      'Forwarded to the USPTO as advance fee deposits.',
      'Held in cash in the practitioner’s office safe.',
    ],
    correct: 0,
    explanation: '37 CFR 11.115(a) requires client funds to be held separate from the practitioner’s own property, with complete records kept for five years after termination of the representation. Commingling client funds with the practitioner’s own is a classic safekeeping violation.',
  },
  {
    id: 'pb_gf7_009', topicId: 7, subtopic: 'ethics_fees', difficulty: 2,
    question: 'A client terminates the representation after paying a $10,000 advance, of which only $4,000 has been earned. The practitioner must:',
    options: [
      'Keep the full advance as liquidated damages for the termination.',
      'Keep the full advance if the fee agreement is silent on refunds.',
      'Apply the unearned $6,000 to any future work the client might request.',
      'Promptly refund the unearned $6,000 to the client.',
      'Deposit the unearned portion with the USPTO.',
    ],
    correct: 3,
    explanation: 'Upon termination, 37 CFR 11.116(d) requires the practitioner to refund any advance payment of fee or expense that has not been earned or incurred. Client discharge does not convert unearned fees into the practitioner’s property.',
  },
  {
    id: 'pb_gf7_010', topicId: 7, subtopic: 'ethics_safekeeping', difficulty: 3,
    question: 'A practitioner holds settlement-related funds in which both the practitioner (for fees) and the client claim an interest, and the amounts are disputed. Under 37 CFR 11.115, the practitioner should:',
    options: [
      'Transfer the entire amount to the practitioner’s operating account until the dispute resolves.',
      'Release the entire amount to the client to avoid any appearance of impropriety.',
      'Distribute the undisputed portions and keep the disputed portion separate until the dispute is resolved.',
      'Split the disputed amount evenly between practitioner and client.',
      'Interplead the funds with the OED Director.',
    ],
    correct: 2,
    explanation: 'Under 37 CFR 11.115(e), when two or more persons claim interests in held property, the disputed portion must be kept separate until the dispute is resolved, while undisputed portions are promptly distributed to those entitled to them.',
  },
  {
    id: 'pb_gf7_011', topicId: 7, subtopic: 'ethics_confidentiality', difficulty: 2,
    question: 'Under 37 CFR 11.106, a practitioner may reveal information relating to the representation of a client without the client’s informed consent:',
    options: [
      'Whenever the information would be helpful to another client.',
      'Whenever the information is more than ten years old.',
      'Only after the client’s death.',
      'To the extent reasonably necessary to prevent reasonably certain death or substantial bodily harm, among other enumerated exceptions.',
      'Never — the duty of confidentiality is absolute.',
    ],
    correct: 3,
    explanation: '37 CFR 11.106(b) enumerates exceptions permitting disclosure reasonably necessary to, e.g., prevent reasonably certain death or substantial bodily harm, prevent client crime or fraud using the practitioner’s services, secure legal ethics advice, establish a defense in a controversy with the client, or comply with law or a court order.',
  },
  {
    id: 'pb_gf7_012', topicId: 7, subtopic: 'ethics_duty_disclosure', difficulty: 2,
    question: 'A client tells the practitioner about a material prior art reference but instructs the practitioner to keep it confidential and not cite it to the USPTO. The practitioner should advise that:',
    options: [
      'The instruction controls — client confidentiality overrides all other duties.',
      'The reference may be withheld if it is a foreign-language document.',
      'Confidentiality does not excuse compliance with the duty of disclosure — 37 CFR 11.106(c) requires disclosure to the Office of information necessary to comply with 37 CFR 1.56, and prosecution cannot ethically continue while withholding it.',
      'The reference need only be disclosed if the examiner asks for it.',
      'The practitioner may cite the reference anonymously through a third party.',
    ],
    correct: 2,
    explanation: '37 CFR 11.106(c) expressly requires a practitioner to disclose to the Office information necessary to comply with the duty of disclosure (37 CFR 1.56). If the client insists on withholding material information, the practitioner cannot continue prosecuting the application and must counsel the client accordingly (and consider withdrawal under 11.116).',
  },
  {
    id: 'pb_gf7_013', topicId: 7, subtopic: 'ethics_duty_disclosure', difficulty: 2,
    question: 'Under 37 CFR 1.56, the duty of candor and good faith in a patent application is owed by:',
    options: [
      'Only the registered practitioner prosecuting the application.',
      'Each named inventor, each practitioner who prepares or prosecutes the application, and every other person substantively involved in preparation or prosecution who is associated with the inventor or assignee.',
      'Only the assignee of record.',
      'Anyone who has ever read the specification.',
      'Only persons who sign papers filed in the application.',
    ],
    correct: 1,
    explanation: '37 CFR 1.56(c) defines the individuals owing the duty: each named inventor, each attorney or agent who prepares or prosecutes, and every other person substantively involved in the preparation or prosecution who is associated with the inventor, assignee, or anyone obligated to assign.',
  },
  {
    id: 'pb_gf7_014', topicId: 7, subtopic: 'ethics_duty_disclosure', difficulty: 3,
    question: 'Which statement about the 37 CFR 1.56 duty of disclosure is most accurate?',
    options: [
      'The duty ends when the Notice of Allowance is mailed.',
      'The duty extends only to United States patents and published applications.',
      'All information known to the applicant must be submitted, regardless of materiality.',
      'Information is material only if it would invalidate every claim.',
      'There is no duty to submit information that is cumulative to information already of record in the application.',
    ],
    correct: 4,
    explanation: '37 CFR 1.56(a) expressly excludes cumulative information: the duty covers information MATERIAL to patentability that is not cumulative to what is already of record. The duty runs while the application is pending (until the patent issues), covers all forms of material information, and materiality does not require invalidating force.',
  },
  {
    id: 'pb_gf7_015', topicId: 7, subtopic: 'ethics_confidentiality', difficulty: 3,
    question: 'A former client files a DOJ complaint and a malpractice suit alleging the practitioner botched a prosecution. May the practitioner reveal confidential representation information in response?',
    options: [
      'Yes — 37 CFR 11.106(b) permits disclosure to the extent reasonably necessary to establish a defense to the client’s allegations concerning the representation.',
      'No — the practitioner must remain silent and default.',
      'Yes, but only information that is already public.',
      'Only with a court order compelling each specific disclosure.',
      'Only if the client consents in writing to the disclosure.',
    ],
    correct: 0,
    explanation: 'The self-defense exception in 37 CFR 11.106(b) permits disclosure reasonably necessary to establish a claim or defense in a controversy between practitioner and client, or to respond to allegations concerning the representation. Disclosure is limited to what is reasonably necessary for the defense.',
  },
  {
    id: 'pb_gf7_016', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'Under 37 CFR 11.107, a practitioner may represent a client despite a concurrent conflict of interest only if:',
    options: [
      'The practitioner reasonably believes competent and diligent representation can be provided to each affected client, the representation is not prohibited by law, the clients are not adverse in the same proceeding, and each affected client gives informed consent, confirmed in writing.',
      'The practitioner discloses the conflict orally to both clients.',
      'The clients are related corporate entities.',
      'The fee is reduced for both clients.',
      'The OED Director approves the joint representation.',
    ],
    correct: 0,
    explanation: '37 CFR 11.107(b) permits representation despite a concurrent conflict only when all four conditions are met: reasonable belief in competent and diligent representation of each client, no legal prohibition, no claim by one client against another in the same proceeding, and informed consent from each affected client CONFIRMED IN WRITING.',
  },
  {
    id: 'pb_gf7_017', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'A practitioner who formerly prosecuted patent applications for Company X is asked by Company Y to challenge, in reexamination, a patent the practitioner personally obtained for X. Under 37 CFR 11.109, the practitioner:',
    options: [
      'May accept — the representation of X ended when the patent issued.',
      'May accept if the practitioner remembers nothing about the earlier work.',
      'Must accept, because reexamination serves the public interest.',
      'May not represent Y in this materially adverse, substantially related matter unless former client X gives informed consent, confirmed in writing.',
      'May accept if Y pays a premium fee reflecting the conflict.',
    ],
    correct: 3,
    explanation: 'Under 37 CFR 11.109(a), a practitioner who formerly represented a client may not represent another person in the SAME OR A SUBSTANTIALLY RELATED matter whose interests are MATERIALLY ADVERSE to the former client absent the former client’s informed consent confirmed in writing. Attacking a patent one personally prosecuted is the paradigm case.',
  },
  {
    id: 'pb_gf7_018', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 3,
    question: 'A practitioner wants to take a 5% equity stake in a startup client in lieu of prosecution fees. Under 37 CFR 11.108(a), the transaction is permissible only if:',
    options: [
      'The equity is worth less than $50,000.',
      'The startup’s board unanimously approves.',
      'The terms are fair and reasonable and fully disclosed in writing, the client is advised in writing to seek independent counsel and given the opportunity to do so, and the client gives informed consent in a signed writing covering the essential terms and the practitioner’s role.',
      'The practitioner resigns from all other representations of the client.',
      'Such transactions are categorically prohibited.',
    ],
    correct: 2,
    explanation: '37 CFR 11.108(a) permits business transactions with a client (including acquiring an ownership interest) only when the terms are fair, reasonable, and fully disclosed in an understandable writing; the client is advised in writing of the desirability of independent counsel and given a reasonable opportunity to seek it; and the client signs an informed consent covering the essential terms and whether the practitioner represents the client in the transaction.',
  },
  {
    id: 'pb_gf7_019', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 3,
    question: 'One partner in a firm has a personal financial investment in a company adverse to a prospective firm client. Under 37 CFR 11.110, the other practitioners in the firm:',
    options: [
      'Are all automatically disqualified in every case.',
      'May take the representation if the disqualification is based on the partner’s personal interest and does not present a significant risk of materially limiting the representation by the remaining practitioners.',
      'May take the representation only after the invested partner divests.',
      'May take the representation only with OED approval.',
      'Are disqualified unless the firm has fewer than ten practitioners.',
    ],
    correct: 1,
    explanation: 'Under 37 CFR 11.110(a), conflicts are generally imputed to the whole firm — EXCEPT where the prohibition rests on a personal interest of the disqualified practitioner and there is no significant risk that the representation by the remaining practitioners would be materially limited.',
  },
  {
    id: 'pb_gf7_020', topicId: 7, subtopic: 'ethics_prospective_client', difficulty: 3,
    question: 'An inventor consults a practitioner about an invention, shares technical details, but never retains the firm. Regarding the practitioner’s duties to this prospective client under 37 CFR 11.118:',
    options: [
      'No duties arise because no engagement was signed.',
      'The practitioner owes duties only if a consultation fee was charged.',
      'The information may be used freely after one year.',
      'The practitioner may represent the inventor’s competitor without restriction.',
      'The practitioner may not use or reveal the consultation information (with limited exceptions), and may be barred from representing a client with materially adverse interests in the same or a substantially related matter if the information received could be significantly harmful.',
    ],
    correct: 4,
    explanation: '37 CFR 11.118 protects prospective clients: information learned in the consultation may not be used or revealed (subject to the 11.109-type exceptions), and representation adverse to the prospective client in the same or a substantially related matter is barred where the information received could be significantly harmful — even though no engagement ever formed.',
  },
  {
    id: 'pb_gf7_021', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'An employer offers to pay a practitioner to prosecute an application naming its employee-inventor as the client. Under 37 CFR 11.108(f), the practitioner may accept compensation from the employer only if:',
    options: [
      'The employer signs the power of attorney.',
      'The employer is a small entity.',
      'The inventor-client waives all confidentiality as to the employer.',
      'The practitioner bills the employer at a discounted rate.',
      'The client gives informed consent, there is no interference with the practitioner’s independent judgment or the client relationship, and information relating to the representation remains protected under 37 CFR 11.106.',
    ],
    correct: 4,
    explanation: '37 CFR 11.108(f) allows accepting compensation from someone other than the client only with the client’s informed consent, no interference with the practitioner’s independence of professional judgment or the client-practitioner relationship, and preservation of confidentiality under 11.106.',
  },
  {
    id: 'pb_gf7_022', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 3,
    question: 'Which acquisition of an interest in a client’s patent matter is permitted under 37 CFR 11.108(i)?',
    options: [
      'Buying the client’s patent at a discount mid-prosecution without the 11.108(a) safeguards.',
      'A lien authorized by law to secure the practitioner’s fee or expenses, or a reasonable contingent fee contract.',
      'Taking a majority ownership stake in the invention as a condition of filing.',
      'A secret royalty on future sales of the patented product.',
      'An assignment of the application in exchange for waiving all fees, undisclosed to the client’s other counsel.',
    ],
    correct: 1,
    explanation: '37 CFR 11.108(i) prohibits acquiring a proprietary interest in the cause of action or subject matter of litigation/proceedings the practitioner is conducting for the client, EXCEPT a lien authorized by law to secure fees or expenses and a contract for a reasonable contingent fee.',
  },
  {
    id: 'pb_gf7_023', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'While still prosecuting an inventor’s high-profile application, a practitioner negotiates for the exclusive book and film rights to the inventor’s story. Under 37 CFR 11.108(d), this is:',
    options: [
      'Permitted if the rights are paid for at fair market value.',
      'Permitted because media rights are not a proprietary interest in the application.',
      'Permitted with oral consent from the inventor.',
      'Prohibited — a practitioner may not negotiate for literary or media rights based in substantial part on information relating to the representation before the representation concludes.',
      'Prohibited only if the application is under a secrecy order.',
    ],
    correct: 3,
    explanation: '37 CFR 11.108(d) flatly prohibits negotiating for literary or media rights to an account based in substantial part on information relating to the representation PRIOR TO the conclusion of the representation — the concern being that the practitioner’s judgment could be skewed toward a more dramatic (not better) outcome.',
  },
  {
    id: 'pb_gf7_024', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 3,
    question: 'Under 37 CFR 11.108(e), which financial assistance may a practitioner provide to a client in connection with contemplated or pending proceedings?',
    options: [
      'Advancing proceeding costs and expenses, with repayment contingent on the outcome — and paying such costs outright for an indigent client.',
      'A personal loan to cover the client’s living expenses during prosecution.',
      'Guaranteeing the client’s bank loan against future royalties.',
      'Paying the client a monthly stipend until the patent issues.',
      'Any assistance, as long as it is interest-free.',
    ],
    correct: 0,
    explanation: '37 CFR 11.108(e) limits financial assistance to (1) advancing costs and expenses of the proceeding, repayment of which may be contingent on the outcome, and (2) paying those costs and expenses outright for an indigent client. General living-expense support is not permitted.',
  },
  {
    id: 'pb_gf7_025', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 2,
    question: 'A grateful elderly client asks her practitioner to draft a will leaving the practitioner her patent portfolio. Under 37 CFR 11.108(c), the practitioner:',
    options: [
      'May draft the will if the gift is genuinely voluntary.',
      'May draft the will if a paralegal witnesses the signing.',
      'May not solicit a substantial gift from a client, nor prepare an instrument giving the practitioner a substantial gift, unless the practitioner is related to the client.',
      'May draft the will but must donate half the portfolio to charity.',
      'May draft the will after obtaining OED clearance.',
    ],
    correct: 2,
    explanation: '37 CFR 11.108(c) prohibits soliciting a substantial gift from a client and prohibits preparing an instrument that gives the practitioner (or a close relative of the practitioner) a substantial gift, unless the practitioner is related to the donee client. She would need independent counsel to draft such a will.',
  },
  {
    id: 'pb_gf7_026', topicId: 7, subtopic: 'ethics_candor', difficulty: 2,
    question: 'During an appeal before the PTAB, a practitioner realizes a statement of fact previously made to the Board was false. Under 37 CFR 11.303(a), the practitioner must:',
    options: [
      'Say nothing — the duty of candor only bars future false statements.',
      'Withdraw from the representation without comment.',
      'Correct the false statement of material fact previously made to the tribunal.',
      'Wait to see whether the Board relies on the statement.',
      'Disclose the falsity only if opposing counsel raises it.',
    ],
    correct: 2,
    explanation: '37 CFR 11.303(a)(1) prohibits knowingly making a false statement of fact or law to a tribunal AND requires correcting a false statement of material fact or law previously made. Silence after discovering the falsity continues the violation.',
  },
  {
    id: 'pb_gf7_027', topicId: 7, subtopic: 'ethics_candor', difficulty: 3,
    question: 'Patent prosecution is an ex parte proceeding. Which statement best captures the resulting candor obligation under 37 CFR 11.303?',
    options: [
      'Candor duties do not apply because there is no opposing party.',
      'The practitioner may present only the facts favorable to patentability.',
      'The examiner bears the entire burden of discovering unfavorable facts.',
      'Candor duties apply only in inter partes proceedings such as interferences.',
      'In an ex parte proceeding, the practitioner must inform the tribunal of all material facts known that will enable it to make an informed decision, whether or not the facts are adverse.',
    ],
    correct: 4,
    explanation: '37 CFR 11.303(d) imposes a heightened duty in ex parte proceedings: the practitioner must inform the tribunal of all material facts known to the practitioner that will enable an informed decision, whether or not the facts are adverse — which dovetails with the 37 CFR 1.56 duty of disclosure in prosecution.',
  },
  {
    id: 'pb_gf7_028', topicId: 7, subtopic: 'ethics_candor', difficulty: 3,
    question: 'Briefing an appeal to the PTAB, a practitioner knows of controlling Federal Circuit authority directly adverse to the client’s position; the examiner’s answer never cites it. Under 37 CFR 11.303(a)(2), the practitioner:',
    options: [
      'Must disclose to the tribunal legal authority in the controlling jurisdiction known to be directly adverse to the client’s position and not disclosed by opposing counsel.',
      'May remain silent — disclosing adverse authority would violate the duty of zealous advocacy.',
      'Must disclose the authority only if the Board requests supplemental briefing.',
      'May cite the authority in a footnote without discussion, which satisfies nothing further.',
      'Must withdraw from the appeal.',
    ],
    correct: 0,
    explanation: '37 CFR 11.303(a)(2) requires disclosure of controlling, directly adverse legal authority not disclosed by opposing counsel. Advocacy operates within candor: the practitioner may argue to distinguish the authority, but may not conceal it.',
  },
  {
    id: 'pb_gf7_029', topicId: 7, subtopic: 'ethics_certifications', difficulty: 2,
    question: 'Under 37 CFR 11.18(b), presenting a paper to the USPTO (whether or not the party signs it) certifies, among other things, that:',
    options: [
      'The paper was reviewed by at least two registered practitioners.',
      'The client has paid all outstanding fees.',
      'The paper is being filed within a statutory period.',
      'It is not being presented for an improper purpose, the positions are warranted by law or nonfrivolous argument, and factual contentions have (or are likely to have) evidentiary support.',
      'The paper was prepared without artificial-intelligence assistance.',
    ],
    correct: 3,
    explanation: '37 CFR 11.18(b) attaches Rule-11-style certifications to EVERY paper presented to the Office: statements are believed true (with false statements punishable under 18 USC 1001), the filing is not for delay or harassment, legal positions are warranted, and factual contentions have or are likely to have evidentiary support.',
  },
  {
    id: 'pb_gf7_030', topicId: 7, subtopic: 'ethics_certifications', difficulty: 3,
    question: 'Violating the 37 CFR 11.18(b) certifications can result in which consequence under 37 CFR 11.18(c)?',
    options: [
      'Only a private warning letter from the examiner.',
      'Sanctions including striking the offending paper, precluding a party from submitting papers or contesting issues, or terminating the proceedings in the Office.',
      'Automatic exclusion from practice for one year.',
      'Referral to the Federal Circuit for contempt.',
      'A mandatory continuing-education course.',
    ],
    correct: 1,
    explanation: '37 CFR 11.18(c) authorizes the Office to impose sanctions for 11.18(b) violations, including striking the paper, referring the practitioner’s conduct to the OED Director, precluding the party from submitting papers or contesting issues, affecting the weight given the paper, or terminating the proceedings — in addition to any disciplinary action.',
  },
  {
    id: 'pb_gf7_031', topicId: 7, subtopic: 'ethics_truthfulness', difficulty: 2,
    question: 'While negotiating with a third party on a client’s behalf, a practitioner is asked a direct factual question about the client’s issued patent. Under 37 CFR 11.401, the practitioner:',
    options: [
      'Must not knowingly make a false statement of material fact or law to the third person.',
      'May say anything, since the third party is not a client or tribunal.',
      'Must answer every question the third party asks, fully and completely.',
      'Must refer all factual questions to the client.',
      'May make false statements if they benefit the client.',
    ],
    correct: 0,
    explanation: '37 CFR 11.401 prohibits knowingly making a false statement of material fact or law to a THIRD PERSON in the course of representing a client, and requires disclosure of material fact when necessary to avoid assisting a client’s crime or fraud (subject to 11.106). Truthfulness duties are not limited to tribunals.',
  },
  {
    id: 'pb_gf7_032', topicId: 7, subtopic: 'ethics_candor', difficulty: 3,
    question: 'A practitioner offers a declaration in an application, then later learns the declaration contains material false test data. Under 37 CFR 11.303(a)(3), the practitioner must:',
    options: [
      'Do nothing if the practitioner did not know of the falsity when the declaration was filed.',
      'Quietly stop relying on the declaration in future arguments.',
      'Take reasonable remedial measures — including, if necessary, disclosure to the tribunal.',
      'File a continuation and abandon the tainted application without comment.',
      'Ask the client whether they prefer to correct the record.',
    ],
    correct: 2,
    explanation: 'Under 37 CFR 11.303(a)(3), a practitioner who comes to know that offered material evidence is false must take reasonable remedial measures, including disclosure to the tribunal if necessary. Silently ceasing reliance, or abandoning-and-refiling to bury the record, does not cure the fraud on the Office.',
  },
  {
    id: 'pb_gf7_033', topicId: 7, subtopic: 'ethics_misconduct', difficulty: 2,
    question: 'A practitioner signs and files a declaration under 37 CFR 1.132 containing experimental results the practitioner knows were never obtained. Beyond the application’s validity, the practitioner faces:',
    options: [
      'No personal exposure, since declarations speak only for the declarant.',
      'Only the possibility of an examiner interview.',
      'A patent term adjustment reduction.',
      'Discipline for conduct involving dishonesty, fraud, deceit or misrepresentation under 37 CFR 11.804(c), and potential criminal liability for false statements under 18 USC 1001.',
      'Suspension of the client’s other applications.',
    ],
    correct: 3,
    explanation: 'Knowingly submitting fabricated evidence is dishonesty within 37 CFR 11.804(c) (professional misconduct) and violates the 11.18(b)(1) certification, which expressly warns that willful false statements are punishable under 18 USC 1001 — personal disciplinary and criminal exposure, independent of the application’s fate.',
  },
  {
    id: 'pb_gf7_034', topicId: 7, subtopic: 'ethics_withdrawal', difficulty: 2,
    question: 'Under 37 CFR 11.116(a), a practitioner MUST withdraw from representing a client before the Office when:',
    options: [
      'The client questions the practitioner’s bills.',
      'The representation will result in violation of the USPTO Rules of Professional Conduct or other law.',
      'The practitioner’s physical or mental condition materially impairs the ability to represent the client.',
      'The practitioner is discharged by the client.',
      'Any of the above circumstances in (B), (C), or (D) exists.',
    ],
    correct: 4,
    explanation: '37 CFR 11.116(a) makes withdrawal MANDATORY in three situations: the representation will result in a violation of the conduct rules or other law; the practitioner’s physical or mental condition materially impairs the representation; or the practitioner is discharged. Fee grumbling alone is not among them.',
  },
  {
    id: 'pb_gf7_035', topicId: 7, subtopic: 'ethics_withdrawal', difficulty: 3,
    question: 'A client insists on using the practitioner’s services to submit data the practitioner reasonably believes is fraudulent. Withdrawal in this situation is:',
    options: [
      'Prohibited until the application is expressly abandoned.',
      'Permitted under 37 CFR 11.116(b) — a practitioner may withdraw when the client persists in a course of action involving the practitioner’s services that the practitioner reasonably believes is criminal or fraudulent.',
      'Permitted only after the OED Director consents.',
      'Mandatory only if the fraud has already been consummated.',
      'Prohibited because withdrawal would prejudice the client.',
    ],
    correct: 1,
    explanation: '37 CFR 11.116(b) permits withdrawal when, among other grounds, the client persists in a course of action involving the practitioner’s services that the practitioner reasonably believes is criminal or fraudulent, or has used the services to perpetrate a crime or fraud. If continuing would itself violate the rules, withdrawal becomes mandatory under 11.116(a).',
  },
  {
    id: 'pb_gf7_036', topicId: 7, subtopic: 'ethics_withdrawal', difficulty: 2,
    question: 'Upon termination of a representation, 37 CFR 11.116(d) requires the practitioner to:',
    options: [
      'Retain the client’s files for ransom until all invoices are paid.',
      'Destroy the client’s files within thirty days.',
      'Transfer the files only if the successor practitioner is from the same firm.',
      'Take steps reasonably practicable to protect the client’s interests — reasonable notice, time to employ other counsel, surrendering papers and property to which the client is entitled, and refunding unearned advances.',
      'File a continuation application to preserve the client’s rights.',
    ],
    correct: 3,
    explanation: '37 CFR 11.116(d) requires steps reasonably practicable to protect the client on the way out: reasonable notice, time to engage other counsel, surrender of papers and property the client is entitled to, and refund of unearned fees. Holding the file hostage over a fee dispute is a classic violation.',
  },
  {
    id: 'pb_gf7_037', topicId: 7, subtopic: 'ethics_withdrawal', difficulty: 2,
    question: 'Regarding a client’s right to end the relationship, which statement is correct?',
    options: [
      'A client may discharge the practitioner only for cause.',
      'A client may discharge the practitioner at any time, with or without cause, subject to the practitioner’s right to be paid for services rendered.',
      'A client must give ninety days’ written notice before discharge.',
      'Discharge requires approval of the examiner in each pending application.',
      'A discharged practitioner may continue prosecuting until a new power of attorney is filed.',
    ],
    correct: 1,
    explanation: 'The client controls the relationship: discharge is effective at any time, with or without cause (see 37 CFR 11.116(a)(3), making withdrawal mandatory upon discharge). The practitioner is entitled to earned fees but must stop representing and take the 11.116(d) protective steps; continuing to act after discharge is unauthorized.',
  },
  {
    id: 'pb_gf7_038', topicId: 7, subtopic: 'ethics_registration', difficulty: 2,
    question: 'To be registered to practice in patent matters before the USPTO under 37 CFR 11.7, an individual must establish:',
    options: [
      'United States citizenship.',
      'A law degree from an accredited school.',
      'Two years of apprenticeship under a registered practitioner.',
      'Membership in at least one state bar.',
      'Good moral character and reputation, the legal, scientific, and technical qualifications to render valuable service, and competence demonstrated by passing the registration examination.',
    ],
    correct: 4,
    explanation: '37 CFR 11.7(a) requires an applicant for registration to establish good moral character and reputation, plus the legal, scientific and technical qualifications necessary to render applicants valuable service — demonstrated by the technical requirements (the categories of the General Requirements Bulletin) and passing the registration examination. Neither citizenship, a law degree, nor bar membership is required to be a patent AGENT.',
  },
  {
    id: 'pb_gf7_039', topicId: 7, subtopic: 'ethics_practice_scope', difficulty: 3,
    question: 'Which activity falls OUTSIDE the authorized scope of practice of a registered patent agent (who is not an attorney)?',
    options: [
      'Drafting claims and amendments in a pending application.',
      'Advising a client on patentability of an invention.',
      'Rendering an opinion on whether a competitor’s product infringes the client’s issued patent, for use in contemplated litigation.',
      'Interviewing the examiner in a pending application.',
      'Filing and prosecuting a reissue application.',
    ],
    correct: 2,
    explanation: 'A registered agent’s authorization covers patent prosecution before the Office and what is reasonably necessary and incident to it (preparing applications, amendments, patentability advice, interviews — see 37 CFR 11.5(b)(1)). Infringement/validity opinions for litigation, litigation itself, and general legal services are the practice of law outside the agent’s federal authorization.',
  },
  {
    id: 'pb_gf7_040', topicId: 7, subtopic: 'ethics_unauthorized_practice', difficulty: 2,
    question: 'An unregistered engineering consultant offers, for a fee, to draft and file patent applications for local inventors. This is:',
    options: [
      'Unauthorized practice before the Office — only registered practitioners may prepare and prosecute others’ patent applications, though an inventor may always prosecute pro se.',
      'Permitted as long as an attorney reviews the final filings.',
      'Permitted because application drafting is a technical, not legal, service.',
      'Permitted for provisional applications only.',
      'Permitted if the consultant discloses non-registration to the clients.',
    ],
    correct: 0,
    explanation: 'Preparing and prosecuting patent applications for OTHERS is practice before the Office reserved to registered practitioners (37 CFR 11.5, 11.10(a)); assisting it as an unregistered person is unauthorized practice (cf. 11.505). Inventors may represent themselves pro se, but may not be represented by an unregistered agent.',
  },
  {
    id: 'pb_gf7_041', topicId: 7, subtopic: 'ethics_registration', difficulty: 3,
    question: 'A nonimmigrant alien scientist residing in the United States on a work visa wishes to prosecute patent applications for her employer only. Under 37 CFR 11.9(b), she may:',
    options: [
      'Never practice before the USPTO in any capacity.',
      'Be granted limited recognition to prosecute patent applications for her employer, if she is authorized to be employed in that capacity, with the recognition lasting only while those conditions hold.',
      'Practice fully upon passing the registration examination, identical to a citizen.',
      'Practice only in trademark matters.',
      'Practice only through a U.S.-citizen co-counsel.',
    ],
    correct: 1,
    explanation: '37 CFR 11.9(b) allows LIMITED RECOGNITION for a nonimmigrant alien residing in the U.S. who is authorized to be employed for patent-prosecution work — confined to the employer’s applications and automatically expiring when the authorized employment or residence conditions end.',
  },
  {
    id: 'pb_gf7_042', topicId: 7, subtopic: 'ethics_former_examiner', difficulty: 3,
    question: 'A former patent examiner joins a law firm. Regarding applications the examiner personally examined while at the USPTO, the former examiner may:',
    options: [
      'Never prosecute or aid in the prosecution of those applications — the bar on particular matters in which one participated personally and substantially as a government employee is permanent.',
      'Prosecute them after a two-year cooling-off period.',
      'Prosecute them with the supervising SPE’s written consent.',
      'Prosecute them if the assignee has changed since examination.',
      'Prosecute them upon passing the registration examination.',
    ],
    correct: 0,
    explanation: 'Under 37 CFR 11.10(b) (implementing 18 USC 207) a former Office employee may NEVER prosecute, or aid in any manner in the prosecution of, an application that was pending in the employee’s official responsibility in which the employee participated personally and substantially. Time does not cure participation in the particular matter (separate, shorter restrictions cover matters merely under official responsibility).',
  },
  {
    id: 'pb_gf7_043', topicId: 7, subtopic: 'ethics_unauthorized_practice', difficulty: 2,
    question: 'A practitioner suspended from practice by the OED continues to correspond with examiners on clients’ applications using a still-registered colleague’s customer number. This conduct is:',
    options: [
      'Acceptable if the colleague reviews each paper before filing.',
      'Acceptable during the first sixty days of suspension.',
      'Unauthorized practice by the suspended practitioner — and the assisting colleague also violates the rules by aiding it.',
      'A mere administrative infraction curable by fee payment.',
      'Acceptable if clients consent to the arrangement in writing.',
    ],
    correct: 2,
    explanation: 'A suspended or excluded practitioner may not practice before the Office (see 37 CFR 11.58’s duties of disciplined practitioners), and doing so through another’s credentials is unauthorized practice (11.505). The registered colleague who knowingly lends credentials assists that violation (cf. 11.804(a), 11.505).',
  },
  {
    id: 'pb_gf7_044', topicId: 7, subtopic: 'ethics_practice_scope', difficulty: 2,
    question: 'Regarding practice in TRADEMARK matters before the USPTO, which statement is correct?',
    options: [
      'Registration as a patent practitioner also authorizes trademark practice.',
      'Patent agents may practice trademark matters if supervised by an attorney.',
      'Trademark prosecution is open to anyone, registered or not.',
      'Patent agents may file trademark applications but not respond to office actions.',
      'A registered patent agent who is not an attorney may not represent others in trademark matters before the Office — trademark representation is limited to attorneys.',
    ],
    correct: 4,
    explanation: 'Recognition to practice in TRADEMARK matters (37 CFR 11.14) extends to attorneys (and certain grandfathered agents and reciprocally recognized foreign practitioners) — a patent agent’s registration under 11.6 covers PATENT matters only. Representing trademark applicants without such recognition is unauthorized practice.',
  },
  {
    id: 'pb_gf7_045', topicId: 7, subtopic: 'ethics_titles', difficulty: 1,
    question: 'A registered practitioner who is not an attorney lists himself on business cards as a “Patent Attorney.” This is:',
    options: [
      'Acceptable — “attorney” and “agent” are interchangeable at the USPTO.',
      'Acceptable if the cards also list his registration number.',
      'Acceptable in states that do not regulate the word “attorney.”',
      'A false or misleading communication about the practitioner’s services — a registered non-attorney may hold out as a “Registered Patent Agent,” not a “Patent Attorney.”',
      'Required by OED style guidelines.',
    ],
    correct: 3,
    explanation: 'Only registered practitioners who are attorneys may use “patent attorney”; a non-attorney’s use of the title is a false or misleading communication prohibited by 37 CFR 11.701 (and invites state unauthorized-practice problems). The accurate title is “Registered Patent Agent.”',
  },
  {
    id: 'pb_gf7_046', topicId: 7, subtopic: 'ethics_advertising', difficulty: 2,
    question: 'Under 37 CFR 11.701, a communication about a practitioner’s services is prohibited if it:',
    options: [
      'Mentions the practitioner’s registration number.',
      'States the practitioner’s technical degrees truthfully.',
      'Appears on the internet rather than in print.',
      'Truthfully lists representative issued patents with client consent.',
      'Contains a material misrepresentation of fact or law, or omits a fact necessary to make the statement as a whole not materially misleading.',
    ],
    correct: 4,
    explanation: 'The touchstone of 37 CFR 11.701 is that communications about the practitioner or the practitioner’s services must not be FALSE OR MISLEADING — including literally true statements rendered misleading by material omission. Truthful credentials and media choice are not the problem.',
  },
  {
    id: 'pb_gf7_047', topicId: 7, subtopic: 'ethics_solicitation', difficulty: 3,
    question: 'After reading a published application naming a solo inventor who has no counsel of record, a practitioner telephones the inventor to offer prosecution services for a fee. Under 37 CFR 11.703, this is:',
    options: [
      'Permitted — published applications are public records.',
      'Permitted if the practitioner records the call.',
      'Permitted if the inventor does not hang up.',
      'Prohibited live solicitation — a practitioner may not solicit professional employment by live person-to-person contact for pecuniary gain unless the target is a practitioner, a family or close personal relationship, or an experienced commercial user of legal services.',
      'Prohibited only if the practitioner has previously been disciplined.',
    ],
    correct: 3,
    explanation: '37 CFR 11.703 restricts live person-to-person solicitation motivated by pecuniary gain to narrow categories (other practitioners; family, close personal, or prior professional relationships; and sophisticated commercial users). A cold call to an unrepresented lay inventor is squarely prohibited.',
  },
  {
    id: 'pb_gf7_048', topicId: 7, subtopic: 'ethics_advertising', difficulty: 2,
    question: 'Which self-description by a registered practitioner is proper under 37 CFR 11.704?',
    options: [
      '“Guaranteed allowance or your money back.”',
      '“Registered Patent Attorney” (for a registered practitioner who is an attorney), since registration to practice before the Office in patent matters may truthfully be communicated.',
      '“The USPTO’s preferred practitioner.”',
      '“Certified patent specialist” without any certifying organization.',
      '“Success rate: 100%” based on a single allowed case.',
    ],
    correct: 1,
    explanation: '37 CFR 11.704(d) expressly permits a registered practitioner to use the designation “Patents,” “Patent Attorney,” “Patent Lawyer,” “Registered Patent Attorney” (attorneys) or the agent equivalents. Outcome guarantees, implied USPTO endorsement, and unsupported specialist or success claims are false/misleading under 11.701.',
  },
  {
    id: 'pb_gf7_049', topicId: 7, subtopic: 'ethics_advertising', difficulty: 2,
    question: 'A two-agent partnership advertises as “National Institute of Patent Sciences,” implying a public or academic body. Under the advertising rules, this firm name is:',
    options: [
      'Improper — a trade name that implies connection with a government agency or public organization is misleading.',
      'Proper because trade names are always permitted.',
      'Proper if the firm registers the name as a trademark.',
      'Proper if a disclaimer appears on the website’s terms page.',
      'Proper because “Institute” is not a protected term.',
    ],
    correct: 0,
    explanation: 'A practitioner may practice under a trade name only if it is not false or misleading — a name implying connection with a government agency, public institution, or charitable legal organization misleads the public and violates the 37 CFR 11.701/11.705 communication rules.',
  },
  {
    id: 'pb_gf7_050', topicId: 7, subtopic: 'ethics_misconduct', difficulty: 2,
    question: 'A practitioner backdates a certificate of mailing to make an untimely reply appear timely. This single act most squarely constitutes:',
    options: [
      'A billing irregularity outside OED jurisdiction.',
      'Permissible zealous advocacy.',
      'Professional misconduct involving dishonesty, fraud, deceit, or misrepresentation under 37 CFR 11.804(c), plus a false 11.18(b) certification to the Office.',
      'A violation only if the examiner detects it.',
      'A matter for the client’s malpractice carrier only.',
    ],
    correct: 2,
    explanation: 'Backdating a certificate of mailing is a deliberate misrepresentation to the Office: dishonesty under 37 CFR 11.804(c) and a false certification under 11.18(b), sanctionable regardless of whether it is caught in the particular case and independent of any harm to the client.',
  },
  {
    id: 'pb_gf7_051', topicId: 7, subtopic: 'ethics_reporting', difficulty: 3,
    question: 'A practitioner learns that another registered practitioner has been forging client signatures on powers of attorney. Under 37 CFR 11.803, the practitioner:',
    options: [
      'May report the misconduct but has no duty to do so.',
      'Must first confront the forger and demand self-reporting.',
      'Must inform the OED Director — knowledge of a violation raising a substantial question as to another practitioner’s honesty, trustworthiness, or fitness triggers a duty to report, except for information protected by 37 CFR 11.106.',
      'Must report only if a client complains first.',
      'Must report to the local bar association instead of the USPTO.',
    ],
    correct: 2,
    explanation: '37 CFR 11.803 makes reporting MANDATORY when a practitioner knows of another practitioner’s violation that raises a substantial question as to honesty, trustworthiness, or fitness to practice — forgery plainly qualifies. The duty yields only to information protected by the 11.106 confidentiality rule.',
  },
  {
    id: 'pb_gf7_052', topicId: 7, subtopic: 'ethics_misconduct', difficulty: 2,
    question: 'Under 37 CFR 11.804(b), it is professional misconduct for a practitioner to:',
    options: [
      'Decline a prospective client’s matter for workload reasons.',
      'Commit a criminal act that reflects adversely on the practitioner’s honesty, trustworthiness, or fitness as a practitioner — even if the act is unrelated to patent practice.',
      'Charge different rates to different clients.',
      'Lose an appeal before the PTAB.',
      'Advertise on social media.',
    ],
    correct: 1,
    explanation: '37 CFR 11.804(b) reaches criminal acts reflecting adversely on honesty, trustworthiness, or fitness — tax fraud or embezzlement counts even though it happens outside prosecution work. Declining work, ordinary fee variation, losing cases, and lawful advertising are not misconduct.',
  },
  {
    id: 'pb_gf7_053', topicId: 7, subtopic: 'ethics_discipline', difficulty: 2,
    question: 'Which sanctions may result from USPTO disciplinary proceedings against a registered practitioner?',
    options: [
      'Exclusion or suspension from practice before the Office, reprimand or censure, and probation.',
      'Imprisonment imposed directly by the OED Director.',
      'Forfeiture of the practitioner’s clients’ patents.',
      'Revocation of the practitioner’s technical degrees.',
      'Only private, non-public warnings.',
    ],
    correct: 0,
    explanation: 'Under 37 CFR 11.20, sanctions include exclusion from practice, suspension, reprimand or censure, and probation (conditions may also be imposed). The OED has no criminal powers, and discipline runs against the practitioner — not the clients’ property.',
  },
  {
    id: 'pb_gf7_054', topicId: 7, subtopic: 'ethics_discipline', difficulty: 3,
    question: 'A registered practitioner is disbarred by her state supreme court for misappropriating client funds. Regarding her USPTO registration:',
    options: [
      'State discipline has no effect on federal registration.',
      'She is automatically excluded with no process of any kind.',
      'The USPTO must wait for a criminal conviction before acting.',
      'She faces reciprocal discipline — the OED may seek an equivalent USPTO sanction predicated on the state disbarment, through the notice-and-response procedure of 37 CFR 11.24.',
      'She may continue patent practice if she surrenders trademark practice.',
    ],
    correct: 3,
    explanation: '37 CFR 11.24 provides reciprocal discipline: on proof of discipline by another jurisdiction, the practitioner is notified and, absent limited defenses (lack of due process, infirmity of proof, grave injustice), substantially equivalent USPTO discipline is imposed. State and federal discipline are linked, not independent.',
  },
  {
    id: 'pb_gf7_055', topicId: 7, subtopic: 'ethics_discipline', difficulty: 2,
    question: 'The USPTO Rules of Professional Conduct and OED disciplinary jurisdiction apply to:',
    options: [
      'Only practitioners who are attorneys.',
      'Only practitioners residing in the United States.',
      'Only conduct occurring inside USPTO buildings.',
      'Only practitioners with active cases before the Office.',
      'All individuals practicing before the Office — registered attorneys and agents, individuals under limited recognition, and persons practicing in trademark and other non-patent matters.',
    ],
    correct: 4,
    explanation: 'OED jurisdiction (37 CFR 11.19) covers practitioners as defined in 11.1 — registered attorneys and agents, those granted limited recognition, and attorneys practicing in trademark and other non-patent matters before the Office — wherever they reside, and includes conduct outside the Office bearing on fitness.',
  },
  {
    id: 'pb_gf7_056', topicId: 7, subtopic: 'ethics_supervision', difficulty: 2,
    question: 'Under 37 CFR 11.501, a practitioner with managerial authority in a firm must:',
    options: [
      'Make reasonable efforts to ensure the firm has measures in effect giving reasonable assurance that all practitioners in the firm conform to the USPTO Rules of Professional Conduct.',
      'Personally review every paper filed by every practitioner in the firm.',
      'Guarantee that no practitioner in the firm ever errs.',
      'Carry malpractice insurance for the entire firm.',
      'File annual compliance reports with the OED.',
    ],
    correct: 0,
    explanation: '37 CFR 11.501 requires partners and managers to make REASONABLE EFFORTS to ensure the firm has measures (docketing, conflict checks, supervision, training) giving reasonable assurance of rule conformance. It is a systems duty, not strict liability or paper-by-paper review.',
  },
  {
    id: 'pb_gf7_057', topicId: 7, subtopic: 'ethics_supervision', difficulty: 3,
    question: 'A junior practitioner follows her supervisor’s instruction on an ethics question that has more than one reasonable answer. Under 37 CFR 11.502, the junior practitioner:',
    options: [
      'Is strictly liable for any resulting violation regardless of the instruction.',
      'Must always refuse to follow a supervisor’s directions on ethics questions.',
      'Transfers all responsibility to the supervisor in every situation.',
      'Must report the supervisor to the OED before complying.',
      'Does not violate the Rules by acting in accordance with a supervisory practitioner’s reasonable resolution of an arguable question of professional duty — though she remains bound by the Rules where the answer is clear.',
    ],
    correct: 4,
    explanation: '37 CFR 11.502(b) protects a subordinate who acts on a supervisor’s REASONABLE resolution of an ARGUABLE ethics question. But 11.502(a) makes clear the subordinate is still bound by the Rules — “my supervisor told me to” is no defense where the violation is clear.',
  },
  {
    id: 'pb_gf7_058', topicId: 7, subtopic: 'ethics_supervision', difficulty: 3,
    question: 'A paralegal in a practitioner’s office, at the practitioner’s direction, tells a client the practitioner filed a response that was in fact never filed. The practitioner is responsible for the paralegal’s conduct under 37 CFR 11.503 because:',
    options: [
      'Practitioners are automatically liable for everything staff do.',
      'The paralegal is unregistered.',
      'A practitioner is responsible for a nonpractitioner assistant’s conduct that would violate the Rules if the practitioner ordered it or, with knowledge, ratified it.',
      'Paralegals owe their own duties directly to the OED.',
      'The misstatement was made by telephone.',
    ],
    correct: 2,
    explanation: 'Under 37 CFR 11.503(c), a practitioner is responsible for a nonpractitioner assistant’s rule-violating conduct when the practitioner ORDERS or knowingly RATIFIES it (or, as a manager, learns of it in time to mitigate and fails to act). Directing staff to lie to a client is the practitioner’s own dishonesty.',
  },
  {
    id: 'pb_gf7_059', topicId: 7, subtopic: 'ethics_diligence', difficulty: 2,
    question: 'A practitioner’s assistant fails to docket a response deadline and the application goes abandoned. Regarding responsibility:',
    options: [
      'The assistant alone is answerable, since she made the entry error.',
      'The practitioner remains responsible — diligence (37 CFR 11.103) and supervision of assistants (11.503) require reasonable docketing measures, and delegation does not delegate the duty.',
      'No rule is implicated because revival under 37 CFR 1.137 is available.',
      'Responsibility passes to the client, who chose the firm.',
      'The USPTO shares fault for not sending a courtesy reminder.',
    ],
    correct: 1,
    explanation: 'Deadlines can be delegated; the DUTY cannot. The practitioner must maintain reasonable docketing and supervision systems (37 CFR 11.103, 11.501, 11.503); a missed statutory deadline from lax systems is the practitioner’s diligence failure even when revival is possible — and the client must be promptly informed (11.104).',
  },
  {
    id: 'pb_gf7_060', topicId: 7, subtopic: 'ethics_conflicts', difficulty: 3,
    question: 'Two clients of the same practitioner end up on opposite sides of the same PTAB interference. Under 37 CFR 11.107(b)(3), the practitioner:',
    options: [
      'May represent both if each consents in writing.',
      'May not represent both — the conflict is nonconsentable where the representation involves the assertion of a claim by one client against another client in the same proceeding before a tribunal.',
      'May represent both if a screening wall separates the files.',
      'May represent whichever client filed first and drop the other silently.',
      'Must represent the senior party as a matter of Office policy.',
    ],
    correct: 1,
    explanation: '37 CFR 11.107(b)(3) makes one category of concurrent conflict absolutely nonconsentable: asserting a claim by one client AGAINST another client represented by the same practitioner in the SAME proceeding before a tribunal. No writing cures it; the practitioner must withdraw consistent with 11.116, protecting both clients’ confidences.',
  },
  {
    id: 'pb_gf7_061', topicId: 7, subtopic: 'ethics_duty_disclosure', difficulty: 2,
    question: 'After the Notice of Allowance but before the patent issues, the practitioner learns of a material, non-cumulative prior art reference. The correct course is:',
    options: [
      'Do nothing — the duty of disclosure ended at allowance.',
      'Wait and cite the reference in a post-grant submission.',
      'Send the reference to the examiner by unofficial email.',
      'Act on it before issuance — the 37 CFR 1.56 duty continues until the patent issues, so the reference must be brought before the Office through an available route (e.g., a proper IDS with the required statement/fee, QPIDS, an RCE, or withdrawal from issue).',
      'Cite the reference only in the family’s foreign counterparts.',
    ],
    correct: 3,
    explanation: 'The duty of disclosure runs while the application is PENDING — through issuance, not merely to allowance (37 CFR 1.56(a)). Material information surfacing after allowance must still reach the Office via the procedures available at that stage; consciously letting the patent issue over withheld material art invites inequitable-conduct and disciplinary consequences.',
  },
  {
    id: 'pb_gf7_062', topicId: 7, subtopic: 'ethics_discipline', difficulty: 3,
    question: 'During an OED investigation into his conduct, a practitioner knowingly gives the OED false information and ignores lawful requests for records. Under 37 CFR 11.801, this is:',
    options: [
      'Itself a disciplinable violation — knowingly giving false or misleading information, or failing to cooperate with an OED investigation, is misconduct in connection with a disciplinary matter, independent of the underlying charge.',
      'Protected litigation strategy in an adversarial process.',
      'Excused if the underlying grievance is ultimately dismissed.',
      'Relevant only to the practitioner’s state bar standing.',
      'Permitted because the Fifth Amendment bars all OED inquiries.',
    ],
    correct: 0,
    explanation: '37 CFR 11.801 makes it a violation to knowingly make false statements of material fact, or to fail to cooperate or respond to lawful demands, in connection with a disciplinary or registration matter (constitutional privileges are preserved when properly invoked, but stonewalling and lying are separately sanctionable even if the original grievance fails).',
  },
  {
    id: 'pb_gf7_063', topicId: 7, subtopic: 'ethics_duty_disclosure', difficulty: 2,
    question: 'A registered practitioner is also the sole inventor and prosecutes her own application pro se. Regarding the duty of disclosure:',
    options: [
      'The duty does not apply to pro se applicants.',
      'The duty of candor under 37 CFR 1.56 applies fully — she owes it both as the named inventor and as a practitioner, and violations carry both patent and disciplinary consequences.',
      'The duty is reduced because there is no client relationship.',
      'The duty applies only if the application is assigned to a company.',
      'The duty transfers to the examiner in pro se cases.',
    ],
    correct: 1,
    explanation: 'The 37 CFR 1.56 duty attaches to each named INVENTOR and to practitioners involved in prosecution; prosecuting one’s own application stacks both roles on the same person. A practitioner-inventor who withholds material art risks unenforceability of the patent AND discipline under Part 11.',
  },
  {
    id: 'pb_gf7_064', topicId: 7, subtopic: 'ethics_communication', difficulty: 3,
    question: 'In a PTAB proceeding, the opposing party conveys a settlement offer to the practitioner. The client has not previously said how it views settlement of this dispute. The practitioner should:',
    options: [
      'Reject the offer if the practitioner considers it inadequate — no client contact needed.',
      'Accept the offer if it looks objectively favorable.',
      'Promptly communicate the offer to the client — accepting or rejecting settlement is the client’s decision under 37 CFR 11.102(a), and 11.104 requires prompt communication of matters requiring the client’s informed consent.',
      'Hold the offer until the next scheduled status call.',
      'Refer the offer directly to the Board for evaluation.',
    ],
    correct: 2,
    explanation: 'Settlement is a paradigm OBJECTIVES decision reserved to the client (37 CFR 11.102(a)), and 11.104(a)(1) requires promptly informing the client of any decision or circumstance requiring the client’s informed consent. Absent prior authoritative instructions, the practitioner has no authority to accept or reject unilaterally.',
  },
  {
    id: 'pb_gf7_065', topicId: 7, subtopic: 'ethics_misconduct', difficulty: 3,
    question: 'Which of the following, standing alone, is NOT professional misconduct under 37 CFR 11.804?',
    options: [
      'Engaging in conduct prejudicial to the administration of justice.',
      'Stating an ability to improperly influence a government official.',
      'Knowingly assisting a judge in conduct that violates applicable rules of judicial conduct.',
      'Engaging in conduct involving dishonesty, fraud, deceit, or misrepresentation.',
      'Zealously but honestly arguing a good-faith interpretation of an ambiguous claim term that the examiner ultimately rejects.',
    ],
    correct: 4,
    explanation: 'Honest, good-faith advocacy — even unsuccessful — is the job, not misconduct. By contrast, 37 CFR 11.804 expressly lists conduct prejudicial to the administration of justice (d), claiming improper influence (e), knowingly assisting judicial misconduct (f), and dishonesty/fraud/deceit/misrepresentation (c).',
  },
];
