/**
 * Patent Bar — WS3 gap-fill: Design & Plant Patents (topicId 6).
 *
 * 66 AI-authored questions closing the deepest blueprint coverage gap
 * (design/plant was 4.1% of the bank vs its 10% blueprint weight — see
 * docs/monetization/PATENT_BAR_COVERAGE_MATRIX.md). 66 is this section's
 * TERMINAL size: at the exact-proportion bank of 980 (the only state in
 * which all six blueprint floors can hold simultaneously), design/plant
 * needs 98 questions and the pre-existing bank held 32. Grounded in
 * 35 U.S.C. 171–173 & 37 CFR 1.152–1.155 (designs), 35 U.S.C. 161–164 &
 * 37 CFR 1.161–1.167 (plants), 35 U.S.C. 382–390 (Hague), and the
 * design/plant/PVPA boundary cases (Egyptian Goddess, In re Webb, In re
 * Zahn, Imazio, J.E.M. v. Pioneer). All original compositions.
 *
 * VERIFICATION STATUS: every item here is 'unverified' (AI-authored,
 * pending SME review via /dashboard/test-prep/patent_bar/review-queue).
 * None may appear in a scored mock until reviewed. Answer keys are
 * deliberately balanced (A:14, B–E:13 — asserted by
 * qbank-key-balance.test.ts).
 */

import type { PatentBarQuestion } from './patent-bar-qbank-data';

export const PATENT_BAR_GAPFILL_DESIGN: PatentBarQuestion[] = [
  {
    id: 'pb_gf6_001', topicId: 6, subtopic: 'design_subject_matter', difficulty: 1,
    question: 'Under 35 U.S.C. 171, a design patent may be obtained for:',
    options: [
      'Any new and useful process, machine, manufacture, or composition of matter.',
      'Any distinct and new variety of asexually reproduced plant.',
      'Any new, original, and ornamental design for an article of manufacture.',
      'Any aesthetically pleasing two-dimensional image, whether or not applied to an article.',
      'Any new and nonobvious improvement to the functional features of a machine.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 171 authorizes a patent for a "new, original and ornamental design for an article of manufacture." Option A is utility subject matter (35 U.S.C. 101); option B is plant subject matter (35 U.S.C. 161). An image standing alone, not embodied in an article of manufacture, is not proper design subject matter (MPEP 1504.01).',
  },
  {
    id: 'pb_gf6_002', topicId: 6, subtopic: 'design_claim', difficulty: 1,
    question: 'The proper form of the single claim in a design patent application for a lamp is:',
    options: [
      '"The ornamental design for a lamp, as shown."',
      '"A lamp comprising an ornamental appearance substantially as depicted in Figures 1–7."',
      '"The ornamental features of a lamp, namely its curved neck and fluted base."',
      '"I claim the design of Figures 1–7 and all colorable imitations thereof."',
      '"An article of manufacture having the ornamental characteristics disclosed herein."',
    ],
    correct: 0,
    explanation: '37 CFR 1.153 requires a single claim in formal terms to "the ornamental design for the article (specifying name) as shown" — or "as shown and described" when a proper descriptive statement appears in the specification. Verbal recitations of features, "comprising" language, and multiple claims are all improper in design practice.',
  },
  {
    id: 'pb_gf6_003', topicId: 6, subtopic: 'design_term', difficulty: 1,
    question: 'A design patent issuing from an application filed June 1, 2015 has a term of:',
    options: [
      '20 years from the filing date.',
      '17 years from the grant date.',
      '14 years from the grant date.',
      '14 years from the filing date.',
      '15 years from the grant date.',
    ],
    correct: 4,
    explanation: '35 U.S.C. 173, as amended by the Patent Law Treaties Implementation Act (Hague implementation), gives design patents issuing from applications filed ON OR AFTER May 13, 2015 a term of 15 years FROM GRANT. (Applications filed earlier: 14 years from grant.) Design terms run from grant, not filing.',
  },
  {
    id: 'pb_gf6_004', topicId: 6, subtopic: 'design_term', difficulty: 1,
    question: 'Maintenance fees on a design patent:',
    options: [
      'Are due at 3.5, 7.5, and 11.5 years after grant.',
      'Are never required — maintenance fees apply only to utility patents.',
      'Are due only if the design patent term was extended.',
      'Are due at 5 and 10 years after grant.',
      'Are required only for design patents issuing from Hague international design applications.',
    ],
    correct: 1,
    explanation: 'Under 35 U.S.C. 41(b), maintenance fees are required only to maintain UTILITY patents in force. Design patents and plant patents require no maintenance fees; the 3.5/7.5/11.5-year schedule is utility-only.',
  },
  {
    id: 'pb_gf6_005', topicId: 6, subtopic: 'design_priority', difficulty: 2,
    question: 'An applicant filed a design application in Germany on January 10. To preserve a right of foreign priority for a corresponding U.S. design application, the U.S. application must be filed within:',
    options: [
      'Twelve months of the German filing.',
      'Twenty months of the German filing.',
      'Three months of the German filing.',
      'Six months of the German filing.',
      'Thirty months of the German filing.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 172 shortens the foreign priority period for designs to SIX months (versus twelve months for utility applications under 35 U.S.C. 119(a)). This is a heavily tested design-specific difference.',
  },
  {
    id: 'pb_gf6_006', topicId: 6, subtopic: 'design_filing', difficulty: 1,
    question: 'A provisional application for a design:',
    options: [
      'May be filed to secure an early effective filing date at reduced cost.',
      'Cannot be filed — provisional applications are not available for designs.',
      'May be filed, but expires after six months instead of twelve.',
      'May be filed only if a utility provisional covering the same article is co-pending.',
      'May be filed only through the Hague system.',
    ],
    correct: 1,
    explanation: 'Provisional applications under 35 U.S.C. 111(b) are not available for design inventions, and 35 U.S.C. 172 further provides that 119(e) provisional benefit does not apply to designs. A design applicant must file a nonprovisional design application (or an international design application).',
  },
  {
    id: 'pb_gf6_007', topicId: 6, subtopic: 'design_filing', difficulty: 2,
    question: 'A design application filed directly with the USPTO (not through the Hague system) is:',
    options: [
      'Published 18 months after its earliest filing date, like a utility application.',
      'Published promptly after the first Office action.',
      'Published only upon the applicant’s request and payment of a fee.',
      'Not published before grant — pre-grant publication does not apply to design applications.',
      'Published within three months of filing.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 122(b)(2)(A)(iv) expressly excludes design applications from 18-month pre-grant publication; a nationally filed design application remains confidential until the patent issues. (Contrast an international design application, which the International Bureau publishes.)',
  },
  {
    id: 'pb_gf6_008', topicId: 6, subtopic: 'design_cpa', difficulty: 2,
    question: 'A continued prosecution application (CPA) under 37 CFR 1.53(d) may be filed:',
    options: [
      'Only for design applications.',
      'For any utility, plant, or design application.',
      'Only for utility applications filed before June 8, 1995.',
      'Only for plant applications.',
      'For any application, provided an RCE has not previously been filed.',
    ],
    correct: 0,
    explanation: 'CPA practice under 37 CFR 1.53(d) is available ONLY for design applications. Utility and plant applicants continue prosecution via an RCE (37 CFR 1.114) or a regular continuation under 1.53(b); the CPA is the design-specific counterpart.',
  },
  {
    id: 'pb_gf6_009', topicId: 6, subtopic: 'design_examination', difficulty: 2,
    question: 'After a final rejection in a design application, the applicant wishes to continue prosecution with a further amendment. A request for continued examination (RCE) under 37 CFR 1.114:',
    options: [
      'Is available upon payment of the RCE fee and submission of a compliant amendment.',
      'Is available only after an appeal brief is filed.',
      'Is available because RCE practice applies to all nonprovisional applications.',
      'Is available if filed within two months of the final rejection.',
      'Is not available — RCE practice does not apply to design applications; a CPA under 37 CFR 1.53(d) is the design counterpart.',
    ],
    correct: 4,
    explanation: '37 CFR 1.114(e) excludes design applications (and international design applications) from RCE practice. The design applicant’s continued-prosecution vehicle is the CPA under 1.53(d), which is itself available only for designs.',
  },
  {
    id: 'pb_gf6_010', topicId: 6, subtopic: 'design_drawings', difficulty: 1,
    question: 'In a design application’s drawings, broken (dashed) lines are properly used to show:',
    options: [
      'The claimed design itself, when the applicant wants broader scope.',
      'Hidden interior structure that is part of the claimed design.',
      'Environmental structure, or portions of the article, that form no part of the claimed design.',
      'Alternate positions of the claimed design that are also claimed.',
      'Prior art features for the examiner’s convenience.',
    ],
    correct: 2,
    explanation: 'MPEP 1503.02: solid lines show the claimed design; broken lines illustrate environment or unclaimed portions of the article (including unclaimed boundaries). Broken-line subject matter forms no part of the claimed design.',
  },
  {
    id: 'pb_gf6_011', topicId: 6, subtopic: 'design_drawings', difficulty: 2,
    question: 'In design patent practice, the scope of the claim is defined primarily by:',
    options: [
      'The title of the application.',
      'The written description of the design’s characteristic features.',
      'The abstract.',
      'The claim’s verbal recitation of ornamental features.',
      'The drawings — the drawing disclosure is the best (and effectively the only) description of the claimed design.',
    ],
    correct: 4,
    explanation: 'In design practice "the drawing is the claim": the formal claim wording simply incorporates the drawings, and the drawing disclosure defines what is protected (MPEP 1503.01, 1504.04). That is why drawing completeness and consistency are the central examination issues in design cases.',
  },
  {
    id: 'pb_gf6_012', topicId: 6, subtopic: 'design_drawings', difficulty: 3,
    question: 'Photographs may be used instead of ink drawings in a design application:',
    options: [
      'Freely, at the applicant’s option, without any justification.',
      'Never — design applications must always contain line drawings.',
      'Only if photographs are the only practicable medium for illustrating the claimed design.',
      'Only in Hague international design applications.',
      'Only when accompanied by duplicate line drawings.',
    ],
    correct: 2,
    explanation: '37 CFR 1.84(b)(1): photographs are not ordinarily permitted, but the Office accepts black-and-white photographs in design applications when photographs are the ONLY practicable medium for illustrating the claimed invention. Photographs and ink drawings may not be mixed in one application.',
  },
  {
    id: 'pb_gf6_013', topicId: 6, subtopic: 'design_examination', difficulty: 3,
    question: 'Expedited examination of a design application under 37 CFR 1.155 (the design "rocket docket") requires, among other things:',
    options: [
      'A showing that the applicant’s health or age justifies special status.',
      'A petition to make special based on prospective infringement litigation.',
      'Payment of the Track One prioritized examination fee.',
      'A request with the fee, a statement that a preexamination search was conducted, an information disclosure statement, and a complete application with formal drawings.',
      'A certified copy of a corresponding foreign design registration.',
    ],
    correct: 3,
    explanation: '37 CFR 1.155(a) conditions expedited design examination on: the request and fee, a statement that a preexamination search was conducted (indicating the field of search), an IDS, and an application that is complete with formal drawings. It is a design-specific procedure, distinct from petitions to make special and from Track One.',
  },
  {
    id: 'pb_gf6_014', topicId: 6, subtopic: 'design_infringement', difficulty: 2,
    question: 'The sole test for design patent infringement is:',
    options: [
      'Whether an ordinary observer, familiar with the prior art, would find the accused design substantially the same as the patented design.',
      'Whether the accused design appropriates the "point of novelty" that distinguishes the patented design from the prior art.',
      'Whether an expert in industrial design would confuse the two designs.',
      'Whether the accused article performs substantially the same function in substantially the same way.',
      'Whether consumers were actually confused at the point of sale.',
    ],
    correct: 0,
    explanation: 'Egyptian Goddess v. Swisa (Fed. Cir. en banc 2008) made the ordinary-observer test — conducted in light of the prior art — the SOLE test for design infringement, abolishing the separate point-of-novelty inquiry. The same ordinary-observer lens governs design anticipation.',
  },
  {
    id: 'pb_gf6_015', topicId: 6, subtopic: 'design_obviousness', difficulty: 2,
    question: 'Obviousness of a claimed design under 35 U.S.C. 103 is evaluated from the perspective of:',
    options: [
      'An ordinary observer purchasing articles of the type involved.',
      'A designer of ordinary skill who designs articles of the type involved.',
      'A person having ordinary skill in the mechanical arts.',
      'The inventor at the time of invention.',
      'An average consumer exercising reasonable care.',
    ],
    correct: 1,
    explanation: 'MPEP 1504.03: design obviousness is judged from the viewpoint of the designer of ordinary skill (or capability) who designs articles of the type involved. The ordinary OBSERVER is the standard for anticipation and infringement — keep the two straight.',
  },
  {
    id: 'pb_gf6_016', topicId: 6, subtopic: 'design_subject_matter', difficulty: 2,
    question: 'A design patent claim directed to a configuration that is dictated primarily by the article’s function is:',
    options: [
      'Invalid/unpatentable — a design that is primarily functional rather than ornamental is not proper design subject matter.',
      'Patentable, because every useful article necessarily has some function.',
      'Patentable if the applicant disclaims the functional features.',
      'Patentable as long as at least one ornamental feature appears somewhere on the article.',
      'Automatically converted to a utility application.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 171 requires an ORNAMENTAL design; a configuration dictated primarily by function fails the requirement (MPEP 1504.01(c)). The existence of alternative designs that perform the same function is classic evidence that the claimed appearance is ornamental rather than dictated by function.',
  },
  {
    id: 'pb_gf6_017', topicId: 6, subtopic: 'dp_comparison', difficulty: 2,
    question: 'An inventor develops a new chair with both a novel load-bearing mechanism and a distinctive ornamental appearance. The inventor:',
    options: [
      'Must elect either a utility patent or a design patent, but cannot have both.',
      'May obtain only a utility patent, because the article is functional.',
      'May obtain only a design patent, because the appearance is what distinguishes it.',
      'Must file a single combined utility-design application.',
      'May obtain both a utility patent (for the functional mechanism) and a design patent (for the ornamental appearance) on the same article.',
    ],
    correct: 4,
    explanation: 'Utility and design patents protect different aspects of the same article — how it works versus how it looks — and both may be obtained on one article (MPEP 1502.01). There is no combined utility/design application and no requirement to elect.',
  },
  {
    id: 'pb_gf6_018', topicId: 6, subtopic: 'design_examination', difficulty: 3,
    question: 'A design application discloses several embodiments of the claimed article. Multiple embodiments:',
    options: [
      'Are never permitted in a single design application.',
      'May be retained in a single application (under the single claim) only if they are not patentably distinct from one another; otherwise the examiner will require restriction.',
      'Are always permitted, because a design application may include up to 100 designs.',
      'Require a separate claim for each embodiment.',
      'Are permitted only in plant applications.',
    ],
    correct: 1,
    explanation: 'MPEP 1504.05: multiple embodiments may stay in one design application only when they involve a single inventive concept (not patentably distinct); independent and distinct designs draw a restriction requirement. The up-to-100-designs allowance belongs to Hague INTERNATIONAL applications, not the single-claim U.S. national application.',
  },
  {
    id: 'pb_gf6_019', topicId: 6, subtopic: 'design_subject_matter', difficulty: 3,
    question: 'The ornamental design of a hip prosthesis that is fully concealed inside the body during its ultimate end use:',
    options: [
      'Can never be design-patented, because ornamentality requires visibility during final use.',
      'Can be design-patented only if X-ray visibility is shown.',
      'May satisfy the ornamentality requirement if its appearance is a matter of concern at some point in its commercial life — for example, at sale or in advertising displays.',
      'Is per se ornamental because prostheses are articles of manufacture.',
      'Must be pursued as a trademark instead.',
    ],
    correct: 2,
    explanation: 'In re Webb: an article hidden in its ultimate use may still meet the ornamentality requirement if its appearance matters at some point between manufacture and final use — display at sale, catalogs, and advertising can supply that concern for appearance.',
  },
  {
    id: 'pb_gf6_020', topicId: 6, subtopic: 'design_claim', difficulty: 3,
    question: 'A design claim directed to only a portion of an article (for example, the shank portion of a drill bit, with the remainder shown in broken lines):',
    options: [
      'Is improper — a design must claim the entire article of manufacture.',
      'Is proper only if the portion is physically separable from the article.',
      'Is improper new matter unless the portion was originally shown in solid lines.',
      'Is proper — a design may be embodied in a portion of an article of manufacture.',
      'Is proper only in continuation applications.',
    ],
    correct: 3,
    explanation: 'In re Zahn (CCPA 1980) upheld a design claim to the shank portion of a drill bit: a design may be embodied in a portion of an article, with the unclaimed remainder shown in broken lines. Physical separability is not required.',
  },
  {
    id: 'pb_gf6_021', topicId: 6, subtopic: 'design_subject_matter', difficulty: 3,
    question: 'A computer-generated icon:',
    options: [
      'Is never proper design subject matter because it is intangible.',
      'Is proper design subject matter standing alone, without more.',
      'Is proper design subject matter only if claimed together with the underlying software.',
      'Is proper design subject matter when claimed as embodied in an article of manufacture — e.g., shown on a computer screen, monitor, or display panel.',
      'Must be registered as a copyright instead; no patent protection is possible.',
    ],
    correct: 3,
    explanation: 'MPEP 1504.01(a): a computer-generated icon per se is mere surface ornamentation, but an icon claimed as shown on a computer screen, monitor, or other display panel satisfies the article-of-manufacture requirement of 35 U.S.C. 171.',
  },
  {
    id: 'pb_gf6_022', topicId: 6, subtopic: 'design_claim', difficulty: 2,
    question: 'Under 37 CFR 1.153, the title of a design application must:',
    options: [
      'Broadly claim all possible uses of the design.',
      'Designate the particular article on which the design is embodied.',
      'Be identical to the title of any parent utility application.',
      'Include the word "ornamental."',
      'List the Locarno classification of the design.',
    ],
    correct: 1,
    explanation: '37 CFR 1.153(a): the title must designate the PARTICULAR ARTICLE on which the design is embodied or to which it is applied, and the single claim uses that same designation. The title frames the claim scope, which is why examiners police it.',
  },
  {
    id: 'pb_gf6_023', topicId: 6, subtopic: 'design_drawings', difficulty: 3,
    question: 'During prosecution of a design application, the applicant amends the drawings to convert several broken lines to solid lines, thereby claiming previously unclaimed subject matter. This amendment:',
    options: [
      'Is always permitted, because broken lines are part of the original disclosure.',
      'Is never permitted after the first Office action.',
      'Is permitted only if the original disclosure (including the broken-line showing) provides 35 U.S.C. 112 support for what becomes claimed — otherwise it introduces prohibited new matter.',
      'Requires a supplemental oath but no support analysis.',
      'Automatically converts the application into a continuation-in-part.',
    ],
    correct: 2,
    explanation: 'MPEP 1504.04: broken-to-solid (and solid-to-broken) line conversions are tested for written-description support in the original disclosure. Because broken lines showed the subject matter, support often exists — but where the original drawings do not adequately disclose what becomes claimed, the amendment is new matter under 35 U.S.C. 132.',
  },
  {
    id: 'pb_gf6_024', topicId: 6, subtopic: 'design_examination', difficulty: 3,
    question: 'Two design applications by the same inventor claim designs that are obvious variants of each other. The examiner rejects the later application for obviousness-type double patenting. The rejection:',
    options: [
      'Cannot be overcome; one application must be abandoned.',
      'Is improper — double patenting does not apply to design applications.',
      'Can be overcome only by merging the two applications.',
      'Can be overcome by arguing that design patents measure their terms from grant.',
      'Can be overcome by filing a terminal disclaimer in compliance with 37 CFR 1.321.',
    ],
    correct: 4,
    explanation: 'Obviousness-type (nonstatutory) double patenting applies in design practice, and — as in utility practice — a terminal disclaimer under 37 CFR 1.321 overcomes it (MPEP 1504.06). Statutory ("same invention") double patenting cannot be cured by disclaimer.',
  },
  {
    id: 'pb_gf6_025', topicId: 6, subtopic: 'design_infringement', difficulty: 3,
    question: 'In addition to ordinary patent remedies, 35 U.S.C. 289 gives a design patentee a special remedy:',
    options: [
      'Recovery of the infringer’s total profit from sale of the article of manufacture to which the design was applied, but not less than $250 — without double recovery of that profit under other provisions.',
      'Treble damages without proof of willfulness.',
      'Statutory damages of $150,000 per infringing article.',
      'An automatic injunction upon a finding of infringement.',
      'Recovery of the patentee’s lost profits plus the infringer’s total profit.',
    ],
    correct: 0,
    explanation: '35 U.S.C. 289 is the design-specific "additional remedy": the infringer’s TOTAL PROFIT on the article of manufacture, with a $250 statutory floor — but the patentee may not recover the profit twice under 289 and 284.',
  },
  {
    id: 'pb_gf6_026', topicId: 6, subtopic: 'design_filing', difficulty: 3,
    question: 'An inventor’s earlier-filed utility application fully discloses the appearance of a device. The inventor later files a design application claiming that appearance. The design application:',
    options: [
      'Cannot claim benefit of the utility filing date — benefit claims cannot cross between utility and design applications.',
      'May claim benefit only through an intervening provisional application.',
      'May claim the benefit of the utility application’s filing date under 35 U.S.C. 120 as a continuation (or division), provided the utility disclosure supports the claimed design under 35 U.S.C. 112.',
      'Automatically receives the utility filing date without any benefit claim.',
      'Must have been filed within six months of the utility application.',
    ],
    correct: 2,
    explanation: 'MPEP 1504.20: benefit under 35 U.S.C. 120 may cross statutory classes — a design application can be a continuation of a utility application (and vice versa) — so long as the parent’s disclosure supports the claimed design under 112 and copendency/reference requirements are met. (The six-month limit of 172 concerns FOREIGN priority, not domestic benefit.)',
  },
  {
    id: 'pb_gf6_027', topicId: 6, subtopic: 'design_examination', difficulty: 2,
    question: 'A restriction requirement between independent and distinct designs in a design application is reviewable by:',
    options: [
      'Appeal to the Patent Trial and Appeal Board.',
      'Civil action in district court.',
      'Direct appeal to the Federal Circuit.',
      'Nothing — it is wholly unreviewable.',
      'Petition to the Director under 37 CFR 1.144 — restriction requirements are petitionable, not appealable.',
    ],
    correct: 4,
    explanation: 'Restriction requirements (design or utility) are reviewable by PETITION under 37 CFR 1.144 after final action on the requirement, not by appeal to the Board — the Board reviews rejections of claims, and a restriction requirement is not a rejection.',
  },
  {
    id: 'pb_gf6_028', topicId: 6, subtopic: 'design_term', difficulty: 2,
    question: 'A design patent issued from an application filed in 2012 (before May 13, 2015) has a term of:',
    options: [
      '14 years from the date of grant.',
      '15 years from the date of grant.',
      '20 years from the filing date.',
      '17 years from the filing date.',
      '14 years from the filing date.',
    ],
    correct: 0,
    explanation: 'Design applications filed BEFORE May 13, 2015 yield a 14-year-from-grant term; the PLTIA’s 15-year-from-grant term applies only to applications filed on or after that date. Either way the design term runs from grant, never from filing.',
  },
  {
    id: 'pb_gf6_029', topicId: 6, subtopic: 'design_drawings', difficulty: 3,
    question: 'Color drawings or color photographs in a design application are accepted:',
    options: [
      'As a matter of right, like black-and-white drawings.',
      'Never — design drawings must be black and white.',
      'Only in plant applications.',
      'Only after the Office grants a petition explaining why color is necessary, filed with the required fee and copies.',
      'Only if the application was filed through the Hague system.',
    ],
    correct: 3,
    explanation: '37 CFR 1.84(a)(2) and MPEP 1503.02: color drawings/photographs are accepted in design applications only on granted petition showing that color is necessary, accompanied by the petition fee and the required sets. (In PLANT applications, by contrast, color drawings are affirmatively required when color distinguishes the variety.)',
  },
  {
    id: 'pb_gf6_030', topicId: 6, subtopic: 'design_drawings', difficulty: 2,
    question: 'Surface shading in design drawings serves to:',
    options: [
      'Indicate unclaimed subject matter.',
      'Show clearly the character and contour of all three-dimensional surfaces of the claimed design.',
      'Denote transparency only.',
      'Mark portions dedicated to the public.',
      'Distinguish prior art features from the claimed design.',
    ],
    correct: 1,
    explanation: 'MPEP 1503.02(II): appropriate and adequate surface shading shows the character and contour of the three-dimensional surfaces. (Oblique line shading is the specific convention for transparent, translucent, or highly polished surfaces; unclaimed matter is the province of BROKEN lines.)',
  },
  {
    id: 'pb_gf6_031', topicId: 6, subtopic: 'design_hague', difficulty: 2,
    question: 'A U.S. applicant may file an international design application under the Hague Agreement:',
    options: [
      'Only directly with the International Bureau of WIPO.',
      'Either directly with the International Bureau or indirectly through the USPTO acting as an office of indirect filing.',
      'Only through the USPTO.',
      'Only if a U.S. national design application is already pending.',
      'Only through a registered Hague attorney in Geneva.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 382: an international design application may be filed directly with the International Bureau, or through the USPTO as an office of indirect filing (which also performs national-security review). No pending national application is required.',
  },
  {
    id: 'pb_gf6_032', topicId: 6, subtopic: 'design_hague', difficulty: 3,
    question: 'A single international design application under the Hague Agreement may include:',
    options: [
      'Up to 100 designs, provided all belong to the same class of the Locarno Classification.',
      'Only one design.',
      'An unlimited number of designs in any classes.',
      'Up to 15 designs in up to three classes.',
      'Up to 100 designs spanning any number of classes.',
    ],
    correct: 0,
    explanation: 'The Hague system permits up to 100 designs in one international application, all of which must belong to the same Locarno class — a striking contrast with the single-claim U.S. national design application. On U.S. examination, independent and distinct designs will still face restriction.',
  },
  {
    id: 'pb_gf6_033', topicId: 6, subtopic: 'design_hague', difficulty: 2,
    question: 'An international design application that designates the United States:',
    options: [
      'Bypasses USPTO examination and registers automatically.',
      'Is examined only for formalities by the USPTO.',
      'Must be refiled as a national design application within 30 months.',
      'Has the effect of a U.S. national design application and is substantively examined by the USPTO under 35 U.S.C. 171.',
      'Issues as a certificate of registration rather than a patent.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 385: an international design application designating the U.S. has the effect of a national application; under 389 the USPTO fully examines it (novelty, obviousness, ornamentality) and, if allowed, issues a regular U.S. design patent — the U.S. did not adopt a registration-only model.',
  },
  {
    id: 'pb_gf6_034', topicId: 6, subtopic: 'design_hague', difficulty: 3,
    question: 'Publication by the International Bureau of an international design application designating the United States:',
    options: [
      'Has no effect in the United States.',
      'Immediately grants enforceable design rights in the United States.',
      'Is deemed a publication under 35 U.S.C. 122(b), which can give rise to provisional rights (a reasonable royalty) under 35 U.S.C. 154(d) once the U.S. design patent issues.',
      'Starts the U.S. design patent term running.',
      'Bars later U.S. substantive examination.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 390 deems the International Bureau’s publication a publication under 122(b), so 154(d) provisional rights are available — subject to the usual conditions (actual notice, and an issued claim substantially identical to the published one). The design term still runs from GRANT.',
  },
  {
    id: 'pb_gf6_035', topicId: 6, subtopic: 'design_hague', difficulty: 2,
    question: 'A U.S. design patent issuing from an international design application (Hague) that designated the United States has a term of:',
    options: [
      '5 years, renewable in 5-year increments up to 25 years.',
      '20 years from the international filing date.',
      '14 years from grant.',
      '10 years from the date of international registration.',
      '15 years from the date of grant.',
    ],
    correct: 4,
    explanation: 'The U.S. patent right arising from a Hague filing is an ordinary U.S. design patent with the 35 U.S.C. 173 term — 15 years from grant. (Five-year renewal periods describe the INTERNATIONAL REGISTRATION’s maintenance at WIPO, not the U.S. patent term.)',
  },
  {
    id: 'pb_gf6_036', topicId: 6, subtopic: 'plant_eligibility', difficulty: 1,
    question: 'Under 35 U.S.C. 161, a plant patent may be granted to whoever:',
    options: [
      'Discovers any plant growing anywhere and files within one year.',
      'Sexually reproduces a new hybrid from seed.',
      'Genetically engineers any new plant cell line.',
      'Cultivates any imported plant variety for two growing seasons.',
      'Invents or discovers and asexually reproduces any distinct and new variety of plant, other than a tuber-propagated plant or a plant found in an uncultivated state.',
    ],
    correct: 4,
    explanation: '35 U.S.C. 161 tracks exactly: invents or discovers AND asexually reproduces a distinct and new variety — including cultivated sports, mutants, hybrids, and newly found seedlings — excluding tuber-propagated plants and plants found in an uncultivated state.',
  },
  {
    id: 'pb_gf6_037', topicId: 6, subtopic: 'plant_eligibility', difficulty: 1,
    question: 'Which of the following is excluded from plant patent protection by statute?',
    options: [
      'Cultivated sports.',
      'Mutants and hybrids.',
      'Newly found seedlings discovered in a cultivated area.',
      'Tuber-propagated plants and plants found in an uncultivated state.',
      'Grafted fruit-tree varieties.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 161 contains two exclusions: tuber-propagated plants (the classic examples are the Irish potato and the Jerusalem artichoke) and plants found in an uncultivated state. Sports, mutants, hybrids, and cultivated-area seedlings are expressly INCLUDED.',
  },
  {
    id: 'pb_gf6_038', topicId: 6, subtopic: 'plant_eligibility', difficulty: 2,
    question: 'A hiker discovers a strikingly distinct wild rose growing in an uncultivated forest and asexually reproduces it. A botanist separately notices a distinct branch sport on a tree in her cultivated orchard and asexually reproduces it. Who can obtain a plant patent?',
    options: [
      'Both — asexual reproduction cures any eligibility problem.',
      'The hiker only, because discovery in nature demonstrates novelty.',
      'The botanist only — a plant found in an uncultivated state is statutorily excluded, while a sport found in a cultivated area is eligible.',
      'Neither — sports and wild finds are both excluded.',
      'Both, but only through the Plant Variety Protection Act.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 161 excludes plants "found in an uncultivated state," so the forest find is ineligible no matter how faithfully reproduced. Sports, mutants, and newly found seedlings ARE eligible when found in a cultivated area, as with the orchard sport.',
  },
  {
    id: 'pb_gf6_039', topicId: 6, subtopic: 'plant_asexual', difficulty: 1,
    question: 'Asexual reproduction, required for plant patent eligibility, includes:',
    options: [
      'Growing the plant from its seeds under controlled conditions.',
      'Grafting, budding, taking cuttings, layering, division, and similar methods that do not use seeds.',
      'Cross-pollinating two parent varieties.',
      'Any laboratory manipulation of plant DNA.',
      'Self-pollinating a stable hybrid.',
    ],
    correct: 1,
    explanation: 'Asexual reproduction means propagation WITHOUT seeds — grafting, budding, cuttings, layering, division, tissue culture and the like — producing a genetically identical copy. Anything grown from seed (including self-pollination) is sexual reproduction and belongs to PVPA/utility territory.',
  },
  {
    id: 'pb_gf6_040', topicId: 6, subtopic: 'plant_asexual', difficulty: 2,
    question: 'The requirement that the inventor asexually reproduce the plant before a plant patent can be obtained exists because:',
    options: [
      'Asexual reproduction demonstrates that the new variety is stable — that its distinguishing characteristics are retained through reproduction and were not a one-time occurrence.',
      'Seeds are prohibited imports under plant quarantine law.',
      'It proves the plant is commercially valuable.',
      'The USPTO requires deposits of asexually reproduced specimens.',
      'Sexual reproduction of the plant would infringe the PVPA.',
    ],
    correct: 0,
    explanation: 'Asexual reproduction is the proof of stability: it shows the claimed characteristics hold true in the reproduced generation. That is also why invention is not complete for 35 U.S.C. 161 purposes until asexual reproduction has occurred.',
  },
  {
    id: 'pb_gf6_041', topicId: 6, subtopic: 'plant_claim', difficulty: 1,
    question: 'The claim of a plant patent application:',
    options: [
      'Is a single claim in formal terms to the plant shown and described.',
      'May include up to three claims: the plant, its fruit, and its propagation method.',
      'Must particularly point out the botanical characteristics in means-plus-function form.',
      'Is optional if the specification is complete.',
      'Must be presented in independent and dependent form.',
    ],
    correct: 0,
    explanation: '37 CFR 1.164: a plant application has exactly ONE claim, in formal terms to the plant shown and described (it may also recite the variety’s principal distinguishing characteristics). Like design practice, multiple claims are improper.',
  },
  {
    id: 'pb_gf6_042', topicId: 6, subtopic: 'plant_term', difficulty: 1,
    question: 'The term of a plant patent is:',
    options: [
      '15 years from grant.',
      '14 years from grant.',
      '20 years from the filing date of the application (like a utility patent), with no maintenance fees.',
      '25 years from filing, in recognition of breeding time.',
      '20 years from grant.',
    ],
    correct: 2,
    explanation: 'Plant patents take the utility term — 20 years from the U.S. filing date (35 U.S.C. 154, applied through 161) — but, like design patents, they require NO maintenance fees (35 U.S.C. 41(b) reaches only utility patents).',
  },
  {
    id: 'pb_gf6_043', topicId: 6, subtopic: 'plant_rights', difficulty: 2,
    question: 'A plant patent grants the right to exclude others from:',
    options: [
      'Growing any plant of the same species.',
      'Selling seeds derived from the patented plant.',
      'Using the plant’s variety name in commerce.',
      'Breeding new varieties using the patented plant as a parent.',
      'Asexually reproducing the plant, and using, offering for sale, or selling the plant so reproduced (or its parts), or importing them into the United States.',
    ],
    correct: 4,
    explanation: '35 U.S.C. 163 defines the plant patent grant: excluding others from ASEXUALLY reproducing the plant and from using/offering/selling/importing the plant SO REPRODUCED or its parts. Seed-grown (sexual) progeny fall outside the plant patent — a key limit on its scope.',
  },
  {
    id: 'pb_gf6_044', topicId: 6, subtopic: 'plant_description', difficulty: 2,
    question: 'Under 35 U.S.C. 162, a plant patent cannot be declared invalid for noncompliance with 35 U.S.C. 112 if:',
    options: [
      'The examiner failed to object during prosecution.',
      'A deposit of plant material was made.',
      'The single claim uses formal terms.',
      'The description is as complete as is reasonably possible.',
      'The plant is commercially available for public inspection.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 162 relaxes the disclosure standard for plants: no invalidity for 112 noncompliance "if the description is as complete as is reasonably possible" — a recognition that living varieties resist the exactness expected of mechanical disclosures.',
  },
  {
    id: 'pb_gf6_045', topicId: 6, subtopic: 'plant_description', difficulty: 2,
    question: 'The specification of a plant patent application must include:',
    options: [
      'A deposit accession number from a recognized depository.',
      'The Latin name of the genus and species of the plant claimed.',
      'A DNA sequence listing.',
      'Certified pedigree records from a breeders’ registry.',
      'An affidavit from an independent botanist.',
    ],
    correct: 1,
    explanation: '37 CFR 1.163(a) requires the specification to contain the Latin name of the genus and species and the variety denomination. Plant PATENT applications have no deposit requirement — deposits belong to UTILITY-patent practice for biological material.',
  },
  {
    id: 'pb_gf6_046', topicId: 6, subtopic: 'plant_drawings', difficulty: 2,
    question: 'Drawings in a plant patent application:',
    options: [
      'Are never required.',
      'Must be mechanical ink drawings following 37 CFR 1.84 shading conventions.',
      'Are replaced by herbarium specimens.',
      'Must be artistically and competently executed, and must be in color when color is a distinguishing characteristic of the new variety.',
      'Must show the plant in winter dormancy.',
    ],
    correct: 3,
    explanation: '37 CFR 1.165: plant drawings are held to an ARTISTIC standard (not mechanical drafting conventions) and must disclose all distinctive characteristics capable of visual representation; when color distinguishes the variety, the drawing must be in color.',
  },
  {
    id: 'pb_gf6_047', topicId: 6, subtopic: 'plant_pvpa', difficulty: 2,
    question: 'Protection for a new SEXUALLY reproduced (seed-grown) plant variety through a Plant Variety Protection certificate is administered by:',
    options: [
      'The U.S. Department of Agriculture’s Plant Variety Protection Office — not the USPTO.',
      'The USPTO’s Technology Center 1600.',
      'The Patent Trial and Appeal Board.',
      'The International Bureau of WIPO.',
      'The Environmental Protection Agency.',
    ],
    correct: 0,
    explanation: 'The Plant Variety Protection Act (7 U.S.C. 2321 et seq.) is administered by the USDA’s Plant Variety Protection Office and covers sexually reproduced and tuber-propagated varieties — the varieties the plant patent statute excludes. It issues certificates, not patents.',
  },
  {
    id: 'pb_gf6_048', topicId: 6, subtopic: 'plant_pvpa', difficulty: 3,
    question: 'Regarding utility patents on plants, the Supreme Court held in J.E.M. Ag Supply v. Pioneer Hi-Bred that:',
    options: [
      'Plants may be protected only under the Plant Patent Act or the PVPA.',
      'Newly developed plants (including sexually reproduced hybrids) may be protected by utility patents under 35 U.S.C. 101; the Plant Patent Act and PVPA are not exclusive.',
      'Utility patents on plants are invalid as claiming products of nature.',
      'Only genetically engineered plants qualify for utility patents.',
      'The PVPA preempts all patent protection for seeds.',
    ],
    correct: 1,
    explanation: 'J.E.M. Ag Supply v. Pioneer Hi-Bred (2001): 35 U.S.C. 101 utility patents remain available for plants; neither the Plant Patent Act nor the PVPA is an exclusive regime. The utility route demands full 112 compliance (often met by seed deposit) in exchange for stronger rights.',
  },
  {
    id: 'pb_gf6_049', topicId: 6, subtopic: 'plant_eligibility', difficulty: 3,
    question: 'For a plant patent, invention is regarded as complete when:',
    options: [
      'The distinct new plant is first observed.',
      'The plant flowers for the first time.',
      'A patent application is filed.',
      'The plant is deposited with a public herbarium.',
      'The new variety has been both discovered (or created) and asexually reproduced, with the reproduction confirming that the distinguishing characteristics hold true.',
    ],
    correct: 4,
    explanation: 'Plant invention is a TWO-step act under 35 U.S.C. 161: (1) discovery or creation of the distinct new variety and (2) asexual reproduction demonstrating the characteristics are fixed. Observation alone — however distinct the plant — is not a complete invention.',
  },
  {
    id: 'pb_gf6_050', topicId: 6, subtopic: 'plant_eligibility', difficulty: 3,
    question: 'For purposes of 35 U.S.C. 161, which of the following is correct about what counts as a "plant"?',
    options: [
      'Bacteria and algae are both regarded as plants.',
      'Only flowering plants qualify.',
      'Algae and macro-fungi are regarded as plants, but bacteria are not.',
      'Fungi are categorically excluded as plants.',
      'Any living organism that photosynthesizes qualifies.',
    ],
    correct: 2,
    explanation: 'MPEP 1601: "plant" carries its ordinary horticultural meaning — algae and macro-fungi are within it, but BACTERIA are not (a bacterium may instead be utility-patent subject matter under Chakrabarty).',
  },
  {
    id: 'pb_gf6_051', topicId: 6, subtopic: 'plant_description', difficulty: 2,
    question: 'Specimens of the plant variety (flowers, fruit, etc.) in a plant patent application:',
    options: [
      'Must be filed with every application.',
      'Must be deposited with the American Type Culture Collection.',
      'Are furnished only if required by the examiner, and then as the Office directs.',
      'Replace the requirement for drawings.',
      'Are required only for fruit-bearing varieties.',
    ],
    correct: 2,
    explanation: '37 CFR 1.166: the applicant furnishes specimens (or plants) only when the examiner requires them, in the quantity and form directed. There is no routine specimen or deposit requirement in plant patent prosecution.',
  },
  {
    id: 'pb_gf6_052', topicId: 6, subtopic: 'plant_rights', difficulty: 3,
    question: 'A nursery independently breeds a rose that happens to be indistinguishable from a plant-patented rose, with no lineage from the patented plant. The nursery:',
    options: [
      'Infringes, because the varieties are indistinguishable.',
      'Does not infringe — plant patent infringement requires that the accused plant be an asexual reproduction (a descendant) of the actual patented plant; independent creation is a defense.',
      'Infringes unless it obtains a compulsory license.',
      'Does not infringe only if it holds a PVPA certificate.',
      'Infringes if it sells the rose within the same state as the patentee.',
    ],
    correct: 1,
    explanation: 'Imazio Nursery v. Dania Greenhouses (Fed. Cir. 1995): a plant patent covers the single claimed variety, and infringement requires asexual reproduction traceable to the patented plant itself. Independent development of an identical-looking plant does not infringe — unlike utility patent law, where independent invention is no defense.',
  },
  {
    id: 'pb_gf6_053', topicId: 6, subtopic: 'plant_eligibility', difficulty: 3,
    question: 'A grower discovers a distinct bud sport on a tree of a variety covered by someone else’s plant patent, and asexually reproduces the sport. The sport:',
    options: [
      'Belongs to the original patentee automatically.',
      'Is covered by the original plant patent.',
      'Cannot be patented for 20 years.',
      'Is unpatentable because it derives from patented material.',
      'May itself be patented by the grower if it is a distinct and new variety — a plant patent covers only the exact variety claimed, not its distinct sports or mutants.',
    ],
    correct: 4,
    explanation: 'A plant patent reaches only the single variety claimed. A sport or mutant that is DISTINCT and new is a different variety — separately patentable by whoever discovers (in a cultivated state) and asexually reproduces it, even though it arose on a patented plant.',
  },
  {
    id: 'pb_gf6_054', topicId: 6, subtopic: 'plant_drawings', difficulty: 1,
    question: 'The required standard for plant patent drawings is that they be:',
    options: [
      'Artistically and competently executed, disclosing all distinctive characteristics of the plant capable of visual representation.',
      'Prepared with drafting instruments following 37 CFR 1.84 mechanical conventions.',
      'Simple sketches, since 35 U.S.C. 162 relaxes all formal requirements.',
      'Photographic only.',
      'Executed by a certified botanical illustrator.',
    ],
    correct: 0,
    explanation: '37 CFR 1.165(a): plant drawings must be artistically and competently executed and disclose all distinctive characteristics capable of visual representation — an artistic standard, unlike the mechanical conventions of utility drawings.',
  },
  {
    id: 'pb_gf6_055', topicId: 6, subtopic: 'plant_pvpa', difficulty: 2,
    question: 'A breeder develops a new corn hybrid that is reproduced commercially from seed and does not want to pursue a utility patent. The appropriate protection is:',
    options: [
      'A plant patent from the USPTO.',
      'A design patent on the kernel’s appearance.',
      'A trademark on the hybrid’s name only — no variety protection exists.',
      'A Plant Variety Protection certificate from the USDA, since plant patents do not cover sexually reproduced varieties.',
      'A Hague international design registration.',
    ],
    correct: 3,
    explanation: 'A seed-reproduced (sexually reproduced) variety cannot get a plant patent (35 U.S.C. 161 requires asexual reproduction). The PVPA certificate from the USDA is the sexual-reproduction counterpart; a utility patent is the other option the breeder here declined.',
  },
  {
    id: 'pb_gf6_056', topicId: 6, subtopic: 'dp_comparison', difficulty: 2,
    question: 'Which correctly compares patent terms?',
    options: [
      'Utility, plant, and design patents all run 20 years from filing.',
      'Utility and design patents run from filing; plant patents run from grant.',
      'All three types run 15 years from grant.',
      'Design patents run 20 years from filing; utility and plant patents run 15 years from grant.',
      'Utility and plant patents run 20 years from the filing date; design patents run 15 years from the grant date (for applications filed on or after May 13, 2015).',
    ],
    correct: 4,
    explanation: 'Utility and plant patents: 20 years from the earliest U.S. filing date (35 U.S.C. 154). Design patents: 15 years from GRANT for applications filed on/after May 13, 2015 (14 from grant before that). Only utility patents pay maintenance fees.',
  },
  {
    id: 'pb_gf6_057', topicId: 6, subtopic: 'design_priority', difficulty: 3,
    question: 'A design application’s attempt to claim the benefit of an earlier provisional application under 35 U.S.C. 119(e):',
    options: [
      'Is proper if the design application is filed within 12 months of the provisional.',
      'Is improper — 119(e) benefit is not available for design applications.',
      'Is proper if the provisional contained drawings of the design.',
      'Is proper only for Hague international design applications.',
      'Converts the provisional into a design application.',
    ],
    correct: 1,
    explanation: '35 U.S.C. 172 provides that the right of priority under 119(e) does not apply to designs — a design application may not claim provisional benefit regardless of what the provisional disclosed. (It MAY claim 120 benefit of an earlier nonprovisional.)',
  },
  {
    id: 'pb_gf6_058', topicId: 6, subtopic: 'plant_eligibility', difficulty: 1,
    question: 'A farmer develops an improved Irish potato variety propagated from its tubers. A plant patent is:',
    options: [
      'Unavailable — tuber-propagated plants are expressly excluded from plant patent protection (the PVPA covers them instead).',
      'Available if the potato is also seed-sterile.',
      'Available, because tuber propagation is a form of asexual reproduction.',
      'Available with a USDA waiver.',
      'Available only as a design patent on the tuber’s shape.',
    ],
    correct: 0,
    explanation: 'Although tuber propagation IS asexual, 35 U.S.C. 161 expressly excludes tuber-propagated plants (Irish potato, Jerusalem artichoke are the MPEP 1601 examples) — the part propagated is also the food. Since 1994 the PVPA covers tuber-propagated varieties.',
  },
  {
    id: 'pb_gf6_059', topicId: 6, subtopic: 'design_subject_matter', difficulty: 2,
    question: 'Under 35 U.S.C. 171(b), the provisions of Title 35 relating to patents for inventions:',
    options: [
      'Do not apply to design patents at all.',
      'Apply to design patents without any exception.',
      'Apply only through the rules in 37 CFR Part 11.',
      'Apply to patents for designs, except as otherwise provided (for example, the six-month foreign priority period and the from-grant term).',
      'Apply only to design applications filed through the Hague system.',
    ],
    correct: 3,
    explanation: '35 U.S.C. 171(b): utility-patent provisions apply to designs "except as otherwise provided." Design practice therefore mirrors utility practice by default, with specific carve-outs — the 172 six-month priority, the 173 from-grant term, no provisionals, no pre-grant publication, CPA availability, and the 289 remedy.',
  },
  {
    id: 'pb_gf6_060', topicId: 6, subtopic: 'design_examination', difficulty: 3,
    question: 'Prioritized examination ("Track One") under 37 CFR 1.102(e):',
    options: [
      'Is available for utility, plant, and design applications alike.',
      'Is available only for design applications.',
      'Is available for original utility and plant applications, but NOT design applications — designs use expedited examination under 37 CFR 1.155 instead.',
      'Replaced the design rocket docket in 2013.',
      'Requires a preexamination search for utility applications.',
    ],
    correct: 2,
    explanation: '37 CFR 1.102(e) offers prioritized examination for original UTILITY and PLANT nonprovisional applications; design applications are excluded and have their own expedited route (1.155, which — unlike Track One — requires a preexamination search and IDS).',
  },
  {
    id: 'pb_gf6_061', topicId: 6, subtopic: 'design_claim', difficulty: 3,
    question: 'The design claim wording "as shown and described" (rather than simply "as shown") is appropriate when:',
    options: [
      'The application contains only photographs.',
      'The specification includes a proper descriptive statement — for example, describing modified forms of the design or the meaning of broken-line showings.',
      'The design is claimed for only a portion of an article.',
      'A foreign priority claim is present.',
      'Never — that wording was abolished by the PLTIA.',
    ],
    correct: 1,
    explanation: '37 CFR 1.153 and MPEP 1503.01: the claim reads "as shown" when the drawings alone disclose the design, and "as shown and described" when the specification contains a proper special description (modified forms, broken-line statements, characteristic-feature statements).',
  },
  {
    id: 'pb_gf6_062', topicId: 6, subtopic: 'design_subject_matter', difficulty: 2,
    question: 'A beautiful abstract painting, claimed as such (not applied to or embodied in any article of manufacture):',
    options: [
      'Is proper design subject matter because it is ornamental.',
      'Is proper design subject matter if reproduced in multiple copies.',
      'Is proper subject matter under 35 U.S.C. 101 instead.',
      'Is not proper design subject matter — a design must be embodied in or applied to an article of manufacture; a picture standing alone is not enough.',
      'Is registrable as a plant patent.',
    ],
    correct: 3,
    explanation: 'MPEP 1504.01: the design must be inseparable from an article of manufacture — a picture or surface ornamentation per se, untethered to an article, is not 171 subject matter. Artwork as such is the domain of copyright.',
  },
  {
    id: 'pb_gf6_063', topicId: 6, subtopic: 'design_hague', difficulty: 3,
    question: 'A design was made in the United States. Before filing an international design application DIRECTLY with the International Bureau of WIPO, the applicant should:',
    options: [
      'File a petition to make special.',
      'Obtain USPTO certification of the design’s novelty.',
      'Obtain a foreign filing license (or instead file through the USPTO as office of indirect filing, where the security screening occurs).',
      'Record an assignment with the USPTO.',
      'Nothing — design applications are exempt from foreign filing license requirements.',
    ],
    correct: 2,
    explanation: '35 U.S.C. 184’s foreign filing license requirement applies to designs made in the U.S. Filing through the USPTO as office of indirect filing satisfies the security-review path; filing directly with WIPO without a license risks the 35 U.S.C. 185 bar (MPEP 2903).',
  },
  {
    id: 'pb_gf6_064', topicId: 6, subtopic: 'design_priority', difficulty: 3,
    question: 'In a design application, the time limits of 37 CFR 1.55(d) (priority claim within the later of 4 months from filing or 16 months from the foreign filing):',
    options: [
      'Do not apply — in a design application, a claim for foreign priority may be presented during the pendency of the application (up until payment of the issue fee).',
      'Apply exactly as in utility applications.',
      'Are shortened to 2 and 8 months respectively.',
      'Apply only to Hague-based priority claims.',
      'Were eliminated for all application types.',
    ],
    correct: 0,
    explanation: '37 CFR 1.55(d)’s 4/16-month window expressly does not apply to design applications: a design priority claim may be made while the application is pending, up to payment of the issue fee (MPEP 1504.10). The underlying six-month filing deadline of 35 U.S.C. 172 still governs whether priority EXISTS.',
  },
  {
    id: 'pb_gf6_065', topicId: 6, subtopic: 'plant_description', difficulty: 3,
    question: 'The inventor’s oath or declaration in a plant patent application differs from utility practice in that it must also state:',
    options: [
      'The inventor’s horticultural qualifications.',
      'The commercial value of the variety.',
      'That specimens have been deposited.',
      'That the USDA has inspected the variety.',
      'That the inventor has asexually reproduced the plant — and, for a newly found plant, that it was found in a cultivated area.',
    ],
    correct: 4,
    explanation: '37 CFR 1.162: the plant oath/declaration includes the statement that the inventor asexually reproduced the plant, and — where the plant is a newly found plant — that it was found in a cultivated area (tracking the 161 exclusion of uncultivated finds).',
  },
  {
    id: 'pb_gf6_066', topicId: 6, subtopic: 'plant_pvpa', difficulty: 3,
    question: 'Which statement correctly distinguishes PVPA certificates from utility patents on plants?',
    options: [
      'The PVPA contains statutory exemptions — such as the saved-seed and research exemptions — that have no counterpart in utility patent law.',
      'Utility patents on plants are examined by the USDA.',
      'PVPA certificates are unexamined registrations.',
      'A variety may never hold both a PVPA certificate and a patent.',
      'PVPA certificates cover asexually reproduced varieties only.',
    ],
    correct: 0,
    explanation: 'As J.E.M. v. Pioneer emphasized, the PVPA’s saved-seed and research exemptions limit certificate rights in ways utility patent law does not — part of why breeders may prefer utility patents. PVP applications ARE examined (for distinctness, uniformity, stability) by the USDA, dual protection is possible, and the PVPA covers sexually reproduced and tuber-propagated varieties.',
  },
];
