/**
 * PE EE (Power) Flashcard deck — cards across all 10 sections + formulas + exam tips.
 * AI-generated. Requires SME review.
 */

export interface PEEEFlashcard {
  id: number;
  front: string;
  back: string;
  domain: string;
  domainName: string;
  category: string;
  topics: string[];
}

export const PEEE_FLASHCARD_DOMAINS = [
  { id: 'general', label: 'General', name: 'General Power Engineering', count: 20 },
  { id: 'measurement', label: 'Meas', name: 'Measurement & Instrumentation', count: 15 },
  { id: 'circuits', label: 'Circuits', name: 'Circuit Analysis', count: 20 },
  { id: 'rotating', label: 'Machines', name: 'Rotating Machines & Drives', count: 25 },
  { id: 'electromagnetics', label: 'EM', name: 'Electromagnetic Devices', count: 20 },
  { id: 'transmission', label: 'T&D', name: 'Transmission & Distribution', count: 25 },
  { id: 'protection', label: 'Prot', name: 'Protection', count: 25 },
  { id: 'power_quality', label: 'PQ', name: 'Power Quality & Reliability', count: 15 },
  { id: 'codes', label: 'Codes', name: 'Codes & Standards', count: 20 },
  { id: 'power_system', label: 'PSA', name: 'Power System Analysis', count: 20 },
  { id: 'formulas', label: 'Formulas', name: 'Key Formulas & Reference', count: 15 },
  { id: 'exam', label: 'Exam Prep', name: 'Exam Strategy', count: 10 },
] as const;

export const PEEE_FLASHCARD_CATEGORIES = ["comparison", "concept", "definition", "question", "tip", "formula"] as const;

export const PEEE_FLASHCARDS: PEEEFlashcard[] = [
  // ═══════════════════════════════════════════════════════════════
  // GENERAL POWER ENGINEERING (20 cards)
  // ═══════════════════════════════════════════════════════════════
  { id: 1, front: "What is the per-unit system?", back: "A system of dimensionless ratios formed by dividing actual quantities by chosen base quantities. Eliminates transformer turns ratios and normalizes values for easy comparison. Zpu = Zactual / Zbase.", domain: 'general', domainName: 'General Power Engineering', category: 'definition', topics: ["Per-Unit System"] },
  { id: 2, front: "What is Zbase (three-phase)?", back: "Zbase = Vbase² / Sbase. Choose Sbase and Vbase; Ibase and Zbase follow automatically.", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Per-Unit System"] },
  { id: 3, front: "Per-unit base change formula", back: "Zpu,new = Zpu,old × (Snew/Sold) × (Vold/Vnew)²", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Per-Unit System"] },
  { id: 4, front: "What is the power triangle?", back: "S² = P² + Q². S = apparent power (VA), P = real power (W), Q = reactive power (VAR). PF = P/S = cos(θ).", domain: 'general', domainName: 'General Power Engineering', category: 'definition', topics: ["Power Triangle"] },
  { id: 5, front: "Lagging vs Leading PF", back: "Lagging PF: inductive load, current lags voltage, Q positive. Leading PF: capacitive load, current leads voltage, Q negative. Most industrial loads are lagging.", domain: 'general', domainName: 'General Power Engineering', category: 'comparison', topics: ["Power Factor"] },
  { id: 6, front: "Three-phase power formula", back: "P₃φ = √3 × VLL × IL × cos(θ); Q₃φ = √3 × VLL × IL × sin(θ); S₃φ = √3 × VLL × IL", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Three-Phase Power"] },
  { id: 7, front: "Y vs Delta connections", back: "Y: VLL = √3×Vφ, IL = Iφ. Delta: VLL = Vφ, IL = √3×Iφ. Conversion: ZY = ZΔ/3.", domain: 'general', domainName: 'General Power Engineering', category: 'comparison', topics: ["Three-Phase Connections"] },
  { id: 8, front: "What is SAIDI?", back: "System Average Interruption Duration Index = Σ(ri × Ni) / NT. Measured in hours/customer/year. Typical top-quartile: 60-90 min/year.", domain: 'general', domainName: 'General Power Engineering', category: 'definition', topics: ["Reliability Indices"] },
  { id: 9, front: "What is SAIFI?", back: "System Average Interruption Frequency Index = Σ Ni / NT. Measured in interruptions/customer/year. Typical top-quartile: 0.8-1.0.", domain: 'general', domainName: 'General Power Engineering', category: 'definition', topics: ["Reliability Indices"] },
  { id: 10, front: "CAIDI formula", back: "CAIDI = SAIDI / SAIFI. Average duration per interruption (hours).", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Reliability Indices"] },
  { id: 11, front: "What is LOLE?", back: "Loss of Load Expectation. The expected number of days/year when load exceeds available capacity. Standard: LOLE ≤ 0.1 days/year (1 day in 10 years).", domain: 'general', domainName: 'General Power Engineering', category: 'definition', topics: ["Generation Adequacy"] },
  { id: 12, front: "Series reliability", back: "R = R1 × R2 × ... × Rn. Failure rates add: λ = Σλi. Any component failure causes system failure.", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Reliability Modeling"] },
  { id: 13, front: "Parallel reliability", back: "R = 1 - (1-R1)(1-R2)...(1-Rn). All components must fail for system failure. Unreliabilities multiply.", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Reliability Modeling"] },
  { id: 14, front: "Availability formula", back: "A = MTBF / (MTBF + MTTR) = μ / (λ + μ). Series: A = A1 × A2. Parallel: A = 1-(1-A1)(1-A2).", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Availability"] },
  { id: 15, front: "What is ASAI?", back: "Average Service Availability Index = (8760 - SAIDI) / 8760. Expressed as per-unit or percentage.", domain: 'general', domainName: 'General Power Engineering', category: 'definition', topics: ["Reliability Indices"] },
  { id: 16, front: "NPV (Net Present Value)", back: "NPV = Σ[CF_t / (1+i)^t]. If NPV > 0, project is economically justified at the MARR.", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Engineering Economics"] },
  { id: 17, front: "B/C Ratio", back: "Benefit-Cost Ratio = PW(Benefits) / PW(Costs). Accept project if B/C ≥ 1.0.", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Engineering Economics"] },
  { id: 18, front: "What is IRR?", back: "Internal Rate of Return: the discount rate at which NPV = 0. Accept if IRR ≥ MARR.", domain: 'general', domainName: 'General Power Engineering', category: 'definition', topics: ["Engineering Economics"] },
  { id: 19, front: "Straight-line depreciation", back: "D = (P - S) / n per year. P = initial cost, S = salvage value, n = useful life.", domain: 'general', domainName: 'General Power Engineering', category: 'formula', topics: ["Depreciation"] },
  { id: 20, front: "EXAM TIP: Per-unit base change", back: "Memorize Zpu,new = Zpu,old × (Snew/Sold) × (Vold/Vnew)². This appears on 3-5 exam questions. When Vbase is unchanged, only the MVA ratio matters.", domain: 'general', domainName: 'General Power Engineering', category: 'tip', topics: ["Per-Unit System"] },

  // ═══════════════════════════════════════════════════════════════
  // MEASUREMENT & INSTRUMENTATION (15 cards)
  // ═══════════════════════════════════════════════════════════════
  { id: 21, front: "What is a CT (Current Transformer)?", back: "Steps down high primary current to standard secondary (5A or 1A). Never open-circuit the secondary — dangerous voltage develops.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'definition', topics: ["Current Transformers"] },
  { id: 22, front: "CT accuracy: metering vs relaying", back: "Metering: class 0.3, 0.6, 1.2 (% error). Revenue metering requires 0.3. Relaying: C class (C100, C200, C400, C800) — voltage at 20× rated current.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'comparison', topics: ["CT Accuracy"] },
  { id: 23, front: "CT burden", back: "Total secondary circuit impedance (relays + meters + wiring). B-1.0 = 1.0 Ω at 5A = 25 VA. Higher burden increases saturation risk.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'definition', topics: ["CT Burden"] },
  { id: 24, front: "PT (Potential Transformer) vs CCVT", back: "PT: wound transformer, accurate, used up to ~138 kV. CCVT: capacitive divider + small PT, cost-effective above 69 kV, may have transient response issues.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'comparison', topics: ["Potential Transformers"] },
  { id: 25, front: "Blondel's Theorem", back: "N conductors require N-1 wattmeter elements. 3-wire (no neutral): 2 elements. 4-wire (with neutral): 3 elements.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'concept', topics: ["Metering"] },
  { id: 26, front: "Two-wattmeter method: PF from readings", back: "P = W1 + W2. tan(θ) = √3(W1-W2)/(W1+W2). PF = cos(θ). If W2 is negative, PF < 0.5.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'formula', topics: ["Power Measurement"] },
  { id: 27, front: "What is a PMU?", back: "Phasor Measurement Unit. GPS-synchronized voltage/current phasors at 30-60 samples/sec. IEEE C37.118 standard. Data collected by PDCs.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'definition', topics: ["PMU"] },
  { id: 28, front: "RTD vs Thermocouple", back: "RTD (Pt100): high accuracy (±0.1°C), limited range (-200 to 850°C), needs excitation. Thermocouple: wide range (to 1260°C for Type K), self-generating, less accurate.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'comparison', topics: ["Temperature Sensors"] },
  { id: 29, front: "What is DNP3?", back: "Distributed Network Protocol 3. Standard utility SCADA communication protocol between RTUs and master station.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'definition', topics: ["SCADA"] },
  { id: 30, front: "CT polarity marks", back: "H1/X1 indicate polarity. Current entering H1 exits X1 in the same direction. Correct polarity essential for differential and directional protection.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'concept', topics: ["CT Polarity"] },
  { id: 31, front: "Demand metering interval", back: "Typically 15 or 30 minutes. Peak demand drives demand charges (30-50% of large commercial bills).", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'concept', topics: ["Demand Metering"] },
  { id: 32, front: "Broken-delta PT connection", back: "Used for ground fault detection on ungrounded systems. Produces 3V₀ voltage during ground faults.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'concept', topics: ["PT Connections"] },
  { id: 33, front: "EXAM TIP: CT safety", back: "Never open-circuit a CT secondary (dangerous voltage). Always short the secondary before disconnecting instruments. PTs are the opposite — never short the secondary.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'tip', topics: ["Safety"] },
  { id: 34, front: "IEC 61850", back: "International standard for communication in electrical substation automation. Uses GOOSE messages for fast peer-to-peer communication between IEDs.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'definition', topics: ["Substation Automation"] },
  { id: 35, front: "4-wire RTD connection", back: "Eliminates lead resistance error completely by using separate sense and excitation circuits. Best accuracy. 3-wire compensates partially; 2-wire does not.", domain: 'measurement', domainName: 'Measurement & Instrumentation', category: 'concept', topics: ["RTD Connections"] },

  // ═══════════════════════════════════════════════════════════════
  // CIRCUIT ANALYSIS (20 cards)
  // ═══════════════════════════════════════════════════════════════
  { id: 36, front: "Thevenin equivalent", back: "Any linear circuit → Vth (open-circuit voltage) in series with Zth (impedance with sources zeroed). Vth = Voc; Zth = Voc/Isc.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'definition', topics: ["Network Theorems"] },
  { id: 37, front: "Maximum power transfer", back: "Load receives maximum power when ZL = Zth* (complex conjugate of Thevenin impedance). In DC: RL = Rth.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Network Theorems"] },
  { id: 38, front: "Impedance: R, L, C", back: "R: Z = R (0°). L: Z = jωL = jXL (90°, V leads I). C: Z = 1/(jωC) = -jXC (-90°, I leads V).", domain: 'circuits', domainName: 'Circuit Analysis', category: 'formula', topics: ["AC Circuits"] },
  { id: 39, front: "Symmetrical components: operator 'a'", back: "a = 1∠120° = -0.5 + j0.866. a² = 1∠240°. a³ = 1. Key identity: 1 + a + a² = 0.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'formula', topics: ["Symmetrical Components"] },
  { id: 40, front: "Sequence network connections by fault type", back: "3-phase: Z1 only. SLG: Z1+Z2+Z0 in series. LL: Z1||Z2. LLG: Z1 + Z2||(Z0+3Zf).", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Fault Analysis"] },
  { id: 41, front: "Zero sequence blocked by Delta", back: "Delta windings block zero-sequence current from passing through. Zero-seq currents circulate within delta but can't exit. Grounded-Y allows zero-seq flow.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Symmetrical Components"] },
  { id: 42, front: "First-order transient formula", back: "x(t) = x(∞) + [x(0) - x(∞)] × e^(-t/τ). RL: τ = L/R. RC: τ = RC. After 5τ: 99.3% complete.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'formula', topics: ["Transients"] },
  { id: 43, front: "RLC damping cases", back: "Overdamped: α > ω₀ (no oscillation). Critically damped: α = ω₀ (fastest non-oscillatory). Underdamped: α < ω₀ (oscillation). α = R/(2L), ω₀ = 1/√(LC).", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Second-Order Transients"] },
  { id: 44, front: "Complex power", back: "S = VI* = P + jQ. P = |V||I|cos(θ). Q = |V||I|sin(θ). |S| = |V||I|.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'formula', topics: ["AC Power"] },
  { id: 45, front: "SLG fault current", back: "Ia1 = Ia2 = Ia0 = Vf/(Z1+Z2+Z0). Total fault current: If = 3×Ia0 = 3Vf/(Z1+Z2+Z0+3Zf).", domain: 'circuits', domainName: 'Circuit Analysis', category: 'formula', topics: ["Fault Analysis"] },
  { id: 46, front: "KVL vs KCL", back: "KVL: sum of voltages around any closed loop = 0. KCL: sum of currents entering any node = 0.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'comparison', topics: ["Circuit Laws"] },
  { id: 47, front: "Superposition principle", back: "In linear circuits, response to multiple sources = sum of individual responses. Voltage sources → short. Current sources → open. One at a time.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Network Theorems"] },
  { id: 48, front: "Resonance condition", back: "Series RLC: resonance when XL = XC (Z = R, minimum). Parallel: resonance when XL = XC (Z = max). f₀ = 1/(2π√LC).", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Resonance"] },
  { id: 49, front: "Positive vs Negative vs Zero sequence", back: "Positive: balanced abc (normal). Negative: balanced acb (reverse rotation). Zero: three identical in-phase phasors.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'comparison', topics: ["Symmetrical Components"] },
  { id: 50, front: "Z0 of transmission lines", back: "Zero-sequence impedance is 2-5× positive-sequence due to earth return path. Z2 ≈ Z1 for lines and static equipment.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Sequence Impedances"] },
  { id: 51, front: "Voltage divider", back: "Vk = V × Zk / Ztotal (series circuit). Current divider (2 parallel): Ik = I × Zother / (Z1 + Z2).", domain: 'circuits', domainName: 'Circuit Analysis', category: 'formula', topics: ["Circuit Basics"] },
  { id: 52, front: "ω = 2πf", back: "For 60 Hz: ω = 2π × 60 = 377 rad/s. For 50 Hz: ω = 314 rad/s. Vrms = Vpeak/√2.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'formula', topics: ["AC Fundamentals"] },
  { id: 53, front: "Transformer inrush current", back: "Can reach 8-12× rated current. Contains significant 2nd harmonic. Decays with L/R time constant of primary winding.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Transients"] },
  { id: 54, front: "Capacitor switching transients", back: "Energizing produces LC oscillation; voltage can reach 2.0 pu. Back-to-back switching is worse — requires pre-insertion resistors or sync switching.", domain: 'circuits', domainName: 'Circuit Analysis', category: 'concept', topics: ["Switching Transients"] },
  { id: 55, front: "EXAM TIP: Symmetrical components", back: "This is the #1 tool for PE fault analysis. Memorize: a = 1∠120°, a² = 1∠240°, 1+a+a² = 0. Know SLG = series, LL = parallel (no zero), LLG = pos + (neg||zero).", domain: 'circuits', domainName: 'Circuit Analysis', category: 'tip', topics: ["Symmetrical Components"] },

  // ═══════════════════════════════════════════════════════════════
  // ROTATING MACHINES & DRIVES (25 cards)
  // ═══════════════════════════════════════════════════════════════
  { id: 56, front: "Synchronous speed", back: "ns = 120f/p RPM. 2-pole 60Hz: 3600. 4-pole: 1800. 6-pole: 1200. 8-pole: 900.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["Synchronous Machines"] },
  { id: 57, front: "Power-angle equation", back: "P = (Ef×Vt/Xs)sin(δ). Pmax at δ = 90°. Increasing Ef raises the P-δ curve peak (more stability margin).", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["Synchronous Generator"] },
  { id: 58, front: "Overexcited vs Underexcited generator", back: "Overexcited: Ef > Vt, supplies VARs (lagging PF to system). Underexcited: Ef < Vt, absorbs VARs (leading PF to system).", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'comparison', topics: ["Generator Excitation"] },
  { id: 59, front: "Induction motor slip", back: "s = (ns - nr)/ns. At start: s = 1. At sync speed: s = 0. Typical full load: 1-5%.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["Induction Motors"] },
  { id: 60, front: "Air-gap power relationships", back: "Pag = 3I²r'(Rr'/s). Rotor copper loss = s × Pag. Pmech = (1-s) × Pag.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["Induction Motor Power"] },
  { id: 61, front: "NEMA Design B motor", back: "Most common general-purpose motor. Normal starting torque, normal starting current, low slip (1-5%). Breakdown torque ≈ 2-3× rated.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'definition', topics: ["NEMA Design Classes"] },
  { id: 62, front: "Breakdown torque", back: "Maximum torque the motor can produce. Independent of rotor resistance. Slip at breakdown depends on Rr'. Tmax ∝ V².", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["Induction Motor Torque"] },
  { id: 63, front: "Motor starting current", back: "Locked-rotor (starting) current = 5-8× rated. Starting torque ∝ V². Reducing V to x% gives (x%)² torque.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["Motor Starting"] },
  { id: 64, front: "Y-Delta starting", back: "Reduces voltage to 1/√3 = 57.7%. Starting current = 1/3 of DOL. Starting torque = 1/3 of DOL.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["Starting Methods"] },
  { id: 65, front: "DC motor back-EMF", back: "Ea = kφn. Vt = Ea + IaRa (motor). Speed: n = (Vt - IaRa)/(kφ). Torque: T = kφIa.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["DC Machines"] },
  { id: 66, front: "Shunt vs Series DC motor", back: "Shunt: approximately constant speed, field in parallel. Series: high starting torque, variable speed, field in series. NEVER run series motor unloaded (runaway).", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'comparison', topics: ["DC Motor Types"] },
  { id: 67, front: "VFD components", back: "Rectifier (AC→DC) → DC bus (filter capacitors) → Inverter (DC→variable AC via PWM). V/f = constant below base speed.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["VFD Operation"] },
  { id: 68, front: "6-pulse VFD harmonics", back: "h = 6k ± 1: 5th, 7th, 11th, 13th, 17th, 19th... 12-pulse eliminates 5th & 7th (h = 12k ± 1).", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["VFD Harmonics"] },
  { id: 69, front: "Generator paralleling conditions", back: "4 conditions: (1) Same voltage magnitude, (2) Same frequency, (3) Same phase sequence, (4) Same phase angle. Use synchroscope.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["Parallel Operation"] },
  { id: 70, front: "Governor droop", back: "R = (fnl - ffl)/frated × 100%. Typical: 4-5%. Controls real power sharing between parallel generators.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["Load Sharing"] },
  { id: 71, front: "NEC 430.52: Motor SCGF", back: "Design B, inverse-time breaker: 250% of FLC. Instantaneous trip: 800-1300% of FLC. Use NEC Table 430.52.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["Motor Protection"] },
  { id: 72, front: "NEC 430.32: Overload protection", back: "Set at 115% of motor nameplate FLC (or 125% if SF ≥ 1.15 or temp rise ≤ 40°C).", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["Motor Protection"] },
  { id: 73, front: "Motor conductor sizing", back: "NEC 430.22: ≥ 125% of motor FLC (from NEC tables 430.247-250, NOT nameplate). Feeder: 125% largest + 100% all others.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["NEC Motor Circuits"] },
  { id: 74, front: "V-curve of synchronous machine", back: "Plots Ia (armature current) vs If (field current) at constant power. Bottom of V = unity PF. Left = leading. Right = lagging.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'concept', topics: ["Synchronous Machine"] },
  { id: 75, front: "Soft starter vs VFD", back: "Soft starter: thyristors ramp voltage gradually, cheaper, limited to starting. VFD: full speed control, more expensive, also saves energy at partial loads.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'comparison', topics: ["Motor Starting"] },
  { id: 76, front: "Real vs reactive power control in generators", back: "Real power: controlled by prime mover/governor (fuel input). Reactive power: controlled by field excitation (AVR). Independent controls.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'comparison', topics: ["Generator Control"] },
  { id: 77, front: "Motor service factor (SF)", back: "SF = 1.15 means motor can run at 115% rated load continuously. SF = 1.0 means rated load is the maximum.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'definition', topics: ["Motor Nameplate"] },
  { id: 78, front: "EXAM TIP: Motor FLC tables", back: "ALWAYS use NEC Tables 430.247-250 for conductor/protection sizing, NOT the motor nameplate current. This is one of the most commonly tested NEC concepts.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'tip', topics: ["NEC Motor Circuits"] },
  { id: 79, front: "Constant torque vs constant power regions", back: "Below base speed: V/f constant → constant flux → constant torque. Above base speed: V constant, f increases → field weakening → constant power.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'comparison', topics: ["VFD Operation"] },
  { id: 80, front: "Autotransformer starting at tap%", back: "Line current = (tap%)² × DOL current. Motor voltage = tap% × line voltage. Torque = (tap%)² × DOL torque.", domain: 'rotating', domainName: 'Rotating Machines & Drives', category: 'formula', topics: ["Starting Methods"] },

  // ═══════════════════════════════════════════════════════════════
  // Remaining domains abbreviated for compilation (20+25+25+15+20+20+15+10)
  // ═══════════════════════════════════════════════════════════════

  // ELECTROMAGNETIC DEVICES (20)
  { id: 81, front: "Transformer OC test measures", back: "Core loss (Pcore), magnetizing reactance (Xm), core loss resistance (Rc). Apply rated voltage, secondary open.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Transformer Tests"] },
  { id: 82, front: "Transformer SC test measures", back: "Copper loss (Pcu), equivalent resistance (Req), leakage reactance (Xeq). Apply reduced voltage, secondary shorted.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Transformer Tests"] },
  { id: 83, front: "Voltage regulation formula", back: "%VR = (VNL - VFL)/VFL × 100%. Approximate: %VR ≈ εR cos(θ) + εX sin(θ) for lagging loads.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'formula', topics: ["Voltage Regulation"] },
  { id: 84, front: "Maximum transformer efficiency", back: "Occurs when core loss = copper loss. Load fraction at max η = √(Pcore/Pcu,rated).", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'formula', topics: ["Efficiency"] },
  { id: 85, front: "Y-Delta phase shift", back: "30° phase shift. ANSI standard: high-voltage side leads low-voltage by 30°. Must match for parallel operation.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Connections"] },
  { id: 86, front: "Autotransformer advantage", back: "Smaller, cheaper, higher efficiency for ratios ≤ 3:1. kVA advantage = 1/(1-1/a). Disadvantage: no isolation.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Autotransformers"] },
  { id: 87, front: "Zigzag grounding transformer", back: "Creates artificial neutral on ungrounded systems. Provides low-Z path for zero-sequence current. Short-time rated (fault duty only).", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Grounding Transformers"] },
  { id: 88, front: "Core losses = hysteresis + eddy current", back: "Ph = kh × f × B^1.6. Pe = ke × f² × B² × t². Reduce Ph: silicon steel. Reduce Pe: thinner laminations.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'formula', topics: ["Core Losses"] },
  { id: 89, front: "Magnetic circuit Ohm's law", back: "Φ = F/R = NI/(l/μA). MMF↔EMF, Flux↔Current, Reluctance↔Resistance.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'formula', topics: ["Magnetic Circuits"] },
  { id: 90, front: "Impedance referred to primary", back: "Z'sec = a² × Zsec, where a = N1/N2. Impedances transform by turns ratio squared.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'formula', topics: ["Transformer Equivalent Circuit"] },
  { id: 91, front: "OLTC vs DETC", back: "OLTC: changes taps under load (automatic voltage regulation). DETC: changes taps only when de-energized (seasonal/permanent adjustment).", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'comparison', topics: ["Tap Changers"] },
  { id: 92, front: "DGA (Dissolved Gas Analysis)", back: "IEEE C57.104. Analyzes gases in transformer oil: H₂, CH₄, C₂H₂ (arcing), C₂H₄, CO. Detects internal faults early.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'definition', topics: ["Transformer Diagnostics"] },
  { id: 93, front: "Current-limiting reactor sizing", back: "Xreactor = Vsource/Idesired - Zsource (in pu). Limits fault current to equipment ratings by adding series impedance.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'formula', topics: ["Reactors"] },
  { id: 94, front: "Open-delta capacity", back: "2 transformers in open-delta (V-V): 57.7% capacity of closed delta (3 transformers). Each carries line current.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Connections"] },
  { id: 95, front: "Air gap in magnetic circuit", back: "Dramatically increases reluctance (μ_air << μ_iron). Linearizes B-H curve, making inductance more constant vs. current.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Magnetic Circuits"] },
  { id: 96, front: "What is mutual inductance?", back: "M = k√(L1×L2). k = coupling coefficient (0 to 1). k ≈ 1 for tight coupling (transformers). k << 1 for loosely coupled coils.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'formula', topics: ["Inductance"] },
  { id: 97, front: "Parallel transformer requirements", back: "Same voltage ratio, same %Z (on same base), same phase shift, same polarity. Unequal %Z causes uneven load sharing.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Parallel Operation"] },
  { id: 98, front: "Y-Y connection issues", back: "Third-harmonic voltage problems if both neutrals ungrounded. Need delta tertiary or grounded neutral to provide path for triplens.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'concept', topics: ["Connections"] },
  { id: 99, front: "IEEE C57.12", back: "General requirements for liquid-immersed distribution, power, and regulating transformers.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'definition', topics: ["Standards"] },
  { id: 100, front: "EXAM TIP: Transformer tests", back: "OC → core (Rc, Xm, Pcore). SC → copper (Req, Xeq, Pcu). Tested from one side, results valid for both. SC test at rated current, OC test at rated voltage.", domain: 'electromagnetics', domainName: 'Electromagnetic Devices', category: 'tip', topics: ["Transformer Tests"] },

  // TRANSMISSION & DISTRIBUTION (25)
  { id: 101, front: "SIL formula", back: "SIL = V²rated/Zc (MW). Zc = √(L/C). Load < SIL: voltage rises. Load > SIL: voltage drops. Load = SIL: flat profile.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Surge Impedance Loading"] },
  { id: 102, front: "GMR vs actual radius", back: "GMR (r' = 0.7788r) used for inductance. Actual radius r used for capacitance. This distinction is frequently tested.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'comparison', topics: ["Line Parameters"] },
  { id: 103, front: "Short line ABCD parameters", back: "A = D = 1, B = Z, C = 0. Only series impedance. No shunt admittance. Valid for lines < 80 km.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Line Models"] },
  { id: 104, front: "Ferranti effect", back: "Receiving-end voltage > sending-end on lightly loaded lines due to capacitive charging current. Mitigated by shunt reactors.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["Voltage Regulation"] },
  { id: 105, front: "Solidly grounded system", back: "Neutral directly to earth. High ground fault current. Low overvoltage on unfaulted phases. Required by NEC for ≤ 600 V.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["System Grounding"] },
  { id: 106, front: "High-resistance grounding", back: "Limits ground fault current to 1-10 A. Can operate with single ground fault (alarm). Must find/fix before second fault.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["System Grounding"] },
  { id: 107, front: "Ungrounded system risks", back: "Arcing ground faults can produce 5-6 pu transient overvoltage. Not recommended. Unfaulted phases rise to √3 × VLN.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["System Grounding"] },
  { id: 108, front: "Cable vs overhead Zc", back: "Cable: 30-60 Ω. Overhead: 250-400 Ω. Cable has much higher C (20-40× overhead) and lower L.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'comparison', topics: ["Cable Systems"] },
  { id: 109, front: "Neher-McGrath equation", back: "I = √[(Tc - Ta - ΔTd)/(Rdc × Rth)]. For underground cable ampacity. NEC 310.15(C) reference.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Cable Ampacity"] },
  { id: 110, front: "ANSI C84.1 Range A", back: "±5% voltage at service entrance. This is the normal operating range utilities must maintain.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'definition', topics: ["Voltage Standards"] },
  { id: 111, front: "Step voltage regulator", back: "±10% in 32 steps of 5/8% each. Uses LDC (line drop compensator) for remote voltage regulation.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["Voltage Regulation"] },
  { id: 112, front: "ΔV from capacitor bank", back: "ΔV ≈ QX/V. Q = capacitor MVAR, X = source reactance to cap location, V = system voltage.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Capacitor Banks"] },
  { id: 113, front: "Cable insulation levels", back: "100%: grounded systems (fault cleared < 1 min). 133%: ungrounded or high-resistance grounded systems.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["Cable Construction"] },
  { id: 114, front: "GMD formula", back: "Deq = (D12 × D13 × D23)^(1/3) for non-equilateral spacing. Used for both L and C calculations.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Line Parameters"] },
  { id: 115, front: "ABCD identity", back: "AD - BC = 1 for any two-port network. Quick check for calculation errors.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["ABCD Parameters"] },
  { id: 116, front: "Low-resistance grounding", back: "100-1000 A limit. Must trip on first ground fault (can't continue operating). Common for 4.16-15 kV industrial.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["System Grounding"] },
  { id: 117, front: "Effectively grounded (IEEE)", back: "X0 ≤ X1 and R0 ≤ X1. Limits overvoltage to 1.38 pu on unfaulted phases during SLG fault.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'definition', topics: ["System Grounding"] },
  { id: 118, front: "Overhead line Zc", back: "Zc = √(L/C) ≈ 250-400 Ω. Higher voltage lines tend to have lower Zc and higher SIL.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Line Parameters"] },
  { id: 119, front: "Shunt reactor purpose", back: "Absorbs reactive power from line charging current. Prevents Ferranti effect. Used on long, lightly loaded lines.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["Reactive Compensation"] },
  { id: 120, front: "Medium line nominal π model", back: "A = D = 1 + YZ/2. B = Z. C = Y(1 + YZ/4). Z = series impedance, Y = shunt admittance. Valid 80-250 km.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Line Models"] },
  { id: 121, front: "XLPE cable", back: "Cross-Linked Polyethylene. Most common modern cable insulation. Max temp 90°C (normal), 250°C (short circuit).", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'definition', topics: ["Cable Insulation"] },
  { id: 122, front: "Cable ampacity derating factors", back: "Ambient temp > 20°C (earth), mutual heating, conduit fill, burial depth, soil thermal resistivity. Lower temp = higher ampacity.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'concept', topics: ["Cable Ampacity"] },
  { id: 123, front: "Bundled conductor GMR", back: "2-bundle: DSL = √(ds × d). 3-bundle: DSL = (ds × d²)^(1/3). 4-bundle: DSL = 1.09(ds × d³)^(1/4).", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'formula', topics: ["Bundled Conductors"] },
  { id: 124, front: "LDC (Line Drop Compensator)", back: "Simulates feeder impedance to regulate voltage at a remote point rather than at the regulator location.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'definition', topics: ["Voltage Regulation"] },
  { id: 125, front: "EXAM TIP: L uses GMR, C uses actual radius", back: "This is tested almost every exam. L calculation → use r' = 0.7788r (or tabulated GMR). C calculation → use actual conductor radius r.", domain: 'transmission', domainName: 'Transmission & Distribution', category: 'tip', topics: ["Line Parameters"] },

  // PROTECTION (25)
  { id: 126, front: "Device 50, 51, 87, 21", back: "50: instantaneous OC. 51: time OC. 87: differential. 21: distance. 67: directional OC. 27: undervoltage. 59: overvoltage.", domain: 'protection', domainName: 'Protection', category: 'definition', topics: ["Device Numbers"] },
  { id: 127, front: "CTI (Coordination Time Interval)", back: "0.3-0.4 seconds between adjacent relays. Accounts for relay overtravel, CT errors, breaker time, and safety margin.", domain: 'protection', domainName: 'Protection', category: 'definition', topics: ["Relay Coordination"] },
  { id: 128, front: "Phase OC pickup setting", back: "1.25-1.5 × maximum load current. Must be above normal load + cold load pickup to avoid nuisance trips.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Overcurrent Protection"] },
  { id: 129, front: "Ground OC pickup", back: "Set much lower than phase OC (0.2-0.5 × CT rating) since normal load has no ground current component.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Ground Protection"] },
  { id: 130, front: "Differential protection principle", back: "Iop = |I1 + I2| > slope × Ires + Ipickup. Normal: Iin = Iout, Iop ≈ 0. Internal fault: Iop is large.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Differential Protection"] },
  { id: 131, front: "2nd harmonic restraint", back: "Blocks diff relay operation during transformer inrush. Inrush has 60-70% 2nd harmonic content.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Transformer Differential"] },
  { id: 132, front: "5th harmonic restraint", back: "Blocks diff relay during overexcitation (overvoltage/underfrequency). Overexcitation produces significant 5th harmonic.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Transformer Differential"] },
  { id: 133, front: "Distance relay zones", back: "Z1: 80-85% line, instantaneous. Z2: 120-150% line, 0.3-0.5s delay. Z3: beyond next bus, 1-2s backup.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Distance Protection"] },
  { id: 134, front: "Mho relay characteristic", back: "Circle through origin, inherently directional. Most common distance relay type. Only operates for forward faults.", domain: 'protection', domainName: 'Protection', category: 'definition', topics: ["Distance Relays"] },
  { id: 135, front: "POTT vs DCB", back: "POTT: both ends must agree fault is forward (permissive). More secure, slightly slower. DCB: trips unless remote sends block. Faster, less secure.", domain: 'protection', domainName: 'Protection', category: 'comparison', topics: ["Pilot Protection"] },
  { id: 136, front: "3-phase fault current", back: "If = Vf/Z1. Only positive sequence involved. Balanced fault.", domain: 'protection', domainName: 'Protection', category: 'formula', topics: ["Fault Analysis"] },
  { id: 137, front: "SLG fault: most common", back: "~70% of all faults on overhead lines. If = 3Vf/(Z1+Z2+Z0). Can be largest if Z0 < Z1 (solidly grounded).", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Fault Types"] },
  { id: 138, front: "LL fault current", back: "If = √3 × Vf/(Z1+Z2). No zero sequence involved. Typically smallest of the four fault types.", domain: 'protection', domainName: 'Protection', category: 'formula', topics: ["Fault Types"] },
  { id: 139, front: "Recloser operation", back: "Fast trip → reclose → time-delay trip → reclose → lockout. 80% of overhead faults are temporary.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Reclosers"] },
  { id: 140, front: "Fuse coordination: TCC curves", back: "Upstream relay above fuse total clearing. Downstream relay below fuse minimum melt. Plot on log-log paper.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Coordination"] },
  { id: 141, front: "Inverse time curves (IEEE C37.112)", back: "Moderately inverse (general), Very inverse (high fault range), Extremely inverse (recloser coordination), Definite time (backup).", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Relay Curves"] },
  { id: 142, front: "X/R ratio and DC offset", back: "Higher X/R → more DC offset → higher asymmetrical fault current. Affects breaker interrupting capability.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Fault Analysis"] },
  { id: 143, front: "Fiber optic vs PLC for pilot protection", back: "Fiber: most reliable, not affected by power system faults. PLC: uses power line itself, susceptible to faults on protected line.", domain: 'protection', domainName: 'Protection', category: 'comparison', topics: ["Communication Channels"] },
  { id: 144, front: "Zone 1 set at 80-85% (not 100%)", back: "Prevents overreach into next line section due to CT/PT errors, line parameter uncertainties, and transient overreach.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Distance Protection"] },
  { id: 145, front: "Fuse-saving scheme", back: "Recloser fast curve operates before lateral fuse for temporary faults. If fault is permanent, time-delay trip lets fuse clear.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Recloser-Fuse Coordination"] },
  { id: 146, front: "Dual-slope differential", back: "Slope 1 (20-30%): low current region. Slope 2 (60-80%): high current (security against CT saturation during external faults).", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Differential Protection"] },
  { id: 147, front: "CT delta connection for transformer diff", back: "Historically, CTs on Y side were connected in delta to compensate for 30° phase shift. Modern digital relays handle this internally.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Transformer Differential"] },
  { id: 148, front: "Fault current ranking (solidly grounded)", back: "When Z0 < Z1: SLG > 3-phase > LLG > LL. When Z0 > Z1: 3-phase > SLG > LLG > LL.", domain: 'protection', domainName: 'Protection', category: 'concept', topics: ["Fault Analysis"] },
  { id: 149, front: "DTT (Direct Transfer Trip)", back: "One end directly trips remote breaker via communication channel. Used for transformer/bus protection where remote breaker must trip.", domain: 'protection', domainName: 'Protection', category: 'definition', topics: ["Pilot Protection"] },
  { id: 150, front: "EXAM TIP: Fault analysis sequence connections", back: "3-phase: Z1 only. SLG: all three in series (most tested!). LL: Z1+Z2 (no zero). LLG: Z1 + Z2||Z0. If = 3Ia0 for SLG.", domain: 'protection', domainName: 'Protection', category: 'tip', topics: ["Fault Analysis"] },

  // POWER QUALITY (15)
  { id: 151, front: "THD formula", back: "THD = √(ΣIh²)/I1 × 100%. TDD uses max demand current IL as base instead of I1.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'formula', topics: ["Harmonics"] },
  { id: 152, front: "IEEE 519 voltage THD limit", back: "5% at PCC for general systems. 8% for dedicated systems. Individual harmonic: 3%.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'concept', topics: ["IEEE 519"] },
  { id: 153, front: "K-factor", back: "K = Σ(Ih/I1)² × h². Standard: K-1. VFD loads: K-4 to K-13. Higher K = more harmonic heating tolerance.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'formula', topics: ["Transformers"] },
  { id: 154, front: "Voltage sag (IEEE 1159)", back: "0.1-0.9 pu RMS for 0.5 cycle to 1 minute. Most common PQ problem. Caused by faults on adjacent feeders.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'definition', topics: ["Voltage Sags"] },
  { id: 155, front: "PF correction sizing", back: "Qcap = P × (tan θ1 - tan θ2). θ1 = arccos(PF1), θ2 = arccos(PF2).", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'formula', topics: ["PF Correction"] },
  { id: 156, front: "Harmonic resonance frequency", back: "fr = f1 × √(MVAsc/MVARcap). If fr = dominant harmonic → dangerous amplification. Detune with 5-7% reactor.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'formula', topics: ["Resonance"] },
  { id: 157, front: "UPS types comparison", back: "Online: best protection, highest losses. Offline: cheapest, 2-4ms transfer. Line-interactive: middle ground with voltage regulation.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'comparison', topics: ["UPS"] },
  { id: 158, front: "ITIC curve", back: "Defines equipment voltage tolerance. Equipment should survive: 80% for 10s, 70% for 0.5s, 50% for ~1 cycle.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'concept', topics: ["Voltage Tolerance"] },
  { id: 159, front: "DVR (Dynamic Voltage Restorer)", back: "Series-connected device injecting voltage to compensate sags. Very fast (< 1 cycle). Sized for sag depth × duration.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'definition', topics: ["Sag Mitigation"] },
  { id: 160, front: "Active vs Passive harmonic filters", back: "Passive: tuned LC, fixed frequency, cheaper. Active: injects anti-harmonic current, adaptive, more expensive.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'comparison', topics: ["Harmonic Mitigation"] },
  { id: 161, front: "6-pulse characteristic harmonics", back: "h = 6k ± 1: 5,7,11,13,17,19... Individual magnitudes ≈ 1/h of fundamental.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'formula', topics: ["Harmonics"] },
  { id: 162, front: "IEEE 519 applies at", back: "Point of Common Coupling (PCC) — the boundary between utility and customer. NOT at individual equipment.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'concept', topics: ["IEEE 519"] },
  { id: 163, front: "Back-to-back capacitor switching", back: "High inrush current at high frequency between energized and switching banks. Requires pre-insertion resistors or synchronized switching.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'concept', topics: ["Capacitor Switching"] },
  { id: 164, front: "Passive filter tuning", back: "Tune slightly below target (e.g., 4.7th for 5th harmonic) to avoid parallel resonance with system impedance.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'concept', topics: ["Filter Design"] },
  { id: 165, front: "EXAM TIP: IEEE 519 TDD vs THD", back: "TDD uses maximum demand current (IL), not fundamental of distorted waveform. This prevents gaming by measuring during light load. Frequently tested distinction.", domain: 'power_quality', domainName: 'Power Quality & Reliability', category: 'tip', topics: ["IEEE 519"] },

  // CODES & STANDARDS (20)
  { id: 166, front: "NEC Article 430", back: "Motors: branch circuits, feeders, disconnects, controllers, overload, SCGF protection.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["NEC"] },
  { id: 167, front: "NEC Article 250", back: "Grounding and bonding: system grounding, EGC, grounding electrode system, bonding.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["NEC"] },
  { id: 168, front: "NEC Table 310.15(B)(16)", back: "Conductor ampacity table for raceways. Apply temperature and fill correction factors.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["NEC"] },
  { id: 169, front: "NEC 240.6(A) standard sizes", back: "15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 110, 125, 150, 175, 200, 225, 250, 300, 350, 400...", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["NEC"] },
  { id: 170, front: "EGC sizing", back: "Per NEC Table 250.122, based on overcurrent device rating (not conductor size or motor FLC).", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["NEC 250"] },
  { id: 171, front: "Ground rod requirements", back: "NEC 250.53(G): minimum 8 ft driven, 5/8\" diameter. If resistance > 25 Ω, add supplemental electrode.", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["NEC 250"] },
  { id: 172, front: "NEC vs NESC", back: "NEC (NFPA 70): premises wiring (building side). NESC (IEEE C2): utility supply and communication lines.", domain: 'codes', domainName: 'Codes & Standards', category: 'comparison', topics: ["Codes"] },
  { id: 173, front: "NESC loading districts", back: "Heavy: 1/2\" ice, 4 lb/ft², 0°F. Medium: 1/4\" ice, 4 lb/ft², 15°F. Light: 0 ice, 9 lb/ft², 30°F.", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["NESC"] },
  { id: 174, front: "NFPA 70E PPE categories", back: "Cat 1: 4-8 cal/cm². Cat 2: 8-25. Cat 3: 25-40. Cat 4: 40-100 cal/cm².", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["Arc Flash"] },
  { id: 175, front: "IEEE 1584", back: "Standard for arc flash incident energy calculations. Inputs: fault current, clearing time, working distance, equipment type, gap.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["Arc Flash"] },
  { id: 176, front: "Arc flash boundary", back: "Distance where incident energy = 1.2 cal/cm² (onset of 2nd-degree burn). Per NFPA 70E.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["Arc Flash"] },
  { id: 177, front: "IEEE Red Book (141/3001)", back: "Electric Power Distribution for Industrial Plants. The foundational reference for industrial power design.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["IEEE Standards"] },
  { id: 178, front: "IEEE Buff Book (242/3004)", back: "Protection and Coordination. The bible for protective device coordination studies.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["IEEE Standards"] },
  { id: 179, front: "IEEE Green Book (142/3003)", back: "Grounding of Industrial & Commercial Power Systems.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["IEEE Standards"] },
  { id: 180, front: "Incident energy reduction", back: "E ∝ I × t. Reduce fault current (current-limiting fuses, smaller transformers) or clearing time (faster relays) to lower arc flash energy.", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["Arc Flash"] },
  { id: 181, front: "NEC 430: motor feeder SCGF", back: "Largest motor branch-circuit SCGF device + sum of all other motor FLCs.", domain: 'codes', domainName: 'Codes & Standards', category: 'formula', topics: ["NEC 430"] },
  { id: 182, front: "NESC Grade B construction", back: "Highest grade. Required for crossings over railroads, limited-access highways, navigable waterways.", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["NESC"] },
  { id: 183, front: "IEEE C37.2", back: "Standard device function numbers for power switchgear. 50=instant OC, 51=time OC, 21=distance, 87=diff, etc.", domain: 'codes', domainName: 'Codes & Standards', category: 'definition', topics: ["IEEE Standards"] },
  { id: 184, front: "NEC 450: transformer protection", back: "Primary-only protection: 125% (next standard size up). Primary + secondary: 250% primary, 125% secondary.", domain: 'codes', domainName: 'Codes & Standards', category: 'concept', topics: ["NEC 450"] },
  { id: 185, front: "EXAM TIP: NEC table locations", back: "Motor FLC: 430.247-250. Conductor ampacity: 310.15(B)(16). Standard OC sizes: 240.6(A). EGC: 250.122. Motor SCGF: 430.52.", domain: 'codes', domainName: 'Codes & Standards', category: 'tip', topics: ["NEC Navigation"] },

  // POWER SYSTEM ANALYSIS (20)
  { id: 186, front: "Load flow bus types", back: "Slack: |V|, δ known. PV (generator): P, |V| known. PQ (load): P, Q known. One slack bus per study.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Load Flow"] },
  { id: 187, front: "Newton-Raphson load flow", back: "Most widely used. Quadratic convergence (3-5 iterations typical). Uses Jacobian matrix of power equations.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Load Flow"] },
  { id: 188, front: "Swing equation", back: "M(d²δ/dt²) = Pa = Pm - Pe. M = 2H/ωs. Rotor accelerates when Pm > Pe (during fault).", domain: 'power_system', domainName: 'Power System Analysis', category: 'formula', topics: ["Stability"] },
  { id: 189, front: "Equal-area criterion", back: "Stable if decelerating area A2 ≥ accelerating area A1 on P-δ curve. Critical clearing angle δcr: maximum angle for stability.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Transient Stability"] },
  { id: 190, front: "Steady-state stability limit", back: "δ < 90° (positive synchronizing power Ps = dP/dδ > 0). At δ = 90°: Ps = 0, stability limit.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Stability"] },
  { id: 191, front: "Generator reactances", back: "Xd\" (subtransient): 0.10-0.25 pu, first cycles. Xd' (transient): 0.15-0.35, seconds. Xd (synchronous): 1.0-2.0, steady state.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Short-Circuit"] },
  { id: 192, front: "First-cycle vs interrupting duty", back: "First-cycle (momentary): use Xd\", includes motor contribution. For bus bracing/fuse. Interrupting (3-8 cycles): use Xd', for breaker rating.", domain: 'power_system', domainName: 'Power System Analysis', category: 'comparison', topics: ["Short-Circuit Studies"] },
  { id: 193, front: "Motor fault contribution", back: "Large motors (>50 HP): 4-6× FLC. Small motors aggregate: 4× FLC. Decays in 1-3 cycles.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Short-Circuit"] },
  { id: 194, front: "Close-and-latch rating", back: "1.6 × symmetrical first-cycle RMS. Accounts for peak asymmetrical current including DC offset.", domain: 'power_system', domainName: 'Power System Analysis', category: 'formula', topics: ["Equipment Ratings"] },
  { id: 195, front: "Economic dispatch principle", back: "Set dCi/dPi = λ (equal incremental cost) for all online units. Subject to ΣPi = PD.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Economic Dispatch"] },
  { id: 196, front: "Incremental cost", back: "dC/dP = b + 2cP for cost function C = a + bP + cP². Units: $/MWh.", domain: 'power_system', domainName: 'Power System Analysis', category: 'formula', topics: ["Economic Dispatch"] },
  { id: 197, front: "Penalty factor", back: "PFi = 1/(1 - ∂PL/∂Pi). Accounts for transmission losses. Generators near loads have lower PF (loaded more).", domain: 'power_system', domainName: 'Power System Analysis', category: 'formula', topics: ["Dispatch with Losses"] },
  { id: 198, front: "DC load flow", back: "Linearized: P ≈ B'δ. Assumes |V| = 1.0 pu, neglects losses and Q. Fast for contingency screening.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Load Flow"] },
  { id: 199, front: "PV bus hits Q limit", back: "Becomes PQ bus with Q fixed at limit. Voltage no longer controlled (may deviate from set point).", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Load Flow"] },
  { id: 200, front: "Inertia constant H", back: "H = stored kinetic energy / rated MVA (MJ/MVA). Higher H = more time to clear faults = better transient stability.", domain: 'power_system', domainName: 'Power System Analysis', category: 'definition', topics: ["Stability"] },
  { id: 201, front: "IEEE C37.010 correction factor", back: "Required when system X/R exceeds breaker tested X/R. Multiplies interrupting duty to account for additional DC offset.", domain: 'power_system', domainName: 'Power System Analysis', category: 'concept', topics: ["Equipment Ratings"] },
  { id: 202, front: "PSS (Power System Stabilizer)", back: "Adds supplementary signal to AVR. Improves damping of 0.2-2 Hz electromechanical oscillations.", domain: 'power_system', domainName: 'Power System Analysis', category: 'definition', topics: ["Stability"] },
  { id: 203, front: "Unit commitment vs economic dispatch", back: "Unit commitment: which units to start/stop (includes start-up costs, min up/down time). Economic dispatch: how to load units already online.", domain: 'power_system', domainName: 'Power System Analysis', category: 'comparison', topics: ["Generation Planning"] },
  { id: 204, front: "Bus force from fault current", back: "F = μ₀I²L/(2πd). Use peak asymmetrical (first-cycle) current. Forces can be enormous — bus bracing critical.", domain: 'power_system', domainName: 'Power System Analysis', category: 'formula', topics: ["Equipment Ratings"] },
  { id: 205, front: "EXAM TIP: Short-circuit studies", back: "Don't forget motor contribution! First-cycle uses Xd\" for generators AND includes motors. Interrupting uses Xd'. Know close-and-latch = 1.6× symmetrical.", domain: 'power_system', domainName: 'Power System Analysis', category: 'tip', topics: ["Short-Circuit"] },

  // KEY FORMULAS (15)
  { id: 206, front: "Per-unit base change", back: "Zpu,new = Zpu,old × (Snew/Sold) × (Vold/Vnew)²", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Per-Unit"] },
  { id: 207, front: "Three-phase power", back: "P = √3 × VLL × IL × cos(θ). S = √3 × VLL × IL. Q = √3 × VLL × IL × sin(θ).", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Power"] },
  { id: 208, front: "Synchronous speed", back: "ns = 120f/p (RPM). f = frequency (Hz), p = number of poles.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Machines"] },
  { id: 209, front: "Slip", back: "s = (ns - nr)/ns. Rotor copper loss = s × Pag. Pmech = (1-s) × Pag.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Induction Motor"] },
  { id: 210, front: "Transformer regulation", back: "%VR = (VNL - VFL)/VFL × 100%. ≈ εR cos(θ) + εX sin(θ).", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Transformers"] },
  { id: 211, front: "SIL", back: "SIL = V²/Zc. Zc = √(L/C). At SIL: flat voltage profile, no net VAR flow.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Transmission"] },
  { id: 212, front: "SLG fault current", back: "If = 3Vf/(Z1+Z2+Z0+3Zf). All three sequence networks in series.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Fault Analysis"] },
  { id: 213, front: "PF correction kVAR", back: "Qcap = P(tan θ1 - tan θ2). θ = arccos(PF).", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Power Factor"] },
  { id: 214, front: "Availability", back: "A = MTBF/(MTBF+MTTR). Series: multiply. Parallel: A = 1-(1-A1)(1-A2).", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Reliability"] },
  { id: 215, front: "SAIDI", back: "SAIDI = Σ(ri×Ni)/NT. Duration index. Hours per customer per year.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Reliability"] },
  { id: 216, front: "Harmonic resonance", back: "fr = f1 × √(MVAsc/MVARcap). Avoid tuning to dominant harmonics.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Harmonics"] },
  { id: 217, front: "Economic dispatch", back: "dCi/dPi = λ (equal incremental cost). With losses: (dCi/dPi)/(1-∂PL/∂Pi) = λ.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Dispatch"] },
  { id: 218, front: "Power-angle equation", back: "P = (Ef×Vt/Xs)sin(δ). Pmax at δ=90°.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Synchronous Machine"] },
  { id: 219, front: "Close-and-latch rating", back: "1.6 × symmetrical first-cycle RMS fault current.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Equipment Ratings"] },
  { id: 220, front: "Voltage rise from capacitor", back: "ΔV ≈ QX/V. Q = cap MVAR, X = source reactance, V = system voltage.", domain: 'formulas', domainName: 'Key Formulas & Reference', category: 'formula', topics: ["Capacitor Banks"] },

  // EXAM STRATEGY (10)
  { id: 221, front: "EXAM TIP: Time management", back: "80 questions in 8 hours = 6 minutes per question. Flag difficult ones and come back. Spend more time on Protection and Machines (24% of exam).", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Time Management"] },
  { id: 222, front: "EXAM TIP: Reference book tabs", back: "Tab your NEC (Art 250, 310, 430, 450), NESC clearance tables, IEEE color book formulas, and per-unit conversion page.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Preparation"] },
  { id: 223, front: "EXAM TIP: Calculator proficiency", back: "Master complex number mode on your approved calculator. Practice phasor addition/subtraction and rectangular↔polar conversion.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Calculator"] },
  { id: 224, front: "EXAM TIP: Per-unit system", back: "At least 3-5 questions require per-unit. Write the base change formula on scratch paper immediately. Know Zbase = V²/S.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Strategy"] },
  { id: 225, front: "EXAM TIP: NEC table lookup", back: "Practice finding values in NEC tables quickly. Motor FLC, conductor ampacity, and standard OC sizes are the most common lookups.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["NEC Navigation"] },
  { id: 226, front: "EXAM TIP: Symmetrical components", back: "This is the highest-yield topic. Know the three fault types' sequence connections cold. SLG = series is the most tested.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["High-Yield Topics"] },
  { id: 227, front: "EXAM TIP: Common traps", back: "√3 factor errors (Y vs Δ), using nameplate instead of NEC table FLC, forgetting motor contribution to faults, sign of Q (lagging vs leading).", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Common Mistakes"] },
  { id: 228, front: "EXAM TIP: Process of elimination", back: "Even if you can't solve exactly, eliminate obviously wrong answers. Per-unit values should be 0.01-10 range. Fault currents in kA, not A.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Test Strategy"] },
  { id: 229, front: "EXAM TIP: Write formulas on scratch paper", back: "At start: per-unit base change, 3-phase power, SLG/LL/LLG fault formulas, PF correction, SAIDI/SAIFI. Reference all exam.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Preparation"] },
  { id: 230, front: "EXAM TIP: PE exam is open book", back: "Bring organized references. You can't memorize everything — know WHERE to find it. Practice looking up NEC articles, IEEE standards, and formulas quickly.", domain: 'exam', domainName: 'Exam Strategy', category: 'tip', topics: ["Preparation"] },
];

export function getPEEEFlashcards(domain?: string): PEEEFlashcard[] {
  if (!domain) return PEEE_FLASHCARDS;
  return PEEE_FLASHCARDS.filter(c => c.domain === domain);
}

export function getPEEEFlashcardsByCategory(category: string): PEEEFlashcard[] {
  return PEEE_FLASHCARDS.filter(c => c.category === category);
}

export const PEEE_FLASHCARD_COUNT = 230;
