export interface SATFlashcard {
  id: number;
  front: string;
  back: string;
  domain: string;      // one of the domain ids below
  domainName: string;
  category: string;    // 'definition' | 'concept' | 'formula' | 'strategy' | 'grammar' | 'vocabulary'
  topics: string[];    // ['SAT']
}

export const SAT_FLASHCARD_DOMAINS = [
  { id: 'reading_writing', label: 'R&W',      name: 'Reading and Writing', count: 30 },
  { id: 'math',            label: 'Math',     name: 'Math',                count: 40 },
  { id: 'strategy',        label: 'Strategy', name: 'Test Strategy',       count: 10 },
];

export const SAT_FLASHCARDS: SATFlashcard[] = [
  // ---------------------------------------------------------------------------
  // MATH (40)
  // ---------------------------------------------------------------------------
  {
    id: 1,
    front: 'Slope of a line through two points',
    back: 'Slope m = (y2 - y1) / (x2 - x1), the change in y divided by the change in x (rise over run). A positive slope rises left to right; a negative slope falls. A horizontal line has slope 0; a vertical line has an undefined slope.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 2,
    front: 'Slope-intercept form of a line',
    back: 'y = mx + b, where m is the slope and b is the y-intercept (the value of y when x = 0). This form makes it easy to graph a line and to read off its rate of change directly.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 3,
    front: 'Point-slope form of a line',
    back: 'y - y1 = m(x - x1), where m is the slope and (x1, y1) is a known point on the line. Use this when you have one point and the slope and need the equation.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 4,
    front: 'Standard form of a line',
    back: 'Ax + By = C, with A, B, and C constants. The slope is -A/B, the x-intercept is C/A, and the y-intercept is C/B. Standard form is handy for finding intercepts quickly.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 5,
    front: 'Parallel vs. perpendicular slopes',
    back: 'Parallel lines have equal slopes (m1 = m2). Perpendicular lines have slopes that are negative reciprocals (m1 times m2 = -1), so if one slope is 3, the perpendicular slope is -1/3.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 6,
    front: 'Standard (general) form of a quadratic',
    back: 'y = ax^2 + bx + c. The constant c is the y-intercept. The parabola opens up when a > 0 and down when a < 0. The axis of symmetry is x = -b / (2a).',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 7,
    front: 'Vertex form of a quadratic',
    back: 'y = a(x - h)^2 + k, where the vertex is the point (h, k) and x = h is the axis of symmetry. If a > 0 the vertex is a minimum; if a < 0 it is a maximum.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 8,
    front: 'Factored (intercept) form of a quadratic',
    back: 'y = a(x - p)(x - q), where p and q are the x-intercepts (roots/zeros) of the parabola. The axis of symmetry lies halfway between them at x = (p + q) / 2.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 9,
    front: 'The quadratic formula',
    back: 'For ax^2 + bx + c = 0, the solutions are x = (-b plus or minus the square root of (b^2 - 4ac)) / (2a). It solves any quadratic, even ones that do not factor nicely.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 10,
    front: 'The discriminant and number of real solutions',
    back: 'The discriminant is b^2 - 4ac. If it is positive there are two distinct real solutions; if it equals 0 there is exactly one real solution (a repeated root); if it is negative there are no real solutions.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 11,
    front: 'Vertex x-coordinate from standard form',
    back: 'For y = ax^2 + bx + c, the vertex occurs at x = -b / (2a). Substitute that x back into the equation to get the vertex y-coordinate (the maximum or minimum value).',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 12,
    front: 'Product-rule for exponents',
    back: 'When multiplying powers with the same base, add the exponents: x^a times x^b = x^(a+b). For example, x^3 times x^5 = x^8.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 13,
    front: 'Quotient rule for exponents',
    back: 'When dividing powers with the same base, subtract the exponents: x^a / x^b = x^(a-b). For example, x^7 / x^2 = x^5.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 14,
    front: 'Power-of-a-power rule',
    back: 'Raising a power to another power multiplies the exponents: (x^a)^b = x^(a times b). For example, (x^2)^3 = x^6.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 15,
    front: 'Zero and negative exponents',
    back: 'Any nonzero base to the 0 power equals 1: x^0 = 1. A negative exponent means reciprocal: x^(-n) = 1 / x^n. For example, 2^(-3) = 1/8.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 16,
    front: 'Fractional exponents as radicals',
    back: 'A fractional exponent is a root: x^(1/n) equals the nth root of x, and x^(m/n) equals the nth root of x^m. For example, x^(1/2) is the square root of x and 8^(2/3) = 4.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 17,
    front: 'Simplifying radicals',
    back: 'Factor out perfect squares from under the radical: the square root of (a times b) = (square root of a) times (square root of b). For example, the square root of 50 = the square root of (25 times 2) = 5 times the square root of 2.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 18,
    front: 'Percent of a number',
    back: 'To find P percent of N, multiply: (P/100) times N. For example, 20 percent of 150 = 0.20 times 150 = 30. The word "of" signals multiplication.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 19,
    front: 'Percent change formula',
    back: 'Percent change = ((new value - old value) / old value) times 100. A positive result is a percent increase; a negative result is a percent decrease. Always divide by the original value.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 20,
    front: 'Percent increase / decrease as a multiplier',
    back: 'Increasing by p percent multiplies by (1 + p/100); decreasing by p percent multiplies by (1 - p/100). A 15 percent increase means times 1.15; a 15 percent decrease means times 0.85.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 21,
    front: 'Exponential growth and decay model',
    back: 'y = a times (1 + r)^t models growth and y = a times (1 - r)^t models decay, where a is the initial amount, r is the rate (as a decimal), and t is time. The base above 1 grows; below 1 decays.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 22,
    front: 'Area and circumference of a circle',
    back: 'Area = pi times r^2 and circumference = 2 times pi times r (or pi times d, the diameter). The radius r is the distance from the center to the edge.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 23,
    front: 'Equation of a circle',
    back: '(x - h)^2 + (y - k)^2 = r^2, where (h, k) is the center and r is the radius. Completing the square converts a general second-degree equation into this standard circle form.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 24,
    front: 'Area of common shapes',
    back: 'Rectangle: length times width. Triangle: (1/2) times base times height. Parallelogram: base times height. Trapezoid: (1/2) times (base1 + base2) times height.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 25,
    front: 'Volume of common solids',
    back: 'Rectangular box: length times width times height. Cylinder: pi times r^2 times h. Sphere: (4/3) times pi times r^3. Cone: (1/3) times pi times r^2 times h. These appear on the reference sheet.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 26,
    front: 'The Pythagorean theorem',
    back: 'For a right triangle with legs a and b and hypotenuse c, a^2 + b^2 = c^2. The hypotenuse c is the longest side, opposite the right angle.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 27,
    front: 'Common Pythagorean triples',
    back: 'Whole-number right-triangle sides include 3-4-5, 5-12-13, 8-15-17, and 7-24-25, plus any multiple (like 6-8-10). Recognizing these saves time versus computing square roots.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 28,
    front: 'Special right triangles',
    back: 'A 45-45-90 triangle has sides in ratio 1 : 1 : the square root of 2. A 30-60-90 triangle has sides in ratio 1 : the square root of 3 : 2, with the shortest side opposite the 30-degree angle.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 29,
    front: 'The distance formula',
    back: 'The distance between (x1, y1) and (x2, y2) is the square root of ((x2 - x1)^2 + (y2 - y1)^2). It is simply the Pythagorean theorem applied to the coordinate plane.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 30,
    front: 'The midpoint formula',
    back: 'The midpoint of the segment from (x1, y1) to (x2, y2) is ((x1 + x2) / 2, (y1 + y2) / 2). Average the x-coordinates and average the y-coordinates.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 31,
    front: 'Mean (arithmetic average)',
    back: 'Mean = (sum of all values) / (number of values). To find a missing value given a target mean, multiply the mean by the count to get the required total, then subtract the known values.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 32,
    front: 'Median vs. mode',
    back: 'The median is the middle value when data are ordered (average the two middle values if the count is even). The mode is the value that appears most often. The median resists being pulled by outliers.',
    domain: 'math',
    domainName: 'Math',
    category: 'definition',
    topics: ['SAT'],
  },
  {
    id: 33,
    front: 'Effect of an outlier on mean and median',
    back: 'Adding a very large or very small outlier shifts the mean noticeably toward that value but changes the median only slightly, if at all. The median is the more robust measure of center for skewed data.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 34,
    front: 'Basic probability',
    back: 'Probability = (number of favorable outcomes) / (total number of equally likely outcomes). Every probability is between 0 (impossible) and 1 (certain). The complement rule: P(not A) = 1 - P(A).',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },
  {
    id: 35,
    front: 'Reading a two-way frequency table',
    back: 'Conditional probability restricts the total to one row or column: P(A given B) uses only the count in the B group as the denominator. Read carefully which subgroup the question limits you to.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 36,
    front: 'Solving a system by substitution',
    back: 'Solve one equation for a variable, then substitute that expression into the other equation to get a single-variable equation. Solve it, then back-substitute to find the second variable.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 37,
    front: 'Solving a system by elimination',
    back: 'Scale the equations so one variable has opposite coefficients, then add the equations to eliminate that variable. Solve the result, then substitute back to find the other variable.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 38,
    front: 'Number of solutions to a linear system',
    back: 'Different slopes give exactly one solution (lines cross). Equal slopes but different intercepts give no solution (parallel lines). Identical lines (same slope and intercept) give infinitely many solutions.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 39,
    front: 'Direct vs. inverse variation',
    back: 'Direct variation: y = kx, so y is proportional to x and their ratio is constant. Inverse variation: y = k/x, so their product xy is constant and y decreases as x increases.',
    domain: 'math',
    domainName: 'Math',
    category: 'concept',
    topics: ['SAT'],
  },
  {
    id: 40,
    front: 'Sum and product of the roots of a quadratic',
    back: 'For ax^2 + bx + c = 0, the sum of the roots is -b/a and the product of the roots is c/a. This lets you check solutions or find a missing root quickly.',
    domain: 'math',
    domainName: 'Math',
    category: 'formula',
    topics: ['SAT'],
  },

  // ---------------------------------------------------------------------------
  // READING AND WRITING (30)
  // ---------------------------------------------------------------------------
  {
    id: 41,
    front: 'Subject-verb agreement',
    back: 'A verb must match its subject in number: singular subjects take singular verbs, plural subjects take plural verbs. Ignore words between the subject and verb, such as prepositional phrases, when checking agreement.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 42,
    front: 'Agreement with tricky subjects',
    back: 'Collective nouns (team, group) usually take singular verbs. "Each," "every," "either," "neither," and "everyone" are singular. Compound subjects joined by "and" are plural; with "or"/"nor" the verb agrees with the nearer subject.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 43,
    front: 'Comma with a coordinating conjunction (FANBOYS)',
    back: 'Use a comma before a FANBOYS conjunction (for, and, nor, but, or, yet, so) that joins two independent clauses. Do not add a comma if what follows the conjunction cannot stand alone as a sentence.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 44,
    front: 'The semicolon',
    back: 'A semicolon joins two closely related independent clauses without a conjunction, acting like a soft period. Each side must be a complete sentence. It also separates list items that already contain commas.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 45,
    front: 'The colon',
    back: 'A colon introduces a list, explanation, or example, and the words before the colon must form a complete sentence. It signals "here is what I mean." Do not place a colon directly after a verb or preposition.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 46,
    front: 'The em dash',
    back: 'An em dash sets off a break in thought or a parenthetical element and can replace commas, parentheses, or a colon. When a dash opens a nonessential insertion, a matching dash (not a comma) must close it.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 47,
    front: 'Commas around nonessential elements',
    back: 'Surround a nonessential (nonrestrictive) phrase or clause with a pair of commas; the sentence still makes sense if you remove it. Essential (restrictive) information that identifies the noun takes no commas.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 48,
    front: 'Do not separate subject from verb with a comma',
    back: 'A single comma should never split a subject from its verb or a verb from its object. For example, "The scientist who won the award, published a paper" is wrong; drop the comma.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 49,
    front: 'Fixing comma splices and run-ons',
    back: 'Two independent clauses cannot be joined by only a comma (a comma splice). Fix it with a period, a semicolon, a comma plus a FANBOYS conjunction, or by making one clause dependent with a subordinator.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 50,
    front: 'Independent vs. dependent clauses',
    back: 'An independent clause has a subject and verb and can stand alone as a sentence. A dependent (subordinate) clause begins with a word like because, although, or since and cannot stand alone.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'definition',
    topics: ['SAT'],
  },
  {
    id: 51,
    front: 'Pronoun-antecedent agreement',
    back: 'A pronoun must match its antecedent in number and person. A singular noun needs a singular pronoun (it, his, her); a plural noun needs a plural pronoun (they, their). Watch for vague or ambiguous references.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 52,
    front: 'Pronoun case: who vs. whom',
    back: 'Use "who" for the subject of a verb (who is calling) and "whom" for the object of a verb or preposition (to whom it may concern). Substitute he/him: if "he" fits use who, if "him" fits use whom.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 53,
    front: 'Its vs. it is and their/there/they are',
    back: '"Its" is possessive; "it is" is the contraction of it is. "Their" is possessive, "there" refers to place, and "they are" is the contraction of they are. The apostrophe versions always expand to two words.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 54,
    front: 'Apostrophes for possession',
    back: 'Singular possessive adds apostrophe + s (the dog is bowl). Plural nouns ending in s add just an apostrophe (the dogs is bowls). Plurals of ordinary nouns take no apostrophe at all.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 55,
    front: 'Dangling and misplaced modifiers',
    back: 'A modifying phrase must clearly attach to the noun it describes, which should immediately follow it. In "Running late, the bus was missed," the phrase wrongly modifies the bus; the person running late must appear right after the comma.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 56,
    front: 'Parallel structure',
    back: 'Items in a list or a comparison must share the same grammatical form: "hiking, swimming, and biking," not "hiking, swimming, and to bike." Keep verbs, nouns, or phrases consistent throughout the series.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 57,
    front: 'Verb tense consistency',
    back: 'Keep tense consistent within a passage unless the meaning requires a shift in time. Look at surrounding sentences to match the established tense, and use context clues about sequence to choose past, present, or future.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 58,
    front: 'Transitions of contrast',
    back: 'Words like however, nevertheless, in contrast, on the other hand, and yet signal that the next idea opposes the previous one. Choose a contrast transition only when the two sentences genuinely conflict.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 59,
    front: 'Transitions of addition and cause-effect',
    back: 'Addition transitions (furthermore, moreover, in addition) add supporting information. Cause-effect transitions (therefore, thus, consequently, as a result) show that one idea produces another. Match the logical relationship, not just the tone.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 60,
    front: 'Strategy for transition questions',
    back: 'Cover the answer choices and read the two sentences to decide the relationship (contrast, cause-effect, addition, example, sequence). Then pick the transition that fits that relationship rather than the one that merely sounds sophisticated.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 61,
    front: 'Command of Evidence: textual questions',
    back: 'These ask which quotation or detail best supports a given claim, conclusion, or hypothesis. Pinpoint exactly what the claim states, then choose the option that directly backs it up rather than one that is merely on-topic.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 62,
    front: 'Command of Evidence: quantitative questions',
    back: 'A graph or table accompanies the passage, and you must select the data point that supports or completes an argument. Read the axis labels and units carefully, and make sure your choice matches both the data and the passage claim.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 63,
    front: 'Words in Context strategy',
    back: 'Predict your own word that fits the blank before reading the choices, using the sentence and surrounding tone as clues. Then match your prediction to the closest answer, and plug the word back in to confirm it fits logically.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 64,
    front: 'Main idea and central claim questions',
    back: 'The main idea is the overall point that the whole text supports, not a single detail. Distinguish it from too-narrow choices (one detail) and too-broad choices (beyond the passage scope). The best answer summarizes the passage as a whole.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 65,
    front: 'Text structure and purpose questions',
    back: 'These ask what a sentence or paragraph does (introduces a problem, provides an example, counters a view). Focus on the function of the text within the argument, not just its literal content.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 66,
    front: 'Cross-text connections questions',
    back: 'Two short passages present related views, and you must compare or contrast the authors positions. Identify each author main stance first, then determine how the second text would respond to or agree with the first.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 67,
    front: 'Rhetorical Synthesis (notes) questions',
    back: 'You are given bullet-point notes and a stated goal, and you must combine the relevant facts into one sentence that meets the goal. Focus only on the details that serve the specified purpose and ignore the rest.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 68,
    front: 'Sentence fragments',
    back: 'A fragment lacks a subject, a complete verb, or a finished thought, so it cannot stand alone. Watch for dependent clauses or -ing phrases posing as sentences; connect them to an independent clause to fix the error.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 69,
    front: 'Comparisons: fewer vs. less, number vs. amount',
    back: 'Use "fewer" and "number" for countable items (fewer books) and "less" and "amount" for uncountable quantities (less water). Comparisons must also be logical: compare a city population to another city population, not to the city itself.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'grammar',
    topics: ['SAT'],
  },
  {
    id: 70,
    front: 'The "no comma needed" principle',
    back: 'When in doubt, prefer fewer commas: the digital SAT rarely rewards extra punctuation. Do not use a comma before a restrictive clause, between two items joined by "and," or anywhere a clear grammatical rule does not call for one.',
    domain: 'reading_writing',
    domainName: 'Reading and Writing',
    category: 'strategy',
    topics: ['SAT'],
  },

  // ---------------------------------------------------------------------------
  // TEST STRATEGY (10)
  // ---------------------------------------------------------------------------
  {
    id: 71,
    front: 'Digital SAT overall structure',
    back: 'The test has two sections: Reading and Writing, then Math. Each section is split into two equal modules. The whole exam runs about 2 hours and 14 minutes and is taken on the Bluebook application.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 72,
    front: 'Multistage adaptive testing',
    back: 'The test adapts between modules, not within them. Your performance on the first module of a section determines whether the second module is easier or harder, and that in turn affects your scoring range. Module 1 matters a lot.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 73,
    front: 'Timing: Reading and Writing',
    back: 'Each Reading and Writing module has 27 questions in 32 minutes, roughly 71 seconds per question. Questions are short and passage-based with one question each, so keep a steady pace and do not linger on any single item.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 74,
    front: 'Timing: Math',
    back: 'Each Math module has 22 questions in 35 minutes, about 95 seconds per question. Roughly a quarter are student-produced response (grid-in) questions; the rest are multiple choice. Budget extra time for the harder final questions.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 75,
    front: 'No penalty for guessing',
    back: 'The digital SAT has no wrong-answer penalty, so never leave a question blank. Always eliminate what you can and pick a letter for anything you cannot solve, ideally before the module runs out of time.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 76,
    front: 'Built-in Desmos calculator',
    back: 'An embedded Desmos graphing calculator is available for the entire Math section (and you may bring your own approved one). Use it to graph equations, find intersections, and locate zeros instead of solving everything by hand.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 77,
    front: 'Desmos tips for solving fast',
    back: 'Graph both sides of an equation and read intersection points to solve; type a system as two equations to see where they cross; use sliders or tables to test values. Graphing often beats algebra for finding roots and solutions.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 78,
    front: 'Mark for review and flagging',
    back: 'Bluebook lets you flag questions and return to them within the same module using the question navigator. Answer easy questions first, flag the tough ones, and circle back so you never run out of time on solvable items.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 79,
    front: 'Grid-in (student-produced response) rules',
    back: 'For math grid-ins, you type your own answer with up to five characters. Fractions and decimals are both accepted, negative answers are allowed, and you should not round unless the value is a long decimal (then give at least three digits).',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
  {
    id: 80,
    front: 'Scoring and score range',
    back: 'The SAT is scored from 400 to 1600, combining a Reading and Writing score and a Math score of 200 to 800 each. Because of adaptivity, the second module you receive caps or raises your possible score, so treat every question as counting.',
    domain: 'strategy',
    domainName: 'Test Strategy',
    category: 'strategy',
    topics: ['SAT'],
  },
];

export function getSATFlashcards(domain?: string): SATFlashcard[] {
  if (!domain) return SAT_FLASHCARDS;
  return SAT_FLASHCARDS.filter(c => c.domain === domain);
}
export const SAT_FLASHCARD_COUNT = SAT_FLASHCARDS.length;
