/**
 * CompTIA Security+ (SY0-701) Flashcard deck.
 * Cards across all 5 domains covering key concepts, definitions, exam tips, and comparisons.
 */

export interface SecurityPlusFlashcard {
  id: number;
  front: string;
  back: string;
  domain: string;
  domainName: string;
  category: string;
  topics: string[];
}

export const SECPLUS_FLASHCARD_DOMAINS = [
  { id: 'domain1', label: 'D1', name: 'Threats, Vulnerabilities & Attacks', count: 180 },
  { id: 'domain2', label: 'D2', name: 'Security Architecture', count: 120 },
  { id: 'domain3', label: 'D3', name: 'Security Implementation', count: 200 },
  { id: 'domain4', label: 'D4', name: 'Security Operations', count: 130 },
  { id: 'domain5', label: 'D5', name: 'Security Program Management & Oversight', count: 90 },
  { id: 'exam', label: 'Exam Prep', name: 'Exam Strategy & Tips', count: 30 },
] as const;

export const SECPLUS_FLASHCARD_CATEGORIES = ["comparison", "concept", "definition", "question", "tip"] as const;

export const SECPLUS_FLASHCARDS: SecurityPlusFlashcard[] = [

// ═══════════════════════════════════════════════════════════════
// DOMAIN 1 — Threats, Vulnerabilities & Attacks (24%)
// ═══════════════════════════════════════════════════════════════

// --- Malware Types ---
{ id: 1, front: `What is a virus?`, back: `Malicious code that attaches to a legitimate program and requires user action to spread. Cannot self-replicate across networks without a host file.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 2, front: `What is a worm?`, back: `Self-replicating malware that spreads across networks WITHOUT user interaction by exploiting vulnerabilities. Consumes bandwidth and resources. Example: WannaCry.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 3, front: `What is a Trojan?`, back: `Malware disguised as legitimate software. Does NOT self-replicate. Relies on social engineering for distribution. Types include RATs, banking trojans, and droppers.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 4, front: `What is ransomware?`, back: `Malware that encrypts victim files or locks system access, demanding payment for the decryption key. Modern variants use double extortion (encrypt + threaten to publish stolen data).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 5, front: `What is a rootkit?`, back: `Malware that operates at the deepest OS levels to hide its presence. Types: kernel-level (modifies OS kernel), bootkit (replaces bootloader), firmware (survives OS reinstall). Very difficult to detect.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 6, front: `What is fileless malware?`, back: `Malware that operates entirely in memory without writing to disk. Uses legitimate tools like PowerShell and WMI (living-off-the-land). Evades traditional file-based antivirus.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 7, front: `Virus vs. Worm vs. Trojan`, back: `Virus: needs host file + user action to spread. Worm: self-replicates over networks, no user action needed. Trojan: disguised as legit software, no self-replication, relies on social engineering.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Malware Types'] },
{ id: 8, front: `Polymorphic vs. Metamorphic malware`, back: `Polymorphic: changes its code SIGNATURE each replication (mutation engine) but core functionality stays the same. Metamorphic: completely REWRITES its entire code each infection. Both evade signature-based detection.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Malware Types'] },
{ id: 9, front: `What is double extortion ransomware?`, back: `Attacker exfiltrates data BEFORE encrypting it, then threatens to publish stolen data if ransom isn't paid. This defeats "restore from backup" defense because data is still at risk of exposure.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Malware Types'] },
{ id: 10, front: `What is Ransomware-as-a-Service (RaaS)?`, back: `Criminal business model where ransomware operators provide tools to affiliates who carry out attacks, splitting ransom payments. Lowers the barrier to entry for cybercrime.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Malware Types'] },
{ id: 11, front: `What is a logic bomb?`, back: `Malicious code that triggers when specific conditions are met (date, event, user action). Often planted by disgruntled insiders. Dormant until conditions are satisfied.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 12, front: `What is a keylogger?`, back: `Records keystrokes to capture passwords, credit card numbers, and other sensitive input. Can be software-based or a physical hardware device inserted between keyboard and computer.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 13, front: `What is a RAT (Remote Access Trojan)?`, back: `A Trojan that provides attackers with remote control of the victim's system. Capabilities include keylogging, screen capture, file transfer, webcam access, and command execution. Examples: DarkComet, njRAT.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 14, front: `What is spyware?`, back: `Software that monitors user activity (keystrokes, browsing, screenshots) and exfiltrates data to attackers. Often bundled with free software installations.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },
{ id: 15, front: `What is a cryptominer?`, back: `Malware that hijacks system CPU/GPU resources to mine cryptocurrency. Degrades performance and increases energy costs. Often delivered via drive-by downloads or malicious scripts.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Malware Types'] },

// --- Malware Indicators ---
{ id: 16, front: `What is C2 beaconing?`, back: `Regular, periodic outbound connections from a compromised system to a command-and-control server. A key network indicator of compromise. Look for consistent-interval connections to unknown IPs.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Malware Indicators'] },
{ id: 17, front: `Host-based vs. Network-based indicators of compromise`, back: `Host-based: unusual processes, file changes, registry modifications, disabled security tools, new scheduled tasks. Network-based: beaconing, DNS anomalies, unusual outbound traffic, port scanning, protocol anomalies.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Malware Indicators'] },
{ id: 18, front: `What does DNS tunneling indicate?`, back: `Data exfiltration or C2 communication hidden within DNS queries. Indicators: unusually long DNS queries, high volume of DNS traffic, queries to newly registered domains. Effective because DNS is rarely blocked.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Malware Indicators'] },
{ id: 19, front: `What is lateral movement?`, back: `After initial compromise, the attacker moves through the network to other systems using captured credentials or exploits. Indicator: one system connecting to many others using admin tools or protocols.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Malware Indicators'] },
{ id: 20, front: `EXAM TIP: Malware identification`, back: `If you see "regular periodic outbound connections to unknown IP" → C2 beaconing. "Self-replicating across network" → worm. "Operates in memory using PowerShell" → fileless malware. "Hides at kernel level" → rootkit. "Encrypts files + threatens data leak" → double extortion ransomware.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'tip', topics: ['Malware Types'] },

// --- Social Engineering ---
{ id: 21, front: `What is phishing?`, back: `Fraudulent email that appears from a trusted source to trick victims into revealing credentials, clicking malicious links, or downloading malware. The most common social engineering attack.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Social Engineering'] },
{ id: 22, front: `Phishing vs. Spear phishing vs. Whaling`, back: `Phishing: generic mass emails. Spear phishing: targeted at specific individuals using personal details. Whaling: spear phishing targeting senior executives (CEO, CFO). Each level increases targeting specificity.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Social Engineering'] },
{ id: 23, front: `Phishing vs. Vishing vs. Smishing`, back: `Phishing: email-based. Vishing: voice/phone-based (voice phishing). Smishing: SMS/text-based. All use social engineering but through different delivery channels.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Social Engineering'] },
{ id: 24, front: `What is Business Email Compromise (BEC)?`, back: `Attacker compromises or spoofs a legitimate business email to send fraudulent requests (wire transfers, payment changes). #1 cybercrime by financial loss according to FBI. No malware needed.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Social Engineering'] },
{ id: 25, front: `What is pretexting?`, back: `Creating a fabricated scenario (pretext) to extract information. Attacker assumes a false identity and builds a believable backstory. Example: posing as IT help desk to get passwords.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Social Engineering'] },
{ id: 26, front: `What is a watering hole attack?`, back: `Compromising a website frequently visited by the target group instead of attacking them directly. Exploits trust in third-party sites. Bypasses email filters because victims visit a site they already trust.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Social Engineering'] },
{ id: 27, front: `What is tailgating vs. piggybacking?`, back: `Both involve following an authorized person through a secured door. Tailgating: WITHOUT the person's knowledge. Piggybacking: WITH their consent (e.g., holding the door open).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Social Engineering'] },
{ id: 28, front: `What is baiting?`, back: `Leaving infected USB drives or media in locations where targets will find them (parking lots, lobbies). Exploits human curiosity — victims plug them into their computers.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Social Engineering'] },
{ id: 29, front: `What is typosquatting?`, back: `Registering domain names similar to legitimate ones (e.g., gogle.com) to capture users who mistype URLs. Often combined with credential harvesting pages that look identical to the real site.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Social Engineering'] },
{ id: 30, front: `Best defense against social engineering?`, back: `Security awareness training with phishing simulations. Measure effectiveness by BEHAVIOR CHANGE (reduction in click rates), not just training completion. Technical controls (MFA, email filtering) are important layers.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Social Engineering'] },
{ id: 31, front: `What are SPF, DKIM, and DMARC?`, back: `SPF: verifies sending server is authorized for the domain. DKIM: adds digital signature to emails. DMARC: policy framework that uses SPF + DKIM to prevent email spoofing. Together they defend against phishing.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Social Engineering'] },

// --- Application Attacks ---
{ id: 32, front: `What is SQL injection?`, back: `Inserting malicious SQL into input fields that are passed to database queries without sanitization. Can bypass authentication, extract data, modify records, or execute commands.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Application Attacks'] },
{ id: 33, front: `Best defense against SQL injection?`, back: `Parameterized queries (prepared statements). Input is ALWAYS treated as data, never as code. This is the gold standard — not input validation, not WAFs, not stored procedures.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Application Attacks'] },
{ id: 34, front: `Reflected XSS vs. Stored XSS vs. DOM-based XSS`, back: `Reflected: malicious script in URL, requires victim to click a link. Stored: script permanently saved on server, executes for ALL visitors (more dangerous). DOM-based: entirely client-side JavaScript, server never sees the payload.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Application Attacks'] },
{ id: 35, front: `What is CSRF (Cross-Site Request Forgery)?`, back: `Tricks an authenticated user's browser into making unwanted requests. Exploits the browser's automatic inclusion of cookies. Prevention: anti-CSRF tokens, SameSite cookies, re-authentication for sensitive ops.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Application Attacks'] },
{ id: 36, front: `What is a buffer overflow?`, back: `Writing more data to a buffer than it can hold, overwriting adjacent memory. Can inject and execute arbitrary code. Mitigations: ASLR, DEP/NX bit, stack canaries, bounds checking.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Application Attacks'] },
{ id: 37, front: `ASLR vs. DEP vs. Stack canaries`, back: `ASLR: randomizes memory layout (can't predict where code is). DEP/NX: prevents code execution in data segments. Stack canaries: values that detect stack overwrites before return. All three mitigate buffer overflows.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Application Attacks'] },
{ id: 38, front: `What is BOLA/IDOR?`, back: `Broken Object Level Authorization / Insecure Direct Object Reference. Accessing other users' data by modifying object IDs in API requests. The #1 API vulnerability. Always validate authorization at the object level.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Application Attacks'] },
{ id: 39, front: `What is a race condition (TOCTOU)?`, back: `Time of Check, Time of Use. Exploits the gap between checking a condition and using the result. Attacker changes the resource between check and use. Prevention: atomic operations, proper locking.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Application Attacks'] },
{ id: 40, front: `Vertical vs. Horizontal privilege escalation`, back: `Vertical: lower-privilege user gains higher-privilege access (user → admin). Horizontal: user accesses resources of another user at the SAME privilege level.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Application Attacks'] },
{ id: 41, front: `What is a replay attack?`, back: `Capturing valid authentication data and retransmitting it to gain unauthorized access. Prevention: session tokens with expiration, nonces (numbers used once), timestamps.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Application Attacks'] },
{ id: 42, front: `EXAM TIP: Application attack defenses`, back: `SQLi → parameterized queries. XSS → output encoding + CSP. CSRF → anti-CSRF tokens + SameSite cookies. Buffer overflow → ASLR + DEP + stack canaries. Know the PRIMARY defense for each attack type.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'tip', topics: ['Application Attacks'] },

// --- Network Attacks ---
{ id: 43, front: `Volumetric vs. Protocol vs. Application-layer DDoS`, back: `Volumetric: flood bandwidth (bps). Protocol: exhaust server resources with protocol exploits (pps), e.g., SYN flood. Application-layer: target services with legit-looking requests (rps), e.g., Slowloris.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Network Attacks'] },
{ id: 44, front: `What is a SYN flood?`, back: `Protocol DDoS attack sending thousands of SYN packets without completing the 3-way handshake, exhausting the target's connection table. Mitigation: SYN cookies (encode info in SYN-ACK, no resource allocation until handshake completes).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Network Attacks'] },
{ id: 45, front: `What is DNS amplification?`, back: `Reflection/amplification DDoS. Small queries (~60 bytes) sent to open DNS resolvers with spoofed victim source IP. Resolvers send large responses (~3000+ bytes) to victim. 50x+ amplification.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Network Attacks'] },
{ id: 46, front: `What is ARP poisoning?`, back: `Sending forged ARP replies to associate the attacker's MAC address with the gateway's IP. Traffic intended for gateway flows through attacker (on-path attack). Prevention: Dynamic ARP Inspection (DAI).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Network Attacks'] },
{ id: 47, front: `What is DNS spoofing/poisoning?`, back: `Injecting false DNS records into a resolver's cache, redirecting users to malicious IPs. Prevention: DNSSEC (cryptographically signs DNS records).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Network Attacks'] },
{ id: 48, front: `What is SSL/TLS stripping?`, back: `On-path attack that downgrades HTTPS to HTTP. Attacker maintains HTTPS with server but serves HTTP to victim, intercepting plaintext. Prevention: HSTS (HTTP Strict Transport Security).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Network Attacks'] },
{ id: 49, front: `What is VLAN hopping?`, back: `Gaining access to traffic on other VLANs by exploiting switch misconfigurations. Double tagging: two VLAN tags — first stripped by first switch, second routes to target VLAN. Prevention: change default native VLAN.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Network Attacks'] },
{ id: 50, front: `What is MAC flooding?`, back: `Overwhelming a switch's MAC address table with fake entries, causing it to fail open and broadcast all traffic like a hub. Attacker can then sniff all network traffic.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Network Attacks'] },
{ id: 51, front: `On-path attack defenses`, back: `ARP poisoning → Dynamic ARP Inspection. DNS spoofing → DNSSEC. SSL stripping → HSTS. Rogue DHCP → DHCP snooping. General → encrypted protocols (HTTPS, SSH, TLS).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'tip', topics: ['Network Attacks'] },

// --- Vulnerability Scanning ---
{ id: 52, front: `Credentialed vs. Non-credentialed scans`, back: `Credentialed: logs into systems for deeper analysis — finds MORE vulns with FEWER false positives. Non-credentialed: scans from outside, attacker's perspective — finds fewer vulns, more false positives.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Vulnerability Scanning'] },
{ id: 53, front: `What is CVSS?`, back: `Common Vulnerability Scoring System. Rates vulnerability severity 0-10. None: 0.0. Low: 0.1-3.9. Medium: 4.0-6.9. High: 7.0-8.9. Critical: 9.0-10.0. Three score types: base, temporal, environmental.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Vulnerability Scanning'] },
{ id: 54, front: `CVSS vs. EPSS`, back: `CVSS rates HOW BAD a vulnerability is (severity). EPSS rates HOW LIKELY it is to be exploited in the wild (probability). Use both for prioritization: a critical CVSS with high EPSS = fix immediately.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Vulnerability Scanning'] },
{ id: 55, front: `True positive vs. False positive vs. False negative`, back: `True positive: real vuln correctly found. False positive: phantom vuln reported (most common issue). False negative: real vuln MISSED (most dangerous). Credentialed scans reduce both false types.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Vulnerability Scanning'] },
{ id: 56, front: `Black box vs. White box vs. Gray box testing`, back: `Black box: no prior knowledge (external attacker simulation). White box: full knowledge including source code (most thorough). Gray box: partial knowledge (most common in practice). All require written authorization.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Penetration Testing'] },
{ id: 57, front: `Red team vs. Blue team vs. Purple team`, back: `Red: offensive (simulates adversaries). Blue: defensive (detects and responds). Purple: collaborative (red shares techniques with blue in real-time for immediate improvement). White team: oversees exercises.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Penetration Testing'] },
{ id: 58, front: `What is the #1 prerequisite for penetration testing?`, back: `Written authorization and clearly defined rules of engagement (ROE). Without them, testing is unauthorized access — a criminal offense. ROE define scope, authorized activities, contacts, and timelines.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Penetration Testing'] },

// --- Threat Intelligence ---
{ id: 59, front: `Strategic vs. Tactical vs. Operational vs. Technical intelligence`, back: `Strategic: executive-level trends. Tactical: adversary TTPs for defense. Operational: specific attack campaigns. Technical: machine-readable IOCs (IPs, hashes, domains) for automated detection.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Threat Intelligence'] },
{ id: 60, front: `STIX vs. TAXII`, back: `STIX: Structured Threat Information eXpression — defines WHAT to share (JSON format for threat data). TAXII: Trusted Automated eXchange — defines HOW to share (transport protocol). STIX = what, TAXII = how.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Threat Intelligence'] },
{ id: 61, front: `MITRE ATT&CK: Tactics vs. Techniques`, back: `Tactics: the adversary's GOALS (why) — e.g., initial access, persistence, privilege escalation. Techniques: the specific METHODS (how) — e.g., phishing, DLL sideloading. Sub-techniques add granularity.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'comparison', topics: ['Threat Intelligence'] },
{ id: 62, front: `Cyber Kill Chain phases`, back: `1. Reconnaissance 2. Weaponization 3. Delivery 4. Exploitation 5. Installation 6. Command & Control 7. Actions on Objectives. Break the chain as EARLY as possible (delivery phase is most effective).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'concept', topics: ['Threat Intelligence'] },
{ id: 63, front: `What are ISACs?`, back: `Information Sharing and Analysis Centers. Sector-specific organizations for sharing threat intelligence. Examples: FS-ISAC (financial), H-ISAC (healthcare), IT-ISAC (information technology).`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Threat Intelligence'] },
{ id: 64, front: `What is threat hunting?`, back: `PROACTIVE search for threats that evaded existing detection. Assumes adversaries may already be in the network. Approaches: hypothesis-driven, IOC-driven, analytics-driven, TTP-driven.`, domain: 'domain1', domainName: 'Threats, Vulnerabilities & Attacks', category: 'definition', topics: ['Threat Intelligence'] },

// ═══════════════════════════════════════════════════════════════
// DOMAIN 2 — Security Architecture (21%)
// ═══════════════════════════════════════════════════════════════

{ id: 65, front: `NIST CSF five core functions`, back: `Identify, Protect, Detect, Respond, Recover. These provide a common language for managing cybersecurity risk. Implementation tiers range from Partial (T1) to Adaptive (T4).`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Security Frameworks'] },
{ id: 66, front: `NIST RMF seven steps`, back: `Prepare, Categorize, Select, Implement, Assess, Authorize, Monitor. Mandatory for US federal agencies. Uses NIST SP 800-53 controls.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Security Frameworks'] },
{ id: 67, front: `ISO 27001 vs. ISO 27002`, back: `ISO 27001: ISMS requirements, CERTIFIABLE. ISO 27002: best practice guidance for controls, NOT certifiable. 27001 says WHAT is required; 27002 says HOW to implement.`, domain: 'domain2', domainName: 'Security Architecture', category: 'comparison', topics: ['Security Frameworks'] },
{ id: 68, front: `What is Zero Trust?`, back: `"Never trust, always verify." Core principles: verify explicitly, least privilege access, assume breach. NOT a product — it's an architecture requiring identity management, micro-segmentation, and continuous monitoring.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Security Frameworks'] },
{ id: 69, front: `CIA Triad`, back: `Confidentiality: only authorized access (encryption, access controls). Integrity: data is accurate and unmodified (hashing, digital signatures). Availability: accessible when needed (redundancy, backups).`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Security Models'] },
{ id: 70, front: `Defense in depth`, back: `Layered security: physical → network → host → application → data → administrative. Multiple overlapping controls so if one fails, others continue protecting. No single point of failure.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Security Models'] },
{ id: 71, front: `Security control types`, back: `By function: preventive, detective, corrective, deterrent, compensating. By implementation: physical (locks, guards), technical/logical (firewalls, encryption), administrative/managerial (policies, training).`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Security Models'] },
{ id: 72, front: `Shared responsibility model`, back: `IaaS: customer manages OS, apps, data. PaaS: customer manages apps, data. SaaS: customer manages user access, data classification. Customer ALWAYS owns data and identity management.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Security Models'] },
{ id: 73, front: `What is a DMZ?`, back: `Demilitarized Zone. Network segment between internal network and internet for hosting internet-facing services. Typically uses dual firewalls. Protects internal network from direct internet exposure.`, domain: 'domain2', domainName: 'Security Architecture', category: 'definition', topics: ['Secure Network Design'] },
{ id: 74, front: `What is 802.1X?`, back: `Port-based network access control. Three components: supplicant (client), authenticator (switch/AP), authentication server (RADIUS). Devices must authenticate before receiving network access.`, domain: 'domain2', domainName: 'Security Architecture', category: 'definition', topics: ['Secure Network Design'] },
{ id: 75, front: `What is micro-segmentation?`, back: `Extending segmentation to the workload level (individual servers, apps, containers). Enables zero trust networking. Every workload-to-workload communication is verified. Implemented via SDN or host-based firewalls.`, domain: 'domain2', domainName: 'Security Architecture', category: 'definition', topics: ['Secure Network Design'] },
{ id: 76, front: `IDS vs. IPS`, back: `IDS: passive monitoring, generates alerts only, can be out-of-band. IPS: active blocking, drops/resets malicious traffic, must be INLINE. Both use signature-based and anomaly-based detection.`, domain: 'domain2', domainName: 'Security Architecture', category: 'comparison', topics: ['Secure Network Design'] },
{ id: 77, front: `What is a NGFW?`, back: `Next-Generation Firewall. Combines stateful inspection + deep packet inspection + application awareness + IPS + URL filtering + threat intelligence. Operates at Layer 7 (application).`, domain: 'domain2', domainName: 'Security Architecture', category: 'definition', topics: ['Secure Network Design'] },
{ id: 78, front: `Insecure → Secure protocol replacements`, back: `Telnet → SSH. HTTP → HTTPS. FTP → SFTP/FTPS. SNMP v1/v2 → v3. LDAP → LDAPS. DNS → DNSSEC/DoH/DoT. IMAP/POP3 → IMAPS/POP3S.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Secure Network Design'] },
{ id: 79, front: `IPSec tunnel mode vs. transport mode`, back: `Tunnel mode: encrypts ENTIRE packet (headers + payload), new IP header added. Used for site-to-site VPN. Transport mode: encrypts PAYLOAD only, original headers visible. Used for host-to-host.`, domain: 'domain2', domainName: 'Security Architecture', category: 'comparison', topics: ['Secure Network Design'] },
{ id: 80, front: `Split tunnel vs. Full tunnel VPN`, back: `Split tunnel: only corporate traffic goes through VPN; internet traffic goes direct. Less VPN load but less control. Full tunnel: ALL traffic routes through VPN. Maximum security and visibility.`, domain: 'domain2', domainName: 'Security Architecture', category: 'comparison', topics: ['Secure Network Design'] },
{ id: 81, front: `What is a CASB?`, back: `Cloud Access Security Broker. Sits between users and cloud providers. Functions: shadow IT visibility, compliance enforcement, data security (DLP), threat protection. Deployment: forward proxy, reverse proxy, or API-based.`, domain: 'domain2', domainName: 'Security Architecture', category: 'definition', topics: ['Cloud Security'] },
{ id: 82, front: `What is CSPM?`, back: `Cloud Security Posture Management. Continuously monitors cloud configs for misconfigurations: public storage buckets, open security groups, disabled encryption. Automates compliance checking.`, domain: 'domain2', domainName: 'Security Architecture', category: 'definition', topics: ['Cloud Security'] },
{ id: 83, front: `#1 cause of cloud data breaches?`, back: `Misconfigured cloud storage and services (public S3 buckets, open security groups, disabled encryption). Not sophisticated attacks — basic security oversights. Use CSPM to detect.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Cloud Security'] },
{ id: 84, front: `IaaS vs. PaaS vs. SaaS security responsibility`, back: `IaaS: customer has MOST responsibility (OS, apps, data). PaaS: customer manages apps and data. SaaS: customer has LEAST responsibility (access, data classification only). Data & identity: ALWAYS customer.`, domain: 'domain2', domainName: 'Security Architecture', category: 'comparison', topics: ['Cloud Security'] },
{ id: 85, front: `VM escape`, back: `An attacker breaks out of a virtual machine to interact with the hypervisor or other VMs. The MOST serious virtualization threat because it breaks VM isolation. Mitigation: patched hypervisors, Type 1 hypervisors.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Virtualization'] },
{ id: 86, front: `Type 1 vs. Type 2 hypervisor`, back: `Type 1 (bare-metal): runs directly on hardware, MORE secure, no underlying OS. Examples: ESXi, Hyper-V. Type 2 (hosted): runs on host OS, LESS secure, additional attack surface. Examples: VirtualBox, VMware Workstation.`, domain: 'domain2', domainName: 'Security Architecture', category: 'comparison', topics: ['Virtualization'] },
{ id: 87, front: `Containers vs. VMs: isolation`, back: `Containers share host OS kernel → LESS isolation. VMs each have their own OS kernel → MORE isolation. Container escape exploits kernel vulnerabilities. VM escape is harder because of stronger isolation.`, domain: 'domain2', domainName: 'Security Architecture', category: 'comparison', topics: ['Virtualization'] },
{ id: 88, front: `Container security best practices`, back: `Scan images for vulnerabilities. Use trusted base images. Don't run as root. Use secrets management (not hardcoded). Implement SBOM for supply chain security. Use immutable infrastructure.`, domain: 'domain2', domainName: 'Security Architecture', category: 'concept', topics: ['Virtualization'] },
{ id: 89, front: `What is "denial of wallet"?`, back: `Serverless equivalent of DoS. Attackers trigger excessive function invocations to drive up cloud costs. Each invocation costs money, so massive triggering creates huge bills.`, domain: 'domain2', domainName: 'Security Architecture', category: 'definition', topics: ['Virtualization'] },

// ═══════════════════════════════════════════════════════════════
// DOMAIN 3 — Security Implementation (25%)
// ═══════════════════════════════════════════════════════════════

{ id: 90, front: `AES`, back: `Advanced Encryption Standard. SYMMETRIC encryption. Key sizes: 128, 192, 256 bits. The current standard for bulk data encryption. AES-256 is the gold standard for data at rest.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['Cryptography'] },
{ id: 91, front: `Symmetric vs. Asymmetric encryption`, back: `Symmetric: same key encrypts/decrypts, fast, used for bulk data (AES). Asymmetric: key pair (public/private), slower, solves key distribution (RSA, ECC). Typically combine both: asymmetric for key exchange, symmetric for data.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Cryptography'] },
{ id: 92, front: `Encrypt with whose key? Sign with whose key?`, back: `ENCRYPT: use recipient's PUBLIC key (only their private key decrypts). SIGN: use YOUR PRIVATE key (anyone with your public key can verify). This is a critical exam distinction.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Cryptography'] },
{ id: 93, front: `RSA vs. ECC`, back: `RSA: most widely used asymmetric algorithm, larger keys (2048-4096 bit). ECC: equivalent security with MUCH smaller keys (256-bit ECC ≈ 3072-bit RSA). ECC is more efficient for mobile/IoT.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Cryptography'] },
{ id: 94, front: `What is Diffie-Hellman?`, back: `Key EXCHANGE protocol — allows two parties to establish a shared secret over an insecure channel. NOT for encryption or signing directly. Ephemeral DH (DHE) provides perfect forward secrecy.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['Cryptography'] },
{ id: 95, front: `MD5 vs. SHA-1 vs. SHA-256`, back: `MD5: 128-bit, BROKEN — never use for security. SHA-1: 160-bit, DEPRECATED — collision attacks demonstrated. SHA-256: 256-bit, CURRENT STANDARD. Use SHA-256 or SHA-3 for all security purposes.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Cryptography'] },
{ id: 96, front: `What is perfect forward secrecy (PFS)?`, back: `If long-term key is compromised, past sessions remain secure. Achieved with ephemeral keys (DHE, ECDHE) — each session uses unique temporary keys. TLS 1.3 MANDATES PFS.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Cryptography'] },
{ id: 97, front: `Password hashing: bcrypt vs. PBKDF2 vs. Argon2`, back: `bcrypt: adaptive with configurable work factor, standard choice. PBKDF2: HMAC-based with configurable iterations, NIST recommended. Argon2: memory-hard (resists GPU attacks), PHC winner. All use salting.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Cryptography'] },
{ id: 98, front: `ECB vs. CBC vs. GCM block cipher modes`, back: `ECB: each block independent, INSECURE (reveals patterns). CBC: blocks chained, requires IV, secure but not parallelizable. GCM: counter mode + authentication (AEAD), PREFERRED for modern apps (TLS 1.3).`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Cryptography'] },
{ id: 99, front: `Root CA vs. Intermediate CA`, back: `Root CA: top of trust hierarchy, self-signed, private key must be OFFLINE/air-gapped. Intermediate CA: issued by root, issues end-entity certs. If intermediate is compromised, only its certs affected.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['PKI'] },
{ id: 100, front: `CRL vs. OCSP`, back: `CRL: Certificate Revocation List — downloaded list of revoked certs. OCSP: Online Certificate Status Protocol — real-time status check. OCSP is more efficient. OCSP Stapling: server includes OCSP response.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['PKI'] },
{ id: 101, front: `DV vs. OV vs. EV certificates`, back: `DV: domain validation only, quickest, minimal assurance. OV: domain + organization identity, moderate assurance. EV: rigorous verification of org identity, physical address, legal status, highest assurance.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['PKI'] },
{ id: 102, front: `TLS 1.3 improvements`, back: `1 round-trip handshake (vs. 2 in TLS 1.2). Removed insecure algorithms. ONLY AEAD ciphers (AES-GCM, ChaCha20). PFS is MANDATORY. TLS 1.2 is the minimum acceptable version.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['PKI'] },
{ id: 103, front: `Authentication factors`, back: `Something you KNOW (password, PIN). Something you HAVE (token, phone, smart card). Something you ARE (biometrics). MFA requires 2+ DIFFERENT factors. Two passwords is NOT MFA.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Authentication'] },
{ id: 104, front: `Strongest to weakest MFA methods`, back: `FIDO2/hardware keys (phishing-resistant) > authenticator apps (TOTP) > push notifications > SMS codes (weakest — SIM swapping, SS7 vulnerabilities). NIST discourages SMS-based MFA.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Authentication'] },
{ id: 105, front: `FAR vs. FRR vs. CER in biometrics`, back: `FAR (False Acceptance): unauthorized user accepted (Type II). FRR (False Rejection): authorized user rejected (Type I). CER (Crossover Error Rate): where FAR=FRR. Lower CER = more accurate system.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Authentication'] },
{ id: 106, front: `Kerberos`, back: `Ticket-based authentication for Active Directory. Uses KDC (Key Distribution Center) with AS (Authentication Service) and TGS (Ticket-Granting Service). Attacks: golden ticket, silver ticket, Kerberoasting.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['Authentication'] },
{ id: 107, front: `RADIUS vs. TACACS+`, back: `RADIUS: encrypts ONLY password, UDP 1812/1813, combines auth+authz. TACACS+: encrypts ENTIRE packet, TCP port 49, SEPARATES authentication/authorization/accounting. TACACS+ is more secure.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Authentication'] },
{ id: 108, front: `OAuth 2.0 vs. OpenID Connect`, back: `OAuth: AUTHORIZATION only — grants access to resources, does NOT identify users. OIDC: adds AUTHENTICATION on top of OAuth — adds ID token identifying the user. "Login with Google" = OIDC.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Authentication'] },
{ id: 109, front: `SAML`, back: `Security Assertion Markup Language. XML-based SSO for web applications. Three parties: Identity Provider (IdP), Service Provider (SP), User. Used for enterprise web SSO.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['Authentication'] },
{ id: 110, front: `DAC vs. MAC vs. RBAC vs. ABAC`, back: `DAC: owner decides (flexible, less secure). MAC: system-enforced labels (military). RBAC: role-based (simplifies large orgs). ABAC: attribute-based (most flexible, used in cloud/zero trust).`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Access Control'] },
{ id: 111, front: `Least privilege vs. Separation of duties`, back: `Least privilege: minimum permissions for the job (vertical restriction). Separation of duties: critical tasks divided among multiple people to prevent fraud (horizontal division).`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Access Control'] },
{ id: 112, front: `What is implicit deny?`, back: `If no rule explicitly permits access, access is DENIED by default. Foundational principle for firewalls, ACLs, and access control. The secure default — whitelist approach.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['Access Control'] },
{ id: 113, front: `What is privilege creep?`, back: `Accumulation of unnecessary privileges over time as users change roles but old permissions aren't revoked. Addressed through regular access reviews and recertification.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['Access Control'] },
{ id: 114, front: `EDR vs. XDR`, back: `EDR: Endpoint Detection and Response — monitors endpoints with behavioral analysis, investigation, automated response. XDR: Extended DR — correlates data across endpoints + network + cloud + email + identity.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Endpoint Security'] },
{ id: 115, front: `Allowlisting vs. Blocklisting`, back: `Allowlisting (whitelist): only approved apps can run — MORE secure (implicit deny). Blocklisting (blacklist): known bad apps blocked, everything else allowed — LESS secure. Allowlisting is recommended for high-security.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Endpoint Security'] },
{ id: 116, front: `DLP types`, back: `Endpoint DLP: monitors device-level transfers (USB, email, print). Network DLP: monitors traffic leaving the network. Cloud DLP: monitors data in cloud services. Use all three for comprehensive coverage.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Endpoint Security'] },
{ id: 117, front: `TPM vs. HSM`, back: `TPM: chip on motherboard, stores keys, verifies boot integrity. Required for BitLocker. HSM: dedicated hardware for high-security crypto operations (CA keys, payment processing). Tamper-resistant.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Endpoint Security'] },
{ id: 118, front: `MDM vs. MAM`, back: `MDM: Mobile Device Management — controls entire device (wipe, lock, encrypt). MAM: Mobile Application Management — controls only apps (better for BYOD where org doesn't own device).`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Endpoint Security'] },
{ id: 119, front: `BYOD vs. COPE vs. CYOD`, back: `BYOD: personal device for work — highest risk, lowest cost. COPE: company-owned, personally enabled — more control. CYOD: choose from approved list — balance of both. Corporate-owned: maximum control, highest cost.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Endpoint Security'] },
{ id: 120, front: `WEP vs. WPA vs. WPA2 vs. WPA3`, back: `WEP: RC4, BROKEN. WPA: TKIP, deprecated. WPA2: AES-CCMP, current standard. WPA3: SAE + GCMP + mandatory PMF + forward secrecy, latest. Never use WEP/WPA.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Wireless Security'] },
{ id: 121, front: `What is WPA3-SAE?`, back: `Simultaneous Authentication of Equals. Replaces 4-way handshake with Dragonfly protocol. Prevents offline dictionary attacks — each guess requires online interaction. Provides forward secrecy.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Wireless Security'] },
{ id: 122, front: `Enterprise vs. Personal wireless mode`, back: `Personal (PSK): shared password for all users — if compromised, all affected. Enterprise (802.1X): unique credentials per user via RADIUS — individual accountability, centralized management.`, domain: 'domain3', domainName: 'Security Implementation', category: 'comparison', topics: ['Wireless Security'] },
{ id: 123, front: `Most secure EAP method?`, back: `EAP-TLS: mutual certificate authentication (both client AND server). Most secure but requires certificate deployment to all clients. PEAP and EAP-TTLS only require server certificates.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Wireless Security'] },
{ id: 124, front: `What is an evil twin attack?`, back: `Rogue AP mimicking a legitimate network's SSID. Users connect to it and have traffic intercepted. Often combined with deauthentication attack to force disconnection from real AP.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['Wireless Security'] },
{ id: 125, front: `Why disable WPS?`, back: `WPS uses an 8-digit PIN (effectively 7 with checksum) that can be brute-forced in hours. Reveals WPA/WPA2 passphrase regardless of its complexity. Always disable WPS on access points.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['Wireless Security'] },
{ id: 126, front: `CIS Benchmarks`, back: `Detailed, consensus-based configuration guides for hardening OSes, apps, and network devices. The most widely used industry security baselines. Organized into Implementation Groups (IG1-IG3).`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['System Hardening'] },
{ id: 127, front: `Patch management process`, back: `Inventory → Identify → Evaluate → Test (in staging) → Deploy (production) → Verify → Document. NEVER deploy patches directly to production without testing first.`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['System Hardening'] },
{ id: 128, front: `What is configuration drift?`, back: `Systems deviating from the approved security baseline over time due to ad hoc changes, manual modifications, or unmanaged updates. Detect with automated tools; enforce with IaC.`, domain: 'domain3', domainName: 'Security Implementation', category: 'definition', topics: ['System Hardening'] },
{ id: 129, front: `NIST 800-88 data sanitization`, back: `Clear: overwrite with zeros/patterns (reuse within org). Purge: cryptographic erasure or degaussing (reuse outside org). Destroy: physical destruction — shredding, incineration (highest sensitivity).`, domain: 'domain3', domainName: 'Security Implementation', category: 'concept', topics: ['System Hardening'] },

// ═══════════════════════════════════════════════════════════════
// DOMAIN 4 — Security Operations (20%)
// ═══════════════════════════════════════════════════════════════

{ id: 130, front: `NIST IR phases`, back: `1. Preparation 2. Detection & Analysis 3. Containment, Eradication, Recovery 4. Post-Incident Activity (Lessons Learned). Preparation is the MOST important phase.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Incident Response'] },
{ id: 131, front: `Containment vs. Eradication vs. Recovery`, back: `Containment: STOP the spread (isolate systems). Eradication: REMOVE the threat (delete malware, patch vuln). Recovery: RESTORE operations (rebuild, restore from backup). Always in this order.`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Incident Response'] },
{ id: 132, front: `Why is Preparation the most important IR phase?`, back: `It determines how effectively ALL subsequent phases are executed. Without an IR plan, trained team, tools, and procedures, response will be chaotic and slow. You can't respond well without preparing.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Incident Response'] },
{ id: 133, front: `Playbook vs. Runbook`, back: `Playbook: HIGH-LEVEL guidance for responding to specific incident types (ransomware playbook). Runbook: STEP-BY-STEP technical procedures for specific actions (how to isolate a host).`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Incident Response'] },
{ id: 134, front: `GDPR breach notification timeline`, back: `72 hours to supervisory authority after becoming aware. Individual notification without undue delay if high risk. HIPAA: 60 days for 500+ individuals. State laws vary.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Incident Response'] },
{ id: 135, front: `What is a tabletop exercise?`, back: `Discussion-based walkthrough of an incident scenario. No actual system actions. Tests IR plan effectiveness and team coordination with minimal risk and cost. Should be conducted regularly.`, domain: 'domain4', domainName: 'Security Operations', category: 'definition', topics: ['Incident Response'] },
{ id: 136, front: `Order of volatility`, back: `CPU registers → RAM → swap files → hard drive → remote logs → physical config → archives. Collect MOST VOLATILE first. RAM contains encryption keys, running processes — lost on power-off.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Digital Forensics'] },
{ id: 137, front: `What is a write blocker?`, back: `Hardware or software that prevents write operations to source media during forensic imaging. MANDATORY for maintaining evidence integrity and admissibility. Ensures original evidence is unmodified.`, domain: 'domain4', domainName: 'Security Operations', category: 'definition', topics: ['Digital Forensics'] },
{ id: 138, front: `What is chain of custody?`, back: `Documentation tracking every person who handled evidence, when, why, and what they did. Proves evidence hasn't been tampered with. BROKEN chain = potentially INADMISSIBLE evidence.`, domain: 'domain4', domainName: 'Security Operations', category: 'definition', topics: ['Digital Forensics'] },
{ id: 139, front: `What is file carving?`, back: `Recovering files based on file headers and footers rather than file system metadata. Can recover deleted files even when directory entries are destroyed.`, domain: 'domain4', domainName: 'Security Operations', category: 'definition', topics: ['Digital Forensics'] },
{ id: 140, front: `What is timestomping?`, back: `Anti-forensic technique of altering file system timestamps to confuse timeline analysis. Modifies creation, modification, and access dates to obscure the true sequence of events.`, domain: 'domain4', domainName: 'Security Operations', category: 'definition', topics: ['Digital Forensics'] },
{ id: 141, front: `What is steganography?`, back: `Hiding data within innocent-looking files (images, audio, video). The carrier file looks normal but contains embedded secret data. An anti-forensic technique for covert communication.`, domain: 'domain4', domainName: 'Security Operations', category: 'definition', topics: ['Digital Forensics'] },
{ id: 142, front: `SIEM vs. SOAR`, back: `SIEM: aggregate logs + correlate events + generate alerts. SOAR: automate response workflows + orchestrate actions across tools. SIEM detects; SOAR responds. Together they reduce MTTD and MTTR.`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Logging & Monitoring'] },
{ id: 143, front: `Why is NTP critical for security?`, back: `NTP synchronizes time across all systems. Without it, log correlation is unreliable — events from different sources can't be accurately sequenced. NTP is a PREREQUISITE for effective SIEM operation.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Logging & Monitoring'] },
{ id: 144, front: `What is alert fatigue?`, back: `Analysts overwhelmed by too many alerts (mostly false positives), becoming desensitized and potentially missing real threats. Mitigate by tuning rules, prioritization, and SOAR automation.`, domain: 'domain4', domainName: 'Security Operations', category: 'definition', topics: ['Logging & Monitoring'] },
{ id: 145, front: `MTTD vs. MTTR vs. Dwell time`, back: `MTTD: Mean Time to Detect (intrusion to detection). MTTR: Mean Time to Respond (detection to response). Dwell time: total time attacker is undetected in environment. All should be minimized.`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Logging & Monitoring'] },
{ id: 146, front: `SOC tiers`, back: `Tier 1: Alert triage — monitor dashboards, initial investigation, escalate. Tier 2: Investigation — deep-dive analysis, scope, containment. Tier 3: Threat hunting/engineering — proactive hunting, detection rules, malware analysis.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Logging & Monitoring'] },
{ id: 147, front: `Syslog ports`, back: `UDP 514: traditional syslog (no encryption, unreliable). TCP 6514: syslog over TLS (encrypted, recommended for sensitive environments). Always use encrypted syslog for security logs.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Logging & Monitoring'] },
{ id: 148, front: `Full vs. Incremental vs. Differential backup`, back: `Full: everything, slowest backup, fastest restore. Incremental: since LAST backup (any type), fastest backup, slowest restore. Differential: since last FULL backup, medium speed. Know restore requirements!`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Backup & DR'] },
{ id: 149, front: `RTO vs. RPO`, back: `RTO (Recovery Time Objective): maximum acceptable DOWNTIME. RPO (Recovery Point Objective): maximum acceptable DATA LOSS (in time). RTO is time-focused; RPO is data-focused. RTO must be less than MTD.`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Backup & DR'] },
{ id: 150, front: `Hot site vs. Warm site vs. Cold site`, back: `Hot: fully equipped, real-time replication, minutes to hours ($$$$). Warm: hardware installed, needs data restore, hours to days ($$). Cold: empty facility, needs everything, days to weeks ($).`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Backup & DR'] },
{ id: 151, front: `3-2-1 backup rule`, back: `3 copies of data, on 2 different media types, with 1 copy offsite. Extended: 3-2-1-1-0 (plus 1 immutable/air-gapped + 0 errors verified). Immutable backups are critical for ransomware defense.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Backup & DR'] },
{ id: 152, front: `RAID 0 vs. 1 vs. 5 vs. 6 vs. 10`, back: `RAID 0: striping, NO redundancy. RAID 1: mirroring, 50% capacity. RAID 5: striping+parity, tolerates 1 disk failure, min 3 disks. RAID 6: double parity, tolerates 2 failures. RAID 10: mirror+stripe, performance+redundancy.`, domain: 'domain4', domainName: 'Security Operations', category: 'comparison', topics: ['Backup & DR'] },
{ id: 153, front: `DR plan testing methods (least to most disruptive)`, back: `Checklist review → Tabletop exercise → Simulation → Parallel test (DR + production) → Full interruption (production stopped). Full interruption: highest confidence, highest risk.`, domain: 'domain4', domainName: 'Security Operations', category: 'concept', topics: ['Backup & DR'] },

// ═══════════════════════════════════════════════════════════════
// DOMAIN 5 — Security Program Management & Oversight (10%)
// ═══════════════════════════════════════════════════════════════

{ id: 154, front: `Policy vs. Standard vs. Guideline vs. Procedure`, back: `Policy: WHAT is required (mandatory, management-approved). Standard: specific technical requirement (mandatory). Guideline: recommendations (NOT mandatory). Procedure: HOW to do it (step-by-step instructions).`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Policies & Procedures'] },
{ id: 155, front: `Data owner vs. Data custodian`, back: `Data owner: senior management, CLASSIFIES data and makes protection decisions. Data custodian: IT staff, IMPLEMENTS controls defined by the owner. Owner decides; custodian executes.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Policies & Procedures'] },
{ id: 156, front: `Government data classification levels`, back: `Top Secret → Secret → Confidential → Unclassified. Commercial equivalent: Restricted/Confidential → Internal/Private → Public. Classification drives handling requirements and access controls.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'concept', topics: ['Policies & Procedures'] },
{ id: 157, front: `Separation of duties vs. Job rotation vs. Mandatory vacation`, back: `Separation of duties: divide critical tasks among multiple people. Job rotation: rotate employees through positions. Mandatory vacation: require time off so others perform duties. All detect/prevent fraud.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Policies & Procedures'] },
{ id: 158, front: `Most critical offboarding step?`, back: `Revoking all system access and authentication credentials IMMEDIATELY. Must happen before or simultaneously with notification. Collect assets second. Everything else is administrative.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'concept', topics: ['Policies & Procedures'] },
{ id: 159, front: `SLE = AV × EF`, back: `Single Loss Expectancy = Asset Value × Exposure Factor. Example: $500,000 asset × 60% exposure = $300,000 SLE. This is the expected loss from a single event.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'concept', topics: ['Risk Management'] },
{ id: 160, front: `ALE = SLE × ARO`, back: `Annualized Loss Expectancy = SLE × Annual Rate of Occurrence. Example: $300,000 SLE × 0.5 ARO = $150,000 ALE. Don't spend more than ALE on controls for that risk.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'concept', topics: ['Risk Management'] },
{ id: 161, front: `Risk response strategies`, back: `Avoid: eliminate the risk entirely. Mitigate/Reduce: implement controls. Transfer/Share: shift to third party (insurance). Accept: acknowledge and do nothing (must be documented and management-approved).`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'concept', topics: ['Risk Management'] },
{ id: 162, front: `Inherent risk vs. Residual risk`, back: `Inherent: risk level BEFORE controls. Residual: risk AFTER controls are applied. Residual risk must be within the organization's risk tolerance. If not, add more controls or accept formally.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Risk Management'] },
{ id: 163, front: `Risk appetite vs. Risk tolerance`, back: `Risk appetite: strategic, board-level willingness to take risk (broad). Risk tolerance: operational, acceptable deviation from risk targets (specific). Appetite = governance; tolerance = operational.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Risk Management'] },
{ id: 164, front: `STRIDE threat model`, back: `Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege. Used during design to identify potential threats systematically.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'concept', topics: ['Risk Management'] },
{ id: 165, front: `Qualitative vs. Quantitative risk analysis`, back: `Qualitative: subjective ratings (High/Medium/Low), faster, less precise. Quantitative: numerical/financial values (SLE, ALE, ARO), more precise but requires more data. Most orgs use both.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Risk Management'] },
{ id: 166, front: `GDPR`, back: `General Data Protection Regulation. EU law with GLOBAL reach — applies to ANY org processing EU resident data. 72-hour breach notification. Penalties: up to €20M or 4% of global annual turnover.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'definition', topics: ['Compliance'] },
{ id: 167, front: `HIPAA`, back: `Health Insurance Portability and Accountability Act. Protects PHI (Protected Health Information). Applies to covered entities + business associates. Requires BAA with third parties handling PHI. 60-day breach notification.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'definition', topics: ['Compliance'] },
{ id: 168, front: `PCI-DSS`, back: `Payment Card Industry Data Security Standard. Industry standard (NOT government law) for payment card data. 12 requirements in 6 goals. Compliance levels based on transaction volume.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'definition', topics: ['Compliance'] },
{ id: 169, front: `SOX`, back: `Sarbanes-Oxley Act. US regulation for publicly traded companies. CEO/CFO must certify financial statement accuracy. Requires internal controls over financial reporting. Criminal liability for non-compliance.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'definition', topics: ['Compliance'] },
{ id: 170, front: `SOC 1 vs. SOC 2 vs. SOC 3`, back: `SOC 1: financial reporting controls. SOC 2: security controls (Trust Services Criteria) — most relevant. SOC 3: public summary of SOC 2. Type I: point-in-time. Type II: over a period (more valuable).`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Compliance'] },
{ id: 171, front: `Anonymization vs. Pseudonymization vs. Tokenization`, back: `Anonymization: IRREVERSIBLE removal of identifying info. Pseudonymization: REVERSIBLE replacement with artificial identifiers. Tokenization: replaces data with tokens, original in secure vault (used for credit cards).`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Compliance'] },
{ id: 172, front: `Due diligence vs. Due care`, back: `Due diligence: investigation and research (doing your homework). Due care: implementing safeguards based on findings (acting on your homework). Negligence = failure of due care.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'comparison', topics: ['Compliance'] },
{ id: 173, front: `Which regulation for which scenario?`, back: `EU personal data → GDPR. Healthcare/PHI → HIPAA. Payment cards → PCI-DSS. Public companies → SOX. Federal agencies → FISMA. Financial institutions → GLBA. Students → FERPA. Children online → COPPA.`, domain: 'domain5', domainName: 'Security Program Management & Oversight', category: 'tip', topics: ['Compliance'] },

// ═══════════════════════════════════════════════════════════════
// EXAM STRATEGY & TIPS
// ═══════════════════════════════════════════════════════════════

{ id: 174, front: `Exam format: CompTIA Security+ SY0-701`, back: `90 questions, 90 minutes. Mix of multiple choice and performance-based questions (PBQs). Score range: 100-900, passing: 750. PBQs first — skip and return if stuck. Manage your time.`, domain: 'exam', domainName: 'Exam Strategy & Tips', category: 'tip', topics: ['Exam Strategy'] },
{ id: 175, front: `Domain weights for SY0-701`, back: `D1 Threats/Vulns/Attacks: 24%. D2 Architecture: 21%. D3 Implementation: 25% (largest!). D4 Operations: 20%. D5 Governance: 10%. Focus study time proportionally.`, domain: 'exam', domainName: 'Exam Strategy & Tips', category: 'tip', topics: ['Exam Strategy'] },
{ id: 176, front: `EXAM TIP: "BEST" answer strategy`, back: `When multiple answers seem correct, choose the MOST specific and direct answer. "Parameterized queries" beats "input validation" for SQLi. "Security awareness training" beats "firewall" for social engineering.`, domain: 'exam', domainName: 'Exam Strategy & Tips', category: 'tip', topics: ['Exam Strategy'] },
{ id: 177, front: `EXAM TIP: Process of elimination`, back: `On the Security+ exam, eliminate obviously wrong answers first. Usually 2 answers are clearly wrong and 2 are close. Read the question carefully — key words like "BEST", "FIRST", "MOST" change the answer.`, domain: 'exam', domainName: 'Exam Strategy & Tips', category: 'tip', topics: ['Exam Strategy'] },
{ id: 178, front: `Key port numbers for Security+`, back: `SSH: 22. DNS: 53. HTTP: 80. HTTPS: 443. LDAP: 389. LDAPS: 636. RADIUS: 1812/1813. TACACS+: 49. Syslog: 514 (UDP), 6514 (TLS). RDP: 3389. SNMP: 161/162.`, domain: 'exam', domainName: 'Exam Strategy & Tips', category: 'concept', topics: ['Exam Strategy'] },
{ id: 179, front: `EXAM TIP: "FIRST" step questions`, back: `If asked what to do FIRST: Preparation/planning before action. Contain before eradicate. Identify before protect. Get authorization before testing. Collect volatile evidence before stable. Verify before trust.`, domain: 'exam', domainName: 'Exam Strategy & Tips', category: 'tip', topics: ['Exam Strategy'] },
{ id: 180, front: `EXAM TIP: Scenario-based approach`, back: `Read the ENTIRE scenario before answering. Identify: what's the attack/threat? What's the environment? What's the goal (prevent, detect, respond, recover)? Then choose the MOST appropriate control.`, domain: 'exam', domainName: 'Exam Strategy & Tips', category: 'tip', topics: ['Exam Strategy'] },
];

export function getSecurityPlusFlashcards(domain?: string): SecurityPlusFlashcard[] {
  if (!domain) return SECPLUS_FLASHCARDS;
  return SECPLUS_FLASHCARDS.filter(c => c.domain === domain);
}

export function getSecurityPlusFlashcardsByCategory(category: string): SecurityPlusFlashcard[] {
  return SECPLUS_FLASHCARDS.filter(c => c.category === category);
}

export const SECPLUS_FLASHCARD_COUNT = 180;
