"""Chemistry tables: molecules, reactions, mechanisms, spectra, sims, blueprints

OCTET's first migration. The models in app/domains/chemistry/models.py predate
any migration history, so this revision is what actually creates them. Written
by hand rather than autogenerated so applying it leaves zero drift against the
ORM models, and so the table order respects the foreign keys (mechanisms before
reactions, molecules before spectra).

Revision ID: 0001_chemistry
Revises:
Create Date: 2026-07-24 21:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_chemistry"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "molecules",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("smiles_canonical", sa.String(length=2000), nullable=False),
        sa.Column("inchikey", sa.String(length=30), nullable=False),
        sa.Column("formula", sa.String(length=200), nullable=False),
        sa.Column("molar_mass", sa.Float(), nullable=False),
        sa.Column("coords_2d", sa.JSON(), nullable=True),
        sa.Column("coords_3d", sa.JSON(), nullable=True),
        sa.Column("real_world_note", sa.Text(), nullable=False),
        sa.Column("safety_flags", sa.JSON(), nullable=True),
        sa.Column("review", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("inchikey", name="uq_molecule_inchikey"),
    )
    op.create_index("ix_molecules_name", "molecules", ["name"])
    op.create_index("ix_molecules_inchikey", "molecules", ["inchikey"])

    op.create_table(
        "mechanisms",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    op.create_table(
        "reactions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("reactant_pattern", sa.String(length=2000), nullable=False),
        sa.Column("product_pattern", sa.String(length=2000), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=False),
        sa.Column(
            "mechanism_id",
            sa.Uuid(),
            sa.ForeignKey("mechanisms.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("misconception_codes", sa.JSON(), nullable=True),
        sa.Column("roundtrip_ok", sa.Boolean(), nullable=False),
        sa.Column("roundtrip_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("safety_reviewed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_reactions_name", "reactions", ["name"])

    op.create_table(
        "spectra",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "molecule_id",
            sa.Uuid(),
            sa.ForeignKey("molecules.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("modality", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("generating_parameters", sa.JSON(), nullable=False),
        sa.Column("generator_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "molecule_id", "modality", "generator_version", name="uq_spectrum_variant"
        ),
    )

    op.create_table(
        "sim_states",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("scenario", sa.String(length=80), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("server_key", sa.JSON(), nullable=False),
        sa.Column("prediction", sa.JSON(), nullable=True),
        sa.Column("prediction_graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_sim_states_user_id", "sim_states", ["user_id"])

    op.create_table(
        "exam_blueprints",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("source_note", sa.Text(), nullable=False),
        sa.Column("review", sa.String(length=20), nullable=False),
        sa.UniqueConstraint("code"),
    )

    op.create_table(
        "triangle_views",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("node_code", sa.String(length=120), nullable=False),
        sa.Column("macroscopic_asset", sa.String(length=500), nullable=False),
        sa.Column("particulate_animation", sa.String(length=500), nullable=False),
        sa.Column("symbolic_form", sa.Text(), nullable=False),
        sa.Column("synchronized", sa.Boolean(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("node_code", name="uq_triangle_node"),
    )
    op.create_index("ix_triangle_views_node_code", "triangle_views", ["node_code"])


def downgrade() -> None:
    op.drop_index("ix_triangle_views_node_code", table_name="triangle_views")
    op.drop_table("triangle_views")
    op.drop_table("exam_blueprints")
    op.drop_index("ix_sim_states_user_id", table_name="sim_states")
    op.drop_table("sim_states")
    op.drop_table("spectra")
    op.drop_index("ix_reactions_name", table_name="reactions")
    op.drop_table("reactions")
    op.drop_table("mechanisms")
    op.drop_index("ix_molecules_inchikey", table_name="molecules")
    op.drop_index("ix_molecules_name", table_name="molecules")
    op.drop_table("molecules")
