-- ============================================================================
-- Phase 5 Session 5.1 — Question (item) bank (2026-05).
--
-- A reusable, skill-tagged, variant-aware, pgvector-indexed bank of
-- assessment items that any tier / course / exam can pull from. Distinct
-- from the assess service's `questions` table — that one is per-assessment
-- and embedded; this is the canonical bank.
--
-- "Item" is the QBank-industry term (NBME, AAMC, UWorld all use it):
-- a stem + options + correct answer + explanation + skill tags + provenance.
--
-- Five tables:
--
--   item_banks         Named collections ("USMLE Step 1 Cardiology",
--                      "FE Electrical Practice", "AP Calc BC Mock 2027").
--                      A bank groups items for browsing, licensing, and
--                      mock-exam generation.
--
--   items              The canonical item. Stem + answer_options +
--                      correct_answer + explanation + difficulty + Bloom +
--                      IRT params + family_id (for variants). Tagged into
--                      the skill graph via content_skills from Phase 4.2.
--
--   item_variants      Linkage between two items in the same variant
--                      family. Carries provenance: which is the source
--                      variant, who generated it (human SME / Claude /
--                      imported), the validation status.
--
--   item_sources       Provenance + license per item: where it came from,
--                      the licence under which we use it (CC-BY, NCEES
--                      sample, licensed-from-X, AI-generated), the
--                      attribution string the renderer must show.
--
--   item_embeddings    pgvector column for semantic search. Generated by
--                      the embedding pipeline (Phase 6 RAG). Stored
--                      separately because the embedding dimension is a
--                      deployment concern; one row per item per model.
-- ============================================================================

-- Reuse the bloom_level enum from 06_skill_graph.sql.

CREATE TYPE item_kind AS ENUM (
    'mcq_single',      -- multiple choice, exactly one correct
    'mcq_multi',       -- multiple choice, multiple correct
    'short_answer',    -- free-text short answer (regex or AI-graded)
    'numeric',         -- numeric answer with tolerance
    'essay',           -- long-form free-text, AI-graded
    'matching',        -- left-right matching
    'ordering',        -- arrange items in correct order
    'cloze',           -- fill-in-the-blank
    'case'             -- multi-part clinical case (USMLE Step 2/3 CK style)
);

CREATE TYPE item_review_status AS ENUM (
    'draft',           -- just landed, not reviewed
    'in_review',       -- SME has it open
    'approved',        -- live for learners
    'flagged',         -- AI cross-grader / learner reported a problem
    'retired'          -- pulled from circulation
);

CREATE TYPE item_source_kind AS ENUM (
    'imported',        -- bulk-imported from a real bank (NCEES sample, OpenStax, etc.)
    'commissioned',    -- a paid SME wrote it
    'ai_generated',    -- Claude-generated variant
    'community',       -- learner / instructor contributed
    'licensed'         -- under a paid commercial license
);

-- ----------------------------------------------------------------------------
-- item_banks
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS item_banks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    slug VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,

    -- Loose hint about what tier / exam this bank targets. Items can
    -- still be tagged into any skill — this is for browsing only.
    framework skill_framework,
    tier VARCHAR(40),

    -- Licensing inherits to items unless overridden.
    default_license VARCHAR(80) NOT NULL DEFAULT 'CC-BY-4.0',
    default_attribution TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT valid_bank_slug CHECK (slug ~ '^[a-z0-9-]+$')
);

CREATE INDEX IF NOT EXISTS idx_item_banks_framework ON item_banks(framework);
CREATE INDEX IF NOT EXISTS idx_item_banks_tier ON item_banks(tier);

-- ----------------------------------------------------------------------------
-- items
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    bank_id UUID NOT NULL REFERENCES item_banks(id) ON DELETE CASCADE,

    -- The variant family. All variants of one base question share the
    -- same family_id. The base item points to itself.
    family_id UUID NOT NULL,

    kind item_kind NOT NULL,

    -- Stem + options + correct answer + explanation. Stored together as
    -- JSONB for flexibility across kinds; specific shape validated by
    -- the Pydantic schema in api-core.
    --
    --   mcq_single   stem (str), options (list), correct_index (int)
    --   numeric      stem (str), correct_value (float), tolerance (float), unit (str)
    --   essay        stem (str), rubric (dict)
    --   case         vignette (str), sub_items ([{...}])
    content JSONB NOT NULL,

    -- Long-form explanation shown after attempt.
    explanation TEXT,

    -- Difficulty. We store BOTH the SME's nominal level AND the IRT-
    -- calibrated parameters from Phase 7.2. Until calibration runs,
    -- only difficulty_nominal is set.
    difficulty_nominal VARCHAR(20) NOT NULL DEFAULT 'medium'
        CHECK (difficulty_nominal IN ('easy', 'medium', 'hard', 'expert')),
    irt_difficulty NUMERIC(5, 3),      -- b parameter
    irt_discrimination NUMERIC(5, 3),  -- a parameter
    irt_guessing NUMERIC(5, 3),        -- c parameter
    irt_calibrated_at TIMESTAMP,
    attempts_count INTEGER NOT NULL DEFAULT 0,  -- denormalised for analytics

    bloom_level bloom_level,

    -- Estimated time to answer (seconds). Used for mock-exam pacing.
    estimated_time_sec INTEGER,

    -- Free-form tags that don't fit the skill graph (eg "high yield",
    -- "uncommon", "first aid 2026").
    tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],

    review_status item_review_status NOT NULL DEFAULT 'draft',
    reviewed_at TIMESTAMP,
    reviewed_by UUID REFERENCES users(id),
    review_notes TEXT,

    -- Soft delete + audit
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by UUID REFERENCES users(id),

    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_items_bank ON items(bank_id);
CREATE INDEX IF NOT EXISTS idx_items_family ON items(family_id);
CREATE INDEX IF NOT EXISTS idx_items_status ON items(review_status)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_items_kind ON items(kind);
CREATE INDEX IF NOT EXISTS idx_items_difficulty ON items(difficulty_nominal);

-- Full-text on the stem + explanation. We extract a text projection
-- from the JSONB content for indexing.
CREATE INDEX IF NOT EXISTS idx_items_content_fts
    ON items USING gin (to_tsvector('english',
        COALESCE(content->>'stem', '') || ' ' ||
        COALESCE(content->>'vignette', '') || ' ' ||
        COALESCE(explanation, '')));

-- ----------------------------------------------------------------------------
-- item_variants — links variants in a family
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS item_variants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    family_id UUID NOT NULL,
    item_id UUID NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    base_item_id UUID NOT NULL REFERENCES items(id),
    generation_method VARCHAR(40) NOT NULL,  -- 'human_sme' | 'claude' | 'gpt4' | 'imported'
    generation_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- Cross-grader validation: how a second model graded the variant
    -- against the base's skill + rubric. NULL until validation runs.
    crossgrader_agrees BOOLEAN,
    crossgrader_score NUMERIC(3, 2),  -- 0..1 confidence
    crossgrader_notes TEXT,
    crossgrader_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_variant_per_item UNIQUE (item_id)
);

CREATE INDEX IF NOT EXISTS idx_item_variants_family ON item_variants(family_id);
CREATE INDEX IF NOT EXISTS idx_item_variants_base ON item_variants(base_item_id);

-- ----------------------------------------------------------------------------
-- item_sources — provenance + license, one row per item
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS item_sources (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_id UUID NOT NULL UNIQUE REFERENCES items(id) ON DELETE CASCADE,
    source_kind item_source_kind NOT NULL,
    source_uri TEXT,
    source_name VARCHAR(200),
    license VARCHAR(80) NOT NULL,
    attribution TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_item_sources_kind ON item_sources(source_kind);

-- ----------------------------------------------------------------------------
-- item_embeddings — pgvector per (item, model)
--
-- Separate table so we can have multiple embedding columns / models
-- side-by-side during migrations. Dimension picked at deployment time
-- (1024 here = bge-large or text-embedding-3-small).
-- ----------------------------------------------------------------------------
DO $$ BEGIN
    CREATE EXTENSION IF NOT EXISTS vector;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pgvector extension unavailable; semantic search disabled';
END $$;

CREATE TABLE IF NOT EXISTS item_embeddings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_id UUID NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    model VARCHAR(80) NOT NULL,
    -- pgvector dimension. If pgvector is unavailable on a deployment,
    -- this column will be created as bytea; queries that need vector
    -- ops will fail loudly. We chose 1024 to fit bge-large and OpenAI's
    -- text-embedding-3-small (truncated). Resize via ALTER + reindex.
    embedding vector(1024),
    text_hash VARCHAR(64) NOT NULL,  -- sha256 of the indexed text; invalidate on change
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_item_model_embedding UNIQUE (item_id, model)
);

-- HNSW index for cosine distance — the typical embedding distance metric.
CREATE INDEX IF NOT EXISTS idx_item_embeddings_hnsw
    ON item_embeddings USING hnsw (embedding vector_cosine_ops);
