"""The OCTET curriculum: a two year sequence as courses, units and nodes.

This replaces a three tier CF / G1 / G2 split that presented one year of
general chemistry as three courses. No registrar, syllabus or textbook is
organized that way, so an instructor could not map a course onto it and a
learner could not tell where they were. It also covered roughly a third of the
material.

    GEN1  General Chemistry I     11 units    91 nodes
    GEN2  General Chemistry II     9 units    75 nodes
    ORG1  Organic Chemistry I     10 units    70 nodes
    ORG2  Organic Chemistry II    10 units    76 nodes

Unit order follows the standard chapter sequence, and every unit records the
textbook chapters it covers, which is what makes syllabus alignment possible
during an adoption conversation.

Source of truth. curriculum.json is loaded at import time and is the runtime
data. It is generated by the scripts in curriculum_source/, which build the
prerequisite edges rather than listing them by hand: nodes chain within a
unit, each unit declares the nodes it builds on, and genuinely non-linear
links are declared separately. Hand listing 388 edges across 312 nodes would
not survive a single revision. A test regenerates and compares, so the two
cannot drift apart silently.

Authoring metadata. lab_adjacent and triangle_eligible are instructions to
content authors and are never learner-facing labels. A learner sees a flask
icon with a tooltip, and Johnstone triangle eligibility shows up as a view
toggle inside the lesson, which is where it is useful.

Node codes are the stable key for lessons, items and links. They are never
displayed to a learner, who sees generated positional numbering instead
("3.4" is the fourth node of the third unit).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_DATA = Path(__file__).with_name("curriculum.json")


@dataclass(frozen=True)
class Node:
    """One knowledge node."""

    code: str
    title: str
    description: str
    kind: str
    course: str
    unit: str
    number: str
    unit_index: int
    node_index: int
    lab_adjacent: bool = False
    triangle_eligible: bool = False


@dataclass(frozen=True)
class Unit:
    id: str
    title: str
    chapters: str
    course: str
    index: int
    node_codes: tuple[str, ...]


@dataclass(frozen=True)
class Course:
    id: str
    title: str
    semester: str
    unit_ids: tuple[str, ...]


def _load() -> tuple[
    tuple[Course, ...], tuple[Unit, ...], tuple[Node, ...], tuple[tuple[str, str], ...]
]:
    raw = json.loads(_DATA.read_text())
    courses: list[Course] = []
    units: list[Unit] = []
    nodes: list[Node] = []
    edges: list[tuple[str, str]] = []
    seen_edges: set[tuple[str, str]] = set()

    for course in raw["courses"]:
        unit_ids: list[str] = []
        for u_index, unit in enumerate(course["units"], start=1):
            node_codes: list[str] = []
            for n_index, node in enumerate(unit["nodes"], start=1):
                nodes.append(
                    Node(
                        code=node["id"],
                        title=node["title"],
                        description=node["description"],
                        kind=node["kind"],
                        course=course["id"],
                        unit=unit["id"],
                        number=f"{u_index}.{n_index}",
                        unit_index=u_index,
                        node_index=n_index,
                        lab_adjacent=bool(node.get("lab_adjacent")),
                        triangle_eligible=bool(node.get("triangle_eligible")),
                    )
                )
                node_codes.append(node["id"])
            units.append(
                Unit(
                    id=unit["id"],
                    title=unit["title"],
                    chapters=unit["chapters"],
                    course=course["id"],
                    index=u_index,
                    node_codes=tuple(node_codes),
                )
            )
            unit_ids.append(unit["id"])
        courses.append(
            Course(
                id=course["id"],
                title=course["title"],
                semester=course.get("semester", ""),
                unit_ids=tuple(unit_ids),
            )
        )
        # The generator can emit the same edge twice when a unit prerequisite
        # restates a link that is already explicit. Deduplicate on load rather
        # than in the source, so the source stays readable.
        for a, b in course["edges"]:
            if (a, b) not in seen_edges:
                seen_edges.add((a, b))
                edges.append((a, b))

    return tuple(courses), tuple(units), tuple(nodes), tuple(edges)


COURSES, UNITS, NODES, EDGES = _load()

NODES_BY_CODE = {n.code: n for n in NODES}
UNITS_BY_ID = {u.id: u for u in UNITS}
COURSES_BY_ID = {c.id: c for c in COURSES}


def course_counts() -> dict[str, int]:
    """Node count per course. Replaces the tier counts of the old map."""
    counts: dict[str, int] = {}
    for n in NODES:
        counts[n.course] = counts.get(n.course, 0) + 1
    return counts


def nodes_in_unit(unit_id: str) -> list[Node]:
    unit = UNITS_BY_ID.get(unit_id)
    if unit is None:
        return []
    return [NODES_BY_CODE[c] for c in unit.node_codes]


def units_in_course(course_id: str) -> list[Unit]:
    course = COURSES_BY_ID.get(course_id)
    if course is None:
        return []
    return [UNITS_BY_ID[u] for u in course.unit_ids]


@lru_cache(maxsize=1)
def _prereq_index() -> dict[str, tuple[str, ...]]:
    """Prerequisites by node.

    Built once rather than scanned per call. The old map had 60 nodes and a
    linear scan was free; at 312 nodes and 388 edges the path planner and the
    Learn page both ask for this per node, and the scan showed up.
    """
    index: dict[str, list[str]] = {n.code: [] for n in NODES}
    for a, b in EDGES:
        if b in index:
            index[b].append(a)
    return {k: tuple(v) for k, v in index.items()}


def prerequisites_of(code: str) -> list[str]:
    return list(_prereq_index().get(code, ()))


def topological_order() -> list[str] | None:
    """Kahn's algorithm. None when the graph contains a cycle."""
    indegree = {n.code: 0 for n in NODES}
    adjacency: dict[str, list[str]] = {n.code: [] for n in NODES}
    for a, b in EDGES:
        if a not in indegree or b not in indegree:
            return None
        adjacency[a].append(b)
        indegree[b] += 1

    ready = [c for c, d in indegree.items() if d == 0]
    order: list[str] = []
    while ready:
        current = ready.pop()
        order.append(current)
        for nxt in adjacency[current]:
            indegree[nxt] -= 1
            if indegree[nxt] == 0:
                ready.append(nxt)
    return order if len(order) == len(NODES) else None
