"""phase 1 curriculum content assessment attempts adaptive

Revision ID: 0e71108be406
Revises: 0001_initial
Create Date: 2026-07-05 20:37:16.176482
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0e71108be406"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_banks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("grade_band", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "reasoning_traces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=24), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reasoning_traces_subject_id"), "reasoning_traces", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_reasoning_traces_subject_type"), "reasoning_traces", ["subject_type"], unique=False
    )
    op.create_table(
        "standards_frameworks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "item_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bank_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("stem", sa.Text(), nullable=False),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("answer_expr", sa.String(length=500), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("tolerance", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["bank_id"], ["item_banks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_templates_bank_id"), "item_templates", ["bank_id"], unique=False)
    op.create_index(op.f("ix_item_templates_node_id"), "item_templates", ["node_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bank_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct", sa.String(length=500), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("tolerance", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["bank_id"], ["item_banks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_bank_id"), "items", ["bank_id"], unique=False)
    op.create_index(op.f("ix_items_node_id"), "items", ["node_id"], unique=False)
    op.create_table(
        "knowledge_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_node_id", sa.Uuid(), nullable=False),
        sa.Column("to_node_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(["from_node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_node_id", "to_node_id", "kind", name="uq_edge"),
    )
    op.create_index(
        op.f("ix_knowledge_edges_from_node_id"), "knowledge_edges", ["from_node_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_edges_to_node_id"), "knowledge_edges", ["to_node_id"], unique=False
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_node_id"), "lessons", ["node_id"], unique=False)
    op.create_table(
        "standards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("framework_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(["framework_id"], ["standards_frameworks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("framework_id", "code", name="uq_standard_code"),
    )
    op.create_index(op.f("ix_standards_framework_id"), "standards", ["framework_id"], unique=False)
    op.create_table(
        "content_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_steps_lesson_id"), "content_steps", ["lesson_id"], unique=False
    )
    op.create_table(
        "irt_parameters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("a", sa.Float(), nullable=False),
        sa.Column("b", sa.Float(), nullable=False),
        sa.Column("c", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["item_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("answer", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["template_id"], ["item_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_variants_template_id"), "item_variants", ["template_id"], unique=False
    )
    op.create_table(
        "objectives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("standard_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["standard_id"], ["standards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id", "standard_id", name="uq_objective"),
    )
    op.create_index(op.f("ix_objectives_node_id"), "objectives", ["node_id"], unique=False)
    op.create_index(op.f("ix_objectives_standard_id"), "objectives", ["standard_id"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assessments_created_by"), "assessments", ["created_by"], unique=False)
    op.create_table(
        "learning_path_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("current_node_id", sa.Uuid(), nullable=True),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["current_node_id"], ["knowledge_nodes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_path_user"),
    )
    op.create_index(
        op.f("ix_learning_path_states_user_id"), "learning_path_states", ["user_id"], unique=False
    )
    op.create_table(
        "mastery_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("p_known", sa.Float(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "node_id", name="uq_mastery_user_node"),
    )
    op.create_index(op.f("ix_mastery_states_node_id"), "mastery_states", ["node_id"], unique=False)
    op.create_index(op.f("ix_mastery_states_user_id"), "mastery_states", ["user_id"], unique=False)
    op.create_table(
        "review_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("ease", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "node_id", name="uq_review_user_node"),
    )
    op.create_index(
        op.f("ix_review_schedules_node_id"), "review_schedules", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_schedules_user_id"), "review_schedules", ["user_id"], unique=False
    )
    op.create_table(
        "assessment_forms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_forms_assessment_id"),
        "assessment_forms",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "assignment_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignment_targets_assessment_id"),
        "assignment_targets",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_targets_user_id"), "assignment_targets", ["user_id"], unique=False
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("answered_count", sa.Integer(), nullable=False),
        sa.Column("score_scaled", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attempts_assessment_id"), "attempts", ["assessment_id"], unique=False)
    op.create_index(op.f("ix_attempts_user_id"), "attempts", ["user_id"], unique=False)
    op.create_table(
        "assessment_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["assessment_forms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["item_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_items_form_id"), "assessment_items", ["form_id"], unique=False
    )
    op.create_table(
        "responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("answer", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["item_templates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["item_variants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_responses_attempt_id"), "responses", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_responses_node_id"), "responses", ["node_id"], unique=False)
    op.create_index(op.f("ix_responses_template_id"), "responses", ["template_id"], unique=False)
    op.create_index(op.f("ix_responses_user_id"), "responses", ["user_id"], unique=False)
    op.create_table(
        "grading_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("response_id", sa.Uuid(), nullable=False),
        sa.Column("grader", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["response_id"], ["responses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grading_records_response_id"), "grading_records", ["response_id"], unique=False
    )
    op.create_table(
        "mastery_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("response_id", sa.Uuid(), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("p_known_before", sa.Float(), nullable=False),
        sa.Column("p_known_after", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["knowledge_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["response_id"], ["responses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mastery_events_node_id"), "mastery_events", ["node_id"], unique=False)
    op.create_index(op.f("ix_mastery_events_user_id"), "mastery_events", ["user_id"], unique=False)
    op.create_table(
        "scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("response_id", sa.Uuid(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["response_id"], ["responses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scores_response_id"), "scores", ["response_id"], unique=True)
    op.create_table(
        "step_credits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("response_id", sa.Uuid(), nullable=False),
        sa.Column("milestone", sa.String(length=200), nullable=False),
        sa.Column("awarded", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["response_id"], ["responses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_step_credits_response_id"), "step_credits", ["response_id"], unique=False
    )
    # Note: this migration only creates the Phase 1 tables. Alembic autogenerate
    # also proposed alter_column and unique-constraint edits on the identity
    # tables (created in 0001); those were spurious noise and have been removed
    # so the migration is idempotent and runs clean on Postgres and SQLite.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_step_credits_response_id"), table_name="step_credits")
    op.drop_table("step_credits")
    op.drop_index(op.f("ix_scores_response_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_mastery_events_user_id"), table_name="mastery_events")
    op.drop_index(op.f("ix_mastery_events_node_id"), table_name="mastery_events")
    op.drop_table("mastery_events")
    op.drop_index(op.f("ix_grading_records_response_id"), table_name="grading_records")
    op.drop_table("grading_records")
    op.drop_index(op.f("ix_responses_user_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_template_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_node_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_attempt_id"), table_name="responses")
    op.drop_table("responses")
    op.drop_index(op.f("ix_assessment_items_form_id"), table_name="assessment_items")
    op.drop_table("assessment_items")
    op.drop_index(op.f("ix_attempts_user_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_assessment_id"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_index(op.f("ix_assignment_targets_user_id"), table_name="assignment_targets")
    op.drop_index(op.f("ix_assignment_targets_assessment_id"), table_name="assignment_targets")
    op.drop_table("assignment_targets")
    op.drop_index(op.f("ix_assessment_forms_assessment_id"), table_name="assessment_forms")
    op.drop_table("assessment_forms")
    op.drop_index(op.f("ix_review_schedules_user_id"), table_name="review_schedules")
    op.drop_index(op.f("ix_review_schedules_node_id"), table_name="review_schedules")
    op.drop_table("review_schedules")
    op.drop_index(op.f("ix_mastery_states_user_id"), table_name="mastery_states")
    op.drop_index(op.f("ix_mastery_states_node_id"), table_name="mastery_states")
    op.drop_table("mastery_states")
    op.drop_index(op.f("ix_learning_path_states_user_id"), table_name="learning_path_states")
    op.drop_table("learning_path_states")
    op.drop_index(op.f("ix_assessments_created_by"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_objectives_standard_id"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_node_id"), table_name="objectives")
    op.drop_table("objectives")
    op.drop_index(op.f("ix_item_variants_template_id"), table_name="item_variants")
    op.drop_table("item_variants")
    op.drop_table("irt_parameters")
    op.drop_index(op.f("ix_content_steps_lesson_id"), table_name="content_steps")
    op.drop_table("content_steps")
    op.drop_index(op.f("ix_standards_framework_id"), table_name="standards")
    op.drop_table("standards")
    op.drop_index(op.f("ix_lessons_node_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_knowledge_edges_to_node_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_from_node_id"), table_name="knowledge_edges")
    op.drop_table("knowledge_edges")
    op.drop_index(op.f("ix_items_node_id"), table_name="items")
    op.drop_index(op.f("ix_items_bank_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_item_templates_node_id"), table_name="item_templates")
    op.drop_index(op.f("ix_item_templates_bank_id"), table_name="item_templates")
    op.drop_table("item_templates")
    op.drop_table("standards_frameworks")
    op.drop_index(op.f("ix_reasoning_traces_subject_type"), table_name="reasoning_traces")
    op.drop_index(op.f("ix_reasoning_traces_subject_id"), table_name="reasoning_traces")
    op.drop_table("reasoning_traces")
    op.drop_table("knowledge_nodes")
    op.drop_table("item_banks")
    # ### end Alembic commands ###
